### ISSUE TITLE
No monsters or animals spawning Alpha_1.3.11dev 

### ISSUE THREAD

**Issue by Dougle-1** [PocketMine/PocketMine-MP#1006]
No matter what i do i cannot seem to get monsters or animals to spawn everything else works fine.  i have tried with and without plugins and still no monsters or animals.. 

I have tried with monsters and animals as =true and on.
I have tried changing difficulty to 3 and changing to creative and back to survival
I have looked in all the dark places but nothing spawned.

Please help below is my Server porperties
server-name=survival 3 
description=Survival03
motd=Welcome @player PEserver!
server-ip=
server-port=19135
server-type=normal
memory-limit=512M
last-update=1387152545
white-list=off
spawn-protection=16
view-distance=10
max-players=20
allow-flight=on
spawn-animals=on
spawn-mobs=on
spawn-monsters=on
gamemode=0
hardcore=off
pvp=
difficulty=3
generator-settings=
level-name=Survival03
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=1234
send-usage=on
auto-save=on
announce-player-achievements=on

**Comment by john-hughes** [comment]
I had the same issue. With no mobs or animals is there any point to using pocketmine in survival mode? I'm new to Minecraft.

**Comment by VaporFan** [comment]
Any update on this ?
