### ISSUE TITLE
friends can't connect to my server whats the problem please help me mcpe 0.8.1

### ISSUE THREAD

**Issue by AliNeedsHelp** [PocketMine/PocketMine-MP#1043]
I have mcpe 0.8.1 and the server from pocket mine with the development file wich allows mcpe 0.8.1 so i did the server 
On my phone it pop up like a wifi world so i think that is correct but my friend cant join it as a external server did anyone know the solution pleas help me 
Thanks

**Comment by iamstewpeed** [comment]
.
