### ISSUE TITLE
cant open chest help alpha 1.2dev

### ISSUE THREAD

**Issue by elvis989** [PocketMine/PocketMine-MP#114]
i cant open chest on alpha 1.2dev the chest will act like a block and ill not open 
and when i downgrade to alpha 1.1 ill give me 
[DEBUG] Unhandler Data Packet 
then a code name 0xaf  

and items wont save on chest ill come out please help me
when i open chest i have wood my hand and then i hit chest to open instead ill place the wood i had my hand  here my 

server.properties
# Properties Config file
# Mon Feb 18 20:07:39 UTC 2013

server-name=Minecraft Server
description=Server made using PocketMine-MP
motd=Welcome @username to this server!
invisible=on
server-ip=192.168.1.3
port=19133
memory-limit=256M
last-update=1361215901
white-list=on
debug=2
max-players=20
server-type=normal
time-per-second=20
gamemode=0
difficulty=1
generator=
generator-settings=
level-name=world
server-id=6747758481299293056
upnp-forwarding=on
send-usage=on

**Comment by daniktheboss** [comment]
Wait... how did u get it running?

**Comment by daniktheboss** [comment]
Nvm sorry
