### ISSUE TITLE
pocketmine 1.4 cant place blocks

### ISSUE THREAD

**Issue by Mr3Superfake** [PocketMine/PocketMine-MP#1499]
i cant place most of the blocks like mobs minecrat on a rail because if i place the minacart down its changing to cobblestone and my second prob is chunks are not always loading and if i go into a area where chunks are not loaded mcpe freezes in and i need to rejoin server... any sugestions?

(srry for my bad english hope u still understund what i mean...)

**Comment by cloud9350** [comment]
@Mr3Superfake http://github.com/PocketMine/PocketMine-MP/issues/1534
