### ISSUE TITLE
php compilation with pthreads fails

### ISSUE THREAD

**Issue by corrinewinslow** [PocketMine/PocketMine-MP#160]
The pthreads version was updated from krakjoe/pthreads@0d5df071231478ff3b1982eb2b0d96cc24e39d9a to krakjoe/pthreads@722f546aa6ec406b35c3e5c6f3fcb243866bb053 a few days ago and the prior version is no longer available. This causes the pthread wget in compile_php.sh to fail with no entries captured in the install.log.

Currently confirming an update to the PTHREADS_VERSION variable corrects the issue ...

**Comment by andreimo** [comment]
hikh
