### ISSUE TITLE
Failed to login:Invalid Session(Try restaring The Game)

### ISSUE THREAD

**Issue by rensxzkiie** [PocketMine/PocketMine-MP#1648]
![image](https://cloud.githubusercontent.com/assets/8143260/3563626/c7cd52f6-0a45-11e4-8902-5accb115dca2.png)

![image](https://cloud.githubusercontent.com/assets/8143260/3563627/d3262b3c-0a45-11e4-9e79-f4ba2aeb0b1f.png)

plss help me!

**Comment by edgararroyo** [comment]
2017-10-12 [08:13:30] [Server thread/INFO]: Steve[/172.58.169.16:35057] logged out due to Invalid session

This is not the same as #8, any ideas?
