### ISSUE TITLE
No recognition of biome colors on Anvil worlds.

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#1792]
Grass color on Anvil maps are not recognized/transmitted by PocketMine 1.4dev (last build) to 0.9.5 client.

**Comment by roroB20** [comment]
Now that the1.4 update is released, are you trying to find a way to use informations from anvil format to send an equivalent to MCPE client ?

**Comment by shoghicp** [comment]
@roroB20 It'll be done later after all biomes are implemented. Since MCPE only accepts colors, it needs calculations, and it'll look bad in the end too.

**Comment by alejandroliu** [comment]
So is this now available with v1.5.

**Comment by matcracker** [comment]
#2845

**Comment by roroB20** [comment]
There is a strange thing happen since v1.5 is that grass is black on Anvil and other MCRegion worlds !

**Comment by matcracker** [comment]
Yeah... I hope to be resolved as soon as possible! It is ugly to see the grass like that!

**Comment by vvzar** [comment]
already corrupted worlds still have black grass areas (borders - are chunks,  or other smallest parts of map)
How can I fix them?
