### ISSUE TITLE
Bugs with imported PC(Anvil) worlds

### ISSUE THREAD

**Issue by MobileCrafter** [PocketMine/PocketMine-MP#2361]
Found some bugs with imported pc worlds, but these bugs dont happen on pocketmine created worlds.

1. Spawnpoint is not saving with and without /save-all.
You spawn on every reconnect on the worldspawn.
!Update: Level and worldfolder name has to match and it works

2. Slabs and Stairs from the imported world have the lowest lightlevel when blocks are over them.
When you replace them the light level updates.
But when you reconnect the light level is going again to the lowest.

Tested on different imported worlds with PC version 1.7.5.
Deleted chunks with MCEdit-Unified around the worlds. 

Worldspawn saving is working correctly.

**Comment by Alcatraz-Du** [comment]
You need to change world's name in level.dat

**Comment by MobileCrafter** [comment]
Oh Thank you guys! :+1:

**Comment by Creeperface01** [comment]
how can I covert world from anvil to MCregion format?

**Comment by ztdroider25** [comment]
@Creeperface01 here are files @MobileCrafter gave me: http://www.mediafire.com/download/13g2zdwq6ram09u/Converter.zip

**Comment by matcracker** [comment]
I have got this problem with a map imported by PC (1.7.10)
I convert .mca to .mcr and with a normal map i've got this:
http://imgur.com/Im1TOl2
How i van resolve the normal chunk load?

**Comment by Creeperface01** [comment]
Yes I known about it but chunks still doesn't load sometimes

**Comment by matcracker** [comment]
News? @shoghicp

**Comment by alejandroliu** [comment]
Is this issue still open?  The latest update should have fixed some of these.
