### ISSUE TITLE
deopping player still keeps those permissions

### ISSUE THREAD

**Issue by advocaite** [PocketMine/PocketMine-MP#2372]
when you op a player so that they can use permisions defaulted to ops only after deoping player they can still do those things as if they were still op.

For instance  plugin requires op to run setspawn after deop player can still use command.

problem fixes it self soon as player logsout or idles too long and is booted. im assuming it updates permissions then.

**Comment by advocaite** [comment]
100% your bug ignoring facts

**Comment by PEMapModder** [comment]
What plugins do you have in your server?
