### ISSUE TITLE
Crash after new install

### ISSUE THREAD

**Issue by erikvcl** [PocketMine/PocketMine-MP#2382]
I followed the instructions "wget -q -O - http://get.pocketmine.net/ | bash -s - -v development" to download and install the development build. I get a crash. I tried the beta build as well and get the same error.

http://crash.pocketmine.net/view/287781

**Comment by SeangJemmy** [comment]
Dear Erik,

    Mine have the same problem when upgrading from the old version to the new one. I think you need to reset the server to try the new version. It worked for me!

Regards,
     Jemmy

**Comment by WhiteWolfOwner** [comment]
I have had this same problem once, its just a plugin you installed that is working against another plugin. It works so hard that it keeps crashing and rebooting... I just backed up my server and it fixed it. I didnt really look to much into the problem I was just happy to get the server working again.

Thanks,
WhiteWolfOwner

**Comment by LDX-MCPE** [comment]
@WhiteWolfOwner, this is **not** being caused by a plugin. If you don't know what you're talking about, don't talk about it.

**Comment by WhiteWolfOwner** [comment]
Okay well then I would like to know what it is because i had this problem... And in the crash dump it said it was the plugin i had just installed...

**Comment by WhiteWolfOwner** [comment]
@LDX-MCPE

**Comment by PEMapModder** [comment]
@WhiteWolfOwner for the last time, this is not a support channel or a forum. If you continue to use this issue tracker like a forum or ask for individual help here, you may be blocked from PocketMine GitHub.

**Comment by WhiteWolfOwner** [comment]
How can i block some on from seeing their messages on GibHub?
