### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by ghost** [PocketMine/PocketMine-MP#2430]
Im getting this Error when someone dies (fall) on my Server without Plugins and a PC World.

17:24:22 [CRITICAL] Could not tick level world: Trying to get property of non
-object
17:24:22 [NOTICE] InvalidStateException: "Trying to get property of non-object"

**Comment by XxDXM-hippiexX** [comment]
i see this is from a few years back..but i have the same issue im running pm 1.4.1 dev 965 and if someone falls in the void i get this error and they get stuck in the void. Im pretty sure its a corrupted chunks issue but not positive, any way i used the plugin alwaysspawn for kinda a walk around but they have to quit and rejoin to spawn again and even then it takes a second sometimes. Really with i could fix it without that plugin bc its annoying to be at spawn every time you join..any suggestions on how to fix corrupted chunks?
