### ISSUE TITLE
Player Location Glitching

### ISSUE THREAD

**Issue by GreatWisher** [PocketMine/PocketMine-MP#2465]
People for some reason like to mine strait down, (stupid idea) and usually when they mine a block, the block reappears several times and they suffocate. Another glitch, when players walk forward casually, all the sudden they are teleported back. They can't move at all. Their screen vibrates as they walk forward. We decided that jumping while walking works, but it is very annoying. The walking glitch happens when you walk every few seconds. It's very common. These glitches are extremely annoying, and I would like you to fix them.

**Comment by iJoshuaHD** [comment]
walking glitch can be fixed by using PocketMine-MP_Soft. download it and replace the old phar with the soft phar. run the server, let it generate pocketmine-soft.yml and edit it find check-movement, set true to false.

**Comment by shoghicp** [comment]
This might have been fixed by the latest commit.

**Comment by GreatWisher** [comment]
Thank you! I will try that and see if it works!
