### ISSUE TITLE
many times pc map chunks are not load

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2467]
![be2](https://cloud.githubusercontent.com/assets/8337568/5575360/c438796a-901c-11e4-8d3c-719824ee34de.jpg)
[Chunk load screen]

![be1](https://cloud.githubusercontent.com/assets/8337568/5575359/c4387096-901c-11e4-997d-d5cf281ed348.jpg)
[Chunk load fail screen]

[PM 1.4 version Dev 910]
[PC Map: McRegion]

many times PC map Chunks are not load
(looks like a Chunks loads are stopped..)

I try to modify pocketmine.yml chunk option,
but my tries are failed to solve (´･ω･`)

**Comment by Creeperface01** [comment]
what version of MC(PC) are the maps?

**Comment by shoghicp** [comment]
This seems like a network and device issue, as other features load. Sometimes removing the chunk cache and closing Minecraft: PE properly fixes this issue.
