### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by FunnyCrafteur** [PocketMine/PocketMine-MP#2477]
Hello,  

I host many server
All servers crash with the error : http://crash.pocketmine.net/view/157544

I have update they servers to pocketmine 913 !

I have open a new issue because you have close the other :(

Thank you and Good new years

**Comment by shoghicp** [comment]
This is already fixed, disabling the updater is not recommended as you won't receive the notification of new updates in case of an important update (security, etc.) as it happened a few times in the past.
