### ISSUE TITLE
Motion Lag

### ISSUE THREAD

**Issue by sithsiri** [PocketMine/PocketMine-MP#2478]
Sometimes, the server seems to think you're in one place, when you are actually in another. This usually occurs when squeezing through tight spaces or flying under things. It makes it so that I can't break or place, and gets annoying reeeaally fast. Dev 912 helps a bit but we always have problems after a while. It can be temporarily fixed by /tp @player @player but it only helps for getting through that space. Not a big issue, but please fix. I love PocketMine and download every single new release from Jenkins.PocketMine.net as often as i can. Sorry if this issue has been already seen or is just lag, but it happens over any connection. ;)

**Comment by sithsiri** [comment]
I just updated to dev 913 and replicated bug like this:
Build a structure at least 3 blocks high, 5 wide, and 5 long, but preferably more. Break 2 blocks near the corner and place a door. Inside, make a hallway at least 2 blocks long with the door, 2 high, and 1 wide. It is hard to enter and exit without /tp player player.

**Comment by iJoshuaHD** [comment]
@shoghicp this is the bug i meant what i said on irc D: no need to duplicate issue :)

**Comment by shoghicp** [comment]
This might have been fixed by the latest commit.
