### ISSUE TITLE
Bugs.

### ISSUE THREAD

**Issue by mmlmml1** [PocketMine/PocketMine-MP#2480]
(I'm a Chinese, so my English is not very good....)
There are a lot of bugs in V 900(0.10.4), my players suffer a lot from them,even in V 913
1. If I use the  crafttable or furnace or change gamemode for someone ,the cilent will crash and I will lose my things which was put in the crafttable
2. If I sleep in a cave （there‘s enough space obove the bed,about 1-2 blocks) ,I will  get stuck and die.

**Comment by PEMapModder** [comment]
1. is reported already.
