### ISSUE TITLE
Console spamming "PLAYER moved wrongly!"

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#2481]
The console is spamming the message "PLAYER moved wrongly!" over and over when players are just normally walking around the server.

**Comment by ns827** [comment]
Did you check clients' network speed?

**Comment by MobileCrafter** [comment]
This must be your internet.

**Comment by HmHmmHm** [comment]
@ns827 No it's not problem internet speed(Player.php 1110 line -> $diff problem), i think it's about binding box (other say damage block..?) problem, I don't know why PM is revert..

**Comment by HmHmmHm** [comment]
@ns827 No it's not problem internet speed(Player.php 1110 line -> $diff problem), i think it's about binding box (other say damage block..?) problem, I don't know why PM is revert..

**Comment by shoghicp** [comment]
This is not an issue, that message will show when players go inside blocks when going around. As MCPE sends invalid positions, this happens. Testing with PC clients doesn't cause this issue.
