### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by MegaSamNinja** [PocketMine/PocketMine-MP#2483]
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 130968 bytes) in 
PocketMine-MP.phar/src/pocketmine/block/Sandstone.php on line 500

**Comment by PonyPC** [comment]
same issue as you, guy

**Comment by misha1** [comment]
,

**Comment by shoghicp** [comment]
Please do not open duplicated issues.

**Comment by shoghicp** [comment]
It also seems like you are running a weird version with strange content, as the Sandstone file doesn't have that amount of lines :)
