### ISSUE TITLE
Still Out Of Memory on Linux X64

### ISSUE THREAD

**Issue by PonyPC** [PocketMine/PocketMine-MP#2484]
Still Out Of Memory on Linux X64

I've set memory to 1024Mb, but after several time, memory goes to 5620Mb
0.0

**Comment by PonyPC** [comment]
dev#916, doesn't crash now, but exceed 5 times of setting memory size

**Comment by shoghicp** [comment]
Is this the memory showing up on the process list or in the console?
If it's the process list, this is not a PM issue but a PHP one, since multiple threads can use different amounts of memory.

**Comment by PonyPC** [comment]
shows at 'ps' command, doesn't contains cache size.
0.8.1 has no effect.

**Comment by shoghicp** [comment]
Yes, this is a threading issue. Try to run the server without plugins, they might have done something wrong in their threading usage.

**Comment by PonyPC** [comment]
PocketMine-MP Crash Dump Fri Jan 2 20:11:15 CST 2015

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 82185 bytes)
File: /src/pocketmine/level/format/mcregion/McRegion
Line: 133
Type: E_ERROR

Code:
[124] 
[125] 		$biomeColors = \pack("N*", ...$chunk->getBiomeColorArray());
[126] 
[127] 		$ordered = \zlib_encode(
[128] 			\pack("V", $x) . \pack("V", $z) .
[129] 			$chunk->getBlockIdArray() .
[130] 			$chunk->getBlockDataArray() .
[131] 			$chunk->getBlockSkyLightArray() .
[132] 			$chunk->getBlockLightArray() .
[133] 			$chunk->getBiomeIdArray() .
[134] 			$biomeColors .
[135] 			$tiles
[136] 			, ZLIB_ENCODING_DEFLATE, Level::$COMPRESSION_LEVEL);
[137] 
[138] 		$this->getLevel()->chunkRequestCallback($x, $z, $ordered);
[139] 
[140] 		return \null;
[141] 	}
[142] 
[143] 	public function unloadChunks(){

Backtrace:

PocketMine-MP version: 1.4 #916 [Protocol 20; API 1.10.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ls2.nide8.com 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
CustomAlerts 1.1 by EvolSoft for API(s) 1.9.0
TouchIt 1.1 Alpha by Marcus, Marcus for API(s) 1.4.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
EconomyJob 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1
Protection 1.5.1 by zzx for API(s) 1.9.0, 1.10.0
SimpleWarp 1.3 by Falk for API(s) 1.0.0
TapToDo 2.0.0 by Falk for API(s) 1.0.0
DisguiseMe 1 by Falk for API(s) 1.0.0
KeepInventory 1.1.0 by boybook for API(s) 1.0.0
SimpleSnow 0.1.2 by MUedsa & boybook for API(s) 1.4.0
Broadcaster 1.01 by EvolSoft for API(s) 1.2.0
CustomChat 1.1.0 by Array for API(s) 1.8.0
iProtector 2.0 by LDX for API(s) 1.6.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
SignStatus 1.1.2 by xpyctum for API(s) 1.0.0
PocketGuard 2.1 by MinecrafterJPN for API(s) 1.6.0
WorldBorder 1.0.0 by Topic for API(s) 1.0.0
ItemCase DeBe by DeBe for API(s) 1.6.0
CommandRepeater 1.0.1 by iksaku for API(s) 1.8.0
ALLSurvival 1.2.1 by PMPCT-Zzm for API(s) 1.0.0
WorldMonitor 2.0.0.000.0 by Steven for API(s) 1.2.0
automaticDoor 1.0-alpha by hm for API(s) 1.4.1
WorldEditArt 1.0.0_beta_dev_#044 by PEMapModder for API(s) 1.0.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PVP_Manager DeBe by DeBe for API(s) 1.6.0
SignCommand Build_1 by 18WYJ2 for API(s) 1.8.0
MSpawns 1 by EvolSoft for API(s) 1.2.0
xPermissions 1.3.1 by 64FF00 for API(s) 1.2.0
BanItemAdd 1.2 by zzx for API(s) 1.8.0
SWorld 1.1.0 by 18WYJ2 & boybook for API(s) 1.0.0
EconomyAPI 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
DevTools 1.8.0 by PocketMine Team, shoghicp for API(s) 1.0.0
EconomyShop 2.0.0 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.1 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyTax 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.0 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNO4ty27aWv4KRMzvJHVEP6mFJHXfGkZ2uu3aitZRmt2XHA5GQyGuSYAnQltzpv+85AB+g5DSy
ozt30+mYPADO+wUQ+rMhg4g1Jt2+3bE7neHpoNlgacrTxuTPhtwmMNS4vLu8vf1022g2IiYEXSPs
PAz5I/NIxCKebokInhjhK9LtnPZO+92R3SfLrWSCsI1PMyFh5luZBvBHckJhrUslIyO7Oxroie8A
+yoIEXVbpG474e49k1EQs3bIHljYXvE0orIduSlbBzxu37i36gHWhTALJOj1/mo2kjBbB3FjsqKh
YM2Gyz2GknTtPmCGuV17AA+OdOSbZcAjNuUhTwU5I46TUPf+rdP4+A+n0SStVuuN62fxvfXjmsn3
5dTzNKXbt+/e/aBwDQukpwVSnnosBTER4VMYLO9YjDy8VbNG+Sz4r6D2CxJ7s3lHWmQH9gQwtWpc
rjI5AhXeX3k5O3pmr/PVmRdU0vrc7lfnzu+318Hal/X59lfnPzO59+xkVOIuy/1qpmkPPTioBiX4
hlDAYQlskl+vr97fXX6cfrq4+vjT3cXlh+vzxWWTXKPHTCZvpp9uZreX8/nVp49315e/XF5rs/VO
c7P1CoO8kX4gFJNq6dt31o+K71v2R8aEnILHLtE2bzZoGPg/N3OOb5zj6xcGSJnM0hgsGmdhqOb0
tb7/Us92MV/rKcmWYeCSVRa7EjyaZHHIqTdFBsTbd382wK1lSl1w5N9+bzbWLGYpDdGrH1gqMAQm
jW6rDwiXWRB6jcm4O4RASLnkLod5dqfZoEmgZnU7rQ5MXAcSXjsH/oMFKb0HZ8Y1rVOFIYsppo3G
dRBnGxIKuxUHHhu1XB4RuzVs9Wyr3+u2WDhsbUbDu2GfnHTJ/GZGPqQB+cgfiG2TTm/SHUw6Y/J5
MSV2p9sjeiqgT/wEkA8AkQ1vTywGsRqIt6MH77goiANAvYTqpUwBAhU0hdTDo/OQpVK950zXwM2a
GrvwTjPpgxOCuhuXDzyc85Vs/J7r8DeYMwYu4J3FdBkyYEymGaQajyXAptBGErDmwgREFLNSjbLj
3CAQ8hdYG8bmi/PbxecZAB7ZUgQSOfWlTMSk3X58fGwx4AXxtuQ9irngmetfSUOsArIjETkPE5/W
5bqhqZuh7PmDKV4flPBK8XIOHKdiJRdu9mm++PLp9vriWfHAH/1sic7TnmcJSzVX7QILShtgbogi
GkPgmTLX4Ibkdk3e64v/qcmowwCUk/+187+9/G//9SYGUiC/ydauoZ/VBWYKkPPS5TGPtj/zpSGk
ATRta+diGHLymC3h/4NktV9v55yM4zDN2T/50nFqXB4g6gwyFFMZzxDVANbdeLAbmk9Pm72obBYp
7pVyJSV1x6lxcoA48yBKQvaFpokhjgE0xAE/q4nygYb3eyZ7pQhCUXwEio5To36ACAuaLPgFN8Mr
h3zD7Y4pgKSJ5B6HGCppH8D6RSDWWSDYDTO4N4Cm9v9lrHs5vQgio0b7AAH+i7HkKn5gsYR+2pCh
Dt9J7bt2WPLtkvOjyVOj/ZIsph1vHvPHvVhQQFOMDohh71Snz8wTlPwHeU6e70jNFQdFbOTcfLNI
5SUYdi2SpduWG2NNep/CMpfC7sasSCa0FvOd7rdbC/v1whl0v7Oz0E3K1Kdyr2dSwL93wt8gh9MN
NtQxf3B9nH5BsUuDyp7Sxu+muKPXi1sn4jgVf47juoe7apDneW7a0ADuZL7G37YVw+9sGyq6L4k2
2JRDiAaw413MDCFq4LrNOq1xTZAj5QuTIvQGdfoHpY11PJdUZqKWNkrgruPtpI1NsnVlFh0r+1WE
MVsYTBzS26jji58ymnpmc2NAzVa1Vc8MN0HM3JSuIJJ/nn08loPVsUJ/U2PmpW16HVvbQNbGFPKF
p6H3Xu2SDflN6K5D7kTWgieBeyxLGnQdp87EAba8kiyaUmE2FiXIlOKCvWd1IRTkSOZDXDO9s3Wc
gn71dJgo+ZbkFvDTetXaHdk1z07zHdwLep81jpTLd4i/JPedX1/Ps/QheNAnIrk0JrQuib0ryexm
Nl1Yvz4dLW0YtB2nzsjXy3EujfLNGx4H9XJUA++14q1OZy985pJB23as1sKk/xLjAEM8ojJwL3hN
njp8x9Usun9c4UfHOqHwI8epkd95PUwwpZBLL5Dnqdy1UwHeS3B3Sybpncce7k46/f6OF17e0OSG
e5iUjuSHCYtoEimUjvOInDHgjKYyT4EVny/N/Qaz7XlEw9D6dWrluaktU8bakWpD2zU6oLbNbRYy
sTE0VkC+UQ02H0KasmOlG43NcXLiL/Ho2S+zuxsa03UteZrQf1NFABZyDsznw9uuPAXv9F0F1BTq
PR4y3+1k0e7oy//+bB/LQAbplxjnZp7Qx9jsHQvIV3f/x96E5QS/cwO2mbE0CgQybEpTA9cjprdb
1ob9Dx86nWOJdafRQcgYLNTfDhPWyCIaZbuGAzfVNMae5twzfdEA7pTzvz8T/A4fzEk6Tv5wYCip
lGdGkQZ849xGh89XDjy+ZwujqMP2peDi8BPo89nV/gk0Anf7j66TDd3+2MkGve5wuXWy8chlAFv2
XXg+HdgwMrbH33dObZ7N9/L3fnlWf7RzbOClPMfWsh5y9MgeFhzi1zx4LEB1u4927a63TbiXIgtG
0ceEz9d+4CbH8oCCE8cxeHpZoFZMtksclZ/MfZ7sO4qC7nWqx/KU13qC6cYv8AqwSVK6RS7Z4YE0
Z2H4jIIQuhdK//9EBzYr0TXPh4u+oJt9yRd08xrB/1XZ4ZWKkXRT6kVLdLharuuNlgk98ue9f4Ni
QtW01WX6pmrwqz1NQR2waygSGktBFa0k5QlLZcDwE//JrHwjUx6vgjXBO0NO6sQneK/gZxoTm3TH
k15/0umR6XyB1woGOI5Xmc46+BRx6Z3hg6ZgJTyVZ91xdzBSo+o+kxUGUQDQjt2/QeijD7wCUEiN
g8Yxz2KXWUlIt4CDun4AG+6IxVKc8Vhhx0bQqj4onnWHCj/d5IvE2UDjwptU1irEWzRnfLWqFtM4
gN1VHWHElwVgTZFZLxdrxVPgp4TliHyaei5Py/fkIclXe8FqFbhZKLdnXYVNXSuBDb4lmJRBvBZK
SerylYWeevbkVgDBmGeMK+1eXH44/3y9QKh2KuuPjKXbgnQOS8EzChA+txIqBGxPvbN/qH+gENiP
W4I+sJzTh4A9Wh7onoLGz/radLFnZXgVrUCF10LKK2OtbRSiuxDswomrPCUD4fByDToMAWWRqqxZ
NzNwILLwmWCkkJ7AFpFInxFwbgEPVBIXzS7JkpEgdsMM9tPwQPYcFXHNeaTuw8l9nIKuWJNwGEkF
oiTLlNF7suVZmuMiwYqAEYNVoCiA/VLwoXDrxCi5RjVxgLKfSY+jU+hreRPiNOYagxtywTynAbNO
1FU9gs4LC0l+O4Y8BJT8N9oHpig7WfnIhGAmwIVQ6h4JRf0JDkrLqZBHn8UA1tNJJkA9kDWARYrX
/CBdwEzIWB4owhiwgK0lMFWhv1QOUeCBTEHQUwkoEmyErC63sH5FwUdheu4+5eiEqCt+MEK9B/QM
z3IhDFkFz5I4scDSjxADtQUnc8xiQJHH24hngoBrSVSPK/B6opviKSRR7kVShvkBRal8rhLhYxYt
Qdtg6HOxjd0FFfcEfPkeTIuMIczK3yekj/bz2DJbo/FOrlbkR9JtkkCSxyAMwZqgbTVcaFqge6EL
5haAVSrcJqRb6U+QttAfKdDT1Z5ZlKJW4Vp5zQn4eaFXom9VavdWU4VmBqyq7ayV4SlTqiWWXjIh
xU3MXBZVPpDTB7zbRFYpj8BJTPyBIBg+0iAP2pb73ECUYsVQAil0Jc1SLH2rEE2CllVeDpaMJZpC
jQm0lyKQZ1sC0UnAxPcwGR4tfFQ2ISdTHoGXqi2oVgKK72n5cxI50hb5T0jTgOgMAhR8dTr73IQl
QpAl6P0x8KSv/UYbo8Bq5WYbPcsoygrkaApwTwUWMozej7rRKaFJIK+1yGAITkVuphMyuySd1rg1
UNqP0UoC2cQvopo1UHlMxkPyFhYALXPNO5V2XIpGhp13xtDowLlytTBAvQXrmKeV3EAFC5d+mQDa
ygaox8IGN3RD6K54ELEufgr0CIP43DfBqINLb6kXZMJYtqsOdBW9FP9YqZo/ITYGBZZOK0s88NTK
90EURjURVbn3vCeveGAfxfwXn2FORkJppuOumoE+SQnWTJYqv/JB4x6BMsL1VOyGcigi+6laqeIJ
aoZyk3UYSNffPrOqSZZZnglCulY2RESfK7MqG62okKSs1QKDChIsxD34qQpTjMW8p2vmweUFOjUb
4uT8R3QLfEH10W2Po9K5pfKWkS7BrK19u4KecoSsjC2oa3G4VeXVQJRny8rkXcMI7kQPBdyzglhN
ABsOOx2co94sGMVJuh2yVB+E6RSngJ5iPGouoZgZsYHA/kGhwUmqMFjoD3GWgPtq5LqhUp2eSowF
LsByiqtygogUw4w84rcpqwQqGI2WGC96St666JIxKQoNpFAq/KKQKN3kIQGWLQubV6pJ1Rm8M16H
lCm8Bk38JIDWrwT6HB1dUWwZ/VDMZMmejhOl0ZJ0YWpIVXp4ogVOYyuvPSUFDeWJ0SdMsYlBR4Mk
xxNsgsGZmaQYHlCbgEQLbZwyCJ4U6zSkphjzIU7KXTZTfk5NJCTfChklMltDVYRGDBCsdVwwkmND
jejhAr/Y0QoetD6jkzCg0MIoc11uKF4K0i9YjwF/zsSk4EYNgXMJycGVfsNHC1r4JkHA74hRfWsp
S63Z/ikhOCBKA4+ZGQYVxeSz3aRqjNQeQVcKFDuCYhkAo3nJNlhXVBUD6olgn46houpcRW1C8Kb8
xP7htDkYb7rN3qbXtH/o/uBBKtEZ4i1+x3Ex5M9GHbIGhxL6rT/An2qwjWRxeT49hWRlXNdGBzJe
IWOuyx9kJC5OzV/EH5AOWU9fK7fA9HjXW98z17vYpQtl369+zUFDcHqaVgD9C5XiLUvD8gW6RPWF
G++X6a3xSibl6Dqqnn0IFv3ZCSb9U9Q+FEdLIbEOlpOh69kmspIANiWeuuRRijufXSuq+Jy4saxY
irYgsLrJnj+RAZ59dFFyYuFW1e4MYN9qkTdXGJS90x6jA88bDHqj02G33xnSUce2aX85or3Tfr87
Wtr9DiNvgNLMR7WoMwNFmItgUyldp3tRnLagoLdsFRa3bxuK3ogNVi60Iqs+kO2sTk/d09FoOBgA
6d7Y7rFeZzk+HXueoif8iFcqFCqsRF3SQCsfJkt+z+LgqTAHQL5A0YF8oBXVGgBkS9WeDc8xcMJT
kOg3W/2y4VdMpJ9mKpED/BSk6KPaPlyqG/86C+KvKv76PyBoUBs=
===END CRASH DUMP===

**Comment by shoghicp** [comment]
@PonyPC That's a completely different issue, please do not report multiple issues in the same ticket. Alsi, it's duplicated
