### ISSUE TITLE
bug with server stuck

### ISSUE THREAD

**Issue by Alcatraz-Du** [PocketMine/PocketMine-MP#2486]
I start my server ,a few minutes later,console is stuck,and 28players (all player) are timeout,
Console is stuck, I check my device's CPU,find.              Server use CPU 80%!!,,,but console is stuck, 
Not only me,my friends,their severe have the same problem.

My device
4core 2.1GHZ    28G RAM  60Mbandwidth

please fix this.

**Comment by Alcatraz-Du** [comment]
I try to find problems,but four days,I don't have progress.

**Comment by Alcatraz-Du** [comment]
When player timeout console didn't show anything,
It just was stuck.

**Comment by Alcatraz-Du** [comment]
Many server got the same problems

**Comment by Alcatraz-Du** [comment]
no matter I use soft or mp,old version or new version, it will stuck.

**Comment by Alcatraz-Du** [comment]
when I use old version,and debug=5.  console  will show this,     then server is stuck.

11:53:31 [DEBUG] #1 /src/raklib/server/SessionManager(91): raklib\server\SessionManager->tickProcessor()
11:53:31 [DEBUG] #2 /src/raklib/server/SessionManager(79): raklib\server\SessionManager->run()
11:53:31 [DEBUG] #3 /src/raklib/server/RakLibServer(239): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
11:53:31 [DEBUG] [RakLib Thread #5556] An E_NOTICE error happened: "Undefined variable: size" in "/src/raklib/server/Session" at line 367
11:53:31 [DEBUG] #0 /src/raklib/server/SessionManager(105): raklib\server\SessionManager->receivePacket()
11:53:31 [DEBUG] #1 /src/raklib/server/SessionManager(91): raklib\server\SessionManager->tickProcessor()
11:53:31 [DEBUG] #2 /src/raklib/server/SessionManager(79): raklib\server\SessionManager->run()
11:53:31 [DEBUG] #3 /src/raklib/server/RakLibServer(239): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)
11:53:35 [DEBUG] [RakLib Thread #5556] An E_NOTICE error happened: "Undefined variable: size" in "/src/raklib/server/Session" at line 367
11:53:35 [DEBUG] #0 /src/raklib/server/SessionManager(105): raklib\server\SessionManager->receivePacket()
11:53:35 [DEBUG] #1 /src/raklib/server/SessionManager(91): raklib\server\SessionManager->tickProcessor()
11:53:35 [DEBUG] #2 /src/raklib/server/SessionManager(79): raklib\server\SessionManager->run()
11:53:35 [DEBUG] #3 /src/raklib/server/RakLibServer(239): raklib\server\SessionManager->__construct(raklib\server\RakLibServer object, raklib\server\UDPServerSocket object)

**Comment by Alcatraz-Du** [comment]
Can you fix it?

**Comment by PEMapModder** [comment]
@Alcatraz-Du do not report duplicated issues. And closed issues mean they are either invalid or fixed.
