### ISSUE TITLE
Crash on loading LevelDB world on Final release 1.4 "Zekkou Cake"

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#2487]
Here is crashdump file and the world !

PocketMine-MP Crash Dump Fri Jan 2 20:35:58 AST 2015

Error: file_put_contents(C:\Users\Romuald\Documents\Servs MCPE\Test 1.4Beta\worlds/world/level.dat): failed to open stream: Permission denied
File: /src/pocketmine/level/format/mcregion/McRegion
Line: 102
Type: warning

Code:
[93] 			"generatorOptions" => new String("generatorOptions", isset($options["preset"]) ? $options["preset"] : ""),
[94] 			"LevelName" => new String("LevelName", $name),
[95] 			"GameRules" => new Compound("GameRules", [])
[96] 		]);
[97] 		$nbt = new NBT(NBT::BIG_ENDIAN);
[98] 		$nbt->setData(new Compound(\null, [
[99] 			"Data" => $levelData
[100] 		]));
[101] 		$buffer = $nbt->writeCompressed();
[102] 		\file_put_contents($path . "level.dat", $buffer);
[103] 	}
[104] 
[105] 	public static function getRegionIndex($chunkX, $chunkZ, &$x, &$z){
[106] 		$x = $chunkX >> 5;
[107] 		$z = $chunkZ >> 5;
[108] 	}
[109] 
[110] 	public function requestChunkTask($x, $z){
[111] 		$chunk = $this->getChunk($x, $z, \false);
[112] 		if(!($chunk instanceof Chunk)){

Backtrace:
#0 /src/pocketmine/level/format/mcregion/McRegion(102): file_put_contents(string C:\Users\Romuald\Documents\Servs MCPE\Test 1.4Beta\worlds/world/level.dat, string ‹      MAnÂ0D'"…T©‡Š !T*¡–ÝWýÕZ8väPºêiØp V½CW=NÕ ³{ãñh~
¤ˆ3
!y'¯^gDi«ƒ&£?XE=$*¹h*†¨‡‡7¶ì)8¿b_kgÅ•T?¯hoŸ>;xw°¾¼vÝ§Ù—PFM¡ËssŒtNux2Ô°’ÊÙñô=sIV¹2çÖŠÃÏ¯˜¹l[ØL×\#îšZ%¸ÿßù(ûÑ·Î—d’›ý‹*È’º
ç¼csÞí7*Å°={¹5,ü	ûý"+  )
#1 /src/pocketmine/Server(1147): pocketmine\level\format\mcregion\McRegion::generate(string C:\Users\Romuald\Documents\Servs MCPE\Test 1.4Beta\worlds/world/, string world, integer 1420220158, string pocketmine\level\generator\Normal, array Array)
#2 /src/pocketmine/Server(1650): pocketmine\Server->generateLevel(string world, integer 1420220158)
#3 /src/pocketmine/PocketMine(440): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Users/Romuald/Documents/Servs MCPE/Test 1.4Beta/PocketMine-MP.phar/, string C:\Users\Romuald\Documents\Servs MCPE\Test 1.4Beta\, string C:\Users\Romuald\Documents\Servs MCPE\Test 1.4Beta\plugins\)
#4 (1): require(string phar://C:/Users/Romuald/Documents/Servs MCPE/Test 1.4Beta/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4 #916 [Protocol 20; API 1.10.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT ROMUALD-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

World link : https://www.dropbox.com/sh/dm6ti294rv746wm/AAA_2hqMaXL2-MIUUjQT0CsNa?dl=0

**Comment by shoghicp** [comment]
It seems like you don' have permissions on that folder AND you did not read the release notes, as Windows doesn't support LevelDB worlds.
