### ISSUE TITLE
Player suffocates when putting blocks to climb higher

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#2488]
When player is trying to climb higher and putting blocks below it too quickly when jumping, he suffocates in the placed block.

**Comment by shoghicp** [comment]
Hmm, is it happening on the latest development build?

**Comment by roroB20** [comment]
I'll try it !

**Comment by roroB20** [comment]
Yes, unfortunately it happened on build #919 too :/ !

**Comment by MobileCrafter** [comment]
I also can reproduce it.
