### ISSUE TITLE
Worldborder is too small

### ISSUE THREAD

**Issue by MobileCrafter** [PocketMine/PocketMine-MP#2492]
I was messing arround with the world limit in mcpe.
I know its really buggy on an mcpe client.
So I joined the server from a pc client and teleportet me to 29999999 90 29999999, but I was out of the border.
So the border is at:
![2015-01-02_23 28 17](https://cloud.githubusercontent.com/assets/5413827/5600393/507638ae-92d9-11e4-8de2-ccb54db4c3ad.png)

Strange.

**Comment by shoghicp** [comment]
This is not a PocketMine-MP issue. Please refer from posting this kind of issues in the future.
