### ISSUE TITLE
Chestbug

### ISSUE THREAD

**Issue by MobileCrafter** [PocketMine/PocketMine-MP#2493]
Chests in other  direction can be placed against chests and are not transferring to a double chest.
(Sorry for bad english)
Also I think there are other issues with chests placement.

**Comment by shoghicp** [comment]
Double chests are buggy, this is a known issue.

**Comment by Creeperface01** [comment]
yes all items are despawning from double chest

**Comment by wsantos** [comment]
I have the same issue

**Comment by stxyzth** [comment]
Any fix on this yet?

**Comment by prankard** [comment]
This was annoying me on my server. So I had a go at fixing it. Please test, check, test.
