### ISSUE TITLE
[ERROR] Corrupted chunk header detected

### ISSUE THREAD

**Issue by redmanjbj** [PocketMine/PocketMine-MP#2494]
Began getting this error today. "[ERROR] Corrupted chunk header detected"
When i log into the world it spams it continuously and then disconnects.

EDIT: After restarting the server a few times the issue seems to be gone. It spammed the message a few hundred times and then stopped. The world seems to be OK now...

**Comment by silversittich** [comment]
I noticed the same.

**Comment by shoghicp** [comment]
This is a new security measure that protects against several types of world corruption. Before, finding one of these chunks caused the server to crash. Now it detects them.
