### ISSUE TITLE
in PC maps chunks are not loading

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2495]
if i have PC map in latest stable pocketmine, chunks only load if i join to this map and after chunks are not loading. and console say: dont keep up! server is overloaded

**Comment by PEMapModder** [comment]
Chunks are not supposed to be loaded if nobody is using them...

**Comment by shoghicp** [comment]
Please convert your PC worlds to McRegion using external tools. You'll get greater performance than using Anvil directly.

**Comment by Creeperface01** [comment]
thanks

**Comment by Creeperface01** [comment]
how can i convert it? i didn´t find ANY CONVERTER. please
