### ISSUE TITLE
Server will get stuck,when memory rise to 900M RAM

### ISSUE THREAD

**Issue by Alcatraz-Du** [PocketMine/PocketMine-MP#2496]
Everytimes I Start my server,players join ,Memory get 900M RAM,then,server get stuck, There's no reaction in console.

Please fix it.

**Comment by Alcatraz-Du** [comment]
It seem that, pm can't use memory over 1024M

**Comment by PEMapModder** [comment]
Increase your memory limit. This is not a PocketMine issue.
About console being stuck, there is a duplicated issue. Use the latest build.

**Comment by Alcatraz-Du** [comment]
But I give it 2048M

**Comment by PEMapModder** [comment]
But can the players still join? If they can, it is not a memory issue. Search for the issues before creating one.

**Comment by Alcatraz-Du** [comment]
Then can't, And all timeout,   ,, you type anything in console,It doesn't work

**Comment by PonyPC** [comment]
same issue as you, shoghicp said that isn't pm issue. it's about PHP thread issue. ( ▼-▼ )

**Comment by Alcatraz-Du** [comment]
Always get stuck,,players even can't play
