### ISSUE TITLE
Slabs and Stairs Glitch

### ISSUE THREAD

**Issue by SeangJemmy** [PocketMine/PocketMine-MP#2499]
Slabs and stairs always put us back on them. We can't move and it always teleport us back.

**Comment by shoghicp** [comment]
Is this happening on the latest development build?

**Comment by SeangJemmy** [comment]
Idk, but I gonna try :)

**Comment by SeangJemmy** [comment]
Is the furnace glitch fixed?

**Comment by MobileCrafter** [comment]
I cannot reproduce it on the newest build^^

**Comment by TonyDroidd** [comment]
I have the same problem:/
I'm using the last build of Pocketmine-Soft

**Comment by Creeperface01** [comment]
please how can i disable this? :/ player can't move on stairs or slabs! and on LBSG servers players can move so how to disable it???

**Comment by TonyDroidd** [comment]
Use PocketMine-Soft

And disabld the 'check-movent' in pocketmine-soft.yml

**Comment by Creeperface01** [comment]
Fatal error: Uncaught exception 'RuntimeException' with message 'socket_bind(): unable to bind address [98]: Address already in use' in phar:///hlserver/27750/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php:57
Stack trace:
#0 [internal function]: ExceptionHandler::handler(2, 'socket_bind(): ...', 'phar:///hlserve...', 57, Array)
#1 phar:///hlserver/27750/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php(57): socket_bind(Resource id #63, '93.91.250.135', 27750)
#2 phar:///hlserver/27750/PocketMine-MP.phar/src/pocketmine/Server.php(1576): pocketmine\network\rcon\RCON->__construct(Object(pocketmine\Server), 'kaktus01', 27750, '93.91.250.135', 1, 50)
#3 phar:///hlserver/27750/PocketMine-MP.phar/src/pocketmine/PocketMine.php(437): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'phar:///hlserve...', '/hlserver/27750...', '/hlserver/27750...')
#4 /hlserver/27750/PocketMine-MP.phar(1): require('phar:///hlserve...')
#5 {main}
thrown in phar:///hlserver/27750/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php on line 57
stop
