### ISSUE TITLE
Big memory consumption on chunk generation?

### ISSUE THREAD

**Issue by ns827** [PocketMine/PocketMine-MP#2500]
The process php.exe(32-bit mode on 64-bit windows 7) consumes 250~450 KB of memory per second and its TPS decreases down. Also server prints several overloaded warnings and the memory consumption stopped at 104MB, but please notice that I didn't do anything, just running a server without any client.

I've thought it was from the first chunk generation, but size of r.0.0.mcr is just around 1228KB.

So, I saved all data and restarted the server, and the server seems to work fine, using 60MB of memory without any client, neither.

Tested on:
Intel Core i7-3630QM processor(2.4Ghz, with Turbo Boost up to 3.4Ghz)
4GB of memory
Windows 7 Ultimate(maybe?) 64-bit
PocketMine-MP 1,4 stable build fresh, default configuration

**Comment by shoghicp** [comment]
Yes, world generation uses memory. Check your pocketmine.yml for some dangerous settings.

**Comment by ns827** [comment]
@shoghicp I didn't touch any configuration file for server. But do you think consuming 60MB of memory with loading a 1300KB sized level isn't a problem?

**Comment by shoghicp** [comment]
@ns827 The world is saved compressed, while it's handled and loaded in RAM uncompressed. Try lowering the amount of sent chunks per client.
