### ISSUE TITLE
Dissapearing chunks

### ISSUE THREAD

**Issue by redmanjbj** [PocketMine/PocketMine-MP#2501]
One of my server users built a large structure, logged out and back in to find that it wasn't there. I restarted the server, but it happened to him a second time.  Also, after he logged off I found that half of the house i built the night before was missing.  

-I've been using the latest build since yesterday and didn't experience this issue until tonight. 
-When i viewed the other user on my screen he was NOT moving... but he was moving and building on his screen.
-There were no errors reported by the server.

**Comment by shoghicp** [comment]
This can be caused due to bad network issues, too. Try using the latest development build.

**Comment by redmanjbj** [comment]
Thx. The network on my side seems ok. I can't speak for my friend's.  

Just tried the dev build. I had the same issue... This time i got the "Corrupted Chunk Header" spam.  And after that stopped i noticed that only part of my map would load. I just hit an invisible wall and the rest of the terrain would not generate no matter how long i waited.  I'd also like to note that when this happened last night my friend and I were building in two separate regions of the world, quite a ways apart.  Not sure if that means anything.

**Comment by FunnyCrafteur** [comment]
I have the same problem

**Comment by redmanjbj** [comment]
this one is becoming really annoying.  I'm now running a pocketmine server from pocketserver because i thought this might be something to do with my PC or modem.  But i'm having the same issue with the online server too. Tonight we lost a big chunk of a castle we built.... just a big square chunk is gone.

**Comment by shoghicp** [comment]
@redmanjbj This is due to a save corruption, using the latest build might fix this issue

**Comment by shoghicp** [comment]
4b73dbd and efe75f2 might fix this issue, they are available on the latest development build.

**Comment by richard20020815** [comment]
using dev #950 same thing happens, no record,half my house disappears together with whole mining facililty.I m using a bridge across the hole, thats really horrible!

**Comment by alejandroliu** [comment]
Does this still happen with 1.4.1?
