### ISSUE TITLE
banip

### ISSUE THREAD

**Issue by llj070** [PocketMine/PocketMine-MP#2503]
Is the command for ban player's ip go wrong ? For it was  "banip" in 0.8.1 ,but now "ban"  ????Why not keep "banip" in 0.10.4 ???

**Comment by PEMapModder** [comment]
It is /ban-ip
Use /help for help.

**Comment by llj070** [comment]
I go to the git ,and found it is now  "/ban <address|player> [reason...]"

**Comment by 64FF00** [comment]
@PEMapModder https://github.com/PocketMine/PocketMine-MP/commit/c8b5c023cd066c20465b94627f10d8612f375150

**Comment by PEMapModder** [comment]
Yes I saw it.
