### ISSUE TITLE
Unselectable Items/Blocks in Creative Mode

### ISSUE THREAD

**Issue by MobileCrafter** [PocketMine/PocketMine-MP#2510]
I made a list of all unselectable Items/Blocks:
-Bone
-Raw Beef
-Bowl

-Rail
-Powered Rail
-Minecart
-Spawnegg:Chicken
-Spawnegg:Cow
-Spawnegg:Pig
-Spawnegg:Sheep
-Spawnegg:Wolf
-Spawnegg:Mooshroom
-Spawnegg:Creeper
-Spawnegg:Enderman
-Spawnegg:Silverfish
-Spawnegg:Skeleton
-Spawnegg:Slime
-Spawnegg:Spider
-Spawnegg:Zombie Pigman

-Lily Pad
-Spruce Fence
-Birch Fence
-Jungle Fence
-Acacia Fence
-Dark Oak Fence
-Blue Orchid (Plant)
-Allium (Plant)
-Azure Bluet (Plant)
-Red Tulip (Plant)
-Orange Tulip (Plant)
-White Tulip (Plant)
-Pink Tulip (Plant)
-Oxeye Daisy (Plant)
-Sunflower (Plant)
-Lilac (Plant)
-Double Tallgrass (Plant)
-Large Fern (Plant)
-Rose Bush (Plant)
-Peony (Plant)
-Brown Mushroomblock
-Red Mushroomblock
-Mushroomstem (Brown)
-Mushroomstem (Red)
-Spruce Sapling
-Birch Sapling
-Jungle Sapling
-Acacia Sapling
-Dark Oak Sapling

I know that Minecart and other things will not be implemented yet, but it would be cool if you could place Rails, Saplings, Fences, Plants and more and just select all Items/Blocks.

**Comment by shoghicp** [comment]
I can select all kind of fences and saplings correctly, are you sure that got tested correctly?

**Please follow the Contribution Guidelines. This includes posting features listed in the "Not implemented or known issues" section on each release**
