### ISSUE TITLE
Inventory Shifts after a tool breaks

### ISSUE THREAD

**Issue by adamsd5** [PocketMine/PocketMine-MP#2514]
While mining, my stone tool broke.  After that, the items in my inventory hotbar all shifted.  I selected another and the items seem to shift around at unpredictable times.  One moment I'm mining with an iron pickaxe and the next I'm mining with my torches.  Then half the bar goes blank and I have to re-select items.  I pulled the latest stable last night (1/5/2015) and it happens there.  Apologies if this is a known issue already as I don't see it in the bug list.  Let me know if more information helps.

**Comment by shoghicp** [comment]
This is a protocol issue. As the client doesn't send the hotbar slot they are using, the server has to guess and sending the inventory again (to maintain synchronization) shows the real order the server is using.

This is the protocol fault, not PocketMine

**Comment by adamsd5** [comment]
I've been keeping a close eye on this project as I think it is a fantastic idea.  However, this particular issue is the reason I cannot use it.  My kids and the neighbor kids will be very frustrated by this.  I can understand it is not PocketMine's fault.  However, if PocketMine cannot work around the problem, then Survival mode is unusable, at least until the protocol changes.

I've got some Java skill.  Perhaps I'll take a look and see if I can come up with anything.

**Comment by shoghicp** [comment]
This has been fixed in 0.11. Doing this in another language and implementing cheat protection would have the same issue :)

**Comment by adamsd5** [comment]
Excellent! I'll give the latest a try.  (I'm not sure I understand the language and cheat protection comment, but perhaps I will once I know the code base a bit better.  Overall, very nice, clean code.  I'm impressed.)

**Comment by shoghicp** [comment]
You'll have to wait a bit, 0.11 is not yet released :)
