### ISSUE TITLE
Massive Lagg on new chunk creation

### ISSUE THREAD

**Issue by MobileCrafter** [PocketMine/PocketMine-MP#2516]
Worlds that are created with Pocketmine are lagging so hard(1.7 TPS for me).
Durring this lagg I pinged my router. Was stable with 1 ms.
Then after some minutes it will convert the chunks and the server gets stable. 
But when you generate new chunks(flying in new terrain) it will lagg again.
I just tested on older builds.
For me it still hapenned on build 878.
But maybe I downgraded wrong.(Just replaced the phar)
Im on win64bit.

**Comment by shoghicp** [comment]
How old were those builds?

**Comment by MobileCrafter** [comment]
So first I testet with the newest build
Then I just downgraded more and more...
As I said still happened between 870-890.
I dont now the exact build that was the lowest.

**Comment by shoghicp** [comment]
Ah, I thought you mean that it did not lag before. Sorry, but it has lagged all the time, and it has only improved. World generation is costly.

Please read the pocketmine.yml and tune your chunk generation settings, you might also want to try the threaded generator (that might leak memory).

**Comment by MobileCrafter** [comment]
Ok there is definetly a bug. I testet more.
On beta 16 it just generated normally and was super fast.
Then I took beta 17 and it was just massivley lagging like on the newest build and beta.
So I updatet beta 16 with several builds. Also build 900 was just generating fast.
Offcourse I deleted the world  an player data on every change.
Offcourse theres a bug^^

**Comment by shoghicp** [comment]
You can view the list of changes in https://github.com/PocketMine/PocketMine-MP/compare/Alpha_1.4dev-900...master#files_bucket

Be aware that testing under my environment allows generating them normally.

**Comment by MobileCrafter** [comment]
Yeah I know that with the changes. But thanks.
I have windows 7 64bit.
When more people having this problem would you look into it?
I will make a video when I have time.
Then you will understand what I mean exactly.

**Comment by shoghicp** [comment]
@MobileCrafter I have the same issue, and I can only work around it. The main issue is noise generation. I speed up chunk generation 80% in the latest stable, but it still takes more than a few ticks per chunk.

**Comment by MobileCrafter** [comment]
Ohhhh ok.
