### ISSUE TITLE
hey im having troubles understanding how to send you a pull request.

### ISSUE THREAD

**Issue by neggersm** [PocketMine/PocketMine-MP#2519]
hey so ive been playing around with my servers php scripts and ive come up with a way to use all the fences all the saplings, and most of the flowers, how would i go about forwarding my ideas onto you as to update your server builds?

**Comment by Intyre** [comment]
Please read https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md or http://pocketmine-mp.readthedocs.org/en/latest/developers.html#contributing-code or https://help.github.com/articles/creating-a-pull-request/ or google?

**Comment by sekjun9878** [comment]
To phrase that easier, you can either forward the requests directly to us using our IRC channel, or code it yourself and make a pull request.
