### ISSUE TITLE
Sign dosen't works setCancelled()

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2521]
I'm writing the function to use BlockBreakEvent and
I set the all BlockBreak to setCancelled ().
But Sign dosen't works setCancelled()

(PocketMine version 1.4 Development 936)
(OS:CentOS, plug-in API:[1.10.1])
(world type: mcregions, PE: 0.10.4(BlockLauncher))

**Comment by shoghicp** [comment]
It does work. This is a client-side glitch
