### ISSUE TITLE
some items should not drop after explosion

### ISSUE THREAD

**Issue by mmlmml1** [PocketMine/PocketMine-MP#2522]
When i light some tnts, some glass windows become an item after the explosion. (glass windows or glass should not drop). 
When a falling sand meet water, it becomes an item(It should stay in the water as a real sand not an item

**Comment by mmlmml1** [comment]
I mean after the explosion, some glass windows become an item.
Sorry for bad english :)

**Comment by mmlmml1** [comment]
And also when a falling sand drop into water, it.becomes an item.(It should be stay in the water as a real sand)

**Comment by PEMapModder** [comment]
@Falkirks isn't this issue about droppable glass/glass pane, which was fixed by @Intyre in a recent commit?

**Comment by Falkirks** [comment]
> When a falling sand meet water, it becomes an item(It should stay in the water as a real sand not an item
