### ISSUE TITLE
Spawnpoint splits in half after world tp

### ISSUE THREAD

**Issue by ztdroider25** [PocketMine/PocketMine-MP#2524]
When ever I teleport from my Lobby to another world, the spawn area splits in half.  If i touch the edge of a block where a wall or floor, etc. is supposed to be, it appears.  If I touch the other half that is below the spawn, the block(s) disappear.  I can land and walk on the 'invisible' blocks, but tnt falls right through them. 

I have posted links to my screenshots below:
I apologize if you wanted me to upload the images directly to the post, but I know how everyone is about the risk of viruses. (By no means would I upload a virus)
1. http://postimg.org/image/oe5nnqjyn/
2. http://postimg.org/image/4aqmpfhcf/
3. http://postimg.org/image/rnoo7xxfz/
4. http://postimg.org/image/c4r8atp5b/

EDIT: Forgot to mention I am running the latest dev build (936) like @shoghicp  mentioned in #2501 .

**Comment by MobileCrafter** [comment]
I have this bug too on the SG4 Map.
https://www.youtube.com/watch?v=BZ_muecCluc

**Comment by iJoshuaHD** [comment]
it would be nicely to know what kind of level type did you use? mcregion, mca, or leveldb?

**Comment by ztdroider25** [comment]
Good question @ijoshuahd, its an anvil map.  Im not messing with any of the leveldb stuff :).  But seriously dude chill out.

**Comment by iksaku** [comment]
It's recommended to use MCRegion worlds, Anvil are kinda buggy xD

**Comment by ztdroider25** [comment]
Thanks @iksaku, but how do I convert Anvil to McRegion then?  I've been researching, and all I can find is McRegion to Anvil.  Or maybe I have it all backwards?

**Comment by MobileCrafter** [comment]
I have one.
I can give you the files tommorow :)
And from me too a big thanks too @iksaku
World loads so much faster in mcregion!
