### ISSUE TITLE
Pocketmine-MP Development Build For iOS

### ISSUE THREAD

**Issue by devin5411** [PocketMine/PocketMine-MP#2526]
On The Cydia Repo it only Shows The Version of Pocketmine-MP Being 1.3.12 Is this still 1.4?

**Comment by devin5411** [comment]
Oh I mean The 1.4 Zekkou Cake Not Development

**Comment by Intyre** [comment]
Please use the forums to ask a question. 
There is no PHP binary for iOS and PocketMine-MP 1.4.

**Comment by devin5411** [comment]
When I Go To pocketmine.com and click get Pocketmine-MP 1.4 There is a popup and it has iOS on it.
