### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by diamond-gold** [PocketMine/PocketMine-MP#2527]
High CPU usage(~56%) even when there is only 1 player in the server. 2 Players will cause the server load to be near 100% (Latest build 936)

**Comment by Intyre** [comment]
We need more info. Please read [this](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue) and [this](http://pocketmine-mp.readthedocs.org/en/latest/issues.html).
