### ISSUE TITLE
Server Fatal error

### ISSUE THREAD

**Issue by Joci5525** [PocketMine/PocketMine-MP#2528]
HI  EVERYBODY!

Im found why my server crashing every time:

Fatal error: Allowed memory size of 209715200 bytes exhausted (tried to allocate 130968 bytes) in phar:///home/tcagame_svc888/JozsefO/888/PocketMine-MP.phar/src/raklib/protocol/EncapsulatedPacket.php on line 35

Anyone know how to fix this?

Best regards: Joci5525

**Comment by MobileCrafter** [comment]
On which build are you?
