### ISSUE TITLE
Server just stopped without any reason at all.

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2530]
im getting a bug where in a middle of a gameplay, the server will just stop and will show this kind of message:
./start.sh: line 56:  3214 Segmentation fault      "$PHP_BINARY" "$POCKETMINE_FILE" $@

this doesnt show when you shutdown the server properly.

**Comment by shoghicp** [comment]
It seems like you are using new binaries on a system with no base support for them. Please do not report PHP bugs in this reposiotory,
