### ISSUE TITLE
Console messages and chat are shown incorrectly

### ISSUE THREAD

**Issue by DaveJukes** [PocketMine/PocketMine-MP#2534]
The message and console windows don't work

**Comment by DaveJukes** [comment]
I'm trying to do this on a combination of iPad app and iPhone website!
At the current dev build, neither are working correctly @Shoghicp

**Comment by Intyre** [comment]
Please read [this](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue) and [this](http://pocketmine-mp.readthedocs.org/en/latest/issues.html).
