### ISSUE TITLE
pocket mine doesnt start on debian 7.7

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2537]
I ran installer.sh and after installation i ran command ./start.sh
Couldn't find a working PHP binary, please use the installer.
i used the installer 3 times and always terminal said it:
Couldn't find a working PHP binary, please use the installer.

please help me with it :(

**Comment by shoghicp** [comment]
**Please use the proper repository for installation issues**
---
It seems like the installer did not finis successfully, did you install the packages required for the fallback compilation?

**Comment by Creeperface01** [comment]
i installed perl, gcc, make, automake, libtool, autoconf and m4

**Comment by Creeperface01** [comment]
i install all of packages that are on https://github.com/PocketMine/PocketMine-MP/wiki/Setting-up-a-Server#linux

**Comment by shoghicp** [comment]
Please read and follow http://pocketmine.readthedocs.org/en/latest/
