### ISSUE TITLE
Segmention fault

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PocketMine/PocketMine-MP#2539]
![screenshot_2](https://cloud.githubusercontent.com/assets/9496359/5738344/64ff07ea-9bd2-11e4-9af4-746302897321.png)
Error while closing the server using "/stop"

(This also happens in the stable build)

**Comment by shoghicp** [comment]
This is due to PHP, and the experimental pthreads extension. As some threads (specifically, console reading) gets blocked, things go wrong at the end.
