### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2541]
Players can duplicate items. i dont know what method they used but one of my player just duplicated hundreds of diamond block stack inside of his chests. i think there is a duplication protection built-in in pocketmine, just to check again to patch it up.

**Comment by shoghicp** [comment]
There is no "duplication" protection.
There is a Transaction checking, so players must interact correctly with inventories as otherwise the server will refuse the transaction and rollback it.
If there is a bug, the server will create those items, so players can then use them.

Note that currently this issue is **invalid**. Please add extra information as this cannot be reproduced right now.

**Comment by iJoshuaHD** [comment]
ic. i hope there would be item duplication protection in the future soon! a new feature in the anti cheating protection. im closing this issue.

**Comment by iJoshuaHD** [comment]
im reopening the issue. i just figured out what the bug is.
Players duplicate items using chest and some timings. for instance, i do some automation server restarts and i broadcast messages when the server will have its next reboot hence here comes the born of the glitch. Lets assume the server has ASR installed and the server will restart for the next 30 seconds. players would put their items in chest and wait for the 10 secs countdown to start. when it starts, they would grab their items in chest and wait for the server to stop. When the server starts, the item they removed in the chest was still present in the chest even though its been removed.

i did some tests with and without auto restarts. i put my item in a chest, removed it. restart the server and the item is still there even though i have removed it. now i have a duplicated item.

**Comment by joelmatousek** [comment]
This might be a little noob coment but I know of another glitch where when two people take one item out at the same time it gives it to both players. This could also be apart of people duplicateing

**Comment by iJoshuaHD** [comment]
I tested that glitch running pocketmine server, it doesnt work like the single player.

**Comment by mightysun99** [comment]
There is also another way to duplicate Go fair away from spawn /sethome or remember your location there then place a chest, put the stuff you wanna duplicate in that chest. Place some blocks in the chunk that the chest is in wait a minute or so now re log and check if the stuff is still in the chest. Should still be in there so take it out and say head back to spawn. Now head back to where the chest was and the stuff will still be in there that uve already taken out. So now uve got double. Players can repeat this and gain alot.

**Comment by iJoshuaHD** [comment]
bravo @mightysun99 :)

**Comment by iJoshuaHD** [comment]
the bug still exist ...

**Comment by shoghicp** [comment]
@iJoshuaHD We fixed the documented way to trigger the bug. If you can correctly document another way to duplicate items, please open a new issue.

**Comment by iJoshuaHD** [comment]
the same bug with the server stop. idk why. im using your current builds ... not soft.
