### ISSUE TITLE
Server not responding

### ISSUE THREAD

**Issue by KiddRock** [PocketMine/PocketMine-MP#2545]
all chat and all broadcast message is stop, and when i type and command such list or help, it doesnt work. and i still waiting for see the crash

this is crash info : 
Fatal error: Out of memory (allocated 1268514816) (tried to allocate 33554432 bytes) in phar:///root/Downloads/pm/PocketMine-Soft.phar/src/raklib/server/Session.php on line 176
00:19:21 [EMERGENCY] [RakLib Thread #-1270875280] RakLib crashed!

but on my console, the memory load is 296 / 383 MB

thank you :)

**Comment by devin5411** [comment]
Ya that has happened to me just restart the server that's the best solution I know until they fix this :)

**Comment by iksaku** [comment]
Maybe it's because of internet...

**Comment by Intyre** [comment]
"Out of memory (allocated 1268514816) (tried to allocate 33554432 bytes)"
Allocate more memory.
