### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by Zomboy36** [PocketMine/PocketMine-MP#2546]
*Hello!* When I open *Start*, it comes with a white screen with a small black box on the top-left-corner. It's supposed to be the Terminal. On top of the page, says *Not Responding*. So, I try to fix this problem.. This happened be before. I go to *TaskManager*, click terminal, and go to details, click set priorty to RealTime. After that, It unfroze. This time, when it unfreezes my screen, a text comes up on the terminal/Mintty, saying: *bin\php\php.exe: Segmentation fault*
Any help? Please?!

**Comment by PEMapModder** [comment]
Try reinstalling using the provided installer.
