### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by GoneTone** [PocketMine/PocketMine-MP#2550]
I do not know how this is going on, please help me.

LOG File : https://drive.google.com/file/d/0B6wBz0-FGPC9RmRfVThZdk9EWHc/view?usp=sharing

**Comment by shoghicp** [comment]
This issue is **invalid**. Please follow the [Contribution Guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) and upload crash reports to the [Crash Archive](https://crash.pocketmine.net/)
