### ISSUE TITLE
PvP Player Kick Bug

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2554]
If a player1 hits player2 many times, player2 gets kicked. i checked the console, it only shows player just get disconnected. the cause is not flying or something.

**Comment by PEMapModder** [comment]
What is the cause exactly? "Client disconnect"?

**Comment by iJoshuaHD** [comment]
Yup. Only client disconnect. Not being kicked

**Comment by iJoshuaHD** [comment]
fixed the bug after reinstalling pocketmine php binaries. weird bug for me ...
