### ISSUE TITLE
wont work after plugin

### ISSUE THREAD

**Issue by joelmatousek** [PocketMine/PocketMine-MP#2556]
Im making a multiworld server so I downloaded a sign portal plugin and when I was using it my server crashed and wouldn't start in the command section I get this
![screenshot_2015-01-20-20-55-01](https://cloud.githubusercontent.com/assets/10624070/5830033/78aaba76-a0e8-11e4-9dbb-66fd1b0591ce.png)

How do I fix this (im a noob so I need a step by step list)

**Comment by joelmatousek** [comment]
By the way I deleted the plugin

**Comment by Darkrift411** [comment]
The error above says that something is already bound to that port on your server. The port is 19132 - Most likely when you stopped the server the first time it never fully stopped, so you are running it a second time. You can try to find the process and kill it. start by typing (assuming you are on linux):

netstat -pant|grep ":19132"

That will show you the process that is listening on that port. You may be able to kill it using the process number that it shows. I cannot guarantee that killing the process will not corrupt your world, so I hope you have backups just-in-case

**Comment by Intyre** [comment]
Please ask questions on the [forums](https://forums.pocketmine.net/forums/)
