### ISSUE TITLE
Console is spammed with => Could not tick level worldName: Trying to get property of non -object

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2561]
I turned on debug mode and got this data below:

-------------------------------------------------------------------------------------------------------------
05:36:27 [NOTICE] InvalidStateException: "Trying to get property of non-object"
(E_NOTICE) in "/src/pocketmine/Player" at line 1244
05:36:27 [DEBUG] #0 /src/pocketmine/level/Level(515): pocketmine\Player->onUpdat
e(integer 226)
05:36:27 [DEBUG] #1 /src/pocketmine/Server(2182): pocketmine\level\Level->doTick
(integer 226)
05:36:27 [DEBUG] #2 /src/pocketmine/Server(2282): pocketmine\Server->checkTickUp
dates(integer 226)
05:36:27 [DEBUG] #3 /src/pocketmine/Server(2168): pocketmine\Server->tick()
05:36:27 [DEBUG] #4 /src/pocketmine/Server(2044): pocketmine\Server->tickProcess
or()
05:36:27 [DEBUG] #5 /src/pocketmine/Server(1758): pocketmine\Server->start()
05:36:27 [DEBUG] #6 /src/pocketmine/PocketMine(437): pocketmine\Server->__constr
uct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object,
 string phar:///imcpe/v3/PocketMine-MP.phar/, string /imcpe/v3/, string /imcpe/v
3/plugins/)
05:36:27 [DEBUG] #7 (1): require(string phar:///imcpe/v3/PocketMine-MP.phar/src/
pocketmine/PocketMine.php)
05:36:27 [CRITICAL] Could not tick level Factions: Trying to get property of non
-object
05:36:27 [NOTICE] InvalidStateException: "Trying to get property of non-object"
(E_NOTICE) in "/src/pocketmine/Player" at line 1244

-----------------------------------------------------------------------------------------------------------------------
So i checked this: https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/Player.php#L1244
which happens to be ++$this->inAirTicks;

im not sure whats wrong with this.

**Comment by shoghicp** [comment]
This is a plugin issue, as I told you before on the IRC channel. Plugins schedule things that break ticking.
Also, it seems like you are using Soft. Soft is not supported here, so this issue is **invalid**.
