### ISSUE TITLE
[Bug] Porting Anvil Worlds To Server

### ISSUE THREAD

**Issue by ZenCloudMC** [PocketMine/PocketMine-MP#2562]
So, Basically I tried to port a PC Survival World To The Server And When I Completed The Transfer From The %appdata% to the worlds folder. I loaded it on MCPE using a World Manager. When I tp to that world only one chunk of that world was loaded the other chunks around it stayed the same with normal generation of Pocketmine.

**Comment by shoghicp** [comment]
This issue is **invalid**. Please follow the Contribution Guidelines.
