### ISSUE TITLE
Server not allocating enough CPU 

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#2567]
I've been having this problem for awhile. The server does not allocate enough CPU to efficiently run and sometimes enough to even startup.

Normally the CPU starts at around 7-12% ( Server CPU ) when booting and then slowly increases from that point on when players start to join. ( With plugins, world files, ect. ) The server usage with the pocketmine console normally bounces around 20-30% usage.

However as of recently, that completely changed. It nows starts from 0.1% to 2% and hinges around that number until it falls down sometimes to a solid 0%. ( With plugins, world files, ect. )  Sometimes it will slowly crawl back up to 1% ( Server CPU ) and 100% Usage ( Pocketmine Console Statistics ) depending on the player count but it's not enough to support much players.

I also ran the same pocketmine version on a home server and a laptop. ( Both of these had clean installs of Pocketmine without any plugins and a newly generated world ). Both started up normally and hung around 1% ( On the pocketmine statistics ) with no lag issues without any players online. However, once I attempted to log on as a player account, the CPU stayed the same and the CPU usage on the pocketmine console shot up to 100% dropping the TPS down into decimal digits.

I am currently using the most recent developer build ( 954 )

**Comment by MobileCrafter** [comment]
Do you use Pocketmine generated worlds or Anvil worlds?
Anvil worlds are buggy and use much performance.

**Comment by peepzandmeepz** [comment]
The worlds were all fully generated with Pocketmine.

**Comment by MalekAlrwily** [comment]
I confirm that.

Also, sometimes when TPS is 20 and the allowed RAM is 700M, the server shows this message: Can't keep up! Is the server overloaded?

**Comment by LaudaM** [comment]
I can confirm this. The usage goes to %25 sometimes, and focuses on 1 core more than others bringing down the TPS and then it starts to lag.
The usage is high as it is for a PE server in comparison to CraftBukkit for the full version, and unstable.

**Comment by d3sperad0** [comment]
I've been having this exact same issue since I installed on my comp. Trying to run the server on a windows 7 64bit system. I've tried messing with the config files and two versions of pocketmine to no avail...

**Comment by shoghicp** [comment]
Wanted to use more CPU? Now PM 1.5 will generate, compress, and do a lot of things using the async workers!

**Comment by sekjun9878** [comment]
Now the real question is: When will 1.5 be released? xD

**Comment by iVertx** [comment]
@shogicp if possible, please implement a properly multi-core support for PM 1.5, it will boost up pocketmine performance...
I have a VPS with 14.4 GHz in total, but only 2.44 GHz each core, and Pocketmine only use the main core, instead of use all of then... Really it need to be implemented...
