### ISSUE TITLE
Plz help me

### ISSUE THREAD

**Issue by gksehdtjq** [PocketMine/PocketMine-MP#2568]
It just do  like this
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 00:15:41 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 00:15:41 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 00:15:41 [INFO] Loading pocketmine.yml...
[Server] 00:15:41 [INFO] Loading server properties...
[Server] 00:15:41 [INFO] Advanced cache enabled
[Server] 00:15:41 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 00:15:41 [INFO] This server is running PocketMine-MP version 1.4.1dev-954 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 00:15:41 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 00:15:41 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
[Server] 00:15:41 [CRITICAL] Perhaps a server is already running on that port?
[Server] 00:15:41 [EMERGENCY] [RakLib Thread #1079700776] RakLib crashed!
[Server] 00:15:46 [INFO] ----- PocketMine-MP Auto Updater -----
[Server] 00:15:46 [INFO] It appears you're running a Beta build, when you've specified that you prefer to run Stable builds.
[Server] 00:15:46 [INFO] If you would like to be kept informed about new Beta or Development builds, it is recommended that you change 'preferred-channel' in your pocketmine.yml to 'beta' or 'development'.
[Server] 00:15:46 [INFO] ----- -------------------------- -----
[Server] 00:15:46 [INFO] Preparing level "world"
[Server] 00:15:47 [INFO] Starting GS4 status listener
[Server] 00:15:47 [INFO] Setting query port to 19132
[Server] 00:15:47 [INFO] Query running on 0.0.0.0:19132
[Server] 00:15:47 [INFO] Default game type: SURVIVAL
[Server] 00:15:47 [INFO] Done (11.529s)! For help, type "help" or "?"
[Server] 00:15:47 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
[Server] 00:15:47 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 00:15:47 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Tue_Jan_27-00.15.47-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 00:15:52 [INFO] Unloading level "world"

**Comment by Rexo52** [comment]
Try with the stable version not the beta build

**Comment by peepzandmeepz** [comment]
I believe that your problem exists in your server configuration file considering it's saying your IP address on boot is this..
[Server] 00:15:41 [INFO] Starting Minecraft PE server on 0.0.0.0:19132

And therefor, causes this..

[Server] 00:15:47 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32

Its saying the address is in use as 0.0.0.0 isn't your server IP. I would try looking in your config file for any IP with that and removing it from the config file.
