### ISSUE TITLE
How can I do this

### ISSUE THREAD

**Issue by gksehdtjq** [PocketMine/PocketMine-MP#2570]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 07:32:52 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 07:32:52 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 07:32:52 [INFO] Loading pocketmine-soft.yml...
[Server] 07:32:52 [INFO] Loading pocketmine.yml...
[Server] 07:32:52 [INFO] Loading server properties...
[Server] 07:32:52 [INFO] Advanced cache enabled
[Server] 07:32:52 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 07:32:52 [INFO] This server is running PocketMine-Soft version 1.4.1dev-232 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 07:32:52 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 07:32:52 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
[Server] 07:32:52 [CRITICAL] Perhaps a server is already running on that port?
[Server] 07:32:52 [EMERGENCY] [RakLib Thread #1079487784] RakLib crashed!
[Server] 07:32:58 [NOTICE] Level "world" not found
[Server] 07:32:58 [INFO] Preparing level "world"
[Server] 07:32:58 [NOTICE] Spawn terrain for level "world" is being generated in the background
[Server] 07:32:58 [INFO] Starting GS4 status listener
[Server] 07:32:58 [INFO] Setting query port to 19132
[Server] 07:32:58 [INFO] Query running on 0.0.0.0:19132
[Server] 07:32:58 [INFO] Default game type: CREATIVE
[Server] 07:32:58 [INFO] Done (11.615s)! For help, type "help" or "?"
[Server] 07:32:58 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
[Server] 07:32:58 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 07:32:58 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Tue_Jan_27-07.32.58-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 07:33:04 [INFO] Unloading level "world"

**Comment by andrewnoelcasper** [comment]
Means you have an instance of Pocketmine running or there is another pocketmine running binded to your ip
