### ISSUE TITLE
Can't download for install

### ISSUE THREAD

**Issue by flareofghast** [PocketMine/PocketMine-MP#2578]
I have tried both suggested ways to download but I keep getting errors.

    curl -sL http://cdn.pocketmine.net/installer.sh | bash -s -
    [*] Found PocketMine-MP Final_1.4 (build 916) using API 1.10.0
    [*] This stable build was released on Fri Jan  2 11:06:11 ACDT 2015
    [+] The build was signed, will check signature
    [*] Installing/updating PocketMine-MP on directory ./
    [1/3] Cleaning...
    [2/3] Downloading PocketMine-MP Final_1.4 phar...bash: line 194: PocketMine-MP.phar: Permission denied
     failed!
    [!] Couldn't download PocketMine-MP automatically from https://github.com/PocketMine/PocketMine-MP/releases/download/1.4/PocketMine-MP_1.4.phar

    wget -q -O - http://get.pocketmine.net/ | bash
    [*] Found PocketMine-MP Final_1.4 (build 916) using API 1.10.0
    [*] This stable build was released on Fri Jan  2 11:06:11 ACDT 2015
    [+] The build was signed, will check signature
    [*] Installing/updating PocketMine-MP on directory ./
    [1/3] Cleaning...
    [2/3] Downloading PocketMine-MP Final_1.4 phar...bash: line 194: PocketMine-MP.phar: Permission denied
     failed!
    [!] Couldn't download PocketMine-MP automatically from https://github.com/PocketMine/PocketMine-MP/releases/download/1.4/PocketMine-MP_1.4.phar

**Comment by shoghicp** [comment]
Please check the permissions in your current folder.
This issue is **invalid**. Please follow the Contribution Guidelines.
