### ISSUE TITLE
superuser privileges is needed to run command ifconfig on openSUSE

### ISSUE THREAD

**Issue by hot123tea123** [PocketMine/PocketMine-MP#2580]
Hello, I found PocketMine use `ifconfig` to get the IP address, but superuser privileges is needed to run command ifconfig on openSUSE.
Maybe you could use command `ip` instead, which is a replacement of `ifconfig` and do not need superuser privileges.

**Comment by Intyre** [comment]
The directory /sbin/ isn't in the PATH for a normal user on openSUSE?
Add it or make a symlink.
