### ISSUE TITLE
couldn't tick world,uninitialized string offset -1

### ISSUE THREAD

**Issue by Alcatraz-Du** [PocketMine/PocketMine-MP#2582]
Shog,sometimes when player join server,he will get stuck,console will show
      "couldn't tick world,uninitialized string offset -1 "
,then,there is no any block around ,he can't move ,can't send message,because there is no reaction when press chat button,especially iOS,iOS system always got this issues,  OH before get stuck,player will hear the sound of the arrow.

**Comment by fengberd** [comment]
Sometimes,my Android device also got the issue.

**Comment by Drumpit** [comment]
yes on my Server too

**Comment by shoghicp** [comment]
If you can provide further information (backtrace) it would be great. Otherwise this has been fixed in 1.5
