### ISSUE TITLE
Jack-O-Lanterns emit no light

### ISSUE THREAD

**Issue by Darkrift411** [PocketMine/PocketMine-MP#2585]
I am unable to detect any light coming from jack-o-lanterns. They change appearance when crafted as they should but appear to be missing their light value.

**Comment by Darkrift411** [comment]
After testing further, it looks like the jack-o-lantern is changing back to a pumpkin. I am trying to tell if it is changing when I place it in the action bar, or when I place it.

**Comment by MobileCrafter** [comment]
Thats the server ;)

**Comment by WhiteWolfOwner** [comment]
Some times this glitches due to the server not loading fully when you last placed that Jack-O-Lantern it will lose some of the memory of the block being placed in a confined area.

Thanks,
WhiteWolfOwner

**Comment by PEMapModder** [comment]
@WhiteWolfOwner did you do `/save-on`?

**Comment by WhiteWolfOwner** [comment]
https://github.com/PEMapModderWell it wasnt really my server when I first noticed it. So I couldnt test that.

**Comment by WhiteWolfOwner** [comment]
@PEMapModder

**Comment by PEMapModder** [comment]
And the comment is irrelevant.
If it isn't your server, don't report. It may be the other server doing that on purpose. And this issue is about light population. Your comment is irrelevant.
