### ISSUE TITLE
Eating items does not repeat (turns into using food as a tool)

### ISSUE THREAD

**Issue by Darkrift411** [PocketMine/PocketMine-MP#2587]
When you eat food (bread or potatoes in my case), the first item is consumed properly, but then when the action should start to consume the second piece, the act of eating stops and you are suddenly using the food as a tool.

This causes you to sometimes break blocks depending on where you are aiming when you eat. To duplicate, start eating something while pointing at a nearby block in the wall. Continue eating until after the food item has been consumed and your player will start hitting the wall to break the block.

Also, a slightly reversed version of this, if you are performing an action with food selected (such as breaking down crops where the edible crop is the selected food), you will sometimes stop breaking the crops and start eating.

Easiest way to duplicate the last one is to select an empty slot in your action bar and start breaking down a crop such as potatoes or carrots (while having none of these in your inventory). When you pick up the first food/crop it will normally jump to the active slot in your inventory. At that point instead of breaking the crop with your hand you are breaking it with the food item. After a few more breaking actions, player will stop and start to eat the crop.

**Comment by LDX-MCPE** [comment]
These are client-side bugs. They exist even in local worlds.

**Comment by PEMapModder** [comment]
It is a client-side issue. PocketMine doesn't control how the player eats. (Use absence of network latency as proof)

**Comment by shoghicp** [comment]
Please report this on the [Mojang bug tracker](https://bugs.mojang.com/browse/MCPE)
