### ISSUE TITLE
Cant enter World after reloading

### ISSUE THREAD

**Issue by Sulfatezzz** [PocketMine/PocketMine-MP#2589]
When im reloading a Level with my self coded Plugin (->unloadLevel()....loadLevel()) I cant enter them.

I became this error every time:

Fatal error: Call to a member function getChunk() on null in C:\Server\s
rc\pocketmine\level\Level.php on line 2013

**Comment by PEMapModder** [comment]
Any stack trace?

**Comment by shoghicp** [comment]
Duplicated issue.
