### ISSUE TITLE
pocketmine

### ISSUE THREAD

**Issue by marnixah** [PocketMine/PocketMine-MP#2591]
i can`t go in the world its 0.8.1 i also can`t update it

**Comment by ztdroider25** [comment]
Idk if those worlds are supported anymore.  If you are on 0.8.1, you have to update manually to pocketmine 1.4 alpha.  If you use Mcedit, you can convert your 0.8.1 world into a McRegion or Anvil map which pocketmine 1.4 can use.  You can get McEdit here: http://khroki.github.io/MCEdit-Unified/ and newer pocketmine: http://www.pocketmine.net/
