### ISSUE TITLE
Enum Crashes

### ISSUE THREAD

**Issue by Samueljh1** [PocketMine/PocketMine-MP#2598]
Here is a Crash Report... Its weird, it was fine before, but now started to crash!

19:31:49 [NOTICE] RuntimeException: "Method pocketmine\nbt\tag\Enum::__toString() must return a string value" (E_RECOVERABLE_ERROR) in "/src/pocketmine/utils/TextFormat" at line 71

**Comment by shoghicp** [comment]
hmm, who tried to print a NBT tag? seems like a plugin issue, but adding a workaround

**Comment by Samueljh1** [comment]
Yea, a plugin causes this, and then one it has happened, it will cause crashes when a player joins that certain world. Also did you get my alert on the forums? I got IRC banned for no reason! :(

IP: 82.21.217.124

Also auto banned from #McpeDevs

(ChanServ) thanks in advance :)
