### ISSUE TITLE
Doesn't work server.log

### ISSUE THREAD

**Issue by cloud9350** [PocketMine/PocketMine-MP#2599]
PocketMine-MP Version : PocketMine-MP 1.4.1dev-954
Error : The output from the Console message is not written to the server.log.
Screenshot (GIF)
![_2015_02_03_09_23_16_465_mp4](https://cloud.githubusercontent.com/assets/5405019/6012113/43fc419c-ab87-11e4-9d18-29dd1fc16144.gif)

**Comment by unerds** [comment]
my server.log is also not populating - there is a workaround:

./start.sh 2>&1 | tee -a server.log

**Comment by cloud9350** [comment]
@unerds It's work! Thanks.
