### ISSUE TITLE
Doesn't work achievement.

### ISSUE THREAD

**Issue by cloud9350** [PocketMine/PocketMine-MP#2600]
PocketMine-MP Version : PocketMine-MP 1.4.1dev-954
Error : Doesn't work achievement - Acquire Iron

Code (src/pocketmine/Achievement.php)

61		"acquireIron" => [
62			"name" => "Acquire hardware",
63			"requires" => [
64				"buildFurnace",
65			],
66		],

97		"diamonds" => [
98			"name" => "DIAMONDS!",
99			"requires" => [
100				"acquireIron",
101			],
102		],

**Comment by sekjun9878** [comment]
What do you mean by "doesn't work achievement"? Is this a crash or a game play issue?

**Comment by OutTyre** [comment]
https://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issueshttps://github.com/PocketMine/PocketMine-MP/issues

**Comment by cloud9350** [comment]
@sekjun9878 Game play issue.

**Comment by cloud9350** [comment]
@sekjun9878 그냥 철괴를 획득했는데 도전과제가 작동하지 않습니다 :smile:

**Comment by HmHmmHm** [comment]
@sekjun9878 He said, when he get the Iron Ingot Achievement does not work 
@cloud9350 You must ensure that you have an Achivement(buildFurnace)

**Comment by cloud9350** [comment]
@HmHmmHm Get wood -> Build WorkBench -> Build Pickaxe -> Build Hoe -> Build Sword -> Build Furnace -> Acquire IronBar [failed]
