### ISSUE TITLE
items in furnaces disappear if chunk containing said furnace unloads

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2605]
according to my player base, they often lose items when smelting if they travel far enough away from the furnace while it still contains items.

dev956

**Comment by Darkrift411** [comment]
Verified.

**Comment by luca28pet** [comment]
It also happens with chest and double chest items

**Comment by devin5411** [comment]
double chest glitch use single chests and this bug is invalid please mark invalid
and close

**Comment by shoghicp** [comment]
This should have been fixed by 9173f930ca0c4ff6570ac10f8f0eb6876e42265e already
