### ISSUE TITLE
players able to place blocks in the same location they are standing

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2606]
both creative and survival mode players can do this.

dev 956

**Comment by Darkrift411** [comment]
I have duplicated this many times on 956. This should only be allowed with blocks that you can walk through, such as fences, torches, saplings, crops, etc. Instead, it works with any blocks, such as stone, which can cause you to take damage or even die.

You can place blocks both at your foot level and your head level.

**Comment by shoghicp** [comment]
This has been already fixed
