### ISSUE TITLE
**URGENT** Chests and Crafting Tabels!

### ISSUE THREAD

**Issue by zachrocks22** [PocketMine/PocketMine-MP#2610]
Tell me, what is the point of minecraft if you CANT KEEP ALL YOUR STUFF! Pointless right? Currently players in my game anytime they place ANYTHING in a chest it all disappears (the contents not the real chest) and it is very upsetting.

Please ANYONE give me advise, feedback or any help what so ever! THANK YOU.

**Comment by Darkrift411** [comment]
This is not a support forum. It is an issue tracker, which if you had read, you would know that double chests are bugged.
