### ISSUE TITLE
install fails on docker

### ISSUE THREAD

**Issue by tyedco** [PocketMine/PocketMine-MP#2611]
I tried to install on a docker container (debian stable). When  I enter:
./start.sh -p /usr/bin/php
It throws the following error:
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in phar:///home/steve/PocketMine-MP.phar/src/pocketmine/PocketMine.php on line 347

**Comment by shoghicp** [comment]
You have to use the provided binaries, or build your own using the installer
