### ISSUE TITLE
torches cannot be placed on cobblestone walls

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2615]
dev956

**Comment by shoghicp** [comment]
On top of them? there is a special case for fences, might need to add one for walls.

**Comment by Darkrift411** [comment]
I was not able to place torches on the sides or the top of them (like I can with a fence). I thought this was by design, but now that I think about it, it should be allowed as it is with wood fences.

**Comment by unerds** [comment]
yes, on top - they just disappear...

i'll keep polling my peeps for bugs - more to come ;)

we all really appreciate it shoghi!  drop by any time
