### ISSUE TITLE
Raspberry Pi 2 zlib

### ISSUE THREAD

**Issue by flaxues** [PocketMine/PocketMine-MP#2617]
I wanted to try if pocketmine works better now there is a new raspberry pi with better hardware but if i install it it's stopping by '[zlib] downloading 1.2.8... checking...pi@raspberrypi ~/Downloads/Pocketmine $' 

Install.log: http://pastebin.com/QwAZdMF0

**Comment by Guillaume351** [comment]
try : apt-get install g++

**Comment by shoghicp** [comment]
Seems like the newest RPi uses a different arch, it won't be auto detected. Please submit this report to the php-build-scripts repo, and the gcc version you have
