### ISSUE TITLE
tall grass can float when block below it is removed

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2624]
title says it all

bonemeal some grass blocks, and break them - floaty grass!

dev956

**Comment by WhiteWolfOwner** [comment]
If you are using worldeditart then it will do that because of lag also read this issue might help with thise issue as well...
https://github.com/PocketMine/PocketMine-MP/issues/2735

Thanks,
WhiteWolfOwner

**Comment by SoyBueno** [comment]
There is a bug in economys api muy consomé detected it.please fix this problem thanks for your attention!

**Comment by SoyBueno** [comment]
My console
