### ISSUE TITLE
waterfall into still water creates air pockets in the still water when stopped

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2625]
made a waterfall into a lake, and when i blocked the waterfall, the still water in the lake seems to have been overwritten by the falling water, and when the falling water stopped flowing, it just left air.

i hope i'm explaining that well enough.

cheers

**Comment by jingz2007** [comment]
That happens to me even on a local minecraft pocket edition world.

**Comment by PEMapModder** [comment]
Good. Minecraft is now more realistic. :)

**Comment by JoahDave** [comment]
@PEMapModder :)

**Comment by dktapps** [comment]
Duplicate of #2584
