### ISSUE TITLE
trees take on their intended shape/composition, but change shape and/or block type when tapped

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2626]
all tests were conducted using bonemeal in creative mode

oak saplings product oak trees just fine, though as you tap the leaf blocks some appear and some disappear ultimately changing the shape of the tree... you'll end up with an oak tree of a different shape (taller or shorter typically)

spruce saplings seem to behave the same way as oak though with spruce logs and leaf blocks and they do not revert to oak.

birch behaves the same as oak and spruce, correct block types but the shape changes as you touch the leaves... 

jungle just generates an oak shaped tree, that can similarly be tapped to produce a different shape.  the block types are correct and do not revert.

acacia saplings seem to produce a proper acacia tree, however when interacting with them as described above, they completely revert to a standard oak tree.  blocks and all - they turn to oak logs and oak leaves.

dark oak saplings seem to produce nothing, then as you tap the locations where the tree should have grown, it seems like a proper spruce tree populates in its place.

dev 956.

again, i hope i'm explaining this well enough

**Comment by iJoshuaHD** [comment]
i can confirm this bug too

**Comment by shoghicp** [comment]
Trees grow on the client side. This is a Mojang bug :P

**Comment by shoghicp** [comment]
This should have been fixed for the next release of Minecraft

**Comment by Bidou0418** [comment]
anyone fix this?
