### ISSUE TITLE
exception when stopping the server

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#2629]
doesn't seem to have any negative effects, but i get it every time:

Fatal error: Uncaught exception 'RuntimeException' with message 'Failed to correctly release the reference on free' in [no active file]:0
Stack trace:
#0 {main}
  thrown in [no active file] on line 0
Segmentation fault (core dumped)

**Comment by Creeperface01** [comment]
I have same problem. But server works fine.

**Comment by unerds** [comment]
i'm not sure if this is related, but we've had quite a lot of chunk errors where an entire chunk, and exactly a chunk will reset to default terrain overwriting player builds completely.

here is one pretty clear example.

http://redd.it/2wj1na

they seemed to have started around the time this error message first popped up - shortly after anyway...

**Comment by shoghicp** [comment]
This error is just something PHP causes :(

@unerds Please test the latest dev, it has fixes for that
