### ISSUE TITLE
Anti-Fly is very sensitive

### ISSUE THREAD

**Issue by Striker209MPE** [PocketMine/PocketMine-MP#2632]
By jumping multiple times, you get kicked:
10:12:04 [INFO] Striker209_MPE[/192.168.0.51:55604] logged out due to Kicked by admin. Reason: Flying is not enabled on this server

while you are not cheating :-(

**Comment by Striker209MPE** [comment]
Also, carpets and fence (wooden + stone) do the same only by walking on

**Comment by Striker209MPE** [comment]
Also in cobweb

**Comment by devin5411** [comment]
also when u stand on a chest u get kicked
