### ISSUE TITLE
OPs are deleting after restart or reload

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2636]
when a run command "op steve" from console and reload server steve isn´t OP.

**Comment by Darklord505** [comment]
I have the same problem,so I'm op on Jayaxe Creative And Jayaxe Survival and when the server is laggy I restart it and then I'm not op and all the staff only the owner.

**Comment by Darklord505** [comment]
Well only the owner is op

**Comment by shoghicp** [comment]
I can't reproduce this issue.
