### ISSUE TITLE
World not found/lebel won't load

### ISSUE THREAD

**Issue by LegaZy13** [PocketMine/PocketMine-MP#2639]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 20:28:27 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 20:28:27 [INFO] Loading pocketmine-soft.yml...
[Server] 20:28:27 [INFO] Loading pocketmine.yml...
[Server] 20:28:27 [INFO] Loading server properties...
[Server] 20:28:27 [INFO] Starting remote control listener
[Server] 20:28:27 [INFO] RCON running on 0.0.0.0:19132
[Server] 20:28:27 [INFO] Advanced cache enabled
[Server] 20:28:28 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 20:28:28 [INFO] This server is running PocketMine-Soft version 1.4.1dev-233 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 20:28:28 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 20:28:30 [INFO] Loading SimpleAuth v1.6.0
[Server] 20:28:30 [INFO] Loading EconomyAPI v2.0.4
[Server] 20:28:30 [INFO] Loading EconomyAuction v2.0.1
[Server] 20:28:30 [INFO] Loading EconomyCasino v2.0.1
[Server] 20:28:30 [INFO] Loading EconomyJob v2.0.2
[Server] 20:28:30 [INFO] Loading EconomyLand v2.0.5
[Server] 20:28:30 [INFO] Loading EconomyProperty v2.0.2
[Server] 20:28:30 [INFO] Loading EconomySell v2.0.3
[Server] 20:28:30 [INFO] Loading EconomyShop v2.0.3
[Server] 20:28:30 [INFO] Loading EconomyTax v2.0.2
[Server] 20:28:30 [INFO] Loading EssentialsPE v1.0.2
[Server] 20:28:30 [INFO] Loading DisguiseMe v1.1
[Server] 20:28:30 [INFO] Loading WorldEditArt v1.0.0_beta_dev_#045
[Server] 20:28:30 [INFO] Loading iProtector v2.0
[Server] 20:28:30 [INFO] Loading ArmorSpawn v2.0
[Server] 20:28:30 [INFO] Loading EconomyAirport v2.0.2
[Server] 20:28:31 [INFO] Enabling SimpleAuth v1.6.0
[Server] 20:28:31 [INFO] [SimpleAuth] Everything loaded!
[Server] 20:28:31 [ERROR] Could not load level "world": zlib_decode(): data error
[Server] 20:28:31 [WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 124
[Server] 20:28:31 [EMERGENCY] No default level has been loaded
[Server] 20:28:31 [INFO] Disabling SimpleAuth v1.6.0
[Server] 20:28:31 [INFO] Stopping other threads
[PocketMine] Server was stopped.
>plugins

**Comment by shoghicp** [comment]
Your world seems corrupt, or the format is not supported on your platform

**Comment by LegaZy13** [comment]
How do I fix that

**Comment by PEMapModder** [comment]
This is not a help forum. Please use our forums for that purpose.
