### ISSUE TITLE
Cannot detect Speed hacks

### ISSUE THREAD

**Issue by predawnia** [PocketMine/PocketMine-MP#2640]
Good work for detecting flying, no more flyers in the server, are you able to fix the Speed hackers too? Thank you in advance.

**Comment by PEMapModder** [comment]
Technically they aren't called "hackers". They are just people who use mods.

**Comment by shoghicp** [comment]
Speed enforcement is not set on the server.
This issue is **invalid**. Please follow the Contribution Guidelines in the future and only submit **REAL** bugs, not feature requests.
