### ISSUE TITLE
bin\php\php.exe: Exit 127

### ISSUE THREAD

**Issue by Thines11** [PocketMine/PocketMine-MP#2643]
I tried install Visual C++ everthing and uninstall and reinstalling it and its not fixing
Please Give Me a fix.

Thanks
![error](https://cloud.githubusercontent.com/assets/8815883/6242885/f9a8701a-b771-11e4-8fec-9b001173d5ef.PNG)

**Comment by Thines11** [comment]
why???

**Comment by Thines11** [comment]
help?

**Comment by Thines11** [comment]
dude so rude

**Comment by HmHmmHm** [comment]
HERE IS NOT FORUM, AND DON'T SPAM '~';

**Comment by 64FF00** [comment]
@HmHmmHm :+1:

**Comment by PEMapModder** [comment]
This is a bug tracker not a forum or support forum.
This is not a bug, it's only your problem

Please refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md) when creating an issue.
