### ISSUE TITLE
Server was stopped.

### ISSUE THREAD

**Issue by anonblizz** [PocketMine/PocketMine-MP#2646]
Hello everyone :D
So I have a problem. When I'm trying to start server it closes. In console found this:
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] data/data/net.pocketmine.server/php[1]: syntax error: 'D4??x4' unexpected
[PocketMine] Server was stopped.
How to fix this?

**Comment by iksaku** [comment]
Reinstall PocketMine, PHP and/or their dependencies

**Comment by anonblizz** [comment]
Maybe Andyroid simulator works not properly?

**Comment by shoghicp** [comment]
This issue is **invalid**. Please follow the Contribution Guidelines and submit the issue to the proper repository.
