### ISSUE TITLE
Please Help:bin\php\php.exe: Ex

### ISSUE THREAD

**Issue by Thines11** [PocketMine/PocketMine-MP#2648]
Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127Please Help:bin\php\php.exe: Exit 127

**Comment by PEMapModder** [comment]
This is **not** a help channel. It is **not** a bug. Stop spamming this bug tracker with invalid issues, or you'll most likely be blocked from PocketMine GitHub. If you need help, use [our forums](forums.pocketmine.net) for that.
