### ISSUE TITLE
Can't join server [iOS]

### ISSUE THREAD

**Issue by CokeZero** [PocketMine/PocketMine-MP#2654]
Hello, I have downloaded all of the pocket mine things needed to run the server, set it up in mobile terminal, but then when I try to join it says I can't join because the server is outdated and when I go back to mobile terminal the pocket mine build is version 1.3 I think and I think that is supporting Mcpe 0.8.1. So can somebody please help me get the correct pocket mine version so I can set up a server for Mcpe 0.10.4 on iOS. Thank you! :)

**Comment by PEMapModder** [comment]
This is not a place for individual support. The latest PocketMine build is available on pocketmine.net although (as I remember) there is no support for iOS yet.

**Comment by CokeZero** [comment]
Oh ok we're do I go for individual support if I need it?

**Comment by PEMapModder** [comment]
When creating an issue,

> Please review the [https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md](guidelines for contributing) to this repository.

**Comment by CokeZero** [comment]
I clicked the link and it sai 404 not found

**Comment by iksaku** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md

**Comment by CokeZero** [comment]
Do we have a timeframe of when it will be updated?

**Comment by iksaku** [comment]
No, there aren't any timeframes nor ETAs

**Comment by sekjun9878** [comment]
You can download the latest version of PocketMine from pocketmine.net. For further questions please visit our IRC channel or our forum.
