### ISSUE TITLE
World not Generating Correctly!

### ISSUE THREAD

**Issue by LouPit929** [PocketMine/PocketMine-MP#2725]
So I finally got PocketMine set up, but now when I start the server and generate a world, the world doesn't correspond to the seed I give it. The world always generates as if it had been made before version .9 (no new biomes, grass, etc.). When I tried putting in an already generated world from my iPad (with the same name as configured in the settings), the client says "level 'world' not found" "preparing 'world' " and generates a pre .9 world. /version says the PocketMine I downloaded is for PE 0.10.4, so I know I downloaded the right version.

**Comment by iksaku** [comment]
Right now, Pocketmine as a simple world generator, it generates the same wolrd always, so Seeds are not supported, neither biomes.

**Comment by crazyravenspeep** [comment]
I don't care about pocket mine please stop sending me this stuff! I can't log out please just delete my user from the website

**Comment by iksaku** [comment]
@crazyravenspeep Sorry? Please un subscribe from Github, you're the only one that can stop your problems, no one subscribed your email here.

**Comment by PEMapModder** [comment]
@crazyravenspeep https://github.com/PocketMine/PocketMine-MP/subscription

**Comment by crazyravenspeep** [comment]
I do NOT CARE!!!!

**Comment by PEMapModder** [comment]
@crazyravenspeep if you want to unsubscribe, click that link. If you refuse to, fine, continue reading your emails.

**Comment by caingaroo** [comment]
A nother way to get seeds is to port a pc seed map take everything but leveldat and region file off and put it in worlds but it will lag the server cause its a pc map but its worth a try, i guess
