### ISSUE TITLE
Mac install fails with ./bin/php5/bin/*: No such file or directory

### ISSUE THREAD

**Issue by Raketemensch** [PocketMine/PocketMine-MP#2726]
[3/3] MacOS 64-bit PHP build available, downloading PHP_5.6.4_x86-64_MacOS.tar.gz...chmod: ./bin/php5/bin/*: No such file or directory

I have tried this on both Snow Leopard and Yosemite.

**Comment by cloud9350** [comment]
Retry install
curl -sL http://get.pocketmine.net/ | bash

If you fail install, manually compile the php.
curl -sL http://get.pocketmine.net/ | bash -c
