### ISSUE TITLE
Random speed buffs when walking

### ISSUE THREAD

**Issue by FatalDeath** [PocketMine/PocketMine-MP#2729]
When walking around the player get's random speed buffs, i'm not sure what causes it but it seems to only happen when you're in survival

**Comment by MobileCrafter** [comment]
I think you mean the Fly Protection that causes that.

**Comment by shoghicp** [comment]
Did you try using the latest development build?

**Comment by Sulfatezzz** [comment]
Yes i tested it with the latest Build and it happends random.
