### ISSUE TITLE
players can't join

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2730]
I have server on Ubuntu server 14 and players stuck in building terrain screen always. I tried everything but still same problem. I tried diferent versions of PM diferent maps and diferent config but players still can't join the game!!!!!!!!!!!!!!!!!

**Comment by awesome1029** [comment]
You need to port forward it... -_-

**Comment by PEMapModder** [comment]
@awesome1029 if he didn't, players can't even show the building terrain screen
@Creeperface01 try deleting everything in players/
