### ISSUE TITLE
something wrong pocketmine-soft #238

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2732]
http://crash.pocketmine.net/view/257387

![32151514](https://cloud.githubusercontent.com/assets/8337568/6320670/b2109b88-bb27-11e4-9ec9-ccc4d9b8a2f2.png)

06:24:59 [CRITICAL] Could not tick level world: Trying to get property of non-object
06:24:59 [NOTICE] InvalidStateException: "Trying to get property of non-object" (E_NOTICE) in "/src/pocketmine/Player" at line 1288
06:24:59 [DEBUG] #0 /src/pocketmine/level/Level(515): pocketmine\Player->onUpdate(integer 58316)
06:24:59 [DEBUG] #1 /src/pocketmine/Server(2189): pocketmine\level\Level->doTick(integer 58316)
06:24:59 [DEBUG] #2 /src/pocketmine/Server(2289): pocketmine\Server->checkTickUpdates(integer 58316)
06:24:59 [DEBUG] #3 /src/pocketmine/Server(2175): pocketmine\Server->tick()
06:24:59 [DEBUG] #4 /src/pocketmine/Server(2051): pocketmine\Server->tickProcessor()
06:24:59 [DEBUG] #5 /src/pocketmine/Server(1765): pocketmine\Server->start()
06:24:59 [DEBUG] #6 /src/pocketmine/PocketMine(437): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/root/dereSoft/PocketMine-Soft.phar/, string /root/root/dereSoft/, string /root/root/dereSoft/plugins/)
06:24:59 [DEBUG] #7 (1): require_once(string phar:///root/root/dereSoft/PocketMine-Soft.phar/src/pocketmine/PocketMine.php)

map: McRegion(i converted by AnvilToRegion)
os: CentOS, version: PocketMine-Soft#238

I just updated before.. and some lag here..
(sometimes player speeds are stopped)
i think it's a maybe wrong patch to soft-#238

**Comment by shoghicp** [comment]
This issue is **invalid**. Please follow the Contribution Guidelines and report the issue to the proper repository.
