### ISSUE TITLE
Invisible fire blocks 

### ISSUE THREAD

**Issue by mmlmml1** [PocketMine/PocketMine-MP#2734]
If somebody light fire on some blocks(like stones), it will disappear immediately, but if a player stand on the same location of the fire that lit a moment ago, he or she will on fire. If I put a block at the same location and remove , it will not happen. It will also happen after restarting the server.
World format is mcregion

**Comment by ztdroider25** [comment]
I have this same issue. Water buckets won't get rid of the fire.  I will attach a screenshot of a player in water, but on fire.

**Comment by MobileCrafter** [comment]
PC Servers also sometimes have problems with this. Fire logic in Minecraft...
This was already an issue on 1.3 and talked with shoghicp about that.
You just have to do a short click on the fire and it will dissappear.
If you do a long click on the fire, it will be invisible.
Damn fire logic>.>

**Comment by mmlmml1** [comment]
But the player just light lit a fire and the fire disappeared, without a long click

**Comment by thelucyclub** [comment]
This is not a glitch in PM. This is  glitch in MCPE. It should be fixed in the next update (0.11.0) 😛
