### ISSUE TITLE
Player spawns under the ground

### ISSUE THREAD

**Issue by mmlmml1** [PocketMine/PocketMine-MP#2736]
Player will die again and again...

**Comment by unerds** [comment]
confirmed this one - it happens when using /tp and /spawn...

at first, it seemed to relate to slow chunk loading,  but there are instances where you spawn into an unloaded chunk, and still stay at the proper y dimension until the chunk fully loads.

**Comment by mmlmml1** [comment]
But the player's spawnpoint is under the gruond. This is impossible because using /tp or /spawn can;t change the player's spawnpoint...

**Comment by kevin200** [comment]
Do you mean player into the void？ I will use sign command, when the player join the game, I will tp him.. to me

**Comment by unerds** [comment]
i mean, that when players spawn into an unloaded chunk, they sometimes *fall* a few blocks until the chunk loads, at which point, they're suffocating in blocks.

**Comment by thelucyclub** [comment]
If you have always spawn, try removing it.
