### ISSUE TITLE
unable to connect to world

### ISSUE THREAD

**Issue by divitoDBA** [PocketMine/PocketMine-MP#2738]
Hi, I installed PocketMine-MP version 1.4.1dev-965 on OEL 7.0

Firewall is disable and I verified with tcpdump that packets are being received, but it seems that server doesn't answer them.

Here it goes a captured packet after I clicked "PLAY" button: 

23:37:53.647678 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 53)
    192.168.0.18.48335 > 255.255.255.255.19132: [udp sum ok] UDP, length 25
        0x0000:  4500 0035 0000 4000 4011 79fe c0a8 0012  E..5..@.@.y.....
        0x0010:  ffff ffff bccf 4abc 0021 4f06 0100 0000  ......J..!O.....
        0x0020:  0000 56fc ea00 ffff 00fe fefe fefd fdfd  ..V.............
        0x0030:  fd12 3456 78                             ..4Vx

And this packet is captured after I clicked on my server details 

23:38:29.525472 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 576)
    192.168.0.18.49114 > 192.168.0.107.19132: [udp sum ok] UDP, length 548
        0x0000:  4500 0240 0000 4000 4011 b6df c0a8 0012  E..@..@.@.......
        0x0010:  c0a8 006b bfda 4abc 022c c3c9 0500 ffff  ...k..J..,......
        0x0020:  00fe fefe fefd fdfd fd12 3456 7805 0000  ..........4Vx...
        0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0040:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0070:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0080:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0090:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0100:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0110:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0120:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0130:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0140:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0150:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0160:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0170:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0180:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0190:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0200:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0210:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0220:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0230:  0000 0000 0000 0000 0000 0000 0000 0000  ................

My Minecraft pocket edition is v0.8.1 alpha on Android 4.0

Any suggestions ?

Best regards

**Comment by 64FF00** [comment]
v0.8.1? O_o

**Comment by divitoDBA** [comment]
Using v0.10.5 alpha on Android 4.1.1 has the same behavior.

Packet caputered after I click "PLAY" button:

10:50:54.759813 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 53)
    192.168.0.10.50293 > 192.168.0.255.19132: [udp sum ok] UDP, length 25
        0x0000:  4500 0035 0000 4000 4011 b85e c0a8 000a  E..5..@.@..^....
        0x0010:  c0a8 00ff c475 4abc 0021 4048 0100 0000  .....uJ..!@H....
        0x0020:  0000 0175 8500 ffff 00fe fefe fefd fdfd  ...u............
        0x0030:  fd12 3456 78                             ..4Vx

And this packet is captured after I clicked on my server details:

10:50:59.138716 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto UDP (17), length 1492)
    192.168.0.10.57979 > 192.168.0.107.19132: [udp sum ok] UDP, length 1464
        0x0000:  4500 05d4 0000 4000 4011 b353 c0a8 000a  E.....@.@..S....
        0x0010:  c0a8 006b e27b 4abc 05c0 9a08 0500 ffff  ...k.{J.........
        0x0020:  00fe fefe fefd fdfd fd12 3456 7805 0000  ..........4Vx...
        0x0030:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0040:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0050:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0060:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0070:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0080:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0090:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x00f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0100:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0110:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0120:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0130:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0140:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0150:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0160:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0170:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0180:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0190:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x01f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0200:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0210:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0220:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0230:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0240:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0250:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0260:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0270:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0280:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0290:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x02f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0300:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0310:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0320:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0330:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0340:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0350:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0360:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0370:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0380:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0390:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x03f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0400:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0410:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0420:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0430:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0440:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0450:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0460:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0470:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0480:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0490:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04d0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04e0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x04f0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0500:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0510:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0520:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0530:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0540:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0550:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0560:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0570:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0580:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x0590:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x05a0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x05b0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x05c0:  0000 0000 0000 0000 0000 0000 0000 0000  ................
        0x05d0:  0000 0000                                ....

Any suggestions ?

**Comment by PEMapModder** [comment]
Please contain the payload in \`\`\`... It is a pain to scroll them.

**Comment by jython234** [comment]
@divitoDBA Could you use Wireshark and post a UDP dump on dropbox so we can look at it?

**Comment by divitoDBA** [comment]
@jython234 I found out the cause using Wireshark. It was a network problem, nothing related to PocketMine-MP. Thanks for your suggestion, it was very useful. I'm closing this issue. Best regards

**Comment by jython234** [comment]
No problem.

On Sunday, March 8, 2015, divitoDBA <notifications@github.com> wrote:

> Closed #2738 <https://github.com/PocketMine/PocketMine-MP/issues/2738>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketMine/PocketMine-MP/issues/2738#event-248227987>.
>


--
