### ISSUE TITLE
[Linux installation] No public key.

### ISSUE THREAD

**Issue by hefangdotcom** [PocketMine/PocketMine-MP#2740]
$ wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4 (build 916) using API 1.10.0
[*] This stable build was released on Fri Jan  2 00:36:11 UTC 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Fri 02 Jan 2015 01:18:02 AM UTC using RSA key ID A7837F89
gpg: requesting key A7837F89 from hkp server pgp.mit.edu
gpg: key 33DABBE5: rejected by import filter
gpg: Total number processed: 1
gpg: Can't check signature: No public key
[!] Invalid signature! Please check for file corruption or a wrongly imported public key (signed by 20D377AFC3F7535B3261AA4DCF48E7E52280B75B)

**Comment by shoghicp** [comment]
> gpg: key 33DABBE5: rejected by import filter

Seems like you have filters that disallow getting the signing keys. You can do it manually via https://www.pocketmine.net/keys.html or download the development release
