### ISSUE TITLE
Massive Tree Generations.

### ISSUE THREAD

**Issue by iVertx** [PocketMine/PocketMine-MP#2745]
Hi
I'm facing a very strange error in my server and i need help or fix for that... Basically for a unknown reason, pocketmine is generating trees in every grass block in some chunks im my server:
![screenshot_2015-02-28-11-14-00](https://cloud.githubusercontent.com/assets/10237969/6428206/1d135fc0-bf78-11e4-88c2-c86ae29d6810.png)
![screenshot_2015-02-28-18-19-33](https://cloud.githubusercontent.com/assets/10237969/6428207/2f933a80-bf78-11e4-965b-c1e4d1cea1d6.png)
But the more stange is that:
![screenshot_2015-02-28-18-23-30](https://cloud.githubusercontent.com/assets/10237969/6428212/45063ce6-bf78-11e4-9b52-65a98b15617d.png)
(Some chunks are bugged with tree walls, and others are fine! Wtf? And yes, there are corrupted chunks in this screenshot how you can see)
And it are destroing my buildings...
![screenshot_2015-02-28-18-26-58](https://cloud.githubusercontent.com/assets/10237969/6428223/a3df84a2-bf78-11e4-91bd-324d3d24e853.png)
I'm using latest development build, and already tested with stable and soft and a reseted flat map generated by pocketmine itself... My pc map also have this problem and it's a very bad error for my server... Sorry for my probally bad english and hope anyone can explain me what the hell is going on in my maps, thanks

**Comment by Lucario2** [comment]
What did you do? did u edit something?

**Comment by iVertx** [comment]
Nope, it's a bug... I got this trees only in some ramdom maps, when i restore a previous un-bugged map backup i got trees in another one... I simply don't understand what this happens... But i found a temporally solution =  replaced grass blocks with green wools... (--')

**Comment by shoghicp** [comment]
Could you send me your world files, and list of plugins you are using?

**Comment by iVertx** [comment]
Here you go
https://www.dropbox.com/s/e7zhdumb7d1wgjt/Maps%20and%20Plugin%20list.zip?dl=0
(I'll remove this link soon)
Inside this zip you got my Bugged Wotld files and plugin list.
I can't send for you my most recent World file, because it's on a VPS, and i can't download anything from there yet, 
But this worlds can show you how is the bug.

One more thing, my most recent world have more than 12,000 mcr files with 4kb, i think PocketMine is generating McRegion files for every new chunk generated...
![img_20150314_161859](https://cloud.githubusercontent.com/assets/10237969/6653269/4b162578-ca69-11e4-8e14-8879970a2630.jpg)
Is it normal?
Thanks.

**Comment by Kadin15** [comment]
May I ask exactly who is this? Is this falk?

**Comment by shoghicp** [comment]
@Kadin15 you are subscribed to email notifications on GitHub. https://github.com/PocketMine/PocketMine-MP/issues/2745

**Comment by shoghicp** [comment]
@iVertx Seems that your issue is related to the plugins you have installed. I could not reproduce this with your world data.
Also, the high number of regions is due to the plugins. This same issue got reported and was caused by plugins not being developed properly.

**Comment by iVertx** [comment]
Hum, i'll investigate if really is my plugins that is generating huge ammount of files, but about trees, i already tested without plugins and got the same error... Go to position 78 68 155 on world PCBR, is the same positition where i take the first screenshot. 
In this place you can see massive trees, try to cut off some trees and go far, when you return, the trees will be reborn...

**Comment by Lucario2** [comment]
Hm............ i really want a plugin like that!! can u tekll me this bug i want it for my server andf if its a plugi n tell em which one i wanna have it!

**Comment by iVertx** [comment]
It's not a plugin, i confirmed that myself, the massive trees happens without any plugin on folder... I reproduced this issue on my old map by restarting and restarting the server few times, I got huge ammont of trees in just one region of map, probally a issue of the map itself, but on flat worlds it happens in every place, so, pocketmine issue, i think... And for huge ammount of files, I don't found the root of problem, i found that really is a plugin problem, i confirmed that, but when the plugin starts to generate this huge ammount of files, the pocketmine still doing the same thing after remove all plugins... Now my world folder have 16511 files and still increasing this number... But i don't know what is the bugged plugin

And lucario, please improve your grammar, english is not my native language, so, is a little bit hard to understand what you're trying to say XD

**Comment by iVertx** [comment]
Plugin that causes the huge ammount of mcr files problem is EssentialsPE... I tested all my plugins one per time to see what is the bugged one, and i confirmed without any trouble that is EssentialsPE the plugin that cause this worlds issues..  @iksaku see that

**Comment by iksaku** [comment]
EssentialsPE isn't related to this issue, it doesn't have any *working* piece of code that generate trees, the command that generate trees is not enabled and doesn't even work, so is not EssentialsPE's fault :P

**Comment by Lucario2** [comment]
Actually. You think you know it? SORRY BUD! It is actually EssentialsPE fault. There is a little bit of coding in it that has massive tree generations, and something is apparently messing with it.

**Comment by iksaku** [comment]
Yes, I should know it because I'm the developer of EssentialsPE xD anyways, the "tree generation" code just available when you execute the "tree or bigtree" commands... That are not available in anyways... Even if you edit the code and get to enable the commands, they just still don't work xD
