### ISSUE TITLE
Death On Join

### ISSUE THREAD

**Issue by thelucyclub** [PocketMine/PocketMine-MP#2746]
When players join my server they die and lose all their stuff. I am running PM-Soft API 1.11.0 For MCPE 0.10.5

**Comment by Subtleoliver** [comment]
I dont know if this is pocketmine. this happens in singel player.

**Comment by thelucyclub** [comment]
I removed all plugins. Still happens. But I am using MCPE 0.11.0 DevBuild #937

**Comment by thelucyclub** [comment]
really... Closed without an explination.
