### ISSUE TITLE
How to import world (iOS,MineCraft PE 0.10.4,Single Play) to PocketMine-MP?

### ISSUE THREAD

**Issue by zxl777** [PocketMine/PocketMine-MP#2749]
How to import world (iOS,MineCraft PE 0.10.4,Single Play) to PocketMine-MP?

./world files

level.dat
./db:
000005.ldb	000084.ldb	CURRENT		LOG		MANIFEST-000083
000082.ldb	000085.log	LOCK		LOG.old

**Comment by Intyre** [comment]
Please use the [forums](https://forums.pocketmine.net/forums/) for questions.
