### ISSUE TITLE
Large LevelDB World Out of Memory Crash - Every Time

### ISSUE THREAD

**Issue by bgbrandongomez** [PocketMine/PocketMine-MP#2752]
I have decided to import my survival world I made during the 0.9.x series of Pocket Edition and liked how the levelDB format world loaded without issue.

Well, I found out when the server is stopped and reloaded, a large leveldb world such as mine will crash the server before even loading the visual part of the world every time I try to visit it. It was my first survival world, so I tried to fix it to no avail by using methods such as increasing memory (which only caused my computer to freeze if I increase the memory high enough to stop the server from reaching max), putting a cpu limiter on the process (which did nothing), and even reloading the world directly on the device and copying it (which only proved that PocketMine for some reason does not like it, but my phone can handle it just fine).

I have a crash dump that was auto submitted located at http://crash.pocketmine.net/view/402777 and my world is located at https://drive.google.com/open?id=0B7pkAMl3n7uhQ0dvMEVWb1ZQS2s&authuser=0

This is a bug that I know is specific to large worlds, because I tested a newly created world from my phone and it worked fine (except for, it adds new chunks with the PocketMine generator, but that is not a problem).

Thank you for looking at this and if you have questions about my data or want more, please contact me through GitHub.

**Comment by bgbrandongomez** [comment]
Also to note, using an alternate version of my world, when I get timeout issues or disconnect, sometimes all torches in a surrounding area will break and leave item drops that cannot be picked up. It is weird to get item drops when I am the only one on and am in creative mode. However, that is just a weird, random, event I noticed and may or may not have anything to do codewise with this issue.

**Comment by bgbrandongomez** [comment]
It appears that other small 5 megabyte worlds can cause the crashes too. It just takes longer to develop the problem, but once developed, it happens every time the world is loaded. That is apparent in some of the worlds located in my public world folder located at https://drive.google.com/folderview?id=0B7pkAMl3n7uhQjFXMHRTeGxDMjQ&usp=sharing

**Comment by shoghicp** [comment]
Seems like this was a problem due to entities duplicating in levelDB worlds. I pushed a patch a day ago that can fix this.

**Comment by AndreyNazarchuk** [comment]
@bgbrandongomez You store worlds online and multiple servers can access them?

**Comment by bgbrandongomez** [comment]
No, I could only access them from my computer as I had it as a single server setup. I am sorry that I don't remember much, it has been so long since I have played pocket edition as I now use Spigot and play PC edition.

**Comment by AndreyNazarchuk** [comment]
Ok, thanks

**Comment by shoghicp** [comment]
This is not a forum. Please follow the Contribution Guidelines or you may be blocked from this organization.
