### ISSUE TITLE
Blocking players randomly

### ISSUE THREAD

**Issue by diamond-gold** [PocketMine/PocketMine-MP#2753]
1. For some unknown reason all players use the same ip as the host machine, anyone know why?
2. Server blocking players randomly with following message:
**(ip) is the same for all players**
19:31:17 [NOTICE] [RakLib Thread #6084] Blocked (ip) for 300 seconds
19:31:27 [INFO] iyee9098 退出了游戏 !
19:31:27 [INFO] iyee9098[/(ip):62591] logged out due to timeout
19:31:27 [INFO] Gamepp 退出了游戏 !
19:31:27 [INFO] Gamepp[/(ip):50074] logged out due to timeout
19:31:27 [INFO] soonhang 退出了游戏 !
19:31:27 [INFO] soonhang[/(ip):4371] logged out due to timeout
19:31:27 [INFO] TheJN 退出了游戏 !
19:31:27 [INFO] TheJN[/(ip):46000] logged out due to timeout
19:31:27 [INFO] Jnzhxxhs 退出了游戏 !
19:31:27 [INFO] Jnzhxxhs[/(ip):49193] logged out due to timeout

Is there a way to fix this? Or is there a option to turn the blocking off?
Thanks in advance

**Comment by PEMapModder** [comment]
The RakLib block is because client sends incorrect data.
This is not a support channel, and what you're reporting is not a bug.

**Comment by diamond-gold** [comment]
Ok, sorry about that. May i know where should i seek help about this issue?

**Comment by Falkirks** [comment]
@PEMapModder If RakLib is blocking legitmate packets, this is a bug.

**Comment by sekjun9878** [comment]
Sounds like a RakNet issue. Please report this issue here https://github.com/PocketMine/RakLib/issues.
