### ISSUE TITLE
Server not using all allocated ram

### ISSUE THREAD

**Issue by Midnight-Shadow** [PocketMine/PocketMine-MP#2754]
My pocket mine (latest beta build to date), is allocated 7 gigs of ram (7168 M), but the console only uses 50.7 megabytes. I've reinstalled, gotten rid of plugin, generated new world, but the problem persists. The world generation is little to none, but I assume that this is due to the server only using 50 megabytes -.-

I apologize for bad English.

**Comment by Intyre** [comment]
Why would you want the server to use all the RAM? It uses the RAM when it is needed.
