### ISSUE TITLE
Server not allocating ram [EDITED]

### ISSUE THREAD

**Issue by Midnight-Shadow** [PocketMine/PocketMine-MP#2755]
My pocket mine (latest beta build to date), is allocated 7 gigs of ram (7168 M), but the console only uses 50.7 megabytes. I've reinstalled, gotten rid of plugin, generated new world, but the problem persists. The world generation is little to none, but I assume that this is due to the server only using 50 megabytes -.-

EDIT: The server load stays at 100%, using 50.7/50.7 M constantly, the number not going ups.i apologize for not being clear. 

I apologize for bad English.

**Comment by Midnight-Shadow** [comment]
And don't close my issue without giving me a chance to respond. I wasn't clear, and if you asked, you would've gotten more information. The server, is NOT allocating the ram like it should be, and I am having a problem.

**Comment by jython234** [comment]
@Midnight-Shadow It happens for me too. Your computer does have that RAM available correct? Try using lower values and see what happens. In fact, even when allocating 256MB of RAM, It ends up having the max of 27MB.

**Comment by jython234** [comment]
@Midnight-Shadow What is the TPS rate? Also, what specs for your computer?

**Comment by Midnight-Shadow** [comment]
Oh, my computer can handle it. Core i5, 16 gigs ram, windows 8.1. I'll try
using lower values, and what is a TPS rate?

**Comment by jython234** [comment]
In the console title it should say "TPS".

On Thursday, March 5, 2015, Midnight-Shadow <notifications@github.com>
wrote:

> Oh, my computer can handle it. Core i5, 16 gigs ram, windows 8.1. I'll try
> using lower values, and what is a TPS rate?
>
> On Thursday, March 5, 2015, jython234 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > @Midnight-Shadow <https://github.com/Midnight-Shadow> What is the TPS
> > rate? Also, what specs for your computer?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/PocketMine/PocketMine-MP/issues/2755#issuecomment-77387743
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketMine/PocketMine-MP/issues/2755#issuecomment-77397937>
> .
>


--

**Comment by Midnight-Shadow** [comment]
The TPS rate says 20.

here's my serverr.properties:

#Properties Config file
#Tue Mar 3 17:16:30 ACT 2015
type=0
server-name=Minecraft: PE Server
server-port=19132
memory-limit=7168M
gamemode=1
max-players=20
spawn-protection=16
white-list=off
enable-query=on
enable-rcon=off
motd=Minecraft: PE Server
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
rcon.password=blahblahblah
auto-save=on

**Comment by jython234** [comment]
@Midnight-Shadow It's a PHP issue I believe.

**Comment by Midnight-Shadow** [comment]
I think I fixed it...
goto "Your server files"\bin\php\php.ini
and find 0memorylimit = 256M, and change it to something else like 1024M
