### ISSUE TITLE
server not starting [EMERGENCY]

### ISSUE THREAD

**Issue by awesome1029** [PocketMine/PocketMine-MP#2756]
Okay so when i started the server it worked and then i stopped it and edited what simple auth said and then it said...[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 16:07:23 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 16:07:23 [WARNING] Non-packaged PocketMine-MP installation detected, do not use on production.
[Server] 16:07:23 [INFO] Starting Minecraft: PE server version v0.10.4 alpha
[Server] 16:07:23 [INFO] Loading pocketmine.yml...
[Server] 16:07:23 [INFO] Loading server properties...
[Server] 16:07:23 [INFO] Starting remote control listener
[Server] 16:07:23 [INFO] RCON running on 0.0.0.0:19132
[Server] 16:07:23 [INFO] Advanced cache enabled
[Server] 16:07:23 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 16:07:23 [INFO] This server is running PocketMine-MP version 1.4-916 "絶好(Zekkou)ケーキ(Cake)" (API 1.10.0)
[Server] 16:07:23 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 16:07:24 [ERROR] Could not load plugin 'ServerKits': API version not compatible
[Server] 16:07:25 [INFO] Loading mcg76_BasicPerms v0.7.0
[Server] 16:07:25 [WARNING] RuntimeException: "yaml_parse(): end of stream reached without finding document 0" (E_WARNING) in "/src/pocketmine/utils/Config" at line 137
[Server] 16:07:25 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 16:07:25 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Thu_Mar_5-16.07.25-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
now im realy sad because i took the time to portforward and everything... i love your mods, and thanks for reading this <3

**Comment by Falkirks** [comment]
This is **not** a support forum and this is **not** a bug. The config file for `mcg76_BasicPerms` is invalid.

**Comment by awesome1029** [comment]
Yay thanks for noticing! <3 I fixed it thanks to you, idk how to thank you! Do you wanna join my server now?
