### ISSUE TITLE
Raklib Crash report

### ISSUE THREAD

**Issue by McDrakon123** [PocketMine/PocketMine-MP#2759]
PocketMine-Soft Crash Dump Fri Mar 6 16:57:51 UTC 2015

Error: RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use
File: /src/raklib/server/UDPServerSocket
Line: 32
Type: error

Code:
[23] 
[24] class UDPServerSocket{
[25]     /** @var \Logger */
[26]     protected $logger;
[27]     protected $socket;
[28] 
[29]     public function __construct(\ThreadedLogger $logger, $port = 19132, $interface = "0.0.0.0"){
[30]         $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
[31]         //socket_set_option($this->socket, SOL_SOCKET, SO_BROADCAST, 1); //Allow sending broadcast messages
[32]         if(@socket_bind($this->socket, $interface, $port) === \true){
[33]             socket_set_option($this->socket, SOL_SOCKET, SO_REUSEADDR, 0);
[34]             $this->setSendBuffer(1024 * 1024 * 8)->setRecvBuffer(1024 * 1024 * 8);
[35]         }else{
[36]             $logger->critical("**** FAILED TO BIND TO " . $interface . ":" . $port . "!", \true, \true, 0);
[37]             $logger->critical("Perhaps a server is already running on that port?", \true, \true, 0);
[38]             exit(1);
[39]         }
[40]         socket_set_nonblock($this->socket);
[41]     }
[42] 

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(154): pocketmine\network\RakLibInterface->doTick()
#1 /src/pocketmine/Server(2281): pocketmine\network\RakLibInterface->process()
#2 /src/pocketmine/Server(2175): pocketmine\Server->tick()
#3 /src/pocketmine/Server(2051): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1765): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(437): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#6 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1dev #239 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20-g61ca73f #1 SMP PREEMPT Tue Jan 6 16:42:38 GMT 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
ChatBubbles 1.1.7 by Comedyman937 for API(s) 1.0.0, 1.1.0, 1.2.0
EssentialsPE 1.0.2 by LegendsOfMCPE Team for API(s) 1.9.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
BigBrother 1.5.0-beta by shoghicp for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWVtz27gV/iuokpnaGVEidbcy2q5iO6lbO1FtZfIQZTwQCUpYUySXAG0rO/nv/Q4ASZQdby59
6cMq8YgEDs79Cv1R03IlasOg0+r2eoHfD+q1hCt9WhRZURv+UdPrHNs1Yd7rtZVQii9o5ZLfnMs5
my4LwSMWFlwtRcQ+FvwmkfPZTIniVhSz2fuTyZV5vMrCG6E/DZkyD9dzmUYHh0NWpnyeCKYzRiuM
R1EBGuzj0QCwY/cmU1YqAfpxmSSvZUIM5EteDJvNptJZAZaaYlUmXIuo6TcnhsSFTEXl0buYNOhM
UxVh07LZtFw2HzAJsJxoWTrfhgdsAgK1YbtVr+mCh3j8WHvmM3M0NzArYiYV+i4rbppWd2epFkUM
6IOg24EmdoCzmYOczR6Aer9E2VSGNweHIPoseETBsnXQag2C78aYF1kIJVuUrSdRBv3uA5R2x/tF
bxlqP3na7wZ/cnpiWcgKi6bzFJqg33uKCaV5oe3x7qPjOy846LT7T2C4vg6zVOmiDPVBdf84W+Vc
S3jpMUJDnWc8EgXL5r+JUNf3MJVaJmo2u+AyPc8WiwoU0Mp0wX7aZ7cYvnH0e+HypFzIVDWNvnrs
gIxTiN9LWYiD/5XXJ3VPcXVY+/Sl7tLJ/2F6+YmQhzhWm7VhzBMl6rUwiwQJ12oDFyBbHXyH5Dvs
AZo/aLeLXYZP88UL9ustL9hs5rznRZP2e24fcarhTFDD88Tsv6Td/uNdqwKzO3AcHG2gynkiQxaX
aahllrKqz89mVtsicuQdmTp7nmeFZiMWHAVIcey53CQPrM1qfsP8m9UOSZy270jR57leSoXYNAwB
2BknBBktDsavr8/enk7r7Ord8b+vT95cji/o+fwaWjok9ttBBRc80Z5W+MtyYv9gD789S7gszutX
l+/GJ8fjK7wFhy+BYJwk2R1TIo3IwecFIjlEsWPO7RSRbFVIyvjg16o/PSC304NT0SEbjaCRGfQp
rDLaFWz0+VERLk/fX52OT04u68y3Kuk8wLg5L/QV5HpVxjHlSb/VYS+Y+xocmv1LEd4+sW8wdyuY
vwh4spGg95CedQrvl7CQSN08OZjVXuDDXo/Pzk9P2PQde3X21nzPaqxRdZYGVoZ20TgUvf9tVqs7
je2+naj97yA9EcWS54pxZgOVSTwn5MZrVpRpSoaGn+sl14yI/uNP6A0e0BP3UiMzmr2jqnKw0Km6
ecWqaZbOE7zu29Xg6Gy82ZwnP6t9+atf+Ktf+Ktf+PN+oV5biFQUPKGaCs0rpE0ET9DoNIJI3IKj
eSmTqDZstY9Qi1EHszADcMuv13guDWgQNHwALqTGq/+dHxywTQCdafQNBvQTNC/VzmVa3jNEOk+W
GUpIuxH4jZbvLXpByPvtmCHYri4mbHJ5enoxmbJpKdi/eMp6LOgNO61he8DeXExZyw+6jBer234C
5DR3DGvdRq/Rwttn5HO8tvDq283rTG1IY8G88DQqMhnVtl2IIi0dI929KudwQfPqeK6u1vc0GTT6
WOGlXmaFomQEHxbResXTI2ThT06PHwHpG17ohP1u4Rv7wrRZYNck1FokcjBPmLCnslifVBdWnJql
Kjs2BqipQrBga/Luavrh3eX5CZbuxFxJDf5TzH4Q81ShgGuJVmtyWhFub3lfOt+osyLduVgQN+/i
i+PJKZsKvtqT8ejnZapyQW0chf43xKottc4VIgfOuSznjTBbNS2Dlr/mnmRQwIlUi1IqcSEq4lcW
K8LDTnuCv+bJjSxu1J64vZ8XN3JUV0hmexx8hx2v5CpPxBjMVcSoLO7b0MZARZRdmrAGBJPLbLGU
Yb4n3ODnhdvxgpxf5csJdzUdX07fT75ly0ryq2CBAl7JxSskq6UoKgqoLO4roNvwvbnQfF8LX5U5
8H9U6KredwrYIJ/NdlxVn39YFRuEzQqOL5S5eAHp0WBsmDMVtoFUnotCS0pitWeT7Rs7ztJYLhhN
a7Nilj57XUh2gcHJJNduf9jps/fTY5NcaX+V6WhEBsAYGeshQ8zbGk6blpZHveHIzDfmhFhlxdpL
5ErqUdf3L2jxbgnBsKb0KItjWuFpmmGSEl6e8DWQ8HApxS2iIdVqlKUGfc7vUs8NZ7DlKOgZAvze
HVKjlm9w0WzixYlcLLf47WGeyhWCfw/hKptvFhacuI3EyKCJswL8bNccIpTZKMyK7Xt+m7vTkYxj
GZaJXo8Cg82UWpRwD92sRl1XI1pOIFbikY+O0BUm0W5NCRFVQGigH52cvh6/P5/SqvVB7/dSFGtH
0i0V6J42/NBzI0ezBOTR6IX5QCWlzjzFb8VGdGsqw8VT5jRGqtooEgrjgpm1RhaMrZCVMfBT07LX
jlRoGDHSrIDijWyYEr0yj9DPbPDeSnHnIf9pDgcYGaNSkd72MY31KiG3ZVTZWGg8toRmaeomx2Ww
VJX8FQISrsymS6EE2ygfvYHA8CIww8DvzRQTktdpNhdMpmFSYlyn+4tHIUO4rlDFWRYTgoc4FY8x
+JgQVIQS07DgN2ydlcV2kooZfEjG0lCA+xRw4WQ9S0lLFtVwBsrLUkcZ+aSdooeY6pyiwyRTIprV
APXMzt5kGdMs2l6F3UrO/kO+ARDjI57bGTJKWnTwaolznDSoMqjNUWF3S5Fi2YLT9Y1iSHBgkXpO
Np6cARJpMoIiKhse2JqDqR36U3tB5PCgnWIUKHSdAiuZa4I1zsccIQJw57vb3S0eHt2SI0ReiCSw
Q1/mae7B0ncIQANuroiMWJR6QS9L16usVOjD4RtQTqjossrekEAsErUQlJ1IELq68Eqr5Y0Ab8vV
nCaHmI3VOg2nXN0wmtxgWNr+ML58e/b2zRCOhdH4TiYJGRPo4RGLJJvzhNlsZ4nV2bzUTGqgSP9u
vIxMZn2M/FBnmicNEpiIeY7QkAXkFpGYlwvyiWdnMfuFBXWDiEgqMqLZ3l62bDA6w+KUySAG1cYs
iuYSrkuSBAUE/Wi09YxdAtr54jNEz8ZaFGArxIsJGgPqxIevWO+xSo6Mg5gjnj0yZCtsLRCpThR7
SwBG4T1asbjIVnC9Kn6oloJSV8jDivoxN4h+qpnGcO+mp84s+B+WiK8U8WUQmXJMdcSw5yhv2XNO
NEvDZZneeO5CyyhgDGdKNXmD2VPkMoYXV20Y0gOjERrAOSU6PDqV09xK16GUoYy+SFORVdXmzswi
bbB/okwB0QgZAsFyPHlfxxGl2BwWupORXlpvsmbbYPWcgQdPM8oLrEZMIIgcx4ClYmmBhqzV7e0E
J+Y3gl/we8Yf4nRXFcJhfCS3TycveSQRgLtTjgnuODCWtCfpyysM/JB1fsyIprK7IqJ2iSBMBLfs
mNbikXFdQYb6jJgfloJyNvFUlDaAdhDkXZxRSReFMbu9PUehySwoNXZulZC92Z00kUHRTlZcJFKH
y/VXTtn0YIATvjDWJ0TvTTHVNsPA+DHdqm5bCaMaJGAEMNzIKIOiyrWndRcmkbSpuyKO43/F1+AL
1ckmqplJ955JQJWECgdoPPYA6MkhFFvXR91LYSIqwF9BtBcVWyuEQ7sls8iTqQGAEXu+TzDmzcMu
Adl2zTN9GnkJgUBRKbJosV2lgKP2hrobg4aATOnwyCHSMh+yI4vcNnymFTU5boMLWPp0yhEkpF16
veNEaLto1vhqLuEQFsQ1VraqDDe1yP7Gsqk1RjkuemDabeWLtnXHlCL6pWN/ZZuN91bzZS7Rmu6U
THcmQ0uyUemZUqG3/NlIMSp9SBupxO4OrcBF6rkqsgWxq1m+Y8SSvLu7+xrBRKIe2hJyes8pbu0L
1S24pxvEhsw9mC2YTukMhvpIjx4aeLpNy/JPhNF0yduaVO2+TPBkQFTISFQDOKPOS3+1mTN9iZkQ
lCkfFG0rVBUJRl1tq7BuqBoGzBOjFp0c0SSsHbUhe30+ng5bL/v17tF9UG/ft+utl8HLCJFqA/BA
FwIviKjRwGcLWEvZt0730LS74l6LlBRib52QDSr3V2SgyitS0mL7E1keEqh7Ub8j34i2vWXz7JXe
Z3vt1jJj/zxE2Vvufl/jCZyKF7sF+zPi5q0sku0L2jRNAzZQuzvAWOfb3cVq97yEL9rrIgD9ptzY
3WoE9Lvk3F5yboHRIKxzvZMAUwAYiiriXk3ODVV6zkPUhN3ZNQQ2V3vuiWG2B3ckOfNoam35Xb+N
x+dnsFvc7rcF70ZRt9se9HtBx+/xgd9q8c58wNv9TicYzFsdX7DnoDRZklpIbZZwpuT9Tuk2nyoH
EJCglyJO7GSKVUNvILpxiAkp7oCsH/f7YX8w6HW7IN0+arVF258f9Y+iyNBTy1W2U6H9sUPtSyqt
8gGssxuRys8bc2DlA7J6IWKrqEYXK2tuxia6YCSAzzK3b61Gp/bly38BqaiuVQ==
===END CRASH DUMP===

**Comment by jython234** [comment]
@McDrakon123 Another server is using the UDP port 19132. Close all your other pocketmine servers, or change the port pocketmine runs on.

**Comment by thelucyclub** [comment]
1. Go open server.properties
2. Locate the "port" option
3. Change the port to something other than '19132'. PORTS MUST BE 5 NUMBERS AND NO SPACES!
4. Restart server
5. Thank @TheLucyClub for their help.

**Comment by jython234** [comment]
Your users will also have to know the port the server is running on.

On Tuesday, March 10, 2015, thelucyclub <notifications@github.com> wrote:

>
>    1. Go open server.properties
>    2. Locate the "port" option
>    3. Change the port to something other than '19132'. PORTS MUST BE 5
>    NUMBERS AND NO SPACES!
>    4. Restart server
>    5. Thank @TheLucyClub <https://github.com/TheLucyClub> for their help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PocketMine/PocketMine-MP/issues/2759#issuecomment-78142228>
> .
>


--

**Comment by PEMapModder** [comment]
This is not a support forum. Please go to the help forum if you want to get help _or if you want to find someone to help_. Support should not be provided here.

**Comment by thelucyclub** [comment]
It could also be you have your IP set to something incorrect. In server.properties make sure IP looks like this: `ip=0.0.0.0`.

**Comment by jython234** [comment]
@thelucyclub Actually ports can be one number or two numbers too.

**Comment by thebigsmileXD** [comment]
I just made it in ClearSky that the server's machine address will be used instead of 0.0.0.0
We'll test it, if this works fine, i'll create a PR
