### ISSUE TITLE
Pocketmine very laggy

### ISSUE THREAD

**Issue by Lucario2** [PocketMine/PocketMine-MP#2760]
Hi my pocketmine is very very laggy. i have a 3.2ghz computer with 12gb of ram it uses around 300mb of ram and only uses 32 percent of ram. and uses around .5 mbps of internet. My internet is 75 mbps per second. I Tried to get pocketmine to use more cpu power from all cores by clicking minty on highest priority and php on highest priority and console window hostx32 AND terminal ALL on highest priority. (yes, the affinity is all on cores for all the processes)
Result: Nothing absolutely no differnce. 
I tried all the ways to get pocketmine to use more cpu power.
I even did a computer torture test. It used 90% of cpu and boy It was going through the threads at LIGHT SPEED. so if anyone can help me please, HELP ME!!!

**Comment by iVertx** [comment]
Go to your pocketmine folder and tweak your server.properties and pocketmine.yml, on server properties, increase the memory limit... In pocketmine.yml tweak this lines:

[CODE]
 #Amount of chunks sent to players per tick
 per-tick: 2
 #Compression level used when sending chunks. Higher = more CPU, less bandwidth usage
 compression-level: 8
 #Amount of chunks sent around each player
 max-chunks: 56
chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 50
 #Radius of chunks around a player to tick
 tick-radius: 2
[/CODE]

This is my pocketmine.yml, my computer with only 4 gb of ram is running the server with 120 slots very well with this cfg, but if you increase so much like this
[CODE]
#Amount of chunks sent to players per tick
 per-tick: 16
[/CODE]
it will make your server slow down and stops from loading chunks with less than 10 players...

**Comment by Lucario2** [comment]
I meant 32% of cpu power not ram

**Comment by iVertx** [comment]
I know, For example, increasing this value:

#Max amount of chunks processed each tick
per-tick: 50

To 256, 512, whatever, will use more cpu power, this is the main option for use more power from cpu... Anyway you need to tweak your pocketmine.yml...
