### ISSUE TITLE
Rails, paintings, spawn eggs, and most flowers cannot be placed.

### ISSUE THREAD

**Issue by MrSteave** [PocketMine/PocketMine-MP#2768]
Rails,powered rails,most flowers,paintings,and spawn eggs cannot be place inside of a creative server.

**Comment by MrSteave** [comment]
I have not found a solution in changing any settings in the app or within PocketMine files.

**Comment by Calrizer** [comment]
All the above items cannot be used as there is no api in place for the minecart and mob entities, so PocketMine simply blocks them from being used.

**Comment by Creeperface01** [comment]
Use pocketmine soft and you can use flowers, color fences, bone etc

**Comment by matcracker** [comment]
#2910
