### ISSUE TITLE
Armor damage protection is not proportional to the damage value

### ISSUE THREAD

**Issue by matcracker** [PocketMine/PocketMine-MP#2772]
Version: PocketMine Development build 1.4.1dev Build 972 (Last Build)
OS: Windows
Problem: On PvP the bow with two shot kill players with any armor... Can you fix it?

Thanks a lot!

-matcracker

**Comment by PEMapModder** [comment]
Actually, PocketMine needs better implementation for armor. Right now armor protection is constant, rather than proportional to the damage value.

**Comment by mahboi** [comment]
Is anyone currently working on that? I may do it myself.

**Comment by matcracker** [comment]
I don't know

**Comment by mahboi** [comment]
Unfortunately, me and my good friends bash, grep, cat, and nano couldn't find where it does the calculation. Does the client calculate it?

**Comment by sekjun9878** [comment]
Please see #2786.

**Comment by matcracker** [comment]
Thank You! And thank you @PEMapModder ! But I wait an official release, I think the next release will be 1.5 and not 1.4.2 xD

**Comment by shoghicp** [comment]
@matcracker That depends if I have enough time :(
Getting a release out has to be done after work, and sometimes it takes pretty long :P

**Comment by matcracker** [comment]
Yes, I know it :) Don't worry @shoghicp, good work! :D
