### ISSUE TITLE
Ubuntu Linux setup in terminal

### ISSUE THREAD

**Issue by kestrelfalconry** [PocketMine/PocketMine-MP#2775]
So i have tried for what feels like a million times to get this server set up on Ubuntu Linux 14.04 LTS, and to no avail, i have had no luck whatsoever, is there anyone out there that can help?

**Comment by Intyre** [comment]
Please use the [forums](https://forums.pocketmine.net/forums/) and [read the docs](http://pocketmine-mp.readthedocs.org/en/latest/)
