### ISSUE TITLE
bug with map folder

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2781]
when folder name is diferent then level.dat name so map works bad on pocketmine: 
1. players spawn on main spawn always
2. plugins cant load data on this map so /home etc doesn't work

**Comment by sekjun9878** [comment]
Could you please clarify how this is a problem? By convention the folder name should be the same as the level name.

**Comment by Creeperface01** [comment]
But when i rename folder so players spawn on main spawn always and others.
