### ISSUE TITLE
Could not tick level plot2 (World)

### ISSUE THREAD

**Issue by LifelessPanda** [PocketMine/PocketMine-MP#2782]
When i try to enter this world with signportal it drops me into the void and then instantly bans me... I just got the new update today and this is when it started happening.. There is also another bug where it deops players like every time i restart server or sometimes when the op leaves the game... If you know a solution please help me

More info on 'Could not tick'
the exact message it says is ... [CRITICAL] Could not tick level Plot2: Object of class pocketmine\inventory\PlayerInventory could not be converted to int

And these occurs in all flat worlds...
I am running the server on a windows 8

**Comment by Creeperface01** [comment]
This issue already exist
