### ISSUE TITLE
Snowballs deal too much damage when thrown against players

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#2783]
As for the new PocketMine update, snowballs have become very glitchy. They have become very OP as they now deal multiple hearts of damage. The damage is different for each armour type you wear (they are not in correct order of damage, like diamond actually receives the most damage from snowball impact). 

This has started in the new stable version released on March 17th (PocketMine 1.4.1)

**Comment by peepzandmeepz** [comment]
The damage from snowballs I'm talking about is when a player through one and it hits another players.

**Comment by PEMapModder** [comment]
This applies to most damage tyeps other than normal PvP. This has been confirmed and is being fixed.
