### ISSUE TITLE
Bugs I've encountered so far.

### ISSUE THREAD

**Issue by ERR404** [PocketMine/PocketMine-MP#2784]
-When players go into another world they are immediately taken down to void
-Placing signs crashes your game
-When players fall into void they get banned
-Some people can't do /home anymore; may be because of new api
To be continued...

**Comment by PEMapModder** [comment]
-that's because of lag
-that's MCPE bug
-are you using hardcore? are you sure they are "banned"?
-we do not support plugins here. /home is a plugin command and not supported by PocketMine foficially.

**Comment by Creeperface01** [comment]
Home maybe doesn't work because (my new issue: bugs with map folder)

**Comment by Creeperface01** [comment]
And falling into void can be fixed like in PC servers.
