### ISSUE TITLE
Chunk at 0,0 not loading in Flat worlds

### ISSUE THREAD

**Issue by alejandroliu** [PocketMine/PocketMine-MP#2787]
Apparently Chunk at 0,0 does not load from file properly.

Can be modified and while in-memory seems OK and event gets saved correctly.  After unload, it doesn't get loaded and it gets re-generated.

**Comment by alejandroliu** [comment]
To recreate this issue:

- Create a flat world.
- Place stuff at Chunk 0,0 (teleport to 8, 64, 8).
- Re-start server.
- The stuff at Chunk 0,0 is gone.

**Comment by PEMapModder** [comment]
:+1:

**Comment by alejandroliu** [comment]
This can be closed, as the fix in "Clone initial chunk in Flat.php #2788" has been merged.
