### ISSUE TITLE
[ERROR] Pocketmine API error

### ISSUE THREAD

**Issue by sigbinium** [PocketMine/PocketMine-MP#279]
What error is this pertaining to? The configs? or world?
Last time I started the server, it had no such error.

**Comment by StringerJ** [comment]
Error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 150994944 bytes)
File: /src/pocketmine/Server
Line: 1644
Type: E_ERROR

Code:
[1635] 			Server::$sleeper->wait($ms);
[1636] 		}, $microseconds);
[1637] 	}
[1638] 
[1639] 	public function getExpectedExperience($level){
[1640] 		if(isset($this->expCache[$level])) return $this->expCache[$level];
[1641] 		$levelSquared = $level ** 2;
[1642] 		if($level < 16) $this->expCache[$level] = $levelSquared + 6 * $level;
[1643] 		elseif($level < 31) $this->expCache[$level] = 2.5 * $levelSquared - 40.5 * $level + 360;
[1644] 		else $this->expCache[$level] = 4.5 * $levelSquared - 162.5 * $level + 2220;
[1645] 		return $this->expCache[$level];
[1646] 	}
[1647] 
[1648] 	public function about(){
[1649] 		$this->logger->info($this->aboutstring);
[1650] 	}
[1651] 
[1652] 	public function loadAdvancedConfig(){
[1653] 		$this->playerMsgType = $this->getAdvancedProperty("server.player-msg-type", self::PLAYER_MSG_TYPE_MESSAGE);
[1654] 		$this->playerLoginMsg = $this->getAdvancedProperty("server.login-msg", "§3@player joined the game");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.2dev #607 [Protocol 81; API 2.0.0]
uname -a: Linux ca4.server.pro 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 11 hours 25 minutes 58 seconds
Number of loaded worlds: 3
Players online: 0/10

Loaded plugins:
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PlayerStats 0.1.0 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
CTF_DODO 1.1.0 by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
PerWorldAlerts 1.1 by EvolSoft for API(s) 1.9.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
Slapper 1.2.9.6 by jojoe77777 for API(s) 2.0.0
mcg76_TNTRun 1.6.0 by minecraftgenius76 for API(s) 1.12.0
superBAR 1.5.0 by FaigerSYS for API(s) 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
SkyWarsDoDo 1.0.0 Reloaded_ENGLISH by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
BlockBoost 1.0.0 by  for API(s) 1.13.0
MicroBattles 2.3.0 by KaitoDoDo+LittleBigMC for API(s) 1.0.0, 2.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
FSurvivalGame 1.0.3(Translated by Anie) by FENGberd for API(s) 1.0.0
WorldEdit 2.0.0 TRANSLATE BY ZIKEN by ikenusi, hmy2001(Plug- source reference) for API(s) 1.13.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
JoinPopup-NoMessage 1.0.0 by  for API(s) 1.14.0, 2.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
TapToDo-LEET.CC 1.0.0 by Falk, 64FF00 for API(s) 1.0.0
StaffList 3 by Array for API(s) 1.10.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
InfiniteSlots 1 by DRedDogPE for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
KillChat 1.0.2.MOD by Array for API(s) 1.9.0, 2.0.0
PerWorldChat 1.3 by EvolSoft for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
BetterRaw 2.0_BUILD_#5 by Ad5001 for API(s) 1.14.0, 2.0.0
Healthy 1.1 by MamayAdesu for API(s) 1.12.0
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
Error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 150994944 bytes)
File: /src/pocketmine/Server
Line: 1644
Type: E_ERROR

Code:
[1635] 			Server::$sleeper->wait($ms);
[1636] 		}, $microseconds);
[1637] 	}
[1638] 
[1639] 	public function getExpectedExperience($level){
[1640] 		if(isset($this->expCache[$level])) return $this->expCache[$level];
[1641] 		$levelSquared = $level ** 2;
[1642] 		if($level < 16) $this->expCache[$level] = $levelSquared + 6 * $level;
[1643] 		elseif($level < 31) $this->expCache[$level] = 2.5 * $levelSquared - 40.5 * $level + 360;
[1644] 		else $this->expCache[$level] = 4.5 * $levelSquared - 162.5 * $level + 2220;
[1645] 		return $this->expCache[$level];
[1646] 	}
[1647] 
[1648] 	public function about(){
[1649] 		$this->logger->info($this->aboutstring);
[1650] 	}
[1651] 
[1652] 	public function loadAdvancedConfig(){
[1653] 		$this->playerMsgType = $this->getAdvancedProperty("server.player-msg-type", self::PLAYER_MSG_TYPE_MESSAGE);
[1654] 		$this->playerLoginMsg = $this->getAdvancedProperty("server.login-msg", "§3@player joined the game");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.2dev #607 [Protocol 81; API 2.0.0]
uname -a: Linux ca4.server.pro 3.14.32-xxxx-grs-ipv6-64 #1 SMP Sat Feb 7 11:35:27 CET 2015 x86_64
PHP version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 11 hours 25 minutes 58 seconds
Number of loaded worlds: 3
Players online: 0/10

Loaded plugins:
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PlayerStats 0.1.0 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
CTF_DODO 1.1.0 by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
Lightning_Strike 2 by MichaelM04 for API(s) 1.0.0, 2.0.0
PerWorldAlerts 1.1 by EvolSoft for API(s) 1.9.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
Slapper 1.2.9.6 by jojoe77777 for API(s) 2.0.0
mcg76_TNTRun 1.6.0 by minecraftgenius76 for API(s) 1.12.0
superBAR 1.5.0 by FaigerSYS for API(s) 1.13.0, 2.0.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
SkyWarsDoDo 1.0.0 Reloaded_ENGLISH by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
BlockBoost 1.0.0 by  for API(s) 1.13.0
MicroBattles 2.3.0 by KaitoDoDo+LittleBigMC for API(s) 1.0.0, 2.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
FSurvivalGame 1.0.3(Translated by Anie) by FENGberd for API(s) 1.0.0
WorldEdit 2.0.0 TRANSLATE BY ZIKEN by ikenusi, hmy2001(Plug- source reference) for API(s) 1.13.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
JoinPopup-NoMessage 1.0.0 by  for API(s) 1.14.0, 2.0.0
BuyCraft 1.2.2 by Falkirks for API(s) 1.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
TapToDo-LEET.CC 1.0.0 by Falk, 64FF00 for API(s) 1.0.0
StaffList 3 by Array for API(s) 1.10.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
InfiniteSlots 1 by DRedDogPE for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
KillChat 1.0.2.MOD by Array for API(s) 1.9.0, 2.0.0
PerWorldChat 1.3 by EvolSoft for API(s) 1.10.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
BetterRaw 2.0_BUILD_#5 by Ad5001 for API(s) 1.14.0, 2.0.0
Healthy 1.1 by MamayAdesu for API(s) 1.12.0
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
