### ISSUE TITLE
Players fall into void when teleporting to each other

### ISSUE THREAD

**Issue by ERR404** [PocketMine/PocketMine-MP#2791]
Seems like its not lag. When players tp to each other, when a player goes into another world they will fall into the void and die. The server owner has a somewhat decent connection:
Ping: 28ms
Download: Approx 60Mb/s
Upload: 4Mb/s

We have found a temporary fix though by clicking on the warp signs while moving around. This problem began when we updated to the new version of pocket mine btw.

**Comment by Creeperface01** [comment]
i have same bug: player fall into void and still die and can't move or send messages.

**Comment by ERR404** [comment]
Yeah @Creeperface01 one of our OP members couldn't move or execute any commands. Teleporting him to another place didn't work either.

**Comment by Theapp** [comment]
How do I you do this??? Umm it looks really hard.😩

**Comment by Theapp** [comment]
How do I do it

**Comment by alejandroliu** [comment]
This should be fixed in the current dev versions.
