### ISSUE TITLE
Too much damage from the fall and lighters!

### ISSUE THREAD

**Issue by Vladik46** [PocketMine/PocketMine-MP#2796]
When you step on the fire in the diamond armor, immediately die.
When a fall from the 5th block from the earth in iron armor, take down 7 HP.

In fact ,the better the armor, the more damage the player.

**Comment by thelucyclub** [comment]
This is not @PocketMine this is @MCPE because this happens in single player too. :toilet: :sob:

**Comment by shoghicp** [comment]
This does not apply to the version on the repository

**Comment by PEMapModder** [comment]
Use the latest development version. Thr changes that made that bug is reverted.

**Comment by thelucyclub** [comment]
:hankey:
