### ISSUE TITLE
Pocketmine recreates automaticaly .mca files !

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#2801]
When using a RegionMC world converted from Anvil and start a PocketMine 1.4.1 server it recreates random Anvil's region files (.mca) between RegionMC's files (.mcr) !

**Comment by shoghicp** [comment]
That's because you did not remove all .mca files before loading the world. Please remove them before loading a MCRegion file

**Comment by roroB20** [comment]
No there is only .mcr files in region folder and I've testing it many times and I always get the same problem :/

Please reopen this issue !

**Comment by roroB20** [comment]
@shoghicp I've found the origin of the problem: for my PocketMine servers I've renamed all my folders with an "[Pocket]" indication before the server name (example: "[Pocket] My server1") and a [PC] indication for bukkit servers...
So it seems that when the server folder name contains "[" "]" characters the server creates automatically some .mca files into the region folder even if files into this folder are in MCRegion format !
Did you know why PocketMine do this ??
