### ISSUE TITLE
Worlds Not Working

### ISSUE THREAD

**Issue by Holicou** [PocketMine/PocketMine-MP#2808]
So, whenever i TP to a different world, I either die and respawn in the void, or in like 5 seconds disconnect. I'm using Many Worlds and sign portal plugins, just so you know :)

**Comment by Holicou** [comment]
this only happens in pc ported maps

**Comment by Midnight-Shadow** [comment]
This is an issue with your plugins, not PocketMine. This is the wrong place to post this.
