### ISSUE TITLE
PlayerDeathEvent does not pass through from time to time ...

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2811]
Ok, here is the issue it seldomly happens but its kinda annoying because its getting more frequent.

When a player dies, he died client sided showing the death screen but on the server side, this player didnt die. It sends some packets about the death of player but doesnt pass through PlayerDeathEvent.
Now, what happens is, when this player tap on Respawn button or something like that, they teleported back to the place where they died and turned invisible. To only fix this bug for the player is to reconnect which is so much hassle.

**Comment by PEMapModder** [comment]
Are you sure it isn't a plugin problem? May it be another handler canceling it?

**Comment by iJoshuaHD** [comment]
no, its not. i have tested it with and without plugins.

**Comment by shoghicp** [comment]
Please do not open duplicated issues. This happens when clients go below Y = 0 and it's a client-side bug. In the future, use the search field at the top of this page to find duplicates.
