### ISSUE TITLE
Could not tick level world: Object of class PlayerInventory could not be converted to int

### ISSUE THREAD

**Issue by tyan-boot** [PocketMine/PocketMine-MP#2815]
It says "[CRITICAL] Could not tick level world: Object of class pocketmine\inventory\PlayerInventory could not be converted to int16:39:01".

**Comment by tyan-boot** [comment]
![screenshot_2015-03-30-00-54-37](https://cloud.githubusercontent.com/assets/4982027/6886690/e89303e6-d678-11e4-9506-0de747335755.png)
I am using centos 5

**Comment by PEMapModder** [comment]
Please check if it only happens after the 0,0 chunk is modified and relaoded.

**Comment by alejandroliu** [comment]
Is this for Normal or for Flat worlds?

**Comment by tyan-boot** [comment]
Yes,when i walk to 0,0 chunk,this error appears again.But i do not know if it happns in other chunks.
> Please check if it only happens after the 0,0 chunk is modified and relaoded.

**Comment by tyan-boot** [comment]
In fact,i find only if somebody stuck in the chunks,this error will happen.
>Please check if it only happens after the 0,0 chunk is modified and relaoded.

**Comment by tyan-boot** [comment]
I do not test Flat.But i think it is the same.
>Is this for Normal or for Flat worlds?
