### ISSUE TITLE
Disable Console Message for plaher

### ISSUE THREAD

**Issue by mikki-mc** [PocketMine/PocketMine-MP#2819]
I got problem again, im using PurePerms Plugins...
When player come to my server, he can see my admin teleport to other player :
[Admin Teleport to Player]

And :

[CONSOLE : set time to 0]

Ban, ban-ip, save-all and other console message or op message, player can see :((

Fix or solution for me...

Thank you :D

**Comment by mikki-mc** [comment]
Oops.. sorry

Closed this thread...

Sorry Shoggi :-)

**Comment by PEMapModder** [comment]
This is not a support channel. If you have problems, ask it on the IRC channel. Please read the [contribution gudielines](../blob/master/CONTRIBUTING.md).
