### ISSUE TITLE
HELP PEOPLE

### ISSUE THREAD

**Issue by DarkPlague2** [PocketMine/PocketMine-MP#2822]
11:02:32 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
11:02:32 [INFO] Loading pocketmine.yml...
11:02:32 [INFO] Loading server properties...
11:02:32 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
11:02:32 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
11:02:32 [INFO] PocketMine-MP is distributed under the LGPL License
11:02:32 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
11:02:32 [CRITICAL] Perhaps a server is already running on that port?
11:02:32 [EMERGENCY] [RakLib Thread #4354289664] RakLib crashed!
11:02:33 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [48]: Address already in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
11:02:33 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by Thecraftdu34** [comment]
Reboot your computer and delete Pocketmine.phar file and re-dowload this

**Comment by Intyre** [comment]
11:02:32 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
11:02:32 [CRITICAL] Perhaps a server is already running on that port?
