### ISSUE TITLE
Items from furnace disappearing after world unload, even after save-all

### ISSUE THREAD

**Issue by diamond-gold** [PocketMine/PocketMine-MP#2823]
Items from furnace disappearing after world unload(server close/no players in server), even if you used the command "/save-all"

**Comment by Ishannaik** [comment]
it happened with me too but i reinstated my server and replaced my worlds and plugins and .... all the files eccept the start file and it got fixed

**Comment by Ishannaik** [comment]
And help me for the bukkit plugins at  https://github.com/PocketMine/PocketMine-MP/issues/2824
