### ISSUE TITLE
BUKKIT PLUGINS NOT WORKING

### ISSUE THREAD

**Issue by Ishannaik** [PocketMine/PocketMine-MP#2824]
11:27:52 [ERROR] Could not load 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\AreaGuard' in folder 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\': Undefined index: api
11:27:52 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 67
11:27:52 [ERROR] Could not load 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\BuyCraft' in folder 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\': Undefined index: api
11:27:52 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 67
11:27:52 [ERROR] Could not load 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\PowerRanks' in folder 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\': Undefined index: api
11:27:52 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 67
11:27:52 [ERROR] Could not load 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\Simple-Prefix' in folder 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\': Undefined index: api
11:27:52 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 67
11:27:52 [ERROR] Could not load 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\worldedit-bukkit-6.0' in folder 'C:\Users\lenovo pc\Desktop\PocketMine-MP\plugins\': Undefined index: api
11:27:52 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api" (E_NOTICE) in "/src/pocketmine/plugin/PluginDescription" at line 67

**Comment by PEMapModder** [comment]
Please read the [contributing guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. We do not support plugins here, nor do we provide individual support in an issue tracker.
