### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by DarkPlague2** [PocketMine/PocketMine-MP#2826]
Can you tell me what to fill in? This doesn't show in the doc

![screen shot 2015-04-02 at 4 20 55 pm](https://cloud.githubusercontent.com/assets/11718516/6961790/912faa68-d958-11e4-9940-67fa07d6f9e1.png)

**Comment by DarkPlague2** [comment]
Wheres the guidelines?

**Comment by PEMapModder** [comment]
The guidelines are hyperlinked above. Please do not comment on this issue anymore, as we do not provide support here.
