### ISSUE TITLE
Could not tick level: Object of class pocketmine\inventory\PlayerInventory could not be converted to int

### ISSUE THREAD

**Issue by ctalbot2004** [PocketMine/PocketMine-MP#2828]
When I get in a bed it gives me this error:

09:48:06 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:06 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:06 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:07 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:08 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:09 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:10 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int
09:48:11 [CRITICAL] Could not tick level hills: Object of class pocketmine\inventory\PlayerInventory could not be converted to int

When I get out of bed it won't let me move as well.

**Comment by alejandroliu** [comment]
I have tested this.  The error happens on 1.4.1 but *not* on the current dev version.  It has to do with the proportional armor patch that was applied to 1.4.1 but was then reverted in dev.

It has to do with adding armor components to the damage modifier event and then the getFinalDamage function expecting Int's instead of PlayerInventory objects.
