### ISSUE TITLE
Get level "Tiles"

### ISSUE THREAD

**Issue by iksaku** [PocketMine/PocketMine-MP#2829]
When you try to get all the tiles that a "Loaded" world contains using the function ``geTiles()``, an empty array is returned.

Now my question is: ``Do I need to manually register all the tiles that I want to use by scanning the whole world, or is there another way to do that?``

Thanks...

**Comment by Humerus** [comment]
You have to load the chunks prior to running that function or it will not work properly.

**Comment by iksaku** [comment]
Well I don't really understand the way that levels are loaded, but what if I'm trying to get them in the "default world"?

**Comment by Humerus** [comment]
Chunks aren't loaded by default start, if a user joins and is in that vicinity when you execute that code, you should get tiles. Take a look at using load chunk also

**Comment by iksaku** [comment]
Okey ^_^ thanks! :'D
