### ISSUE TITLE
Cannot pass closures to CallbackTask

### ISSUE THREAD

**Issue by PEMapModder** [PocketMine/PocketMine-MP#2830]
Closures are not supported for `pocketmine\scheduler\CallbackTask`s. 

This is the code that has the error:

```php
		if($task instanceof CallbackTask){
			$callable = $task->getCallable();
			if(is_array($callable)){
				if(is_object($callable[0])){
					$taskName = "Callback#" . get_class($callable[0]) . "::" . $callable[1];
				}else{
					$taskName = "Callback#" . $callable[0] . "::" . $callable[1];
				}
			}else{
				$taskName = "Callback#" . $callable; // <<< If $callable is a Closure, it will go here but $callable cannot be converted into a string
			}
		}else{
			$taskName = get_class($task);
		}
```

**Comment by Falkirks** [comment]
What is the problem? Closures aren't strings but they are callable.

**Comment by PEMapModder** [comment]
In the line commented, PocketMine attempts to convert them to string. This is not possible in my test with PHP 5.6.4.

**Comment by sekjun9878** [comment]
Ha :) CallbackTask is an internal class, and shouldn't be used by plugins. All tasks by plugins should extend pocketmine\scheduler\PluginTask. If you want to use closures, you will need to make a subclass of PluginTask - something like this which is what I'm using:

```php
<?php

namespace CakePowered\Agent;

use pocketmine\plugin\Plugin;
use pocketmine\scheduler\PluginTask;
use pocketmine\utils\PluginException;

/**
 * Class PluginCallbackTask
 * @package CakePowered\Agent
 */
class PluginCallbackTask extends PluginTask
{
	/** @var callable $callable */
	private $callable;


	/** @var array $args */
	private $args;

	/**
	 * @param Plugin $owner
	 * @param callable $callable
	 * @param array $args
	 */
	public function __construct(Plugin $owner, callable $callable, array $args = []){
		parent::__construct($owner);

		$this->callable = $callable;
		$this->args = $args;
	}

	public function onRun($currentTick)
	{
		if(call_user_func_array($this->callable, $this->args) === false)
		{
			//TODO: Detailed error message
			throw new PluginException("Could not run PluginCallbackTask");
		}
	}
}
```

**Comment by sekjun9878** [comment]
This is a problem though because it means not even PM's internal classes can use closures to schedule callbacks.

**Comment by PEMapModder** [comment]
CallbackTask can still be considered as part of API, because there may be some schedules that a plugin wants to run even after being disabled. For example, a plugin that wants to do something _after_ an event is executed - and if cancelled, _after_ being cancelled properly - in the current API, needs to run that one tick later; and even if the plugin is disabled, that thing still needs to be run. `(For example, setting block drops needs to use that method, although this example is only because of the API being incompleted, but there are still other examples)` This is when it is necessary to use a non-`PluginTask` schedule.

**Comment by sekjun9878** [comment]
Hmm alright, will fix it.

**Comment by shoghicp** [comment]
@PEMapModder Plugins MUST NOT execute something after being disabled. This class will be removed as soon as the core dependency is removed.

**Comment by sekjun9878** [comment]
@shoghicp He means that CallbackTask should be able to accept Closures for future internal ephemeral PM tasks - and that its a broken feature.

If it isn't going to be fixed, there should at least be a check on CallbackTask __construct to see that the callable is not a Closure.

**Comment by shoghicp** [comment]
@sekjun9878 I might create a different CallbackTask for plugins in the future, where you have to specify the plugin as a parameter. Having tasks by plugins not deleted can cause memory leaks, chunks not unloading, and duplicated players in memory that fire its own updates.
Any plugin that executes code after being disabled won't be accepted in the repository, as specified by the guidelines and enforced by the core

**Comment by sekjun9878** [comment]
@shoghicp I'm not trying to say anything about plugins staying loaded after it disables... I'm simply saying "Callback"Task doesn't accept Closure callbacks so it should either be fixed or parameter checked beforehand so we don't get that ambiguous error message.

**Comment by shoghicp** [comment]
It's using a callable and not a closure. It'll be done in a different way after changing it for plugin usage

**Comment by sekjun9878** [comment]
Okay then, whatever you see fit. I assume you already have changes in mind for 1.5.

**Comment by shoghicp** [comment]
Yep, I've to work more on 1.5 but I'm waiting for some last protocol changes - working on three branches with different protocols is a bit messy D:
