### ISSUE TITLE
Snowball & arrows BUGS

### ISSUE THREAD

**Issue by DanielZ123** [PocketMine/PocketMine-MP#2834]
When you shoot snowball , it is not always inflicts damage .
The same problem is with arrows.
The problem arose from the introduction of snowballs / arrows.
I tested this bug on different maps, without plugins . Nothing helped .

**Comment by PEMapModder** [comment]
Do you mean it doesn't always touch and be absorbed by the victim?

**Comment by DanielZ123** [comment]
Yep

**Comment by PEMapModder** [comment]
This is a duplication of #2172. Please search for similar issues before creating an issue.
