### ISSUE TITLE
[CRITICAL] Can't get on to my OWN server!?

### ISSUE THREAD

**Issue by DominationCraft** [PocketMine/PocketMine-MP#2837]
So, I just went through the properties and stuff, but I CAN'T EVEN GET ON TO MY OWN SERVER TO BUILD!!! Please help me, as this is a cool app, but this error is driving me up the wall! @shoghicp
Oh, and yes, I started the server.

**Comment by DominationCraft** [comment]
Wait, sorry, I was connecting to my friends IP god I'm an idiot. Nvm.

**Comment by PEMapModder** [comment]
This is not a help forum. Do not create help request here in the future. If you can't join a server, it is most likely your own problem not a bug since obviously other people can.
