### ISSUE TITLE
Sorry! Please Read (not kidding) can't use admin permissions.

### ISSUE THREAD

**Issue by DominationCraft** [PocketMine/PocketMine-MP#2838]
Is it possible to change my password for SimpleAuth? I accidently hit "Done" before I was actually done.....BIGGER ISSUE: IT SAYS I'M NOT ADMIN which means that I can't use any of the plugins.

**Comment by DominationCraft** [comment]
@shoghicp

**Comment by PEMapModder** [comment]
Please read the [Contribution Guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. Plugins are not supported on this bug tracker.
