### ISSUE TITLE
People can't join my server if they aren't using my internet connection!

### ISSUE THREAD

**Issue by JJthebestinVG** [PocketMine/PocketMine-MP#2839]
I recently created a Pocketmine server and told my friend to join it and so we could have some fun on it  
suddenly he skypes me and says "cant enter on the server :(" and i told him to retry and it didnt work
he retried like a million times and when i went to my friend and used his internet connection to enter
my server it didnt work even if i left my android device at home and the server is on sticking it crazy
like a maniac on the router!Please help me!Want to try yourself and check if it doesnt work : 
ip=192.168.1.68  port=19132

**Comment by JJthebestinVG** [comment]
Im using 10.0.4 by the way.

**Comment by thelucyclub** [comment]
Check your firewall, you may need to open the port. It may very well also be that:
* 1: Your server is out of date
* 2: You need to [port-foward](http://forums.pocketmine.net/threads/port-forwarding-guide.1294/)

**Comment by PEMapModder** [comment]
You are using an internal IP.
[Read the docs](http://pocketmine-mp.readthedocs.org/en/latest/) if you are confused with using PocketMine.
Use our [forums](https://forums.pocketmine.net) if you need help.
Read the [contributing guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue.
