### ISSUE TITLE
[CRITICAL] Could not tick level HUB: Object of class pocketmine\inventory\PlayerInventory could not be converted to int

### ISSUE THREAD

**Issue by thelucyclub** [PocketMine/PocketMine-MP#2840]
**ERROR:** *[CRITICAL] Could not tick level HUB: Object of class pocketmine\inventory\PlayerInventory could not be converted to int*
WHY???? It laggs my server!

**Comment by thelucyclub** [comment]
```javascript
function fancyAlert(arg) {
  if(arg) {
    $.facebox({div:'#foo'})
  }
}
```

**Comment by PEMapModder** [comment]
This issue is duplication of #2828 #2815 #2798 #2795 #2782. And you have already submitted the issue #2798 for exactly the same thing 14 days ago. Please do not submit duplicated issues. Read the [contributing guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue.
