### ISSUE TITLE
Blocks take multiple breaks to break

### ISSUE THREAD

**Issue by tourn171** [PocketMine/PocketMine-MP#2842]
When using tools blocks will break then reappear. Can take several tries for the block to actually break and become an entity and only if you continue to use the tool without stopping. 
  
version 1.5dev-999 for MCPE 0.11.0

**Comment by shoghicp** [comment]
0.11 sends block breaking orders in a different way, that might cause this

**Comment by Striker209MPE** [comment]
I've the same problem, this must be fixed!

**Comment by diamond-gold** [comment]
seems to happen with wooden pickaxe mining stone

**Comment by andry888** [comment]
Happens even in latest stable build.
Using 1.4.1-988 for MCPE 0.10.5 alpha

**Comment by mcprostar205** [comment]
I'm seeing this issue in Survival mode with the new MCPE v0.11 running on iOS 8.3 with PocketMine 1.5 Build 1213. Blocks break, re-appear, and second break finally turns ithem into a dropped item -- twice the work to break blocks.

**Comment by crashdogy** [comment]
Did not happen with stone pickaxe new 1.5

**Comment by mcprostar205** [comment]
Good point. Looks like issue is with Wood, Iron, Gold, and Diamond Pick Axe.

**Comment by ExpandingDev** [comment]
Using 1.5 Dev Build 1244, survival mode with MCPE v0.11. running on Windows Phone 8.1, same issue happens when breaking stone with wooden pickaxe. Looks like blocks only breakable by the tool will have this issue; dirt being broken by wooden pick breaks normally.

**Comment by LinuxSolutions** [comment]
I have the same problem.  Using 1.5 Dev Build 1244 and it doesn't matter what I break blocks with...blocks reappear multiple times.

**Comment by daywalk8r** [comment]
is there a fix to this problem yet or we still lookign at it ?

**Comment by dhecker** [comment]
Also hoping for a fix on this..

**Comment by shoghicp** [comment]
This is what is being worked on the branch new-blocks for a few weeks already

**Comment by TrendyGuy** [comment]
The only material I have had a problem mining so far is stone. It doesn't matter what tool I mine it with. This is with the latest dev build #1254. Everything else, wood, dirt, sand and such works fine. WIth stone I have to mine it two quickly in order to break. If I mine it once it will respawn immediately.

**Comment by Striker209** [comment]
@shoghicp I noticed on my server that if you drop and then pickup the pickaxe, you can mine what you want without having problems! That is strange but it should be a first step to fix

**Comment by Kanonen** [comment]
Running build 1257. This issues doesn't seem to just be unique to any kind of tool or target. Have experienced it with stone shovel and sand, stone axe and leaves, stone shovel and dirt, iron shovel and sand, wooden/stone pickaxe and stone.

**Comment by PEMapModder** [comment]
Does this issue happen if you add a plugin that calls `PlayerInteractEvent->setInstaBreak(true)`?

**Comment by Kanonen** [comment]
@PEMapModder I see there is a setInstaBreak() for BlockBreakEvent - is that the function you had in mind? i called that w/'true' on BlockBreakEvent and, in my preliminary testing with the tools/targets that were most problematic, the "multiple breaks" issue is no longer occurring. 

Does that help?

**Comment by PEMapModder** [comment]
It appears that the issue originates from the server lag. PocketMine assumes that player packets are sent to the server immediately, or at least, with the same latency. In that case, the server can measure the time the player used to break the block, and hence defend against an insta block-breaking mod. Nevertheless, it seems that lag makes this feature a bug.

**Comment by TrendyGuy** [comment]
PEMapModder, wouldn't this be true for all other blocks then? I am only having this problem so far with stone.

**Comment by TahaTheHacker** [comment]
i have the way to break them with one break : first hold an empty slot or anything instead of tools then start mining the block, then hold a pickaxe (if you are mining stone) without stopping mining then it will break with a one break. i don't now the way to fix it but how to break it :+1:

**Comment by TahaTheHacker** [comment]
you can close it or until it get fixed

**Comment by PEMapModder** [comment]
They have invalid parameters set for stone blocks. It is already, or soon (like in one or two days) fixed.

**Comment by mcprostar205** [comment]
This is really annoying. Issue still exists on build 1258. It makes mining in survival nearly impossible. Any update on when it will be fixed? Also, looks like MCPE .12 is due out soon and we will need to go to PM 1.6 before 1.5 is stable and released.

**Comment by TahaTheHacker** [comment]
even in MCPC latest version so it won't be fixed when 12.0 comes out anyway i told you how to break them xD
