### ISSUE TITLE
Call to undefined method pocketmine\network\Network::getUploadUsage()

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#2843]
When i type the command */status* the server crashes with this:

Fatal error: Call to undefined method pocketmine\network\Network::getUploadUsage() in phar:///dir/PocketMine-MP.phar/src/pocketmine/command/defaults/StatusCommand.php on line 47

**Comment by shoghicp** [comment]
Meh, I though I pushed this days ago. Seems like not!
