### ISSUE TITLE
Remove debug Yellow Grass Biome.

### ISSUE THREAD

**Issue by matcracker** [PocketMine/PocketMine-MP#2845]
Last dev build: PocketMine 1.5-dev 1000
OS: Android and Windows 8

I've got this generation.. http://imgur.com/EP6CNY9

**Comment by shoghicp** [comment]
Colors are wrong on a few biomes. It is this way to debug them, will be fixed before a beta build is released

**Comment by matcracker** [comment]
Ok, good! :D

**Comment by MCPEGamerJPatGitHub** [comment]
close please.

**Comment by roroB20** [comment]
Use grass color pattern to calibrate biomes's color:
http://hydra-media.cursecdn.com/minecraft.gamepedia.com/8/87/Grasscolor.png

**Comment by matcracker** [comment]
It becomes black with  anvils worlds.

**Comment by MCPEGamerJPatGitHub** [comment]
yea
