### ISSUE TITLE
fix please

### ISSUE THREAD

**Issue by Vladik46** [PocketMine/PocketMine-MP#2854]
11.04 14:05:10 [Server] INFO Threads: 6
11.04 14:05:10 [Server] INFO Memory: 884.02 MB
11.04 14:05:10 [Server] INFO Download: 305581.86 kB/s
11.04 14:05:10 [Server] INFO Upload: 2028858.66 kB/s
11.04 14:05:10 [Server] INFO TPS Load: 42.18%
11.04 14:05:10 [Server] INFO TPS: 16.47
There is something that needs to be fixed.

**Comment by shoghicp** [comment]
Seems like you disabled compression.
