### ISSUE TITLE
 the codes about "metadata" in AddPlayerPacket,pm1.5 is different from 14

### ISSUE THREAD

**Issue by Alcatraz-Du** [PocketMine/PocketMine-MP#2857]
I need codes "metadata"  In AddPlayerPacket, it changed in pm1.5,,,

$pk->metadata = [ 0 => [ 0,0 ],1 => [ 1,0 ],16 => [ 0,0 ],17 => [ 6,[ 0,0,0 ] ] ];

I don't know how to write,   it will make mcpe crash..     
Help me ,I want codes of "metadata"

**Comment by Alcatraz-Du** [comment]
I just want to send  players addPlayerPacket but I don't know how to write "metadata"

**Comment by shoghicp** [comment]
You can send Floating text using FloatingTextParticle, or NPCs using the Human class. Doing things manually with packets will break with each MCPE update (**protocol is not versioned in the API**)
.
You can check what PocketMine does if you read its source code.
