### ISSUE TITLE
After server updated and stopped for restarting - console freezes and only kill -s KILL helps.

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#2858]
In logs I see:

19:48:16 [INFO] Unloading level "survival"
19:48:17 [INFO] Unloading level "The o2 Concert/WWE"
19:48:17 [INFO] Unloading level "Paradise Cove"
19:48:18 [WARNING] RuntimeException: "Division by zero" (E_W
ARNING) in "/src/pocketmine/Server" at line 2158

**Comment by shoghicp** [comment]
Could you enable debug level 2 on pocketmine.yml to see if you get extra information?

**Comment by vvzar** [comment]
Done! Now waiting for your next dev build :)

**Comment by vvzar** [comment]
Debug 2 give us some additional info:23:11:43 [INFO] Unloading level "The o2 Concert/WWE"
23:11:43 [INFO] Unloading level "Paradise Cove"
23:11:44 [WARNING] RuntimeException: "Division by zero" (E_W
ARNING) in "/src/pocketmine/Server" at line 2158
23:11:44 [DEBUG] #0 /src/pocketmine/Server(2392): pocketmine
\Server->checkTickUpdates(integer 1)
23:11:44 [DEBUG] #1 /src/pocketmine/Server(2146): pocketmine
\Server->tick()
23:11:44 [DEBUG] #2 /src/pocketmine/Server(2022): pocketmine
\Server->tickProcessor()
23:11:44 [DEBUG] #3 /src/pocketmine/Server(1695): pocketmine
\Server->start()
23:11:44 [DEBUG] #4 /src/pocketmine/PocketMine(444): pocketm
ine\Server->__construct(pocketmine\CompatibleClassLoader obj
ect, pocketmine\utils\MainLogger object, string phar:///home
/minecraft/server-mpe/PocketMine-MP.phar/, string /home/mine
craft/server-mpe/, string /home/minecraft/server-mpe/plugins
/)
23:11:44 [DEBUG] #5 (1): require(string phar:///home/minecra
ft/server-mpe/PocketMine-MP.phar/src/pocketmine/PocketMine.p
hp)

**Comment by vvzar** [comment]
New update:
14:51:38 [INFO] Unloading level "Paradise Cove"
14:51:39 [WARNING] RuntimeException: "Division by zero" (E_W
ARNING) in "/src/pocketmine/Server" at line 2158
14:51:39 [DEBUG] #0 /src/pocketmine/Server(2392): pocketmine
\Server->checkTickUpdates(integer 648001)
14:51:39 [DEBUG] #1 /src/pocketmine/Server(2146): pocketmine
\Server->tick()
14:51:39 [DEBUG] #2 /src/pocketmine/Server(2022): pocketmine
\Server->tickProcessor()
14:51:39 [DEBUG] #3 /src/pocketmine/Server(1695): pocketmine
\Server->start()
14:51:39 [DEBUG] #4 /src/pocketmine/PocketMine(444): pocketm
ine\Server->__construct(pocketmine\CompatibleClassLoader obj
ect, pocketmine\utils\MainLogger object, string phar:///home
/minecraft/server-mpe/PocketMine-MP.phar/, string /home/mine
craft/server-mpe/, string /home/minecraft/server-mpe/plugins
/)
14:51:39 [DEBUG] #5 (1): require(string phar:///home/minecra
ft/server-mpe/PocketMine-MP.phar/src/pocketmine/PocketMine.p
hp)

**Comment by shoghicp** [comment]
Yep, I'm working on this :)

**Comment by vvzar** [comment]
Looks normal now. Thank You! Is it OK, that i must start server manually after updating? Screen closes terminal while pocketmine restarting in progress.
