### ISSUE TITLE
Clones when you leave 

### ISSUE THREAD

**Issue by ChrisNML** [PocketMine/PocketMine-MP#2859]
The game clones the player (name & skin) when they leave, when the player joins agian they cannot see their own clone but other players see two (one frozen the other active)

**Comment by thelucyclub** [comment]
This has nothing to do with pocketmine. It means you are playing on an overloaded client which does not have enough strength to process `playerQuitEvent`.
It can also happen in MCPE multiplayer when playing with friends. I recommend getting a better device to play on.

**Comment by ChrisNML** [comment]
If it is the device then there is no device out of all the people in our
server that can handle it.

~Chris

**Comment by DanielZ123** [comment]
I have too this bug.
(Intel i5, 16Gb ram with 100mb/s)

**Comment by ChrisNML** [comment]
He replied to my reply

**Comment by WhiteWolfOwner** [comment]
This will happen some times because of lag, or it maybe because when you don't log out of the game it will stay there for a few seconds... 

Thanks,
WhiteWolfOwner
