### ISSUE TITLE
Can't cancel scheduled tasks

### ISSUE THREAD

**Issue by iksaku** [PocketMine/PocketMine-MP#2862]
While calling the ``getScheduler()->cancelTask($taskId)`` from anywhere, and using the real given task id, it simply doesn't cancel the task, the task keeps executing... the worst thing is that even if you try to cancel the task from inside it self, it doesn't work neither...

Used (inside the task): ``$this->getPlugin()->getServer()->getScheduler()->cancelTask($this->getTaskId());``
Where ``getPlugin()`` is the access to the main file (``PluginBase``) of the project

**Comment by shoghicp** [comment]
You have to use the TaskHandler to cancel the task.

**Comment by iksaku** [comment]
TaskHandler? Could you explain that?

**Comment by Samueljh1** [comment]
running $this->getHandler() inside a task returns null.

**Comment by PEMapModder** [comment]
Is your task scheduled?

**Comment by Samueljh1** [comment]
yea, i had to this as a workaround:

$task = new FlyTask($this->plugin, $player, time());
$handler = $this->plugin->getServer()->getScheduler()->scheduleRepeatingTask($task, 1);
$task->setHandler($handler);

**Comment by PEMapModder** [comment]
Then please create another issue with a script plugin to reproduce this bug.
