### ISSUE TITLE
Server Chat Broken

### ISSUE THREAD

**Issue by ChrisNML** [PocketMine/PocketMine-MP#2864]
When I speek from the console or using /say command in chat it will only say "[(0)] 1 "

**Comment by ChrisNML** [comment]
Using PocketMine-MP 1.5dev-1023

**Comment by LilCrispy2o9** [comment]
I think this is because of the new languages commit thing in BaseLang.php. Do your join and leave meassages say ({0} joined the game)?

**Comment by ChrisNML** [comment]
No, when i join or someone else joins it says, "<player> has joined the game

**Comment by LilCrispy2o9** [comment]
Hmm thats weird.. i get "{0} has joined the game" and I think it might be the recent commit to PlayerChatEvent.php instead, ill try to fix

**Comment by LilCrispy2o9** [comment]
I went and typed in chat, it works fine for me, still trying to figure out why the join message is messed up
