### ISSUE TITLE
Generic reason

### ISSUE THREAD

**Issue by DanielZ123** [PocketMine/PocketMine-MP#2866]
I use PocketMine 1.5 #1023
I have server with Intel i5 and 16Gb ram.
Disconnet every few minutes all the players with reason "generic reason".
It seems to me that it's appeared for updating raklib.
In addition , after the recent updates (pocketmine), sometimes there are lags.
At the first versions 1.5 pocketmine these problems were not
Sorry for my english

**Comment by shoghicp** [comment]
Generic reason means that a plugin has called that.
