### ISSUE TITLE
new dev version API 1.12.0 lag

### ISSUE THREAD

**Issue by AngelM701** [PocketMine/PocketMine-MP#2869]
I was just wondering if its a pocketmine problem or mcpe bugs because every 0.11 server lags

**Comment by DanielZ123** [comment]
I have this same problem (Server with Intel i5 and 16Gb ram (Centos 6) ) + disconnect with "generic reason"

**Comment by Guillaume351** [comment]
Me too, it shows 20 TPS, but in fact we are far from that ; When I schedule a reapeating task every 20 ticks, il only display every 3-4 seconds

**Comment by DanielZ123** [comment]
I dont mean that lags. :)

**Comment by Guillaume351** [comment]
Oh.. i have a huge lag problem : i have only 32 slot and about 10 player try to connect each second, so the server lag because it can't kick people fast enough.......

**Comment by shoghicp** [comment]
Please update to the latest dev build :)

**Comment by AngelM701** [comment]
Thanks shoghi :) your awesome
