### ISSUE TITLE
bin\php\php.exe: Segmentation fault bug! Plese fix!

### ISSUE THREAD

**Issue by GaminSwed** [PocketMine/PocketMine-MP#2872]
15:53:35 [INFO] Loading pocketmine.yml...
15:53:35 [INFO] Loading server properties...
15:53:35 [INFO] Selected English (eng) as the base language
15:53:35 [INFO] Starting Minecraft: PE server version v0.11.0 alpha build 2
15:53:35 [INFO] Starting remote control listener
15:53:35 [INFO] RCON running on 0.0.0.0:19132
15:53:36 [NOTICE] The memory limit will only affect the main thread, and it's unreliable.
15:53:36 [NOTICE] To control the memory usage, reduce the amount of threads and chunks loaded
15:53:36 [INFO] Opening server on 0.0.0.0:19132
15:53:36 [INFO] This server is running PocketMine-MP version 1.5dev-1022 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
15:53:39 [INFO] ----- PocketMine-MP Auto Updater -----
15:53:39 [INFO] It appears you're running a Beta build, when you've specified that you prefer to run Stable builds.
15:53:40 [ERROR] Could not load level "world": zlib_decode(): data error
15:53:40 [WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 124
15:53:40 [EMERGENCY] No default level has been loaded
15:53:40 [INFO] Stopping other threads

bin\php\php.exe: Segmentation fault

**Comment by 3mpireGamerxx** [comment]
Why are you guys closing this? this is a REAL PROBLEM!!

**Comment by GaminSwed** [comment]
I know right!

**Comment by GaminSwed** [comment]
I deleted it because there was no way of fixing! I deleted all plugins but still did not work.

**Comment by sekjun9878** [comment]
For your information, it looks like your world has been corrupted. This is not a PocketMine Issue.
