### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by LDX-MCPE** [PocketMine/PocketMine-MP#2873]
About once every hour and a half, my server will stop with the message "Segmentation fault" printed straight to the console. (Not viâ the logger.) I have DO_LOOP enabled in my start.sh, but it doesn't automatically restart when this crash happens. No error dump is created, no PHP error messages are present. I'm using an Ubuntu 14.04 VPS with the latest development build and PHP binaries.

**Comment by jython234** [comment]
This happens to me too. Only thing is that it happens when I do /stop.

**Comment by jython234** [comment]
Segmentation fault is a PHP problem.

**Comment by LDX-MCPE** [comment]
Actually, this isn't really a problem. Apparently, when you update PocketMine, it overwrites the start.sh file, disabling DO_LOOP again. ASR was restarting it once an hour, but because DO_LOOP got disabled, it just shut the server down.

**Comment by PEMapModder** [comment]
@LDX-MCPE you don't need to edit `start.sh` to enable the loop. You can start the server with `./start.sh -l`, where the `-l` option would set `DO_LOOP` to `"on"`.
