### ISSUE TITLE
List command doesn't show player count when executed by player

### ISSUE THREAD

**Issue by LDX-MCPE** [PocketMine/PocketMine-MP#2879]
When you type /list in-game, it says "There are / players online:".
Screenshot: http://i.imgur.com/A4KVh5J.png

**Comment by shoghicp** [comment]
Please do not report client-side issues

**Comment by LDX-MCPE** [comment]
This isn't a client-side issue... The problem is somewhere in PocketMine's new TranslationContainer. I've tried tracing the problem, but the network of files gets so complicated that I can't find where the variables get inserted.

**Comment by shoghicp** [comment]
No, it's not. You are completely wrong. Wait patiently for build 3 and see :)

**Comment by jython234** [comment]
@shoghicp :O

**Comment by LDX-MCPE** [comment]
@shoghicp :O

**Comment by andrewnoelcasper** [comment]
:0

**Comment by LDX-MCPE** [comment]
@shoghicp, you made it seem like build 3 would have commands without PocketMine. It is, however, fixed on servers.

**Comment by PEMapModder** [comment]
and the fact is numbers with colors in chat have a problem rather than the server sending wrongly? (I guess)

**Comment by shoghicp** [comment]
@PEMapModder no, MCPE did not replace the language parameters correctly.
