### ISSUE TITLE
help

### ISSUE THREAD

**Issue by stephancevallos** [PocketMine/PocketMine-MP#2881]
./sta
![screen shot 2015-04-13 at 7 11 21 pm](https://cloud.githubusercontent.com/assets/11933621/7127931/f340d3d8-e21
![screen shot 2015-04-13 at 7 11 21 pm](https://cloud.githubusercontent.com/assets/11933621/7127933/fed57b54-e210-11e4-888a-a1177b70f4bb.png)
![screen shot 2015-04-13 at 7 11 21 pm](https://cloud.githubusercontent.com/assets/11933621/7127934/01140ac0-e211-11e4-9e9f-f2b884fd0413.png)

0-11e4-83ed-7bf102ee4c21.png)

**Comment by jython234** [comment]
Something is running on port 19132. Perhaps another server?
