### ISSUE TITLE
How do you install it on windows?

### ISSUE THREAD

**Issue by Nicholas20006** [PocketMine/PocketMine-MP#2885]
how do you install the pocket mine server on windows

**Comment by Logalicioustuff** [comment]
This is not the place to ask that question.

**Comment by Nicholas20006** [comment]
"facepalm"

**Comment by PEMapModder** [comment]
@Nicholas20006 this is not a support channel. Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. This is a _bug tracker_ not a _question tracker_.
