### ISSUE TITLE
Add new language for Simple Chinese  zh.ini

### ISSUE THREAD

**Issue by llj070** [PocketMine/PocketMine-MP#2886]
language.name=中文(简体)
language.selected=设定 {%0} ({%1}) 为基本語言

multiplayer.player.joined={%0} 进入游戏
multiplayer.player.left={%0} 离开游戏

chat.type.achievement={%0} 刚刚获得了成就 {%1}

disconnectionScreen.outdatedClient=用戶端版本过旧！
disconnectionScreen.outdatedServer=服务器版本过旧！
disconnectionScreen.serverFull=服务器人数已满！
disconnectionScreen.noReason=与服务器连线中断
disconnectionScreen.invalidSkin=无效的皮肤！

death.fell.accident.generic={%0} 从高处摔落
death.attack.inFire={%0} 在火焰中升天
death.attack.onFire={%0} 被烧死
death.attack.lava={%0} 在岩浆游泳
death.attack.inWall={%0} 在墙壁里窒息
death.attack.drown={%0} 溺死了
death.attack.cactus={%0} 被仙人掌刺死了
death.attack.generic={%0} 已死亡
death.attack.explosion={%0} 被炸飞了
death.attack.explosion.player={%0} 被 {%1} 炸死了
death.attack.magic={%0} 被魔法杀死了
death.attack.wither={%0} 凋零至死了
death.attack.mob={%0} 被 {%1} 杀死了
death.attack.player={%0} 被 {%1} 杀死了
death.attack.player.item={%0} 被 {%1} 用 {%2} 杀死
death.attack.arrow={%0} 被 {%1} 射杀了
death.attack.arrow.item={%0} 被 {%1} 用 {%2} 射杀
death.attack.fall={%0} 以为能安然无恙的着地
death.attack.outOfWorld={%0} 掉到世界外面了

gameMode.survival=生存模式
gameMode.creative=创造模式
gameMode.adventure=冒险模式
gameMode.spectator=观众模式
gameMode.changed=您的游戏模式已更新

potion.moveSpeed=移动加速
potion.moveSlowdown=移动減速
potion.digSpeed=挖掘加速
potion.digSlowDown=挖掘減速
potion.damageBoost=力量
potion.heal=立即治疗
potion.harm=立即伤害
potion.jump=跳跃提升
potion.confusion=噁心
potion.regeneration=恢復
potion.resistance=抗性
potion.fireResistance=抗火性
potion.waterBreathing=水下呼吸
potion.invisibility=隐身
potion.blindness=失明
potion.nightVision=夜視
potion.hunger=饥饿
potion.weakness=虛弱
potion.poison=中毒
potion.wither=凋零
potion.healthBoost=生命值提升
potion.absorption=吸收
potion.saturation=饱食

commands.generic.exception=尝试执行此命令时发生未知错误
commands.generic.permission=只有服主或OP才能使用该命令
commands.generic.notFound=无效命令。查看命令列表用 /help 页码
commands.generic.player.notFound=找不到该玩家
commands.generic.usage=用法 ：{%0}

commands.time.added=时间增加了 {%0}
commands.time.set=时间设定为 {%0}
commands.time.query=现在时间是 {%0}

commands.me.usage=/me <action ...>

commands.give.item.notFound=不存在ID为 {%0} 的物品
commands.give.success=成功将{%1}个 {%0} 给玩家 {%2}

commands.effect.usage=/effect <姓名> <效果> [秒数] [倍数] [隐藏粒子] 或 /effect <姓名> clear
commands.effect.notFound=ID为 {%0} 的特殊效果並不存在
commands.effect.success=對 {%3} 加上了 {%4} 秒的 {%0} (ID {%1}) * {%2}
commands.effect.success.removed=从 {%1} 身上移除了 {%0}
commands.effect.success.removed.all=已解除 {%0} 身上所有特殊状态
commands.effect.failure.notActive=无法从 {%1} 身上移除 {%0}，因为其身上无此效果
commands.effect.failure.notActive.all=无法移除效果因为 {%0} 身上沒有任何效果

commands.particle.success=正在应用 {%0} 效果 {%1} 次
commands.particle.notFound=未知的效果名称 {%0}

commands.players.usage=/list
commands.players.list=共有 {%0}/{%1} 玩家在线上 ：

commands.kill.successful=已刪除 {%0}

commands.banlist.ips=共有 %d 个被封锁的 IP地址：
commands.banlist.players=共有 {%0} 個被封锁的玩家：
commands.banlist.usage=/banlist [ips|players]

commands.defaultgamemode.usage=/defaultgamemode <模式>
commands.defaultgamemode.success=现在这个世界的预设游戏模式为 {%0}

commands.op.success=玩家 {%0} 成为OP管理员
commands.op.usage=/op <姓名>

commands.deop.success=玩家 {%0} 被解除OP管理員
commands.deop.usage=/deop <姓名>

commands.say.usage=/say <消息...>

commands.seed.usage=/seed
commands.seed.success=种子码 ：{%0}

commands.ban.success=成功封禁玩家 {%0}
commands.ban.usage=/ban <姓名> [原因...]

commands.unban.success=成功解封玩家 {%0}
commands.unban.usage=/pardon <姓名>

commands.banip.invalid=您输入了无效的IP地址、玩家名称或该玩家不在线
commands.banip.success=封禁IP地址 {%0} 。
commands.banip.success.players=封禁IP地址 {%0} 來自 {%1}
commands.banip.usage=/ban-ip <IP 位址|姓名> [原因 ...]

commands.unbanip.invalid=您输入了一个无效的IP地址
commands.unbanip.success=成功解封IP地址址 {%0}
commands.unbanip.usage=/pardon-ip <IP地址>

commands.save.usage=/save-all
commands.save-on.usage=/save-on
commands.save-off.usage=/save-off
commands.save.enabled=成功开启地图自动存档功能
commands.save.disabled=成功关闭地图自动存档功能
commands.save.start=正在储存地图...
commands.save.success=地图储存完毕。

commands.stop.usage=/stop
commands.stop.start=正在停止服务器...

commands.kick.success=玩家 {%0} 从游戏中被踢出
commands.kick.success.reason=玩家 {%0} 从游戏中被踢出 ：{%1}
commands.kick.usage=/kick <姓名> [原因...]

commands.tp.success=传送 {%0} 至 {%1}
commands.tp.success.coordinates=传送 {%0} 至 {%1}，{%2}，{%3}
commands.tp.usage=/tp [姓名] <目标玩家> 或是 /tp [姓名] <x> <y> <z> [<y-rot> <x-rot>]

commands.whitelist.list=有 {%0} 人(全部 {%1 人) 为白名单玩家:
commands.whitelist.enabled=成功开启白名单
commands.whitelist.disabled=成功关闭白名单
commands.whitelist.reloaded=成功重新载入白名单
commands.whitelist.add.success=新增 {%0} 至白名单
commands.whitelist.add.usage=/whitelist add <姓名>
commands.whitelist.remove.success=从白名单刪除 {%0}
commands.whitelist.remove.usage=/whitelist remove <姓名>
commands.whitelist.usage=/whitelist <on|off|list|add|remove|reload>

commands.gamemode.success.self=成功设定自己的游戏模式为 {%0}
commands.gamemode.success.other=成功设定玩家 {%0} 的游戏模式为 {%1}
commands.gamemode.usage=/gamemode <模式> [姓名]

commands.help.header=--- 查看帮助表第 {%0} 页共 {%1} 页 (/help 页码) ---
commands.help.usage=/help [页码|命令]

commands.message.usage=/tell <姓名> <讯息...>
commands.message.sameTarget=您不能发送讯息給自己！

commands.difficulty.usage=/difficulty <难度>
commands.difficulty.success=设定游戏难度为 {%0}

commands.spawnpoint.usage=/spawnpoint [姓名] [<x> <y> <z>]
commands.spawnpoint.success=设定玩家 {%0} 的出生点为 ({%1}，{%2}，{%3})

commands.setworldspawn.usage=/setworldspawn [<x> <y> <z>]
commands.setworldspawn.success=成功设定地图出生点为 ({%0}，{%1}，{%2})

pocketmine.data.playerNotFound=无法找到玩家数据 "{%0}"，创建新的玩家数据
pocketmine.data.playerCorrupted=发现损坏的玩家数据 "{%0}"，创建新的玩家数据
pocketmine.data.playerOld=发现旧的玩家数据 "{%0}"，更新玩家数据
pocketmine.data.saveError=无法储存 "{%0}" 的玩家资料：{%1}

pocketmine.level.notFound=无法找到 "{%0}" 地图
pocketmine.level.loadError=无法读取地图 "{%0}"：{%1}
pocketmine.level.generationError=无法生成地图 "{%0}"：{%1}
pocketmine.level.chunkUnloadError=移除一个区块时发生错误：{%0}
pocketmine.level.defaultError=没有读取预设的地图
pocketmine.level.preparing=准备地图中... "{%0}"
pocketmine.level.unloading=正在停用地图 "{%0}"

pocketmine.server.start=服务器版本 Minecraft：PE {%0} 版本
pocketmine.server.networkError=[网络] 由于 {%1} 停止接口 {%0}
pocketmine.server.networkStart=正在启动服务器在 {%0}:{%1}
pocketmine.server.info=此服务器正在运行 {%0} {%1} 版本 "{%2}" （API {%3}）
pocketmine.server.info.extended=此服务器正在运行 {%0} {%1} 「{%2}」 执行API版本 {%3} 支援 Minecraft：PE {%4} （協定版本 {%5}）
pocketmine.server.tickOverload=注意！加载区块中tps会暂时降低
pocketmine.server.startFinished=读取完成 ({%0}秒)！如需帮助，请输入 "/help 页码" 或 "/? 页码"
pocketmine.server.defaultGameMode=预设的游戏类型：{%0}
pocketmine.server.query.start=启动 GS4 状态监控器
pocketmine.server.query.info=设定 query 接口到 {%0}
pocketmine.server.query.running=Query 运作在 {%0}:{%1}

pocketmine.command.plugins.description=获取在服务器上运行的插件列表
pocketmine.command.plugins.success=插件 ({%0})：{%1}
pocketmine.command.plugins.usage=/plugins

pocketmine.command.reload.description=重新读取服务器设定和插件
pocketmine.command.reload.usage=/reload
pocketmine.command.reload.reloading=重新读取服务器...
pocketmine.command.reload.reloaded=重新读取完成

pocketmine.command.status.description=重新读取服务器的性能。
pocketmine.command.status.usage=/status

pocketmine.command.timings.usage=/timings <reset|report|on|off|paste>
pocketmine.command.timings.enable=启用定时和重启
pocketmine.command.timings.disable=停用定时
pocketmine.command.timings.timingsDisabled=启用定时工具通过 /timings on
pocketmine.command.timings.reset=定时重启
pocketmine.command.timings.pasteError=已记录在事件记录档中

pocketmine.command.version.usage=/version [插件名称]
pocketmine.command.version.noSuchPlugin=该服务器沒有运行任何叫这个名称的插件。使用 /plugins 來获得插件列表。

pocketmine.command.give.description=给指定玩家一定數量的物品
pocketmine.command.give.usage=/give <姓名> <代码[:附加码]> [数目]

pocketmine.command.kill.description=自杀或杀死其他玩家
pocketmine.command.kill.usage=/kill [姓名]

pocketmine.command.particle.usage=/particle <姓名> <x> <y> <z> <xd> <yd> <zd> [数目] [数据值]

pocketmine.command.time.description=更改每个世界的时间
pocketmine.command.time.usage=/time <set|add> <數值> 或 /time <start|stop|query>

pocketmine.command.banlist.description=查看來自該服务器禁止的所有玩家
pocketmine.command.defaultgamemode.description=设定預设的游戏模式
pocketmine.command.difficulty.description=设定游戏的难易度
pocketmine.command.gamemode.description=改变玩家到一個特定的游戏模式
pocketmine.command.help.description=显示帮助列表
pocketmine.command.list.description=显示在线玩家列表
pocketmine.command.save.description=储存服务器数据到磁盘上
pocketmine.command.saveoff.description=停用自动储存服务器
pocketmine.command.saveon.description=启用自动储存服务器
pocketmine.command.seed.description=显示世界种子码
pocketmine.command.setworldspawn.description=设定一个地图的出生点。未指定坐标，将使用玩家所在位置坐标。
pocketmine.command.spawnpoint.description=设定玩家出生点
pocketmine.command.stop.description=关闭服务器
pocketmine.command.tp.description=传送指定玩家（或是自己）到另一位玩家或坐标
pocketmine.command.tell.description=发送私聊信息给指定玩家
pocketmine.command.whitelist.description=管理員允许进入此服务器的玩家列表

pocketmine.debug.enable=启用输出debug调试信息

pocketmine.player.invalidMove=玩家 {%0} 移动错误 ！

pocketmine.plugin.load=读取中... {%0}
pocketmine.plugin.enable=启用中... {%0}
pocketmine.plugin.disable=停用中... {%0}
pocketmine.plugin.incompatibleAPI=不相容的API版本
pocketmine.plugin.unknownDependency=本插件无法单独使用
pocketmine.plugin.genericLoadError=无法读取插件 '{%0}'
pocketmine.plugin.loadError=无法读取插件 '{%0}'：{%1}
pocketmine.plugin.duplicateError=无法读取插件 '{%0}'：已有相同插件

**Comment by shoghicp** [comment]
Please do this on translate.pocketmine.net, besides, this is not the repository for this issue.
