### ISSUE TITLE
stopping network

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#2891]
19:41:18 [INFO] Lagarto[/85.70.125.129:39429] logged out due to Outdated server!
19:41:18 [CRITICAL] [Network] Stopped interface pocketmine\network\RakLibInterface due to Undefined index: 85.70.125.129:39429

**Comment by shoghicp** [comment]
I'm not able to reproduce this issue.
Are you sure you are on the latest pocketmine development build? Otherwise this issue breaks the Contribution Guidelines.
