### ISSUE TITLE
Wooden Pickaxe block respawn

### ISSUE THREAD

**Issue by Guillaume351** [PocketMine/PocketMine-MP#2894]
When you break stone with a wooden pickaxe, the block will respawn. There is only this issue with the wooden pickaxe

**Comment by WhiteWolfOwner** [comment]
Some times the server will lag and any block you break/mine will re-appear and you will have to mine it again but this is only in survival mode.

Thanks,
WhiteWolfOwner

**Comment by PEMapModder** [comment]
@WhiteWolfOwner this is a bug tracker, not a forum. Don't go anywhere posting replies like on a forum. Read [this](../blob/master/CONTRIBUTING.md).

**Comment by Striker209MPE** [comment]
I have the same problem, it also happens with all pickaxe, it's really annoying

**Comment by MCPEGamerJPatGitHub** [comment]
thats lag

**Comment by sekjun9878** [comment]
Duplicate of #2842. Please refer all future replies to #2842 instead. Or, reopen this issue if this issue only happens to the wooden pickaxe. Thanks!
