### ISSUE TITLE
API call Level::removeTile doesn't work

### ISSUE THREAD

**Issue by alejandroliu** [PocketMine/PocketMine-MP#2896]
When I do a Level::removeTile, the tile gets removed from the Level list however it remains in the Chunk list.  I have to then getChunk and then removeTile on the chunk also.

That is not needed when doing Level::removeEntity.

I don't know if this is the intention or it is a bug.

I wonder if issue #2823 is related to this.

Essentially the Tile array in the Level gets out of sync with the Tile array in the Chunk.

**Comment by shoghicp** [comment]
@alejandroliu You have to call Tile->close(), that'll do everything for you.
