### ISSUE TITLE
Some times when you put a piece of armor on it lags you out of the game. 

### ISSUE THREAD

**Issue by WhiteWolfOwner** [PocketMine/PocketMine-MP#2899]
Some times it does this, It annoys me when it does because normally when i put armor on its before a fight or something going on quickly. Also when i used to play SG it would crash me in the middle of a game. Normally when im unlucky. LOL
But I have had many problems recently with this.
Please fix it!

Thanks,
WhiteWolfOwner

**Comment by mightysun99** [comment]
Duplicated issue. Search issues before creating.
