### ISSUE TITLE
My server will not allow pvp in any world!

### ISSUE THREAD

**Issue by WhiteWolfOwner** [PocketMine/PocketMine-MP#2900]
I own a server and its a factions server so I am making this issue... I had another server before. And it disabled pvp as well... It maybe might be a plugin? I will give a list of all of my plugins and my config for area protect and other things... Like my config for server.properties!
-------------------------------------------------------------------------------------------------------------------------------

#Properties Config file
#Thu Apr 16 21:24:35 UTC 2015
type=0
motd=White Wolf Factions
server-port=19132
memory-limit=-1
white-list=off
announce-player-achievements=on
spawn-protection=45
max-players=20
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password= <private>
auto-save=on

Also here is the EssentalPE config...
---
safe-afk: true
auto-afk-kick: 300
oversized-stacks: 64
near-radius-limit: 200
near-default-radius: 200
enable-custom-colors: false
...

Here is the area config...
# Config file for iProtector by LDX;

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false

  # Keep players from editing the world?
  Edit: false

  # Keep players from touching blocks and activating things like chests?
  Touch: false

# Settings for unprotected areas in individual worlds:
Worlds:

  world:

    # Keep players from getting hurt?
    God: false

    # Keep players from editing the world?
    Edit: false

    # Keep players from touching blocks and activating things like chests?
    Touch: false

Heres the list...
-------------------------------------------------------------------------------------------------------------------------------

[{"name":"spawn","flags":{"edit":true,"god":false,"touch":true},"pos1":[107,54,149],"pos2":[147,95,105],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"shop3","flags":{"edit":true,"god":false,"touch":true},"pos1":[139,86,154],"pos2":[121,79,143],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"shop2","flags":{"edit":true,"god":false,"touch":true},"pos1":[155,87,118],"pos2":[142,79,138],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"shop1","flags":{"edit":true,"god":false,"touch":true},"pos1":[121,86,103],"pos2":[141,79,117],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"floor","flags":{"edit":true,"god":false,"touch":true},"pos1":[105,78,137],"pos2":[116,78,121],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"floor2","flags":{"edit":true,"god":false,"touch":true},"pos1":[122,78,104],"pos2":[140,78,116],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"floor3","flags":{"edit":true,"god":false,"touch":true},"pos1":[154,78,119],"pos2":[143,78,137],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"enterance","flags":{"edit":true,"god":false,"touch":true},"pos1":[144,66,189],"pos2":[159,69,185],"level":"world","whitelist":["megatron0802"]},{"name":"roof","flags":{"edit":true,"god":false,"touch":true},"pos1":[122,86,142],"pos2":[138,86,153],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"pedestrianshome","flags":{"edit":true,"god":false,"touch":true},"pos1":[155,65,278],"pos2":[140,65,292],"level":"Factions","whitelist":["pedestrian"]},{"name":"tree!","flags":{"edit":true,"god":false,"touch":true},"pos1":[183,67,193],"pos2":[178,67,188],"level":"Factions","whitelist":["octo_spy_miner"]},{"name":"parkourroom","flags":{"edit":true,"god":false,"touch":true},"pos1":[141,76,103],"pos2":[121,92,117],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"parkouroutside","flags":{"edit":true,"god":false,"touch":true},"pos1":[120,95,141],"pos2":[71,64,217],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"parkour3","flags":{"edit":true,"god":false,"touch":true},"pos1":[112,69,59],"pos2":[138,90,61],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"hq","flags":{"edit":true,"god":false,"touch":true},"pos1":[141,68,356],"pos2":[109,92,324],"level":"world","whitelist":["megatron0802"]},{"name":"hungergames","flags":{"edit":true,"god":true,"touch":true},"pos1":[-359,75,-173],"pos2":[-399,65,-138],"level":"world","whitelist":["thunderbolt_ray"]},{"name":"spawnfac","flags":{"edit":true,"god":false,"touch":true},"pos1":[84,79,150],"pos2":[88,71,146],"level":"Factions","whitelist":["thunderbolt_ray"]},{"name":"awesomedolphin89","flags":{"edit":true,"god":false,"touch":true},"pos1":[70,65,225],"pos2":[53,76,249],"level":"world","whitelist":["megatron0802"]},{"name":"purge","flags":{"edit":false,"god":false,"touch":true},"pos1":[421,73,370],"pos2":[300,63,269],"level":"Purge","whitelist":["thunderbolt_ray"]},{"name":"purge2","flags":{"edit":true,"god":false,"touch":true},"pos1":[300,92,269],"pos2":[420,63,369],"level":"Purge","whitelist":["thunderbolt_ray"]}]
-------------------------------------------------------------------------------------------------------------------------------

Tell me if there is any other config or info you need. 

Thanks,
WhiteWolfOwner

**Comment by mightysun99** [comment]
This is not a support channel. Please read the contribution guidelines before creating an issue.

**Comment by LDX-MCPE** [comment]
Please report this bug in the iProtector issues area. An admin will close this issue soon. https://github.com/LDX-MCPE/iProtector

**Comment by MCPEGamerJPatGitHub** [comment]
this should be a world issue. disable all protection/

**Comment by WhiteWolfOwner** [comment]
Okay thanks!!

**Comment by WhiteWolfOwner** [comment]
@shoghicp read my message on pocketmine.net
