### ISSUE TITLE
Upon repspawing after falling into the void while in creative your hotbar gets cleared.

### ISSUE THREAD

**Issue by mightysun99** [PocketMine/PocketMine-MP#2902]
Title says it all.

**Comment by WhiteWolfOwner** [comment]
Could you give more info about this? Is this even an issue? Does it need to be fixed? Or are you just stating this? Go to https://forums.pocketmine.net/forums/help/ and post a new thread and i'm sure you might get some help there...

Thanks,
WhiteWolfOwner

**Comment by mightysun99** [comment]
Upon respawning in creative your hotbar shouldnt be cleared.

**Comment by MCPEGamerJPatGitHub** [comment]
the title doesnt make sense

**Comment by WhiteWolfOwner** [comment]
@MCPEGamerJPatGitHub 
Title:
I have found a glitch, when you put on a peice if armor it does the same thing as when you switch to creative.

**Comment by NML32** [comment]
That's the only way I know how to clear the hot bar so I don't mind.

**Comment by sekjun9878** [comment]
The /kill command also clears your hotbar, so this is the desired behaviour. Please reopen this issue if you believe otherwise. Thanks!
