### ISSUE TITLE
Server is using WAY to much RAM

### ISSUE THREAD

**Issue by CDFalcon** [PocketMine/PocketMine-MP#2907]
My server is climbing into 10,000 megabytes of RAM!!! It has never used more than 1,000 RAM before, but I did recently transfer it to a new, faster computer...
Why is this happening? please respond ASAP

**Comment by ztdroider25** [comment]
Try limiting it to 1000mb in the server.yml.

**Comment by CDFalcon** [comment]
In the server properties? But that just makes it shut down...

**Comment by iJoshuaHD** [comment]
ikr! im getting this aswell but the maximum was only 950MB for 15 players online D:

**Comment by PEMapModder** [comment]
Does that happen without any plugins at all?

**Comment by iJoshuaHD** [comment]
@PEMapModder yep. i think its with worlds. so far this only happens with PM1.5.

**Comment by shoghicp** [comment]
The amount of memory reported by PocketMine 1.5 is different than the amount of reported by 1.4.

1.4 only reported the current thread PHP space memory, while 1.5 reports the allocated memory for the entire process (and all threads), including RAM and virtual memory.

**Comment by CDFalcon** [comment]
Found out why it was! It was my BuyCraft plugin!
