### ISSUE TITLE
Corrupted chunk when importing MCregion map

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#2915]
When using an external map in MCRegion format in last PocketMine build I get this error and the server regenerate all the chunks ....

Error :
13:01:20 [ERROR] Corrupted chunk detected

**Comment by shoghicp** [comment]
Shouldn't happen anymore

**Comment by PEMapModder** [comment]
This still happens on my clone that uses the latest commit on the `master` branch with only start.sh slightly modified to pull the latest commit every restart. The world works well before.
