### ISSUE TITLE
ChunkEvent error...

### ISSUE THREAD

**Issue by CDFalcon** [PocketMine/PocketMine-MP#2916]
My server crashes every few hours with the ChunkEvent on line 37. The reason I am not submitting my crash dump is because I *think* this issue has been fixed, I just need to know how to fix it.

**Comment by HmHmmHm** [comment]
how about the increasing the chunks tick?
In my guess, when a chunk is overuse this error occurs

**Comment by CDFalcon** [comment]
How would I do this? In pocketmine.yml?
