### ISSUE TITLE
Tree generation in two chunks

### ISSUE THREAD

**Issue by Mstrodl** [PocketMine/PocketMine-MP#2922]
When a tree is generated and is not in one chunk only part of the tree is generated (the part in the chunk with the trunk) and you get something like this:
![2015-04-21_16 46 52](https://cloud.githubusercontent.com/assets/6877780/7262244/0b608d42-e846-11e4-83af-ae72e567b37b.png)

**Comment by shoghicp** [comment]
This has been already fixed.
