### ISSUE TITLE
Colors doesn't work properly on Windows.

### ISSUE THREAD

**Issue by MagicDroidX** [PocketMine/PocketMine-MP#2925]
It always print lots of Minecraft Color Format symbols with no color.
Like this:
§b17:28:21§r §e[WARNING] Non-packaged PocketMine-MP installation detected, do not use on production.§r
§b17:28:21§r §f[INFO] Loading pocketmine.yml...§r
§b17:28:21§r §f[INFO] Loading server properties...§r
I use the mintty.exe to boot the PocketMine.

**Comment by PEMapModder** [comment]
Isn't this fixed in the latest development build?

**Comment by MagicDroidX** [comment]
Nope.I use the lastest one.

**Comment by shoghicp** [comment]
Seems like you have some strange issue with text replacement, but it works the same as on Linux. Did you use the normal start.cmd script instead of manually launching it?
