### ISSUE TITLE
Map issue in 1060 and up!

### ISSUE THREAD

**Issue by fengberd** [PocketMine/PocketMine-MP#2926]
There's a big issue!In PocketMine #1060 and up,any PC map will be broken and the server will crash!And all map after load in these crash server will be broken!

**Comment by PEMapModder** [comment]
Worlds generated in 1.4 cannot be loaded with 1.5 because worlds from other builds are broken. Generate a new map instead.

**Comment by shoghicp** [comment]
Seems lime you are not using the latest development build. Please follow the Contribution Guidelines when reporting issues.

**Comment by 64FF00** [comment]
lime? Hehe
