### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by fengberd** [PocketMine/PocketMine-MP#2927]
New pocketmine have a isset,it will lost any color on some device,but the other device will keep colors,for example it's lost color in my first VPS,all text looks like be '§f[INFO]xxx',but my second VPS can display color...and windows was lost color in #1003 and up..

**Comment by MobileCrafter** [comment]
No windows is fixed.

**Comment by fengberd** [comment]
but some linux have this issue...

On 周四, 4月 23, 2015 at 4:22 下午, Shoghi Cervantes < notifications@github.com [notifications@github.com] > wrote:
Closed #2927 [https://github.com/PocketMine/PocketMine-MP/issues/2927] .

—
Reply to this email directly or view it on GitHub
[https://github.com/PocketMine/PocketMine-MP/issues/2927#event-288066801] .[https://github.com/notifications/beacon/AIGMcegZ5YXsXQvV7iWBpURfVS9TKc95ks5oCKNdgaJpZM4EGqs9.gif]
