### ISSUE TITLE
Color issue is still there.

### ISSUE THREAD

**Issue by MagicDroidX** [PocketMine/PocketMine-MP#2928]
I'm using the version which released after the commit "Fixed the color on windows" was commited.
And I am using the start.cmd without any changes.
The problem is still exist.Plz check it out!
:D
With an image:
![361706030310196127](https://cloud.githubusercontent.com/assets/8433134/7295489/04bc63ea-e9e9-11e4-8ee0-8ec7b1d8f5b7.png)

**Comment by MobileCrafter** [comment]
Lol.
Okay for me it is fixed on Windows 7 64Bit.
Strange.
