### ISSUE TITLE
Can't go in the groud..

### ISSUE THREAD

**Issue by matcracker** [PocketMine/PocketMine-MP#2932]
PocketMine Build: 1088
OS: Android
Plugins: 0

I encountered this problem, when you dig down, at a certain depth is no longer possible to continue and place blocks and I was teleporting up.

**Comment by sekjun9878** [comment]
There isn't enough information for us to reproduce this problem. Please post the exact steps that we can use to reproduce this issue, and then reopen if this is still an issue. Thanks!

**Comment by matcracker** [comment]
No, quiet, it has been fixed that problem does not give me more! Sorry but I had forgotten to close this message! Thanks!
