### ISSUE TITLE
"Player Moved Wrongly

### ISSUE THREAD

**Issue by LouisBHirst** [PocketMine/PocketMine-MP#2933]
Twice this has happened, I see "Player Moved Wrongly" in console, then the player can't connect until the user dat file is deleted out of /players.  On the client side player is stuck at "Generating World / Building Terrain (90% progress bar)"  Server console reports the player has joined the game, but they don't get on.

**Comment by LouisBHirst** [comment]
Base64 representation of the dat file:
http://www.motobit.com/util/base64-decoder-encoder.asp

H4sIAAAAAAAAC5XVy07bQBQG4D++BNtJoKV3oBRKuaSky+66aNQoAYlLVBC7SgxkAIuJJ5o4qSKx
yDv0Bfomzab7vgI73qIdR+qCRavfs5kz9qczxxv/EeChdBGbftpWYiQ7QGHv7ufN2EOkxL2Ht9fV
EG5b94sA3B+TL99WbPGxPUa2Jh/eV07tHsDfk0Op4H/VRnVChLvJUCapNqPIvn5XgP9JD5IUDooN
0RWX0jaHd6R0avfg2AxkVv924MT2XvzHF3J6J6d3c3ovp/dz+mJOP5PTBzl9SJiIMCXClAlTIcws
YeYI84AwDwkzT5hHhHlMmCeEeUqYZ4R5TpgXhFkgzCJhlgjzkjDLhHlFmBXCrBLmNWHWCPOGMOuE
2SDMJmG2CFMlzFvCbBOm9tdEKNfPr2IbcV2ban24mO1lGWlaoiuPRz2ZhWGI4r5OY51MoxL/WCGC
zzoVmfPt0al/B+q/AB/lplCqEfdTkZxPGzrwmrGRWeHWY1Oo2V/1YdIydtqOjcGyzdiBSqQRZ0ra
CJ45yIYRlwhOdLKThbv9oh0pVHplm/0B6xJf8vQHAAA=

**Comment by shoghicp** [comment]
This has been already fixed

**Comment by LouisBHirst** [comment]
Cool thanks!
