### ISSUE TITLE
1088 version always Load 100%..!

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2934]
![e1](https://cloud.githubusercontent.com/assets/8337568/7333163/d028d14c-eb9e-11e4-973f-e13eb83bbe2c.png)
![556](https://cloud.githubusercontent.com/assets/8337568/7333183/8350d38c-eb9f-11e4-90c7-480a3716949b.png)

PocketMine: PocketMine Dev1088
Map format: anvil
Ram: 32GB
Cpu: Intel i7-4790 3.6Ghz

I can't control my world tick

I have been using the 1068 version, 
Was updated in 1088 last few minute

http://timings.aikar.co/?url=10885828
- auto tick enable timings(default pocketmine.yml)

http://timings.aikar.co/?url=10886259
- auto tick disable timings(auto tick disabled, sending per tick discounted)

somethings... wrong...
overload is still continuing and some user is want to kill me..

**Comment by shoghicp** [comment]
Seems like you are abusing callback tasks and they take a lot of time. Please check your plugins as they are lagging your server. Remember that we don't support plugins here.

**Comment by HmHmmHm** [comment]
I'm solved by dumping the 1079 version
