### ISSUE TITLE
Incomplete and error generating classes

### ISSUE THREAD

**Issue by Falkirks** [PocketMine/PocketMine-MP#2935]
I want to point out that if you try to `require` every php file in the PocketMine codebase you will end up with a fatal error. I would consider this as an issue. The issue is that classes like `Chicken`, `Cow`, and `Creeper` are empty placeholders. This would be find and dandy if they were valid PHP, but as it stands they yield a fatal error upon require (not instantiation). It would make life easier if I could assume that PHP files included in the project were all valid PHP.

**Comment by shoghicp** [comment]
@Falkirks That would happen even with only include. It's due to the classes being incomplete that it fails, not require

**Comment by Falkirks** [comment]
I know, when will this be fixed? It's very annoying.
