### ISSUE TITLE
respawn

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#2936]
When my players die the Respawn or Main menu button don't appear.

**Comment by Striker209MPE** [comment]
What are your enabled plugins? Do they handle Death/Respawn Events?

**Comment by PEMapModder** [comment]
But the "You died" screen appears? If that is the case, PocketMine has nothing to do with that.

**Comment by Artide** [comment]
It got fixed in the dev #94 thanks anyways
