### ISSUE TITLE
 joined game 2 chunks loaded.

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#2945]
![screenshot_2015-04-27-20-07-49](https://cloud.githubusercontent.com/assets/5399200/7353039/59c11d76-ed19-11e4-986b-e9eda6217df4.png)

I wait 2 minutes in game and nothing changed.
Build 1094

In console:
20:05:58 [DEBUG] Level "enter" took 276.19ms, setting tick rate to 5 ticks
20:05:58 [DEBUG] Raising level "enter" tick rate to 4 ticks
20:05:58 [DEBUG] Raising level "enter" tick rate to 3 ticks
20:05:58 [DEBUG] Raising level "enter" tick rate to 2 ticks
20:05:59 [DEBUG] Raising level "enter" tick rate to 1 ticks

Linux Ubuntu 14.04 x64 vmware vmachine 16 cores and 32Gb RAM

Timings:
 http://timings.aikar.co/?url=10913805

**Comment by shoghicp** [comment]
Seems like there is a chunk not loaded for you internally, and the server waits for it.

**Comment by vvzar** [comment]
I found potentional reason - default world format is set to anvil and convert world is set to true.
after I set it back to mcregion and false, chunks loaded succesfully.

**Comment by shoghicp** [comment]
convert world is not yet implemented, and doesn't change the format of existing worlds. seems like a random occurrence.

**Comment by thelucyclub** [comment]
@shoghicp when will it be implemented? Everyone has been waiting... :smiley:

**Comment by HmHmmHm** [comment]
@vvzar You can use AnvilToRegion Program
https://www.dropbox.com/s/1w257bvm1gyd5cq/AnvilToRegion.zip?dl=0

I had only recently succeeded in converting,
After conversion you must clear all the files in the 'world\region\*.mca'

AnvilToRegion does not automatically delete files mca
If you do not delete, will the #2897 problem occurs,

So have a nice day ~

**Comment by shoghicp** [comment]
Is this still happening on the latest promoted 1.5 build?

**Comment by vvzar** [comment]
No . it not happens anymore. But chunks have black grass blocks. After some latest build was out - not all chunks, but too many still are black.
