### ISSUE TITLE
Arrows bug

### ISSUE THREAD

**Issue by JoahDave** [PocketMine/PocketMine-MP#2947]
When I use a bow and arrow, the arrow flies like normal until it hits a block but then starts going north, ignoring any collision. Arrows also deal no damage at all, or they're a one hit kill.

**Comment by JoahDave** [comment]
Similar to #2905

**Comment by JoahDave** [comment]
Oops

**Comment by shoghicp** [comment]
Seems like you are not using the latest version.

**Comment by JoahDave** [comment]
I am!

**Comment by JoahDave** [comment]
I was in the slab bug issue also!
