### ISSUE TITLE
how to fix this ?????

### ISSUE THREAD

**Issue by ppgamer** [PocketMine/PocketMine-MP#2948]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 19:01:42 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 19:01:42 [INFO] Loading pocketmine-soft.yml...
[Server] 19:01:42 [INFO] Loading pocketmine.yml...
[Server] 19:01:42 [INFO] Loading server properties...
[Server] 19:01:43 [INFO] Advanced cache enabled
[Server] 19:01:43 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 19:01:43 [INFO] This server is running PocketMine-Soft version 1.4.1-240 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 19:01:43 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 19:01:45 [INFO] Loading SimpleAuth v1.6.0
[Server] 19:01:45 [INFO] Loading SimpleWarp v1.4
[Server] 19:01:45 [INFO] Loading EconomyAPI v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyAuction v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyCasino v2.0.1
[Server] 19:01:45 [INFO] Loading EconomyJob v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyLand v2.0.6
[Server] 19:01:45 [INFO] Loading EconomyProperty v2.0.3
[Server] 19:01:45 [INFO] Loading EconomySell v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyShop v2.0.4
[Server] 19:01:45 [INFO] Loading EconomyTax v2.0.2
[Server] 19:01:45 [INFO] Loading ItemCloud v1.1
[Server] 19:01:45 [INFO] Loading ChatBubbles v1.1.7
[Server] 19:01:45 [INFO] Loading RandomItem v4.2
[Server] 19:01:45 [INFO] Loading PeacefulSpawn v2.4
[Server] 19:01:45 [INFO] Loading iControlU v1.3
[Server] 19:01:45 [INFO] Loading BanItem v2.1
[Server] 19:01:45 [INFO] Loading EconomyAirport v2.0.3
[Server] 19:01:45 [INFO] Loading EconomyPShop v2.0.0
[Server] 19:01:46 [INFO] Loading BattleKits v1.0.3
[Server] 19:01:46 [INFO] Enabling SimpleAuth v1.6.0
[Server] 19:01:46 [INFO] [SimpleAuth] Everything loaded!
[Server] 19:01:48 [ERROR] Could not load level "world": zlib_decode(): data error
[Server] 19:01:48 [WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 124
[Server] 19:01:48 [EMERGENCY] No default level has been loaded
[

**Comment by Subtleoliver** [comment]
This isn't support. This is bug report. Look at the pocket mine forums.

**Comment by ppgamer** [comment]
Oh...ok

**Comment by LDX-MCPE** [comment]
Your world is corrupt. Try deleting it and letting PocketMine generate a new one.

**Comment by JellyBellyMaker** [comment]
how do I fix this?                                                                                                                                PocketMine-MP Crash Dump Sun Jan 22 12:02:50 CST 2017

Error: 
File: 
Line: 
Type: 

Code:
[1] 
[2] 
[3] 
[4] 
[5] 
[6] 
[7] 
[8] 
[9] 
[10] 

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/Server(2227): pocketmine\Server->titleTick()
#2 /src/pocketmine/Server(2110): pocketmine\Server->tick()
#3 /src/pocketmine/Server(1986): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct()
#6 (1): ()
#7 (0): {main}()

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT KIDSLIVINGROOM 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
PocketDockConsole 0.0.14 by humerusj for API(s) 1.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNqlWA1v3LgR/SvE+oAmxWot7bc32AOM2Jdza8db22mKxoeAkqiVzpKoI6msN0H+e9+QklaJ4/aA
LoyEGs4MhzNvZkh+GZisEINVMF3OAn8ZLPzhQCgl1WD1ZZBkOaYGg+HA7CuMyjrPvw4HVV5vs3Kw
SniuxXAQyVgQd+AYhoNxO5i0g2k7mLWDeTtYtINlOzhpB4HfLWkUj7DIh8GRz461io4rGT0IU2Sl
OL4V6pNQL/yXK3ag3t87svdzpLhOz+qievESGzkKnpMfj8eLZ1SYzOTiLosenIrxsyqCwH9WRSs9
eU46OFnO/4v0RslIaC2VUzN9Vs3CnzyjRhuujBOfPRHf2OEVhi+m0/EzGj5+jGSpjaqjRs+cvQjA
6z4WzEbhS8Gz8itIvw0HW1EKxXPCBxToTAI3g2A0HQUQCOssjwerkyVAVylpZCTBOcYXrzLLFwQj
H4zbzODT/5M/CCj+kGchyYwWVkNdcoL54H1WxnKn2ds79veLs9vLi39evH1zc319xeajMbMGsZOx
77MXLeeS/SoLwTZKFFldsPM4M9jFS5bNlnMortIKamej+Yi+PosSGxqM8em7yY9S07IXb9/egWA/
dkieLo00ucb5/gz/voZ7ZW7zqbH46dyw50p/5I+CKUi8NqlUmnIkrQuhav07+d868gM8CUb6FiUP
cwEbEUPkbiwqWExSmNMyMWd9AsXxRxbc31/RzHCQS07b3Vzf3r2/vrk8A2knQp0ZMjw1ptKr42ME
L63DUSSL4yeanlLIMzfCIvWq74YDbfgNksbW0b3dvwE/cj4xQn3jgOD/8IByixfYed+OZvu3d6c3
d+82/2vzPcN6yeZtHAyOjRLiuOCapg+LfCWgcAVR0FsrbTKOkDGVUCYThKmjTffF4Mkk2zKq3vfq
vjy6rUv2N16y8ZgF45WPvyl7fXvHxn6wIIZCmnhNtljrVmxzzly+06RbzKukMusT/8S3AqKQau/l
WZGZtRcQaZdi36Bos5ZJQhRelrIuI+FVOd9DA4/STHwShSiNXsvS6q74rvQo80VESbUO5lY9f2yE
9Ho8s7ryXO68JM+2aaffCfMyK9CGvlFYyLAlbDnZGou1tTuRCvZ0tEZRylUcSdV9V5+qRjrOkiSL
6tzs13aTrpgZqTwtjMnKrV4TOce2co9wut5JlccHmhYi7rFQF12fnf9y+u7yjqgOit4ftVD7ZsmG
pFBmW3toPKq41lAer/9qf3BJbaSn+SfRCFK16Qr2aF/kBApGecoii4calsPHFhYMnmA9DF5tABN2
lwotWLs1xpVgJhVMlsCUSblhEcXUsFCwrIzyOhYxBuwJHEnXLdVMmZCC73Vqnoghk5hRmlSyUAn+
wPayVo0uliUMEcqSzK6A4CgAJN/fl4RHp2p1j5XT2qBGI+JojHwrVux+4JDLolxqEd8PwHV0Suhh
hE0Isqbssk8ZZ/8gz4PFRsBrZlaMKgMJ3qaQ4+Q/qkysWYXtUlGC7NhZreEeVBGYyA3sPd1cgBPl
KIYjehMezAph1EH9uY11q4eXMSMYMjgSMSJTwz3kEw4Agr1BRje7Yvb8hRkef+JItNiLkGPiQK+r
svIQ6R0A/o3A0S1VOKwoy30ha81QbQy5J0KgJYsQDyOwMdqsEpT6tBUNIa92fm638LYuQngbgT7V
+zK64/qBAaYPCC1Nvz+9eYv+ugK0Ms12WZ5TOKEemNjmMuQ5c7XELTZEAzYsM1BR/sXijILmUEZI
NNLwfEQ7psW8ZqEVCwgYsQjrLaHi6CJhP7NgaBXRkprCaKfbEOpWYxNaSNkMtarawGgckeCXmnaC
+l0gQLrz4SHDD3A8QgK1AaMMK5AyNm8sa7N/wMUByHk5thixIp4TWbECU1ukarMX26fIUgDIaJYo
WQB9ff3wLeWl6S2PMJqn1iD9qWfZyF3fnTdxwV9UI8VKpJhVlBVVbgu1Na9ZuTOv80CU1uWDR7Ag
dNlMA5pKQ3Cwc5owY21pyjlDhWB0mAUzhh4NV2xKoq9lgUzR1Nedv8hTsXNVs0SjdMR+RR+AojWK
BPLl9ebdECJasxAh2mWxSR2cXNxarV4T4eXzhnIFaswE0qixGLzUjRzTio1n88PGyfh241f8kfHv
dVbuxC4ajU/2PZ77JHvD4ww5eJBrzOCNDTaWTpb+85Tlb9z258Nom6dXVzFQd8AxCqXgziDbvZ+E
t+l5cKDd6PtUUOEmm1TtcujAQfjijLqmUDbwKTAeM/Qa6VjpONVQSdmbg6TNDUp4iuM2z0yU7n8g
5SqEZc751safFL3TBA/jigzCn+AYxbpubV2DKowcBpCsM4AtzxaRQylDCEdPY4h9NnpEB140rxIu
ph7a09M69BDfoOfFaOWmMhl7WWkZEIS57xOP/fIwS0zuROPZowxFmViw0ZIOhh2VyhSdAOgAYNUQ
ky3/HgW0rKsVO3HK3ZnIntVslWp1QcuCpJoFSemMPnecFuqIlsaLMENAHUtz9nCNYdW2E2bv2W27
sM5p8I/QdO0r7vxtuwk9HXxL6erpN1TcozKc3jpiKgmpdsVR79RTCtOZ54BuPfr90qgFbnbl9qtK
r+kDHYujyqp3GHhNJxWqqKgisqK0AhiF4QRv9AmsQJ0J1QbgV9SMU5yWqOC4yaaY1xapvK+GNdeZ
XsOqt+hROG9BxdYhW7BGH7nETbcr6O/cstvtfuSUPEPXdX3q/JFTaXAf1B2hvzFi1Vpjp4AubSSw
9IGGHo7hQ0aE30ijPet2ja9/yrObkFCkslj0awS5SpgfHhrt+cee87XtUbTtAq0rg6FNA+2Zble1
BtgRo4M25YqtiYfVVuyXy9O71fjVYjg7eQyGk8fJcPwqeBWjGLjC84KuXREl/Xrpsy0Qpd3XdPbS
HqrFoxElOcRe1F+j4PSu+2GEjpgeXsJ4DrRydSC4d7PmiyDXE0aN3HZzONPRhZUu9M2bR2KqbjYF
0O1tlyYyasjd1O+6uwjTkwrODvvKdLO3m0urc0xvD3EYdUqqSB0MuxFJ7m5gmP/pAp4USbIM42g+
C/1Q8GSZTHks5ok/T5bTpZjH00mcxMvxnP00oPuodtfxRh0AT16Ie3st9vqP3D6NNCM2o4eLwEMe
MI9uomN/5k8wtMtPovlyGc7DMJr48WTOkwmPJtMkjqfhIpyFi+UiETP87PJGPogy+9x6j15hssq9
Ho1H9DTy2T0FuZcCjB/pctTGRBY05fuTIBifYH5zdu2cNJrCNiKkFFCStl68tV31X1eX3Wq7OH7s
9PV1Y0w9q2cYKDuVmR7lPa4+KBkuSNZV6OEHFdZbWcdNH0ZM3LuW5+zTNtX1QSTURiF7OsKe28sg
3GF1VK6T6mZPATkFrfFjLA1KRbdU4TDX6Pg3Vfjrje0wYFmQe2j9X85pV/ZsbfXRFr7ady+q1/R2
/PU/uQ+hIw==
===END CRASH DUMP===
