### ISSUE TITLE
Tiles are not recognized using LevelDB with $level->getTiles() (perhaps other formats?)

### ISSUE THREAD

**Issue by Striker209MPE** [PocketMine/PocketMine-MP#2949]
After loading a Level with tiles (signs for instance), I print_r the $level->getTiles() and it displays:
Array
(
)

**Comment by LDX-MCPE** [comment]
This is not a bug. You should use the var_dump method to print objects.

**Comment by Striker209MPE** [comment]
Oh, my bad I was sure it was because of print_r :D

**Comment by shoghicp** [comment]
@Striker209MPE You can only get the tile entities on loaded chunks
