### ISSUE TITLE
I found this Bug ^_^

### ISSUE THREAD

**Issue by HalkWise** [PocketMine/PocketMine-MP#2950]
PocketMine-MP Crash Dump Fri Apr 24 01:10:41 UTC 2015

Error: mkdir(): File exists
File: /plugin-4.phar/src/SimpleAuth/provider/YAMLDataProvider
Line: 63
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SimpleAuth v1.6.0

Code:
[54] 	}
[55] 
[56] 	public function unregisterPlayer(IPlayer $player){
[57] 		$name = trim(strtolower($player->getName()));
[58] 		@unlink($this->plugin->getDataFolder() . "players/" . $name{0} . "/$name.yml");
[59] 	}
[60] 
[61] 	public function registerPlayer(IPlayer $player, $hash){
[62] 		$name = trim(strtolower($player->getName()));
[63] 		@mkdir($this->plugin->getDataFolder() . "players/" . $name{0} . "/");
[64] 		$data = new Config($this->plugin->getDataFolder() . "players/" . $name{0} . "/$name.yml", Config::YAML);
[65] 		$data->set("registerdate", time());
[66] 		$data->set("logindate", time());
[67] 		$data->set("lastip", null);
[68] 		$data->set("hash", $hash);
[69] 		$data->save();
[70] 
[71] 		return $data->getAll();
[72] 	}
[73] 

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1079 [Protocol 23; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-787812 #1 SMP PREEMPT Tue Jun 4 00:57:38 KST 2013 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
ManyWorlds 1.3.2 by aliuly for API(s) 1.10.0
ColorText 1.3.0 by Heromine for API(s) 1.4.0
SignShop 0.9.2 by xionbig, xionbig for API(s) 1.10.0
SimpleWarp 1.4 by Falk for API(s) 1.0.0
AreaProtect 1.0.1 by Comedyman937 for API(s) 1.2.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNqtWY1v2zYW/1d4boElg2Vb/o4L7xak7dZd0/qaFMFhHgpaom0tkqiRVBy36P9+v0dSspz0dlu3
okCkx8fH9/F7H5Q/tUySidYsHPbPpoPJdBi2W0IpqVqzTy2zL7DUevHh5vzdm1dvfmi1W5nQmm+I
mt3GiTo5nbGXSSqYuE+00WBY4w2r3SItN0keDDvFlquuVlH3KsmKVJyXZtstlLxLYqG6/zm/fP2c
G77wBAhIkxwCxoPP7ZaTAWmHrWCIZCxIu9EQK0vzGaTRCI/0d2xJRblKk4ityzwyicxZmSuxgX5C
LVK+F+rklfvLnhb27+kn2juxe5fmac4zwebMqCQ70UYZmcodNnnm4LuNMG/AcnJ6evqMNk79xu/L
HMrfnjw120QH33kPEDuZ+FKmMPDklHXYsuVE6e6yhVd74KfeZ7vStW+dfZYuW078WW3muOfMHIdf
NPP3jWyzp1uut9bWcf8rbR0PKltd+P+aqd7C8bDSJsZmaJOLHbuQ+TrZ/H2+bHuJsxlhzp07ap4b
fKeFOVm2Ki+CJmgb5ceJt378pQ2phGpf4p58kZtrkxTEmpdp6hinX2KkYBGbi5rlO3vAx+9wFq1M
PDAmoedQwpQqZ54RXjtPU8/ar+E0oWC2kGdG8Qgp9XPrSY9RRhcyuhUmQyIul1dC3REQIgU1npdZ
cXLa+qXd2ohcKJ5SHmJZA36QFXZGsbiD5FWZpDGKSm9yhixW0shIgrc/aLd4kVjOsN/pgXOTGLz2
/uA/bFD8Nk1WtKczsRJKijHeXyd5ec9SGfF0K7Vhg06vMwiDyXQyDfvsSciuLhds8e7Fi8vFNbsu
BfupzNmQ9Xqz0WQ2mLJ/XV2zfi8cMK6yu0kKycW2gNxRZ9zp4+2jyGFSq4/Xnlv8IHV1Lgj2heex
kkncqouXJg81yhfevL5HNa3pQyefY0EqTVFZ2HBcIhzsWvAMi3orN9skKigS1qE/Y98U+/Aucr5K
BVQ1qhTtViwKKE5ysKbl2jxvEjL+oL4i4E29UsnJ6Kvr83fX7xcg7MRKJ4b03xpT6Fm3iwhuy1Un
kln3oGij2JMvLnm+v5EqjXXDAQ3isQMG1t8NB/A0KdP9kbFh7+utdeKWywwK7KwCy+UlLdX2Lt5e
Xd+8fff6edNiylfYcoESqa7FvWmYcqA9tORBKH8USlJeHdky/HpT6oOXy6YOf8CMq2STX21lcYRI
T2oa0eucPQzHPVZWyQbE6unvikylAaGw1uX3jLEoBAi9Ih2eonLfoX7zjlSbbi3FGkyIvOGqeJSE
ltgwGiE5MvglT2+PbPwLJmp74g4nVqnmT/8DMTtXgiYlI6Im+JrUY/j1OuFx5C5kJuI9cH82mBwZ
1P96gxrH/5k08rVC5mLfsKVJbdoyfGwLlRk0pTUC/tPiDdYeEP4uTDZUWi6P9fu/yHxQH4817DaF
faaOwRW8gMVKI9t6O+ifhVAmEdRgnizqNz/QMJq4l2qZP7neluy8UKw/YP1w1h/NhkP2/vqCutqI
GJy8gFw9X5b98Xj0g8hEnrCLxOwdocFWSGXm4Vk46BNxg00ZBu95j94yfh/4sWs+shRd8F0eFA4H
iNk8CIm828IZKfJxLtdrIrgIBL+VQu3nMm+QVIRdnisWOlJJYQX9iPRg11tuNHPq/tNqIE08vxEp
3CrY904XZiSjcZE5C/7RMIZuMvNcqoyndjdsUfsgTbLEzPuj8SURaTILyoImuUoPnucS07XwxgY8
2ibijrQw2mt/l4hdEFPFAd88tM7gKaboYJ0mm21tuHMQzxOoUO11tEyuKgKuSnEkVX1+cVfULknW
6yQqU7Ofu4DYAcxIFWBcNEm+0XNrBNRLXYhtazvQtBBxg8V65OXr82sike87Bdcae+L5t/YfzCiN
DGjI9NrZYAbNaK6lgnNqbHgqTUf1BEnTN+GWUWlgkYVsCcXpwkLIZZDBDoNDcLkAkhFvoQWrLMNI
JhBZwZAqGg/csIhCY9hKsCSP0jIWMR7Yo4whWVcEEbkmAQ9lar4WbSaxojSJZCsUs1u2l6Xysliy
ZrAtWSf2BARHAeCYHiD4Da4plbhuLNYc0dFsJ/NvDONFIbhi5MIMxmIoTfdQ3+HT2r3bCtxMi43i
MQR0ljmB1QmbLXOGbFYC3gYJWqQ835S4dzO6/FqXeWBr3Jrd0Jt8tE6lrRdbEXkrjjdCgaosibyz
S26TQsSJ65X01n2N4H6Q6w+vrt5+GA/Ogv4H2gc31oJmuFeJfLNs0UE3W0G+o8TTKJwMVjLcIq1/
canIdYpkit2y9abVFHrgSRgbUlwYkkiwLSbn1AY5g2CHq8ORa+SMAF1vSxNLyhn3GYKUcRcUFqVS
i9ipdU75xwio0IT5QZzdJZz9m+oOWGz9CfzKjFE7oI2YFXaME0q1hDb+FBcq7gWxUgOEaB0AgrXu
fPEKnOhLMfnpsBBArRWUOoh/YStdJQcWM0p2BrgCEaTqas88jsDu62K9enDDkyvqUhAg830mSxQ8
g9jD2kiTryOA2AjoSborQYWcNKMIBaVzW6XRmzJbwXnIjnO9z6Nrrm8BYHWLfOjQ+nv41MKt0pm4
tkrmdKoBt24zW2eYr0dAYBtWZXCCpt5trURTJFpW5kgEYuk4I4xLB+SKkvcojGgVezLAIjevVSMn
WXXs6YHXb8b6lDO5MESoUwZXo9SpvOIG5ZoAwKm6QFMYsNobyGJvczrJFgS/ynYJwLsStfIAU6Wk
ZD3rV7/CUEDV3pDsNgtCWkIDoGCRkvbYwFSqQM3R2CZlwym2BBOQYoctCo2NP+0F0evUYT+ihcAJ
c9QgAOVi8b6NvdBgBbfukthsXZSXedPngRU/YxMfwUNstXVMg7XDzmMgacvTdRfFlQFCt4Agup0/
CEcyGnOodNBAxMgwHtfBaMhq4Pwe5TehLslTlFfyNZ17k+RIXlh1rWh8gdvgAfZ+kS/o+bhUEmhp
EwZlOqws8iLwr81UoFFhVW5s9F+t2XcsRJSNi6WmZLbLVSJrZg0QVYIvfSRmLDykp2ZdSqdSO6di
WI5147yqmR5ValGlLakMI1yPsqweWGSpDbVLzthWCrslcFtmLIvo05Or4LDFjqikKcAGeK5xcUQN
aspH6lAPNI3j7QT0SBtCnLRBe/Lm7fWLGdor9uJ/VKKd5WhnVpC9jVDUrHr+5Fq9uvicHwUqQuVG
mfG2Wvwoqj7QhPBiCDP9nl3QDLAA1iHZAojGC6IHtKFCzxL1pcxvA58S1sHnKHK5saWA1mjAy62t
fga1ckkSmAua9vA4Y9P/vZUrUGMmMM95GUuC933gmOqcfbTb+j0XrqethJO2EmvKTjvNURZTBGqp
bsZrlAMn+QpjFcKJtphQ6xbUCoq9H1PcaQRWN6ja7Flz+ipZlQqf2usytWxSI4iBbQORK8ia4KZo
NgB4ILZy1a+SyrhDjaaPv/TFksINX4ja/hruLhjk0CoYl/ye8Yd+QQGPbM10Pn0Ui2GPtr7DqFPq
xjYfB84aA7zb6nFB/DM2+HPItXO3n+QPtmBCwETmAEejwSMjDx2ssrPz2FBfQHY8sbMF5ohSeCz4
/a5vvDLfaPReKiAIWDUD+YaH5yH7tp4dO0d9zU0npcBo91F4FP9pXQpZlKnXxT9TY2gK7jcsj2Yu
WomMgyS3PoLjxr0e8di3AKvE5C4wgUW1prhSYDOUU0PDqKeGPrvp7mDF9A4AQxDyspixMyfcpYe9
iNliWsmClAnt8geS0BG97jgdVBMtjWerBLF3LP7a4saeWTUsMfv5uhqG3ETjIOtyyX8YqFuYnZVo
9D2m1GX/iFpsiwRXoQPS6PvzzB3ZadyEMKrU+jl0Wpc+PBtxcqszZ7DKA9+vahZHlUVjdL2g24sd
p0UqC8qFNt4Np1kbdcEPJ+jVa4HMgXGo2zm1PmLyLackbyAbG0KY/wbTaKvlBp3UuMJflTsvjTzi
liv5Bw2dU3a73ZdckiYcU/XMDQ+cstm9UA+HfK/ErNLGLgFc2khA6Wd6DNCN2owIv5BEVwOr9ty8
91kjJAQpujqR8vVV2mbol66Rdoq1t3ptOymZnaHBJlDUt76G6vZUq4B9YnTzplQZ2rf6tBmj6/es
/2zSHp3dh+3B/aDdfxY+i1E1XB06MbgCRpT182mP4aaotXsbjk7tNVvcG5GTQ+x39Qt0ocYPFgSh
xiuawaY1sxDF/TwiVv+if0txsR+431QC9wvOR/cji/uRZhWh329rfrrC5TFXB4L7obh6K1Vav+Dq
Aphb0WFoha1NUa9ussMz/czlvlqC6VftP2H27We/bOVulTUzZqV9YQ4WGE4KxQ1zrxav7an0XETo
FIe9exhsf8vxT2xEXxdDspwF9LWs3xv1Bnh8+gpxWw8mA8FHcTwaDaaTcTjsjfm01+/z4WrKB5Ph
MJyu+sOeYE9x0mJLbiG3uYOlTu4PTnezs/YMIRn6TqxT98UMVHveVIzWEccEN8SxvfVkEk2m0/Fo
hKMHZ/2BGPRWZ5OzOLbn6W0mDy7UNrH0saWJcz6YjbwVOWq/qik3gt+iIjhHdUag7Ln9XBN2Qsvw
MSmqX+uGrc+f/wvr7fiS
===END CRASH DUMP===

**Comment by LDX-MCPE** [comment]
This is a SimpleAuth bug. Please do not report plugin-caused issues on the PocketMine-MP repository.

**Comment by HalkWise** [comment]
ScreenREC Users share video to you
