### ISSUE TITLE
Wrong messages

### ISSUE THREAD

**Issue by Sulfatezzz** [PocketMine/PocketMine-MP#2952]
When im starting my Server i will get this messages:
21:06:02 [INFO] pocketmine.server.networkStart
21:06:02 [INFO] pocketmine.server.info
21:06:02 [INFO] pocketmine.server.license
21:06:02 [INFO] pocketmine.plugin.load
21:06:02 [INFO] pocketmine.plugin.enable

**Comment by shoghicp** [comment]
Seems like you are using an unsupported distribution of PocketMine, we don't support them here. Please review the Contribution Guidelines or you may have the permissions on this repository revoked.
