### ISSUE TITLE
 [ERROR] A level 8 error happened: "Undefined index: width" in "/src/pmf/Level.php" at line 311

### ISSUE THREAD

**Issue by mydevelops** [PocketMine/PocketMine-MP#2953]
Hello, I am getting this error on server. When I connect to server I immediately die.
Thanks for help.
[ERROR] A level 8 error happened: "Undefined index: width" in "/Applications/Games & Fun/MinecraftPE/src/pmf/Level.php" at line 311

**Comment by PEMapModder** [comment]
Please use the latest stable/beta/development version...

**Comment by mydevelops** [comment]
ok, thank you
