### ISSUE TITLE
Error installing 1.3.9 pocketmine

### ISSUE THREAD

**Issue by mydevelops** [PocketMine/PocketMine-MP#2954]
I run installer PocketMine-MP_Installer_Alpha_1.3.9 and I ve got this error:
[PHP] downloading 5.5.3...mv: rename php-5.5.3 to php: No such file or directory

**Comment by PEMapModder** [comment]
It is PocketMine 1.4 (development version 1.5) now! PocketMine 1.3 is no longer supported.

**Comment by mydevelops** [comment]
ok, thank you
