### ISSUE TITLE
Corrupted map

### ISSUE THREAD

**Issue by mydevelops** [PocketMine/PocketMine-MP#2957]
My map not working on 1.4.1. It shows level not found, creating new one.
So I started my old server 1.3.9 and my map stopped working, showing error
[ERROR] A level 8 error happened: "Undefined index: spawnY" in "/Applications/Games & Fun/MinecraftPE_1.3.9/src/pmf/Level.php" at line 85

It is possible to somehow save this data.
https://mega.co.nz/#!ut50BZoR!28yuTpi3yFstjLwysv6ILHsNCew3yODHlQc5jWOO8qA

Thanks

**Comment by shoghicp** [comment]
Stop opening issues for old versions of PocketMine.
