### ISSUE TITLE
Super Shadow

### ISSUE THREAD

**Issue by HalkWise** [PocketMine/PocketMine-MP#2961]
We often see this shadow area when blocks or chunks havent been touched by light and it reloads slowly and can cause crashes like after placing a sign on a shadow area.Please fix this And pls Remove this shadow area they cause Lags =(

**Comment by PEMapModder** [comment]
Invalid but open?

**Comment by HalkWise** [comment]
Its complicated

**Comment by HalkWise** [comment]
Ill send  a vid if thats ok so I can prove it
