### ISSUE TITLE
unregisterGenerator seems not work.

### ISSUE THREAD

**Issue by MagicDroidX** [PocketMine/PocketMine-MP#2962]
I made a map with a floating island which surrounded by void.I don't the server to continue generating other chunks so i use the "unregisterGenerator". However, chunks still continue generating. Am I use this in a wrong way? How can I disable generation of a level?

maybe add an api: setGenerator?Than i can use my custom void generator.And that's ok!

**Comment by shoghicp** [comment]
@MagicDroidX you can't change the generator of a level using that.
