### ISSUE TITLE
Inventory slots change rampidly 

### ISSUE THREAD

**Issue by xMDwesLARLx** [PocketMine/PocketMine-MP#2964]
If select a slot under certain cases, your slit will change automatically. You can duplicate item slots and once that's done your inventory will spaz out! I can't exactly tell how to replicate it exactly but it shouldn't be too hard to encounter. Pocketmine build 8 version (not formal at all)

**Comment by shoghicp** [comment]
You can only have the same slot placed on the same spot twice, it's not duplication. Also, seems like you are not using the latest version. latest version has fixes for this.
