### ISSUE TITLE
How to use maps MCPE in pocketmine ?

### ISSUE THREAD

**Issue by KiYuuKu** [PocketMine/PocketMine-MP#2971]
does anyone know how to use the maps on the server MCPE pocketmine?
whether there are applications to import maps to pocketmine?
please tell me ...
* sorry for my bad english

**Comment by PEMapModder** [comment]
This is a bug tracker not a support channel. Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue.
