### ISSUE TITLE
CRASH!

### ISSUE THREAD

**Issue by Shamil0402** [PocketMine/PocketMine-MP#2975]
Fatal error: Maximum function nesting level of '100' reached, aborting! in phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php on line 39

Call Stack:
    0.0312     369136   1. {main}() C:\Users\▒▒▒▒▒▒\Desktop\PocketMine-MP\PocketMine-MP.phar:0
    0.0312     364144   2. require('phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\▒▒▒▒▒▒\Desktop\PocketMine-MP\PocketMine-MP.phar:1
    0.3120     499632   3. pocketmine\Server->__construct() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:463
    6.9732   15517392   4. pocketmine\Server->start() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1748
    6.9888   15544296   5. pocketmine\Server->tickProcessor() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2070
    9.7968   28112272   6. pocketmine\Server->tick() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2188
    9.7968   28112304   7. pocketmine\Server->checkTickUpdates() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2395
    9.7968   28112336   8. pocketmine\level\Level->doTick() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2211
    9.7968   28037056   9. pocketmine\Player->onUpdate() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/level/Level.php:605
    9.7968   28037088  10. pocketmine\Player->sendNextChunk() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:1416
    9.9372   28285432  11. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:703
    9.9372   28285576  12. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28285888  13. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28285888  14. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28285888  15. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28285888  16. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28286032  17. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28286192  18. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28286528  19. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28286888  20. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28286888  21. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28286888  22. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28287192  23. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28287336  24. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28287648  25. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28288008  26. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28288008  27. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28288008  28. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28288320  29. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28288464  30. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28288776  31. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28289136  32. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28289136  33. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28289136  34. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28289440  35. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28289584  36. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28289912  37. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28290272  38. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28290272  39. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28290272  40. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28290576  41. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28290720  42. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28291032  43. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28291392  44. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28291392  45. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28291392  46. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28291696  47. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28291840  48. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28292152  49. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28292512  50. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28292512  51. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28292512  52. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28292816  53. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28292960  54. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28293272  55. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28293632  56. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28293632  57. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28293632  58. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28293936  59. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28294080  60. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28294392  61. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28294752  62. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28294752  63. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28294752  64. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28295056  65. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28295200  66. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28295512  67. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28295872  68. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28295872  69. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28295872  70. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28296176  71. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28296320  72. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28296632  73. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28296992  74. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28296992  75. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28296992  76. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28297296  77. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28297440  78. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28297752  79. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28298112  80. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28298112  81. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28298112  82. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28298416  83. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28298560  84. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28298872  85. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28299232  86. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28299232  87. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28299232  88. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28299536  89. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28299680  90. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28299992  91. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28300352  92. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28300352  93. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
    9.9372   28300352  94. Sergey_Dertan\PrivateRegionProtector\PrivateRegionProtectorMainFolder\PrivateRegionProtectorEventListener->EntityTeleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36
    9.9372   28300656  95. pocketmine\Player->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/plugins/PrivateRegionProtector.phar/src/Sergey_Dertan/PrivateRegionProtector/PrivateRegionProtectorMainFolder/PrivateRegionProtectorEventListener.php:227
    9.9372   28300800  96. pocketmine\entity\Entity->teleport() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:2957
    9.9372   28301112  97. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php:1402
    9.9372   28301472  98. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:670
    9.9372   28301472  99. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/▒▒▒▒▒▒/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96

**Comment by shoghicp** [comment]
This is a problem with your plugin. If you continue opening issues that break the Contribution Guidelines, you may be blocked from this organization.
