### ISSUE TITLE
Segmentation fault when stopping the server

### ISSUE THREAD

**Issue by ChrisVeryTall** [PocketMine/PocketMine-MP#2981]
Every time I stop my Minecraft PE  server I get this error message:

stop
20:42:27 [INFO] CONSOLE: Stopping the server...
20:42:27 [INFO] Unloading level "world"
20:42:27 [INFO] Stopping other threads
Segmentation fault: 11

I am running Minecraft: PE server version v0.10.5 alpha, running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0) on Mac OS X 10.10.3

**Comment by Hitechcomputergeek** [comment]
12:07:49 [INFO] CONSOLE: Stopping the server...
12:07:49 [INFO] Unloading level "world"
12:07:49 [INFO] Stopping other threads
bin\php\php.exe: Segmentation fault

Happens every time I stop then server.
Running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0) on Windoze 7.

**Comment by Hitechcomputergeek** [comment]
Tested on a proper OS (Ubuntu 15.04 liveUSB, as this computer is shared, but my crappy netbook isn't fast enough to run PocketMine decently):
20:28:58 [INFO] CONSOLE: Stopping the server...
20:28:58 [INFO] [UPnP] Removing port forward...
20:28:58 [INFO] Unloading level "world"
20:28:59 [INFO] Stopping other threads
Segmentation fault (core dumped)
ubuntu@ubuntu:~/PocketMine-MP$

**Comment by shoghicp** [comment]
You are using an outdated version.
