### ISSUE TITLE
time_sleep_until problem!

### ISSUE THREAD

**Issue by da123rrell** [PocketMine/PocketMine-MP#2982]
PocketMine-MP Crash Dump Mon May 4 03:40:16 UTC 2015

Error: time_sleep_until(): Sleep until to time is less than current time
File: /src/pocketmine/Server
Line: 2191
Type: warning

Code:
[2182] 	public function __debugInfo(){
[2183] 		return [];
[2184] 	}
[2185] 
[2186] 	private function tickProcessor(){
[2187] 		while($this->isRunning){
[2188] 			$this->tick();
[2189] 			$next = $this->nextTick - 0.001;
[2190] 			if($next > \microtime(\true)){
[2191] 				\time_sleep_until($next);
[2192] 			}
[2193] 		}
[2194] 	}
[2195] 
[2196] 	public function addPlayer($identifier, Player $player){
[2197] 		$this->players[$identifier] = $player;
[2198] 		$this->identifiers[\spl_object_hash($player)] = $identifier;
[2199] 	}
[2200] 
[2201] 	private function checkTickUpdates($currentTick){

Backtrace:
#0 /src/pocketmine/Server(2191): time_sleep_until(double 1430710816.3266)
#1 /src/pocketmine/Server(2070): pocketmine\Server->tickProcessor()
#2 /src/pocketmine/Server(1748): pocketmine\Server->start()
#3 /src/pocketmine/PocketMine(463): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#4 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.5dev #1116 [Protocol 25; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20 #1 SMP PREEMPT Sat Aug 23 18:11:19 CST 2014 armv7
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SimpleMOTD 0.1 by hoyinm14mc for API(s) 1.12.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
SimpleAuthHelper 1.0.0 by aliuly for API(s) 1.10.0
Afk 0.1 by hoyinm14mc for API(s) 1.12.0
ManyWorlds 1.3.4 by aliuly for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
EconomyAPI 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
CustomRanks 1.0.0 by shoghicp for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
FastTransfer 1.0.1 by shoghicp for API(s) 1.12.0
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
AllServers 0.3.2 by hoyinm14mc for API(s) 1.12.0
FactionsPro 1.2.0 by Tethered_ for API(s) 1.4.0
PvPWorlds 1 by  for API(s) 1.0.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
EconomyGamble 2.0-alpha by hmm for API(s) 1.4.1
ServerChannels 1.1 by EvolSoft for API(s) 1.9.0
ReportRTS 1.1.3 by ProjectInfinity for API(s) 1.9.0
Alias 1.1.1 by ZacHack for API(s) 1.1.0
ItemCloud 1.1 by onebone for API(s) 1.4.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
SignWarp 1.3.2 by aliuly for API(s) 1.10.0
MeTooPortal 1.0.0 by aliuly for API(s) 1.10.0
WorldProtect 1.2.3 by aliuly for API(s) 1.10.0
EconomyPShop 2.0.0 by onebone for API(s) 1.6.0, 1.7.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfYt22ziS6K/gOH1uOzuSrIdly+51n+vYSuIdP9SWkkxPay4PREISY5Lg8GFbmZ1/v1UFkAQp
SrY7mezOOZ1uS3gUCoVCoarw1D92EtcXO8ed/V77sNMedA4aOx6Pk2EUyWjn+B87ySqE7J0HHgVu
sNhp7PgijvkC07CkFXtChFYaJK63+/qYjTHKKMoSyRCEuTHzoBBLljxgdhpFIkgoB7DNU89763qI
Llzy6Hhvby9OZAQV7Ak/9XginL323kjadyK5cgNhBJtXoxaW2Ysjey+kZB8hxiK6FxFkhYhf4a6H
gXwPYjvH3c5Rp7GTRNyGyG87r9qsvsAuAkIr11ruyHTmCVZwsdXrHhy8hgpedTbiah+2AVeRMZ2q
nObPiWvfjSJpA9dktEtoupvQdA73BxvQxAmPElW8t1a8YOTu/kFvAwbLsmUQJ1FqJ7tm/pn0Q564
0OYzkJb4UnJHREzOPgs7aZQwpcCeeDq94m5wKRcLAwrQgkSx393tOYYnij4XLvTShRvEe8SvfbaL
HR2Jv6duJHa/ltaNvEcxfb3zt382dsT3GnHPHhFAlOLJzvGce7Fo7NjSEUhitzPoAo5pEoLYuzab
p4GduDJgluWIWbq4COZy9/U/ABtA9ghymkQiSaOA/fa3n1T6PqX/U0X6EFGhA4U4cu+BswXmypDQ
uA817ocltGr3h2Tpxs2f3fg2DZB3GdRAQ00TDYHIdl9rOo6K3EA8JuyEaSiMTQCSNVm71W53FPxR
O4d357uqyM9sOvVdO5LI490ptDUVr3XtR50cHv6brnUhYdC0HHVzWMWXo4x5Omry7Cjn2dFBbWdw
xxl5fAU64gfXAQlw566IGkylsR9C+s6ozDip264y49+Mkn9Dzqh0Te2gXKYAjX+bTuPQs9RQt5Y8
Xu5m9RGaAlSjOioa1m23dcO67U69MNhLYd9h13wIHciId3/QQo5p0KJ//qHM/1Dm/2PKvLGzEIGI
uIeqEjgfg8iCHHdafUfcAz2z1PUccLk66GyFoDSkLQG222/s8NAlyE631QbIhZtAtP3Mf1Ag4nee
O8MyrUPCkAYc3budSzdIH5knbe4tZZywXqvTbnXbDCR6fDVio9vh8Go0YWOesNN0wbo91hkAhced
I3Y2njAYifuMR/79IeBEz+p4p986aHUh9kUE0JidLkTbKtOScVYjJFCEB04kXWcnNykx8mbs+qEn
rm4m5xjTlBqJjYJ77RY4aDxNljKKcVQv5coN/M6+byO/iW2/ZXyDBBFwEGegCzVxY8cRIVCJBSEv
lvPk3EzwOZo4o2IYMiYRHgwIyB/djCefbm4vMelBzGI3AXID8F+hUQr+FOhbawklNkpyoDhltKYQ
ITYR3IfMeCkXS9cOS60bfG3jkJascZou3bjx5PR28mFkNm1nmSRhDCMEpHCZzlq29M2BYWApMeC9
8EIR1bJBZ5WZ0a4yg3tu6q3K3dr+/S1X6KbTJVWulNfzOvV0fmc0A2PfVyChxulUVfsMaq94sPok
I8+JDaKNxDLXe63978J1Hwh4IAJewvkzT/Doki8WRlOKtHJLOlX5uRSgfp2b+dXZaFhqz1c0J698
OlXm8Yl21I0dk669ojXQ3CHYZemvTkcXRnuNRLPBIE+tg3KDZSBm8LfW1kbOnU6rm3936Lun4z0d
39fxfYj/Th5pMqZToSgHWqbTUiue0/MpmGP/lgd3phibqU9oj1rF+RU9n+EDN6kg4iWyPAH3Ejws
GAhOSS2W041WdcvSfP6XZ3VsL+/A391UqGo6LZH1kna+5XEyiXgQz0vNLCVX+67zjL77Gg1adJ5J
Rjn2YhuYId0rYSmG8X/J2fowxsTqMO79Wwzjz3KWD2PVimcIg4a/5OgbVnlBqf+LdJqpal/AGA+a
kXNGt+n5rBkLz1tnDaVWWbP/NGu+c9NjIDNvuqb5BU1fyrCm6Zj6b9B0ILNouqL5Ob6k56lpuGnW
jESz4aAZaGb1L/Yu88rByTQJeZaup3WYeBTJkqovUsuavlu10hORLEUkHKvUnK+wXUbdLzFao/vR
ms9cpBmNKDn738i1GHM/Fd7nZWc6zetEj/nZxEfuF/EJURW0Z0lVS1tRr5eudxa5cbjqyqO902Ah
PMk+uk7kym82A8hIeUl36GH1jvszT6yrCJ1eURJN7oVLXhkvvl+RrN9tD5d+PtxV/ZXoMxcIaHid
LXkQCM+UtkpGZW5TbtXwXnpjILPUtKOvEMBS3dWO2uYOPTw8tARQg5hbyR16P7cilFFyOxkbjSvS
qnO2iu8DwxbXES+CuRu4yepbNbCCdjrNCTKCz1XgLi/rboxXm1XpsL9y+z2378pj6mtUNtSpuolW
ap9H+UUi/DNPpqYnVqRtFbg6e/sVSjq3pUCeb2P1L27MhIcTeW5anSylrBU6VQv6lnt332pOmPAw
kQ4YmqLuZ60RLoJPPApLS2M6qbo40/0XLM6UF4NKk5f1dZsYKHsAyl6iva/ERMoRDCpuerZm6v/M
yp+fvKgZxCLQHAloDqMdpeSqe9P7F/fXeqNoUS1U5DxDc5cN7KjeBR/V+uDtp3XCgfa5D59oY3lR
q1BCL/C/w5IDPnquB44bDzyC1iYic+FifU4kkqGIElfgPsWrUR5jZxLMxoLhfvk0mgavrmTArviK
7bN2+7jdO+4O2IfJGW6N9DEft+1P2hhSiJvI25PhYxIJX7CziM+haiMbrc9Jp9PtdjFxAcC+dDQG
nz829Q7syaHCGfKHoKn7G/rmpN/B5IclNNFz4+REBhhXnG/+PRXRqpwUAcNO5HyOSY6I7cgNCY/y
AZjPHcHSGPfFSjteRI1MnGpDWuy/pBuwa/lgNIlYEMjI5x6VgxZFq6bn+m5y0uu3rzARDxc1U9q2
zcgB90OmgS10k5vcXrriHioLkjiDuXfFQ9OBhnIAPOlRMc+TD8255y6WSQam2MQDF0iINQNUmi9n
WcKSR44to7z+8D7UOY47n7t26iWrE2Kv2sdLZNSMRZIAc+ITagNQ56n+9eRstirSYiEcA4QY8vby
dIJJ2AOtECwdDF3n5D/oH7QiTWQz5vdCk0A92lRdqsibywh4kwuITsWttnwPsrXyPZRehnqA2SS4
KRCOe+UovwxwVPo1eMUmSxELlrWM8UgwmJUxGG10ciRhNvZMwmaCuYHtpY5wIMDWxg3iGkuQDTlH
BFWcMZ+LBpM44YsRJZtFgt+xlUwjjYu5cwZtw/MAWAP0TQRSDlouQNFSqI6nUPMyTRyJnalOxByz
qfZhGXgTsXCmOwD16hQFgyELaZtX7Teye5ezX3BcAAiNj6bOOWaoprAgKJMHxpF/sQSm6VrYw1IE
kKzAYZAAe0ClAYm4W8xAlwEkqEeYvAVGRhPImgFRBfohjcQMDw8chlLIgJHQR0jqbAXl5xzkD8D1
uM1zjxkdwpniuY57HAVO04aRIor0NAzCJvQ02G2nVODVGNUq1CiDlS/TmMEwSpA9doxHhmzojwRH
PzY2IrcYmxJDoWaq+Jw14Tr1Z7jrP2en8SqwJzy+YyDOd7iKANmfTm+vL67fHYNouTF7cD0PuxPQ
g0wsYKhwjymloCprsFmaMDcBFMGPJGfYaUrKUBITCU5DC1uMlTV1Rcesg4JBB41QKl5dzNnPrNMg
RFhljN1I2VkXxhlG3bVQigYooco6JsYzBTxJsSW2WgGPcx4WA7wQx1cwgLIOwxHmw5ChcUOguv0g
LkqAFJcdkhEq0lRFjpkPWQsYqrotZDSRUhCgJGbzSPogfSZ+4C2Oy8SoHk9+rVMDwx8tI/XczWSo
+wX+18dlvBUhog1aVLdEnq45Jy/ngL1Mg7smigVKF400kKYgQXGgvBhlhmjRxouBhqCTWwAcooGA
4DHbx6J46CSC3kEVRfxCTjmKVboKjbTF3oOKB0QnoCRgvJyNPjTU8bYZdNGD6yRLJU6q3zKsTd3D
g82E8ghSHSZgGGmKARZtrwI6Zt3+QdFwJD5r+BV/ZLyKM1SHfITGuNbu7kEby95yx4UxWJTTZHBN
gzrFR2XxqxkRvGbb87uR7KK2tIUcg6IUXBFERmate7XJAwZSQz8taaUOaYpSNYYKCJQvztBoCnXC
cAky7jCwNVKBog+nUxHZu6IkjQ0c8NiPC89N7OWqppTSEATs8QX1PyL6QI5KopQMdP8cnAqWG2ti
DWhhGMMgSMQMkK0mKZFClUEXttb7ENqp8YhceMF4BcBitKEGnoyhRf92DC7axyrLlU7TDQgAOuGg
3UYYijUhF4GUs9IkLwV7GUGgoQEowihPRTWFngI6CoQGgUj9N7FDgzQ8ZkcKuXJ3yOkiLZXhAiyH
WEpXiEj7GH3gWFGeSGncn7nQoQpE+yjKMBxn5gT0GY+Xmbkg5mj5h67JzZeT85usCZ4fLafk+rSU
Gi5DF/yePBGPLB2rGluG1xOIJCdPCTpxtFo16AKVe6zaGwVNbQdyEJUqQ8MZOENPBTUqaBEZ4rAC
YRQJR/EGOwE1oGUCbQPCH6ExVstoxzpTK3PlUnMTDdPTK8NgpQuwUeBvAYqFkmzBND5kicrOaogr
bMG1uBqm4FqRUHZq+MhRNagIWkfAr4k4zqihLJCuOJEgS79hsAkeNp63k+HfEKM6xpEZPtPLo0ZI
QBS5jjB1BLJKJLVOI/k/5MLHZKOw2T6YLhcI1QbUIJ1qJQIoxNDPxrFCOrGo7Zihs33c/emw0T96
7DR6j71G96fOTw4oA6V4dmEWAxEY9CeDNluARMUqtt9/TU61eExEgAyhxb4zUDjGWTcUIiMKWm+R
n40ObQTVkfjvoNJETx3Ea6pjf1/UyTy1FzKzwbYui4PV3AO551GRoE6BZ7E08vIIuIMJbrED6o7a
Cp0nYZ678IswnrtVKy0A9DnOVytwlc+fqWOQOTB4IaswKVoAMy0gyDGaOx5dUq0YDm0wO0XZFTSY
jgHqEOvj7n4HW86aOEXutvvtHgR/uIB+m/cOe4L3Haff7w0ODzr77QM+aHe7fH824L3D/f3OYNbd
bwv2A9Q0WiJbaCWCKpax+1gwXZmJWAN0sKG3Yu6pSTKkUn0D0Z/bMMGd70O17fnhoX04GBz0+1B1
76jbE7327OjwyHGovnjpy4KFMQ2suNxSVzEfgBN5JwL3S9YdkPIJ5jagExSjWn1IWXGanGXLw1/c
MDviuU/nIZWuowswFNoFQRy9H7GPamCyk58Z9QCOwfEKVLmPSd/sQOc0eIPnUdk5mjxAfGMnrHOo
AAB+v3/cO5oGZ3pOCe6Xco0RlP3Y2ssmm+JHiDabetbiBniNABRqAnboC428HzEb1aX7eLJ3z6M9
GA57n0Vwh8d0P8PsfA8a3TQmqafqzOgeuv1g1Gyxh94dzGb37EjisFURfbS0SY3Zm7nBHvCxT7WJ
R2F/5yrRHWnicP2uFaJq+e4VNh03+q6V4kD6rhUqlfhdqwT1/T3rk2nSDEBcwVMopaFSxRH8ozGm
M4thpmV2y0x7UBrQTMrUNKU5bkyJuDCF+q6UCM1+9L1SUjXuSL8Uj2neU1MKqxRRNfUhAstcTrUX
bhmjmkGWa8X1hFJK6MgSz0Kh+ZAluDiTLoM4sqlcg6LHQ9cusWpZ5iY5AmaCtkilJCgjnJNAlhJx
jcc+WYkKKFi3Uq/CZCuBP5gDfEnKHQSeYpQ0E74oYfhCbru7AA+zlE4egZkg/JlwYPrVVDazVKny
EoyRRiAnZroGVY5SiSNlXGBPzSj4QoaaQlrv/ZN3N5MbSkVTeQJjAeQMzGfTT2OYPc3cdb4hwF2J
G254f2DCyZDmX4rriNcil7se+9lZTTrMErHrz8BnfTc+acaA/KaLVcxHF2f4rUgphxTE+fiXy4vJ
0Hp/+nFoXYyvT6+pXCCbyK0meOJKGOZpgMuvKtW0xnEGjz0JfQQujMzTkoiH4Iosmhnr57R/nqGB
yXAGSSsXJUiNkuOSZTPguiL0upv34JVJPBVCSRImqM05bsk0QwkyqMYkEvyAqwFNT8J0jJLce6A8
NpuDeTXNAVPvuOD5wdQFJ/8y0NpqTpfBooISKu+SGplHAhfym7gER9NkSrQf1QwaOBPBnEz8CKmX
51lHZZ1xefFmfALgntZvWNRzaBCA8oEJ5j2WO/vLX2o7/09/Upl/dP+/QfeD6602GnC5H1zfzAu+
xDs7F0j+HOqYBh/dKEm5x87diJq7YuM0xCUSLKQXJgpvWq2F4f13tgt2uQVsfs1GwEuE/te7AYh9
GtCFBofV0ARE7AYyEDAhGePGDS24gddHqz3ccVwEhcYi3bTPFJtFTmsBQh7hCqkBh3MdzVWYdPQ6
nfaBShxmU/E8q9uFrL/i6lM5b2OmmtoACFSQQzUm42oFJTgT7Jy2EfLsQE6DiVrlHIMkJqtSt1Ll
YxJ/9h5YTps6awBXagfkigccb1Cu5+MqyGwFszFDdMJI3rvYTbMVyxyxaXAxuj8wobStAkznE5T5
+rxpcKulHfAhH8YwKrhPnZctoLfQw28wkJIGdVyD9m8azOEJbzA8Bgbp+IH+SoOBES5hVRjZmASV
0TkTtU4IVSQ2FEsd/AjcRwwu6sq+pWUOKoG0tP6jwZQ/TiFH5GHFjFYkk04vjyUSWo63nfO4Jx+M
OH6FFvo2+VYL4sJ1wdQXDjRU0EoucotW26EDFqCtmM/vQIpxV0ftdjLV6Wo/Hbr7EvRFihtpQ1zK
w4UrJZIUY/d0TbIBgy1cRbhAz3bt16xzdDRo0oSbYCdQdQD0LmhvFf9j1rf5p7CVRjomKB8LQ2/O
rlD7xDU6C2SKdBqoV1p/wJUH9pF7KUWvOPaeimcIWzFODzC3TR+0PK4nDESHDm+o7owW+zevhTyf
HFpmtGBSbs1lKAjLjf40M/UmN2XM5/oLAR74KrZCGdL9YCviDxABfw/Hgtk6Hi2sWOAxE1D8oPLC
lJr0f+ijmg3TgWp+rARyrf40kRZYZOCVNddqOZDsPmtrFtaQap81tj67SaWhmAuD+xmIZpF8gM4L
N0PojUbLXqI+p5rSZN4cYODD5G1zUID4ri9wEkNjXzwme8vE90oRPHhBysmy8SSgMiMb6tWA2VMA
20FxQ82ihzUIbjw5v/kwKUIFDF2uT0MDVvMNO8CRthVJmWypStow47Xo9YgnYLYjUuJvOV6563Ry
LnUWWiBtXAwoJD6TFH3JfXNNBAxK5imQTGKeh1DtB2nAdgXi0U0sGVj44IJUsm/KuXiE9kEjl2Gl
WZmVttD1+G6OEQb2it2APfBsaQ0Ap8nNzEf4X0bONMBxbaUh7qjEZTYuwdzQnnBLbYwS//9zLiEQ
JytPnEx3bDA60TF79fbtAHcYd37Wof/cQ7CfX1zArDQ7mbARB75g8OYN4lChJyvdUMCsNNM0mxEo
qlXoWTXWFDBrvBN43dnZhuPwMMOBoWdUWlvArLQYmvUozs8zulXoyTo3FIA6gaGmkjSGL7i9YLBR
AdA5l2dCxTKNbLEBCrws0Gcz7RqUAPzQc21QJ3MvjZdlQddm3Ar1PKp1rD4xB0yuJQJbOltVGU1H
we4/AxQU6IaWFjmWzx8tT/kdnXZ3P/vGc56u14KJlPVoLWmxsoqEAOgAIBqXiFvFIdbNNFGhrZod
CcLNkRRNKOlj04/B3Koe6bbVp8pVjAwEnbCz1PEdyD7YV58mUIa82VGfZh4ozlgxo93OvrNjoxZN
wIuSne7gahqg+2bNOMwglSmob57yraxZigdTTFvUzvOe7lkNuMR5nNhSGRllbFPsfqGswZX6hCxw
UN3Mb+2ofgfmgPH2UDgtWkDMy3UO/qy/1kCSxFM8aOsvhFATJgvcShs/7sujQBliC5jpCX4X12bi
8qh6sKsqd/hUDvSuBapsW9vxsAZKm0WH1J4Gy4Ykayas6TIjSGeIXe4BL6wy2w7VJwDgcrRFEgBu
cpXi8dVkhJFiR9SMQGk/Ca1sltHtq09I/rvXwjUlC8/WVnHG4PYnwg+trdKGq0t3G5RAajQLSPFm
CIq+62Z0atBZ2SDMpKN7pT5zgOQpukh7Pg3hBm6rJGU9NRh7OBZzCCQFF8pIlWIqLemYkWkAw9ml
g5SF2Azfjc7GeWAa4K5MaCtmWYE6TGoMTjN7jZcoreBG4AF4Kw1cO+uwXKoJQLvKC7smz89XVupQ
qzPxz9AMCpqWeSx6iayKDqa5OOHJA6w0WzGmuLhRTN8fbi9rZ8GUga/p4VFMPSIOW71Bq908H36c
BqcLoq03Dd6CPU0jXDCgk7nL82vi+6+YcgaTNJj0k4a4ltmilo68G4+b12IhE1cfAMDEi/PrPIhr
TDp8F832s/Al6ByRTSOpGvBSv+SR68nlVQaK4U9vsth4dD18d5PHxpd5mfFYLQNi+uRy3BzfjrLo
SD+TRRxUC1JzvQYVZ+tRdDlxGrzXgx/X3NPgLpB0HM5ce1e1GmsKI+nxCNL28O4VTF3/eunOzHw8
NDOgQ8fAo+x7j0xb7drFzo0XS/hi+JrGFxkIPF3B0W6ZWHHFpwWKbR0IMjMfBHtLH/HNwGiKffay
JRAkOPPBLQ9kKdErHb1O6/Dg4NAIVoFlsCig+61ur9czgho6ToPIhdkbjA1X6fijdqs/6GngPFKA
xyJ5LnSl5eXRiDNPsdCrmuKRQddFPKKF2Tcp2m6HeTrJGHnqEBWGLmidBtjkOmqI4bK+WnysLt/e
ivvcLtHBon2nNzg6Eu3BkTgQ+/1Zp394dNi3hZh3uX0IlvVAHDmHB132w8t6S1FnzpnUzgeuPZVj
VVhwiPUSUr3uAvgkxK+3YC7r190Wfqi/agHeXY2yM4Pk7eENMYTHw2bZd23B95CBHFVLoUSj73Th
bx/++ixe8g5+dMFBxq/+AX71BhTrd7oMtLPwHfADs9

**Comment by shoghicp** [comment]
That's an interesting race condition!

**Comment by PEMapModder** [comment]
Wow! That's rare. :+1:

(Using a fast system reduces the chance of having this)

**Comment by ZroidXYT** [comment]
So many plugins

**Comment by HmHmmHm** [comment]
![11](https://cloud.githubusercontent.com/assets/8337568/7491767/cbd6bffa-f427-11e4-93e9-1f8080062416.png)
it's still causes a crash

**Comment by shoghicp** [comment]
You are not using the latest version. Please don't comment on closed commits.

**Comment by da123rrell** [comment]
That is the latest version

**Comment by shoghicp** [comment]
No, it's not. Latest version has that method on a different line

**Comment by da123rrell** [comment]
FINAL_1.5dev-1116 (API: 1.12.0)

**Comment by ryanty0304** [comment]
PocketMine-MP Crash Dump Wed May 6 19:03:39 KST 2015

Error: time_sleep_until(): Sleep until to time is less than current time
File: /src/pocketmine/Server
Line: 2191
Type: warning

Code:
[2182]  public function __debugInfo(){
[2183]   return [];
[2184]  }
[2185] 
[2186]  private function tickProcessor(){
[2187]   while($this->isRunning){
[2188]    $this->tick();
[2189]    $next = $this->nextTick - 0.001;
[2190]    if($next > \microtime(\true)){
[2191]     \time_sleep_until($next);
[2192]    }
[2193]   }
[2194]  }
[2195] 
[2196]  public function addPlayer($identifier, Player $player){
[2197]   $this->players[$identifier] = $player;
[2198]   $this->identifiers[\spl_object_hash($player)] = $identifier;
[2199]  }
[2200] 
[2201]  private function checkTickUpdates($currentTick){

Backtrace:
#0 /src/pocketmine/Server(2191): time_sleep_until(double 1430906619.3338)
#1 /src/pocketmine/Server(2070): pocketmine\Server->tickProcessor()
#2 /src/pocketmine/Server(1748): pocketmine\Server->start()
#3 /src/pocketmine/PocketMine(463): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://X:/PT/1/PocketMine-MP.phar/, string X:\PT\1\, string X:\PT\1\plugins\)
#4 (1): require(string phar://X:/PT/1/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.5dev #1116 [Protocol 25; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT ###-PC 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

We expect you to make rush ^^

**Comment by shoghicp** [comment]
Stop commenting on this issue and inform yourself on the commits pushed to this repository. You are **NOT** in the latest version.
