### ISSUE TITLE
Lighting bug old levels

### ISSUE THREAD

**Issue by QuintonMostert** [PocketMine/PocketMine-MP#2983]
There's a bug on old levels that lighting goes bad like it's night time permanent 

Plus any blocks broken or placed in these areas cause lag spikes and occasionally crash server please fix this or at least make a plugin that reloads theses areas I think it has something to do with chunk height..

**Comment by shoghicp** [comment]
Please do not open **duplicate** invalid issues.

**Comment by QuintonMostert** [comment]
How do I fix it shoghicp?

**Comment by QuintonMostert** [comment]
Or are you guys working on a fix? 
How is it invalid?
