### ISSUE TITLE
Time sleep problem what do i need to do?

### ISSUE THREAD

**Issue by HalkWise** [PocketMine/PocketMine-MP#2987]
PocketMine-MP Crash Dump Tue May 5 22:51:43 UTC 2015

Error: time_sleep_until(): Sleep until to time is less than current time
File: /src/pocketmine/Server
Line: 2191
Type: warning

Code:
[2182] 	public function __debugInfo(){
[2183] 		return [];
[2184] 	}
[2185] 
[2186] 	private function tickProcessor(){
[2187] 		while($this->isRunning){
[2188] 			$this->tick();
[2189] 			$next = $this->nextTick - 0.001;
[2190] 			if($next > \microtime(\true)){
[2191] 				\time_sleep_until($next);
[2192] 			}
[2193] 		}
[2194] 	}
[2195] 
[2196] 	public function addPlayer($identifier, Player $player){
[2197] 		$this->players[$identifier] = $player;
[2198] 		$this->identifiers[\spl_object_hash($player)] = $identifier;
[2199] 	}
[2200] 
[2201] 	private function checkTickUpdates($currentTick){

Backtrace:
#0 /src/pocketmine/Server(2191): time_sleep_until(double 1430866303.2961)
#1 /src/pocketmine/Server(2070): pocketmine\Server->tickProcessor()
#2 /src/pocketmine/Server(1748): pocketmine\Server->start()
#3 /src/pocketmine/PocketMine(463): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#4 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.5dev #1116 [Protocol 25; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-787812 #1 SMP PREEMPT Tue Jun 4 00:57:38 KST 2013 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
PurePerms 1.0.9 (v1.1.0-INDEV) by 64FF00 for API(s) 1.12.0
FactionsPro 1.2.0 by Tethered_ for API(s) 1.4.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
FineJoinEffect 0.3 by Asidert for API(s) 1.0.0
SimpleWarp 1.4 by Falk for API(s) 1.0.0
ManyWorlds 1.3.4 by aliuly for API(s) 1.10.0
Healthy 1.1 by MamayAdesu for API(s) 1.12.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
WorldProtect 1.2.4 by aliuly for API(s) 1.10.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
CustomChat INDEV by Array for API(s) 1.7.1
EconomyAPI 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyProperty 2.0.3 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyTax 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
MeTooPortal 1.1.0 by aliuly for API(s) 1.10.0
FastTransfer 1.0.1 by shoghicp for API(s) 1.12.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
MCG76_WorldEdit 0.5.0 by minecraftgenius76 for API(s) 1.8.0
SimpleAuthHelper 1.2.1 by aliuly for API(s) 1.10.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
KillChat 1.0.1 by Array for API(s) 1.9.0
MassiveEconomyExample 1 by EvolSoft for API(s) 1.4.0
EconomyAirport 2.0.3 by onebone for API(s) 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtXGtz2zbW/isYJTO1dySZutvq6874dZw2rd14Y2fzIcx4IBKSUJMES4CW1U7++55zAN4kJ1Gc
ZLud2V4mIi4H5zl3gGD+bBkZi9a0Nxx4h+PxwBu0WxHX5izLVNaa/tky6xS6WyueJTJZtNqtWGjN
F9iGM290JER6kydGRnv7U3aFj4wemVEMhzCpWQSTmFnyhAV5lonEUA9Qm+dR9FxGSC5d8mx6cHCg
jcpggQMR5xE3IjzwDi5VcCvMhUxE7Wfn4rKLcw50Fhyk1BzjiCuR3YkMulKkb2k/PAb6I3hqTfu9
o167ZTIewMPb1hOPPTxhDwcCyi3kocpnkWCVFLv9o3FvHxZ40vsgLW/iAa2qw/dtT+cHI4Pby0wF
IDWV7RGZ/ofI9CbDww+Q0YZnxk4fbE2vBLk3HA8+QOHmJlCJNlkemL16/6mKU24kYD4Fa9Hnioci
Y2r2mwhMu0EpB/Fo37/gMjlXi0VtFJAFi2KPVntJ4RNTdx2XRvlCJvqA5DVke6joTPyey0zsfSmv
H5Q9mul+6937dkv8pzxuZ48ApqxMWtM5j7RotwIVCmSx3zvsAw3fpGD2MmDzPAmMVAm7uQnFLF+8
SOZqb/9PoAYjBzTSN5kweZawt+++t+1Dan9vH0bwYH+NLeFM3oFkK8obLuFoTxzt1RJQ7T01S6k7
P0j9Kk9QdsWoQzfKN24EEtvbd3wcVb2JuDfsmLlR+HQNI1mHeV3P69nxR145Xs737JQfmO/HMsgU
ynjPB6y52HerH/XK8fCvv6VCouB4OeqXY61cjgrhuce6zI5KmR2NH1QGD8PLiK8hRjyVIViAnEuR
tZltY09T+rPgspCkw2479dvazHcoGdvuuD1szqmG6re+r9Poxrr6zZLr5V6xHpGphjpSRxWwvuc5
YH2v97AxBEsR3KJqXqchdOi9p87IsQ0Qvf9fMP9fMP/Lgnm7tRCJyHiEoRIkr8FkwY573VEo7oCf
WS6jEEquXm8MERaChgoUjO2P2i2eShrZ63c9GLmQBh69Hf+BCRm/jeQM53QnRCFPOJZ3rXOZ5Pcs
UgGPlkobNuh63UGvMzmcHPb6DOz66uKSXb46O7u4vGbXuWA/5wkbMs+bjibTwSH75eqagTsOGM/i
u0kElLG+mrZG3XG3D09/iAQgtfrw6NnOG6WLdaGBHngSZkqGrTKxaJTQlYzTSJzkZolPjt9aY7sh
Q0ufQ4fKNPp3JX52LXgMnXqpFksZpKgJEuhbmHcI8+BZJBzsHFjFEN1uhSIFxpEO9Gk1N8/qDTHH
3FfjBXypzlcEnoL91yevrl9fQsNKzLQ0yP/SmFSDdYEGl/msG6i4blQ1KiAL+3Rhs7zeEkLZURNE
r9tvCOFZbtRtA6/3pXiLZQvMNTYc7suXV9dvXr46f1ZHnkBBD5hOQuDVSA2O9gvEvxqozZ6mer0N
9X4lSM94dvvrQAOYjeW3GnaDd5ln4lJkcV1bVdsmpCO2dwc+3fU6L359dvav/aYBj4fPn3teQ3nk
/o+EemPp+X7JT+3n5xstznSxtKICEnjOKRVryGw1GdRbm1Lob/rttTBLkYnwpoF8+HjgtbVtitpN
ldc8vVbP6iCKljqAPqiv3wTwnEdfzeUMT40Kge9q7R1Yt455DmH1R0o4xm4gGtGj2ftxZ2tdvBah
5l/NFB/gwGqG6oyP2qJD+Byi5c9KJmfzOZQZdUNrdtRwQV5rYDrRUGxm5mtpypHz/S0OPqYwci3w
rNVq1V2r3OQzQe51kRXslep8w7N0S4vU2Ij/w29mi5pWhO1nWoR+t/oOFnnBk/UblUVhPTDWGpv2
N+gOm/bHI5lH66b9fQESSw62ZsDAihj4nMDwk+CRWa5rQIqWJorehg/xmK9PQqHzr+ZHMZLkSNL3
lyUPO0A4XXJzKhLdiAu1xiaQDWWc3anoCjhqwDh6PIpq3U0tfCwXoccI4ASpds0t+gnZEkR50wwJ
jebN5PMtDK1u2NtGRwaXWnZ2AFw6kNbyTpzBTk3F64YTNTo2Ajl7Nfi2ymsuj3jqzyeXLx6tzdMc
NmAxGkfdRqvGOlIqnxpAof7P+D2ePyTqLlgC3jrgCTjnIwE3ycImueTI94Ng9yhSk1AFryG2epHh
dcdNPapEzOD/rdjeblFBSX/2yz979OfAPQ/c89A9Dx8vDceG7wvLOfDi+w8pfxdR5FSnPSAO17Ep
kt5fJ5K6pj5HPBZJJaIS2e5iOuWwJVHbUnLtf38hBQSklFGJa3cR/axm2/LBxk3hDP4WTvWbmpXS
sCh2FwUW2duyoNb/ogjzSEuJAEYpGYdpd9FASZBChb3eFk/Z8wh7+VaicfAeJ6jUASqFVUO4u8Cu
RBRtC4taNwU1/LSg/sO2ooHNEr7j+TOgL1X6AHRs/RtABzYr6Jbn3aFf8/tt5Ni4Cbz/t4sfht+X
crGIdtnKimulLlVmeN0Z6q0b28DNw5RvtZk16efsYp9zba4znui5yBoHdbXmzVOhjVriwfP0L9nP
FgR9v85G8+mzTyoLogcNKnisQq+/fpGmcbReNW6cSeywj+r1vuBMrFx4113wB7ZNkeDZOV8s6rum
su0TpnkuFsDYy/nF6eXZ1zo2Khf3ffsGcZcjsQ0d1vk6qNCgN57+OBnf0Gb7LJT1reJmTx261x1t
QsdXdkHG5wZWkrmejL/WW6I4WEzGvm9fbLntvwCGfL/kDQ/SXySfc7aLr4h+ElEqsgffjbmuzcOO
3pcHovoLuB2C0pIY+Zy4JLTGKwA80teXNWyN5q33KN/i1VB9RcgYzfV3APJM6kUutbgQNRi1xsap
bW/r1FZmt7qhmvHjoYRu1RhSX4ODHWD8IqNo4xCmbPp4fgAcEb8DX+phZfCx45hPnT/Vj30+42im
4LP6tethdf0M6+yeo8V/8Mit6K/r89Op4lPvszbP9XY+gnPsQF1T8vW487eipJJZCmXNA6cyruMR
e6S/+hTGcl6dwpRIPmkceEOBZyAHI4pYo921UrujkviivvXksnxipyqZywXD63V+5idP8BLFBV+z
Eev3p4P+1Dtkr69P8RLFCPstuQ7K+vj/fgSXTSSztcEP7K1HJQb7f7wowo7esbf94cHkXW0a4jju
HfUGfWxcAJFYheLYw6eY33fc9a3jnkdNOuWrpOMOo0GFx50eNq+WgDiS2hyr+RwbrAY6v+ciWx+r
pNaUgQiLUaHQQSZTIvRGsCW/E1PmZHxwIROJ/OiDqzy7k3c8OniJL3o1saZMeOznnscnM4vZQma2
jTvg79zz+G0hgRp0vB55nKgs5hGRBOTZuhPJWIJE+ocX2Ig3mDs53Q0rmOZJovIkEE40HR4spbhD
HowuxtxJsepAEDUcBoLsaF4UqVVnHsnFshSTFSdPJPCgnZxsW6xmRcOSZ2GgspKB9C51PaGcz2WQ
R2Z9PCD1FS9HO1oYI5OFPiYQwF5kDYSKiapNCxHWhpBEnp+fXGMTKqqbQqiAOeHxP+gfQJEb1dGg
KMcCab5DqieUc5WBaEo7cizjRZ7ynlN3HUdo8gxzPAvI2nNgG+/jodEzoMEat6XACdj1UmjBClyM
Z4KBNTBwU7qdaliAijFsJphMgiiHkgl+sC1nQ1pXKoaZcySwSVPzuWgzRYaGJNksE/yWrVWeOVpM
zhlgwzuHuAJoJgNfgNoFCP8qViW5g1DMOehGs5VKvjOMpymUoQwFGAPYAOxhzfA+KiQgi3u1FAnL
00XGQyDQ9RM0VUts6ifsyfUyEyBraAIuIp4scr4QDK/SksicWeNrYHs/S/5BQsWpp3jP0aJoTgQG
ipAuku5K3soUak3eVdniAJ8OzkG1N2p+8+Lq5c14cNTp3+A8EGNJaMp8iLgLv4ULvVnSbQy8QAz1
T8gApbtoB2rCvRTdjLPdJE3iFPiAX8KQSkNxJwOMBkkYkZJjIGztqlqS7hFDu17mJlToMPZWETLj
QkEQKS1Cy9YJOh9DM6ULe/YeCruTnP0TQxQMoVDVcT1ThpkDJ14tYR5HK9UKuHGrWFVxR4jlGowQ
sgwYAqGD9AIjIaOFKKeqowNszYCpivwZBcWCDiBm6OkMzBUsAlmdrZmzIxjuQmjZW4nhyRUmMSCg
knWscg0yB90D2kCjrAMwYiOAT+Q9Exj0kTPUUCe3Yis4+jWPZ3gdc85O9DoJrrm+BQPObsEfutj/
GmRK5lbwjKOWGcRsWNXAaN1mFGWYi0ZggW1AFYMQtKbbxIASkiS2xXkCjoBDuhaEse4AvpKpe4iK
kFXWCIAsNylZQyFZdl7M0eFwCDpWm0nzHVicyWhWKDBNkVFtzGV7gADUxvr7vsPQcSinRAmdz2YE
cr0fIzXjYMlQMDDbzChRYIiJxYLP1gYYYleWFY8Wlxq1ZR0XMK0kMSbptiumApdwXJMmucwlaB+i
DoTjhEjNweWLFcnoEIzV40IBDoWWjjKDdRbEpM1gUzbq9X3yfQqzBmIHD//LAWD5VbA/6HuW/UuR
SUWxHO8/W3OmaOaI7jn/YD2wBPDTEDVKIzpgfWDZBSGoq8D7oZgCHtG1PgTBsk4fAmB4xMBhh/mU
rZAG2Hoxp/AcXOFlAtaK6YGGd7cH4/cUrjgFWaciwCyiSSTIq1WGnVsCAFcWqa5gDjyHU+8/yJBD
PbCoFzybgaw7gYoiW7KhPT8oVVIdsuLmMDcHPCXmSU75qs4F5PIcjGa/XXjghtU4s1EoFE53m4h6
XJljl720yYKeIGgtVR6FJSMS/HWVsIp1tBGWEucAcOx5FiN78pysbisSka3Y2SWoeabiIqDhXNff
qceAmk4BhFPdpik8YD+1eVg7B8s8udVW3ufkbBh+qBE5w70DomG2kGyTK2SQvbUd1MHwjIVARQtJ
FWp2fnI0dnw+U3bapvow5GKZYafVKdhV3LCvgJnCfieAglhY1M4WioWwo0w0HyXlJ4kwqIuy7gHT
iGzemXEDFTdmcY4lIqQbsCcXvsgBbVXnem3UmokyA0FFUGQaZ7FFDzp+tjZIu806vZoxY6ahZTum
YAXCymhso0qV2aiKxrQS2lDnFGjnQqPjqct+gk0AiPcYCkkw3NPL1237mdUM4s9KhmZpIyT5d0m+
Q+SnbOLScJWgNQmmNrTLTkLwpyWP5gdQIZOPQzYEO3MLwZLW/lRSd8gyF9Zo1YqVe/Q93OjwqG39
Gtd9IxOowAAVWI0gy8bE+voyuSzSclXvYuWBk1awp/Gx2E3Sjnus1zO4NZzli6nL8D+wHmZ2q0uN
FRl1F9WYpjC2FEWV5jtNTFmvqrE0fujBTa6tUCGihbq2XrEfapTboqi9kGUAYTcaNNQZFiIlVdsK
K6Ryj6Z07JQpi6Fr4cpwwEJHEsgpXhbXNhzxBn2ImbiRMbXl8XO8bW7IO0lpT359eX02ZRRv4T/3
DRPIGwnR+StqjdhzK5fslRXkSUNRAZTfEEMcVrIfSkbACdqLQZvpey55YBCzOQkNCHeI2O4SkbOe
ZnMRvTA3kzfaJDjjWtQW2+uBizywSpv1oaP3UIcwQXef3FWLOhdkCfQNHu5I3KkGExCS7HqY9K0m
ae9XbQoxBNDmAWsUDAQ8WvG1trQdnZodNSI3mdEJ1ONJPfRrVxkVTCD7SA0Gp3gsAT+nbPjhqTyD
1tDybmk08w3rHfUfnE3WlQi7/ZoJS20m5hiD6NQBYxWqoaRqzyJqQc/GvCvY/4PRwg5O4i5T4K4l
XbsdtctCZSlDMWLOtSGpklxcAJvnEQ1TGky1QzuWwCYRjarIcBsLhgFkC1H9pnDHYX1D81jQJ3do
1JhaSvwbykCBFsq44PeMb8oltd/UibCyh6YuyEhfwa4817VpTg/ccWe/maWpzu5wPNQpn+efdD7k
jpwqLLCZFdzyQ4ctWyCrzVaBs7sN1IXJFZe0DYYtby6cLbj5Nju+MN9p2CZimASFFdt1tzeD30P2
j9JBuo3Nk91I56KjwSym7PBRvKQqtR/QoRbsb0x/dcK0tSHv74CeELI9ROuQxWrUGSotxs8U8UzE
tfZcINJ00mgLyMJ4QMBJnkJBZatKa/oUpmwx42gBlQnOcgsi0RE+rjguVDZSG49nEvRqh7izM7v7
nhZ7dkgcXC+LPbndWFtztH7idgtlGKUtO57ANFvKxNVoTZepTOaqsiL8Ym9ql+zWDuSg2Cr5s5ZH
It1cG3Rge6cWcJZ0XMatqjpqVWntBOUUD9HoVEdEKkU7b8Oz4XjkAz7vyiuoNuZQ/QoAB5knweSN
g1zSzFEa4Gk1Isy9RKgVBjkUkdrY1FWEMkcNJWK7C/oVh1Yo+ELjAZFEEhKJrQfc+xH7gFUI0HdM
TAtuqAuMSxsFpvQWf3YgfeDHpip9hxRtfCsKjPrxI4Eo9gB2I1ac55L3PXSaSRtWyk+aagGEHUOJ
IIFRl7xrrNOqxAD9Ynj8i65CyaZabcrwDHja/37SHh3d99qD+0G7/33v+xAigo0xewZ29QF69PGh
xxZgT9o+DUf7dNor7o1IUCB0VeIUMkztE080odojBPpF+RcDpAEOdQ/690gaMbBfoXbsN69/2M9S
7RuhWQAVy7L6WwV4BGbPs6rB/hUIxVOeReXDXEYGX4a37JsC/PsMTFr2LuLqN350bt9XwqDfdOPl
eDyzh5vlYKj21qmpEBiODIU1uFeX57Qq/k4DyALV3DUApq9f3S82wnekPUTOOvjCp++NvAH8fPoC
9DYfTAaCj8JwNBocTsa9oTfmh16/z4ezQz6YDIe9w1l/6An2FN+mLlEs5bWrVGl5XwndbcCLG8AI
9JWYu90jtNJ6h2I0DzjUoENY1ptPJsHk8HA8GsHSg6P+QAy82dHkKAxpPb2MVSVCTY6lm0ilFT4M
NupWJBDXs7LljeC3EBGsoLojaFlzemuAd1BwwB8yLb5vHrbev/83iXumpQ==
===END CRASH DUMP===

**Comment by LDX-MCPE** [comment]
This is a duplicate issue. Please read the (contribution guidelines)[https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md] before opening issues.
