### ISSUE TITLE
Please allow me ...!

### ISSUE THREAD

**Issue by Conankun17** [PocketMine/PocketMine-MP#2991]
Hello, I'm a Japanese.
There are a lot of sites of PM-MP in English in the Web.
I want to make Japanese one.
Please allow me to create OFFICIAL Wiki of PM-MP in Japanese...!

**Comment by shoghicp** [comment]
This issue is **invalid**. Please follow he Contribution Guidelines when reporting issues for PocketMine.

You can join the Japanese section on the official forums. There is no official wiki or other sites besides the forums.
