### ISSUE TITLE
build 1126 Chunk Processing speed is changed more slowly

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#2997]
I started this test in its default state
And I did not put any plug-ins.

And I used a flat map made on a server.
something wrong with chunks loading speed.

http://timings.aikar.co/?url=11026682
↑ Timings Reports

OS Windows 7 - X64 | CPU: i5-4690 3.5Ghz |RAM 8.00GB
↑ Testing PC Performance

![11](https://cloud.githubusercontent.com/assets/8337568/7538179/2f3591ea-f5d9-11e4-95ce-7460232e8e1a.png)
↑ Server Screenshots

**Comment by HmHmmHm** [comment]
I'm 100% sure that the 'Calculate skylight on chunk population' is problem
fb03df3d06262fc31d6a56ce3966580bb2de08b4

This timing report of build 1122
http://timings.aikar.co/?url=11027006

**Comment by shoghicp** [comment]
Yes, this is 100% intended as it fixes the light on old worlds. If you let the worlds save they'll receive the new light
