### ISSUE TITLE
PlayerDeathEvent Not Working

### ISSUE THREAD

**Issue by yungtechboy1** [PocketMine/PocketMine-MP#2999]
I have Tried Everything! And I am almost 100% sure that PlayerDeathEvent() Dose not call! My Plugins that deal with Death are just spazing out!

**Comment by PEMapModder** [comment]
Possible reasons:

* you didn't register the listener
* the player shows death screen but server doesn't think it dies. Client-side issue, won't fix.

**Comment by yungtechboy1** [comment]
That the Thing I did register the Listener and It Does Show the Death Screen
