### ISSUE TITLE
std::bad_alloc ./start.sh: line 57: 3847 Aborted

### ISSUE THREAD

**Issue by xpyctum** [PocketMine/PocketMine-MP#3000]
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./start.sh: line 57:  4012 Aborted                 "$PHP_BINARY" "$POCKETMINE_FILE" $@

And server stopping (or restarting because using do_loop)

Using 1128 Build.

**Comment by xpyctum** [comment]
![image](https://cloud.githubusercontent.com/assets/6584811/7553827/4c9ed55a-f725-11e4-8bf9-ffeea5fb7f87.png)

**Comment by shoghicp** [comment]
Are you using LevelDB as the level format?

**Comment by xpyctum** [comment]
@shoghicp Oh, Yes

**Comment by shoghicp** [comment]
Seems like it's a problem with LevelDB when stopping/saving. I'll try to reproduce it on my installation.

**Comment by xpyctum** [comment]
@shoghicp It can be fixed today?

**Comment by HmHmmHm** [comment]
@xpyctum How about the LevelDb2Avnil?
It can convet leveldb -> anvil (using java)
https://github.com/ljyloo/LevelDb2Avnil

And I recommand the try convert Anvil To Region,
FlowChart : leveldb->anvil->region

**Comment by shoghicp** [comment]
@HmHmmHm we are trying to find a solution to the issue, not workaround it.

**Comment by xpyctum** [comment]
@shoghicp I'm install a new map, but thanks!)

**Comment by shoghicp** [comment]
This is a leveldb error triggered when there is not enough memory to allocate.
We can't do anything on our side.
