### ISSUE TITLE
getSafeSpawn());

### ISSUE THREAD

**Issue by SurvivalHive** [PocketMine/PocketMine-MP#3003]
$event->getPlayer()->teleport(Server::getInstance()->getLevelByName($event->getPlayer()->getLevel()->getName())->getSafeSpawn());

doesnt work after dev 1120 by 1116 all works fine...

**Comment by TruDan** [comment]
Don't you mean $event->getPlayer()->teleport($event->getPlayer()->getLevel()->getSafeSpawn()); O.o

**Comment by shoghicp** [comment]
```php
$p = $event->getPlayer();
$p->teleport($p->getLevel()->getSafeSpawn());
```

WHY would you even want to get the level object, then the name, then lookup (using an *O(n)*) method then use the same object to teleport?
