### ISSUE TITLE
Import MCPE Map

### ISSUE THREAD

**Issue by tbremer19** [PocketMine/PocketMine-MP#3007]
Hey, I'm trying to import my MCPE map but it doesn't work. 
I use Pocketmine 1.4.1 with MCPE 0.10.5Alpha. I took the folder from my android device and put it in pocketmine/worlds. After that I changed the level name in the properties to the name of my world's folder. Pocketmine says 

`2015-05-10 16:11:25 [NOTICE] Level "world" not found
2015-05-10 16:11:25 [INFO] Preparing level "world"
2015-05-10 16:11:25 [NOTICE] Spawn terrain for level "world" is being generated in the background`

What am I doing wrong?

**Comment by shoghicp** [comment]
LevelDB is not supported on systems that are not Linux due to the binding author decision.

**Comment by tbremer19** [comment]
Ok, thank you. Is there any way I can import this world?

**Comment by shoghicp** [comment]
@tbremer19 You can convert it using other tools to Anvil/McRegion, preferably McRegion. Both will be loaded by PocketMine. You can also run a virtual machine or switch to linux, where PocketMine will run way faster.
