### ISSUE TITLE
I have no idea what to do

### ISSUE THREAD

**Issue by XxepicgamerxX** [PocketMine/PocketMine-MP#3009]
I mining and when the server restarts I get disconnected and then it doesn't load. I have 6 accounts on a server and one is new,the others are not generating and I have vauleable things. It's making me mad at what ever is causing it

**Comment by LDX-MCPE** [comment]
Please read the [Contribution Guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before opening issues.
