### ISSUE TITLE
Error Loading In Chunks... Still

### ISSUE THREAD

**Issue by yungtechboy1** [PocketMine/PocketMine-MP#3012]
20:07:36 [INFO] A new SkyWars round has Began!
    20:07:36 [INFO] Preparing level "SPLEEF"
    91 76 128
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    97 72 98
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    20:07:36 [ERROR] Corrupted chunk detected
    
    Fatal error: Call to a member function isPopulated() on null in phar:///home/MCPE/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 2424
    20:07:36 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
    20:07:36 [EMERGENCY] Please upload the "/home/MCPE/CrashDump_Mon_May_11-20.07.36-CEST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

I still get this error When Teleporting a Player to a New World

**Comment by yungtechboy1** [comment]
And with 0.11.0.10 I get This Error. This is with the default World that is set in Server.properties 


    21:19:37 [ERROR] Corrupted chunk detected
    21:19:37 [ERROR] Corrupted chunk detected
    21:19:37 [ERROR] Corrupted chunk detected

**Comment by shoghicp** [comment]
**DO NOT OPEN DUPLICATE ISSUES**. Please read the Contribution Guidelines and search the repository and open issues for similar ones before creating an open one.
