### ISSUE TITLE
"Could not start server" What's up with this?

### ISSUE THREAD

**Issue by Inc1998** [PocketMine/PocketMine-MP#3015]
Every time I click "Start server" on the PocketMine android app, it says 'could not start server'. What's up with this, and how do I fix it?

**Comment by LDX-MCPE** [comment]
This is not the repository for the PocketMine-MP for Android app. Please read the [Contribution Guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before opening issues.
