### ISSUE TITLE
player game mode change crash

### ISSUE THREAD

**Issue by da123rrell** [PocketMine/PocketMine-MP#3016]
PocketMine-MP Crash Dump Wed May 13 07:33:08 UTC 2015

Error: Call to a member function clearAll() on null
File: /src/pocketmine/Player
Line: 1021
Type: E_ERROR

Code:
[1012] 		$this->server->getPluginManager()->callEvent($ev = new PlayerGameModeChangeEvent($this, (int) $gm));
[1013] 		if($ev->isCancelled()){
[1014] 			return \false;
[1015] 		}
[1016] 
[1017] 		if(($this->gamemode & 0x01) === ($gm & 0x01)){
[1018] 			$this->gamemode = $gm;
[1019] 		}else{
[1020] 			$this->gamemode = $gm;
[1021] 			$this->inventory->clearAll();
[1022] 			$this->inventory->sendContents($this);
[1023] 			$this->inventory->sendContents($this->getViewers());
[1024] 			$this->inventory->sendHeldItem($this->hasSpawned);
[1025] 		}
[1026] 
[1027] 		$this->allowFlight = $this->isCreative();
[1028] 
[1029] 		if($this->isSpectator()){
[1030] 			$this->despawnFromAll();
[1031] 		}else{

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1133 [Protocol 25; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20 #1 SMP PREEMPT Sat Aug 23 18:11:19 CST 2014 armv7
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.6 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomySell 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyShop 2.0.4 by onebone for API(s) 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
Alias 1.1.1 by ZacHack for API(s) 1.1.0
CustomRanks 1.0.0 by shoghicp for API(s) 1.0.0
EconomyGamble 2.0-alpha by hmm for API(s) 1.4.1
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
MSpawns 1.4 by EvolSoft for API(s) 1.9.0
ItemCloud 1.1 by onebone for API(s) 1.4.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
WorldGM 7 by Exxarion for API(s) 1.11.0, 1.12.0
FactionsPro 1.2.0 by Tethered_ for API(s) 1.4.0
ReportRTS 1.1.3 by ProjectInfinity for API(s) 1.9.0
ServerChannels 1.1 by EvolSoft for API(s) 1.9.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PvPWorlds 1 by  for API(s) 1.0.0
ManyWorlds 1.3.4 by aliuly for API(s) 1.10.0
TAGBlock 0.3-Alpha by hm for API(s) 1.4.1
WorldProtect 1.2.3 by aliuly for API(s) 1.10.0
SimpleAuthHelper 1.0.0 by aliuly for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
Afk 0.1 by hoyinm14mc for API(s) 1.12.0
SimpleMOTD 0.1 by hoyinm14mc for API(s) 1.12.0
FastTransfer 1.0.1 by shoghicp for API(s) 1.12.0
MeTooPortal 1.0.0 by aliuly for API(s) 1.10.0
AllServers 1 by hoyinm for API(s) 1.12.0
EconomyPShop 2.0.0 by onebone for API(s) 1.6.0, 1.7.0
SignWarp 1.3.2 by aliuly for API(s) 1.10.0
Specter 0.2 by Falkirks for API(s) 1.8.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVOwtv2ziaf4Vwi9vkYDmWHOfhgQvk0nSmi2TqS9zt4UaLgpYoS40kakUqjjuY/37f95F6OZlp
0nb2dosZxKTI7/2kqF8HOsnEYOYeTtzp2JucnAwHoixlOZj9OtDbAh4NLj5eXF+/ux4MB5lQiq9x
7pynKdOScZaJbCVKFlV5oBOZsyAVvDxL0719BqO8SlPYGCUp7jpQZXBQyOBW6CzJxcEi5VtRwvMU
RkDE2HN/Gw6KtFon+WAW8VSJ4SCQoUBq3LHrAQxf+/qljhPlvFKivBOl82ot9IL2XPEcyCv39p1X
ARB4cSdyvfdS3LE5y8WGGXQ/8kxcAczzmOdrYdcgwCHbS3K9z16us/39H4AqwDixGJMI4TivEnXO
80CkqQj39vd/NYsO7SJfl0JXZc58n2i3MKb28W9meARD8+u4Bb5nWVoDcRkQx/6Dje/H7j6bz+ds
DyiqJ2qcJw3O3Z1zZMCiPq1RCyDH7PTGT9npuburkhwlJcstyLZRsV3s/cFiJfLwXOYaxspwWe+a
PGsXqflvidiIUu3V+vEOvwDjJ5GGb7XIahgxVzcF3+QirCH0teM12vGO+8YG9iQ3b9JkHWsUlMWm
zkvBdXInGlmcNABOO7ZTL78pRKA50NdYz+SBPkKhkMQ3pcw6Qp64fV2Co+iSB+AavwxejNne/oy1
nuX7N9Y3gpKr+HWVFXv7g78PB2uRi5Kn6E/wWIHDAlR3NA3FHWBZVUkagh+6kwm4YSm1DCSs9abD
AS8SWul6ozGsXCcahuMn/oMNJb9NkxXuGR0ThCrnGHgGl0le3bNUgsPGUmk2GbnjkTdmL1x2c7Vg
i+uLi6vFkt1wzc6qNfMmzD0BCmfuKTu/WTIP3I/xMrs7BphFXADE6eho5MHoM+gfhh4Mx+bhR6lq
jDBBA56HpUzCQRN3FMrmIpC5zLZni7c4spR2Jocd6YFARkcwwysdy1KhPmQuVvA/Cpzk9gsIbkxE
gADtX6/569LfiR1P7PjQjg9hDHBEzlcQdAYzXVYQFENRAHeIDJ4pGenX3YmMY/ysyfB9YSgHWny/
x0UqOYpo8e5m+eHd9eVrmNqIlUo08IuhG6Ri1/9Vrh6KAid3RTH5txDFJ7lqRGG4eLooLjna1a4s
aPZfyC665voMwaTARiMZy9PTRXMDmfGhaGh2VzSHXxbNP5l1BWQ2rFuan8F6LItHWMfZfwPWgcyW
dUPzE1i/SbIiFWfASofzzuSwl2RMGO4wvqB8dQX5ii0Fz+Ah0LGOk6DoyeIE9n2l27e0QEbs0mWZ
u1meXS/fL7qsDWKtCzU7OIAUF1erUSCzg5bQgw4UEMCSF0v5Wna4r2f6OncpIXVYf8PT2wdh4CuZ
1LzQMpS+3+J+gu7O0oSrDuFm3NeYS9bXIft/efATD/qUu19POeH0/SsYnadcqadRfl4pLbNrnt92
6e/O9rkY79rdo1b2DQqo4fl+hwjD1rNCCHQmq1Q8DCJ2fieMODwtYt7nLM6yHlPfkDHjrAkIBv/O
8GmcLaG7PJdZBolElF036c13OPN6/Fy+/p8nJctJEx6/WomACjyoS9ZzNHhFXUXXHuuZvi3uhP6L
O5neAEE9Jk+/ngmLdJfyPwpzm81mJIAMBDnStxjVsGE6T2XVrXLauZ0Q8eVc9g1KafIU0JwFiP75
0SIWSl9iAO/aX3e2z5D3BA19Q0bqIP5GLX2QZRr+eNVhqp7pMHTcZ+b+npc434vftTNRa/eVbFnU
vt/S8Ee6Ib6ALQ49l3KgR224esPpGEktym5W7c7uqGs3uC+FjkUpwo/fywY7uJ8TEa5FIUt9vbzp
sNHO7ebZna4JcH0SgX6bR0me6O33Cg87YH2/Iajz84mlH50v4BlaLtJu3Nt58IfR4nuHvz7ub/Sv
RZl8Fh8QbsNbM7VbYOz0eZdJel4mqth68vTgLF+LVLK/JSG4Xt/zxt+iSkPKc0xycbcg9+yqq53r
8OR2uflORdINzyqRfopd329w+n729AzL8+0D6juTfZVMdjMtT5Mq3X438RtwSH++3Vhenq6I5dmP
/5VCDugWRPVUl4/xaOKcPVblfa8ir8YKlU+L/wkMkMwhmmiIJrsJqJ7ejdOTP0EhXQN4qBxSTGHI
eUIweNDU/iTSolc1PHj0hUbjTzK6mJA/x+DO8cT+kq/X3RKomdtNRjtcXIo1kPIuujpfXHyvlqlB
7vuXQL55CfSlgmGnK+/SddByg71t1HUtHHVYHI/cvjfJbZJn7mEW9BX1DdUQYPR9g/bJpyhX75av
H5gaTf5zaW8R10cmlogncPKGK70sea6intv0pnddxn1Cb/4t/LTNeZeM/ujZB0I10IMeFMxSYinl
Agop3j0H7c7+/4SMTBfPiRdnaWpqqf4JUTP5e7WCNcjv50gNSvCnLvqnH6osHj+YXTx6Mjv+cjd7
ZLul4y9w1X9d1LbPzziVLXrHsovnnMuu8w+8LHrxxE7t1knen5yWd6LCQ9NUQNkGKHuOfdJr1H5q
tjO9YOk9OHNNylv1ba38IMH30qVM33d4UQY7RMyGjC9ygW8ceQnUa1HX2eZCwwhKFsjvOhH4gtJe
ckA253gCTc3yjC0umPEGP7crsH2bu67neX5ev9Kfj/084/dOQTcf1Px4CsvxiMixZREIau65fr6J
gbA0UXoucz830nD+UYly250owRLnMor8PBQqKJOC9hs6WAZpnFUqydesPS93rhZAgdTh3K/GY348
MX8kJn1YORqN2AIytxJswxPd8II3T+a5LDOewnZgpdw6aZIlwOB4PL7y8xRsyqmKkGthCIKWT1Z5
ICyrDg/iRNyJDC8QmBV3idg4IbCIFzjmE9iCb/SdiF7pmyVGNDxPAK8ixs1MJldmGPMyDGRpcRZ3
Bc2GSRQlQZXq7RxEaV6xa1k6SmgNTKo50Au0pEaJqVyttvWMEiJsHhPXry/enL2/XPo5CntUcKWg
jA3n/0n/gOhKS0fxO0GYSW2O0RtSFMkSRNBon+bw1XdzMWC0zSAxDV4w9DUGGKJkXQG1eHMHL+kw
gLCrvhdsGQvQUM0O46VgOhYMYpWCH1yzAMWv2UqwJA/SKhQh/GAPzBlh3cgMdkYIYBem4pEYMonn
NwpBslUp+C3byqq0sFgSMeAsiRLCAKoowYghigDgn8WmAXcQioiDQhTbyPwvmvGigPKQofAyYBYv
B23xehJeuDB8b2KRs6pYl8YufdS9BTbzc/ZiGZcCJA1TQEXK83XF14Lh3SQSmbVblcCY7jIkn0mo
uPU8FoHlor8RCKhrC5GPNsltUogw4SNZrg9wdHAJiv0oo49vb959PJqcOt5H3AdibADNmA+xa+0P
ENGHmM6+8F4W3n1heEdL6ZLkqzEAp+AuoXlM0iRKgQ74JTSpNBR3SSBYzPMwJSVnANhYVYuSLjfB
vIorHUr0D3MvDImxwSBIpRKhIesM/YyhkWJssLcs2F3C2X9jgIElFGgc+2TGMAbjRkh4G8bRSpUE
aiwWoypuAUHEASOEeA2GQNxBvoWVEPRDlFP7wAGyVkBUC/6CgloNBzhm6NoMzBUsAkldbZm1I1hu
Q2DztBXDixtMDQBA5ttMVgpkDroHbgOFsg7whhBGRqS9pFM2pAw15FRGbDVFP1d0lw6840xt82DJ
1S0YcHkL/jDC5+9BpmRuNc24Ki6hPACsGlarIaOml9kgBBY4BK4yEILCpEhcQhrCuazKwRFwycgw
oY07gK+U8h5CICSELTJAlps3pKGQDDlvI3Q4ugYIjjVkif4L3gosaVcoML+QUe3sZXvAAaiNefu+
5cGxXM4IEjqfCfrkej9CxORgyZCGmZlmlAswxGRizVdbDQSxG0PKmJAnCrVlHBd42iREWLJek9Vv
HJtT7JQiuUQJaB+ijsAbZAglApevMZLRITNGj2sJfEi0dJQZ4FkTkSZJzdjU9XzyfQqzGmIHD//F
GcBKpiZ/4o0N+QtRJpJiOVjzrTFnimYW6J71D+aCJYCfhqhRWuGA9YFl14CwZkrySiCN6Fq/x4Ih
HdJaSuERA4dZ5lO2Qhhg6/We2nMQw7scrBXTAy0fPVzMQIy2zANZQ52GWUSRSJBWowyzt2EAXFkU
qmVzMrZ8qv1HCbJcTwzXa16uQNZOINPU1Fpoz49KlVSHpNg9zO6RWFflFeWrLhWQyyswmv1h7YE7
VmPNRqJQeBTVnpi15jhi70yyoBEErVhWadgQkoC/bnLWko42wgqiHBg8gjKMeGQv3pDVPYhEZCtm
d8NUVMqsDmi41z53ujGgo1Ngwqpu1xQesZ/OPqx4g7jKb5WR9yU5G4YfmkTKsDpHbpgpF4fkCiVk
b2UWORiesRBoYSGoWs3WT06PLJ2vpdm2qz4MuVhmmG1dCAaLXfYdeKaw7wRQ9grDtbWFGhE+aBLN
H4Ly81xo1EVT94BppCbvrLiGuhqzOMcSEdIN2JMNX+SApqqzT03UWokmA0FFUGcaa7H1E3T8cqsR
9pA5bseYMdMQWkfXpEBYmR6ZqNJmNiqhMa2EJtRZBZq9MGlpGrGfoN4H8c6hkATDPV+8H8JeoGAF
8WeThDo2EZL8uwHvEPgZO7ZpuE3QigTTWTpiZyH4U8zT6AAqZPJxyIZgZxYRoDT2J/OuQza5sAOr
U2Rc3KPzYT/D06FxbET8IcmhBAO2wGwEmTZm1veLfFHn5bbgxdIDN0G3jdiqIi8cO+wWNNjdrar1
zKb4V8zF1G6UqbAko8d1OaYojsWiLtN8q4oZc9siS7EDLIoqZaSK9ytUB1/dC/XqbVEXX0gyMGE6
DVpqLQs5JV2bEiukeo+2OGbLjGXwaG3rcOCFunukFKwN7JPiEe/Bh6CJnYzuoAc56ofUkHuS1l78
/G55MWMUcOG/oIKmJIemhADRCSpqjcizmBvyGu2e9RQV0KcJNa9kQJSNgBI0GI1G441t9sAoZpIS
WhC2hzhvM5F1+P50Hb4wOZM7miy4wja8Rbbngo88gmXIPHjgPvZA6GC0T/6qRJcKsoQlQsaWxB5G
MAExyeDDrG80Sc1f2xViDKDuAYsUjAQ83fCtMrAtnI4d9UI3mdEZFOR5N/YrWxrVRCD5CA0WF3jw
AD9n7PD3t/ISZkNDu4HRTzjMPfUe3U3WlQvTf62EgbYSEQYhOmXAYIVqaKCas4dO1DNB7waafzBa
aOESbDMFti3F1rbUNg01tQzFiIgrTVIludgIFlUpLZMKTNWhliUwWUShKkrsY8EwAGwtqk8SWw7j
G4pnaCsZhUnMLQ3/O8pAgdbKuOL3jO/KBZqNgFJDaw99XZCRXkNbXqnONqsHbqkjJzVbrd3heihU
nuefdBZkz5VaXsw3TcbosI19wGTbbdV8jh4yasMknnOhqqHnrYS1BbufSKB5R4FiZ+zkq6AVsqhS
C83+xgzWBUzdCfmvA5JGos2hl0M2p1DqKPYMQrrGYw0769pQgudPM2ZqwFr9IKK8KqAmMoWhMV4K
NKYesbAAyjHusggR6BSHG46Imkma49kqAc2YJfboyzTQs7rtZvR9S91Wm97YGJSxdFvwN4GQum48
ROnPNKmnN1vERZJHsrUD/EBlZlCOOmdqUC819BnbIZHu4gYdmKczw3CZOzZntoUZzcqicwhyjudg
dDAjUlmgpQ5hrDme2oDX2goJCoYIClgBzJnbLzNaZNOeOZXlXSDMHpN3UnsFdaDSJvnUwchCQ4mY
xzX8lkIjFLxA84hI8IKvKUihgOHoa2aAdQTAt0TMamroERiX0hJM6Rf86UACgC4HJv6OEE2EqkuE
7gkiMVGX8aaXqk9iqUl67ECSek7KMIqyObKdQZJPgFCbfjukE1YigH4xPLxFV6F00WKbsTeXZ8uZ
98PxcHp67w4n95Oh94P7QwhZ0kSJPQ2NeYAePT8ZszXYkzKjw+k+HdiKey1yFAi9fzuHHNH5rglN
qDOEUL1uPpYsAlxqB+ofaaLFxHx05ZhPvD6br7DMtblVADVH3H5pyVMwe162E+YL0HpUlWkziJKU
XsAAaHuBMNJF83Sdtb9j8BbzrhMWfVLNfRB88ZutzPlksxjqtW2hWw40R4LCDrs3i0vCir+LAOJ4
u3cLDNMnX/YXm+L7ZRc5Zw5+KeaNp+MJ/Hz5FvQWTY4ngk/DcDqdnBwfuYfjI34y9jx+uDrhk+PD
Q/dk5R2OBXsJmBYxioXeERJiqZL7Vui2h7YLXGT0WkS2AYRZwnciplHAoYo8BLTj6Pg4OD45OZpO
AfXk1JuIyXh1enwahoRPxZlsRajIsVSf08QIHxZreStyiOtlM/NB8FuICEZQoynMbDkd/Nd3+j8n
Rf053+Hgt9/+D/VvE8I=
===END CRASH DUMP===

**Comment by shoghicp** [comment]
This is a fault of a plugin, setting the gamemode on an unexpected place
