### ISSUE TITLE
In creative, a player can move below bedrock and will not die

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#3021]
I have 2 bugs on my server...
1. In creative you can go further down bedrock and you won't die.
<s>2. When you use bone meal you will instantly crash.</s>

**Comment by PEMapModder** [comment]
Crashing is most likely an MCPE client-side issue.

Also, one issue for one issue, please.

**Comment by Artide** [comment]
Ok. how about the bedrock??

**Comment by sekjun9878** [comment]
One issue for one issue submission please. The second one has been removed. Please create a separate ticket for that issue. This issue will now focus on the bedrock issue only.

**Comment by Artide** [comment]
Ok

**Comment by RandomAltThing** [comment]
@sekjun9878 Read the change log. The bedrock is not a bug, it is implemented. You are meant to be able to fly in the void in creative.
