### ISSUE TITLE
Logout reason is not shown

### ISSUE THREAD

**Issue by Gonbe34** [PocketMine/PocketMine-MP#3027]
Reason displayed on client when server rejects a player - I remember that is on MCPE 0.11.0 build 7(I don't know what PMMP version is)
Now, on 0.11.0 beta 10 and PMMP 1.5-1136, the kick reason is not shown on the client, like "you are banned" or "server is full!" (So people can't understand why they could not enter to the server)
The message works once player is entered, but while processing for spawning this not works
Sorry for bad English

**Comment by LDX-MCPE** [comment]
This is not a PocketMine bug, but an MC:PE bug. Please read the PocketMine [Contribution Guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before opening issues.
