### ISSUE TITLE
chunks in mca human made map. build 1136

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#3028]
loading chunks stopped while traveling in world. after several minutes.
![screenshot_2015-05-17-12-34-00](https://cloud.githubusercontent.com/assets/5399200/7669857/dadea0ae-fc91-11e4-9083-fe295f53f4fb.png)
![screenshot_2015-05-17-12-33-41](https://cloud.githubusercontent.com/assets/5399200/7669859/e87c13ae-fc91-11e4-8492-28816256bea5.png)

**Comment by shoghicp** [comment]
Don't use Anvil for worlds, the are slow and will fill your async queues, stopping world loading.
