### ISSUE TITLE
mcr map has the same problem as mca "chunks stop loading" build 1136

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#3030]
This occurred when I go underground and then return to surface. And cant come back to spawn as world bordered by "empty chunks"
![screenshot_2015-05-17-13-42-16](https://cloud.githubusercontent.com/assets/5399200/7670558/5e2baf68-fcb2-11e4-8168-c15bd2c23eb0.png)
![screenshot_2015-05-17-13-41-44](https://cloud.githubusercontent.com/assets/5399200/7670563/758f473c-fcb2-11e4-95ea-b14c927ba8a5.png)

**Comment by shoghicp** [comment]
You may be in a network with high packet loss rate or filled the tasks.
Also, you are not using the latest version.

**Comment by vvzar** [comment]
This network 1Gb L2 with juniper ex2200 switch 
Connected using cat 6a cables intel pro1000 network card and server running on 32 cores server with 64Gb of RAM.
Latest version of server or client?

**Comment by shoghicp** [comment]
Server. It doesn't matter on the server, but the client may be dropping packets. Just by using wireless networks it's around 15%, and worse over mobile data.

**Comment by vvzar** [comment]
I cant check while last server version for build 11 and i cant find such client for tests
