### ISSUE TITLE
Self cloning of spawned villagers

### ISSUE THREAD

**Issue by vvzar** [PocketMine/PocketMine-MP#3031]
How can i delete them? I cant even enter this map. And after killing one or two, they are not react on swords hit ever. 
I spawn several citizen. And after week of server running this trouble occurs. only with one of them. Another spawned citizens looks normal.
![screenshot_2015-05-17-22-49-58](https://cloud.githubusercontent.com/assets/5399200/7671867/1a05a394-fce8-11e4-815d-17df30686283.png)
![screenshot_2015-05-17-22-49-46](https://cloud.githubusercontent.com/assets/5399200/7671868/2020077e-fce8-11e4-8c79-3eb5b2ee29bf.png)

**Comment by shoghicp** [comment]
Can you drop an item in the area and see if this happens?
There was an issue with duplicated entities on some chunks, but it was fixed.
Also, I only see a few of them. The duplication that I know of created a few thousand from a single one.

**Comment by vvzar** [comment]
Nothing happens when i drop item near him. I cant reproduce. I will keep in mind this moment and try to check it out when it happens.
But one thing is -  it happened twice in same place and chunk.

**Comment by xpyctum** [comment]
@vvzar Try disable mobs in pocketmine.yml file

**Comment by PEMapModder** [comment]
The title should be corrected to _villagers_ instead of _citizens_.

**Comment by SuperPitty** [comment]
Did the bug fixed? Beacause, i ever get that Issue. They can't die when i try to kill them

**Comment by sithsiri** [comment]
This happens to me, but in much less quantity.

**Comment by thebigsmileXD** [comment]
They cant die because they have no AI.
That will be added sooner or later

**Comment by legoboy0215** [comment]
The smile, please do not say things that are not right. It is a bug. If you code, add a entitydamageevent and if($entity instanceof Villager) then $entity->kill();

**Comment by thebigsmileXD** [comment]
@legoboy0215 First of all, my username is thebigsmileXD, not "The smile".
Secondly: It is not that incorrect. You sometimes cannot kill them by hand, there is another bug which was reported a while ago, where it says, that its an async on server and client. the mobs are actually somewhere else, but the client displays them to be at another location.

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
