### ISSUE TITLE
Linux install script "Couldn't download PocketMine-MP automatically" 

### ISSUE THREAD

**Issue by LukeLukeLukeLuke** [PocketMine/PocketMine-MP#3033]
Howdy

On my Ubuntu box I get:  

*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 13:00:47 EDT 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar...bash: line 194: PocketMine-MP.phar: Permission denied
 failed!
[!] Couldn't download PocketMine-MP automatically from https://github.com/PocketMine/PocketMine-MP/releases/download

However I could install it on OSX afterwards.  Is this a problem with my Ubuntu box or the script? 

Thanks

**Comment by shoghicp** [comment]
> bash: line 194: PocketMine-MP.phar: Permission denied
Do you have permissions to write in the current directory?

Also, this is not the repository to open this issue.
