### ISSUE TITLE
Not a Plugin Problem

### ISSUE THREAD

**Issue by HalkWise** [PocketMine/PocketMine-MP#3035]
PocketMine-MP Crash Dump Tue May 19 18:26:14 UTC 2015

Error: Call to a member function getX() on integer
File: /src/pocketmine/level/Level
Line: 803
Type: E_ERROR

Code:
[794] 			$this->chunkTickList = [];
[795] 			return;
[796] 		}
[797] 
[798] 		$chunksPerLoader = \min(200, \max(1, (int) ((($this->chunksPerTick - \count($this->loaders)) / \count($this->loaders)) + 0.5)));
[799] 		$randRange = 3 + $chunksPerLoader / 30;
[800] 		$randRange = $randRange > $this->chunkTickRadius ? $this->chunkTickRadius : $randRange;
[801] 
[802] 		foreach($this->loaders as $loader){
[803] 			$chunkX = $loader->getX() >> 4;
[804] 			$chunkZ = $loader->getZ() >> 4;
[805] 
[806] 			$index = \PHP_INT_SIZE === 8 ? ((($x) & 0xFFFFFFFF) << 32) | (( $z) & 0xFFFFFFFF) : ($x) . ":" . ( $z);
[807] 			$existingLoaders = \max(0, isset($this->chunkTickList[$index]) ? $this->chunkTickList[$index] : 0);
[808] 			$this->chunkTickList[$index] = $existingLoaders + 1;
[809] 			for($chunk = 0; $chunk < $chunksPerLoader; ++$chunk){
[810] 				$dx = \mt_rand(-$randRange, $randRange);
[811] 				$dz = \mt_rand(-$randRange, $randRange);
[812] 				$hash = \PHP_INT_SIZE === 8 ? ((($dx + $x) & 0xFFFFFFFF) << 32) | (( $dz + $z) & 0xFFFFFFFF) : ($dx + $x) . ":" . ( $dz + $z);
[813] 				if(!isset($this->chunkTickList[$hash]) and isset($this->chunks[$hash])){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1146 [Protocol 26; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-787812 #1 SMP PREEMPT Tue Jun 4 00:57:38 KST 2013 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.1 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.7 by onebone for API(s) 1.12.0
EconomyProperty 2.0.4 by onebone for API(s) 1.12.0
EconomySell 2.0.5 by onebone for API(s) 1.12.0
EconomyShop 2.0.5 by onebone for API(s) 1.12.0
EconomyTax 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FastTransfer 1.0.1 by shoghicp for API(s) 1.12.0
SimpleWarp 1.4 by Falk for API(s) 1.0.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
FactionsPro 1.2.0 by Tethered_ for API(s) 1.4.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
MassiveEconomy 1.0 R3 by EvolSoft for API(s) 1.9.0
PurePerms 1.1.1 by 64FF00 for API(s) 1.11.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
ManyWorlds 1.3.4 by aliuly for API(s) 1.10.0
MCG76_WorldEdit 0.5.0 by minecraftgenius76 for API(s) 1.8.0
CustomChat INDEV by Array for API(s) 1.7.1
KillChat 1.0.1 by Array for API(s) 1.9.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
SpawnMgr 1.1.0 by aliuly for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
essentialsTP 1.0.9 by  for API(s) 1.0.0
EconomyUsury 1.0.0 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
WorldProtect 1.2.4 by aliuly for API(s) 1.10.0
SimpleAuthHelper 1.2.1 by aliuly for API(s) 1.10.0
MassiveEconomyExample 1 by EvolSoft for API(s) 1.4.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwt32zay/itYJWdrb0SZ1MOSlSr3+DhOm9ZOdG1ls6dhjw9EQhJrvpYALSvd/vc7MwBfspPI
bnq7zT5MgsBgvnkPRP7aUkEkWmOn3+vag6OjYb/dElmWZK3xry21SeFR6/Tq9OLi7UWr3YqElHyJ
Yyc8DJlKGGeRiOYiY4s89lSQxGwp1L/29hlcBbESS5HBukUQ4qIDmXkHaeJdCxUFsTgIxY0ID87w
/2FSCEOt8cju/dZupWG+DOLWeMFDKdotL/EFMjQ86gMZV+F/nqpVIK0X3iqPr2eBd30WSMUm7MPP
z4HW8GhQTsyEyrNYjx6a0d/obgh3dDEyw0+JmpyK7CzhPqCaMNcFVve6tt3GS36757TZHiDbZ3t7
e3UecBXywSyY6CV5rIrHIdGS+/vs4NOPnjG7M9jf39d8HhUMZTz2L3i8FMBKDybd4fCA9WxcM7Lt
+9bUbl6wbZFdcD/IJfufTz0Y15brPRwtsZHdNZstkkxwb7WFh3HJnurr/V9pfq/SG+3yL+RNz7Be
GJN58YL19Tb9rdk/bc3+qTF7UDB1WC0LYl/ckvqm30+vXr+ZXV2+/umUTSYTNgLAqLvbffZ3Zt++
Mv/22bffsl53n/0HnrKnH7efjhkt6TC3NXZb8JcmaQ6G1cbiFuwwiJdnRhITYzZgP4GUQu3dZ7cf
NL8/79+ji/pzYMI2W44+6wjlApDbNkfPmKNJHJUkQIt7WtKwwH5urIx9e8fcnrNnz/SY1qtjlzSA
EV9LPFJXaDZ7VmU97ZolaQCO01j58QEru/WVKy5Xn9czcAV+83ltw/7PPqHzcnlD88UCzVGvxlGw
2Pvb5zSNDIOiAdM9BiGL5yBeCIMq4x4Evg+tJzbb2x+zKna67qXIbtAdvAwWvMyjdG+/9XO7tRSx
yHiI0RIeS4jIwJvTGfjiBlid50HoQ7R3+ocQZLNEJV4Cc7twx9OAZjrdjg0zl4GCW3vHf7Ag49dh
MMc1nSFRyGOOmaV1FsT5LQsTj4erBGJ0r2N3eo41HA1BleyJwy7Pp2x6cXp6Pp2xWS7YD3nM+sy2
x4PhuDdiP17OWNd2eoxn0c0QM0W6SoHuoHPY6cLdRxEDpFYXbm398CqRxb4wQDcg7iwJ/FaZWyRK
6NRL4iTaHE9f453htzbYrskQxNIZwgjP1SrJJGolicUc/odiJ+l9APHZxASI0fztln8d+tsz9z1z
3zf3fbgHOiLm81AAHpXlkPh8kQI63AyeyWShXtYHIo45smDDdYXmHHhx3QYKDJ0wcfr2cvb+7cXZ
Sxhai7kMFOCN8zAEqRTzc8ri94jDPNgWSffPE0ldUw8Rj0ZSiahEtruYTrgM4uSulMz4tpCcv5yQ
PAJSyqjEtbuIfkjmd+WDg9vC6f0lnOqXZF5KQ6PYXRRnHCPUtixo9BERhgL0H6DyEPgpIRrmdsc4
zZJUZGpzF2f5ZBtr/ytiNfw+DnlqOCzR11jeXQKXIgzvoqfRbeSDP0/LEvgpcRrmHoBxlaT3YMTR
/yaMwE+FUTO3O8YZv70LEQf/+qlP8dtSLhrRDmJ5xaWaQQ0uFyKrCaYx3G4Um3cSHihkuQq89GHa
/wywgqDr1tlo3lXoLmfHF7N30zq21kqpVI4PDqDOXeXzjpdEBwXRgwYVkMBlEKWheM+zuu3XBmvo
QXUN5K94eH3HIh4LmnZcw45Q/dd330GJM57Okpf1iqUYaVq1s23VXxOA4qlKfKgqqr13sj+qzyQE
5Yb5VaNN69M+VoMwE2olMuFfNXD0H4+jtrfrnuPYTkB0x/ZjoGTdjKrBJoytsuj0JgkvgZ+mCzmP
B1FtvI3hU+4C3rJerzsCOEGiHXWNznHOpQxuhIkqNWRbD7ZCBLvYBeDR4/E1t0eM9ftGX/S5+HAP
4mmeianIoroaq7EmTmc7FB72X72y7a+mxStNz3VLBmqXD46AtFK3xwcVlTICHgOMOxGQBpugD7c9
cErnFudBLNhM8Age3psRRr/Dmkteitho+HqgAEpGD2pUSgGc6/NveUcI5YNGKug2hPAyV8lXC6XN
bQvMNTZ2iEfnPN68T7LQlw2vLQe34tF2vc7DIA83TUv+HYg0OTwsjTdrYuAhsfX85Lvh4RUxfurj
0VUFaOtJHRVUqdumiodrXsYXainiIJfDw69loZG3HB66rj59cl2CKIAh1y15Q9d7vSPgk1yqJDpZ
8TrW2mAd5us3L0//2YAJLpnxWzx4jJMbbwVBt45y+Pi2uUnWdSuOXNfzdtfnj0EYboErhz5fbELJ
EvIbUJ2DlcznYH4pudTF+QDIBZ/V1W6QX4qbWQKJpga5HNpKKvaXAmwdZu/x2iz2d90aJ4+OqCUN
jKcpX8fny3pDUQ5tZ1D7/yXuSNw+WmYPiTonoeDZGV8u6z5Yjn0Bx5mAEOO/XZyfTE+/VlooN3dd
/YPNF3Dcp7E6XwcVGoAL2UXEKuChnE1riBvD28551AD9lWDWd4Tmtrn/7p3+O5ln9xxY6eFtIPaf
d56RI0Nl416w94BD/SBLk0zdc6hvHvyRJ3MPPZ3XLFWn8yWLO+ClTApdmRJeHW1jeLtZ/COqmnoV
dTfSUOpPNTs79F5F91jWo9+LMG0cxdx5tI3R+f0Y69X+DtF0RYw8qIJr9Gentxy3+2Q7WTyv19tf
bie/1PNv96w7t5eGHbDakq/H9Jb46yTPAK8SRbiU1KZ3zBF1gL1H68m0vGMnSbwIlgzfsHEzN36C
P6Ce8w1zjpgzGncH496QvZud4C+oA5yg6Vko1Ml3IoIil+mTgNpDdLiJc+T0uji4hKlR4ouJjXcR
v7XSkG+AwckRjVDitIw9gyYmloPD6xWADQOpJkmM91ro1r9zkW2aQxnIcJIsFjjkC+llQUp0fkiC
mL1J1n+jfRPlT9zctvkw1H+4Zl/fzDUIpu/8l+c1OPga0yROsoiHRAnQZBsrDKIAUHZHNDXkUll5
6nMlClZ4HCd57AkD1+LeKhA3uKeSxZybQKwtH0BymDhxSB48DJO1tQiD5UoV87SMeBwAD9Kg12NR
Mi8GVjzzvSQrGUhv0lIswWIReHmoNhOtE/qVXyWZJYXClzvkhFDgq1RatxRkqjEphF+bQiJ5dXY8
wyGUfycFe4Y1/uQf9A9gQLtqSX4jDHekT4sUSjAXSQayKY3DMIo/wJcvKXQ2UYjmyjAKMI8sNQe2
8TUxNFgGNFhVIFrnUzBgNlsJKViBi/FMMLUSDJKEhAuumIeaUWwuWBB7YQ5dFFywO46CtC6TCFYu
kMA2TckXos0SPBqUSJLNM8Gv2SbJM0OLBQsG2IJFQDuAajKwcIhuQPiNWJfkDnyx4KAbydZJ/I1i
PE2haGIowAjAemAQG3wfDpsEjXu9EjHL02XGfSDQcWO0VU1s7MbsyWyVCZA1DAEXIY+XOXT1DN+C
I5EZu5YB3NN7FcFHEiouPVkJz6BoLgQGirgj4s46uA5SaD95J8mWB3h3gK+nXCWLq9eXb68Oe0dW
9wrXgRhLQmPmQuxcui3c6P2KjlXxJUAov3yGLwRKlZF8FR6eh+BLvn5M0iROgQ+4EopU6oubwBNs
xWM/JCVHQFjbVbUlvQII43KVKz9Bj9GHHMiMcXovTKTwNVvH6H0s1K88MfOuB7sJOPtfjDwwhSKQ
ZZ6MGeYAXHi5gnUcrVQmwI3ZRauKG0Isl2CEkC/AEAgdFDcwE5KOj3KqHljA1hyYqsifUqwr6ODb
P+jqDMwVLAJZnW+YsSOYbiJj+bQSw5NLTEVAIIk3UZJLkDnoHtB6EmXtgRErAXwi75nASI6coYas
XIut4OhNTi9ugnccy03szbi8BgPOrsEfOvj8HciUzK3gGWetMsh3sKuC2bLNKMowE43AAtuAKgIh
SEzJhBKyHo5FeQyOgFM6GoTS7gC+kiW3EBYhV2wQAFluXLKGQtLsvF6gw9E7p+BYbRaob/AV1IxW
+QKTDxnV1lq2BwhAbay77xoMlkE5JkrofDolkOt9FyZzDpYMKZnpYUaZAkNMJJZ8vlHAELvUrNi0
eSBRW9pxAdM6IMaC5ZKsfm2ZjGOGJMllEYD2IepAOI6J1AJcvtiRjA7BaD0uE8CRoKWjzGCfJTGp
U9iYDZyuS75PYVZB7OD+fzkALKIK9ntdW7M/FVmQUCwHa77W5kzRzBDdM/7BHLAE8FMfNUozLLA+
sOyCENRE4P1QCAGP6FqfgqBZh8QWUnjEwKGnuZStkAbYerGm8Bzc4W0M1orpgaZ37k5mIEZTZoKs
U+FhFpEkEuRVK0OvLQGAK4tUVjB7tsEp9+9lyKDuadRLns1B1paXhKEuxNCe75UqqQ5ZMWuYWQOe
EvE4p3xV5wJyeQ5Gs98uPHDLaozZJCgUvlgUnhhV5thhb3WyoDsIWqskD/2SkQD8dR2zinW0EZYS
5wDw0LY1RvbkFVndnUhEtqJXl6AWWRIVAQ3XmudWPQbUdAogjOq2TeEe+6mtw4JYv7up5X1Gzobh
hwaRM2wFEA3TlWSbXCGD7C31JAvDMxYCFS0kVajZ+MnRoeHzZaKXbasPQy6WGXpZnYLexUz7Cpgp
7FseVMRCoza2UGyED8pE81lSbhwLhboo6x4wjVDnnTlXUHJjFudYIkK6AXsy4YscUFd15qmOWnNR
ZiCoCIpMYyy2eIKOn20U0m4zy6kZM2Ya2tZSBSsQVgaHOqpUmY2qaEwrvg51RoF6LQwanjrse+gC
6DuCCLP9yfRdG9YCB3OIP+vAVysdIcm/S/IWkR+zoUnDVYKWJJja1A479sGfVjxcHECFTD4O2RDs
zGwEW2r7S+K6Q5a5sEarVmSc3qLzYavDw7Z2bNz4fRBDCQawwGwEmTZm1nfTeFrk5argxdIDF62h
q3Gx2o1Ty9zWCxps+eb5cmxS/AvmYGrXypRYktHjohyTFMdWoijTXKOKMXOqIkuyAyyKcqmlCiHN
l7X9ioaoUW+LovhClgGE7jRoqrEsREq61iWWT/UeLbH0kjGL4NHS1OGAhU4XkFOwNrBPike8QR+C
JnYyqrY9yFHd5Ybck7T25M3b2emYUcCF/3o5NCUxNCVEiI5oUGvEntm5ZK/U7nFDUd6KPg8xWMmA
KBsBJ2gwCo2ma5vsgVFMJyW0IGwRcdxkIuPwzeEifGFyJnfUWXDOpahttueAj9yzS5t14YFz3wOh
vM4++asUdS7IEuhLHGxJzFkFw69U9H6Y9bUmqfmrukKMAdQ9YJGCkYCHa76RmrahU7OjRugmMzqO
8NueWuyXpjQqmED2kRpMTvFgAi7HrP/ppTyDUV/zrmk0Ew5zjrr3ribrioXuv+ZCU5sL/FqH0bkD
BitUQ0lVn0bUop4Oepf8BvIttnABtpkC25Z0Y1pqk4bKWoZixIJLRVIluZgItshDmpZIMFWLWhZP
ZxGJqsiwjwXDALKFqH7Bwx+ufUPyCG0lojCJuaXEv6UMFGihjHN+y/i2XKDZ8Cg1VPbQ1AUZqfn8
qVpm9MANd+SkeqmxO5wPhcrD/JNOiMyhU4UFulnBNT902nIHZNVtFTg7d4GaMLnmAfXB0PPmwtiC
Wa/T42v1jYQ+EcMkKKzo101zBtd99o/SQTqN7kl30rmwJJjFmI0exUuapHloeDHXmP/qhKm3Ie+3
QE8IWR+jWWSxEnWGSosgISg8FDGjjglEeII1ZrqCLIwHBBznKVRUuqzUpk9hSlczhhZQGeIqsyES
HeDtmuNG5SCN8WgegF71FHN4ptvvcdG0M/pSp2jKdWetzVH7iWkXyjBKPTsewTRHysTVGE1XaRAv
ksqK8FObsd6yUzuRg2qr5E9bHol0e2/QgX461oCz2DIZtyrraDRJa0coJ3iKRsc6IkxStPM23CuO
Zz7g86a+gnJjAeWvAHCQeWJM3jjJJM0cpQGeViPCzBF/rTDIoYqUSqeuIpQZaigR/bigX3GohYLH
7veIJAwgkeh6wJzi6xusQoC+YWJccEOPwLikSsCUPuClBekDeiQY+Bkp6vhWFBj180cCUTQBuhMr
DnTJ++47zqSOlfKTpFoAYUdQIgTAqEneNdZpV2KArhie/6KrULKpdhszPAQed58P24OjW6fdu+21
u8+d5z5EBB1j9hS09fTN6mRksyXYk9R3/cE+HfeKWyViFAi9uHACGab2bRaaUO0WAv2y/Kg39XCq
uZH/DgMlevrzMUt/rPZRf0+m3+ece1CxrKovgnkIZs+zakB/rFzc5VlY3iyCUOHvZUDa0b/CL1Ra
Pl1G1TV+e6d/7oVJv8jG72fRXJ9ulpOh2tukqkKgODLk1+BeTs9oV7xOPcgC1doNAKbP1swVG+CL
LA4iZxb+WNO1B3YPLp++Br0tesOe4APfHwx6o+Gh07cP+cjudnl/PuK9Yb/vjObdvi3YU3zlZYVi
Kd9QTxMZ3FZCNx148WESAr0QC9M+wijtNxKDhcehBu3DtvZiOPSGo9HhYABb9466PdGz50fDI9+n
/eQqSioRSnIs2UQaaOHDZJVcixjielaOvBf8GiKCFhR9NbDh9LNB8fLkxyAtPkzst3777f8AUDX6
Sg==
===END CRASH DUMP===

**Comment by MagicDroidX** [comment]
the same

**Comment by shoghicp** [comment]
If you keep opening **invalid** and **duplicated** issues, you may be blocked from this organization.
