### ISSUE TITLE
Unable to Generate a New Anvil World

### ISSUE THREAD

**Issue by yungtechboy1** [PocketMine/PocketMine-MP#3044]
When i try and Generate a new Anvil Level i get this error:
18:20:31 [CRITICAL] InvalidStateException: "Could not create new Chunk" (EXCEPTION) in "/src/pocketmine/level/Level" at line 2289
18:20:31 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
18:20:31 [EMERGENCY] Please upload the "/home/PVE/CrashDump_Tue_May_19-18.20.31-CEST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
 Then When i restart server it says it loads but I am not able to Join and It says Login Timeout

**Comment by LDX-MCPE** [comment]
You shouldn't use Anvil, it's slow and prone to corruption.

**Comment by yungtechboy1** [comment]
Yea, But its Easy to Edit and Import Builds and Schematics
