### ISSUE TITLE
we need a toggle key about setLightPopulated() and populateSkyLight()

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#3045]
I don't clearly understand but,
some light fix function is exist so many perfomance problem,,,
http://timings.aikar.co/?url=11228692

I can't explain to other server manager how to fix it,
and some managers say to me 'we'll never update 0.11.0 b11'

**Comment by shoghicp** [comment]
This is not a proper issue. Please follow the contribution guidelines.

 Seems like light is being calculated on chunks and they are not being saved.
