### ISSUE TITLE
doChunkUnload() is always working problem

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#3046]
![a1](https://cloud.githubusercontent.com/assets/8337568/7710758/e52e4fb2-fea0-11e4-926b-706dea951f1d.gif)
i found something weird chunk problem
when my server no one connected,
my server over and over again some chunks unload.
(i'm tried removed chunk light function and it's a same problem exist)

it's a appeared when using mcregion map,
Connecting to the server and generated
according to several minutes over time.

http://timings.aikar.co/?url=11229731

**Comment by shoghicp** [comment]
I'm not able to reproduce this. Is this still happening? Remember to use the latest build available when testing for bugs.

**Comment by HmHmmHm** [comment]
![s1](https://cloud.githubusercontent.com/assets/8337568/7713400/73657d6c-feb2-11e4-87b7-4bdad71cec7c.gif)

I tested second test in build 1152
there still remains a little lag :S (Compared to Before)

http://timings.aikar.co/?url=11231535
