### ISSUE TITLE
I can't place rails flowers mushroom block or minecart

### ISSUE THREAD

**Issue by Villefrog99** [PocketMine/PocketMine-MP#3047]
I downloaded the latest version of the pocketmine.phar. whenever I select rails flowers mushroom block or a minecart it selcts it then automatically switches it back to the item it was before. Am I using the wrong version or is this issue already known about.
Thanks,
Ville

**Comment by LDX-MCPE** [comment]
These items are not yet implemented in PocketMine. Please read the [Contribution Guidelines](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before opening issues.

**Comment by Villefrog99** [comment]
Sorry it said I had no permission to post on the forums
