### ISSUE TITLE
Error loading pocketmine.yml

### ISSUE THREAD

**Issue by matcracker** [PocketMine/PocketMine-MP#3050]
PocketMine 1.5 Build 1153
OS: Windows 8

When I start my server, I've got this error in the console:
15:41:29 [INFO] Loading pocketmine.yml...

Fatal error: Uncaught exception 'RuntimeException' with message 'yaml_parse(): scanning  (line 37, column 1), context while scanning a plain scalar (line 36, column 14)' in phaMine-MP(Lobby)_1.5/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 138

RuntimeException: yaml_parse(): scanning error encountered during parsing: found a tab cplain scalar (line 36, column 14) in phar://C:/Users/Matteo/Desktop/PocketMine-MultiServmine/utils/Config.php on line 138

Call Stack:
    0.0121     373528   1. {main}() C:\Users\Matteo\Desktop\PocketMine-MultiServer\Pocke
    0.0141     368864   2. require('phar://C:/Users/Matteo/Desktop/PocketMine-MultiServeine/PocketMine.php') C:\Users\Matteo\Desktop\PocketMine-MultiServer\PocketMine-Servers_1
    0.1423     507408   3. pocketmine\Server->__construct() phar://C:/Users/Matteo/DesktMine-MP.phar/src/pocketmine/PocketMine.php:463
    0.1518     548480   4. pocketmine\utils\Config->__construct() phar://C:/Users/MatteoPocketMine-MP.phar/src/pocketmine/Server.php:1535
    0.1518     548656   5. pocketmine\utils\Config->load() phar://C:/Users/Matteo/Desktoine-MP.phar/src/pocketmine/utils/Config.php:76
    0.1521     559936   6. yaml_parse() phar://C:/Users/Matteo/Desktop/PocketMine-MultiSketmine/utils/Config.php:138
    0.1523     563248   7. ExceptionHandler::handler() phar://C:/Users/Matteo/Desktop/PoMP.phar/src/pocketmine/utils/Config.php:138

My pocketmine.yml configuration: http://pastebin.com/rfb16Zej
Is it my problem?

- Thanks!

**Comment by shoghicp** [comment]
You may have edited this and added a tab, **read the error message**
