### ISSUE TITLE
Problem with in-game chat message font format

### ISSUE THREAD

**Issue by matcracker** [PocketMine/PocketMine-MP#3060]
PocketMine: build 1170 
OS: Android and Windows 8 

Problems: 
When you enter or exit a server using the written format of chat colored, they are set to a predetermined format by PocketMine and so you can not change it. Image of what happens: http://i.imgur.com/uqj0Rn5.png

During testing of the formats of chat I did not use any plugins. :)

<s>Also without opening another report, when you use the command "/plugins" in the game, it says "Plugins ({0}) {2}" while the console is working properly.</s>

Thanks!

-matcracker

**Comment by sekjun9878** [comment]
Hello, please refer to #3061 for your second issue, as duplicate issues in one issue are not allowed. Thanks!

**Comment by matcracker** [comment]
Oh, sorry >.< I forgot about this thing! I'll be more careful in the future :D and thank you for opening the second issue!

**Comment by LDX-MCPE** [comment]
@sekjun9878 You do know that this is a bug with MC:PE build 13, not PocketMine, right?

**Comment by sekjun9878** [comment]
Ah of course :/ ty

**Comment by matcracker** [comment]
No @LDX-MCPE. It happened this problem since @shoghicp solved the problem of the impersonality of the chat from other players, but it was already build 13 ...

**Comment by LDX-MCPE** [comment]
![screenshot_2015-05-24-12-39-21](https://cloud.githubusercontent.com/assets/3160400/7788658/f2768b0c-0211-11e5-981a-5146f4211b1e.png)

**Comment by matcracker** [comment]
Ok  withdrawing what I said xD
