### ISSUE TITLE
Using /plugins command in game results in invalid response

### ISSUE THREAD

**Issue by sekjun9878** [PocketMine/PocketMine-MP#3061]
Originally from #3060 

> Also without opening another report, when you use the command "/plugins" in the game, it says "Plugins ({0}) {2}" while the console is working properly.

**Comment by shoghicp** [comment]
This is caused by an MCPE issue, as the string is sent partially translated with the proper parameters but corrupts it instead.

Please don't open client-side issues here.

**Comment by matcracker** [comment]
I thought it was a problem related to PocketMine, for this I reported here. But in this case it is a problem of the client so it is up to the developers to fix this problem. Thanks for the support!
