### ISSUE TITLE
items disappear

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#3064]
When a player dies and quits the server, when the player comes back their items are gone. Many players reported this to me and its true, the same thing happened to me. I think this bug is related to pocketmine.

**Comment by LDX-MCPE** [comment]
This is happening with my server, too. I have disabled all plugins, but it still happened.

**Comment by shoghicp** [comment]
This might happen if you have auto save off or there is an issue saving files (or players are closed several times incorrectly)

**Comment by LDX-MCPE** [comment]
Would having DO_LOOP enabled, then stopping the server and spamming CTRL-C cause this issue?

**Comment by Artide** [comment]
This has been fixed, thanks shoghi.
