### ISSUE TITLE
2015  Error: mt_rand(): max(-1) is smaller than min(0)

### ISSUE THREAD

**Issue by Stiletto021** [PocketMine/PocketMine-MP#3065]
Sorry if this has already been solved before. I searched and couldnt find it. I'm trying to use the stable version 1.4.1 because I have MCPE 10.5 alpha. Soft will run but wont let us in because or clients are outdated. Thanks.

PocketMine-MP Crash Dump Mon May 25 00:54:36 UTC 2015

Error: mt_rand(): max(-1) is smaller than min(0)
File: /src/pocketmine/scheduler/AsyncPool
Line: 61
Type: warning

Code:
[52] 	}
[53] 
[54] 	public function submitTask(AsyncTask $task){
[55] 		if(isset($this->tasks[$task->getTaskId()]) or $task->isGarbage()){
[56] 			return;
[57] 		}
[58] 
[59] 		$this->tasks[$task->getTaskId()] = $task;
[60] 
[61] 		$selectedWorker = \mt_rand(0, $this->size - 1);
[62] 		$selectedTasks = $this->workerUsage[$selectedWorker];
[63] 		for($i = 0; $i < $this->size; ++$i){
[64] 			if($this->workerUsage[$i] < $selectedTasks){
[65] 				$selectedWorker = $i;
[66] 				$selectedTasks = $this->workerUsage[$i];
[67] 			}
[68] 		}
[69] 
[70] 		$this->workers[$selectedWorker]->stack($task);
[71] 		$this->workerUsage[$selectedWorker]++;

Backtrace:
#0 /src/pocketmine/scheduler/AsyncPool(61): mt_rand(integer 0, integer -1)
#1 /src/pocketmine/scheduler/ServerScheduler(78): pocketmine\scheduler\AsyncPool->submitTask(pocketmine\scheduler\SendUsageTask object)
#2 /src/pocketmine/Server(2189): pocketmine\scheduler\ServerScheduler->scheduleAsyncTask(pocketmine\scheduler\SendUsageTask object)
#3 /src/pocketmine/Server(1961): pocketmine\Server->sendUsage()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#6 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.0-4086253 #1 SMP PREEMPT Mon Feb 23 17:46:35 KST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWmtz2za6/itYOTMrn4qyqKutrDubyTq7mY1bb+1MPkSZDESCEmreSoCW1U7++3neFyBFX9Lt
6dkP+6EeT0wCeO93ML/0rM5UbxlOJ+NZOBsv5oNeKo29qKqi6i1/6dl9ie3eTla5zje9QS9TxsgN
rWX2cyXzuH+8FJm87wfhsdBGmEymqaqE3cpcZDrvj44BldRp+kanBFZuZbU8OTkxtqiA6ERldSqt
ik9GJ1dFdKvspc5V5zG4vBoSzImpopOSlzM6YaKtimuQOnll9nl0VRQpzpVEzBH6DQA4nGKrt5yH
g56tZITHj72jkfgNsP15SJJ7Jejcqg3EHg1E8wiFAP9R+CvIrlV1p6rr5r2/OAXKw8nVqj26WrWE
g29Nvc60vZHmtv+Vw9cqj9+TneiQKNY/qsgyN+Mn3Dge+uPw9OzrxB8xChb8I3P1uziZfI2T8Iw1
28XndkC1QdZnFNOvoliMJl9DYWVlHfjsCfjB6/rT6fgrGD5/jorc2KqO7AOhXxdZKa1ep+o1Qsi8
K2QML3ASDx5gqq1OzWp1KXX+rthsOqeAFmEmfneMtBj+DehvPVem9Ubn5oT1NRd9Mkylfqp1pfr/
X16/qnsK4+Pepy+DnvpPp6HfkxnAh1NDb5nI1KhBLypiRVzNxkC2sl9weDbBI/2d8lJZr1MdiaTO
I6uLXHQito0Y8cLi3+NfCGrGUCurk742Rtn+C7vVJviWTpiPfDD4dqMYw1vI+ulYFJXw69r8XVZr
jgqHbe6xrWylbF3lL2lx4ReZ21PP7Zlf/HfkxLkjRpjmIwc8Dxtgo1J4r4o/FNUtdH4uVqvGKsiH
HrfRPysRiPCYcYwfwxIpw2T49I5Rcax/fIT/EyOYeARJUfVfaACOXgr8/UuX3EvxzTcvNOtkPm11
Ah0/R0R/IuAH7DjIWQv5nKgvNLMzf+7Qr8mknRiLFo7sMj/tGGl+5vS8GD00kkNjnqiFc1t023du
RdgX4XOQzyv1m29e9r78UQT/KIJ/FMH/piI46G1UriqZUr2B5g2qCYI6HE6HIdhZ1zqNe8uz0xGK
VFXYIkLpWo7xJkvN58JwOMLBjbZ4Hf3GHwBU8jbVa4IZLhhDnUuaFHrvdF7fi7SIZLotjBUTsDIK
pqPT+Xg2EYj068srcfXDxcXl1Y24RO17o9ZiPBHhYjmdLycz8c/rGzEehTMhq+xuQZWW2vZlbzac
D8d4+xn+jdcxXkdu83NhGsJY4Bekm6rQca8tzlj8CG2VsgKbFopy74b9dQjdlKqyWhHs0VX7Jl4X
eaI3ghqDVbXKj4jhS7kX45kYjZaz6XIyF+9vXjPDdMDhC0gX52SmqJKJXYqrC+Eio3OmLCp7Hp6F
kzEtbgCRoW84D+kNnUpQpnIPPs9525RylwdkQsUdw3k4p+XdVluVamPPiyShBZVLxFbwU62q/aO1
ChHZLMXKRJUuGZNjDM1RrERtyFsf+CGzU9j4/INKoyJT4q+OMWELQWVDOHH+1JGMurHzvKjQYzE0
BKv2QaqRj8/D8eklLdIUGdRljChomJJ5XqAhUl7yQEZbre5UpnJrmjN3Wu2CGAJLHDwPRwyXpsUu
SFK92bZ6cPqSuQYPAM4Pa1mxbhYQYHFUVC0D5V3ZKkgniY7q1O7PmYaLMkRvgO7LQknmnKUAf6mz
NopnGh/WjFJx5wir5G8Xb169f3dDq2SMYYkMCLD4/H/4B5LUtgiMvFOeQTZv0LUv2hkoqHUWv0ph
0CaJ4T5LyYsFpU4RsQPX4J36TPJjARxdE18XiYVni5utMko04iH6FOyrRJEjDNAmWxGRgaxYK1Tv
KK1jFeNBPIkgwnVNjlIkhOAxTiMTNRAFdipDKMW6UvJW7Iu68riETgSk04lmCrBQBadP94T4O7Vr
0Z3EKpEwkRG7Iv+zFbIslawEKTGDuEhA6R7sOy9lyXdblYu63FQyBoLhKieXdciWq1wc3WwrBX1j
CVykMt/USNaC2nlWmndvo/HOCU7/zGol0NdbFXkpHgKCga21pUH6V/lwp291qWIth0W1OaG3k3cw
7+ci+fz2+vvP88lZMP5McFBji2gpVj2Vb1Y9IvRhq0h3FH5U6QWk9HUKZkKbZbiwuG3WJnOqaB6A
YGzSWN3pSAmMPnHKRs6A2HnWgSTPMlg329rGBQWOG6mIGZ8yorQwKnZsvaIgFOSqXO9czhV3Wop/
US7CEc5Jgd9Zgtea0B9dbwEnyU9NAW48FWcq6REhL8EJY1XCEVi6V1dvcdJui5j0dNgIwNYaTB3Q
X3Dya/BAYkERL+Cu8Ahidb0X3o9w3KfKdrfDJnQNB86LfJ8VNbKehekhbGRI1RF82FL6JNYrRamd
GCMDBbXTWoPouzpbUzOTiMOk51v2Ie2/h0rZ2xqW6dS2KnKiygPYQHCuET4nwQEHECqDDgyVfxZy
h6KKtazOEQd0ZOiEsC4aECpVcY/kiOqxJwHYcfOWNdKRY+dtQvFGRyiu0LjbP8PhbMVQsaJyxD71
CFb0IQGsJsbHKy9D4KVcMiaKPVcYOPL+nhZrCUdGLhJuWXC9oAyTqY1c7y0YEteOlRET14aM5eIW
Mu00M6a5V6SK4OuOXzKslwRNGR4EknLOqBJEfEORfY6EcXbcFJCjuONbAk3m3DCTrpAtUfKnpyuO
fU60FrlDxv/lEmTgtOE/HI2njv8rVemCkzn8+dY5NKczj7XvA0SE8AUEakw25RMB/E+RKhwidEsI
/1oRkxRbX5PB8Y7qlnJ+pMzhjq24YBEOeHsD08QOUfg+h79SfeDjw6eH6XLHRXEMZZcqojJiWCfE
q7OGg20FQDCr0hzEnIy8nOb4WYa81BMn9cZdrgRorVPXnJFHP6tVth2x4mGEhymo/cprLlhdLlDO
a3jN8aCJwUdu4/2mIKXIJGliMTv441B876oFvyFtbYs6jVtGNCJ2l4sD6+QkomTOIeAcvT7LKI7e
sNs9yUXsKw66FSqpiqxJaQTr94NuFujYFEJ40z12hWf8pwNHPXK0rfNb4/T9jqONEhAvEmcpxkuS
RriOcsCxUKF8G3cooARNncABF6FqzOwD5Wzu+fxb4cAem4+SLvUZDqyLwVHxx/4DMnPiDyJ0xspJ
7X2hIUQbban5VVSrPFeWbNE2PnCN1FWetbRovamMS+oSDV3XCJ+/OABdW+d3Xdpaq7YGoSVoao33
2GaHAr/aW8I9EEHYcWaqNUw2sA0rSCuzucsqh9rG3TQVltjlOm9AB4tFz9NQ/APTAF/AZVTuX1+9
HwAWHKyRf3Y6tluXIjm+W/QBo1+KhS/EhxJtWDGdo0PxKkY8bWWanKBF5hhHPYSfeUIg6fyvyLsB
2VbDDq5Ds3V0cU/BRyOPTAcusInwB52jB4NYcBvFrk219f1VftVU5kPHS80HAe0w3ayo3c3LwL9y
R+Np0RC4rjdLX+S/FSEVd2dMQz0Zbzf9mOE8tlVNn7bypkAZOXRZhm5KpK2N0ypSWmwOHtfMRQ/6
bdU0X8QxZHCTBh/1jkWCsqldjxVzv8cggQNZigxbG9+HQxQiSB1RDmeDe3I6kg/wI2fSJGM75Hma
fcINRycb7ei7728uloLzLX6jGkNJjqGEEemsTHlOZfY85Za91rivHtgpQv+NHOJlZf/hYgROyF8s
+cx45IsHJTFXk8iBaEykdV+IfLw/XG6y18wHo6uBa2lUh1Y/RIQ8Q2QgxtgIn9tQNhoec7Qa1WWC
/eCGMNNE4i8vhEJGcvSo5jtD8ux3GAopA/DwQD0K5QGZ7uTeONwez8GLHuRtdqJX6MfzbuI3vjFq
eCDuCRkOl3Q7gUfklq+DygqrsWPd4XhYbUR49jw0+1au3PS1Vg7bWiWUgfjygTIVWaHF6q4kOinP
ZbxreYdiSwOcpiFT0dBS7v1A7WtQ28hwgkiksaxU1otPX0md8rHCwFEDnlgiV0IMWaKiKRZ+AbSN
qn4saOJwkWFkRq6ScY6kwtLK32YQZwxSaGOMS3kv5GO9YNaIuC4c3OGBLUYE+QNm8tp0oLwZpOjc
NzlI73V0Hk3K/y04+ZbIXzwdRMEoq6Rjh69bnsh4mLUaMYdP5fQpcic1D8EYeGvlXcHDMwu8HtAH
qKU4/V3YyqJ098ekRvdM1auLeEy8c/QGUDQx7S7DAnY5SD6l1g6+kZPjtKuhzyN0CbUUrv9rrA8V
5XWJfsg1hc53Ocu4XsTjApYFQXmChJRyEAQhQu0ir8lsrWEZd8Tff7nxedkM3cj70mybodpNxs6f
nKP7Zr/Ngjxz0w3Kw5W27jxYLbelzpPi4Ad0Zb10JIedKzX0Si1/zndYpY9pwwZud+kErvLA18tD
U8arRXlgxJHc7XbPEUw10qwrlhf3kjzZvVCFhnf4G/+l8A+8BdMZW8BQH+kxQHKlLxlF+YkwuvBv
qm/3co6rbdMguymlufTk8eO5uz6e5jh7Gy6U5KgZ6qcGo76ydVhnqswAPwm6IyVHnPJbS20p3rx7
dbMcv1wMZmf34WByPxmMX4YvY1QgF4N9i5k3ong5Px2JDaxl3Nt0dsy3oereqpwUYui7yGsk4M4H
BDJQ5xV5cNN+ui8jOupfzE+ptmriPnIEsbqjrw/uq8eYvz2sI5Tz7eG7v0zhVLI6LLj/l9C81VXa
viQ6hRMxav8JJrFlu7vJDs9b+CJ/qqFDPxr/fWfM33eytbv6aw+jFdqX9iCBlcRQ3BH3+uodU6Xn
MkKWPMDuITB/W/FPYjYk7khyEdAnjvFoNprg8cVb2C2ZLCZKzuJ4NpucLubhdDSXp6PxWE7Xp3Ky
mE7D0/V4OlLiBShdbUktpDZHuDD6/qB0P536AyEJ+oNK/GiFVaZ3qmZJJNGgTUF2lCwW0eL0dD6b
gfTkbDxRk9H6bHEWx0zPbLPioELDgWUeSqqd8nHYFrcqR9as2pUPSt5WKnGKGs6wspd8qx4OQz7w
sy7d23g47X358r9iCq82
===END CRASH DUMP===

**Comment by shoghicp** [comment]
You put invalid settings in your PocketMine.yml

Please don't report this kind of issue
