### ISSUE TITLE
Bone Meal  seems that it can not be cancelled

### ISSUE THREAD

**Issue by alejandroliu** [PocketMine/PocketMine-MP#3068]
If I cancel in PlayerInteract with a Bone Meal item (Dye with Damage = 15) the client still grows grass.  However the server doesn't.  That is if I quit the server and join I can see the level without the tall grass, but until then, I see large grasses around.

**Comment by shoghicp** [comment]
That happens because the client predicts interactions. Some of them are bugs and some others expected behavior, this one seems a bug of the client

**Comment by shoghicp** [comment]
Could you report this on bugs.mojang.com?

**Comment by alejandroliu** [comment]
Done
