### ISSUE TITLE
CRASH DUMP

### ISSUE THREAD

**Issue by Kiko1234** [PocketMine/PocketMine-MP#3069]
EVRYTIME I OPEN MY SERVER IT CRASHES

**Comment by Kiko1234** [comment]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 08:43:22 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 08:43:23 [INFO] Starting Minecraft: PE server version v0.10.4 alpha
[Server] 08:43:23 [INFO] Loading pocketmine.yml...
[Server] 08:43:23 [INFO] Loading server properties...
[Server] 08:43:23 [INFO] Starting Minecraft PE server on 1215454134:19132
[Server] 08:43:23 [INFO] This server is running PocketMine-MP version 1.4.1dev-936 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 08:43:23 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 08:43:23 [CRITICAL] **** FAILED TO BIND TO 1215454134:19132!
[Server] 08:43:23 [CRITICAL] Perhaps a server is already running on that port?
[Server] 08:43:23 [EMERGENCY] [RakLib Thread #1078738216] RakLib crashed!
[Server] 08:43:24 [ERROR] Could not load duplicate plugin 'SimpleAuth': plugin exists
[Server] 08:43:24 [INFO] Loading VoteReward v2.1
[Server] 08:43:24 [INFO] Loading FactionsPro v1.2.0
[Server] 08:43:24 [INFO] Loading SimpleAuth v1.6.0
[Server] 08:43:24 [INFO] Loading SimpleWarp v1.4
[Server] 08:43:24 [INFO] Loading Blood v1.1.1
[Server] 08:43:24 [INFO] Loading ChatDefender v1.1.1
[Server] 08:43:24 [INFO] Loading AlwaysSpawn v2.1.3
[Server] 08:43:24 [INFO] Loading AdvertisingKick v1.0.0
[Server] 08:43:24 [INFO] Loading ItemCloud v1.1
[Server] 08:43:24 [INFO] Loading HealthBar v1.0.0
[Server] 08:43:29 [INFO] Enabling SimpleAuth v1.6.0
[Server] 08:43:29 [INFO] [SimpleAuth] Everything loaded!
[Server] 08:43:30 [INFO] Preparing level "world"
[Server] 08:43:30 [INFO] Enabling VoteReward v2.1
[Server] 08:43:30 [INFO] Enabling FactionsPro v1.2.0
[Server] 08:43:30 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 08:43:30 [INFO] Enabling Blood v1.1.1
[Server] 08:43:30 [INFO] Enabling ChatDefender v1.1.1
[Server] 08:43:30 [INFO] Enabling AlwaysSpawn v2.1.3
[Server] 08:43:30 [INFO] [AlwaysSpawn] AlwaysSpawn Loaded!
[Server] 08:43:30 [INFO] Enabling AdvertisingKick v1.0.0
[Server] 08:43:30 [INFO] [AdvertisingKick] AdvertisingKick Starterd
[Server] 08:43:30 [INFO] Enabling ItemCloud v1.1
[Server] 08:43:30 [INFO] Enabling HealthBar v1.0.0
[Server] 08:43:31 [INFO] Starting GS4 status listener
[Server] 08:43:31 [INFO] Setting query port to 19132
[Server] 08:43:31 [INFO] Query running on 1215454134:19132
[Server] 08:43:31 [WARNING] RuntimeException: "mt_rand(): max(-1) is smaller than min(0)" (E_WARNING) in "/src/pocketmine/scheduler/AsyncPool" at line 61
[Server] 08:43:31 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 08:43:31 [EMERGENCY] Please submit the "/storage/sdcard0/PocketMine/CrashDump_Wed_May_27-08.43.31-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 08:43:37 [INFO] Disabling VoteReward v2.1
[Server] 08:43:37 [INFO] Disabling FactionsPro v1.2.0
[Server] 08:43:37 [INFO] Disabling SimpleAuth v1.6.0
[Server] 08:43:37 [INFO] Disabling SimpleWarp v1.4
[Server] 08:43:37 [INFO] Disabling Blood v1.1.1
[Server] 08:43:37 [INFO] Disabling ChatDefender v1.1.1
[Server] 08:43:37 [INFO] Disabling AlwaysSpawn v2.1.3
[Server] 08:43:37 [INFO] [AlwaysSpawn] AlwaysSpawn Unloaded!
[Server] 08:43:37 [INFO] Disabling AdvertisingKick v1.0.0
[Server] 08:43:37 [INFO] [AdvertisingKick] AdvertisingKick Stopped
[Server] 08:43:37 [INFO] Disabling ItemCloud v1.1
[Server] 08:43:37 [INFO] Disabling HealthBar v1.0.0
[Server] 08:43:37 [INFO] Unloading level "world"

**Comment by JoahDave** [comment]
I might be of some help. Please PM me on Twitter, or email me.
