### ISSUE TITLE
setArmorItem does not update

### ISSUE THREAD

**Issue by alejandroliu** [PocketMine/PocketMine-MP#3073]
If I do:

    $player->getInventory()->setArmorItem($slot,$item)

The client does not change its armor configuration until I open the inventory window and fiddle with it.

Not sure if this is a MCPE client issue.

**Comment by PEMapModder** [comment]
What version?

**Comment by alejandroliu** [comment]
Mcpe 0.11

Using the latest git commit.

Seeing that it was summarily closed I assume is a client issue.
