### ISSUE TITLE
setComponents not defined

### ISSUE THREAD

**Issue by LEETcc** [PocketMine/PocketMine-MP#3074]
http://crash.leet.cc/view/167556

**Comment by LEETcc** [comment]
Introduced here I think: https://github.com/PocketMine/PocketMine-MP/commit/0f5f71e612bf8b7882e60e8788e9fc92a118f5e1

I believe this bug is in all Build 14 versions.

**Comment by shoghicp** [comment]
Hmm, why is that called before the construct?

Also, nice having your own crash archive :)

**Comment by LEETcc** [comment]
Yeah, had to after you shut down the public one :)
