### ISSUE TITLE
Splitting oversized server logs

### ISSUE THREAD

**Issue by PEMapModder** [PocketMine/PocketMine-MP#3079]
This issue is to suggest the the feature of deprecating oversized server logs be implemented.

Introduction
===
Occasionally server owners and developers face the difficulty to read console logs due to lack of appropriate tools to open large files like console logs. (Servers can easily chew up gigabytes of logs, and not everyone has a tool to or knows how to obtain a certain string from files of gigabytes like using `grep` or `tail`.) It may take quite a bit of time for computers (or even mobiles) to scan across gigabytes anyway. A good solution to this problem is to split the file when it reaches a certain limit.

Description
===
This is something like what is implemented in Apache's `access.log` and `error.log`. When the number of lines or bytes in `server.log` reaches a certain limit (probably configurable in `pocketmine.yml`), the server renames `server.log` into `server.log.${i}` (or `logs/server.log.{$i}`), whereas `${i}` is an incrementing integer. Next, the server creates a new `server.log` and log contents into this new file instead.

Backwards compatibility
===
As file streams resources should not be accessed by plugins or other external tools, such change should be backwards-compatible.

Customizability
===
There can be an option in `pocketmine.yml` for setting the limit to split the file.

**Comment by shoghicp** [comment]
This can be done with `logrotate`, if you restart the server daily or run it on a cronjob.

**Comment by sekjun9878** [comment]
I agree, under normal circumstances this should be done with logrotate. However, it wouldn't hurt to have at least basic logrotating functionality built into pocketmine (which can be disabled).

**Comment by jython234** [comment]
I personally think this feature would be a good improvement. For example, the vanilla MCPC server logs to the file latest.log. When it becomes a new day, that log is compressed and renamed to log-[date].log.gz and a new latest.log is created. This would improve the endless time of searching through this 5 MB large log file for one particular line that you knew happened on a particular day.

**Comment by sekjun9878** [comment]
@shoghicp Want me to implement this?

**Comment by shoghicp** [comment]
@sekjun9878 as I said, this can be done using logrotate. Let's follow what the official MC PC server does by default on both .exe and .jar versions.

**Comment by sekjun9878** [comment]
Any other comments or opinions before this issue is closed for wontfix?
