### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Stephanie1212** [PocketMine/PocketMine-MP#3081]
I'm using PocketMine ,plugin pureperms ,simpleauth, myhealth. Server says [Critical] MyHealth ran out of memory Please fix

**Comment by Addison118** [comment]
I believe this is a problem with your server. As it says, you ran out of memory.

**Comment by Stephanie1212** [comment]
I have memory It still dosnt work

**Comment by Addison118** [comment]
How much RAM is your server using?

**Comment by SuperPitty** [comment]
So, if the RAM is full the plugins we using not working?

**Comment by JoahDave** [comment]
This might be a MyHealth problem. Please refer to the JoahDave/MyHealth respiratory.
