### ISSUE TITLE
Player->setMotion() only works in a direction

### ISSUE THREAD

**Issue by Striker209** [PocketMine/PocketMine-MP#3084]
Hi,
I'm making a plugin so that players walking on a certain block get bounced in the air. The problem is that the setMotion function works only in a certain direction (I mean North or South or East or West by direction).

**Comment by shoghicp** [comment]
setMotion() is not dependent on direction. Seems like you don't know how to handle negative positions on your plugin, which causes it to set the wrong motion.
If any, there was a problem with downwards motion.

**Comment by Striker209** [comment]
Since I updated from Build 12 to Build 14, the bug no more occurs!
