### ISSUE TITLE
Cant teleport Player

### ISSUE THREAD

**Issue by RaymanT** [PocketMine/PocketMine-MP#3085]
I cant teleport a Player in the PlayerJoinEvent or in the Respawn event. Before the 0.11 it worked as well

**Comment by PEMapModder** [comment]
Suppose you should use `setRespawnPosition` instead?

**Comment by RaymanT** [comment]
No i dont want to set a new Spawnpoint :/

**Comment by RaymanT** [comment]
Thank you, but i really want to teleport a Player instead of setting his RespawnPosition

**Comment by Striker209** [comment]
You have to use setRespawnPosition, no other ways to do so :D

**Comment by RaymanT** [comment]
Im reporting this because it workes before the 0.11 so maybe it is possible to change this in the source code

**Comment by shoghicp** [comment]
This is just an implementation detail. MCPE changed how it spawns so you can't teleport it there. If you can handle an event and set the destination on the event itself, that works better than manually teleporting players, as PocketMine also expects a change there and prepares for it.

**Comment by RaymanT** [comment]
Ok thanks
