### ISSUE TITLE
Unexpected Return

### ISSUE THREAD

**Issue by yungtechboy1** [PocketMine/PocketMine-MP#3088]
Parse error: syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) in phar:///home/--/PocketMine-MP.phar/src/pocketmine/Player.php on line 1375
16:22:36 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
16:22:36 [EMERGENCY] Please upload the "/home/--/CrashDump_Sat_May_30-16.22.36-BST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by shoghicp** [comment]
I'm not able to reproduce this on the latest promoted development build. Are you using that one?

Remember that using non-promoted builds **is not supported** and counts as an invalid issue.

Please remember to follow the contribution guidelines in the future.
