### ISSUE TITLE
Players freeze for 1 second

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#3090]
In my server something weird is happening, sometimes the server lags or freezes very badly for 1-3 seconds, this only occurs when players are walking. Is it a plugin issue or a pocketmine bug? Thank you. :)

**Comment by shoghicp** [comment]
Please don't open duplicate issues related to the client.

**Comment by LDX-MCPE** [comment]
Which issue is this a duplicate of? I have this problem to the extreme, even with 20 TPS.

**Comment by Artide** [comment]
The problem got worse, the lag is more than what you play.
