### ISSUE TITLE
dev 1.12.0 starting server problem

### ISSUE THREAD

**Issue by deathcraft1** [PocketMine/PocketMine-MP#3092]
hi I'm using a mac and downloaded pocketmineMP dev 1.12.0 version after installing on my terminal and starting server it shows this msg in terminal  and the server dosnt even show upat all..

Failed loading /Users/public-demo/.jenkins/jobs/PHP-PocketMine-MacOS/workspace/compile/mac64/bin/php5/lib/php/extensions/no-debug-zts-20131226/opcache.so:  dlopen(/Users/public-demo/.jenkins/jobs/PHP-PocketMine-MacOS/workspace/compile/mac64/bin/php5/lib/php/extensions/no-debug-zts-20131226/opcache.so, 9): image not found

can someone please help I'm new to PM.. ps the normal pocket mine 1.4.1 works its only dev build that dosnt.. or is there a way to run api 1.12.0 plugins on 1.4.1

**Comment by deathcraft1** [comment]
I'm definatly missing something here :/

**Comment by shoghicp** [comment]
This is not the place to open this issue.

**Comment by deathcraft1** [comment]
can u point me in the right direction then
