### ISSUE TITLE
Bug when placing blocks !

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#3093]
On the last PocketMine 1.5 build and MCPE 0.11 build 14 when you are placing a lot of blocks to go up you frequently get into the block when falling (because of the jump) after placing it !

![placingblockbug](https://cloud.githubusercontent.com/assets/186746/7916945/020fe572-0898-11e5-87ec-93485f624061.jpg)

**Comment by JoahDave** [comment]
Reproduced

**Comment by shoghicp** [comment]
Is this still happening on the latest development build?

**Comment by roroB20** [comment]
Yep ! Confirmed on #1​23​8 !

**Comment by shoghicp** [comment]
The server calculates bounding boxes a few ticks after the player moves, which can cause this.

**Comment by roroB20** [comment]
So is there a way to fix it ?

**Comment by DanielZ123** [comment]
Make a plugin and $event->setInstaBreak(true);
