### ISSUE TITLE
Bug when disconnecting on leaves blocks and back to the server.

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#3094]
When you are on a leave block (exemple on the top of a tree ;) ) and disconnecting then get back to the server you are now inside the leave block ! (Can be seen on pictures)

Before:
![beforereconnecting](https://cloud.githubusercontent.com/assets/186746/7917053/9caf4b04-0898-11e5-8f0b-56a0916a6e64.jpg)

After:
![aftereconnecting](https://cloud.githubusercontent.com/assets/186746/7917057/a71bc28e-0898-11e5-8114-810107809575.jpg)

**Comment by DunxGit** [comment]
This may be something to do with minecraft itself. It does that to me sometimes in singleplayer.

**Comment by SuperPitty** [comment]
Is this bug or glitch?

**Comment by roroB20** [comment]
A bug ! you're really inside the block !

**Comment by DunxGit** [comment]
Can you get out?

**Comment by roroB20** [comment]
Yes, but this is definitely a bug ;) !
