### ISSUE TITLE
Muy server crash

### ISSUE THREAD

**Issue by SoyBueno** [PocketMine/PocketMine-MP#3095]
And fatal error ocurred un muy server.muy console write me:fatal error:Call to member function set () on pull in phar:///storage/emulated/0/pocketmine/plugins/plugin-613.phar/src/shoghicp/CustomsRanks/main.php con line 52
[EMERGENCY]:an unrecorable has ocurred and the server has crashed.Creating a crash dump
[EMERGENCY]:please upload the "storage/emulated/0/Pocketmine/CrashDump_Sun_May_31-18.23.11 -UTC_2015.log file to the crash archive and submit the link to the Bug reporting page.Give as much info as you Can.

**Comment by SavionLegendZzz** [comment]
that is a plugins fault not the new build fault
