### ISSUE TITLE
Pocketmine allocating CPU "whacky" 

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#3100]
I updated to the most recent build of PocketMine this morning (Build 2000). It seems to not allocate much cpu to handle much of a player load. It seems to go from 11% usage to 100% (this was in PocketMine stats. I checked the Linux server stats and that bounces from 50% (when PocketMine is 11%) but then 22% (when PocketMine is 100%). The cpu allocation seems to start becoming unstable when about 10 people on.

**Comment by shoghicp** [comment]
Is that percentage the one over all the cores or per single core?

**Comment by peepzandmeepz** [comment]
I'm using async auto so all cores (so 4 cores). The Linux percentages I was mentioning were from an overall statistic (so all 4 combined). I've also tried setting it specific to one core but the problem still occurrs.

**Comment by peepzandmeepz** [comment]
Correction: By setting it to a specific core, I'm mentioning changing the async in PocketMine*

**Comment by shoghicp** [comment]
@peepzandmeepz Using async won't off-load calculations that are done normally on the main thread, so if no world is being generated it won't be used. 22% * 4 is 88%, more likely for 100% (but still strange)

Remember that you are running of a development version and lots of changes can happen all the time.

**Comment by peepzandmeepz** [comment]
The 22% accounts for the stats of all 4 cores. So meaning each one is only using roughly 6%.

**Comment by peepzandmeepz** [comment]
Sorry if my English isn't great, typing on mobile is not fun. Also, thanks for the info on async.

**Comment by shoghicp** [comment]
@peepzandmeepz it also means that one of them is using 88%. Please open an process manager that lets you see it per core to see the percentage directly (for example, `htop`)

**Comment by peepzandmeepz** [comment]
I see what you mean now. There is one core that has a higher percentage compared to the rest. Still odd on how low the cpu usage is compared to the older builds(via Linux "top"). Just found it odd how little it was allocating for the server.

**Comment by shoghicp** [comment]
We know about that issue but I'm not able to reproduce that locally :(

**Comment by peepzandmeepz** [comment]
Is there anything I can do to give to help you get information on this?

**Comment by peepzandmeepz** [comment]
I can provide logs, reports, give you access to the server, ect if requested. :)

**Comment by shoghicp** [comment]
@peepzandmeepz 

Set `settings.profile-report-trigger` to 15 and `settings.enable-profiling` to true on pocketmine.yml

After the CPU thing happens and tps lowers, execute the `timings paste` command and submit the resulting links here (the timings.aikar one)

**Comment by peepzandmeepz** [comment]
I'll get back to you shortly with the reports.

**Comment by peepzandmeepz** [comment]
Hi there! Sorry I didn't get back to you, was swamped.

I did a few timings reports it's a bit hard to catch when the CPU is allocating weird.
http://timings.aikar.co/?url=11566662 <<< This one seems to have a higher CPU usages.
http://timings.aikar.co/?url=11566682 
http://timings.aikar.co/?url=11566708
http://timings.aikar.co/?url=11566711

I noticed that one of the plugins had a high CPU usage also. But I believe that only contributes some of the high CPU usage.
Hope this helps! If you need more/different reports, I will be happy to provide.

**Comment by shoghicp** [comment]
Can you check this issue again?

**Comment by peepzandmeepz** [comment]
Seems to allocate CPU a lot better with the newer updates and a semi tweaked pocketmine.yml  

It still seems to be allocating a low amount for when players join the server. It seems to affect it majorly when multiple users join with-in a short amount of time. The lag/cpu allocation issue is only affected when players log onto the server successfully, haven't had a problem with cpu when players join and get kicked (white-list, full server, ect).

**Comment by shoghicp** [comment]
@peepzandmeepz That is chunk loading, sometimes it can be quite slow when accessing the disk. On SSDs it should behave better, also needs to send them over the network. Try enabling the chunk cache if you have a mostly static world or limited to a small area.

**Comment by peepzandmeepz** [comment]
So I'm assuming that world size has a factor with that. They are running on SSDs. However overall, seems like Pocketmine is allocating CPU more efficiently in the newer builds. :D Thanks!
