### ISSUE TITLE
Black Grass Blocks on Imported Worlds

### ISSUE THREAD

**Issue by iVertx** [PocketMine/PocketMine-MP#3101]
well i`m having an annoying issue with all my PC imported worlds for a log time... I have one originnally McRegion world, and 3 Converted from Anvil to McRegion, and a test fully Anvil world...
on all those worlds, every grass block are black... probally a bug with the especific grass color or texture...

see:
https://www.dropbox.com/s/rbht21urqcwsuf9/Screenshot_2015-06-04-11-39-38.png?dl=1
(is a link because github uploader are bugged for me)

On Pocketmine generated worlds it doesn`t happens...
also, I already see the same issue on another servers... so it`s not only an issue with my server, but a PM or MCPE issue...

**Comment by shoghicp** [comment]
MCPE does not calculate grass colors, so it needs that information.

Biome colors are not populated on old worlds yet, as not all biomes have been implemented yet.

**Comment by iVertx** [comment]
nop, i`m talking about normal biomes... not colors...
How I said, it`s also happens on not coverted mcregion worlds...
complementing...
on old mcpe 0.11 pocketmine builds that bug doesn`t happens...
unfortunatelly i don`t know in how build that started to happens... bug if you want, i send these worlds folder for you... i think is better see with your eyes what is the issue

**Comment by shoghicp** [comment]
yes, biomes have grass colors. there is already an issue about this, but as everything, needs time for fixing it

**Comment by iVertx** [comment]
ok, I understand... thanks for your time and keep your good work!

**Comment by mightysun99** [comment]
@shoghicp Where is the other issue regarding this i cant seem to find it?

**Comment by LouisBHirst** [comment]
@mightysun99 : https://github.com/PocketMine/PocketMine-MP/issues/3180

Bart Hirst
(484) 802-4798
http://www.linkedin.com/in/louisbhirst
