### ISSUE TITLE
Entity ticking

### ISSUE THREAD

**Issue by LDX-MCPE** [PocketMine/PocketMine-MP#3104]
There are some major problems with entity ticking. After taking timings, I can see that the entity ticking functions are having thousands of violations. The symptom of all this is that my players only move about once a second. Even with 20 TPS and only two or three players online, players move very laggily. Here are the timings:
https://gist.github.com/LDX-MCPE/a03555b9e4d22923e99f

**Comment by shoghicp** [comment]
Seems like you are not using the latest development build - timings are different now. Please reopen a new issue if entity ticking is still the source of all your lag.

Also, in the future, provide a direct link to the timings.aikar system - it's uploaded to paste.ubuntu.com with a direct view into that tool.
