### ISSUE TITLE
Sever trys to use invalid provider

### ISSUE THREAD

**Issue by RaymanT** [PocketMine/PocketMine-MP#3115]
When im unloading a Level this will crash my Server
because it trys to get the name of

11. pocketmine\level\Level->unload() C:\Path\src\pocketmine\Server__32bit.php:1021
12. pocketmine\level\Level->getName() C:\Path\\src\pocketmine\level\Level__32bit.php:507

**Comment by shoghicp** [comment]
* You are unloading a level twice
* Level->unload() should never be called directly.
