### ISSUE TITLE
Playerdrops

### ISSUE THREAD

**Issue by RaymanT** [PocketMine/PocketMine-MP#3116]
When a Player dies on my Server with some stuff in his Inventory and respawns the items get dropped at his respawnpoint instead of his deathpoint

**Comment by L3ice** [comment]
Can reproduce

**Comment by shoghicp** [comment]
Do you have a plugin that teleports or does something on PlayerDeathEvent? that could be the source of your problems.

**Comment by RaymanT** [comment]
Oh yes, sorry for that. Fixed now
