### ISSUE TITLE
Level Error

### ISSUE THREAD

**Issue by kevin200** [PocketMine/PocketMine-MP#3118]
I got a Error "[CRITICAL] Could not tick level "world": Division by zero", and I use  build 1213

**Comment by L3ice** [comment]
Same

**Comment by shoghicp** [comment]
It would be nice to get a stacktrace or the full error message, as we can't guess what happens.

**Comment by L3ice** [comment]
For me there is no real "error".
It just says "[CRITICAL] Could not tick level "world": Division by zero" when I tp me in another level.

**Comment by shoghicp** [comment]
did you remember to enable debug level 2 on pocketmine.yml? This is a given when debugging an error.
