### ISSUE TITLE
issue from the latest Minecraft-PE upgrade for the iOS

### ISSUE THREAD

**Issue by perzeababa** [PocketMine/PocketMine-MP#3119]
Minecraft-PE version 0.11.1 was released two days ago from the iOS app store. I noticed that any client that updated to this version can no longer connect to my pocketmine server. I would see timeout based logouts as well as client disconnects.

I'm hosting my server on an iMac, running PocketMine-MP version 1.4.1-980 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)  

Am I the only one experiencing this issue? Are there any work-arounds?

**Comment by Gamecrafter** [comment]
Seriously? Of course you can't connect. 0.11.0 clients cannot connect to older servers, and you said you were running it on 0.10.0.
