### ISSUE TITLE
Pocket Edition v0.11.1 alpha

### ISSUE THREAD

**Issue by jingz2007** [PocketMine/PocketMine-MP#3121]
You can not join a pocketmine server while running pocket edition v0.11.1 alpha. It indicates in the console an IP unsuccessfully tried to join the server.

**Comment by PEMapModder** [comment]
Yes you can join.

**Comment by jingz2007** [comment]
I am running the current stable release on a raspi 2 with 1GB ram and an ARM A7 processor.
