### ISSUE TITLE
"Invalid Playername"

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#3122]
Having a error (on the newest build) where the server is constantly kicking users for reason "Invalid Playername"

It seems to be affecting players with capital letters in their name (all the names trying to log on worked prior to).

Currently running the most recent build.

**Comment by peepzandmeepz** [comment]
If you are unable to reproduce locally, I can provide server logs.

**Comment by iJoshuaHD** [comment]
hah! here's my two cents! same issue!! :O

**Comment by Gasker81** [comment]
Same here bro I was almost done finishing something and then it kicks me saying Invalid Player name

**Comment by Gasker81** [comment]
someone help plz!!!

**Comment by shoghicp** [comment]
I'm not able to reproduce this on the latest development build.

    ^.^

**Comment by peepzandmeepz** [comment]
I shall attach a log! :D One sec

**Comment by Gasker81** [comment]
what?

**Comment by shoghicp** [comment]
@peepzandmeepz Why do you need to attach a log when this has been fixed?

**Comment by peepzandmeepz** [comment]
Didn't see the new comments xD My bad.. Thanks!

**Comment by Gasker81** [comment]
@shoghicp thanks bro!

**Comment by iJoshuaHD** [comment]
@shoghicp try adding a capital letter in your name :P

**Comment by Gasker81** [comment]
@iJoshuaHD its fixed restart your pocketmine window

**Comment by peepzandmeepz** [comment]
@shoghicp Having the same issue with underscores :(
