### ISSUE TITLE
MP Server v1.5dev-1206 API 1.12.0: Maybe Pocketmine.yml not being entirely read?

### ISSUE THREAD

**Issue by sirxon** [PocketMine/PocketMine-MP#3126]
The server starts by reading pocketmine.yml but a few lines later it points out I'm running a Beta and suggests I change preferred-channel even after I've done this.  Also, playing using 0.11.0 for more than an hour with normal difficulty and animal-spawn=45 but have had no animal or mob spawns.  I have restarted the server. No block events reported in firewall. Other problems also but seem more related to other posted issues.

**Comment by shoghicp** [comment]
There are no animals, and there are no beta builds for 1.5

**Comment by sirxon** [comment]
That makes sense. Actually, I'm running development 1.5 but the message I get says beta. I downloaded the dev so I could connect with 0.11.0.

BTW, thank you for all this really cool stuff! It's appreciated!
