### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [PocketMine/PocketMine-MP#3128]
If you come to the server with any of the tabernacle, and then change it , and reconnecting the players do not see a new skin

**Comment by shoghicp** [comment]
This is Pocket Edition fault

**Comment by TheEpicCooldeal** [comment]
If you mean that a user joined your server with a steve skin and then changed his skin you must delete his file in the "players" folder.

PS: This answer might be quite late and you may have figured it out already...
