### ISSUE TITLE
Calling Event with wrong Class

### ISSUE THREAD

**Issue by RaymanT** [PocketMine/PocketMine-MP#3130]
Calling my Function with the wrong class?

[CRITICAL] "Could not pass event 'pocketmine\event\entity\EntityDamageEvent' to 'myPlugin': Argument 1 passed to myListener::onDamage() must be an instance of pocketmine\event\entity\EntityDamageByEntityEvent, instance of pocketmine\event\entity\EntityDamageEvent given, called in D:\path\src\pocketmine\plugin\MethodEventExecutor.php on line 36

**Comment by shoghicp** [comment]
You must listen to EntityDamageEvent directly, then decide.

**Comment by PEMapModder** [comment]
Only event classes with a `public static $handlerList` static property directly declared by that class (instead of by parent classes) can be used as type hints for event handler functions.
