### ISSUE TITLE
[RakLib Thread #] kicking user for too many failed logon attempts

### ISSUE THREAD

**Issue by NML32** [PocketMine/PocketMine-MP#3132]
We are seeing this happen to many users on our servers.  We stay current with the Dev builds and are currently running build PocketMine-MP 1.5dev-1227.  We are also running SimpleAuth version SimpleAuth_v1.7.1 with auto kicked turned off for failed logon attempts.  Not sure if this error is related to SA or PM.

15:17:49 [INFO] MAISY[/xx.xxx.xxx.xx:62293] logged out due to Kicked by admin. Reason: Too many tries!
15:17:49 [NOTICE] [RakLib Thread #140203545052928] Blocked xx.xxx.xxx.xx for 600 seconds

Thanks,
Mark K.

**Comment by shoghicp** [comment]
This is not a PocketMine bug, check SimpleAuth documentation to see how to disable that configuration.
