### ISSUE TITLE
No recognition of biome colors on MCRegion worlds

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#3134]
Grass color is back on MCRegion maps ONLY on PocketMine 1.5dev build #1​22​7 with 0.11.1 client.

PS: Grass color working correctly on Anvil worlds.

**Comment by shoghicp** [comment]
Grass color gets generated if there is enough information available, if not, it can't be created.

**Comment by roroB20** [comment]
And for imported worlds what can we do ?

**Comment by shoghicp** [comment]
Before 1.2, biomes were generated by the client, no information was saved on disk :(

**Comment by roroB20** [comment]
So there is no way to fix it ? And how the client know where to place biome colors when the world is generated by pocketmine server ?!

**Comment by shoghicp** [comment]
On PC they did not know, they tried to generate them but on custom worlds everything was messed up.
On PocketMine worlds (or ported from Anvil) PM knows the biome that gets placed there.
