### ISSUE TITLE
Ban does not pay attention to capitol letters.

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PocketMine/PocketMine-MP#3135]
If my name is typewriter on my server, simpleauth and pocketmine allow TypeWriter to join and register at the same time as me, but if I do not want people to impersonate my account, I do /ban TypeWriter.

The problem is that if I ban TypeWriter, I cannot join as typewriter, If I pardon typewriter, then both TypeWriter and typewriter and all other variations can join.

Please fix this.

**Comment by shoghicp** [comment]
Names and players are case-insensitive on servers.

**Comment by AndreyNazarchuk** [comment]
Then why does it ban me also if I ban case variations of my name?

**Comment by shoghicp** [comment]
Because it's case-insensitive.
