### ISSUE TITLE
Eat much ram , invisible player, flying sign

### ISSUE THREAD

**Issue by icsmoke-mcpe** [PocketMine/PocketMine-MP#3137]
hello,

i got problem after i update my server to 0.11.0 with last PM-Soft

1. Invicible player , when player move and he invicible, but he suddenly vicible
2. flying sign, sign in other world, can i see on spawn world :-1: 
3. eat much ram! not like in 1.4 :( in 1.4 just 300-800 ram but in 1.5 2,1K ram :(

this problem in PM-Soft last update, i ran on ubuntu, 38 Plugins, 4 Active world and 1 useless world

thank youb:)

**Comment by shoghicp** [comment]
We don't support PM Soft here
