### ISSUE TITLE
Issue with spawn protection

### ISSUE THREAD

**Issue by themonsterkill** [PocketMine/PocketMine-MP#3140]
Im using The build 1232. Im having an issue with default spawn protection... Every one can destroy and place block... i use some plugins for remove this issue but keep don't working. Can someone help me? (Sorry for my english... im italian)

**Comment by iksaku** [comment]
If you use plugins then there's nothing we can do here, please directly contact the developer(s) of the plugin you use.

**Comment by themonsterkill** [comment]
You know the default spawn protection? radius from the spawn protected??? Only op can broke but idk why every one can destroy!!!!

**Comment by themonsterkill** [comment]
i run a vanilla server. No plugin... but exist a spawn protection editable in server proprieties!

**Comment by themonsterkill** [comment]
But don't work!

**Comment by iksaku** [comment]
Could you post your "server.properties" file somewhere like in "Pastebin" and provide the link?

**Comment by themonsterkill** [comment]
I dont touch it so is default

**Comment by iksaku** [comment]
Doesn't matter, please provide a copy of it, so we can define what part maybe wrong

**Comment by JoahDave** [comment]
Is the area you want protected your spawn? /setworldspawn

**Comment by shoghicp** [comment]
I'm not able to reproduce this

**Comment by iVertx** [comment]
Yeah, it`s randomly happening!
sometimes when my server restart, (because of memory leaks, cpu usage, annoying lag)
my spawn protection doesn`t work, and not only the default one, plugins that protect areas also stops working, maybe a API function related to protect blocks, wont load properly at startup?

**Comment by iVertx** [comment]
Yeah, its randomly happening! sometimes when my server restart, (because of memory leaks, cpu usage, annoying lag) my spawn protection doesnt work, and not only the default one, plugins that protect areas also stops working, maybe a API function related to protect blocks, wont load properly at startup?

**Comment by RandomAltThing** [comment]
In the plugin put In plugin.yml 

<code>
load: STARTUP
</code>

**Comment by RandomAltThing** [comment]
You can get the plugin source for the area protect by using **DevTools**. Place the plugin *.phar* in the plugins folder and load your server up. Next , (make sure Dev tools is also in plugins folder), type in console <code>makeplugin <Name of plugin></code>. Be careful it is case sensitive.

#The vanilla issues

Idk. Could you please provide a link to pocketmine.yml and server.properties even IF you haven't edited them.

**Comment by iVertx** [comment]
I figured that now every thing related to protect blocks from being grieffed by players isn`t working for me...
this happened before, but a reboot fixed that, now, i had to shutdown my network for try to solve this...

well, my hub server have a longer default spawn protection (10000 blocks for be exactly, yep, there is no need for that, but...) and i use iProtector for a extra security, but it also isn`t working... 

I removed the default pocketmine.yml and server.properties for test without lucky, downgraded pocketmine to build 19132 with no result, removed some plugins such pureperms and another plugins that maybe be related to it, nope... and finally removed the whole plugin folder and the issue still there.
thats soo strange, started to happens from nowere and i cant revert this o.o maybe there is a pocketmine bug... ill try to do a clean reinstall of pocketmine and test if this will happen again after some time.

**Comment by iVertx** [comment]
I figured that now every thing related to protect blocks from being grieffed by players isn`t working for me...
this happened before, but a reboot fixed that, now, i had to shutdown my network for try to solve this...

well, my hub server have a longer default spawn protection (10000 blocks for be exactly, yep, there is no need for that, but...) and i use iProtector for a extra security, but it also isn`t working...

I removed the default pocketmine.yml and server.properties for test without lucky, downgraded pocketmine to build 1223 with no result, removed some plugins such pureperms and another plugins that maybe be related to it, nope... and finally removed the whole plugin folder and the issue still there.
thats soo strange, started to happens from nowere and i cant revert this o.o maybe there is a pocketmine bug... ill try to do a clean reinstall of pocketmine and test if this will happen again after some time.

**Comment by PEMapModder** [comment]
@RandomAltThing this is not a help forum.

**Comment by iamstewpeed** [comment]
Lololo

**Comment by TahaTheHacker** [comment]
iamstewspeed!!! remember me?

**Comment by iamstewpeed** [comment]
yes
