### ISSUE TITLE
[Enhancement] Block certain player names

### ISSUE THREAD

**Issue by RandomAltThing** [PocketMine/PocketMine-MP#3141]
If I can find the code for getting player names, I may do this myself.

Ever wanted to block certain names like "Penis" etc? Annoyed with that one guy called "Steve"? Well you should implement a way to ban certain player names. This could be in an <code>AllowedNames.json</code> or something along the lines of that. This would make it easier rather than having to download, or even code, a plugin to do this.

**Comment by shoghicp** [comment]
Ship your own banlist.txt
Or just do /ban name

**Comment by PEMapModder** [comment]
Also, please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. You **cannot** add custom tags in the title, because the collaborators of this repository will add the tags themselves.
