### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by CandVtyler** [PocketMine/PocketMine-MP#3142]
I just got pocket mine today, and of course added some plugins to make it better. When I tried starting the server, the server immediatly shuts down. I tried deleting plugins, changing the port, but it doesnt work.
Log:
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 20:02:39 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 20:02:39 [INFO] Loading pocketmine-soft.yml...
[Server] 20:02:39 [INFO] Loading pocketmine.yml...
[Server] 20:02:39 [INFO] Loading server properties...
[Server] 20:02:39 [INFO] Selected English (eng) as the base language
[Server] 20:02:39 [INFO] Starting Minecraft: PE server version v0.11.0 alpha
[Server] 20:02:39 [NOTICE] The memory-limit setting has been deprecated.
[Server] 20:02:39 [NOTICE] There are new memory settings on pocketmine.yml to tune memory and events.
[Server] 20:02:39 [NOTICE] You can also reduce the amount of threads and chunks loaded control the memory usage.
[Server] 20:02:39 [INFO] Opening server on 0.0.0.0:19131
[Server] 20:02:39 [INFO] This server is running PocketMine-Soft version 1.5dev-245 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
[Server] 20:02:39 [INFO] PocketMine-Soft is distributed under the LGPL License
[Server] 20:02:42 [INFO] Loading SimpleAuth v1.7.1
[Server] 20:02:42 [INFO] Loading PocketDockConsole v0.0.12
[Server] 20:02:42 [INFO] [PDC] Loaded
[Server] 20:02:42 [INFO] Loading SignShop v1.0.0
[Server] 20:02:42 [INFO] Loading SimpleWarp v1.4
[Server] 20:02:42 [INFO] Loading PocketGuard v2.1.1
[Server] 20:02:42 [INFO] Loading AdminJoin v1.3.0
[Server] 20:02:42 [INFO] Loading ServerKits v1.3
[Server] 20:02:42 [INFO] Loading PeacefulSpawn v2.4
[Server] 20:02:42 [INFO] Loading DevTools v1.10.0
[Server] 20:02:42 [INFO] Loading BanHammer v1.8.5
[Server] 20:02:42 [INFO] Loading ColorText v1.3.0
[Server] 20:02:42 [INFO] Loading SimpleGamemode v1.0
[Server] 20:02:42 [INFO] Loading EnderPearl v1.2.1
[Server] 20:02:42 [INFO] Loading BulkCommands v1.0-build#007
[Server] 20:02:42 [INFO] Loading KeepInventory v1.2.0
[Server] 20:02:42 [INFO] Loading MassiveEconomy v1.0 R3
[Server] 20:02:42 [INFO] Loading MassiveEconomyExample v1
[Server] 20:02:47 [INFO] Enabling SimpleAuth v1.7.1
[Server] 20:02:48 [INFO] [SimpleAuth] Everything loaded!
[Server] 20:02:48 [INFO] Enabling ServerKits v1.3
[Server] 20:02:48 [INFO] [ServerKits] Economy support enabled!
[Server] 20:02:48 [INFO] Enabling DevTools v1.10.0
[Server] 20:02:48 [INFO] [DevTools] Registered folder plugin loader
[Server] 20:02:48 [INFO] Enabling MassiveEconomy v1.0 R3
[Server] 20:02:48 [INFO] Enabling MassiveEconomyExample v1
[Server] 20:02:48 [INFO] [MassiveEconomyExample] Example Plugin using MassiveEconomy (API v0.90)
[Server] 20:02:48 [INFO] Preparing level "world"
[Server] 20:02:48 [INFO] Enabling PocketDockConsole v0.0.12
[Server] 20:02:48 [INFO] [PDC] Enabled
[Server] 20:02:48 [INFO] [PDC] Started SocksServer on 0.0.0.0:9090
[Server] 20:02:48 [INFO] Enabling SignShop v1.0.0
[Server] 20:02:48 [INFO] Enabling SimpleWarp v1.4
[Server] array(0) {
[Server] }
[Server] 20:02:48 [INFO] Enabling PocketGuard v2.1.1
[Server] 20:02:48 [INFO] Enabling AdminJoin v1.3.0
[Server] 20:02:48 [INFO] Enabling PeacefulSpawn v2.4
[Server] 20:02:48 [INFO] Enabling BanHammer v1.8.5
[Server] 20:02:49 [INFO] [BanHammer] BanHammer Loaded!
[Server] 20:02:49 [INFO] Enabling ColorText v1.3.0
[Server] 20:02:49 [INFO] Enabling SimpleGamemode v1.0
[Server] 20:02:49 [INFO] [SimpleGamemode] Loading SimpleGamemode v1.0 by MamayAdesu!
[Server] 20:02:49 [INFO] Enabling EnderPearl v1.2.1
[Server] 20:02:49 [INFO] [EnderPearl] EnderPerl loaded!
[Server] 20:02:49 [INFO] Enabling BulkCommands v1.0-build#007
[Server] 20:02:49 [INFO] Enabling KeepInventory v1.2.0
[Server] 20:02:49 [INFO] KeepInventory by boybook.
[Server] 
[Server] Warning: stream_socket_server(): unable to connect to tcp://0.0.0.0:9090 (Address in use) in phar:///mnt/sdcard/PocketMine/plugins/plugin-698.phar/src/Wrench/Socket/ServerSocket.php on line 63
[Server] 20:02:51 [INFO] Starting GS4 status listener
[Server] 20:02:51 [INFO] Setting query port to 19131
[Server] 20:02:51 [INFO] Query running on 0.0.0.0:19131
[Server] 20:02:51 [INFO] Default game type: Creative Mode
[Server] 20:02:51 [INFO] Done (17.647s)! For help, type "help" or "?"
[Server] 
[Server] Fatal error: Call to undefined method pocketmine\Server::getMemoryUsage() in phar:///mnt/sdcard/PocketMine/plugins/plugin-698.phar/src/PocketDockConsole/RunCommand.php on line 171
[Server] 20:02:52 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 20:02:52 [EMERGENCY] Please upload the "/mnt/sdcard/PocketMine/CrashDump_Mon_Jun_8-20.02.52-UTC_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
>?
[Server] 20:02:57 [INFO] Disabling SimpleAuth v1.7.1
[Server] 20:02:57 [INFO] Disabling PocketDockConsole v0.0.12
[Server] 20:02:57 [INFO] [PDC] Disabled
[Server] 20:02:57 [INFO] Disabling SignShop v1.0.0
[Server] 20:02:57 [INFO] Disabling SimpleWarp v1.4
[Server] 20:02:57 [INFO] Disabling PocketGuard v2.1.1
[Server] 20:02:57 [INFO] Disabling AdminJoin v1.3.0
[Server] 20:02:57 [INFO] Disabling ServerKits v1.3
[Server] 20:02:57 [INFO] Disabling PeacefulSpawn v2.4
[Server] 20:02:57 [INFO] Disabling DevTools v1.10.0
[Server] 20:02:57 [INFO] Disabling BanHammer v1.8.5
[Server] 20:02:57 [INFO] [BanHammer] BanHammer Unloaded!
[Server] 20:02:57 [INFO] Disabling ColorText v1.3.0
[Server] 20:02:57 [INFO] Disabling SimpleGamemode v1.0
[Server] 20:02:57 [INFO] [SimpleGamemode] Disabling SimpleGamemode v1.0 by MamayAdesu...
[Server] 20:02:57 [INFO] Disabling EnderPearl v1.2.1
[Server] 20:02:57 [INFO] [EnderPearl] EnderPearl unloaded!
[Server] 20:02:57 [INFO] Disabling BulkCommands v1.0-build#007
[Server] 20:02:57 [INFO] Disabling KeepInventory v1.2.0
[Server] 20:02:57 [INFO] Disabling MassiveEconomy v1.0 R3
[Server] 20:02:57 [INFO] Disabling MassiveEconomyExample v1
[Server] 20:02:57 [INFO] Unloading level "world"

**Comment by themonsterkill** [comment]
i think one of the plugin have uncorrect usage of the memory... In plugin folder you have /sdcard/PocketMine/plugins/plugin-698.phar/src/PocketDockConsole/RunCommand.php and say the error is on this at line 171

**Comment by iksaku** [comment]
This issue is realted to a plugin, nothing to do with PocketMine.

Please close this issue and contact the plugin developer.

**Comment by shoghicp** [comment]
You are using an outdated version of PocketMine
