### ISSUE TITLE
Player can fly after disabling the feature

### ISSUE THREAD

**Issue by iksaku** [PocketMine/PocketMine-MP#3143]
You can allow players to fly using the ``$player->setAllowFlight()`` function, but the problem comes when the player is already flying.

The player will fall to the ground without receiving any amage (That is OK), but then the "Fly controls" in the client will remain, allowing the player to fly line-straight, but doesn't allow to move up and down, neither leaving the "Fly mode" nor "Jump"... Just levitate.

**Comment by LDX-MCPE** [comment]
This is a client-side issue. I discovered it while experimenting with Ghost Hack.

**Comment by iksaku** [comment]
Just wanted to be sure :P I believe @shoghicp can report and fix it anyways xD

**Comment by shoghicp** [comment]
It's a client-side issue. If allow-flight is disabled, they player will be pushed to the ground automatically
