### ISSUE TITLE
[Linux Install] No public key

### ISSUE THREAD

**Issue by Rondoozle** [PocketMine/PocketMine-MP#3144]
wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 10:00:47 MST 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Tue Mar 17 10:16:17 2015 MST using RSA key ID A7837F89
gpg: requesting key A7837F89 from hkp server pgp.mit.edu
gpg: unable to execute program `/usr/libexec/gpg2keys_curl': No such file or directory
gpg: no handler for keyserver scheme `hkp'
gpg: Can't check signature: No public key
[!] Invalid signature! Please check for file corruption or a wrongly imported public key (signed by 20D377AFC3F7535B3261AA4DCF48E7E52280B75B)

**Comment by shoghicp** [comment]
Could you provide further details on the installer repository?
