### ISSUE TITLE
Cannot connect even the port is open

### ISSUE THREAD

**Issue by cameloper** [PocketMine/PocketMine-MP#3147]
Hi, i want to set up a pocketmine server on my pc to play with family&friends. I installed necessary files and started server but we were unable to connect. First i thought the port is closed but according to test results it's open.  Can you help please.

**Comment by shoghicp** [comment]
Check that the version of PocketMine and MCPE match, as this is the current issue users are having.

**Comment by cameloper** [comment]
Which version should i use to play with MCPE 0.10.4
