### ISSUE TITLE
Big lag when breaking blocks !

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#3150]
On last PocketMine 1.5 build and MCPE 0.11.1 when connecting and when the player is breaking a block there is often a big lag / freeze during few seconds before the client responding :/ !
PS: happens when a chunk is recently loaded I think...

**Comment by shoghicp** [comment]
This is a client-side issue.

**Comment by roroB20** [comment]
So it will be fixed in next MCPE 0.11.2 update ??
