### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Lotteries** [PocketMine/PocketMine-MP#3153]
I'm running a PocketMine server on the latest dev build (#1238) and i've noticed with one single player online the server drops down to around 2-3 TPS. Which i think is kinda strange. Here is the hardware i'm currently running the server on..

Server (Dedicated) Hardware:
- 16GB (Total dedicated server has 16GB, 1GB on the PE Server)
- Intel i7 CPU (8 Cores)
- 1GB/s Port (This obviously does not matter)
- 6 Threads (According to the PocketMine-MP Console)

I don't know if i'm doing something wrong or if its a memory leak. Sorry if this is a invalid issue on the tracker, but i'm new to pocketmine and i want to fix this issue or at least report it! Thanks :)

**Comment by shoghicp** [comment]
Can you drop some timings?
Also, have you checked your settings to see if the memory limit has been hit? You might want to increase that when having extra threads, garbage collection can eat up the tps when not configured

**Comment by Lotteries** [comment]
Let me grab some timings @shoghicp

**Comment by Lotteries** [comment]
@shoghicp I've managed to catch the nasty lag in the act, here is some timings (7secs worth of them, yes i know its short but i think i know which two are lagging it) http://timings.aikar.co/?url=11684363 Seems to be that SimpleAuth (You'res :P) And PurePerms are lagging it.. Well, two of my essential plugins! :(

EDIT: Only happens on player join events..

**Comment by shoghicp** [comment]
They read from disk and set permissions on Join, and permission calculation is slow. But that is a single-tick issue, not something that continues

**Comment by Lotteries** [comment]
Ah, well the problem is what do i do when i have 10+ people joining every 10-20 seconds? It usually pegs my server and makes it bow down to its knees.

**Comment by shoghicp** [comment]
People joining is one of the things that lag the most.

Could you also try to enable debug commands and run /gc? That might free some things after a lot of people join (the command takes a bit of time)

**Comment by Lotteries** [comment]
I'll try that when i get home! :)

**Comment by Striker209** [comment]
This issue interests me because I think it occurs for me aswell...
