### ISSUE TITLE
Aliases not working e.g. savestop

### ISSUE THREAD

**Issue by markkrueg** [PocketMine/PocketMine-MP#3154]
At some point between build 1232 and 1238 aliases stop working. So on clean test server v1238 if I uncomment:

pocketmine.yml

aliases:
 #Examples:
 #showtheversion: version
 savestop: [save-all, stop]

When I enter savestop at console I get:

[22:03:28] [Server thread/INFO]: Unknown command. Try /help for a list of commands

**Comment by shoghicp** [comment]
Did you remember to add the proper indentation (spaces) on the YAML file?

**Comment by markkrueg** [comment]
It is currently indented with a single space. Here is the exact steps to reproduce. In empty directory (Mac):

1) curl -sL http://get.pocketmine.net/ | bash -s - -v development
2) ./start.sh
3) choose defaults (hit return for (en), y to accept, y to skip setup)
4) stop to stop PocketMineMP
5) vi pocketmine.yml
6) delete a single character (#) from line 166 and save file (leaving line indented with 1 space)
7) ./start.sh
8) savestop
9) Unknown command. Try /help for a list of commands

**Comment by alejandroliu** [comment]
Actually for me the properties do not seem to be working.  All my settings in pocketmine.yml seem to be ignored.

**Comment by shoghicp** [comment]
@alejandroliu Yes, and that confused me as well :S

**Comment by PEMapModder** [comment]
@alejandroliu :+1:

**Comment by Striker209** [comment]
:+1:
