### ISSUE TITLE
Stone Bricks immediately disappear after being crafted

### ISSUE THREAD

**Issue by markkrueg** [PocketMine/PocketMine-MP#3160]
When Stone Bricks are crafted they appear in the hot-bar for a moment and then disappear; returning materials to you.

Using clean build of PocketMine-MP 1.5dev-1240 running on Mac. No Plugins.

Steps to reproduce in empty directory:
1) curl -sL http://get.pocketmine.net/ | bash -s - -v development
2) ./start.sh
3) choose defaults (hit return for (en), y to accept, y to skip setup)
4) Open MCPE 0.11.1 iOS 8.3 and connect to new server
5) Console: give steve 5 4
6) Craft crafting table and place
7) Console: give steve 4 4
8) Craft Cutting Table using Crafting Table and place
9) Console: give steve 1 4
10) Craft 4 x Stone Bricks using Cutting table
11) 4 Stone Bricks appear it hotbar and then immediately disappear; returning materials to you

I have also tried this without using any console commands, and have identical results.

I tried again after setting debug level to 5 and saw this in console:

[Server thread/DEBUG]: Unmatched recipe from player Steve: Item Stone Bricks (98:0)x4, using: Item Unknown Stone (1:?)x1, Item Unknown Stone (1:?)x1, Item Unknown Stone (1:?)x1, Item Unknown Stone (1:?)x1

**Comment by markkrueg** [comment]
I apologize in advance for not doing this as a proper pull request, but I'm very new to all this PHP and Github, and I ran into some difficulties. For some reason there are weird backslashes all over my local repository. 

Anyway, I was able to modify 4 lines of code and do a build of PocketMine-MP that fixes crafting of Stone Brick Stairs, Stone Bricks, Stone Brick Slabs and also Chiseled Stone Bricks.

I totally understand if this gets ignored until I can figure out github; but I would feel guilty if I didn't try to share the changes.

src/pocketmine/inventory/CraftingManager.php
Lines 161 through 163

Original

```
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::STONE_BRICK_STAIRS, 0, 4)))->addIngredient(Item::get(Item::STONE_BRICK, 0, 6)));
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::STONE_BRICK, 0, 4)))->addIngredient(Item::get(Item::STONE, 0, 4)));
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::SLAB, 5, 6)))->addIngredient(Item::get(Item::STONE_BRICK, 0, 3)));
```

Updated Code

```
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::STONE_BRICK_STAIRS, 0, 4)))->addIngredient(Item::get(Item::STONE_BRICK, null, 6)));
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::STONE_BRICK, 0, 4)))->addIngredient(Item::get(Item::STONE, null, 4)));
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::STONE_BRICK, 3, 1)))->addIngredient(Item::get(Item::SLAB, 5, 2)));
		$this->registerRecipe((new StonecutterShapelessRecipe(Item::get(Item::SLAB, 5, 6)))->addIngredient(Item::get(Item::STONE_BRICK, null, 3)));[/code]
```

**Comment by shoghicp** [comment]
Thanks for reporting this!
I've extended your pull request with some extra blocks that were missing as well, like mossy stone bricks and cracked stone bricks.

**Comment by markkrueg** [comment]
> Thanks for reporting this!

Thanks for letting me be a small part of this amazing project! That's great that you added those other blocks as well.

I hope to submit more in the future as I learn PHP and GitHub. If I could only figure out where these mystery backslashes and \nulls are coming from in the code i get out of extracted PocketMine-MP and plugin phar files. I must be doing something wrong somewhere.

**Comment by shoghicp** [comment]
@markkrueg Just clone the repository, those things get added as a build step over jenkins.pocketmine.net
It inlines several used methods and/or creates different files per platform integer size for improveed performance.

**Comment by markkrueg** [comment]
Ah THANK YOU; that makes perfect sense -- and is very cool. I was so baffled by those. I will clone from now on.
