### ISSUE TITLE
Server Crash upon Receiving Achievement 

### ISSUE THREAD

**Issue by peepzandmeepz** [PocketMine/PocketMine-MP#3163]
13.06 17:41:14 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
13.06 17:41:14 [Server] INFO Fatal error: Namespace declaration statement has to be the very first statement in the script in phar:///PocketMine-MP.phar/src/pocketmine/event/player/PlayerAchievementAwardedEvent.php on line 22

On the most recent build 1243 :)

**Comment by shoghicp** [comment]
Nothing got changed, and I can't reproduce this on my local server.

Try downloading a new build.
