### ISSUE TITLE
Possible issue on Windows builds with autoloaded classes consuming heavy memory.

### ISSUE THREAD

**Issue by china-richway2** [PocketMine/PocketMine-MP#3166]
I've just wrote a plugin that loads all PHP files in the PocketMine.phar.
The result is that many files (for example, pocketmine\entity\Chicken) has some errors (abstract method undeclared). They are unused in the PocketMine project.
It failed because PHP reached the 512M memory limit very quickly. I think we should prune some useless files from the PocketMine.phar or many servers will stop some time due to high memory usage.

**Comment by shoghicp** [comment]
That is not the problem of the memory usage. Those files are not loaded (they are stubs) except when a plugin uses them (and that's the problem).

All of the PM code compiled to opcodes is around 1.6MB on my 64-bit system, and that's what resides in memory.

Not using autoloader would mean having an include for every file needed, which would negate the use of our existing namespace and use statement usage AND not reduce memory usage (the same files would be included!)

I don't see the point of this issue, nor any benefits from it (only disadvantages!) so I'm closing it.

**Comment by china-richway2** [comment]
Well, on my computer a single PHP file compiles around 3-4MB on my computer. The Windows Task Manager says that PHP is using 91708K of memory at first, and when 189 classes were loaded, PHP says 'segmentation fault' which is probably due to memory limit exceeded. That's 432580K for 189 classes, and each class takes around 2288K of memory. I don't know why 'All of the PM code compiled to opcodes is around 1.6MB on my 64-bit system.'.
The point of the issue is that relying too much on autoloader can cause unknown issues which WILL happen at some time. This should be the exact cause when server owners find their servers 'leaking memory' and 'memory usage does not reduce even when no player is online'. Although autoloader optimizes the speed, we should make sure that our server works without an autoloader.

**Comment by shoghicp** [comment]
Auto loader only allows to load classes when they are needed, instead of all at the same time. Try running on Linux.
Also, it seems like you are using the Windows 64-bit version, which is broken.

**Comment by china-richway2** [comment]
I tested it on both Windows 64-bit and Windows 32-bit VM. Both of them exceeds the memory limit quickly.
Auto loader does not unload classes, so eventually all classes that may possibly be used will be loaded.

**Comment by sekjun9878** [comment]
Hello @china-richway2, the autoloader model is a very widely used concept in the PHP community and has been proven to be reliable. It is a limitation of PHP that classes are not unloadable, and not using an autoloader won't fix that problem.

Sounds like you have a problem with your Windows build, or with your own plugin. 

*What you need to do:*

Could you please post me the build number / commit hash of the PocketMine version you are using, and the **full code** of the plugin you are using to perform this test and I'll debug this issue on Windows 8 x64 for you, and see if this really is an issue.

**Comment by sekjun9878** [comment]
After further review, it's not PocketMine's problem. It's simply that you're trying to load an invalid class file and you're mistaking it for a memory full error. the `segmentation fault` error message is used for all PHP runtime errors, not just memory full errors.

Those files you're trying to include are not meant to be included, and they are Work In Progress. Don't try to load all files next time :)

**Comment by china-richway2** [comment]
@sekjun9878
Yeah it does not have to be a memory full error, but it is true that it takes a lot of memory while loading :)
Here is the code: (Sorry I'm too lazy to put it into a new Git repo):
/src/Bugfix/Bugfix.php
```php
	namespace Bugfix;

	use pocketmine\plugin\PluginBase;
	use pocketmine\event\Listener;

	class Bugfix extends PluginBase implements Listener{
		public function onEnable(){
			$this->getServer()->getScheduler()->scheduleAsyncTask(new AsyncLoader($this));
		}
	}
```

/src/Buggix/AsyncLoader.php
```php
	namespace Bugfix;

	class AsyncLoader extends \pocketmine\scheduler\AsyncTask{
		private $owner;
		public function __construct($owner){
			$this->owner = $owner;
		}
		public function onRun(){
			$filePath = str_replace("\\", "/", \pocketmine\PATH);
			$classes = [];
			$this->owner->getServer()->getLogger()->info("Finding");
			foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($filePath)) as $file){
				$path = ltrim(str_replace(["\\", $filePath], ["/", ""], $file), "/");
				if($path{0} === "." or strpos($path, "/.") !== false){
					continue;
				}
				if(substr($path, 0, 4) === "src/" and substr($path, strlen($path) - 4, 4) === ".php"){
					$classname = substr(str_replace("/", "\\", $path), 4, strlen($path) - 8);
					if(substr($classname, strlen($classname) - 7, 7) !== "__32bit" and substr($classname, strlen($classname) - 7, 7) !== "__64bit")
						if(!class_exists($classname, false)){
							$classes[$classname] = $file;
						}
				}
			}
			$this->owner->getServer()->getLogger()->info("Loading");
			$loaded = 0;
			foreach($classes as $classname => $file){
				//$this->owner->getServer()->getLogger()->info("[$loaded] Loading " . $classname . " from $file: testing");
				if(!class_exists($classname, false)){
					$loaded++;
					$this->owner->getServer()->getLogger()->info("[$loaded] Loading " . $classname . " from $file");
					//require_once($file);
					class_exists($classname, true);
				}
			}
		}
	}
```
And delete any PHP files that makes an error. The memory usage increased very quickly on my VM and my host machine..

**Comment by shoghicp** [comment]
@china-richway2 You should not handle the .phar as an archive of only PHP files, it can include extra data, resources, and duplicate files. For example, PHP files are triplicated with different conversions for platform dependent code, so loading all of them will fail.

What is happening here is that the thread is crashing AND creates a new one, which leaks a lot of memory.

Try doing this on the main thread instead of having an async task to see your problem.

**Comment by china-richway2** [comment]
Yeah I excluded all non-PHP files.
```php
                if(substr($path, 0, 4) === "src/" and substr($path, strlen($path) - 4, 4) === ".php"){
                    $classname = substr(str_replace("/", "\\", $path), 4, strlen($path) - 8);
                    if(substr($classname, strlen($classname) - 7, 7) !== "__32bit" and substr($classname, strlen($classname) - 7, 7) !== "__64bit")
                        if(!class_exists($classname, false)){
                            $classes[$classname] = $file;
                        }
                }
```
I tried to run it on the main thread but PHP died even faster (after loading 35 classes). I tried deleting the last class it loaded, but it will only load 35 classes, not one single more. The AsyncLoader one loaded 190 classes, but not one single more. The main thread one died so fast that I cannot see the memory usage. If the plugin crashed it should either rerun or stop and give warnings, but it run normally.
