### ISSUE TITLE
Locating Server

### ISSUE THREAD

**Issue by halcyonforever** [PocketMine/PocketMine-MP#3168]
Brand new install:
Windows server
1.4.1-980

Android client v0.11.1 alpha

Ports are opened

When the client tries to connect it sits at locating server.  On the server, the user count increases, but the only message is if the client hits cancel it shows ""21:48:51 [INFO] IPADDRESS:52401] logged out due to client disconnect"

**Comment by Addison118** [comment]
Are you running Pocketmine 1.5 Dev 1244?

**Comment by halcyonforever** [comment]
no, I tried downloading the master git but it didn't seem to change anything, let me find that one

**Comment by halcyonforever** [comment]
dev version installed, testing now

**Comment by halcyonforever** [comment]
that fixed it!

**Comment by Addison118** [comment]
1.4.1 won't work with mcpe 0.11.1, this issue should be closed now
