### ISSUE TITLE
Login Timeout

### ISSUE THREAD

**Issue by Rondoozle** [PocketMine/PocketMine-MP#3170]
When a client tries to login into server, client connects, but before world loads it redirects to screen that says "Login Timeout". These clients are on different networks. Also, I am receiving a similar message via admin console:"Server thread/INFO]: [/**.***.**.***:*****] logged out due to Login timeout." I am running PocketMine-MP version 1.5dev-1244  on an Ubuntu 14.04 VPS.

**Comment by peepzandmeepz** [comment]
I have had this issue before, however it was caused by plugin and not PocketMine.

**Comment by Rondoozle** [comment]
I have no plugins installed.

**Comment by Rondoozle** [comment]
I apologize. I may have had a plugin installed that never worked. I did a fresh install and it works fine!. Thanks!

**Comment by cwmahan** [comment]
I have this same issue with a completely fresh install

**Comment by arynes** [comment]
same here, latest iOS client but get a logoff due to login timeout every time
