### ISSUE TITLE
Unkillable Mobs

### ISSUE THREAD

**Issue by Thunder33345** [PocketMine/PocketMine-MP#3171]
after spawning mobs they can't be killed(they can be hit at first few time)(immortal) (only will if you use a strength effect at first hit or it will stay there forever)
reproduce this:
spawn mob using egg
tested on villager
affect:
most spawn egg

**Comment by Creeperface01** [comment]
it happens because mob still stay on the same place only client see it on the another place so you hitting into air. Try to move mob back :D.
It is because pocketmine has not mob AI

**Comment by Thunder33345** [comment]
hitting air well i sure i did wasted some time
so it is a unsync of mob location

**Comment by thebigsmileXD** [comment]
grabbag helped me with that.. i had zombies and villagers standing around.
with /et you can see the id's and remove them

**Comment by Thunder33345** [comment]
@thebigsmileXD actually i will refer a plugin less solution
actually relog then use lava / strength to kill it helps
