### ISSUE TITLE
Invalid Local IP on Linux

### ISSUE THREAD

**Issue by SopaXorzTaker** [PocketMine/PocketMine-MP#3177]
When starting PocketMine, it determines the local IP as 127.0.0.1 instead of an actual one.

Tested on: Ubuntu 14.04 ARMv7 on ODROID-XU with latest dev version.

**Comment by shoghicp** [comment]
The local ip is not used for anything except some non-critical info in the install wizard

**Comment by PEMapModder** [comment]
It is part of the API.
