### ISSUE TITLE
Custom worlds having issues loading

### ISSUE THREAD

**Issue by tiNsLeY799** [PocketMine/PocketMine-MP#3178]
I've used ljyloo's LevelDb2Avnil converter to convert my worlds so i could play them with Pocketmine-MP. The conversion is successful, but the custom worlds have issues loading/generating the chunks and upon joining the server, the land is empty until loaded after two(?) minutes and does this with each player who logs int the server. This only occurs with preloaded (I dont know if thats the right term to describe it?) and wont do it unless the server generates the worlds

(EDIT) Load error is shown by the process/loading bar(?) upon joining the server as worlds generated by Pocketmine load properly vs custom worlds.

**Comment by shoghicp** [comment]
Anvil worlds are really slow due to real time conversion, use LevelDB worlds or McRegion
