### ISSUE TITLE
Grass black in MCRegion

### ISSUE THREAD

**Issue by tiNsLeY799** [PocketMine/PocketMine-MP#3180]
Anvil is no problem anymore. Now I have this lovely error. I'm not quite sure what causes it
![screenshot_2015-06-16-15-37-55](https://cloud.githubusercontent.com/assets/12755193/8196193/fb852f80-143d-11e5-9f3e-8aed48dc920f.png)

**Comment by shoghicp** [comment]
PC McRegion worlds have no information on their biome saved on disk, so you can't regenerate the grass color

**Comment by vvzar** [comment]
Will converting to Anvil help?

**Comment by vvzar** [comment]
worlds are corrupted by earlier version of pm, still not fixed. How can I fix it manually?
When I load empty map on newest builds all looks normal (grass blocks are green) but when I load corrupted - all blocks are black.
