### ISSUE TITLE
About Pocketmine-MP server optimization

### ISSUE THREAD

**Issue by nishuo** [PocketMine/PocketMine-MP#3181]
TPS server always 10%% load number about 50 people of Intel (R) (R) X5650 Xeon CPU @ 10m 4G 2.67GHz 4 * want to asked how to optimize the server can let more players at the same time for the game smooth my English is very poor!

**Comment by PEMapModder** [comment]
This is not a place to ask questions. Please read the [contribution guidelines] (../CONTRIBUTING.md) before creating an issue.

**Comment by nishuo** [comment]
Thanks..I don't know what to do about how to optimize who can help me
