### ISSUE TITLE
Emergency error #3172

### ISSUE THREAD

**Issue by bobbutt101** [PocketMine/PocketMine-MP#3188]
It happened again all the detail are on my last reporting on called Emergency error #3172 please fix it this time

**Comment by iksaku** [comment]
Don't spam issues, if your issue was clsed is because it's ``Invalid`` and the problem may be only on your side, due to bad server configuration or something else like a plugin you have

**Comment by sekjun9878** [comment]
In #3172, you posted the crash dump filename, without any of the contents in it... We can't really help you if you don't post the crash log. Also, please refer to our forums to confirm that this is a bug and not a misconfiguration on your phone(?) before making a bug report.
