### ISSUE TITLE
Screwy World Genration

### ISSUE THREAD

**Issue by camquarter2015** [PocketMine/PocketMine-MP#3191]
I tried using your most recent development build for PocketMine 1.5 and most of it works fine but there's something weird with all the worlds I've tried to use. The grass isn't green like it should be and it appears to be black. The dirt itself still looks brown but the grass on top is black. A lot of other plants are the same way. I'm still able to break them and collect them but this black thing is annoying. It might just be my world but it happens to any world I have tried.

**Comment by shoghicp** [comment]
Please don't open duplicated invalid issues

**Comment by tiNsLeY799** [comment]
@camquarter2015  This is caused by mcregion worlds simply because the disk cannot "understand" just what biome it is. However anvil worlds don't do this but its extremely slow and takes forever to load
