### ISSUE TITLE
Seems like there is a memory leak...

### ISSUE THREAD

**Issue by Striker209** [PocketMine/PocketMine-MP#3192]
Hi PocketMine Team,
I'm hosting two PocketMine Instances on a same machine under Ubuntu 14.04 and sometimes one of them crashes with the only line:

./start.sh: line 56: 26953 Killed                  "$PHP_BINARY" "$POCKETMINE_FILE" $@

I just realized my issue was valid and I'm gonna give you more informations on how to reproduce:

Machine:

 -   Ubuntu 14.04
 -   1024M RAM
 -   2x 2,5GHz Cores

The TWO instance of PocketMine running on that machine:

 -   Runned in two different screens (I mean the package named "screen")
 -   Using the latest build
 -   About four maps loaded at the same time (so a total of 8 maps on the machine)
 -   About 50/70 players online (so a total of 100/140 on the machine)

So I start the two servers, everything is loaded but every time a player connects or just by waiting a bit, I see that the percentage of the used RAM of the machine is increased by 2% or 1%, and then... until it reaches 100%, which makes the server nº2 crash. As I activated the DO_LOOPS in start.sh file, the server restarts and this issue reproduces infinitly

Also, I noticed that if use PocketMine-Soft, there is no more stops but PocketMine-Soft is too old and gets the bug with Invisible Players...

If you are interested, it would be a pleasure to give you more informations about this issue that annoy me a lot for my production servers...

Thanks for reading

**Comment by Striker209** [comment]
I just realized my issue was valid and I'm gonna give you more informations on how to reproduce:

Machine:
- Ubuntu 14.04
- 1024M RAM
- 2x 2,5GHz Cores

The TWO instance of PocketMine running on that machine:
- Runned in two different screens (I mean the package named "screen")
- Using the latest build
- About four maps loaded at the same time (so a total of 8 maps on the machine)
- About 50/70 players online (so a total of 100/140 on the machine)

So I start the two servers, everything is loaded but every time a player connects or just by waiting, I see that the percentage of the used RAM of the machine is increased by 2%, and then... until it reaches 100%, which makes the server nº2 crash. As I activated the DO_LOOPS in start.sh file, the server restarts and this issue reproducts infinitly

If you are interested, it would be a pleasure to give you more informations about this issue that annoy me a lot for my production servers...

Thanks for reading

**Comment by Striker209** [comment]
I just realized my issue was valid and I'm gonna give you more informations on how to reproduce:

Machine:
- Ubuntu 14.04
- 1024M RAM
- 2x 2,5GHz Cores

The TWO instance of PocketMine running on that machine:
- Runned in two different screens (I mean the package named "screen")
- Using the latest build
- About four maps loaded at the same time (so a total of 8 maps on the machine)
- About 50/70 players online (so a total of 100/140 on the machine)

So I start the two servers, everything is loaded but every time a player connects or just by waiting a bit, I see that the percentage of the used RAM of the machine is increased by 2% or 1%, and then... until it reaches 100%, which makes the server nº2 crash. As I activated the DO_LOOPS in start.sh file, the server restarts and this issue reproduces infinitly

If you are interested, it would be a pleasure to give you more informations about this issue that annoy me a lot for my production servers...

Thanks for reading

**Comment by Striker209** [comment]
Also, if I run a single server on this machine, there is also that memory leak and it stops the server...

**Comment by Guillaume351** [comment]
It's just not enough memory I think :/

**Comment by shoghicp** [comment]
You seem like you are not using the latest builds provided.
Also, remember to set the soft limits on pocketmine.yml to something below the RAM you want to use, otherwise it won't free resources when needed.

**Comment by Striker209** [comment]
Hi again shogi,
I updated to the very last version of PocketMine-MP (which change anything) and I thightened again memory params:
memory:
 #Global soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 global-limit: 256

 #Main thread soft memory limit in megabytes. Set to 0 to disable
 #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
 main-limit: 128

 #Period in ticks to check memory (default 1 second)
 check-rate: 20

 #Continue firing low-memory-triggers and event while on low memory
 continuous-trigger: true

 #Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
 continuous-trigger-rate: 30

 garbage-collection:
  #Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
  #This only affect the main thread. Other threads should fire their own collections
  period: 36000

  #Fire asynchronous tasks to collect garbage from workers
  collect-async-worker: true

  #Trigger on low memory
  low-memory-trigger: true




The problem still happens:
"php" tasks take more and more memory and server stops

**Comment by shoghicp** [comment]
Are you sure you want to lower the limit to that ridiculous small value with a lot of players and worlds?

This will only cause issues as it'll try to force-clean memory in a lot of places and cause extra lag.
Misconfiguration of the server is not a valid reason to open an issue.
