### ISSUE TITLE
Could not load level "world": IO error

### ISSUE THREAD

**Issue by Striker209** [PocketMine/PocketMine-MP#3193]
[Server thread/ERROR]: Could not load level "world": IO error: lock /root/servers/rusharena/worlds/world//db/LOCK: Resource temporarily unavailable
[Server thread/CRITICAL]: LevelDBException: "IO error: lock /root/servers/rusharena/worlds/world//db/LOCK: Resource temporarily unavailable" (EXCEPTION) in "/src/pocketmine/level/format/leveldb/LevelDB__64bit" at line 79
[Server thread/EMERGENCY]: No default level has been loaded

This error occurs oftenly and not long after the server restarts

**Comment by shoghicp** [comment]
Please don't open invalid issues not related to the PocketMine core here.
