### ISSUE TITLE
Bug when placing blocks still there !

### ISSUE THREAD

**Issue by roroB20** [PocketMine/PocketMine-MP#3194]
On the last PocketMine 1.5 build and MCPE 0.11.1 when you are placing a lot of blocks to go up you frequently get into the block when falling (because of the jump) after placing it !

PS: still affect last PocketMine build #1251 :/

![placing_block_bug](https://cloud.githubusercontent.com/assets/186746/8256527/aab74f16-16b8-11e5-98c5-fccb97180124.jpg)

**Comment by Kanonen** [comment]
I am also experiencing this in build 1257. It's as if the server is out of sync with what the client - the client sees the block as placed, but the server doesn't register the block being placed until after the client's "jump" animation is complete.

**Comment by sithsiri** [comment]
Check the console/log when this happens. Does it say "playernamehere moved wrongly!"?
