### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by ettevehc** [PocketMine/PocketMine-MP#3195]
Fatal error: Out of memory (allocated 1547960320) (tried to allocate 1424017 bytes) in phar://E:/PocketMine-MP/plugins/PocketDockConsole_v0.0.13.phar/src/PocketDockConsole/RunCommand.php on line 176

Call Stack:
    0.0130     408040   1. {main}() E:\PocketMine-MP\PocketMine-MP.phar:0
    0.0150     402800   2. require('phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') E:\PocketMine-MP\PocketMine-MP.phar:1
    0.1380     540536   3. pocketmine\Server->__construct() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
    1.4531   13111032   4. pocketmine\Server->start() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1784
    1.4701   13208336   5. pocketmine\Server->tickProcessor() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2184
66140.9710 1546626096   6. pocketmine\Server->tick() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2306
66140.9710 1546626160   7. pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2500
66140.9710 1546625864   8. pocketmine\scheduler\TaskHandler->run() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/ServerScheduler.php:247
66140.9710 1546625864   9. PocketDockConsole\RunCommand->onRun() phar://E:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/scheduler/TaskHandler.php:150
66140.9710 1546625912  10. PocketDockConsole\RunCommand->updateInfo() phar://E:/PocketMine-MP/plugins/PocketDockConsole_v0.0.13.phar/src/PocketDockConsole/RunCommand.php:45

[00:30:20] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[00:30:20] [Server thread/EMERGENCY]: Please upload the "E:\PocketMine-MP\CrashDump_Fri_Jun_19-00.30.20-BST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[00:30:20] [Server thread/EMERGENCY]: Crashed while crashing, killing process
bin\php\php.exe: Exit 1

error repeats even if no players played on server since last crash

**Comment by shoghicp** [comment]
This is not a PocketMine crash.
