### ISSUE TITLE
Won't let me switch from survival to creative on PocketMine-MP Android

### ISSUE THREAD

**Issue by JumboFox** [PocketMine/PocketMine-MP#3198]
On PocketMine-MP for Android it won't let me change my gamemode from survival to creative. I want to make a server so my friends can play on it with me and change gamemodes whenever. I'm using the Soft version and have 0.11.0 Minecraft. Please help. Thanks.

**Comment by JumboFox** [comment]
Why'd you close it?

**Comment by shoghicp** [comment]
This issue is **invalid**.
Follow the Contribution Guidelines properly.
