### ISSUE TITLE
Sign Glitch

### ISSUE THREAD

**Issue by Thunder33345** [PocketMine/PocketMine-MP#3206]
when placing a sign and writing text on it sometimes it will became a blank one instate of what it actually should appear

**Comment by sithsiri** [comment]
Um...
1. I know this is a duplicate. Looking for it now.
2. This is just lag. Nothing to do with PocketMine, or even Minecraft.

**Comment by PEMapModder** [comment]
Since #3323 is closed, I suppose this can be closed as well.
