### ISSUE TITLE
Breaking Anvil Worlds?

### ISSUE THREAD

**Issue by PhilipShilling** [PocketMine/PocketMine-MP#3207]
After a short amount of time anvil world chunks are no longer sent to the client.  When building the terrain little to no progress is made then the client spawns anyway only to appear in a completely empty world.  The player also can not move or even open chat.

![screenshot_2015-06-20-11-53-21](https://cloud.githubusercontent.com/assets/11794061/8267986/3ca5501e-1743-11e5-9f12-5fa877a767c3.png)

![screenshot_2015-06-20-11-48-34](https://cloud.githubusercontent.com/assets/11794061/8267987/3ca5d7aa-1743-11e5-8c92-90d531335a47.png)
The pictures above are of two different login sessions. The top is when some progress is made while downloading the terrain. The bottom is when no progress is shown at all.

**Comment by shoghicp** [comment]
This is due to you not allocating enough async workers for this task - it's done asynchronously.

Anvil worlds are not the default format, only MCRegion and LevelDB are supported fully.

**Comment by PhilipShilling** [comment]
Is there a recommended number of async workers to allocate?

**Comment by shoghicp** [comment]
At least 2, and if a task gets locked there (some plugins do this) it may slow down the execution of the other tasks
