### ISSUE TITLE
Low tps

### ISSUE THREAD

**Issue by andris155** [PocketMine/PocketMine-MP#3209]
Pocketmine 0.10.5 works perfectly.
Pocketmine 0.11.0 work, and very laggs, and low TPS.
http://timings.aikar.co/?url=11719742

**Comment by qwefqwfqwefqwef** [comment]
I have the same problem!

**Comment by shoghicp** [comment]
You've to configure your server properly.

Try disabling chunk ticking on your pocketmine.yml

**Comment by xpyctum** [comment]
Wow, 1k % in SimpleAuth...

**Comment by andris155** [comment]
How to disabling chuck ticnking?
