### ISSUE TITLE
Srv crashing: CrashDump Error: Call to a member function hasPermission() on null

### ISSUE THREAD

**Issue by NML32** [PocketMine/PocketMine-MP#3210]
One of my servers keeps crash several times a day and I'm not sure what's causing the issue.  All three of my server are running the save ver of Pocketmine and plugins but only one is crashing.

Crash Dump:
PocketMine-MP Crash Dump Sun Jun 21 10:03:10 EDT 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux NML-VPS 2.6.32-042stab090.5 #1 SMP Sat Jun 21 00:15:09 MSK 2014 x86_64
PHP Version: 5.6.8
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
BanItem 2.1 by LDX for API(s) 1.0.0
SProtect 0.2.0 by xionbig, xionbig for API(s) 1.10.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
PurePerms 1.1.2 by 64FF00 for API(s) 1.12.0
RealTime 2.1 by Guillaume351 for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
SimpleAuthHelper 1.2.3 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfWt32ziS6F/Bcfe9nfRY74dlZd1nHdtJvCPbGktJume0lwckQYkxX8OHLWdm/vtWFUASlCjZ
3k3uvR+SbktAoVAACoWqwlP/OEhdXxyMO/1ef3Q86B23Dw9EHIfxwfgfB+ljBEkHF8bF7e3N7cHh
gS+ShC8RdsY9j6Uh48wXvili5mSBlbphwFY8mYrYd5MEYq9eMwAFmedBbsf1MGsria1WFFp3IvXd
QLSmHn8UsWEM+6abApoHwINxv3f8r8ODyMuWbnAwdriXiMMDK7QFVqzfawOhRbpIY5FmccB+Tldu
0vgtgoIbv7laBWYiffVzwH3x+g2Q7vc6lO9fFO5CmAI9ArZ+/ZVifYqxX9m/RzzmPosKYotFSfif
SRq7wZIRcco3UPkoMiyIqBqaYehRypFKaVFsRLEoMz3X2sVDWf9/EP7xnnbX5aJW99tlq/sd1ep+
V291v7fR6ilxnv2segBRNhmzyYH+YAMB28wY+/mee5nEGGo86h9t8qie06dpyq2VL4KUco10/vWP
a/nHbbvM9aralENZYXbCFgsUzENVvwIAnAbJS2Nugaz97eCnNnv1esxKgV0sZiK+F3HjNyvmyeo8
86NXrw/+8/BgKQIRcw8FFJKx6lC5TnNgi3uoq5m5ng0DrTvog1zHYRpaIBHj7tHhAY9cwux0m23A
XMIwGB+0n/kPMsT8znNNzNM8IgoZdcn4YOIG2ZpdX00an6Yz1m0Om71uo93vJik328ft5oD91GGz
qymb8ZT9Rxawboe12+POYNw+ZlezP7Nuu9Nn69EQBieQjVYREB0AmRHEvooA2nOAVNsy0QiTvFAA
UMSjSDGSE2TOWx5cpsLHoKpnDjnUGNdtdiDOs3QVxgl2xOT8d+QyMetvwK02FAtxEXDTE1CTNM5A
RdgignphBkhLQic91wE+R22CpBYLVehiccVJwL2QY3umN7P555vbyTmAHoSZuCnUEOUCGjGbQr8J
K9WqXoD0urebsie12q8hxXSXAMxDels6/4PG5DUAuSzrsq8xB6s0jcatlqpIk3spCLQLQtEM42Wr
oAINPvMEjyd8udRaXMIOK3Le2WzyRMCIsG+cq7PpxbfquaLwxWICTRTxc9qaQGNhUK0ys2mFfkuv
V6tsDTR3msUCFU+iNbeEbTa3W23usP/uXbtd7dbuf7+lhqQHmjCvgBYsWz2bn97OP06fajPllEOw
VVKBJt8K7s3JBShaXIC0BsNorDT2PWgzj2e+6A0636pv83LliDzzeJI8b1i6SmKl16JaoQH1jus1
O3y/Xjn+H+qVsuBnqZZaCT3/vUHSqTUC1Y/rR544harrCqgEVgX0aFOBTsmEXYEJY3PBUdsmq3C5
cq3omwltWRnQRnrFXiitRU1bGhXgwEWSgEV3wRsElVLyoAJ+llZK5PCXjPhWrder8a30U6VpwIFP
l9OZF6a6hipAVRPUbvarLXf/I0xWGf9w/s0aXFBcLLRKvKyv3S9EY2W3ChIVUf8gPPALawVeJVU7
vNvsVZvNPTfzHl9mbvVRtaf9kvRisaKKPN+TQH8IPWQBhjdnMfmUTXAMgVLqCnSefpoWMXYWBo67
ZDiHWsSL4KcZeGu5xzYaD4bjbp9dnM/RYxsggqTXQJ6dLLJ2mx9Z4AfKkMMabEouc1dDjcI4Pekc
d7oEhGldGD82PNd3AToYtK8QuuQIt8VJh3D4uhHR7C056baJVMQfgkYklRb0yElniOCHFbQdaCXp
Seg4CJGcb/w9E/HjCfj7JSi2IJvC8sPUfqr2PAhC8PuFqkkDvH5X3Av0/JOcDkxWw4eG47nLVVED
WVUeuD6MrSrQD80C4oQx0C7araArHttWGBfx6D7Kg7brOK6VeemjZJKcFYAGbyQiTWHClJwg2IM6
erJ7HsLYs0tYIoStoeAk/MTxeIogZE4zAsMIeeyTX+kfNC9Lw0bC74XiJHrjxXSl+eh7KEsMhZNZ
JEYZVAjnSShNDFrISoXbuJqCdLH5SiSC5TVmPBYsXQmYzIMopiuYLVjI95SZgrmB5WW2sCHAtqQY
ac1CmG6FDhLYpJlwRxyyEFLiBEkyMxb8jj2GWaxoMddhwHnXcakEYHoMogWDLkDBlaTGCyh5laV2
iJ0n1yjGbHEg52nM8sJE2IsDwPrpFCWBoSTi1FVNSti9y9lfUBQBhUSyoVLGDDUDZpytIB9H/iUh
ME2Vwh5WAqabihDLEmAPaBGoIk+hvqfTS8AETWQDI7SEBlTLhEqV5C9I+HM6PLAZihcDRkIfYVXN
R8jvcJArQFdDpUgdM1ogWeDM957DYLAbFowDUcKzKIga0NMPILiVDD/NUKtBiWHw6IdZArN6kA1g
j5Xg+o4F/ZEKaBg2NhaoI7ApYJPsRib5nDfhOqOFIOjo0+QxsOY8uWMgpnfQtZj8+fT2+vL6/RhE
y03YA7iP2J1AHmRi6YUm95jUObKwQ2ZmKXNTIBH8QnKGnSalDCUxDVPuNbHFWFhDFTRmHRQMW5jZ
EqXip0uH/cY6h0QIi0ywGyk578Ikp6i6FnLRwCNSecckrIV8ybAlYLR86KCk4GE5cEtx/AkGUN5h
OMJ8GDI0bghVtR/ERQqQ5LJNMkJZGjLLmPmQtMQFEdkWslNYUxCgNGFOHPogfTp94C2Oy1QrHrox
3a4NDH+0U9RzN/ML1S/wv5XBEAtgiBEhsoOoTKl6quSiegUHrFUW3DVQLFC6aKSBNAUpigOlJSgz
VBdlMXC1h4GY3S1o4aeBwTHrY9az0IeRQos/kl/IKVuyShWhiDbZB9DpQOgElASMl7Ppx0PIkiTM
hC56cO10JcVJ9ltOtaF6eLS7ojwGqM0EDCNVY8BFgyeRxqw7GJYNx8rnDb/ia8Y3acJQtaBsoShu
tbs7bGPeW267MAbLfKoaXNWB+lLmxa9GTPiKbc/vRjKEjSyyQepKOQZFCXNhqhDZ6q3uVaYMGEgN
/bwSqLixTnEmx1CJgfLFGRpDEVPHr0DGbQa2JpSo6EIpKBJ7X+aksYEDHvtx6bmptXqsySU1BCF7
fEn9j4Q+JigeqVQy0P0OT1JWGGFiDWhhGMMgSMQMkK0GKZFSlUEXNrf7ENqp6IhCeMF4BcBitKEa
nZyhZf92NC5aY5nkhnbDDQgBOmEIc33AoVgDUhFJeicN8kqwlxEFGhqAIowLKKop9ADQASAyiETq
v4EdGmTRmB1L4tK9IZ+OtFROC6gcYS5VIBIdYPSBY0EFkGDcN13oUImifA9pGMa5OWG0MJqbC2KO
kn/omsJ82QW/yZrg2n4VUujTCjRaRS54ZQVwFaKkUolNzesJRFpUTwo6cXSzaNAFMnUs2xsHDWUH
ChQJDSPNGThDTwU1KmiRMMJhBcIoUo7ijWurnkDLBNoGhD9GY7wCbwkVjpZDafSMxJXrKUxNZzSr
lS3BUIHTBXSWUrwFU0SRLzI5LybZ4M3Dw0MdZzwXTK80VhdrjvpBRtBEAn1ViXFeG0oCEUvSEATq
bxhscFw+R8B/IkXyYwvrp7t61IgQCMWuLXRFgfwSaa3nSE4QOe4JGSpstg/2y4WKKiuqVZ1KpQpQ
iKETjQOGFGNZ2pi9m5zOx903R4eD43XnsLfuHXbfdN7YoBGk9nmVxgIiMPJPRm22BLFKZKw/eE2e
tVinIkCG0BT8DLSOtiaOkqRFQfUti82ryEJUFUn+DnpN9OSafUPuEHyVi/hy6di0wMCuyp0v7oHw
87gEyM25PJbFXhEBnzDFGTOQ7sjlDyeNitSlXQb9EryC8UPzZ8T/khSTaVxDIm7bcoOh0xyo6vqm
3AAqSICv8hilZRNTjjW2NX7MphO5Oo4zFAuMU5n3EThC+wkqxAZNrD6WBfM9mNV224N2D4I/X0LH
9qzhaGQOTdPqte3ekDs9bvX6jm33zSNzYB6NjhwxgH/sZyhpukK+IV9lwWHirstekcYkUQgdbO+t
cDw5fwUolSccZ2Ta1nBgtk3BnZHT57YYOu2hM+qPxNDu92zHHnWHVF6y8sOSsQmNvKTaUlfyEpDT
8E4E7te8vwDyGWZAoDnUNsIQII+cpnC4mIUIX90o3y7q09aK1IgAU6FXIKnTD1P2SY5cdvIbox7A
QTp7BIXvI+hbbg4tgre4vcXO0TYC7dMoZp0RLUawTn/c7Yz7YC3O1OQT/DTpQyMq+6XZymel4heI
NhpqeuMGuBUMmjcFg/WVRucvmIx61V2ftO553IIh0/oigjtc1/4C0/YWtLuhzWapkS2cHYDts0QL
nUCY9LZoX6pFW84t0w1awLkBERdrYX3fEtAraeCA/Z70UZd8b/oN242/Zxko9t+TvtRX37MEULDf
k3wULL93HyztIhxmaSMAuQWnoQJD9YkDtcyk7MX3GqFSO+TmR4flVlKHPUh1qoNynU8w200IiGth
qDwrQKj82vcqoM24HfqVeEJTrZpcWKSIN6EPMfgBVai1dKsU5aS1WiouYVQgkR1WuiUSig85wMXJ
exXFDhvSEdFkyrUqrFpVuUluhw5Q5q0CgjzCPgnCChCXlayTR7GBCqay0qswv0vhD6YdX9NqB4Ff
GqeNlC8rFL7STMFdgj9bgZN7oQPwmJINM76GNMCVQqXLoWkGQjnR4QpVumUVjlRpgXHWo+B5aUoT
63rvn7y/md/oSGFE0zXJsbOzk6WFfXAGrur72UnjpguozvTyDLPcdPHzfPaXyeX8wvhw+unCuJxd
n14j1AnCBtauAX62ZL6TBbjCKqG6HU1yfOQc8AT8j7CApTGPwI9YNvKmOo4b4AK+JAPz3RyTFicq
mIokx1XJRsBVQehTN+5pHxNcHQKFMAdtOLgH0ohC6HM5BrDCDzjhb3ghzLgI5N5DzRO9OZhW0xyw
2rYLbhtMTHB+HwZKOzh0licua0L5XRq2TixwDb6Bq2w0EyagtZaTZOBMDDMuqrE/7P8C35Nz1S2f
vcNGHEG7T3755Zeff765vXx/ed1qNlHh/YKYJQYQC+7q0RDxbDqVNDH8++8nyz/9SYZ+CMD/dwIA
DrTcVMClffBec0d2grvql9gKB4paBJ/cOM24x87dmFr9yGZZhMshmEktQpQOsVz3eoe7Ma/AzjWB
26/ZFFiK2N/ciiKxRUDb0zarqQKWuQp90Qp8r9fVj2oWFFQAKwocwY0bWnADZ4RWe7htu0gPGIAo
tM+UIN1XQRgImJ2c1iJEPMYVUg0PZzGK0zCX6HU67aEEXuSz8CKp24Wkv+LqUzVtZ6KcseBkZXpZ
YB3OZ5sFVPB0tHPaRiiSg3ARzOUq5wyENH2sdDUVPqORwT6AxNCmzhbCldwBueIBX+Kq9lY6LoCY
jzDJ0sQpisN7F/vSfGS5V7QILqf3w1qhO5/jaNCTlIW1cX54q8YBkEM2zGC8cJ/6Ll8/b6Lvf8ig
+w+p3w5p++aQ2Tzlhwx3+AGOH+g7HDIwiBWqkiKbkVQxqEuQyGVCKCK1IFtm40fgrjG4rMv7jhY4
KAfWpfnrIZO+PIVsUYQlL5pxmHZ6RSwNoeUi1uJe+KDF8Ssy0M8odlqQFi4LZr6woaGCFnKRW7TY
Dvxf4nFXn9+BEOOmjtzsZLLPLSBHu40T0CQZ7qNd4CIeLllJiaQYu6eDlIcwIKPHGNfn2SvrNesc
H48aNI0m3DkUHUB9l7S1iv8x49v8k9Qq2gAB0t/B0NuzK1RISY1EgUyRmgPFSwsLIfjh7JM8VPsb
CDP2noznBJsJuuqY2qYPWh1XzjvVQ4V3FHdGa/27FzmeXx1aYDRgMm44YSSIyo361BPVHjclOI76
QoQH/pgYURhlHk+FEfMHiCSpgWNBbx2Pl0Yi8MwH2ALQeFFGTfrf9LGZDK75ZnoiBXKr/CwNDbDV
wCvDUao7CNl93tY8rDDlNmtifHHTjYZiKgzuZxAy4/ABOi/ajaH2GQ1rheqcSspSpzHCwMf5u8ao
RPFdX+CEgsa+WKetVep7lQiepyDlZFh4HlBakR3lKsT8FPh+VNxPM+imA+HN5uc3H+dlqMSBiQuY
8kjDVXzDDrBDy4jDMN1TVGjB7NOA9jyJs5+QFH/D9qpdp8CF1BlogJRt0bCw8rmkqHP7u0siZFAy
T6HkEvM8gnI7SCG2NzDWbmqEgYGXUUIp+7qcizW0Dxq5ijaalRtpAz2P7+UrYaBVLvu3wMWl6TfO
UBu5R/D/tvRFgKPWyCLcKUmqTFqBMaEN36bc9STu/psTQiBJHz1xsjiwwKTEY/bTu3cj3D48+E2F
/q2FaL+9OINeaH7sYCcNvMTw9i3SkKEnC92RQS801yO7Cchay9CzSqzJoJd4Jx7xTNY+GkdHOQ0M
PaPQ2gx6oeXAqydxfp7XW4aeLHNHBigTGKqrQG1wgk8L5hiHNx1ieSZWEmaxJXZggQ8F2spUhr+C
4Eeea4GycLwsWVUFXRlpI1ITp+ZYfmIKGFRDBFZo71VUNA0Fq/4MVFCPO1paphg+Xxue9Co67W4/
/8aTk67XhFmSsTZWtCy4SYQQ6Owhmo6YG+V50d11okx79TZWCHc4MjSQpG11LwVTN/VIty0/Zapk
ZCDo+Jwhz+ZA8rAvP3WknHijIz/1NNCTiWRGu51/50dODZp4lzk73dHVIkDnzDA5TA+loq9vnvSc
DDPDUye6pWkXaU/3rEJc4SRN7CmMTC62KXG/UtLoSn5CErifbu6VdmS/A3PANHsonAYt9xX5OsM/
q68tlDT1JA/a6gsx5HTIAKfRwo/76iiQZtYAZnqC3yW1ibgQachTcBtyF4u/Z9C7BqiyfW3Hkxgo
bQadQHsaLR+SrJGyhsu0IB0/drkHvDCqbDuSn4CAC78GSQA4wZs1nl3Npxjx0M3HAw+VCOT208jI
5xDdgfwE8N+9Jq4lGXisd5NmAk59KvzI2CttuKp0t0MJZFqzoCqeiajome4mJwedkQ/CXDq6V/Kz
QEifqhdpz6cx3MBtVqSsJwdjD8digYFVkfclQZUilNZr9MgigOHs0inJUmwu3k/PZkVgEeD+R2RJ
ZhmBPCmqDU49eYuXKK3gRuCRciMLXCvvsEKqCUE5wkurJs0vlk3qSCc0Q3+GZpDYtIYDsxth3W2S
g0ksTmeKAKvMRbQJLG7/0vfH20ntHJcSLgN5zlKNiKNmv9NsN84vPi2C0yXVrbcI3oE9zWJcDqBj
t6vza+L7Hwg5gykYTOlJQ1yH+YqViryfzRrXYhmmrtq0R+Dl+XURxAWknNJdbPbzhAkoHZHPEikV
3NSvReR6PrnKUTH8+W0em02vL97fFLHZpMgzm8lFPoTPJ7PG7HaaR6fqqiyxUK43OWqJKcmXm+ha
ySL4oEa/PJPQyIK7IKTzbuBZN5ZBJsvUFgymocdjgLU6zR6uHPx14pp6Oh6AoQUFPNeTf7fIstUu
TBzceEkIXwyvsX0NA4EHIjiaLZ0qLuc0u9DQLSRIzF0Q7Cx1fDdHwyVIH7SKxVvX4sH4A6YQL1vs
wNrn/rjhgVylak2j12keDYdHWnATOQyWJTbUvtfraUGFnWRB7MI8DcaJK/U9HiMZ9RRyESnRE5E+
F3sfG6rDFCecYqkWM8WaQafGPKbl2LcZGnWbeQqkDUl5agpDl7Q8AzxzbTn2cIFfrjluLtreivvC
YNFBodEQjLRp8sFwZA0GneNOn/cGw95QWP32yOmIIzHE00pd9vPLuk7WTp9Mya0QXHKqxjZxwVNW
K0f1Sg3w0wi/3oEdrV9uW9Ln+/Pa5WQAa7JtKga/6uLNO1ozBh4C5mvAvHzHbml5vI4MJJ7JywZ1
ydPr97Vw6EhMqozZYRO9hs9v8ehSTZbf317Vwl/SHUu7+SUSS0PNV/CE6Ia7CTh+pL5q2foeqndf
VnuIN2cRHw/i5d+1GT9AAhYm142pZ327C399+BuwZMU7+NGF+QZ+DYb41RtRbNDpMjB2wrfBrc5D
w7YKIa4M9cDhfFi5sRfhEw6puxQxZDjsqeCwXQSPu0UQEPolQr9EgKID4cSZ+sJilqiq8aNBi/Uh
4+hsw7iwYiv/NJkT3Hcghl9cfcNUg6Lw/SXkPGUrDoIsKyeDVDkZpMpRELhRBAfDAoGqXGTrl9n6
ZbZ+ma1fZhuU2QZltkGZbVBmGzDsUDxUmX/Xdiwl3FetT6e4XmKbWrA2f55WLBbpxIqTmyVergQr
RXbI3pXbSIugds+pKLRMVYsRQm5noBPumr7pgCX7MAfVIhe9CycrxY0fr/Btyi0olataqx7ay7Ja
WhMrmy6Lg4R2iOgu1R0PvriMvEWpEdW1KtrRAU1/cIgibq0YbVwiYTPDC0agwfBw/0qw99cf2QRv
bcRMXk/w1MVDMCkWlC+KSqK2q/Lq1RcecRie4jWLyQole5kncV6FAe6+ZD5/zXDGQDMMVrqawf4s
9/pWyHFz8DKdljM3d7WfmAIW6HmXGhtdWlnOyJHRITbwJDhOZSprDzkG+nJGsUPyRNmEXO6XPB/b
QDko9h9Iif6fV7Tr8E8e4RITNaO1pj2IxZ9gfvL6OThaYS9YSyryePkOISaLLEWJK4MaIn5BF8me
2sfvJIMQeG6poP0YbqX7+hQykjouQ7ViK5MMNarqMHRvtzlAH/o0csGdl+5vu9vpoolW+gTGnOVG
K7W0ZYFQNtA6kYmI3S/g/gmPIOlD6LhgFXlsOXhDlFDRmnjhnXt8pCEfd+lqaRx5WcIeQEUw0wsf
MHNDuiTMhk4v8MlIAjYujoNm4QU2tMhd+pzFVpfhtjA0DvLpNcflA1lv02KWYzIrjZmwTBZgJAjh
A/+kXmIvHJFyI5t7yzAGF9lP9s/qFTrVaD8m4NIJN1JZGLqsP57i4U0fOoBRYyu+8UF9EBHJlSkW
AWyAkiduIFew2uiV873pKrcOehGviSFNueVLy0eghPJJbrmcUEGLyprUIeUOeL4otaPXqsh5J/R6
7WH+vY308Gx68nzms9FxUedJZFrWzvn8MVAnpSqRCm6VT09kwMt5QQC9tqXTVHqoVtPCQC6S2kaE
ldlei1ECqgV36ahvLsr6DVagn+TqYhHQtW619KGByaHBMzwqCe9sasn5MTO5ss3ytcF++3iIk1C+
ldLrHg1HKknbVO11Bj15Q/AM2IhDA+ySduO7WDgqU9Wl7CoSrdOANcnNWosXB8ryO/UlWw9ppdmg
Q3iH+DCHIXEMSjcCjgPUyF81qMGge6kFAgx1UEjF+ayyJFfv6Wp9QfGiz5QYiRLCdg4AcRNQvK2A
EafjzDpeDtrEVOtS5M3gJg7oi51Jiv1bpRrhnSHp1yeL0Nmbjgcs1A7S03iOC26/AR4Pfxo3RvW2
Bwm3/jnt5yUR9IHYi0zXFtWuXgVP57ZhlXeCargOnNqVAkzalaTxZy9KyZq9aMCVXembDNmFp/FC
oUAOUtRAH9+ecEVuvgLQcHsSQd5ssTaypBBJk4RwA5igparmlboCN2FFmsOyWmiUGDvA9fi0Kwug
ANetvbqUKNkgpBgHefDKqdqdLEeZhhAGtBtaScfTSIYjUrIDuBllyIukqgZPYUWJjlG0iFAs8n5q
CNWiVSlVyqoQKnI/E73k81MZtL56BuqL6OKtnzDWETnktdKip2uTqixJ7twoqs2QpxT4Vhg9onmn
uzEG3jS2a1PAr8ANEi2VNIhig5GGoZH4+FBtnkx+hZFkFt5F34A63PXwamIF6tIQ1EZTxTtB+awn
Kl1Vo6SykVB6RDU4Yq3OONDDNQpYHHzQgbab5OVXcMFwurbtCQPMR84UHaEowYmFUDpms5ztpCJX
kvo7KreVAt6DIbAPQsuge9Q1cPXQgpZg7chg7cqA2+a1OfKE7SzUPqsWuoW8owG76r+j+rtqv6vy
O+teW/X6mguYeAZ2Fm2h74JDhl34m2BycwxcECn0Br5utjvVdPdkBWfz0d1Hm44B7E6GvPKEzc7k
fRVb7k23heWWSqsGwfFCvi9/mJme2JOudmDrUx/B+93HN/8JyvsxMBWcZT/aw/nimNkO9nmhuTtV
BJm/h7bYw7elCMEnk1t39Rj0dFgl2XQDHj/ulsiN9E2Z3Eiuk8oNlG253EDYlsxthP1VXD6BUSef
GyjbErpJY1tGNzE2pXQjfUtOt3jpP0n/KZx6ad3skW153WTppsRupG/J7GYJYi8va+V2A0eXXLxd
Vxjq3MOt6NoKBroqG+mQBE6+q0cpi21WEERRJ4zLWQ8+9aQB5Vtk1Yx2HEZVSIyWUh7AVJD8AT4d
VJmDK6B6CQhX10K92IpbpSPeuZoH55fH1nK0sqsxqgmQxMZ3s3CIgcdfaebWPAyh0Ed4fNPOCgEj
mvLkfRWYO17l1F7yRZ3OSzx+Lyq8AM9ITWU2warHN8F4eo5OXpTXSbRU3csqgNAnIt2mg6fn8m0C
PYVkscItcCCCHcsC4I3IGwYVD34nVlSuwtJd7CKw45ABPo9Dd3rObi/Yq6mIPbxcqU4PsFuxzDxQ
LxfrfF0teV1/UACz5yc+tCW+UbPXp4uCjU630Xnh1hjWrVlsyJUnVDvyOLgWVLhAOKOiN3HLELV1
Ja874feY7tudxtYKa1THI8RiF7/P9UV4etRGJeGyWHUvF7ePZ5+uWbx5TKXrdK2+3Rs4w6Etjs2+
OOodmf1+f9AfHQ07vM+79qg34LSWibQbdPSWbvTh7gtWsXqkbf4MnL9eTp/EWX51I/2lvkqiCYnd
zdR855i9gjGe4mwvEpbXMr92Xy+Cm0jQma9k+7JjiY87eni6NElwAy/vDyarGuJTbTzGWxyG6pxD
FsZokkFeLFyTiFK8eXkO4/2RzVbcce+aioQDzscjwzHhfpX3M9+DgsDl1LeC36sd6StgRJawt6GI
lyLGrHhNBqeDeI0QqBRv98mt1eoFwW673WvAxzGeOWN/xhn7V3p+7AXSDVVVJ0FzW7DjxDMi4v0i
evNuY71dJYIRioVBh1cqeyJ0Xtpdy1NZG9I4sLttWxwdDUdH5pF9POyYnUF/0B4d9Rze7ZnHYtjn
nd6Qy0NT+esdGP5UHQmdjqSfP99Uje1a/X/hC0/0kB6+W1EEdmg09TQGvbokgzvOHc2mE/VVS6m4
Vp7IG+dg9THlkN2A0YgvU/m02SHoSFI696IEzYS4Q1wNEnk3plz9osgsM7/gj0fI9/ZlEad0T6zM
cxrH/HEjekPZDtlbbr9Th1zxN4Eu1jge6PE6SLmit2834Gf4QnOwLOmdqfPR8ohdCS/uzmugEB8I
0Yhd+FGqpeP99YReuKrAKmTfg+9Xxi4D+baBDrnHo3+n8TLDQacVluOUuBMRLNOVhjJBda+lh0vX
0pKv1AN2JcZ1eCseXJ3b0Ks3zlt8WCHRchL0Fn0WHQi9CI79gwaacnxuUxOKjSyFkGx0agHf6h4t
pb6fCoSaDivSdmbaZmqRRMc3a+DzWAgdXMWC4QE+oNZkkPJznNw84t6wsCeg4wiIwoJHrItILtMU
XQubWETRD4JHFLhygzLM10VYZp1BDejtYoBMYxd37R//kolMQsrQLOX4dCiE5sKP9KI/4uGjjS79
iCtvtKRKCrtIIR0j3xEk9fGXCQZrVUie5od25onqubAjeSpMouiHZXvNEfzXe5mrpCrU3Lqauesk
Qv5MIBXzGHCfjlfJStQ6eHiVJA1ZfrekcpfkRVe/8WBX2uQFtrxuVCSYinhxh1uC89sce+5aS0Sw
hOB4i3teR0U7MVoUi5ew1dkrfE/LkC8dJ3ru6q6+fl122Jafi2D/lRy8zR4L+epUM79Tzk/ApDqH
oDpUiN5lOUli6xAX2E8OaaYI84iTl2GreyQwJIJ0nwwUjyDSmwp5ZIe1VO8j5kEY//TEMJrHJ44i
0XuKmA9flsNvkLM/Tq8m9Qcb5VD5tOVQ55k+VQ9X9l8mfViFJj47agu1MqD3s55aXfLQEfKjbPh4
u2tV5UxHwD1B2QFd+qimyleycYrUlp/YEHq1A1x2N6owpXwVZdN/co6dTpfD31G/2+max063Oxoe
9Y+6os/54Ehws2+afctB/wmpVicqXWQfMPZrNYUeMKWTn1/pzRp1Q6Ouu9TTIJ/x6SI5pa+8VzJu
tQocaYqK10PcAH9dARQzxWCEeXTZ40zey7Zr7oNIO1J7UeT5AkClFYcRK1Oayg2lerTy7mV5v1JH
ffL2YuUNHinr5Kkqsb+GEY3Ri+DejcNAPlgMg0nd9EJaqh2zDxcTOrJCt9ZNOr0+v7ilK0AgLbGP
t24+GGeTy4tremDhaNA8GkLHjpqdYZcNOr3+iHWhk28m59PP57tfH6LnPm7P1HEOpDmf/0HoYL9a
UZq0QHI/zi5uEYZvKUBHzYyzm8nNLd2IipOT9th2T9qdN73+2AsoMBz7q5N2exy5J/32m15vnIQE
H4ztPGDaMulNuzO2tHAYU7iD4SQ76R296UNgedJrv+n3xhanQGecPlCgOw4h0MdAkhJyfyzWVER3
/Cto4pjCHQwvvxZhHn8p4byEe19XWtjnJZJXIqXrMgwjqwwXob8WIbsELvViiqBGC+bWWrgsrhou
cdISbguzCMeRX4S/aO1/0MJCCydaONbCMDMqmxaGRdiK3DJyVNYhLoNfoqXq5V/pQkcRWbpOETb9
qAhHpl+Gl1o4KsPpkhfhtYa/1nE0+hAuI1FQViK5r4S/FhFfQ4qsdQkP78uw1jRfb5rf1ZDuyvCD
0Ooaam3zo34Z7uslaJH70CzCf0+LYJBpBfhlmCdlk2NfC96XZBzPKvHvXQ2uh0uaS68I2mVwbZUl
rR/sIvyo1czSWiv8Ep+vtRoHa40791q4hHMONW6jVoFwVgTBopRw37X1sFtG7ngZjnpauMwcLpdF
OC7RH/h9We6aa+hlOInWRXidRI6KgFY9nX8gNZolcYtOvrYSUOVjLV5EywQKyGgBw19JSvR8BACb
cno5Kd5HQZ+9JdXzE+r+w83VBaVL7NmHyaeJ8l8mN++vT2WqSkQTc3N9fXE2v7y53mVmOu2jZucY
f/+r1xwMyOpMLmazm+kFZfkny5vWwt+eiNxIsP+VSJyzyc3somDTBgphGXQreuuNvOKdqvyS9A47
aoDl+nRx+7fFAVnUxcF/bhjVEgHNq0pXFlbLXNhahbHL3JZZpOHNC9zRGSU6WWGFvVkyWOScjmaU
Sxw0zwpB9luZVNjqPP2Huf5hrn+Y6x/m+oe5rphrTRGD4c617Xez3WVxaMXz4jYMuVanFxgStO85
8iYdMvYqsWKslOXfYUSqbsAeC1jjCWhlKJ9A5d/lFlQzkIOgd0etj1BkMRRqncNQsbUQmbwrkCs/
1NiMaP9Ya/7Z7eV0bmgMemaOd5eTixfkQskz5ren17PJ6fzi/Jm5zm/OPl6BY2Lc3tzMaxyI24u/
fLyYzY355dWF8W5yc5ojdfrQZced3qjXHHZHo115trB1RHwoSSHQsv4ieIW/7cTY39p7Kk8IHUJo
eIuAtocrNC1NRi+uP+3x3mRqjeumsj3bb5P4z3PaJO6Gx1YWuMNdkwjbvpqE/3DUfjhqPxy1H47a
D0ftCUdNKd//K16aLGufi6Zq81ybUeOc5fat6pkpo1DnlmmW7b/rkynqz3TISuzneWMSf58rJtdu
1HMfG++9u/gDvEIw/HV40K3iDf5uNf2KNf4ORf6gCP6IIw/sVhjL37EGzwMg5SMj6AUk+YvxWmGM
Q0n42ghem8OjY3n6+zjMIvzdc7vy09v0E795qbiRpGB4h33M2OTy7OIaWBJsN0J//ERlWoWRUL8n
nBa/x5olwsm8Q7w/mLLPl/MP+GL26fUf7PPpLfiC8z/eMPXLQkzcC0mIbgbhb/dycLqC9BEaugiu
Lm7PPkCG07eXk8v5H/irme8u59fQbezdzS07ZdPT2/nl2cfJ6S2bfrydQlfS6yqXDnHYdm26H60O
ndKvckePOgs9yUI8qIev8ABKAGynly3pYB03sZIlphssD1nk0W9RW2GQcivNafw7/sxFIFKowMG/
/gvhFBJi
===END CRASH DUMP===

**Comment by HmHmmHm** [comment]
hmm..so is it pureperms Problemm..??
i can't find what is problem.. ┐(￣ヘ￣）┌

**Comment by NML32** [comment]
I disabled the pureperms plugin and server still crashed.  I'm very sure I did cus that is the first thing that came to mind,

**Comment by HmHmmHm** [comment]
hmm.. i guess is it   associated with 5796784442530f3eff37c748bcfcf9ab53fcf2ab

**Comment by RandomAltThing** [comment]
Next time please use pastebin this is a bit long.

**Comment by shoghicp** [comment]
@HmHmmHm if that does not happen, players will leak memory. This is a problem with plugins saving references to players and calling them later

**Comment by NML32** [comment]
I see the ticket is closed.  Is there something I can do to correct the crashes on my server?  Is it a plugin causing it?

**Comment by reidq7** [comment]
Someone please fix this. I have tried all sorts of combinations and its all useless. I've changed pocketmine version, pureperms version, slapper version, essentialspe version, and deleted all of these plugins to see if it would stop. This is on all of my servers and its terrible please help.

**Comment by NML32** [comment]
There's a lot of us still having this issue
