### ISSUE TITLE
Unable to sleep at night

### ISSUE THREAD

**Issue by tiNsLeY799** [PocketMine/PocketMine-MP#3212]
![screenshot_2015-06-21-14-55-51](https://cloud.githubusercontent.com/assets/12755193/8274887/f7bb0f7c-184e-11e5-97cd-65395ece8db8.png)
Title says all

**Comment by RandomAltThing** [comment]
This might be caused with time lock and therefore doesn't belong here

**Comment by xpyctum** [comment]
Yep, on my server players can't sleep too

**Comment by RandomAltThing** [comment]
Do you guys have a time lock block? If so, please close this issue.

**Comment by RandomAltThing** [comment]
I meant time lock*

**Comment by tiNsLeY799** [comment]
I just removed the plugin. Still occurs

**Comment by mightysun99** [comment]
Remove ALL your plugins. If its still occurring then its an issue. Often plugins can interfere with this sort of stuff.

**Comment by Creeperface01** [comment]
I can normaly sleep in latest dev version of PM And MCPE 0.11.1 build 2

**Comment by PEMapModder** [comment]
It is a client-side message. That probably means your client's time is out of sync with the server.
