### ISSUE TITLE
Translate error?

### ISSUE THREAD

**Issue by wrewolf** [PocketMine/PocketMine-MP#3213]
I have message in console
```
[08:42:16] [Server thread/CRITICAL]: pocketmine.plugin.loadError
```

But in code
```
$this->server->getLogger()->error($this->server->getLanguage()->translateString("pocketmine.plugin.loadError", [$name, "%pocketmine.plugin.restrictedName"]));
```

Why not show the name of the log plugin?

**Comment by xpyctum** [comment]
В Русском такое?

**Comment by xpyctum** [comment]
Или на английском?

**Comment by wrewolf** [comment]
Question closed, submodule locale not inited.

**Comment by wrewolf** [comment]
@xpyctum Просто сервак из кода запущен и не было субрепозитория для переводов, соответственно код не мог отработать верно и показывал текст без перевода.

**Comment by xpyctum** [comment]
@wrewolf Ну, у меня также бывало, только с RakLib. Вручную догружал все.

**Comment by wrewolf** [comment]
@xpyctum 
Я вот так обновляю код
```
git pull --recurse-submodules
git submodule sync
git submodule update
```

Но по хорошему не хватате
git submodule init, но сейчас он не смог сам создать модуль для locale решилось ручным git clone в папку

**Comment by PEMapModder** [comment]
Please use English here.

**Comment by xpyctum** [comment]
@PEMapModder No, wohahaha :D
