### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by GAalexandres** [PocketMine/PocketMine-MP#3219]
I don't know why, but sometime it happens, I use the latest version #1254.
http://pastebin.com/x5yQVg0z
O.T.: Oh another question, can I disable the fast break block protection? Because on my server the players are unable to break block with iron and diamond tools, the have to break it several times to effectively break it.

**Comment by Intyre** [comment]
Duplicated of #3214, #3210 and #3202.
This is a plugin issue.

https://github.com/PocketMine/PocketMine-MP/issues/3202#issuecomment-113796701
