### ISSUE TITLE
Command /whitelist off doesn't work properly

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3224]
I must restart server after turning whitelist off

**Comment by RandomAltThing** [comment]
No, you have to do <code>/reload</code>. This is because the changes can't take place unless the server is reloaded. No need for a restart. **Invalid issue, can be fixed with simple common sense**

@shoghicp

**Comment by shoghicp** [comment]
@RandomAltThing You are completely wrong. Please stop using your alternate account after you were blocked from this repository.
