### ISSUE TITLE
Iron Doors Open

### ISSUE THREAD

**Issue by LDX-MCPE** [PocketMine/PocketMine-MP#3225]
You can open iron doors by touching them, just like wooden doors.

**Comment by qwefqwfqwefqwef** [comment]
This is not a bug

**Comment by RandomAltThing** [comment]
This is possibly a bug. How do you expect to use them with no redstone

**Comment by LDX-MCPE** [comment]
A plugin? It doesn't really matter. Even in vanilla MC:PE, touching an iron door doesn't open it.

**Comment by matcracker** [comment]
Are you sure? In 0.10.5 I can open the iron door in singleplayer, I don't try in 0.11.1 and I don't if the Pocket Team fixed it, but the redstone isn't implemented yet and so it should correct open iron door :)

**Comment by RandomAltThing** [comment]
Wtf I couldn't open it in singleplayer

**Comment by KyleTheHack3r** [comment]
@LDX-MCPE I'm sure that opening iron doors was restricted to op-only before.

**Comment by Creeperface01** [comment]
You can disable it with plugin but most of serveru dont have this plugin so players can open iron doors

**Comment by LDX-MCPE** [comment]
@KyleTheHack3r It is a bug, regardless. You can't open iron doors in local MC:PE worlds, you can't open iron doors in MC:PC worlds, you can't open iron doors in vanilla MC:PC servers, and you can't open iron doors in Bukkit servers.

**Comment by Creeperface01** [comment]
But in PC servers is redstone :D

**Comment by JoahDave** [comment]
@LDX-MCPE Is correct. This does appear to be a bug.

**Comment by Creeperface01** [comment]
But it is good

**Comment by PEMapModder** [comment]
PocketMine is coded to simulate behaviour by MCPE vanilla servers. If you would like to see an additional feature, please make a plugin.

**Comment by sekjun9878** [comment]
Let me test this and see if this is an issue.

**Comment by sekjun9878** [comment]
Well I couldn't determine what behaviour iron doors should take because it hasn't been implemented in MCPE client yet, so I'm going to assume that it should behave the same as a wooden door thus the current behaviour.

But of course, you can use a plugin to modify that behaviour if you wanted to.
