### ISSUE TITLE
Anyone can crash 1.5 dev 1244 server with particles

### ISSUE THREAD

**Issue by jazzwhistle** [PocketMine/PocketMine-MP#3226]
I'm using dev build 1244 (can't use latest as it breaks essential plugins) and anyone who can use particles can crash the server silently using 8 million particles.

**Comment by shoghicp** [comment]
Yes, that's why particles are op only. If you are op, you can also stop the server

**Comment by jazzwhistle** [comment]
Ok, Fair enough... but why add a great feature that we can't let players
use?

**Comment by PEMapModder** [comment]
Use a plugin.

**Comment by shoghicp** [comment]
The feature is not the command, that's just ridiculous. The feature is that things can make particles, for example, critical arrows or block breaks

**Comment by jazzwhistle** [comment]
Ok, I see where you are going semantically. I'll try to write a plugin that gives users a "command" to use this "feature" without crashing PM.

That said, and without wishing to irk you further, as a developer myself I consider any command that can be passed parameters by end users to systematically crashes a system a "bug".

**Comment by shoghicp** [comment]
@jazzwhistle Users that use commands to create instant particles somewhere should think of using a plugin that creates particles on tap of a block, or things like that.

If you have OP, you can do anything on the server. It's a design feature and you are not an user anymore, you are an administrator. With that level of access, you can shut down the server, global ban the server, kick everyone, crash it in with several debug commands that warn you of that, or anything.

It seems that you don't even know what a feature is. The feature is not the command, that is just used to debug the feature, particles (development, see what they look like). You are providing a lot of particles, which if sent instantly to the client *will crash it*. I think if you use something that way it can't be called a feature anymore, don't you think? If you decide to crash players as a feature, just don't let them play and that's easier :)
