### ISSUE TITLE
[Server Crash] setHeldItemSlot

### ISSUE THREAD

**Issue by rain318** [PocketMine/PocketMine-MP#3229]
This problem has occurred many times. This has occurred dozens of times. :(
(Plugin does not matter! This causes the same crash in vanilla.)
```
Error: Call to a member function setHeldItemSlot() on null
File: /src/pocketmine/Player__64bit
Line: 1775
Type: E_ERROR
```
CrashRepo: http://pastebin.com/HxSaec9U

**Comment by rain318** [comment]
Oops. Sorry, The last one is a mistake.

**Comment by shoghicp** [comment]
This issue is invalid, check the Contribution Guidelines
