### ISSUE TITLE
I got a lot of issue on my server with  my friends , read comments!

### ISSUE THREAD

**Issue by SimHotMinerYT** [PocketMine/PocketMine-MP#3231]
1.Placing block lags you like game has freeze!
2.Glitch through blocks hardly escape 
3.I keep got Glitch TP around the world
4.Cannot break block sometimes
5.Armor not protecting us
6.Tapping Hotbar sometimes random switch
7.cannot craft boat
8.autokick as flying
9.auto repeat output command usage after command was sent to chat 
10.Weird random people join my server!

**Comment by RandomAltThing** [comment]
3. Maybe they were using /tp to tp you round.
7. Boats are not implemented yet, as they're an entity.
9. Is this a plugin command? Remove the "usage:" part from plugin.yml.
<pre>
name: Example
author: RandomAltThing
website: http://github.com/RandomAltThing
commands:
    test: 
      usage: Get rid of this bit!
      description: Test comman</pre>

**Comment by kevin200** [comment]
Placing block lags is your client problem, autokick as flying you can turn it, what do you mena Weird random people join my server

**Comment by PEMapModder** [comment]
@SimHotMinerYT @RandomAltThing Please read the [contributing guidelines](../blob/master/CONTRIBUTING.md) thoroughly  before creating an issue or commenting on it.

**Comment by SimHotMinerYT** [comment]
My friends Were Not Op

**Comment by PEMapModder** [comment]
@SimHotMinerYT please read the contributing guidelines. You are submitting duplicated issues,  and you should create one issue per issue.
