### ISSUE TITLE
no bag

### ISSUE THREAD

**Issue by qwefqwfqwefqwef** [PocketMine/PocketMine-MP#3240]
Can add permission effect for themselves and for other players 
- pocketmine.command.effect.self
- pocketmine.command.effect.all

Sorry i'm use google translate

**Comment by RandomAltThing** [comment]
I would prefer

•pocketmine.command.effect
•pocketmine.command.effect.others

**Comment by qwefqwfqwefqwef** [comment]
ok)

**Comment by PEMapModder** [comment]
Permission node `a.b.c.d` must be the child of permission node `a.b.c`.  It is a standard.

**Comment by sekjun9878** [comment]
^ It is called inheritance.

**Comment by shoghicp** [comment]
This will be solved with potions later.

**Comment by RandomAltThing** [comment]
POTIONS CONFIRMED
