### ISSUE TITLE
Stone Needs to be Mined Twice

### ISSUE THREAD

**Issue by TrendyGuy** [PocketMine/PocketMine-MP#3244]
Hi,

I am trying to setup a server for a public library. The only version I have been able to get to work with pocketedition 0.11.1 is the development build #1254.

I have installed this now on two separate machines and have had this issue on both. Server is running smoothly I can chop trees, mine dirt, mine sand, but then when I go to mine stone the block will respawn. If I mine the block twice very quickly it will then non respawn and drop the stone quick. I have tried changing various options and install the soft build but at this point it is looking like it is a bug.

**Comment by alejandroliu** [comment]
This is a duplicate to #2842
