### ISSUE TITLE
I can not install on Debian pocketmine

### ISSUE THREAD

**Issue by messi95** [PocketMine/PocketMine-MP#3248]
wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 13:00:47 EDT 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Tue Mar 17 13:16:17 2015 EDT using RSA key ID A7837F89
gpg: Good signature from "Shoghi Cervantes <shoghicp@gmail.com>"
gpg:                 aka "keybase.io/shoghicp <shoghicp@keybase.io>"
[+] Signature valid and checked!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 64-bit PHP build available, downloading PHP_5.6.10_x86-64_Linux.tar.gz...chmod: cannot access './bin/php5/bin/*': No such file or directory
 checking... invalid build detected, please upgrade your OS
[3/3] no build found, compiling PHP automatically
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[ERROR] Please install "libtool"
Libtool i have installed!!!

**Comment by cactusthinking** [comment]
please install libtool by type:

apt-get install libtool -y

before above command

**Comment by messi95** [comment]
/3] Linux 64-bit PHP build available, downloading PHP_5.6.10_x86-64_Linux.tar.gz... checking... invalid build detected, please upgrade your OS
[3/3] no build found, compiling PHP automatically
[PocketMine] PHP compiler for Linux, MacOS and Android
[INFO] Checking dependecies
[INFO] Compiling for current machine using 64-bit
[PHP] downloading 5.6.10... done!
[zlib] downloading 1.2.8... checking... compiling... installing... cleaning... done!
[mcrypt] downloading 2.5.8... checking...messi@193:~$
messi@193:~$

**Comment by messi95** [comment]
3] Linux 64-bit PHP build available, downloading PHP_5.6.10_x86-64_Linux.tar.gz... checking... invalid build detected, please upgrade your OS
How upgrade OS?

**Comment by Intyre** [comment]
Please use the forums to ask for help.
https://forums.pocketmine.net
