### ISSUE TITLE
Ice not melting nor lowering friction

### ISSUE THREAD

**Issue by TigerHix** [PocketMine/PocketMine-MP#3249]
Ice blocks would be melt when any blocks next to them has a light level of 11 or above. Besides, they would have a lower friction factor on entities sliding on them.

**Comment by thebigsmileXD** [comment]
I rewrote the Fire.php onUpdate to work with Ice:
	public function onUpdate($type){
		if($type === Level::BLOCK_UPDATE_RANDOM){
			for($s = 0; $s <= 5; ++$s){
				$side = $this->getSide($s);
				if($side->getLightLevel()>= 11){
				$this->getLevel()->setBlock($this, new Water(), true);
				return Level::BLOCK_UPDATE_NORMAL;
					return false;
				}
			
			}
		}
	}

But i think the ice would also melt in the sun.. i am not sure if the getLightLevel() function shows the sky's light level or only block light level.
I tested if entities slide on ice.. they do.
So the friction is lowered, also i think its done client-side.

**Comment by thebigsmileXD** [comment]
I rewrote the Fire.php onUpdate to work with Ice:
```php
	public function onUpdate($type){
		if($type === Level::BLOCK_UPDATE_RANDOM){
			if($this->getLevel()->getBlockLightAt($this->x, $this->y, $this->z)>= 12){
			$this->getLevel()->setBlock($this, new Water(), true);
			return Level::BLOCK_UPDATE_NORMAL;
			}
		}
		return false;
	}
```

This should check for the light level at the ice blocks position.. if the light level is 12 or higher, it should "melt"

I tested if entities slide on ice.. they do.
So the friction is lowered, also i think its done client-side.

**Comment by thebigsmileXD** [comment]
1 of the examples PocketMine is dead. #4137
