### ISSUE TITLE
CRASH AND BUG ON M'Y MCPE SERVER 0.11.0

### ISSUE THREAD

**Issue by alexisoko** [PocketMine/PocketMine-MP#3250]
J'ai un énorme problème pour mon server ! Premièrement les panneau et les coffre disparaisse à chaque redémarrage su server ! C'est très pénible mais il sont toujours là mais invisible car à l'endroit où il y avait le coffre on ne peut pas marché comme si il était là 

Sinon mon server crash tout le temps et pour 15 personne ci par jour c'est chiant ! Voici le rapport complet du crash

PocketMine-MP Crash Dump Fri Jul 3 00:02:55 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.49-4944491 #1 SMP PREEMPT Thu May 21 16:42:57 KST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PurePerms 1.1.3 by 64FF00 for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
KillMoney 1.1.0 by Topic for API(s) 1.9.0
PureChat 1.2.7 by 64FF00 for API(s) 1.11.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
ArmorSpawn 3.0a by LDX for API(s) 1.0.0
VIPSlots 0.0.3 by iJoshuaHD for API(s) 1.8.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
SpawnWithItems 2 by LDX for API(s) 1.1.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
MineReset 2.0.3 by Falk for API(s) 1.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvlz2ziW/ldQSqom6RJ1y7LV5a512cpOpuNEazmT2W1OuSASEtnm1QRpW93b//t+7wE8JDud
84d1pSriA/Dwju8dAPlHpwhj1ZkPJ+Pp8fFwNpt2OyrP07wz/6NT7DIMdRY3i6urd1edbidWWsst
0c5lFIkiFVLEKl6rXGzKxCvCNBGB1EuVx6HWeHrxUoCUlFGE1ZswoqV9nXv9LPVuVRGHieovI7lT
+c3NeLQOC0yLQOzMJ+OTP7udLCq3YdKZb2SkVbfjpb4iwSbjARi5hVvkqijzRDwvglA7P2XY2Pkp
bAmwUsWL54mM1csfwXoyHvK6P/n3CL/5x5iJ/R9+4KcJP4kfxH9kMpexyGpmrtsw/l9d5GGyFcyc
103tOn44qplYCddpGvHIzI70+emYn7JyHYXex2xo5P+D55/8hd5PrWKtJ4NG68nQaj0ZtbWejA+0
XrLlxXPrAZpyaJhDC0ymBxNIZyHE8zsZlWbGUctGk9mhjZ629FlRSC+IVVLwquO2/SYnT9pP+n6z
6sW+Kl0jsDgVrkvA7Fr5agIsDeQVufSAtV86zwbixcu5aADruiuV36nc+cnLpQ4uyjh78bLz725n
qxKVy4gAimESHcINe1Nf3UHWdRlGPgJtNJ0A13lapB4QMR/Nuh2ZhTxzOOoNMHOLMJh3Bp/5hwW5
vI3CNa3pzZhDyS6Zd96ESfkgotSTUZDqQox7w0FvcuJMTuDNk6F4NhSry6VYXi0Wl8trcR2U4lLu
xGgohkfzyWg+nYmfV9diNBhOhczjuxlBOAsysJ72jnojPP2uEmjVGeFxYAZvUl1tDQI/yMTP09Dv
1BGtyUirMM4idVYWAT1ZkVvE7p4ZZ70hKBIDaa7JMUv2yCU8Iq6VjDGog3QbhF5GzmCb/lIZFQSV
yHWkIGuRl0glvsogOTHCmE43xUWbEEvKOi1h4PS2YFEqSevV9dnV9fslCPdqrcOCFAiKItPzfh9e
DMp1z0vjfiNpv8UFxliWuSKg65YBGtq+/sPeeF//o8mrV4PBd9P1xvBD5FUCtH5+ucq00ri633CB
yq8kh6he5mlL6TZ1X+0xo6yl9rUqApUr/+a7ad7a3HXtw6XkpGeVXr5bXX94d/Xmoq025Qoo9HMY
RZdponYtdRraoQ8HB8qkWejtKXLy9XrUu7puW4DP0IE8dB7I4gCGTNrXYNSbfRqFw0/o0ML4I3X2
oPARdJJcza9vxiYzgRUWWqNchGg1louWJfbIn/DnG7UlPd5tLs+XC5OWvhdK22K47htorPJPePcp
5Y2ERsD+nmqwQAijF8orTPtn9W8R29qjlsgD5S/+9b2gDFau22zsup8Rj09qe/EvhzVtKQE9TQH/
OSzaibdFPEhB+2ou7tJoBbm/DPN/VWXqjQ/1/BigoeT9/X1PQRJi2ituSauzPE7zVSbvk5ZWLeK+
9waf8N7gG73XbPzt3mspAT3/+Xq5itI939Wkto7Q4NB34T9SHZTy7xd7qh5/vao1Q9dtyfBl+Sj8
lXkEfr9mQdkoQYAvlcyjdi5qiId5+UDT/061DsKTk5NHTu3axPW1eagW4bP8aisMO+8DdH5dqL12
52CgpdXoL+E5/EZ47u/7JaqcRfdypx/FWYvads0IrjnoYJZBGIWZWOE/nHW3361CZMxXW7auK1kk
bULwsGA8gU2r33mpizQ+i1S+F2J75H3wTT8nQX6DYu2tXfdAkK9KldSLXymt2h1PQ9v336Mk8kpG
t98rVdKBMqdNgcDW/p8Bww9pHvkLPyzO8rYWe+R9N0HMm7Uq5A0OpDfPBjhJ78NycSmzy9QnmHwn
7TIVyyxmlq57T5IpSCZzaHsg55eWhpaw/VUso8j5n3OnauqKXKl+LHWBwb19YLZrmV2nF+2zR0XZ
9/rwMGq/p9cLmRWpj9NGs/cnPU5nZ7pVUdCqYs+NQy/L0wzBECo6aj9b1k/iPE024VbQvZubu8kz
Ot//o4zESIzG89FsPpyJ99fnfLynccPOIbOcEhi9XG6KuUAjazqU1pwszYvTyXQ0PiHiFivgZXU6
oKdYPjgZ3+np0zFTOAU5menAYOBTZ0jk+wDaRaEuTtOEno0lnd9Kle/2SbmHRelmQyRfaS8PM+Zj
5BIxUpsoNV1GNUdt53LJ0qSFf7paXP1zcSXeLy/OrheiLy7PXr+9Xrw9e3u+aClF152nSZoDTrwS
OuU7JwrjsDgd0lXLJZEj4MopM18WqhJJJklaJp6yajvSC0J1p+jySVtF7kJ17/jQVWLe6YxXRVF6
72yicBtUFjCGkkkIEfQeLU7XFSGQue+leb17dpfZET/cbEKvjIrdKRvYXEih53WQVQqYR5+yBpAt
Mm7mmGxoWim/NYUNcrF4dfb+zTVRyQ29TGqNZf7pD/wHPcoidbS8U1YKdqvDfmXvb9IcpqkxYqWm
u6L6Sq23iyPCrqAqLDyGbQnJ6S6P0CvAo+1aqi7As7gOkC9FpZyQuRJFoAQOvho/ZCE8ck0h1kqE
iReVSD/4IR7FDfFapTFWbojBIU8tN6orUrp30MRSrHMlb8UuLXPLS4QbAe3CTcg7wD05oB7tiPFb
dV+z6/tqI+EgLe7T5G+FkFmGTkqQCWOo6wETO7oxp2tdo/l9oBJRZttc+mDQcxOCq2E2dxOBmEay
cyKQIEUkk20pt0rQRTkbzUJbh3jme8DwdzYrLT0PlGe12F9IN9A25aqkdx/ehhnytuyl+bZPT/03
cO5Nurl5vXp3czQ+cUY3tA5mrBnNhYvMuHU7tNGHgO9s6H0Bzpu+oHcH5vIYbsploiMEk2+G2Zos
KeTAL1WwS1GyQk+JQCZ+xE6Owdggq9mS3xKAjm668FOKGvO+goSxqcKLUq18I9YZBaAgoFLmsBeT
4i6U4r8oBWEKpyLHjswFZXhauAqwThJOdQpp7C7GVdIyQj4CCFENAATW7mz5GjNRTnyyUzPgQKw1
hGrYLzjpVXygsaBwF4ArEEGirnfC4gjTbYqsRxs+H9AIwpdAlPR9gS7DAI+kBNRuIY3UZc5pSgBu
a0XmgM3Vb6Xklzvb8A5zze34C7sjqsVLMDfbITMrKgUOnLndqnwuUEmw89uS3wkhms70LvGupb4F
4PNbxE+Pxt/DBwzPSkeaFeQp0igQgdm6Kzg1CZvCgNgurBDDaPxOgK2C+ki0uEwQODSFea8YMdAH
sZWnD0ilKDI7UoeRntSikVGNOK83FKD8OguB2BVh8Td6u5XzKl9R1WIQHqwVL6AB3CxGZBHWwbFa
zpkTBaupIhyq/xmlaxiWmgJhyIKLC6WkWG3leldAILEyogx481CTd02gQ6f7kAVjYwsqH7ZIWZJm
u2xCoAVZCjk8YVYbpIhqR+P+gOolYXabQo+UIoNshn22LKSpenM4e3LscrLgzFwg2Uj//7kG1GNV
8g8Ho4mRf6nyMOXsT9jXxNTj/Ge51vgeAguIbJ98yjMc4E+RKQwjNFXIF4gICEnB+DEdjOwohhEn
VIotM83lCkc8gPYmckzU0g7vKGSpoPD03uPJFK227YSxM+VR3dFsE5LVeMOsrRVAwlWZbtQcD6ye
+uWTAlmtx0brrczXMLbjpVFkejhC9JNWZd+RKHaNsGtS6tOSkitcWwrU/xKoedmtYvAANhY3Jo9t
NlUsxg0ee+KdKS/8pJH+0zLya0FCROx9IhrRCST0rhGSQ8EjNHaso3j2imH3KBcxVszqWqlNnsZV
SqO1dtxpZ4GWT6GEdd0hFJ7AT2sd9dJeUCa32tj7DUcbJSAmkmR0cCBthGk+uxwLOeq9NpMcKrnU
OjS8iFXlZhsoJ0dWzovULDt0HyVdakzMsjYHs4ud9h105sTveGiildHaYqHaiAbqIveXrNwkUQX5
ou6UAI3IVJ61LNClU92X1Fai4ABPNn9xAJo+0I6atLVWdQ1CD1HVGovYaoQCP98VxLsrnGELzFRr
eFunqERBWpkemazS1DZuvqmw+CbXWQeatSBamXri7zg6wLynaD0B3PPl+y7WQoI18s996BeBSZEc
3zV7h9nPxcwW4qZEazZMa2pPnPmIp0BGmz56atM1+Ao4sxthS4O/NGkHZF0NW7ya7uzZ4oGCj9oO
GXVNYNPGH8IETRvUAmwUQ5tq6/tlsqwqc9MiU9NBi+5xFnKpP04yxz5yC2T3otPiutzObZH/SQyp
uBtnamrieLhq4DTnsUBVjZ1rXYEy0rRlWvRxiCtKAKa/9Yxpkdd83cCuOkvtdemqatlIbChizic8
1aKLtGV/e7BhwQCzSxyzZC5iDG1t9w59+MaBpL2juzCTk+QefyROOv8Ure1hy+KxNByi7Llnb99d
L+aCky7+eSWOMgmOMsyI316T51g8u3MtXu3hsz1neejakUisrgwirkiQhEBTEHBGA1tBKJOZwkQo
oqMl0W01skG/T65S2NRGpCmEa6lVa68XQ4TJE5t0xQgDw6cGVOH1XnLIatUWgsFwTZzpHGNvOoRC
WjL7UeE3juQTY3OUpDTARw5qVCgZmAtaw9vyaVC0l7wZRGdxWibt7K9td1TJQNITM5c/pWG+SDAf
XypzUH0juuGxX3LE8OTp1YytRJkz21oZbmu1oTTE9xWUrsgLNVdzi9HKeybtreQdKi4d+0I6mio6
6mQ7ewy3hajuZjhLbPhar8qJNodtyoinpRpAdSg+Q8/UET7v5HT2BS7AtjLVrykdO0xkaPociD6D
I0hTdan1r9OIcQYZtHLGpXwQ8tAuOHB4XBwaOOz5YkArr3CSL3VrlXWDtMJxhJqVFnU0H50K5SO6
LLK3T418ONUqafbge5dHgjenqEr23mPhbfK7lyGfh3H2LZX1r13PQc90R8NZc3H8VdyyNCsjy83+
prp0wNhNOCQdWI+ENpdiDuMImk+oaYPDE0JDTR3a5EC3UXNhOrvKpTBRUmbodEy7ZwDJqcN0GZYX
uMxold1Q2yMtFKGNaiLTZLwOgXwzxV6EmQPx3OQiOrrTN2LCUE2BtSAx6LVtfJ3aCNcOXabsU+pi
skfNgixMNmmDA/rIa2627LVu19AFsXxJmuxi6vE5QjTsq2tB6dBih0UzzAIDbFLI7Ra1x57E6ysO
ahDpS7nbp7Ux8hA7/ZQ8ZC+DZXbx4WpgwozOjQPyxLGVuWn/mJpm+mBLeuXzxIZRiFxudF48SKpl
5oF6AaDV3v/Phf3BQ4CSLlIA5xf66Uj6YpAI/yaOJsdUJb59b8glvWrFzXmouo3lg85T15B8buQS
obkaU+DEKNIhBLXlsyU678oC8C9Bl7cUGBN+qnebi1dvzq7nox9n3enJw7A7fhh3Rz8Of/RR5kxO
eEHvSzyK39PjgdgCPdo8TaYv+aJWPRQqIYPw+8BzZPnWB4DkoNYjku22/l4382iqfdC/RWGhxuYz
Rcd8FPm7+W7RfPe49tAzBM3HvjICLmXeEMz3yNVTSW/G7cMmjAAiZj00H+Vsiqwe3cbN7wCxYd6G
YdKvun59Th8XxmtzK1lPRr+1y4pGg0KSQH5L3dXyDe9KvzMPfVKzdgeF+dtI+0tMeyQdaS4ceuky
GkwHY/x8/hp+24xnYyWnvj+djo9nR8PJ4EgeD0YjOVkfy/FsMhker0eTgRLPsdMyILPwu0neONXh
Q2N0ew62E4ak6JXa2EMcqLzfsZpuPIkucIJtB5vZzJsdHx9Np9h6fDIaq/FgfTI78X3eTwdx2phQ
c2DpfU1DY3xMLtJblSCL5zXlg5K3udoYQ/Hb4p3kC396jU8Tfg+z6gPYSefPP/8P5NjYwA==
===END CRASH DUMP===

**Comment by 64FF00** [comment]
Duplicated issue

**Comment by alexisoko** [comment]
What is it !

**Comment by alexisoko** [comment]
64FF00 plz tell me how tp fix that !!!!
