### ISSUE TITLE
Crash after about 10 min latest dev mcpe 0.11.1

### ISSUE THREAD

**Issue by 111111111111111111111111** [PocketMine/PocketMine-MP#3251]
These are a all of the crashes i have experienced in latest build.

Open the png as text i cant copy / paste
![crashdump_sat_jul_4-08 53 07-utc_2015 log](https://cloud.githubusercontent.com/assets/8365821/8507331/4065e63e-2236-11e5-9762-665d1f5d6759.png)
![crashdump_thu_jul_2-14 31 28-utc_2015 log](https://cloud.githubusercontent.com/assets/8365821/8507334/63871a02-2236-11e5-86a3-f22707b10a46.png)

**Comment by qwefqwfqwefqwef** [comment]
No picture

**Comment by 111111111111111111111111** [comment]
Sry
