### ISSUE TITLE
TextFormat::RESET doesn't work properly

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3253]
TextFormat::RESET doesn't reset color in chat window.

**Comment by RandomAltThing** [comment]
Obviously thats not what it is for. To reset it to white do §r§f or TextFormat::RESET. TextFormat::WHITE

**Comment by Creeperface01** [comment]
I know but it is bug look 
![screenshot_2015-07-04-21-49-36](https://cloud.githubusercontent.com/assets/10363500/8509271/caf84e22-229a-11e5-9ed2-10083063d507.png)
![screenshot_2015-07-04-21-49-47](https://cloud.githubusercontent.com/assets/10363500/8509272/d0811004-229a-11e5-9840-d95672070354.png)

**Comment by Creeperface01** [comment]
But maybe MCPE bug

**Comment by RandomAltThing** [comment]
Its not a bug. If it is, its an mcpe bug. Just use common sense and after the TextFormat::RESET put TextFormat::COLOTOFTEXT

**Comment by Intyre** [comment]
This is not a PocketMine bug.
Please report it on http://bugs.mojang.com
