### ISSUE TITLE
Suddenly ends with segmentation fault

### ISSUE THREAD

**Issue by tiNsLeY799** [PocketMine/PocketMine-MP#3256]
While the server runs it suddenly (more unexpectedly).it suddenly stops with no warning or even notice that it is stopping. Even as people are online, its as though it just stops and it isn't a crash either.

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
