### ISSUE TITLE
Why my world didn't have any animals.:(

### ISSUE THREAD

**Issue by Playhi** [PocketMine/PocketMine-MP#3257]
Excuse me,
Do you know what can i do to let my world have some animals?
Thank you!

Server version: build 1254(1.5dev)
System:Windows 7 64bit

More ,that's my email address:000902play@gmail.com

**Comment by Intyre** [comment]
You can't. Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.

**Comment by Playhi** [comment]
Thank you,I'm sorry.
