### ISSUE TITLE
Grass block top is black on the worlds from mc pc version

### ISSUE THREAD

**Issue by ingvaras** [PocketMine/PocketMine-MP#3262]
When i put world from minecraft pc version into pocketmine world folder and try to run it, the world loads and all the blocks have good textures, except the grass block. How should i fix it?

**Comment by tiNsLeY799** [comment]
Since you've ported it from PC, the grass will appear black simply because the world does not have the "grass colors" on file so therefore, it appears back. Anvil worlds won't this do this, but it is a lot slower and takes a long time to load.

**Comment by ingvaras** [comment]
I think that it is already anvil type, because files in region folder have the ending .mca? Is there a way to convert to .mcr type?

**Comment by tiNsLeY799** [comment]
My best suggestion is to use @Black_Mantha's converter on the Minecraft
Forums or just click this link to see the thread.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1264128-anvil-to-mcregion-converter-v1-0

**Comment by ingvaras** [comment]
Thanks for quick and informative support
