### ISSUE TITLE
Urgent: Player is banned after respawn

### ISSUE THREAD

**Issue by RandomAltThing** [PocketMine/PocketMine-MP#3263]
On my private test server, I have a plugin that I made so when you /lobby it teleports you to the default world spawn (it teleported me in the air, but that's not my problem). I fell down and died then hit respawn and got kicked for "You are banned". I removed PlayerQuitEvent from my plugin but it still does it, but with no error this time.

Console:
<pre>
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [20:33:18] [Server thread/INFO]: Disabling DevTools v1.10.0
[Server] [20:33:18] [Server thread/INFO]: Disabling ImportMap v2.2-1.5upd1
[Server] [20:33:18] [Server thread/INFO]: [ImportMap] ImportMap Unloaded!
[Server] [20:33:18] [Server thread/INFO]: Disabling FastTransfer v1.0.2
[Server] [20:33:18] [Server thread/INFO]: Disabling SimpleAuth v1.7.1
[Server] [20:33:18] [Server thread/INFO]: Disabling SimpleAuthHelper v1.2.3
[Server] [20:33:18] [Server thread/INFO]: Disabling AutoBotPE v1
[Server] [20:33:18] [Server thread/INFO]: Disabling MinepixelHub v1
[Server] [20:33:18] [Server thread/INFO]: Unloading level "world"
[Server] [20:33:19] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [20:33:19] [Server thread/INFO]: Loading server properties...
[Server] [20:33:19] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [20:33:19] [Server thread/INFO]: Starting Minecraft: PE server version v0.11.0 alpha
[Server] [20:33:19] [Server thread/NOTICE]: The memory-limit setting has been deprecated.
[Server] [20:33:19] [Server thread/NOTICE]: There are new memory settings on pocketmine.yml to tune memory and events.
[Server] [20:33:19] [Server thread/NOTICE]: You can also reduce the amount of threads and chunks loaded control the memory usage.
[Server] [20:33:19] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [20:33:20] [Server thread/INFO]: This server is running PocketMine-MP version 1.5dev-1254 "活発(Kappatsu)フグ(Fugu)" (API 1.12.0)
[Server] [20:33:20] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [20:33:24] [Server thread/INFO]: Stopping other threads
[Server] [20:33:24] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [20:33:24] [Server thread/INFO]: Loading ImportMap v2.2-1.5upd1
[Server] [20:33:24] [Server thread/INFO]: Loading FastTransfer v1.0.2
[Server] [20:33:24] [Server thread/INFO]: Loading SimpleAuth v1.7.1
[Server] [20:33:24] [Server thread/INFO]: Loading SimpleAuthHelper v1.2.3
[Server] [20:33:25] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [20:33:25] [Server thread/INFO]: Loading source plugin AutoBotPE v1
[Server] [20:33:25] [Server thread/INFO]: Loading source plugin MinepixelHub v1
[Server] [20:33:25] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [20:33:25] [Server thread/INFO]: Enabling FastTransfer v1.0.2
[Server] [20:33:25] [Server thread/INFO]: Enabling SimpleAuth v1.7.1
[Server] [20:33:25] [Server thread/INFO]: [SimpleAuth] Everything loaded!
[Server] [20:33:25] [Server thread/INFO]: Enabling AutoBotPE v1
[Server] [20:33:25] [Server thread/INFO]: Enabling MinepixelHub v1
[Server] [20:33:25] [Server thread/INFO]: [MinepixelHub] MinepixelHub Enabled
[Server] [20:33:25] [Server thread/INFO]: Preparing level "world"
[Server] [20:33:25] [Server thread/INFO]: Enabling ImportMap v2.2-1.5upd1
[Server] [20:33:25] [Server thread/INFO]: Enabling SimpleAuthHelper v1.2.3
[Server] [20:33:28] [Server thread/INFO]: Starting GS4 status listener
[Server] [20:33:28] [Server thread/INFO]: Setting query port to 19132
[Server] [20:33:28] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [20:33:28] [Server thread/INFO]: Default game type: Creative Mode
[Server] [20:33:28] [Server thread/INFO]: Done (10.262s)! For help, type "help" or "?"
[Server] [20:33:36] [Server thread/NOTICE]: Player data not found for "thediamondyt7h", creating new profile
[Server] [20:33:36] [Server thread/INFO]: TheDiamondYT7h[/192.168.0.7:35029] logged in with entity id 3 at (world, 128, 4, 128)
[Server] [20:33:36] [Server thread/INFO]: There are 1/20 players online:
[Server] [20:33:36] [Server thread/INFO]: TheDiamondYT7h
[Server] [20:33:42] [Server thread/WARNING]: Can't keep up! Is the server overloaded?
[Server] [20:33:48] [Server thread/INFO]: [Lobby] TheDiamondYT7h > hi
[Server] [20:33:54] [Server thread/INFO]: TheDiamondYT7h has just earned the achievement Getting Wood
>gamemode 0 thedi
[Server] [20:34:12] [Server thread/INFO]: [CONSOLE: Set TheDiamondYT7h's game mode to Survival Mode]
[Server] [20:34:18] [Server thread/INFO]: 
[Server] [20:34:20] [Server thread/INFO]: TheDiamondYT7h left the game
[Server] [20:34:20] [Server thread/INFO]: TheDiamondYT7h[/192.168.0.7:35029] logged out due to Kicked by admin. Reason: You have been banned
[Server] [20:34:20] [Server thread/INFO]: There are 0/20 players online:
[Server] [20:34:20] [Server thread/INFO]: 
</pre>

This is urgent as you can hardly run  a server with this bug.

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue).
