### ISSUE TITLE
Can't run Pocketmine on Android in background

### ISSUE THREAD

**Issue by Wh04m1** [PocketMine/PocketMine-MP#3264]
Hello there,
I recently downloaded Pocketmine MP for my Android Phone and when I tried to join my own server, Pocketmine closed unexpectedly.

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue).

**Comment by RandomAltThing** [comment]
You need to post an error. Also, @Intyre stop just posting that and give a short explanation as to why you closed the issue.
