### ISSUE TITLE
Farming/Mob Issue

### ISSUE THREAD

**Issue by Chiwaii** [PocketMine/PocketMine-MP#3276]
I cant seem to grow any crops... even after surrounding a planted wheat seed with water in sunlight for four days nothing has changed from since it was first planted.

Also, i have the difficulty on hard in the server app and no monsters have shown up.

I have a little over two and a half gigabytes of ram dedicated to this server, and everything else works fine except for the 0 fps lag spikes... i run the server on the same device i play on as a computer is not an option....

Anyways, could someone help me?

**Comment by tiNsLeY799** [comment]
Although I don't work with Pocketmine I can tell you quite a few things..
-Mob spawning has not been implemented yet, along with their AIs so even if
you spawned them they wouldn't do anything.
-Farming doesn't work correctly yet,  but there is a plugin that can help
you with that.
-As for the spikes, I can't tell you much so I'm not entirely useful
because I run my server on a desktop so I get those oftenly.

**Comment by Chiwaii** [comment]
Ok thanks... Which plugin helps with farming and does it work with the 0.11 update?

**Comment by Chiwaii** [comment]
Scratch that.... does it work with the most recent type of server?

**Comment by tiNsLeY799** [comment]
Yes it does.

**Comment by tiNsLeY799** [comment]
Are you using development or build?

**Comment by Chiwaii** [comment]
The soft version...? (Whats the name of the plugin?)

**Comment by tiNsLeY799** [comment]
(Ah, the plugin is http://forums.pocketmine.net/plugins/farms.789/ )
It works with development 1.4

**Comment by Chiwaii** [comment]
... umm... im a total noob at pocketmine versions... im guessing the dev 1.4 is the developer option whenbyou decide if you pick soft, medium and hard.... correct?

**Comment by Chiwaii** [comment]
Just checked.... soft is dev 1.5.1 will it work with thqt

**Comment by PEMapModder** [comment]
Do you have chunk-ticking enabled in pocketmine.yml?

**Comment by Chiwaii** [comment]
I cant seem to access any .yml files. Also, for somerea so n the farms plugin isnt working... in the onsole it says WARNING a plugin attempted a depreciated Callbacktask (callback#hm/Farms/Farms::Farms

Recently, i started up the server (so i could write the line down exactly) and it said 
zend_mm_heap corrupte and it shut down the server. I honestly couldnt care less about the lag spikes, its just i want something i can grow f or a roleplay :)

**Comment by PEMapModder** [comment]
@Chiwaii we don't support plugins here.

**Comment by Chiwaii** [comment]
Soryy...
