### ISSUE TITLE
server doesn't work

### ISSUE THREAD

**Issue by kuroKun** [PocketMine/PocketMine-MP#3281]
so I downloaded PocketMine-MP for Android and then downloaded the soft version and did everything else then started my server but I wanted to change some things in server properties so i did but when I went to minecraft nothing changed I tried again and tried stopping the server and starting it again I tried reinstalling but nothing changed

**Comment by kuroKun** [comment]
[PocketMine] Server was stopped.
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 23:32:25 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 23:32:25 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 23:32:25 [INFO] Loading pocketmine.yml...
[Server] 23:32:25 [INFO] Loading server properties...
[Server] 23:32:25 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 23:32:25 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 23:32:25 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 23:32:26 [ERROR] Could not load plugin 'Volt': API version not compatible
[Server] 23:32:31 [INFO] Preparing level "world"
[Server] 23:32:31 [INFO] Starting GS4 status listener
[Server] 23:32:31 [INFO] Setting query port to 19132
[Server] 23:32:31 [INFO] Query running on 0.0.0.0:19132
[Server] 23:32:31 [WARNING] RuntimeException: "mt_rand(): max(-1) is smaller than min(0)" (E_WARNING) in "/src/pocketmine/scheduler/AsyncPool" at line 61
[Server] 23:32:31 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 23:32:31 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Tue_Jul_14-23.32.31-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 23:32:37 [INFO] Unloading level "world"

**Comment by kuroKun** [comment]
I also tried running the stable version instead of the soft version but I didn't work but that's what I am running right now

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
