### ISSUE TITLE
block break bug

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3282]
when player break a block he touch block with id 0 meta 0 x 0 y 0 z 0 etc

**Comment by TahaTheHacker** [comment]
Huh friend ik how to break them... not fixing it just hold an empty slot or anything that doesn't make you break fast and start mining , then hold a pickaxe (if yu are breaking stone) but hold it without stopping mining then it will break instantly thanks!

**Comment by ijkfvjkjfdvn** [comment]
lol
