### ISSUE TITLE
Coordinates Mapping issue

### ISSUE THREAD

**Issue by iVertx** [PocketMine/PocketMine-MP#3283]
hi, well, I've been seen this issue for months but only now it really interferred on my server gameplay...

well, for a unknown reason, PocketMine (or mcpe, idk) are mapping wrongly the coordinates where the block are located, not exactly wrongly but instead of the center of the  0 67 0 example  coordinate be on the center of the block that are in this location, is on the corner of this block!

a example:
When you teleport to 0 67 0, you are teleported to the corner of this y axis:
![stone](https://cloud.githubusercontent.com/assets/10237969/8731979/1230db08-2bd1-11e5-938d-b261d1be2dfc.png)

instead of teleporting you to the **center** of this y axis:

![stone1](https://cloud.githubusercontent.com/assets/10237969/8732019/423fee9c-2bd1-11e5-8f0d-b0826b6d9b7d.png)

this bug affected directly my TNTRun minigame, due to this issue, PlayerMoveEvent getTo() doesn't work properly, and the player can stop between two blocks and wait in there, because for pocketmine the player still on another block... it's complicated to explain, but it can easly be reproduced...

**Comment by iVertx** [comment]
a better explaination

The PocketMine (or mcpe) coordinates is a bit "displaced" in relation with the blocks in the world, like this:
![overlapping_squares](https://cloud.githubusercontent.com/assets/10237969/8738614/34f4e44a-2c08-11e5-8490-6aee1c03c3eb.png)

this way, the players can stand above four blocks at same time, but for pocketmine the player will be  above one block, that affect directly minigames that need to know player's **exact** location for doing things like removing player's ground...

**Comment by PEMapModder** [comment]
Add 0.5 to x and z. This is how MCPE handles it.

**Comment by iVertx** [comment]
oh, so this is not a pm issue, and is not a issue...
but it's hard for a recently joined plugin developer to 'discover' these small things by thenself...

anyway I think we need to take 0.5 instead of add, atleast this way my project work

**Comment by PEMapModder** [comment]
It is for the convenience in code. Say, if a player is standing at `3.*, 4.*, 5.*`, we can directly tell that he is standing in the block at `3, 4, 5`.
