### ISSUE TITLE
Can't break block with wooden pickaxe

### ISSUE THREAD

**Issue by SonyBravia** [PocketMine/PocketMine-MP#3284]
To my players and me that bug is really annoying pls fix it

**Comment by Goobaroo** [comment]
I had the same issue, but I'll provide more information.

Minecraft iOS v0.11.1
PocketMine-MP PocketMine-MP 1.5dev-1257 「活発(Kappatsu)フグ(Fugu)」 implementing API version 1.12.0 for Minecraft: PE v0.11.0 alpha (protocol version 27)

**Comment by SonyBravia** [comment]
ok

**Comment by PEMapModder** [comment]
This issue is duplicated.

**Comment by Goobaroo** [comment]
Can you reference the duplicate?

**Comment by Kanonen** [comment]
FYI, my debug statements are saying that the wooden pickaxe is "air". Here's the debug for selecting the wooden pickaxe:
<code>Item: Air | IsPickaxe Value:</code>
compared to when i selected the stone pickaxe (note the incorrect isPickaxe value, also a bug)
<code>Item: Stone Pickaxe | IsPickaxe Value: 4</code>

**Comment by Kanonen** [comment]
I just crafted another, and this time the debug statement is correct, and I AM able to mine stone. It looks like the bug might be at the point the wooden pickaxe is crafted.
<code>Item: Wooden Pickaxe | IsPickaxe Value: 1</code>

**Comment by iVertx** [comment]
shovels also have this bug when breaking snow blocks, the block breaks instantly but reappear again, 

and Haste effect and anything supposed to instantly break blocks in survival mode aren't working, exept handling an event and setting the block to air, but when you do it, the blocks only update for the player that breaked it, only happens in multi-world..

**Comment by shoghicp** [comment]
Please don't open duplicated issues
