### ISSUE TITLE
Server not started

### ISSUE THREAD

**Issue by archiestridegmail** [PocketMine/PocketMine-MP#3288]
As soon as I start the server it says that there is a fatal error and here is the crash dump:

PocketMine-Soft Crash Dump Sat Jul 18 13:37:59 UTC 2015

Error: Call to undefined method pocketmine\network\RakLibInterface::getUploadUsage()
File: /plugin-698.phar/src/PocketDockConsole/RunCommand
Line: 174
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PocketDockConsole v0.0.11

Code:
[165]                     $this->removePlugins($plugins);
[166]                 }
[167]             break;
[168]         }
[169]     }
[170] 
[171]     public function updateInfo($user = "") {
[172]         $data = array("type" => "data", "data" => array("players" => $this->sendPlayers($user), "bans" => $this->sendNameBans(), "ipbans" => $this->sendIPBans(), "ops" => $this->sendOps(), "plugins" => $this->sendPlugins()));
[173]         $this->getOwner()->thread->jsonStream.= json_encode($data) . "\n";
[174]         $title = "\x1b]0;PocketMine-MP " . $this->getOwner()->getServer()->getPocketMineVersion() . " | Online " . count($this->getOwner()->getServer()->getOnlinePlayers()) . "/" . $this->getOwner()->getServer()->getMaxPlayers() . " | RAM " . round((memory_get_usage() / 1024) / 1024, 2) . "/" . round((memory_get_usage(true) / 1024) / 1024, 2) . " MB | U " . round($this->mainInterface->getUploadUsage() / 1024, 2) . " D " . round($this->mainInterface->getDownloadUsage() / 1024, 2) . " kB/s | TPS " . $this->getOwner()->getServer()->getTicksPerSecond() . " | Load " . $this->getOwner()->getServer()->getTickUsage() . "%\x07";
[175]         $this->getOwner()->thread->stuffTitle = $title;
[176]         return true;
[177]     }
[178] 
[179]     public function sendPlugins() {
[180]         foreach($this->getOwner()->getServer()->getPluginManager()->getPlugins() as $plugin){
[181]             $names[] = str_replace(" ", "-", $plugin->getName());
[182]         }
[183]         return $names;
[184]     }

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #245 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20-g0c002e7 #1 SMP PREEMPT Fri May 29 11:50:57 UTC 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
PocketDockConsole 0.0.11 by humerusj for API(s) 1.0.0
SimpleWarp 1.4 by Falk for API(s) 1.0.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNqtWQtv2zgS/iuE28MlB8uRZDt+FC7QbdJeF0nrS9LrAXVR0BJlayOJWpGK4+71v983pCTLcbrI
7m1QNOJwOO8Xmd86Ok5FZ+oN+iPfPz0dTbodURSy6Ex/6+htjq3O+dfzq6sPV51uJxVK8RXBXvMk
YVqyMgtFFGciZKnQaxmyXAa3QqcALRaZ0BtZ3C4WV/z2Il6+y7QoIh6I6XQl9Mc8kTz8SPSOjkE7
ihMifJIn5SrOnNPJuJeveXGiiuBkboie4f/XMlMyESdXZfZapinPQhxNwA0qjAbfux17HIQOzgAx
kKEgxbzTITDYIz/P9TpWzstCpPJOzA0tdfTcElXHL0DDOz195Ox3szN6sLMsBL+1h8atLYs8qSBm
NXKxMh9eBc7LZRIHLCqzQMcyY2Ueci3eZZE8el4qUbAZW3QWnWP2mznmt+g/BybHPi8Kvj1aGD8u
Omz2Eidoa9HpNl8ErfHyhG9FoSywsoQSWTi3cMv3mM4ueXaI9p6n4idsHBmUOH8U6d18hyLzw/0P
ebVZ2fwRYaxTjo+tO0b9tuYWD+H1YZOJ4ujYeanXcELovPxFyexa4zvtzRgtvoqM4uHIWOuY9cic
i2zRsVQHe1RjnQhr8MW9t/zivrDRdYnAcy7ngOP4I7zxfS2Ku2axO/Vv2BNePbJ82X/Zh4yi2FIK
ZJnpoyfQs4dq9xxbYidPleaS3zdHazGuXl1aGQrIEB4dpUiEYvsV2F9Lm6rshHmuP6h/d5nfZvuj
Y7ooxQ+PssufwPpjm3ElfsrjrCkbRui9snFA6OxJNM7kJvs9Krc/nSgIdDO/frJnb+LgVs1FcS0C
CdaNPS/A5g8RqWWi839DtLmjOiKHT4tzpcsouqkC1kauPd8uW4XQZZEx8ordHO0Vo3FdjCY/KEZ7
iWgr0Nht0Y8khAnWT4lhS+aSZ9B7H0akuWJV9T22XLwHJfZ5hqqjPn+BskoXXwuBIhYIFDNmq5xD
vyoShjZVqaOqdoz9h1V53D+0kmVhDwwaO6HX6AKsOtPPnWcuOzqe7vU+q6PzMii4Wp+VaY4m96Xb
WQmYgSfUhO5sCQBBrzcMxR3oL8s4CTtTfzBEIyukloEEqj/qdngeG0TP77lAXMUaS/eJPzhQ8Nsk
XtKZ3shQKEkprC/irLxniQx4spZKs37Pc3u+66zcwHV9MWLPPHaNEje/Oj+/nN+wN0XMLvmW+RPm
edOhOx2O2Meb18x3vSEaSXo3SkA9X+egPeyd9nysviFasPSxdO3mV6lq3gCYBVp5IeOw0/RwRUY6
7OIAVqI/1uF3RnV7bs/zAOIlBpNCkZ/WZSqKUv1CnjAW/QyTApHWIuPLREBOSopuJxQ5pKZT2FMy
0mdtANWUxyRYLC5pByMJ8p4QPlzffPpwdXEG0EYsVaxJ8LXWuZqenMCL63LZC2T6yIRzqB0scx2n
eSI+8SJv2aEFbBnA6w32dH/Dk9u/Sm9lOG7AEYHe5v57amdlkkCFqgfKTGwPfGmhbS8OyIv7TqT2
iayKUNF/nr/H3gNAW0fv/3auEWmx2Jfvj3p3X8KTNjGyCEqliMrkOuebrG2TPXjLKv4D116c/WdP
674xGQLgzysPklC6LcCTQrvy8XW8yuay0LbQNWHaALt7xc8zRaKlz2SSCJkFa56tDvT6k/o0BCcT
Ctlakj+dry0RT1qKNfH9tuRFeBDfFtrW3of2vx/ff1U475OtI7qW6C+JaEPspPOdSjgvoDh2a6lM
O+yhqeWi0LGgiv9s3qwYalwUrxhdAhfFInt2zTX7uUyYN2Zef9ofTYenTZshBEvPIevOzjXcgN4T
rGPR2svhkpk38fo+AVecZtJQzFxapfzeqW47M99AFMW4Q01XmBFn5p0SeLOGCZJY6ZmMIgJY0zu/
lqLYzmTWAhWY/CpIKFRQxLmhY+VSLC/iO1zgmJXOCCF1OFtvEtkSmq5qs0wWKWKTUMwc7SRxGkMX
f3xJwIQr7djrYC0VzzKMvBhvrVIOJ553IhWZVpVMd7HYOCE04cCbTcypJJEbJ0ri1VpXWNYMPIsh
gNqDpXJZA3AtDwNMeDX3/C6vFY+jKA7KRG9nfWN1M+5oWThKaB1nKzUzGkC2xDpvI4sk3MGUEOHM
G7hDzx+N3R3c2OXs/M2rjxc3BCVj93KuFM6Hs3+YHyhUaukoficqcYz3nLb7MJjCSk0wVFAaSprZ
rbdNE4pORqUBdzEKzBJK0NxL8UnDLWvd/66RcIhYdrMWitxr9UQ8CqbXgqHKK3wgngPykmZLweIs
SMpQhPhgB5lBtK5lipMREXhIU/FIdJnETqGIpH1kYFtZFhUtFkcM2sVRbDjAUwViOtnicpvVpKYL
cF6XOpTkWvusM8W4bMdWFiRSiRDX3Yw9e0VRwsiIOMiq2YzdxZz9i5IAKCYZnGpnam4VdPB6jXOc
LEjjC6u4sM1aIFsrQqxUMA8KGEREPIfs1fxd9ZQEQ7Q2HIi1hFA78ucm7Wo6GB8ZxSTyTMJLJOpy
i/MRRzQCvUrSZrehw8M7yojQCZA0O/JlnuUOPI0hJzToERLCqkWlFfxktk1lqXDtQGzAOIGiB7EA
3kCWm1svLhBUhEgRujA5pbVyrcD7Ml3C1nDzK7XNghuubhm9l9ETDLY/vbp6/+792ykCK1ZsEycJ
ORPkERGrRC55wmx5sMy6bFlqFmuQyP5uooxcZmOM4lBLNKgeKUzMnIrRlHkUFqFYliuKiWfvIvaS
eV1DiFgqcqLZrh2oaoqVY3HK5KghVbtFsROyS0maBPahromMXa7vYvEZsqf2FiVYinwxSWNQK/UR
KzZ6rJFDEyDmiGOPTFmKrRUytVLF9EcSFNGjFYsKmSL02vRhWkpK3WIPL+pDaZD91CSN4z7cnFdu
wb+gRH5lyC9DyEzDVHeNeBXnRrwqiBaYHMrs1qGooOAyaZbSqw9Fg9lTFDJGlqpPMZQHhii7BXJO
nQKflclfyxRpomiksPYiS4XWVBWLimiP/RPF3jweppQsr+cfuziiFFvCQ5s41GsbTdZtNVWncvD4
x4Jy8+bC6NZfSQxcarMWacr84elOcRK+VvyS3zP+kCbyNABvUVE80Nulk1c8jJGAu1OVELySwHjS
nqRfTmHwp2zwx5xo+mPVcNWuEASJ4FYc02EOnFv1PpjPqPlpLahmk0xFaRNoh0HRxRl1T1EYt5vH
HIZGIy0qDXEVlIi93Z00mUHZTl5cJbEO1ttHTtnyYJATvjLeJ0IfFQWHthUGzo8wW7CmaxvToAAj
gRFGxhiUVdX42a3SJIxt6W6pU8mf8i3kQneyhWphyr1jClCroCIAeocRADtVBEUT+uh7GVxEDfgR
QntZ0XghmNqtWIZOnBkEOPHUdQnHrBzsEpKdehwz7lCUEAoMlaGKFg2UEo7GDJoyDBlCMq3DoYDI
ynzKJpa4nZvM7GZqXE0LVEZ0qmJIRIe03HBi1AANjKfLGAFhUaoBx3aVad2LmHliqnuNMU6VPXBt
0/nCpu+YVkQv3/uQphrvQfN1HmNo2hmZHommlmWvNTNlQjfy2UwxJn3IG6XE7k6twkXmVF2kQbFQ
me8EsSw3m81jDJMY/dC2kPN7TnlrF9S3EJ7VTWvKqg+zBdcpLeGoz/TpYAzuMgJ8IYpmIG16Unv6
MskjQaiIQ9FOYEmTl350mDNziZmzlWkflG0pukoMQave1hLdcDUCmC9G0zAFoilYO25T9ubi1c3U
fzHqDif3Xrd/3+/6L7wXITLVJuCRLoQwf0aYjV22greUXQ2Gx2bcFfdaZGQQ88r2GtWg9V5HDmot
UZJWnakJAMzJAaFWC/Ur6o3o22dFx75hfrPvjPadchmg7a0b/IAnCCpe7AD2T4z1qiySZoExDUFk
SHueIRbpvNldpbvvNWLRPCQQEv1lxyx8c69Ol0oXMHqDjAFhm+udBrgOheaq3qh7Pb8wXOk7D9AT
dme3UNg8ZVZfbGgeGUlz5tDd1HeHbh+fz9/Bb1F/1Bd8GIbDYX88OsWt5pSPXd/ng+WY90eDgTde
+gNXsOfgNF+TWchslrFU8f3O6LaeqgrBI0WvRJTYqyqght9YDKOAY2wZgK0bjUbBaDw+HQ7Buj/x
+6LvLiejSRgafmqdyp0JlUksta9pbI0PZC1vRRZ/q90ByCdU9UJE1lC9ISBbbq5NXvWg8S3O6wfr
Qef79/8BSSMOJg==
===END CRASH DUMP===

**Comment by qwefqwfqwefqwef** [comment]
/plugin-698.phar/src/PocketDockConsole/RunCommand

**Comment by PEMapModder** [comment]
Read:
> THIS CRASH WAS CAUSED BY A PLUGIN

Please read the [contribution guidelines](http://lgpe.co/pc) before creating an issue. We do not support plugins here.
