### ISSUE TITLE
   error: Call to a member function hasPermission() on null in phar:///root/PocketMine-MP.phar

### ISSUE THREAD

**Issue by hafizhcyber** [PocketMine/PocketMine-MP#3292]
error: Call to a member function hasPermission() on null in phar:///root/PocketMine-MP.phar/src/pocketmine/Player_
t.php on line 439
5:01] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash d
 
5:01] [Server thread/EMERGENCY]: Please upload the "/root/CrashDump_Mon_Jul_20-02.55.01-UTC_2015.log" file to the C
Archive and submit the link to the Bug Reporting page. Give as much info as you can.
5:02] [Server thread/INFO]: Disabling EconomyJob v2.0.3
5:02] [Server thread/INFO]: Disabling WorldEditArt v1.0.0_beta_dev_#048

**Comment by PEMapModder** [comment]
This issue is duplicated.

**Comment by Creeperface01** [comment]
disable kick event
