### ISSUE TITLE
Unable to change chat style (you cannot put any tags like Owner in there with any plugin

### ISSUE THREAD

**Issue by TahaTheHacker** [PocketMine/PocketMine-MP#3294]
Help guys help!!!! i can't change the chat style and add Tags like Owner, Mod , Admin...
i use custom chat and pure chat.. but doesn't work ;( i think pocket mine cannot change chat any way it stays the same

**Comment by TahaTheHacker** [comment]
Please HELP!!!!!!!!

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
