### ISSUE TITLE
Jumping in spectator mode

### ISSUE THREAD

**Issue by JoahDave** [PocketMine/PocketMine-MP#3299]
When you are in spectator mode and you die, pressing the jump button will cause you to jump upwards, and walking the lower half of your body into a block will cause auto jump to trigger.

Exact steps I took:
<ul>
<li>Quit from the server in creative mode</li>
<li>Join the server</li>
<li>Change to spectator mode</li>
<li>Run /kill to die whilst in spectator mode</li>
<li>Now this bug is present. Try flying down to ground level wand walking towards something that would cause auto jump if you were in any other game mode.</li>
</ul>

**Comment by PEMapModder** [comment]
This is a client-side issue.

**Comment by JoahDave** [comment]
Can someone check if changing into creative and then back to spectator mode after respawning cancels it out? (I currently can't)

**Comment by PEMapModder** [comment]
PocketMine sends the settings correctly. It is just MCPE.

**Comment by JoahDave** [comment]
Ok then, not the fault of PocketMine. Thank you for your time!
