### ISSUE TITLE
player should not be on fire if not in fire or lava in creative

### ISSUE THREAD

**Issue by jose-vm** [PocketMine/PocketMine-MP#3302]
The burn effect isn't disabled for the player in Creative mode, no matter if you leave the fire area.

**Comment by Pub4Game** [comment]
This is a bug of the game!

**Comment by Pub4Game** [comment]
This is a bug of the game,not the kernel, please close the issue

**Comment by jose-vm** [comment]
Nope, on a local world you can't burn.

**Comment by Pub4Game** [comment]
I just checked in the world. I have a player burns.

**Comment by jose-vm** [comment]
leave the fire. are you still burning? no, right? that's the bug.

**Comment by jose-vm** [comment]
In PocketMine, no matter if you leave the fire area, you still have the burn effect.

**Comment by Pub4Game** [comment]
Ah, Yes, indeed this is a bug

**Comment by Pub4Game** [comment]
I have not understood You correctly

**Comment by tiNsLeY799** [comment]
Nothing in Pocketmine (item wise) burns. You do, but even if the fire is
put out, the Server thinks it's still there when it's not

**Comment by jose-vm** [comment]
How does that help my issue?

**Comment by tiNsLeY799** [comment]
So basically, you're saying that you burn in Pocketmine-MP? That's normal.
Very normal.

**Comment by tiNsLeY799** [comment]
And in creative? Then yes. It happens. I don't really see an issue here.

**Comment by jose-vm** [comment]
Yeah, but that's your opinion, not the answer to this issue.

**Comment by PEMapModder** [comment]
The issue is, "player should not be on fire if not in fire or lava in creative".

**Comment by tiNsLeY799** [comment]
Ah, I see. I tried helping them but I didn't understand too well.
