### ISSUE TITLE
Playing sound while Keyboard opened

### ISSUE THREAD

**Issue by BukkitPlaysMC** [PocketMine/PocketMine-MP#3303]
When adding a sound to the level using Level::addSound(); and a Player has his Chat and Keyboard(!) opened, they sound won't play for this Player. When only the chat is opened, it does play it.

**Comment by hoyinm14mc** [comment]
See what I did to solve this in AuthMePE
github.com/cybercube-hk/authmepe

**Comment by shoghicp** [comment]
This is MCPE, not PocketMine
