### ISSUE TITLE
pls fix file armor.php

### ISSUE THREAD

**Issue by SkygridRex** [PocketMine/PocketMine-MP#3306]
hello, I see a player to have armor and suffer some kind of damage is not worn, and the problem is in the armor.php file. they can not use the code base item.php to fix that?

**Comment by SkygridRex** [comment]
lol eres malo shogui solo queria q corrigiesen ese error para dar una mejor experiencia de pocketmine a los clientes

**Comment by sithsiri** [comment]
@SkygridRex Huh? Confused...
