### ISSUE TITLE
Zombies, skins, light + creative inventory bug!

### ISSUE THREAD

**Issue by xFinnZ** [PocketMine/PocketMine-MP#3313]
Well i report this bug and its the zombie dont react when u spawn it they are like nothing and so hard to kill him and they Don't attack you :/ that happends to all the mobs and when u try to put it in a spawner doesnt even work...... I hope soon will be fixed now the 2nd is the skins: i join with my normal skin and i change it I SEE MY NEW SKIN BUT other players see my old skin. :/ and last one is light sometimes when you /spawn or a command warp to a pvp arena (example) if there is glowing obsidian or glowstone they don't get light i need to break a block but thats annoying :/ and sometimes there is a dark thing so annoying!!! I can't see anything now the last one is c mode inventory (there is not diamond sword, all the egg spawners etc PS: I don't know if someone posted it yet I'm new and I'm just reporting.

**Comment by tiNsLeY799** [comment]
I don't work with Pocketmine but I can answer your questions.
1) Zombies don't have any AI meaning they don't do anything but make sounds
and yeah. My tip would be not to spawn them because too many causes a lot
of lag
2) That's just the server using your old info, should be fixed by reloading
the server, also a bug.
3) Those are mapping bugs, and it should be fixed when you either break a
block or a torch
4) That is a bug by Mojang. In creative, those items aren't supposed to be
there so the program displays the incorrdct GUI but Pocketmine doesn't
Also, please note if you're using development or beta you should expect it.

**Comment by xFinnZ** [comment]
Ok ty and i have a leet server that happends (i have unban items) so i spawn a zombie they dont react btw i would love if they spawn and atrack but no 😞 gg thanks alot

**Comment by tiNsLeY799** [comment]
They also haven't implemented mob spawning yet D: Perhaps in the release of
1.5 or 1.6?

**Comment by KnownUnown** [comment]
Mob AI is currently not in the roadmap of forseeable PocketMine releases. Nothing official written down yet.

**Comment by tiNsLeY799** [comment]
Uh oh. Oh well. At least there are mobs.

**Comment by legoboy0215** [comment]
About the skins, delete the players .dat file. That is the only solution I think.

**Comment by iksaku** [comment]
Pfff, player skin can be changed each time you join a server, no need to delete the "{name}.dat" file

**Comment by thebigsmileXD** [comment]
For the skin fix i have this as onJoin event:
```php
$event->getPlayer()->setSkin($event->getPlayer()->getSkinData(),$event->getPlayer()->isSkinSlim());
```

**Comment by SkygridRex** [comment]
You dont need {name}.dat you most reload your server

**Comment by SkygridRex** [comment]
@thebigsmileXD i think your code realy doesn't for the people have a skin based in steve

**Comment by thebigsmileXD** [comment]
@SkygridRex Reloading does not fix it. Many people complained about that.
A skin based in Steve? You mean, if the player has not slim arms?
isSkinSlim is checking, if the player has the slim arm model and returns false if its Steve-based.

**Comment by thebigsmileXD** [comment]
Created a fix for entity damage bug:


	public function onSpawn(EntitySpawnEvent $event){
		$entity = $event->getEntity();
		if(!$entity instanceof Living){
			$entity->setDataFlag(Entity::DATA_FLAGS, Entity::DATA_NO_AI, true);
			}
		}
	}
