### ISSUE TITLE
Pocketmine Developer issue on Multicraft

### ISSUE THREAD

**Issue by stxyzth** [PocketMine/PocketMine-MP#3317]
So as of the 0.11.0 update and since using the developer version of pocketmine, it seems that the servers running on the recommended .conf file are not bound to their RAM limits.

I have tested the very latest .conf file that can be obtained here: http://cdn.pocketmine.net/multicraft/pocketmine.phar.conf

The command line from that in which has been tested is:

```
command = "{JAR_DIR}/pocketmine/bin/php5/bin/php" "{JAR}" --memory-limit={MAX_MEMORY}M --disable-ansi --no-wizard --data={SERVER_DIR} --plugins={SERVER_DIR}/plugins --level-name={WORLD} --server-ip={IP} --server-port={PORT} --max-players={MAX_PLAYERS}
```

We have also tried a recommended change from Multicraft themselves to replace "--memory-limit=" with "--memory.main-hard-limit=" yet it did not help either.

A server in which is setup to use only a maximum of 300MB of ram could easily manage to creep up to 20GB.

**Comment by shoghicp** [comment]
The memory management in PocketMine servers has changed.
Also, more threading features are used which are not bound (and can't be bound) to the main memory limit.
This is an issue on pthreads, as it's a separate execution context. You can trigger memory collections on other threads on the pocketmine.yml file
