### ISSUE TITLE
Mobs aren't affected by explosions

### ISSUE THREAD

**Issue by jose-vm** [PocketMine/PocketMine-MP#3318]
Mobs like Zombies or Villagers aren't health affected by explosions.

**Comment by SkygridRex** [comment]
Ok AI wasn't implemented (do you know what is AI?) AI allows all mobs the posibility to move so you are saw the mob in  (for example) x he is in  z

**Comment by matcracker** [comment]
Explosions doesn't need mob's AI, it's only an event...

**Comment by PEMapModder** [comment]
The mobs are not at the position you see. Rejoin server.

**Comment by iamstewpeed** [comment]
Or You can Just Download Clear Lagg Plugin  and do /lagg clearall to remove the Mobs and entity

**Comment by TahaTheHacker** [comment]
@iamstewpeed this is not a forum.

**Comment by PEMapModder** [comment]
Cannot be reproduced.

**Comment by jose-vm** [comment]
This is 7 months old...

**Comment by PEMapModder** [comment]
@jose-vm please do not use the issue tracker as a forum.
