### ISSUE TITLE
Colored text?

### ISSUE THREAD

**Issue by Maxomus** [PocketMine/PocketMine-MP#3320]
On windows (Pc) how do I type colored text I type this (§4exsample) and it turns into this when I save it (Â§4exsample) how do I fix!

**Comment by Creeperface01** [comment]
this is pocketmine bug

**Comment by shoghicp** [comment]
You are using the wrong character, please use the Unicode one.

**Comment by PEMapModder** [comment]
You must type it in UTF-8. Maybe you used another encoding?

This is not a PocketMine issue. PocketMine reads contents using native functions readLine() or fopen("php://stdin"). Your error seems to come from the wrapper you use, not an issue of PocketMine itself.

@creeperface01 if he doesn't think this is a PocketMine issue he wouldn't have reported here.
