### ISSUE TITLE
TNT makes server not responding

### ISSUE THREAD

**Issue by TahaTheHacker** [PocketMine/PocketMine-MP#3322]
SomeTimes when you explode 10 or more TNT it makes the server unresponsibile until when you try stop it it won't stop, even if you KILL it, and if you kill it and start the server it become unable to bind the address and if you go to the server you find it online and if you join it it will just keep locating it , the crash takes like 1/2 days so the server get stopped. please fix this

**Comment by sithsiri** [comment]
On a hunch... try posting your server.properties file

**Comment by sekjun9878** [comment]
From experience, this issue is not reproducible. Please let us know your server specs, test this on a performant server, and reopen if issue persists. Thanks!

**Comment by sithsiri** [comment]
How much ram are you allocating, @TahaTheHacker ?
