### ISSUE TITLE
Sometimes the text of a sign dissapear after write it

### ISSUE THREAD

**Issue by VCraft** [PocketMine/PocketMine-MP#3323]
Sometimes when I write something in a sign, when I close the GUI, the sign is empty.

**Comment by vvzar** [comment]
I confirm this thing!
I suppose this happens when we using Backspace button to erase string and write again.

**Comment by PEMapModder** [comment]
Do you use BlockLauncher? Might be because the client rejects invalid (e.g. too long lines) sign tiles.

**Comment by vvzar** [comment]
I do not use any launcher - clean client 0.11.1

**Comment by PrimusLV** [comment]
Same with me on all builds!

**Comment by sithsiri** [comment]
All builds? What device are you running MCPE on?

**Comment by legoboy0215** [comment]
Me too. Most times when you use too many color codes. It is annoying.

**Comment by thebigsmileXD** [comment]
"I confirm this thing!
I suppose this happens when we using Backspace button to erase string and write again."
I can confirm that.

in the Sign.php:
public function __construct(FullChunk $chunk, Compound $nbt){
		if(!isset($nbt->Text1)){
			$nbt->Text1 = new String("Text1", "");
		}
		if(!isset($nbt->Text2)){
			$nbt->Text2 = new String("Text2", "");
		}
		if(!isset($nbt->Text3)){
			$nbt->Text3 = new String("Text3", "");
		}
		if(!isset($nbt->Text4)){
			$nbt->Text4 = new String("Text4", "");
		}

i guess using !empty() instead of isset() could fix it

**Comment by shoghicp** [comment]
@thebigsmileXD your comment does not make sense. The code is checking for something different.

This is related to the client not having the same id, which should not happen on 1.6

**Comment by shoghicp** [comment]
(it can also be cancelled by plugins or by being in the spawn area)

**Comment by legoboy0215** [comment]
Thanks!!!
