### ISSUE TITLE
Unable to Break Redstone Ore

### ISSUE THREAD

**Issue by Kanonen** [PocketMine/PocketMine-MP#3325]
<b>Pocketmine-MP Build #1258</b>
When attempting to break a redstone ore block with an iron pickaxe, diamond pickaxe, and stone shovel: the redstone ore will disappear for a split second when it is supposed to have 'broken', but then immediately re-appears. No redstone is dropped.

<i>Note: Block I'm attempting to break is "Glowing Redstone Ore"</i>

**Comment by sithsiri** [comment]
This is probably lag.

**Comment by JoahDave** [comment]
Reproduced!
@sithsiri This is not lag.

**Comment by sithsiri** [comment]
Okay. I don't go mining on my server, so I wouldn't know...

**Comment by iksaku** [comment]
@sithsiri Then don't fire *useless* solutions

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP. (Hardness bug, it also existed with several other blocks including netherrack.)
