### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by archiestridegmail** [PocketMine/PocketMine-MP#3327]
PocketMine-mp Wed Jul 29 14:11:53 UTC 2015

Error: RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [99]: Address not available
File: /src/raklib/server/UDPServerSocket
Line: 32
Type: error

Code:
[23] 
[24] class UDPServerSocket{
[25]     /** @var \Logger */
[26]     protected $logger;
[27]     protected $socket;
[28] 
[29]     public function __construct(\ThreadedLogger $logger, $port = 19132, $interface = "0.0.0.0"){
[30]         $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
[31]         //socket_set_option($this->socket, SOL_SOCKET, SO_BROADCAST, 1); //Allow sending broadcast messages
[32]         if(@socket_bind($this->socket, $interface, $port) === \true){
[33]             socket_set_option($this->socket, SOL_SOCKET, SO_REUSEADDR, 0);
[34]             $this->setSendBuffer(1024 * 1024 * 8)->setRecvBuffer(1024 * 1024 * 8);
[35]         }else{
[36]             $logger->critical("**** FAILED TO BIND TO " . $interface . ":" . $port . "!", \true, \true, 0);
[37]             $logger->critical("Perhaps a server is already running on that port?", \true, \true, 0);
[38]             exit(1);
[39]         }
[40]         socket_set_nonblock($this->socket);
[41]     }
[42] 

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(143): pocketmine\network\RakLibInterface->doTick()
#1 /src/pocketmine/Server(2216): pocketmine\network\RakLibInterface->process()
#2 /src/pocketmine/Server(2110): pocketmine\Server->tick()
#3 /src/pocketmine/Server(1986): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#6 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20-g0c002e7 #1 SMP PREEMPT Fri May 29 11:50:57 UTC 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWO1T20Ya/1f2TGYOMpaRZBvbyjhXF0iPO0g4IJMPcYdZSyt7i6xVpRXG7eR/v9+zu7YFhDbt
fbkPdZthX5593l/1a0vLpWhFQa87DAajIOi2Wxmv9GlZqrIV/drS6wLXLWH27dZSVBWf08kVvzuX
M3azKAVPWFzyaiES9rnkd5mcTaeVKO9FOZ1+PLm8NstrFd8J/WPEKrO4nck82T+IWJ3zWSaYVoxO
GE+SEjTY59EIsBO3y5Vm/J7LjGDBRlpn2TuZER/FgpfR4eFhpVUJzg7Fss64Fsmhf3hpKF3IXDSW
3sVlh94cVmV8aLk9tMwePuEVYAXRsnR+Hx6wGQi0om7YbumSx1h+bu35zDwtDMySmMmFXqny7tCq
8CzXokwBvQ8jQCE7wOnUQU6nT0C9t4m6kfHd/gGI7gXPKFi29sMwOPpmjEWpYujaogxfRBkE/hOU
9sZ7q7cMdV96HYyGR7/x+tKyoEqLpvcimoHffQFNpXmp7fP+s+c7L9jv9cIXMNzexiqvdFnHer95
f6yWBdcSDniMCKnOFU9EydTsJxHr9iNMtZZZNZ1ecJmfq/m8AQW0Mp+zP+2zWwy/8/Rb4Yqsnsu8
OjT6OmL7AXRSip9rWYr9/5XXF3VPcXXQ+vFL22WV/98s8yciH1JZpbailGeVaLdilQiSMewCFyDD
Hv7G5ELsCZpf6baPW4bf4evX7Lt7XrLp1DnR60O6P3L3CFcNn4I2XmXm/g3dDp7fWk2Y26HjYLSB
qmeZjFla57GWKmdN159OrdJF4sg7Mm32qlClZmMWjAJkOvZKbnIIzqYtv2P+m7YOSJyu70jR75Ve
yAohahgCsLNRDDJa7E/e3Z69P71ps+sPx/++PfnhanJB6/NbaOmA2O8GDVxwSPu6wj9VEPv7j/Db
t4TL4rz9/urD5OR4co1dcPAGCCZZplasEnlCfj4rEdAxSh9z3lcRybBBUqb73zXd6gm5nR6cig7Y
eAyNTKFPYZXRbWCj3x8V4er04/Xp5OTkqs18q5LeE4yb90JfQ67v6zSldOmHPfaauT/DA3N/JeL7
F+4N5n4D8xcBTzYSHD2lZ53CexuXEhmcZ/vT1mv82LvJ2fnpCbv5wL4/e2/+Tlus03SWDk4ie2gc
ivZ/m7baTmO7v07UwTeQvhTlghcV48wGKpNYZ+TGa1bWeU6Ghp/rBdeMiP7jN+gNn9ATD1IjQZq7
UVM5OOg13bxh1Vzlswzbx3Y1OHobbzbvyc9aX/5qG/5qG/5qG367bWi35iIXJc+opkLzFdImgifo
9DoB2JnVMkta0WjooxCjCKpYATLEjhfSwAVBxwfgXGps/W/84YHtAOhNZ2AwoKeg0al1LvP6gSHM
ebZQqB/dTuB3Qt+b+7Hvh2LAEGnXF5fs8ur09OLyhr0rJbvgaxaOWBBEfT/qD9jHm2MW+kGf8XJ5
P8iAnYaPqNXvHHVC7H5BNsc2xNa3l7eq2tDGgdnwPCmVTFrbHgSHn6GwgpfgFBHr9jY3dqCeQpRa
Cnq7d7ndsWOVp3LOqP2ZltN87xPaiH/VmWG4FxHP4ZZhArD4PFLH+BS5NYcU8UKKxh0l27FpGOhw
Dsgl2qKxT7slf/CKjK/B3zg0J1XBV7nnehjYdxwc0fFqIbXIZKXHKk3pQJiuzvu5FuV6rPLGUYlg
3EAlokKJMPV1bBmr0B/Je7ijKxOGC6WT8WKVqQbX1JaOc1UueWZAwHS59jK5lBAmHF7QIU3LXl0k
wLYhyPNcoaUSTiqPE817sRS5rhyb91KsvASicMCNR+YVtSNemsn5QjsoqweeSzBQPTpbqtnmAEGT
xKrcUi/uC3eTyDSVcZ3p9bhr1G4CBwHpoTZpRGk1NhKAt8xaDzk+S3ZnlRDJOOj5/SAcDP3dudHL
yem7ycfzGzolbXcKZDe8T8avzQ8C1Vp5Fb8Xjh1jPq9pP6dmWcA1wk5wNOwgPMMhXaWqhAK3juIe
kOtvc0NnvczIcxllTBYbp60hH3Wy5LsMOFgjw1yrVMObMUyIiixvVQBfxVywEOgL4BemM4jJgJrN
BJN5nNVogbFgz6KGcF2rJV6mhOApzoqnaCYUbsqKUKLDFPyOrVVdbruTlEE6mUpDAUYs4e/ZepqT
aiyqaArKi1oniqxuO9MInZItOyzOVCWSaQtQe7afJf2aBGwzALuXnP2HAgQgJlA8dxMxanfo4fUC
7zhpsFJQm6PCVguBSHaIWF1BPYkowCLlcTa5PAOkXqgEimhceGBrBqZ26E/t7OXwIEkxclcaUWAl
03qv8T7lcFSAuwDe3m7x8OSegiXxYsTTDn1d5IUHS68QBgbcjF1GLORMmAI92Hqp6gq1Db4B5cQV
zYF26oBYJGopKEGRIDQOeLXV8kaA9/VyRtU4ZZNqncc3vLpj1A3BsHT9aXL1/uz9DxEcC+3mSmYZ
GRPo4RHzTM14xmzmsMTabFZrJjVQ5H83XkYmsz5GfqiV5lmHBCZiniMUsYDcIhGzek4+sXeWsrcs
aBtERLIiI5rr7QCzwegMi1cmfA2qjVkqqvVc1yRJrJZLmGfrGbs0sPPFPUTPxloUYEvEiwkaA+rE
h69Y77FKToyDmCeefRKxJa7miFQniu28wSi8R1csLdUSrtfEL+18rhvkYUX9nBtEf4Ymyxjuw82p
Mwv+j2vEV474MojksshMSjbsOcpb9pwTTfN4Ued3nhsSjQImcKZckzeYu4pcxvDiahhDemDUlgK4
oCKCpVM59YL0pYEylNEXaSqxqtrMoRZph/0TdQCIxsgQCJbjy49tPKkqNoOFVjLRC+tN1mwbrJ4z
8PBlRnmJ04QJBJHjGLBUgi1QxML+0U5wYn4j+AV/YPwpTtf+C4fxmdw+vbziiUQA7l45JrjjwFjS
vqQ/XmngI9b7Y0Y0pdPV4mqXCOJMcMuOKT7PjOvKItRnxPy0EJSziSeMjMbDdhDkXZxRYRWlMbv9
MIVCoyzokpugo1NC9sPupYkMinay4jyTOl6sv/LKpgcDnPG5sT4h+liRc2ibYWD8lL5UbAu6UQ0S
MAIYbmSUQVFlcylQ2jBJpE3dDXEc/0u0oxlVJ5uopibdeyYBNRIqHKDz3AOgJ4dQbF0fdS+HiagA
fwXRo6jYWiGO7JVUiSdzAwAjHvk+wZidh1sCsg2RZzoh8hICgaIwfQHx5pQCjjoQakAMGgIypcMj
h8jrImIji9y2VKatMzlugwtYBvTKESSkfdquOBHaHpozvpxJOIQFcb2PrSrRphbZz5ebWmOU46IH
pt1WvmRbd0wpoq+Hj0+22fjRKSYCiaZpp2QaRSJLstPomTDIb/mzkWJU+pQ2Uom9jazAZe65KrIF
saeq2DFiSa5Wq68RzCTqoS0hpw+c4tZuqG7BPd0kFzG3MFcwHeZHGOozLT10yDShquJHwmh61W1N
anZfJngUEJUyEc0AVtR56a82c6YvMS14ZcoHRRtGVi3BqKttDdYNVcOAWTFqlMkRTcLaUYvYu/PJ
TRS+GbT7o4eg3X3otsM3wZsEkWoDcF+XAhtE1HjoszmsVdldr39g2l3xoEVOCqlo3j1GNmhMhWSg
xhYpab797FzEBOo21c/IN6Jrh1cvEfc0UtppNjQD5SxG2VvsvlnzDE7Fy92B/UK/2dVltt2gTYMT
GdRutE51sb2dL3frBXzRjOAE9FPl5vbQzO3Lmf1wsAVGg7Au9E4CTEpgKGmIe315bqjSuohRE3Zv
1xDYDMxuxfod4o4kZx7NraHf97tYvjqD3dLuoCt4P0n6/e5wcISB54gP/TDkvdmQdwe9XjCchT1f
sFegdLkgtZDaLGFVyYed0m0+rRxAQIJeiTSzYyxODb2h6KcxR9vSA1k/HQziwXB41O+DdHcUdkXX
n40GoyQx9KrFUu1UaD8gVo8llVb5ANbqTuTyl405cPIJWb0UqVVUp4+TNTdjU0CzFrmBLOwu7PRa
X778Fz0aKwk=
===END CRASH DUMP===
 is the crash dump

**Comment by Gamecrafter** [comment]
You're already running a server with the same port this server is trying to use, leading to the RakLib error.
