### ISSUE TITLE
Always downloaded,version 0.10.4

### ISSUE THREAD

**Issue by CookieBurger** [PocketMine/PocketMine-MP#3329]
i have an issue with this that when i download pocketminempit keepsaying 0.10.4 when i created the server.please help

**Comment by SurvivalHive** [comment]
download from here
http://jenkins.pocketmine.net/job/PocketMine-MP/1258/
the last pocketmine.phar file and replace it in your server folder

**Comment by PEMapModder** [comment]
Please read the contribution guidelines. Only report issues on the **development** build please. This is not a support channel.
