### ISSUE TITLE
Server refuses to start

### ISSUE THREAD

**Issue by redsoxno10** [PocketMine/PocketMine-MP#3338]
This is in the console when i see it:

==============================================[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 02:34:36 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 02:34:36 [INFO] Loading pocketmine-soft.yml...
[Server] 02:34:36 [INFO] Loading pocketmine.yml...
[Server] 02:34:37 [INFO] Loading server properties...
[Server] 02:34:37 [INFO] Selected English (eng) as the base language
[Server] 02:34:37 [INFO] Starting Minecraft: PE server version v0.11.0 alpha
[Server] 02:34:37 [INFO] Starting remote control listener
[Server] 
[Server] Fatal error: Uncaught exception 'RuntimeException' with message 'socket_bind(): unable to bind address [98]: Address in use' in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php:56
[Server] Stack trace:
[Server] #0 [internal function]: ExceptionHandler::handler(2, 'socket_bind(): ...', 'phar:///storage...', 56, Array)
[Server] #1 phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php(56): socket_bind(Resource id #76, '0.0.0.0', 19132)
[Server] #2 phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/Server__32bit.php(1655): pocketmine\network\rcon\RCON->__construct(Object(pocketmine\Server), '10803879', 19132, '0.0.0.0', 1, 50)
[Server] #3 phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php(458): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'phar:///storage...', '/storage/sdcard...', '/storage/sdcard...')
[Server] #4 /storage/sdcard0/PocketMine/PocketMine-MP.phar(1): require('phar:///stora in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/network/rcon/RCON.php on line 56
==============================================

**Comment by Intyre** [comment]
Please read the error: 'socket_bind(): unable to bind address [98]: Address in use
