### ISSUE TITLE
Tapping a pumpkin changes its direction

### ISSUE THREAD

**Issue by legoboy0215** [PocketMine/PocketMine-MP#3344]
When I tap a pumpkin, it will change its faces direction.

**Comment by SkygridRex** [comment]
Im thinking your issue dont have solution talk about it to shogui

**Comment by Yosshi999** [comment]
How about Jack o'Lantern?

**Comment by legoboy0215** [comment]
Same.

**Comment by JoahDave** [comment]
After quitting and rejoining, all pumpkins will face the correct direction once again.

**Comment by SkygridRex** [comment]
Do you break or touch the pumpkin?

**Comment by JoahDave** [comment]
@SkygridRex legoboy0215 says "tap", not "mine".

**Comment by SkygridRex** [comment]
This is a pocketmine error

**Comment by PEMapModder** [comment]
@SkygridRex this is a issue tracker. We only report PocketMine errors here. If it isn't a PocketMine issue he would not have reported here.
This is not the place to look for help or to give help.

**Comment by SkygridRex** [comment]
@PEMapModder i dont like talk with shogui he always close my issues for example search the next issue Pls fix armor.php

**Comment by SkygridRex** [comment]
Its a MPCE client error (im think)
