### ISSUE TITLE
CraftItemEvent cant be cancelled

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3346]
$event->setCancelled() doesnt work please fix

**Comment by SkygridRex** [comment]
Hey i see you in the MinecraftGenius76 youtube Channel

**Comment by SkygridRex** [comment]
Why you need to cancel this?

**Comment by SkygridRex** [comment]
setCancelled($forceCancel = true);
Try this

**Comment by SkygridRex** [comment]
setCancelled($forceCancel = true);
Try this

**Comment by legoboy0215** [comment]
No. This is a bug I think. #WatchTheForums...

**Comment by sekjun9878** [comment]
Are you sure? Sample code?

**Comment by Creeperface01** [comment]
I tried the simpliest code
Public function onCraft(CraftItemEvent $e){
    $e->setCancelled();
}

I tried cancel transaction event too but players can still craft

**Comment by SkygridRex** [comment]
Try use pocketmine 1.6 (The big Fail) you cant craft anymore xD 
Download
https://transfer.sh/1fzA3N/pocketmine-mp-1.6dev.phar
PS: dont use Creative doesnt work xD

**Comment by Creeperface01** [comment]
I can't get it to work

**Comment by SkygridRex** [comment]
Hey ill make my own pocketmine distribution (Like a SteadBreadFast)

**Comment by SkygridRex** [comment]
@Creeperface01 change the file name to Pocketmine_MP.phar ok

**Comment by SkygridRex** [comment]
Ops is Pocketmine-MP.phar

**Comment by SkygridRex** [comment]
Im tired of shogui with your Pocketmine fails (like a 1.6)

**Comment by SkygridRex** [comment]
Im talking only :'(

**Comment by sekjun9878** [comment]
@SkygridRex Please do not make meaningless posts or you may be permanently banned from our issue tracker.

**Comment by SkygridRex** [comment]
@sekjun0878 Ok no problem!
No hard feelings?

**Comment by SkygridRex** [comment]
@sekjun9878 i forgot 
Can fix Amor.PHP?

**Comment by iksaku** [comment]
I have checked the code for this event and it seems to be fine... Are you sure you're using `$e->setCancelled(true);`?

**Comment by Creeperface01** [comment]
Yes i tried too

**Comment by iksaku** [comment]
@Creeperface01 The default value for the method `setCancelled` is `FALSE` so be sure to always write down `TRUE` ;)

**Comment by Creeperface01** [comment]
I tried both but i try again

**Comment by SkygridRex** [comment]
@iksaku Pienso que hay que hacerle un pocketmine especifico para desactivar el evento de crafteo

**Comment by iksaku** [comment]
@SkygridRex Primero que nada... Hay que hablar inglés ;) Segundo... Ya esta hecho, solo que por alguna razón, no esta funcionando para @Creeperface01

**Comment by SkygridRex** [comment]
@Creeperface01 I was create a Pocketmine Distribution for you, you can download this pocketmine version here:
https://www.dropbox.com/s/koi7l75o1f1v8oa/Pocketmine-MP.phar?dl=0
PS: its pocketmine 1.5 Soft
Know Issues:
*To stop the server you need to kill server :(
*You can see in the console lots of
