### ISSUE TITLE
Server crashing "Call to a member function hasPermission() on null"

### ISSUE THREAD

**Issue by mariusbjornor** [PocketMine/PocketMine-MP#3351]
Fatal error: Call to a member function hasPermission() on null in phar:///home/mariusbjornor/MinecraftServer/PocketMine-MP.phar/src/pocketmine/Player__32bit.php on line 439

Crashreport: http://hastebin.com/vehafahode.coffee 

is this fixable?

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
