### ISSUE TITLE
zlib_decode(): data error when loading leveldb

### ISSUE THREAD

**Issue by D3thw0lf** [PocketMine/PocketMine-MP#3353]
[11:56:37] [Server thread/WARNING]: RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 157

I don't know if this is already known (I guess so) but when you try to load a leveldb (for example: Windows 10 generated map) with PM it Crashs with the error above. I read in Forums that leveldb works only for Linux at PM...could you add a Windows working Version, too? I mean even the Windows 10 Edition use this fileformat now... :/

tried with 0.12.x PM 1.6

**Comment by xHFx** [comment]
Where do you download the 0.12 BETA Phar?

**Comment by Pub4Game** [comment]
No need to create issues about 0.12.0

**Comment by D3thw0lf** [comment]
I run the Server on source

**Comment by shoghicp** [comment]
There is no call to decode on LevelDB, which means you are not using it.

Also, I'm not the one that maintains the extension, only the PHP code. I'm not the one you've to ask to add Windows support.
