### ISSUE TITLE
Far lands? Uhhh...

### ISSUE THREAD

**Issue by JoahDave** [PocketMine/PocketMine-MP#3354]
Now, I know the far lands are, well, the far lands, but not the fault of pocketmine. However, I died (/kill) and respawned in them? This does not seem normal.
![image](https://cloud.githubusercontent.com/assets/11605395/9141947/710e8ec8-3cf1-11e5-9137-459c09e3d830.jpg)

**Comment by SkygridRex** [comment]
I went here using /tp xD

**Comment by sithsiri** [comment]
How do you get there using tp?

Oh right JoahDave, try one of the two below:

- (easiest) Delete your player file in PocketMine and restart
- (better) Get another player. If the other player gets normal terrain, do /tp [you] [otherPlayer]

**Comment by SkygridRex** [comment]
Do /tp 100000 100 100000

**Comment by sithsiri** [comment]
@SkygridRex That didn't take me to the far lands... (that actually took me to a coast off of a forest)
/kill took me back.

**Comment by shoghicp** [comment]
This is a glitch of the client, not PocketMine. @sekjun9878 please don't tag issues not related to PocketMine

**Comment by JoahDave** [comment]
@sithsiri Thanks, but I know how to solve this.
@shoghicp This has never happened in single player...

**Comment by sekjun9878** [comment]
@shoghicp No use reminding me of that, because I wouldn't know that this isn't a PocketMine bug.
