### ISSUE TITLE
Text color-codes not translating

### ISSUE THREAD

**Issue by sithsiri** [PocketMine/PocketMine-MP#3355]
**EDIT: This is build dev 1258**
***EDIT 2: Problem known, but not resolved (8/8/2015)***

There is a weird error.
Instead of:
[Server thread/INFO]: Stopping other threads
I get:
§b[19:20:49] §r§f[Server thread/INFO]: Stopping other threads§r

Oh, and no colors. Confused...
![pocketminedev1258problem](https://cloud.githubusercontent.com/assets/10308055/9148197/c77e4dfa-3d39-11e5-9c83-200ce7747c41.PNG)
 When I look at the log, it doesn't have those chars.

**Comment by D3thw0lf** [comment]
These are color-codes. If your console are not able to "translate" them into Color (green, red, orange whatever) you get those weird stuff in console. ;) 

This is how it Looks (for example) for me:
![colors](https://cloud.githubusercontent.com/assets/895448/9148254/4e25e7a0-3d76-11e5-85b9-9dc998210b0c.jpg)

**Comment by sithsiri** [comment]
Okay. Is it just the build, then? Looks like you tried something that is not in the Jenkins server? I have no idea how to compile from Github...

**Comment by PEMapModder** [comment]
What version are you using? This issue should've been fixed.

**Comment by D3thw0lf** [comment]
@sithsiri I just run it directly from Code as you can see in the first yellow line. :)

**Comment by sithsiri** [comment]
@PEMapModder dev 1258. It's shown in the attached picture.

**Comment by sekjun9878** [comment]
Looks like an issue with the Windows 10 console? You can load the server with `--disable-ansi` to mitigate the issue meanwhile.

Actually why is colour displayed in Minecraft colour codes?

**Comment by sithsiri** [comment]
How do I load the server like that? Do I paste --disable-ansi into server.properties?

**Comment by sekjun9878** [comment]
Paste it into start.cmd where the other "--blah-bla" are

**Comment by sithsiri** [comment]
![pm old dev 907](https://cloud.githubusercontent.com/assets/10308055/9151434/d2b76d1c-3dc7-11e5-984d-a4c4a25be8e7.PNG)
The above is dev 907.
So it isn't Windows 10.

**Comment by sekjun9878** [comment]
Gotya, I'll look for changes

**Comment by sithsiri** [comment]
--disable-ansi works. It just removes color. Not a big problem, but it makes it hard to disinguish warnings from server thread.

**Comment by sithsiri** [comment]
Does this happen on other versions of Windows (and Linux/OS X) running dev 1258? Like Windows 8.1 and 7?

**Comment by sekjun9878** [comment]
I've never had this bug on my Windows 8.1 system so I naturally thought it was a Windows 10 issue

**Comment by sekjun9878** [comment]
@sithsiri Would you be able to check what commit that was? I see you have a non-packaged installation so you might be able to get it. I can't go back so far back to build 907 to see what it was.

**Comment by sekjun9878** [comment]
Nevermind, I think I found the troublesome commit

**Comment by sekjun9878** [comment]
Might be related to this: https://github.com/PocketMine/PocketMine-MP/commit/7cf5df7e4627dc31d4c042429a82e8604fc6bf0d

Because Build 907 was before that

**Comment by sithsiri** [comment]
Ok. By the way, Jenkins is saying that Build Executor 1 and 3 are dead. No idea for sure what that means, but the log says that "java.io.IOException: No space left on device".

**Comment by sekjun9878** [comment]
Yeah, @shoghicp is moving Jenkins off my to be decommissioned server so some problems are to be expected

**Comment by sithsiri** [comment]
Dev 957 also has color. Will check dev 1257.

**Comment by sithsiri** [comment]
Okay! I tested with and without my plugins on dev 1257 and I still had color! It has to be a change from 1257 and 1258!

How accomplished I feel. Dunno why. :)

**Comment by sekjun9878** [comment]
@sithsiri There must be something wrong with your setup. There's nothing that might break terminal display between builds 1257 and 1258.

**Comment by sekjun9878** [comment]
Can you try downloading a fresh packaged version of PocketMine latest dev build inside a new folder, and see if that displays colour?

**Comment by sithsiri** [comment]
K hold on...
wait, what do you mean fresh packaged? Do you mean run the installer and dump in 1258?

**Comment by sithsiri** [comment]
Oops, sorry about the trouble.
Wait, what setting did that?

**Comment by sekjun9878** [comment]
Well, whatever the problem was, it's not our problem anymore :P

Please refer to our forums for additional help.

**Comment by TahaTheHacker** [comment]
the termial in windows , thi sisn't like an issue , just right-click in the console and select options after select text and select allow bold colour and that's it after there will be colours xD
