### ISSUE TITLE
Gamemode not crafting bug

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#3356]
Bug for the 1.6 Dev. (Build 7 Beta)

basically, I got my server on default gamemode creative, so when people join, they can't build.
 - although I did find a way to bypass that bug. Change gamemode from creative to survival, and back again.

bug: http://t.co/SCKJCzihSg

( i dont know if i post it here, or on Twitter, so ill do them both )

**Comment by sekjun9878** [comment]
Duplicate of #3357
