### ISSUE TITLE
Gamemode not crafting bug

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#3357]
basically, I got my server on default gamemode creative, so when people join, they can't build.
 - although I did find a way to bypass that bug. Change gamemode from creative to survival, and back again.

bug: http://t.co/SCKJCzihSg -- Twitter redirect to a paste website, showing the log of players having the problem 

( i dont know if i post it here, or on Twitter, so ill do them both )

**Comment by sekjun9878** [comment]
Twitter redirect: http://paste.ubuntu.com/12028937/

**Comment by sekjun9878** [comment]
It could be that they're inside the spawn protection when they join, and by the time you change gamemode they're outside the protection zone? Please test this and let us know.

**Comment by shoghicp** [comment]
If people are on creative mode, they will be able to build. There is no limitation on that.

Check that they are not inside the spawn radius. Also, if you OP someone, they'll have permissions and spawn area does not apply to them anymore.
