### ISSUE TITLE
Console command '?' doesn't work as a help command

### ISSUE THREAD

**Issue by DarkDracoon** [PocketMine/PocketMine-MP#3364]
![sem titulo](https://cloud.githubusercontent.com/assets/4550303/9184374/b8ed3d3a-3fac-11e5-8467-d54f44544031.png)
As you can see, you can write 'help' or '?'. I've tried with '?' and it told me that it was an unknown command, but it serves as a help command.
The bug occurs in the first 2 tries.

**Comment by SkygridRex** [comment]
What pocketmine distribution are you using?
(Like a Pocketmine Soft 1.5)

**Comment by DarkDracoon** [comment]
PocketMine 1.6dev

**Comment by shoghicp** [comment]
PocketMine 1.6 is not supported here, as we said. It's in a pre-development stage.

**Comment by SkygridRex** [comment]
You do know this is a unstable version?
Give a day to make you a pocketmine edition with this error solved ok

**Comment by SkygridRex** [comment]
@shoguicp you write too fast!

**Comment by PEMapModder** [comment]
@SkygridRex this is not a forum.
