### ISSUE TITLE
PocketMine Fails to Correctly Compile PHP for Raspbian OS on Raspberry Pi

### ISSUE THREAD

**Issue by jingz2007** [PocketMine/PocketMine-MP#3365]
I know exactly how to fix the issue and have tested out the fix but it is not a change I can do on a github fork and pull request it. The initial install script needs to detect if the OS is a version of Raspbian and if it is it needs to make a folder called bin in the pocket mine installation location and extract the file PocketMine-MP.php from http://sourceforge.net/projects/pocketmine/files/builds/PHP_5.6.4_ARM_Raspbian_hard.tar.gz/download. Next, the installer needs to run the command chmod 0755 bin/php. It would probably be preferable to upload the php build for raspbian to your own site/file server instead of depending on source forge. Also, the link I included is not a direct download but a mirror download thing.

**Comment by shoghicp** [comment]
@jingz2007 Seems like you are using an old installer as we don't use sourceforge anymore. Please use the script provided on pocketmine.net as that will keep you updated with the latest PHP as well!

Also, this is not the repository to open this issue, try https://github.com/PocketMine/php-build-scripts

**Comment by jingz2007** [comment]
I did use the script but it does not correctly compile php for raspbian, so I had to manually install the php.

**Comment by SkygridRex** [comment]
Hi, Probably you need to send a email with your seggestion to the pocketmine team, but i think shogui dont use your suggestion

**Comment by jingz2007** [comment]
@SkygridRex I can't find an email for the pocketmine team to make suggestions or report bugs. And what does but i think shogui dont use your suggestion mean?

**Comment by SkygridRex** [comment]
@jingz2007 the email is support@pocketmine.net
