### ISSUE TITLE
Dose making a server slow your PC down or put any viruses on a PC?

### ISSUE THREAD

**Issue by happyhippo123** [PocketMine/PocketMine-MP#3377]
Douse it slow down my internet speed down or put any viruses on my PC.

**Comment by 64FF00** [comment]
@happyhippo123 Nope .-.

**Comment by happyhippo123** [comment]
Are you sure

**Comment by PEMapModder** [comment]
It obviously slows down your internet speed because more data transfer is involved. If we put viruses here in purpose, we shall never tell you we do.

**Comment by 64FF00** [comment]
@PEMapModder True, but why would someone put viruses in purpose just for really small servers
