### ISSUE TITLE
Odd Bug.

### ISSUE THREAD

**Issue by GeekGamingMC** [PocketMine/PocketMine-MP#3380]
This just popped up in my terminal. All it told me to do was send it to the "Bug" section of the Pocketmine Website and now I'm wondering how to fix this issue. /Users/Evan/CrashDump_Fri_Aug_14-02.22.30-UTC_2015.log

**Comment by legoboy0215** [comment]
Lol. You did not even show it to us.

**Comment by JoahDave** [comment]
Upload the crash dump to the PocketMine Crash Archive, and then submit the link!
