### ISSUE TITLE
Running up slabs makes you jump

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3383]
When you run up a staircase of slabs, you jump up the slabs which are at the lower part

**Comment by SkygridRex** [comment]
What version of pocketmine are you using?

**Comment by thebigsmileXD** [comment]
I use the newest version (1.4?).
I found a piece in the code, i guess it was "collision mask", theres the //todo comment behind it.

**Comment by SkygridRex** [comment]
OMG!!! update to PM 1.5 :v

**Comment by thebigsmileXD** [comment]
I do have the latest, i forgot to reply. (1.5)

**Comment by thebigsmileXD** [comment]
1.5dev-1262, still.

**Comment by SkygridRex** [comment]
You can fix it diwnloading this plugin
https://github.com/SaiCoDev/TruFix

**Comment by thebigsmileXD** [comment]
I'll try, but the less plugins the better

**Comment by MagicDroidX** [comment]
well you see. the plugin above fixs nothing but only log something unnecessary

**Comment by thebigsmileXD** [comment]
Thats true, everything is commented ouz

**Comment by shoghicp** [comment]
This is a client-side issue

**Comment by thebigsmileXD** [comment]
I don't think so. I only have this problem on servers, not on mcpe:sp
Are you sure?

I just tried again, exact same test offline+online, happens only on servers.

**Comment by TahaTheHacker** [comment]
do you know what is a client?

**Comment by thebigsmileXD** [comment]
@TahaTheHacker Yes of cause. Its the users device.
My profession is it-specialist, so i know exactly what i talk about.
