### ISSUE TITLE
Unexpected Doom in my server

### ISSUE THREAD

**Issue by astersx** [PocketMine/PocketMine-MP#3389]
I dont know why , but ios players cant be killed by swords (melee attack) , but bows works (that problem happen sometimes) .... What i need to do ? Why that is happening ? Is a Doom on my server , i dont know if they hack .... i wanna a way to know if a player hack , i dont wanna to ban half server for no reason.  Players told me that for long time but i didnt belive until i finished a pvp arena . Im so confused , any advice is veryyyyy helpfull for me . 

P.S.  If is a hack , there are no antihacks?

**Comment by LouisBHirst** [comment]
you ported DOOM to Pocketmine???  Wow I wish I had thought of that!!!

p.s. sorry couldn't resist.

If I might ask tho, what version / build are you running?  Bows have no
effect on 1.5, but on 1.4 they're practically instagib to ppl with armor.
No idea on 1.6

Bart Hirst
(484) 802-4798
http://www.linkedin.com/in/louisbhirst

**Comment by astersx** [comment]
1.5 latest build ,i dont have problem with bow :| , im talking about invincible players :/

**Comment by astersx** [comment]
Its a problem if i deleted in server config world and i placed another name as main world? What could make this problem ? But is strange becouse most are ios players i guess 0.0

**Comment by SkygridRex** [comment]
Are you using pocketmine soft or develoment build?
And what is DOOM?

**Comment by astersx** [comment]
dev 1258  , doom is like big problems :|  use google translate. ("Hell"), Im soooo confused :( .

**Comment by astersx** [comment]
i experienced a invisibility bug in a older version of pocketmine , but fixed , after i update . Now i dont know if players hack or is a bug , they swear is a bug , some say is hack , but only ios version got this problem , and why my server , Always spawn plugin and keepinventory may be the problem ? Any advice?

**Comment by astersx** [comment]
Older version , i guess is 1.4 :D

**Comment by SkygridRex** [comment]
Update to PM 1.5 and close your issue

**Comment by astersx** [comment]
lol i use latest version , i just told i used a oldest version and players was invisible . I found the problem , if i make another world it have bugs ..... So only 1 world for now :/
