### ISSUE TITLE
Cannot hoe seeds. Is this a bug ?

### ISSUE THREAD

**Issue by creeper1968** [PocketMine/PocketMine-MP#3390]
Hi,

Not sure if this is a bug ? On our server install of pocket mine, no one can find any seeds when hoeing tall grass. Is this a feature, bug or config issue ?

The game is hosted on a third party server and different family members are running the android and apple apps versions of MC, connecting to the external. All have the same behavior.

I have tried using all available versions of pocketmine up to build 1258 via multicraft cp on the server, All without any luck. 

Not connecting to the external server and playing the app as local server produces seeds when hoeing.

Many thanks

**Comment by SkygridRex** [comment]
Pocketmine have some issue codes, it's not complete some blocks and items there aren't complete
