### ISSUE TITLE
Out of Memory Crash

### ISSUE THREAD

**Issue by basemiles** [PocketMine/PocketMine-MP#3391]
Started Pocketmine on AWS this AM, it ran for a few hours then saw this message on the console.  
---------------------------
2015-08-20 [08:57:31] [Server thread/INFO]: Query running on 0.0.0.0:19132
2015-08-20 [08:57:31] [Server thread/INFO]: Default game type: Creative Mode
2015-08-20 [08:57:31] [Server thread/INFO]: Done (0.677s)! For help, type "help" or "?"
2015-08-20 [08:58:07] [Server thread/INFO]: swag_c23[/50.136.254.151:41635] logged in with entity id 3 at (world, 42.1683, 67, 251.2761)
2015-08-20 [08:58:08] [Server thread/INFO]: swag_c23 joined the game
2015-08-20 [08:58:47] [Server thread/INFO]: swag_c23 left the game
2015-08-20 [08:58:47] [Server thread/INFO]: swag_c23[/50.136.254.151:41635] logged out due to timeout
2015-08-20 [09:00:50] [Server thread/INFO]: touch man[/50.136.254.151:34486] logged out due to Outdated client!
2015-08-20 [13:37:55] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2015-08-20 [13:37:55] [Server thread/EMERGENCY]: Please upload the "/home/ec2-user/CrashDump_Thu_Aug_20-13.37.55-EAST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

--------------------------

crashdump below

-------------------------

[ec2-user@ip-172-31-17-84 ~]$ more CrashDump_Thu_Aug_20-13.37.55-EAST_2015.log 
PocketMine-MP Crash Dump Thu Aug 20 13:37:55 EAST 2015

Error: Out of memory (allocated 851181568) (tried to allocate 134217728 bytes)
File: /src/pocketmine/nbt/NBT__64bit
Line: 189
Type: E_ERROR

Code:
[180] 			case NBT::TAG_ByteArray:
[181] 				$tag = new ByteArray($this->getString());
[182] 				$tag->read($this);
[183] 				break;
[184] 			case NBT::TAG_String:
[185] 				$tag = new String($this->getString());
[186] 				$tag->read($this);
[187] 				break;
[188] 			case NBT::TAG_Enum:
[189] 				$tag = new Enum($this->getString());
[190] 				$tag->read($this);
[191] 				break;
[192] 			case NBT::TAG_Compound:
[193] 				$tag = new Compound($this->getString());
[194] 				$tag->read($this);
[195] 				break;
[196] 			case NBT::TAG_IntArray:
[197] 				$tag = new IntArray($this->getString());
[198] 				$tag->read($this);
[199] 				break;

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1258 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ip-172-31-17-84 3.14.48-33.39.amzn1.x86_64 #1 SMP Tue Jul 14 23:43:07 
UTC 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWW1v20YS/isLOUDtgyiLercCF3BTt5eDk/hiB/lQFcaSXEqs+Vbu0rJS9L/fM7NLUnbk5nB3
H84tEO3b7LOzM8/MLP/omSRTvaU/mQyHZ9PFfNrvqaoqqt7yj57ZlRjqXd5dfvz44WOv38uU1nJN
fR9qI4pYZCorqp04lmlahNKoSCymvr/wp7PFiTg2VYIeU4hmWPjjycifz0cLEeyM0ieQGScpCTzV
VXhaFuG9MlmSq9M8MKfvf7i9u5tNgsRgXope4Fyc/dnvlWm9TvLeMpapVv1eWESK8PqLISStDP0X
Sq0EBCyXtxc/3/2A3S6qSu6WkAR87bSVeWXkWpyLXG1FO+v4ldkk2vt+rcwNDpGvj09OXvPK0bOV
3veVkpGd76aM96YEGL233ZMXoNkNLK7pYVwOw4ugZt8GNT8MavECqMu8ziyks8OQaMKLgM6G3wR0
5h8EdDZ6AdCbIiuLOo8Y1Nn4MKhm0svAJt8GNj0MbPYCsLe56QzrbH4YWDPpZWCLbwM7+xoYXMFU
MoTx/9I7Gorjk6XoXGi1ulHVg6q878NK6s2PdVYen/R+7ffWKleVTMljMKyTAp7U8wfTSD1go6BO
0giONpou4GhVYYqwwNzRvN+TZcIz/dFgiJlr+OWyN/w3/7CgkvdpEtCawZwl1Lkk8uldJXn9KJLS
8+cjb+zjH28xEeOBPxlMFt54PBifDWT2JfcHj4sZGEEc+eLm3bW4rZX4R50KfyJG4+VkvBzOxafb
N2I09KfCTsUu5abEHtPBbODTpl9UjvP1RmgP7ehdoRsQ6OBGyo2WatD1CzRXygqADZRm25oVPICW
SlWZRNHKo+u2BYPM42QtiOJW1So/ut3U4qJeA58YLpbT+XLsi8uLm1sGTDOsQI/Ucn5VFKWwV7g3
VBaVOYf7jEfUuZbEwJE696mVyUevTOUO+M5HQ15Uym3u0S2q0OCiz/0ZdW83iVFemmhzXsQx9ahc
Bqnyfq9VtTsv8r2uKsQyNysrTHT+WaVhkSnidbNR4urDh2sak3kO3wuVQ+DJcJOoB5Wp3GgnkcLA
1ovTZL1pN7YIZZ5k4HI3z/ZlRdB0xEUFwe1h3dKNrKKwqNp2+VC6+VESx0lYp2ZnFWMt3hSVp5Ux
8Dt9Tt0p8KVW2duiSqOuTysV7U2hQHj+4+VPF5+ubqmXdDIopdZYFp3/jf9wvNoUnpYPyqEg42q9
cbDLUrIO8U4muQjZMGpgwqWwfQicUVzz9HeY7r27hr2I240C2TSghawU67zIYVxmI40ISe1GBEok
eZjWEeItxH9llyTrhi4NMdt8LVPLWPVFgZFKk0jB/CJ2RV05WSJBsC+g14R3gNorWFS6I8HvwXCN
uNNIxRKK12Jb5N8ZIctSyUqQajIcNoQJ7ABfEK/Zc283Khd1ua5kBAGDVU6mboUtV7mAz1QKtoou
oEhlvq6RgQgK+awy5xY6QZuSjDT5wkqlpW82KnSneLoQADbGlHp5eqrywTa5T0oVJXJQVOtTap1e
wTXuivju7c2Hu9n4zBvd0TqosRW0FKueyterHm30eaNId+QSGuxC+Y7QTPC4pkrmOuXciIdZm4wU
OPBLGb5SkG8SKrGReZTyJWcQbO2+25LzHfTrTW2ignzEJmQExjKFCNNCq8jCuiB/E+TmQCIck4mH
RIp/kp9jCvu750aWwFqT+KObDdZJslJdAI3bxV6VdIJErWGEkSphCHy6i+u3mGk2RUR66gY8wAoA
qhN/yczSyMGJBbmxgLnCIghqsBPOjjDd8VA72qnh6HMCRRc5TEpGkaiUtpZHMGFr94AjdV0xBwnY
W6BIH1C6+r2WKV3HOnnA3AeZIpAcuy1BxicQbvcD/ymiXA+3uV6raolR2vl9nQXQNtzpQu/y8Fbq
e1h8dQ8HGtD4J1wC22dzSJq1qQpwJEwCs3VfMOcIx00w2T7UkEFrmkIyq2WrAurL6hyeQ1NY9g2b
DM4D56qKRzCnUVABjsOmnrfQSKsWztuYPJRTcXhiXyTmO2jOVLwqUhQd2AqfrRXHOAHuWYxII3wG
z51yyZLIW20NwL76c1oEUKwuYtOUBmmSJYY4KVNryUn/QNxYKEPePNF0vdbTcaZtwsBY2YLChZXT
6F+zXuIE5gKaAjnnLCoGRzQ72uvHYWo22nWBcxTkGqQz7LNmkB4DW4rhiqmCWdlsKOn6P4efAelf
gKeg+F+B1wZpB+3vqKrF46RpAZei2AeWcWhozwaSPxxNLKprVSUFhyPyRU0bhkzITdHY+JuPrUA1
EdkYz/DgD8p6GtN4kYPA4KHQG7HDS2q16kRukzLDk6/baSsOuCQD3td5sqUj2uEDUUjSlLODryfT
sS0PRVBhqUIKhJrVQlitju3a9gDQpCp1d8zx0J1TnxwE5E49tqdeyyrA/XtIvlObu5GHHdQqmxNB
cWuEWwPfzWRec8jdR4F0pKbiu99wwjNjcNZgeTWOG27IOisbiA823nELFrEp6jRqgSRgkG0uOuhk
t6Jk5DjgDNUAn1Ec/cSe8BU3sq3Y1e2h4qrIGoqltW7c22elvTvFIdzVPTeFA/azt45y6HBT5/fa
6vuKrZ4IkTsJWVrAz3AaYTPdPrtnhQRE20ke5QCUy3SySFRzzc5RzmYO54+FXfb8+igIUKZkl+1L
sLu4af+DM3Mg8kJk7Mqe2tlCsxENtNH7L0Wt8lwZuos2dYNppDYSBtKgJKBERFKWiwAIe3KsxA5o
E1M3askoUG1MZLo52qevZoQcv9oZkt0Xnr9nzBT7eFvPNFBAK9OZZZUu1nKWT4EusnTnLtCuRafD
NBB/R+kC9Z4jF4bhvrn+1MdaIAjAP9skMhvL2uzfrXiPxS/F3CUGXcqgWTF7UwfiIoI/bWQanyLJ
t1lMpGBnbiNsae2vyPcdso3Oe7L28qTLR3I+SoNk2reOTRt/TnJkkTgWzEaxaVOs/3SdXzeZQpez
UxJEi7bg+hUl7HnpueZ+TobaSwX1eumSju+FT8mGiyyUVfJwk1Fq5rGNajLNlbsKhJEuT9TiVBtp
ahjM6Tq0qgWvRXpv06Zqe1I3qCaJJNw4ia2YeKozLzouX3gIJRq2MLfEs0uWIsPQ2tUTOBAZOuVp
OUwORsqkJJ/IB3NSRWb2tneV8jM07KN8dUfvP9xeLgWzLv4PaxRXOYorFpRkZcoZLMNzO7fw2iu+
eHJbIeoIMIk7K1sRhyQgIasxZDmjoQshRGU2MpEZURFL/S4cOa9/2t1wmM2Fb8hd6YABvYx1mx37
cJQDu/TFCAP+oQFlwsEJO61W+yjYHG5JMpVW7o1DKBCT3Y9Cv71JLmK76paIgKsgyp6IDmS6lTtt
ZTs5e3b0hL/ZjC6yos73A4B2OVsDguCTNCoZwM30cykmLy+VFT1RWuxWxtOoI/yz0cHVbF25snVk
oKy0QMXERPxiQoxF19BKte8oe9Rnme9GPiDoUn6XULmsqPwqd+5pwMWiNqFhooilNqxV1oujsbhO
eVqhYaoeuWgS2lDCJVhF9TgMA2IbVf1WUCVkfUNLekICJ5FRU4Bpz//sMkihzWW8k49CPtcLaqCQ
40NnD0/vgo30o4ySWu8tc/cgHTp2UrvU2R3NR7ZCnEQPVl5dRrDFDiBKbSXtJvyU1kVBC7wr7Brs
g6/BO/7byoRrdNTjtXL369az23O/p3FZS7H4j6SVRVmnTpr7TaHpmeBVzj7pQXsE2j7LeWxHmjRJ
qszA1YaeXFyv7+iBXr6WwiZ3zZVCQ3ldItmxGZ81SCYPm2g4WZAyp1VuQxI6peZW0kZtJ/fJLEhg
+XaKe3SzNfrSkhE9J9CDt7C9NsY6I7HW6zL5ltzIrj164Hna04aTJ73lpkzyuOjMYFPQ3fOWg733
PiRCjC8v8l1GaT57iIZ+dQuU6hY3LLphBgxbk0Ku14g+7nGgfXahHJGe/e8Pn8biIXH6EB7SlzVl
vuLnq2ETdnRpL6DKPRecuwyQe4ty78HoDb0Z8iOWSouSolUfbZyAXuhMk4ohM4mRKSsoG/EppzhP
k1xorel24I97QoT7PrGXQ9RIOLWxAa4hPCeNbsgON/L1M6Vst9tDKkkThBt7K5ePkuKtbVDCAvkO
xLJBw0MwdqqUl+IX+ukhyPS5dP6VJFoWbNKQ/ddWPkRTL9iirXmb5mrs0OMtF7ccxTRnDHTsDIlE
AqAuxO9B510ZAP8S9JRNrsshqdttKX66urhdjl7P+9OzR78/fhz3R6/91xEisWWtY1MpNMAw54uh
WMO+tW1Npif8uK0ejcpJIZo+Jb1BHNr/zEI2tN9GQFi3X2zLkCa7hv49TYwa2+9Cnv0K9cV+KLIf
moIQmc2m+9wrU/iOrLoO+6G6adVV2jbiJIWhs2jfZ2GxKdvRddT9zLruDVyZP3TR/N+0+z42Gvj0
GZr0HdmPWP5g6uBmgX3ubUUgbdyVpjuikYQ42lfIzfUVSxnRd4IQ+V63eAeV8Ecq90tMB4SfNhMe
fSwaDafDMX6+eksFdThbLIJZEITjYTSeyXgsw/EkjqJJMA+mwXwxj9UUf+IVdrrekOJIsXbjQieP
3bW4gt5N8OnAH1XsqlH08n4qjhdBFM6mwTBQMl7EExmpWTycxYvJQs2iyTiKo8VoxvvpTVZ0mtXs
fPrpSROrTEw2xb3KEYuqtuezkvdgDauowQw9O8kfUnxonyZ8Scrmm+S09+ef/wLVV12m
===END CRASH DUMP===

**Comment by SkygridRex** [comment]
Look this #3370 and close your issue
