### ISSUE TITLE
Cannot be the owner.

### ISSUE THREAD

**Issue by HotDerpDog** [PocketMine/PocketMine-MP#3394]
I cannot become the owner of my server. How can i be the owner?

**Comment by PEMapModder** [comment]
Please read the [contributing guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. This is an issue tracker, not a question tracker.

**Comment by JoahDave** [comment]
Please refer to the PocketMine help forums! Ask questions here! <a href="http://forums.pocketmine.net">forums.pocketmine.net</a>

**Comment by SkygridRex** [comment]
Do in the console "op (yourplayername)"
PS: close your issue
@PEMapModder help the people

**Comment by UltimateMcraft** [comment]
#helpthepeople

Op in your console

**Comment by PEMapModder** [comment]
@SkygridRex Please read the [contributing guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. This is an issue tracker, not a question tracker. This is not a forum. This is not a place to help people.

**Comment by thebigsmileXD** [comment]
@PEMapModder is right, question that in the forum please and close the issue.

**Comment by SkygridRex** [comment]
@PeMapModder i want to help people it's my problem

**Comment by thebigsmileXD** [comment]
But its not an issue. So please don't post it here.
