### ISSUE TITLE
Not coonected

### ISSUE THREAD

**Issue by GMasterN** [PocketMine/PocketMine-MP#3401]
Why My ip is 0.0.0.0
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 23:07:50 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 23:07:50 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 23:07:50 [INFO] Loading pocketmine.yml...
[Server] 23:07:50 [INFO] Loading server properties...
[Server] 23:07:51 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 23:07:51 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 23:07:51 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 23:07:57 [INFO] Preparing level "world"
[Server] 23:07:57 [INFO] Starting GS4 status listener
[Server] 23:07:57 [INFO] Setting query port to 19132
[Server] 23:07:57 [INFO] Query running on 0.0.0.0:19132
[Server] 23:07:58 [INFO] Default game type: SURVIVAL
[Server] 23:07:58 [INFO] Done (12.747s)! For help, type "help" or "?"

**Comment by TahaTheHacker** [comment]
that's an interface. don't change it. to know your IP go to www.whatsmyip.com and port is 19132 but you need to port forward first.

**Comment by SkygridRex** [comment]
You are trying to connect with ip 0.0.0.0 and this an invalid ip 
You most to find your own ip of your server for example 192.168.0.26

**Comment by SkygridRex** [comment]
@TahaTheHacker port forwarding its not needed he most to find your own private ip not public ip

**Comment by TahaTheHacker** [comment]
ya you're right but i got a little bit confused
Thanks!
