### ISSUE TITLE
Permission code Error on Player_64bit

### ISSUE THREAD

**Issue by SeangJemmy** [PocketMine/PocketMine-MP#3402]
PocketMine-MP Crash Dump Sun Aug 23 00:03:15 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux node3 3.2.0-89-generic #127-Ubuntu SMP Tue Jul 28 09:28:15 UTC 2015 x86_64
PHP Version: 5.6.3
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
IPLogger 1.3 by PEMapModder for API(s) 1.0.0
WorldEditor 1.0.3-0.1 by Array for API(s) 1.2.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
OmegaCMD 1.0.0 by SeangJemmy for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
xSudo 1.0.1 by 64FF00 for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
Pundler 1.4.1 by MinecrafterJPN for API(s) 1.10.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Sneak 1.1 by CrazedMiner for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
NoVoid 0.2 by rirititi for API(s) 1.0.0
Alias 1.1.1 by ZacHack for API(s) 1.1.0
PurePerms 1.1.3 by 64FF00 for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
PureChat 1.2.7 by 64FF00 for API(s) 1.11.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwtz20aS/itTtKvWThF8U6KYUuq0kryxV7J4phxfJdhSDYAhiQjAIBhAFJ3zf7/ungEwgORI
snVXe0l2hWnM9PTj68cA4J+dPIxFZz6cTAaj2Wx4MO12RJbJrDP/s5PvUrjVOb06/fDh4kOn24mF
UnyNtGMeRSyXjLNYxJ7I2KpI/DyUCdtwtRBZHCoFo1evGZCSIopg9SqMcGlfZX4/lf61yOMwEf1F
xHciu7ram3hhDtMiIHbmk/HBl24njYp1mHTmKx4p0e34MhAo2GQ8AEZu7uaZyIssYS/zTaicn1LY
2PkptARYivzVy4TH4vWPwHoyHtK6L3Q9gmu6GBOx/8MPNJrQiP3A/iPlGY9ZWjFz3Zrxf6s8C5M1
I+a0bmrW0WCvYmIk9KSM6M6+udOn0YxGaeFFof81G2r5/6T5B3+h932rSOvJoNZ6MjRaT0a21pNx
S+sFWZ69NB7AKW3DtC0wmbYmoM6MsZc3PCr0jD3LRpP9to3ut/RRnnN/E4skp1Uz236Tg3vtx4Og
XvWqqUpXC8wOmesiMLtGvooAlgbk5Rn3AWu/dV4M2KvXc1YD1nWXIrsRmfOTn3G1OSni9NXrzr+6
nbVIRMYjBCjcRtFBuGFvGogbkNUrwiiAQBtNJ4DrTObSB0TMR/vdDk9Dmjkc9QYwcw1hMO8MHvkP
LMj4dRR6uKa3TxwKcsm8cxYmxS1LIGrGbNwD7s7swCExwVovhqN956NXJHnBlucLdgk2eFdEbDRj
g4P5aDYfTtnHy2M2GsDF7WwPAhRYp5sUGE97e70xjD6LBHTqjGA40DevpCo3BgINIhpU0azQQEfL
D/jHyImjrmU0kLQ3Agov8o3MFLohfCfVpuA/n6ClyWC/lRYDgki4FwkQJc8KyBOBSEEwXAf3lFzl
JzYh5phSao6uG54fL05dF8Rw3TPJA5FhHoILmLa8PPpw+XEBhK3wVJijvJs8T9W83wdPbQqv58u4
X3HrozKg7LGMY54El4Cja5FZyrZudBtgGTa1Xvoyz9nPMD0Su6bmg2/XvCmB696R6OuqY4CAcm8X
Z3K9bqhVkZoKjZsKLU7PeXouAzSxrc53aJOKmKcxsQRPphFJ4brnnNKWUWVxsbz8dPHh7OQhP1oC
9pcxVDnn12NHZxDVh7Qr+jFXOdys9AVzfJJZFJwGYS5ti9jUplEGvbEzaPn6t84/obRCOsco41FY
ROBw20TfAXVLEtdtivVU+/BI/A5YySRI2Pd44Jig7qMdwjdZSBmhskFJaes/acLiLIyOs1Clu5E8
6B8laxFJ9ksYZKFsgn74HeGuJXkUMAzKL2Kx5sfnJ5Y+Famt0KAVuIIn63cijnfPlq/KrdsafD1K
T32ZyHj3TnqWBhaxnXJbTpGJ8OB/d+K0i4qYv6Pq75D+js14bMYTM57A+Bv1NmK4rtCS/y49121o
8QhX3i6LQFpW0OO2E1vZd2/y5s1g8Fx56kqzc13a2/x5cp3RTPp6Mfo4TvMdhbTt45r4AE7LRPNM
GNXswFUowBYFeARaH0wzde9VZZtGJn5/cvpL39IZM9ECOizhNxOyRbTNAljlrXR08l8Nkxx8u0WA
FVSlauNvrkvAx8EupW8pAXr+AtcfxJZntvstoqUnhOhfKvm10B5/p/K1NE/JvadKQe8ewrlvcWoj
2ya3Wqd2y3gm1ijRxQrtxi4Fj58N57YYd1vGxzuVJNQC9huqgQUWAk4gqyJapnybWCZo0hsOnvyl
g+2c/D0ObQjwFJ/+I+Pe3/na0qWkNCvRqLf/cJaq4Fri9Tny1hrk8fj6m6P0KWmr1B0M8wYo0H0n
atVoqRvkdiJvgV1t5HoT+umzQbxk6Lq2GM3Rk9N6ybTf4AIWWIZxGokj0MfS3yI2td9vV+oFmfoc
TK3jvPv89qiFcd2GYE+zQC1p3+KC4V7gIc92f0lp6j5p6468/IyvAFPvFu+f7ZBododwr8R4RIif
iJtLKSNlqVGRWun6Ti/SdmI7d32jIuX+rmtJ8s1Oq3jU/fXR4u3d/hqJ7f569v+ivwZZqv5aa/EI
vy8Twa/t0KWxZYBhq/s4zvhnEaBJs+cLUdz0KQXpuFC5jI8A3bmN2Aa5idq9pgtPb2S0BGmeTQV7
a9dtCfIAaAGz2+22J0AmZN/Lry2QLkUU3UUpUdsw3XsYpg+qaIfBE7CnQJ4KfEa4R/jxvfxFhnYH
bAiWZlAwG1plYRbm8O9zne5Kfq6r934KDI+ikNv40+N2d9tK+79y/2fuXzfd8u3y055a6OOIK/U4
yRdFJvBJvWqUrZLW1mD84PH6e0KnOl9XAliXT0/5uNJ0bTUXUPmcr0P/UkRiIbOc2zHVvtN6ENru
2L7W1H5nCxvn6VOw94bTKxMFp8pG51lTH1DjUuQbkYng6tkcaW2O7SYNHq/Q3zOY41OLbSlkU1uw
/N9O6dbWj30Ycn8mRxgeb3jeijUiNXW6c4C6L9QeShZWIN/RrgGQr4QgylVffXcAEhOrnm1kek89
Q+q/Uz0Deep6poV7TDcVrpNPPEsbZyFDanp62i4Lf3lUfjKK20dQer5mHkB17uYeBUJuQcj/k/Nz
ZZEv+GoRXzgLIJdq0CvaXprJFJqnUOB7yBeLasSOZbIK1ww/SXAzN3mx5Dk7KtZsNGKj8Xy6N5/W
Lz9xQizz4JCewDN6mrQsspvwhkd4T+/lpJD1D4ej4WiMxO0GlHSiUOWHAxzzJJFF4qMq+LmDw/1N
KG4EvqBWhzIhPvg8xUm1dcHBhxO9Nb81ixSw18yiSG6dVRSuN/mhXK3q1TwJYx6pJjGWXkVZg5li
GQgt1UpmIFJFM3M2PAt8mVXj9CY1IgbhahX6RZTvDofEjV555zJzlMjzMFmrQyRHoFnkIHIPz6Tn
7WqaEiKwpuAXJocnp2+OPp5dIlUj0/mjENnObGlIGcRQKQ9e91JoUrYyCw5/oH/AKEUuHcVvhFmI
76MrBPV2cYQQYAhM5pP3C5AcvxZAEDCwBKuPec75AkDBLjdCCVaqxngmGBQ7BhGu4AIg46Nbc+YJ
FiZ+VAQigAt2B3zIayljWLlCBm2eiq9El0msowpZMi+DgwzbySIzvFi4YuChcBXSDuCcDDACIQeM
34ttxa4fiBUH9yi2lcnfcsbTVPCMoWliUNYH4Ozwixz8bETrvd2IhBXpOuMBMOi5CeJZM5u7CXtx
uYGQcyIggRQRT9YFXwuGH+KQyQz2VQjjSAL/8DMZFZceb4RvtGguxC9cTOyLpLcNr8NUBCHvyWzd
x1H/DMLmSq6u3i4vrvbGB87oCteBGStGc+ZCGlu7Hdzo04Z6EPweSUHiYvhtkv44BdyEySviOdiN
bpM1SVKQA65ETi4NxE3oC7ahN+1IiYGxjo56S/oKCehqU+SBxMDS30OhMPqbEOZHUolAi3WEUcow
BeBnMiaFsZuQs/9EfMMUwnmZ3OYM0zEuhEKxZRxRqiRIY3bRruKGESsUgBBSNwCBtIPKBDOhDgRo
p/qGA2J5IFTN/pQiquQDGjMMdgZwBUSgqN6OGRzBdBN/1d3aDC8+hWBomQCkeBCwTCiNPBQTsHYN
4nAFlRtzHAO8eQLtAUYXfxScvh5bhzcwV39+88psCSn3NTDX+0HcC8yrDngTX7bP4S7u/L6gj84g
nI7ULvEvuboGxGfXEEA9vP8RnED4LJXEWZsMynABkIDZqsvo9RQzGQwg2wUzxGA1+uiIzAKlCmlx
kUDk4BTivSTIgD4QXJm8hXybCzABqENQTyrR0KpanLcrjFD6Xg4iscvC/G/4+VxGqwKB+Z5Q2FrL
XoEG4Gc2QouQDo7Rck6cMFoxdWc7itV/RNIDw2IJZ5oM6IvDHHMSli5vl4NAbKlFGdDmoUL36kgH
nbYhCUbGZlhkNJ/S/orssgoBLpCmIIUnxGoFOaLcUbsflCkItGsJekgMDbQZ7LMmIR0SbM6mw5FL
yYLycg7Jhgf/5gpgz1OKP0Y44t7QJ4eSkj8iXyFPn9KfYVqhewhIgMAO0KM0wwH0CY1rSpoygXQB
8QAyYix+TQUtOnQZEeVTjCw9zaXyhjwA63Xc6ODHHS4wYLGe0PTe3ckYq6ZFBFunwseyo8gkKKt2
hl5bKQD5VqSqVnM8MHqq1/cKZLQea63XPPPA1o4vo0j3Pojne61KrkNRzBpm1kCkxDwpqMDZUkDx
LwA0r7tlBLZQY2Cjs9hqVUZiXMOxxy50daGRguwviyioBAkhXrcJq0VHjOCnjCA5KLg3GGgd2Ys3
hLo7mYiwoldXSq0yGZcJDdea+46dAyyfghLGdW0o3IMfax22lv6mSK6VtvcZBRumHyKiZNjBozZM
t6BdCoUMyr3SkxysuNg51LyQVelmEycHe0bOE6mXtd2HKRf7Er3M5qB3MdOeQWdK+44P/bfQWhss
lBvhjapW/iUrN0lEjr6oGiWARqTrjsdzaPCx7OM3dTmUG8CTSV8UgLoNNHd11vJEVYGghSgrjUFs
eQcDP9vlyLvLnKEFZqw0tK2Tl6JAWpnu6axSVzbqvLGsBDrVGQfqtUA0MvXYz3C8APMeQucJwD1e
fOzCWpDAg/yzDYN8ozMkxXfF3iH2c7ZvynBdoBUZxpraY0cBxNOGR6s+tNS6ZwgE4MxsBFtq/MnE
DsiqFlq8rK7k9BaDD5sOHnV1YOPGn8IEejZQC2AjCNpYWT8ukkVZl+sOGVsOXEQfLWB7nKSOGdod
EJyHhFes56bE/8SGWNq1MxX2cHS77N8U5bGNKPs617hizoZ1V6ZYX+U8LwAw/bWvTYvfZipr0/Ik
1ejSRdmyodygiT6f0FQDL1SXHO6DEXNCmFni6CVzFsOtteneQSF6PIDi3uALCJ2UeIM/ZE48/+TW
9mDM/K40FKPkuhfvLy5P54yyLvznF3CUSeAoQ4zojSi6jsQzO1fiVS4+anjLh64dMonRlVBEJQkk
QdTkiJzRwJQQTGW6MiGM8MiIdFOOTNQ3yWUO053nEsMVFfS4EtZmr4YQKPfs0mUjuDG874bI/d5r
ClolbCkIDpfIGQ8y5ujPBCQmvR+Wfu1JOjLWZ0lMBHTmwE4F0wGPtnynNG/Dx8JRI38TjI5iWSR2
AVCmPyqFQPGRm0sf6xPjOZt8fSnPgBpo2TWPZtVhw4PRvasJXYnQpzZPaG6eWGEmoocamLHQDRVX
/ajDSn068y35DRRdPPiFeDgVeNhJd+YgbmpR1dBQoljR46UyLZo0tioimiYVQNXBEA19XUrowJPh
6ReAAWxLU/0u8dyhY0PhDw7whzYIaiwwlf4tZ6BBS2ec81vG23aBE4dP9aHGQ9MXBNIPcJgvlLXM
+IEb6ShI9VKDO5wP3QrmJHyo5BRpAFisBYSDreB6E3qoVVdBLXh9jCpl790V3uS/LQ/pRAyn30IY
/5r1FPZEdxQ4a85m38QtlWkRGW7mGktTi7GbUEw6YD0UWj86cwhHCi2JpowhV+f4gMNQhyY94HOm
OdPNXelSsFBSpNDs6I5PA5KSh240DC/gso+rzIbIdIrDLceNKiLReOyFgHw9xTzi0ifiuU5GeHjH
X6EwTdU11oBEo9d08lVyQ1w7+DilSanKSYOabtIwWckaBhuJvqcte9bTNWiESL5EJrsY23yKEAX2
VZWgeG4xt1l9mwQGrHHG12uoPuYoXj3kwB4Rf4tzfb82Wh5kp+6TB+2loUwubq8GTOi7c+2ALHFM
ca47QKLK1Ho8c4xP6OiRkYhkitWqC2PQAJ+H5WUrBp3JCjplAcaG+pRgncdJprQW6B2IR4sJM8/1
rR6igIZT5brAlQnPcEMP6dslf9UyCr5Busck+J5Xd77QKXGst3qADQvwN0LMS2noFoBd5RKg/Rte
Ohx/NYWEfyFHnQXLNsR+tklKlOcFfWgrnxfTaey+R6V0uKUqpqhjQLVjaCRCENSUeEt02pUEoCuG
j5cxdKkk1bvN2Zuzo8v56Mf97vTgdtgd3467ox+HPwZQiXXWeoVvFnzMMIezAVsDvpUeTaav6VGy
uM1FggahV93HUIesn0EhhKwhlIN19ZvF1MepZqD+iMJcjPVPtRz9w7DP+rdb+ksfz4e+ZlP/4JFH
EDk8qwn6N5nlqMiiarAKI3rnCazNN5GrPK3uruP6egPRq78ihEm/q+qlIb5Kij395LSaDD3hLs2r
4XJxRlvgW+DUh8at1i3nKGpgGSKVKrytLWFO0Oa13BB3/yBW5vgH1JdvwXneiI8Hg+lsbzbj/nQ2
8L3RbDb2JyP4v+HBKhiIwSCYjqfsJX3lF8taL0VoV7XoO7A3/UDNXLEp7jtEwzMH3+2MBtPBGC5p
59V4fyz4NAim0/Fsf284Gezx2WA04hNvxsf7k8lw5o0mA0E7LzboleqXarm8FgkUFmN/fFUm+DWk
AG0sege54/QOovyW43OYlr/6wx9ekIhhtfxXTO0XCyotQNzHn2eg3G9OO1++/A+xjga4
===END CRASH DUMP===

**Comment by SkygridRex** [comment]
Increase the memory to pocketmine

**Comment by SeangJemmy** [comment]
Still not work

**Comment by PEMapModder** [comment]
This is a plugin issue. If you want to know which plugin caused it, please find a crash dump that has more backtrace.

**Comment by SeangJemmy** [comment]
Thanks, but I already fix it. I deleted many player files and it actually work.

**Comment by PEMapModder** [comment]
This issue is caused by plugins assuming the player is still online while the player is already offline, hence the permission base being deleted by PocketMine.

**Comment by SeangJemmy** [comment]
Oh, can you tell me one of those plugins that cause this crash? Thanks

**Comment by legoboy0215** [comment]
PurePerms or GrabBag or EssentialsPE?
All has permission related (I am not sure about EssentialsPE)

**Comment by vvzar** [comment]
>> This issue is caused by plugins assuming the player is still online while the player is already offline
Can You add exception for this event? So people will know whatthe plugin  exactly makes server error. and exception may prevent server crash.
