### ISSUE TITLE
Update install script to download Dev build from correct URL

### ISSUE THREAD

**Issue by benny132** [PocketMine/PocketMine-MP#3403]
Hi Team,

Since the URL change to the Dev phar location running the following command doesn't work anymore
wget -q -O - http://get.pocketmine.net/ | bash -s - -v development

**Comment by SkygridRex** [comment]
Are you using linux?

**Comment by benny132** [comment]
Yes…Specifically pre-made docker container running on a synology NAS, however when i sent the requests to the creators of a couple of the docker files the response i get back is that thats the official way to install the dev version and its something pocketmine would need to fix.

Regards,

Ben Martin

**Comment by SkygridRex** [comment]
If you want try with other linux version. yay

**Comment by flaxues** [comment]
http://cdn.pocketmine.net/api/update-development.phar

For latest Pocketmine build (#1258)
