### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FunnyCrafteur** [PocketMine/PocketMine-MP#3404]
Hi !

Help me please I have an error

[36m14:40:59[m [31m[ERROR] Could not load level "world": zlib_decode(): data error[m
[36m14:40:59[m [33m[WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT__64bit" at line 124[m
[36m14:40:59[m [31m[EMERGENCY] No default level has been loaded[m

===============FILE LOG===========================
[36m14:40:58[m [37m[INFO] Loading pocketmine-soft.yml...[m
[36m14:40:58[m [37m[INFO] Loading pocketmine.yml...[m
[36m14:40:58[m [37m[INFO] Loading server properties...[m
[36m14:40:58[m [37m[INFO] Selected English (eng) as the base language[m
[36m14:40:58[m [37m[INFO] Starting Minecraft: PE server version [36mv0.11.0 alpha[m
[36m14:40:58[m [36m[NOTICE] The memory-limit setting has been deprecated.[m
[36m14:40:58[m [36m[NOTICE] There are new memory settings on pocketmine.yml to tune memory and events.[m
[36m14:40:58[m [36m[NOTICE] You can also reduce the amount of threads and chunks loaded control the memory usage.[m
[36m14:40:58[m [37m[INFO] Opening server on 92.39.243.162:19146[m
[36m14:40:58[m [37m[INFO] This server is running PocketMine-Soft version [33m1.5dev-245[37m "??????(Kappatsu)??????(Fugu)" (API 1.12.0)[m
[36m14:40:58[m [37m[INFO] PocketMine-Soft is distributed under the LGPL License[m
[36m14:40:58[m [37m[INFO] Loading EssentialsPE v1.0.2[m
[36m14:40:58[m [37m[INFO] Loading EconomyJob v2.0.2[m
[36m14:40:58[m [31m[CRITICAL] Could not load plugin 'ChestShop': Unknown dependency[m
[36m14:40:58[m [37m[INFO] Loading EconomyAPI v2.0.4[m
[36m14:40:58[m [37m[INFO] Loading EconomyShop v2.0.3[m
[36m14:40:58[m [37m[INFO] Loading EconomyAirport v2.0.2[m
[36m14:40:58[m [37m[INFO] Loading SimpleAuth v1.7.1[m
[36m14:40:58[m [37m[INFO] Loading EconomyAuction v2.0.1[m
[36m14:40:58[m [37m[INFO] Loading EconomySell v2.0.3[m
[36m14:40:58[m [31m[CRITICAL] Could not load plugin 'ChestShop': Unknown dependency[m
[36m14:40:58[m [37m[INFO] Loading EconomyCasino v2.0.1[m
[36m14:40:58[m [37m[INFO] Loading EconomyLand v2.0.5[m
[36m14:40:58[m [37m[INFO] Loading EconomyTax v2.0.2[m
[36m14:40:58[m [37m[INFO] Loading EconomyProperty v2.0.2[m
[36m14:40:59[m [37m[INFO] Enabling SimpleAuth v1.7.1[m
[36m14:40:59[m [37m[INFO] [SimpleAuth] Everything loaded![m
[36m14:40:59[m [31m[ERROR] Could not load level "world": zlib_decode(): data error[m
[36m14:40:59[m [33m[WARNING] RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT__64bit" at line 124[m
[36m14:40:59[m [31m[EMERGENCY] No default level has been loaded[m
[36m14:40:59[m [37m[INFO] Disabling SimpleAuth v1.7.1[m
[36m14:40:59[m [37m[INFO] Stopping other threads[m

**Comment by SeangJemmy** [comment]
Full Memory, increase the memory size

**Comment by TahaTheHacker** [comment]
ok i know. But HOW?

**Comment by SkygridRex** [comment]
To increase the memory size edit the file "pocketmine.yml" and look this #3370

**Comment by TahaTheHacker** [comment]
ya But i use devolopment build and pocketmine 1.5 dev-1258 not soft and there isn't the massage.
Thanks.
but Help

**Comment by PEMapModder** [comment]
@SeangJemmy that has nothing to do with memory at all...
