### ISSUE TITLE
Server not found when online and is 2/25

### ISSUE THREAD

**Issue by UltimateMcraft** [PocketMine/PocketMine-MP#3405]
I try and join server and it can't be found but i checked and its online and has 5 players out of 25

**Comment by TahaTheHacker** [comment]
Maybe RakLib Thread blocked your IP for seconds check your server console

**Comment by TahaTheHacker** [comment]
or else check if someone IP banned you

**Comment by UltimateMcraft** [comment]
@TahaTheHacker
How do I know if im ip banned? It doesent say

**Comment by UltimateMcraft** [comment]
Hopefully when you join it will say 
You are ip-banned
In the future it turned out someone banned me. I banned them and pardoned myself

Thx guys

P.S How do I submit request to add that feature?

**Comment by TahaTheHacker** [comment]
No it won't say "You are IP banned" like MCP, you will just be unable to connect to the server USING the banned IP. to know if you're IP banned. try know your IP and do /banlist ips and check if your IP is banned.
Thanks!
