### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BenjaCanoodles** [PocketMine/PocketMine-MP#3406]
Can someone please help
![screenshot_2015-08-23-09-19-10](https://cloud.githubusercontent.com/assets/13936404/9431478/204c9682-49c7-11e5-9b09-8961e75c5f8e.png)

**Comment by flaxues** [comment]
Please post the Crack Dump

**Comment by BenjaCanoodles** [comment]
Whats the Carck Dump?

**Comment by flaxues** [comment]
Crash dump*

**Comment by BenjaCanoodles** [comment]
But still what is it
