### ISSUE TITLE
Issue with versions

### ISSUE THREAD

**Issue by TropicalGamer** [PocketMine/PocketMine-MP#3408]
I can't download 1.5 dev versions (soft and development).
It says failed to download the version.

**Comment by thebigsmileXD** [comment]
#3407 Duplicate

**Comment by flaxues** [comment]
http://cdn.pocketmine.net/api/update-development.phar

For latest Pocketmine build (#1258)

**Comment by ultimatecraftxd** [comment]
I heave a same problem pls help

**Comment by EsmailELBoBDev2** [comment]
**SAME**

**Comment by ChaostixZix** [comment]
@EsmailELBoBDev2  Man, The Repository Is Moved to [pmmp](https://github.com/pmmp)

**Comment by thebigsmileXD** [comment]
not really xD pmmp is "just" a fork

**Comment by ChaostixZix** [comment]
@thebigsmileXD ohh, ok .sorry, i dont understand about github :(
