### ISSUE TITLE
setHealth() bug

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3412]
when i use $player->setHeath(20) and player has not 20 HP so it kill him and player cant respawn

**Comment by PEMapModder** [comment]
Use Entity->damage or Entity->heal instead.

**Comment by Creeperface01** [comment]
it is the same like setHealth() it kills player and player can not respawn

**Comment by MajikalPayton** [comment]
Have you actually tried respawning the player?

**Comment by xpyctum** [comment]
player can't respawn after kill +
I was get this bug yesterday

**Comment by iVertx** [comment]
Also happens on 1.6 when the player eat a golden apple...

Well, probally that will be solved when 1.6 got official support, 👌

but ↑ that is a big problem :/ we don't want that the player click on the "Main Menu" and never more come back to the server, lol

**Comment by alejandroliu** [comment]
Same happens to me... When the player dies with setHealth, they can not respawn.  Actually, the player is dead on the client, but the server still shows the player as alive.  If then use /kill to kill the player, they are able to respawn.

I am not sure if this is a client or a server bug.

**Comment by MCPEGamerJPatGitHub** [comment]
That's a server side bug.

**Comment by alejandroliu** [comment]
What is your evidence that it is a server side bug?

**Comment by PEMapModder** [comment]
It is apparently a server side issue. If the server does something that is not expected but it is possible to do otherwise, it is a server side issue. Even changes in the protocol should be regarded as server side issues.

**Comment by MagicDroidX** [comment]
But attack and heal method also invoke setHealth right?

**Comment by Intyre** [comment]
Did I miss anything? https://gist.github.com/Intyre/9f76aed8c17005de632d

**Comment by TigerHix** [comment]
Holy jesus. I can confirm this issue is NOT solved. I have been trying to solve this for a whole week.

I swear this is working in 1.4 (API: 0.11.x). When it comes to 1.6, with the same plugin code, setHealth(20.0) manages to kill my player and the respawn button remains gray. I have no idea why.

**Comment by PEMapModder** [comment]
Should have been resolved in #3978
