### ISSUE TITLE
level unload bug

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3413]
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/level/Level(536): pocketmine\level\Level->getName(boolean)
#2 /src/pocketmine/Server(1037): pocketmine\level\Level->unload(boolean)
#3 /Bedwars/src/BedWars/Arena/Arena(293): pocketmine\Server->unloadLevel(boolean)
#4 /Bedwars/src/BedWars/Arena/Arena(249): BedWars\Arena\Arena->stopGame(boolean)
#5 /Bedwars/src/BedWars/Arena/Arena(164): BedWars\Arena\Arena->checkAlive(boolean)
#6 /Bedwars/src/BedWars/BedWars(283): BedWars\Arena\Arena->leaveArena(boolean)
#7 /src/pocketmine/command/PluginCommand(57): BedWars\BedWars->onCommand(boolean)
#8 /src/pocketmine/command/SimpleCommandMap(195): pocketmine\command\PluginCommand->execute(boolean)
#9 /src/pocketmine/Server(1938): pocketmine\command\SimpleCommandMap->dispatch(boolean)
#10 /src/pocketmine/Player(2580): pocketmine\Server->dispatchCommand(boolean)
#11 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(boolean)
#12 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#13 /src/pocketmine/network/RakLibInterface(79): raklib\server\ServerHandler->handlePacket(boolean)
#14 /src/pocketmine/network/Network(150): pocketmine\network\RakLibInterface->process(boolean)
#15 /src/pocketmine/Server(2471): pocketmine\network\Network->processInterfaces(boolean)
#16 /src/pocketmine/Server(2223): pocketmine\Server->tick(boolean)
#17 /src/pocketmine/Server(2101): pocketmine\Server->tickProcessor(boolean)
#18 /src/pocketmine/Server(1701): pocketmine\Server->start(boolean)
#19 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(boolean)
#20 (1): (boolean)
#21 (0): {main}(boolean)

**Comment by Creeperface01** [comment]
im not sure but this is pocketmine bug too maybe

Fatal error: Call to a member function getName() on null in phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 2731

Call Stack:
    0.0248     383176   1. {main}() C:\Users\Honza\Documents\PocketMine-MP\PocketMine-MP.phar:0
    0.0292     377712   2. require_once('phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Honza\Documents\PocketMine-MP\PocketMine-MP.phar:1
    0.7987     520032   3. pocketmine\Server->__construct() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
    5.9509   16379856   4. pocketmine\Server->start() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:1701
    5.9651   16396160   5. pocketmine\Server->tickProcessor() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2101
  322.3192   70373280   6. pocketmine\Server->tick() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2223
  322.3465   70375328   7. pocketmine\Server->doAutoSave() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2512
  322.3466   70375424   8. pocketmine\Player->save() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server.php:2361
  322.3574   70363904   9. pocketmine\level\Level->getName() phar://C:/Users/Honza/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php:3107

**Comment by SkygridRex** [comment]
Are you changed some code?

**Comment by Creeperface01** [comment]
No

**Comment by Creeperface01** [comment]
Maybe pocketmine 1.6 bug

**Comment by SkygridRex** [comment]
shogui said's don't report issues from PocketMine 1.6 it's under-develoment
