### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Takabrycheri** [PocketMine/PocketMine-MP#3416]
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 332853 bytes) in phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 1915

Call Stack:
    0.0002     127440   1. {main}() C:\Users\Present\Desktop\HappyCraft\LOBBY\PocketMine-MP.phar:0
    0.0328     413264   2. require('phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\Present\Desktop\HappyCraft\LOBBY\PocketMine-MP.phar:1
    0.9543     548216   3. pocketmine\Server->__construct() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
   16.2548   16078296   4. pocketmine\Server->start() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1778
   16.3008   16093552   5. pocketmine\Server->tickProcessor() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2178
 8562.2062 1067790840   6. pocketmine\Server->tick() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2300
 8562.2724 1071961896   7. pocketmine\Player->checkNetwork() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2500
 8562.2724 1071962128   8. pocketmine\Server->batchPackets() phar://C:/Users/Present/Desktop/HappyCraft/LOBBY/PocketMine-MP.phar/src/pocketmine/Player__32bit.php:1563

**Comment by SkygridRex** [comment]
Increase the memory size

**Comment by Takabrycheri** [comment]
I have already 1100MB for the server!! This is an server very big XD

**Comment by Takabrycheri** [comment]
Okay

**Comment by Takabrycheri** [comment]
:+1:
