### ISSUE TITLE
I need help for port forwarding of PocketMine servers

### ISSUE THREAD

**Issue by PIANOCRAFT6000** [PocketMine/PocketMine-MP#3417]
I have a router and a pocket WiFi on router I cannot search in google (router is very useful) and pocket WiFi I can search at Google but cannot be port forward please help

**Comment by Subtleoliver** [comment]
This isn't an issue. Try asking this on the forums. and this 'question' doesn't make any sense.

**Comment by manh994** [comment]
1, Make sure your network opening the port you want ( cuz maybe it's blocked by Service Provider ).
2, Go to 192.168.0.1 set the portforwarder (or NAT) to your local IP with port.
3, Then check your firewall for that port. (windows: go to control panel -> firewall -> advance -> you add that port to both inbound and outbound. Linux: check your iptables config).
4, Config your server and test it.
