### ISSUE TITLE
Multicraft Error Failed to install file: [Errno 13] Permission denied: u'/home/minecraft/multicraft/jar/pocketmine.phar.conf

### ISSUE THREAD

**Issue by KoKuYT** [PocketMine/PocketMine-MP#3419]
pocketmine.phar.conf: Failed to install file: [Errno 13] Permission denied: u'/home/minecraft/multicraft/jar/pocketmine.phar.conf

This error happens when I try to install Pocket Mine on Multicraft Help anyone?

**Comment by manh994** [comment]
i dont know what is that file but you can chmod it to 777

**Comment by KoKuYT** [comment]
Its the conf files so it works on multicraft

**Comment by SkygridRex** [comment]
Are you using windows?

**Comment by PEMapModder** [comment]
You have to chown it.
It isn't PocketMine issue anyway.
