### ISSUE TITLE
 INFO Warning: require(phar:///jar/MCPE/src/pocketmine/PocketMine.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///jar/MCPE/src/pocketmine/PocketMine.php" in /jar/MCPE on line 1

### ISSUE THREAD

**Issue by rohanmcdermott** [PocketMine/PocketMine-MP#3421]
Trying to start a server using Multicraft on a Linux server running CentOS.

I have followed a few tutorials but I'm still getting errors.
When I start the server, I get:
 INFO Warning: require(phar:///jar/MCPE/src/pocketmine/PocketMine.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///jar/MCPE/src/pocketmine/PocketMine.php" in /jar/MCPE on line 1

**Comment by SkygridRex** [comment]
Pocketmine API has been changed those tutorials doesn't work

**Comment by rohanmcdermott** [comment]
Ok, so how can I do this?

**Comment by rohanmcdermott** [comment]
I want to be able to control MCPE servers on Multicraft using PocketMine.

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
