### ISSUE TITLE
Pocketmine api 1.12.0 soft download won't download

### ISSUE THREAD

**Issue by williamal** [PocketMine/PocketMine-MP#3431]
Whenever I try to download the soft version it won't download. All the other versions download fine but the soft just wont.

**Comment by PEMapModder** [comment]
This is an issue with the download server, not with the PocketMine software itself.

**Comment by SkygridRex** [comment]
are you using pocketmine-mp or droidpocketmine?

**Comment by williamal** [comment]
I'm using pocketmine-mp

**Comment by SkygridRex** [comment]
i think the download link it's down

**Comment by williamal** [comment]
Do you know when it will be back up or if it is switching to the 0.12.1
minecraft ps update?

**Comment by SkygridRex** [comment]
i don't know when the download link will be back and the pocketmine team first work on a develoment build and later work on pocketmine-soft, so, you need to wait a long time

**Comment by Galang23** [comment]
pocketmine 1.6dev.phar link?

**Comment by PEMapModder** [comment]
This is not a forum or support channel. Please use the forums or the IRC channel if you wish to get support.
