### ISSUE TITLE
Compound::$item

### ISSUE THREAD

**Issue by Artide** [PocketMine/PocketMine-MP#3433]
No new plugin or changes, just updated pocketmine and started getting so much crash dump. Heres the crash: 31.08 01:18:19 [Server] Server thread/NOTICE UndefinedPropertyException: "Undefined property: pocketmine\nbt\tag\Compound::$Item" (E_NOTICE) in "/src/pocketmine/entity/Item" at line 72

**Comment by flaxues** [comment]
maybe post a CrashDump

and it think this is a duplicate of #3461
