### ISSUE TITLE
How install PocketMine on debian 8?

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3438]
How install? And stop delete my posts! Decide if we undertook this forum!

**Comment by flash586** [comment]
Can't help? Close forum, not my posts!

**Comment by legoboy0215** [comment]
This is not a forum!! This is a issue tracker....... *facepalm*

**Comment by flash586** [comment]
Forum in which to discuss the problem and decides, slow...

**Comment by legoboy0215** [comment]
http://forums.pocketmine.net/forums
HERE is the forums. Now, again this is an issue tracker with PM.
