### ISSUE TITLE
Time Not Correct ( United Kingdom )

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#3442]
My Time on the laptop and time on the server arn't in sync. ( Proof in this link http://snag.gy/XPvKQ.jpg ) 
I have tried to change the time on my router back to normal time, but pocketmine is still an hour behind.

Just asking now, but, could this be a problem for other people not being able to run their server ?
( just a honest question )
Its nothing much, but i believe its still a bug.

Hope i helped, 
TheDeibo

**Comment by SkygridRex** [comment]
You can change this on php.ini

**Comment by thebigsmileXD** [comment]
Actually, same for germany.
changing the php.ini doesn't work properly

**Comment by CyberPowerCrazii** [comment]
Try using some plugins like custom alert. It displays actual time from your time zone. Sorry if I posted a plugin.

**Comment by PEMapModder** [comment]
This is an issue tracker. Using plugins does not help with solving the issue on PocketMine.

**Comment by Intyre** [comment]
Already fixed with c1a484e
