### ISSUE TITLE
Not download PocketMine on Debian 7 amd64

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3446]
I found screen when this program work on my VDS, though your "assistant" intare claimed that I just do not know how to install server! https://pp.vk.me/c628229/v628229770/11f57/8q9KNs6_Zao.jpg When you fix this issue, not close this post. Now I see this 15-20 minuts and line $ 
https://pp.vk.me/c628229/v628229770/13082/BPrNnvQ-Iqo.jpg

**Comment by flash586** [comment]
I install "perl gcc g++ make automake libtool autoconf m4" and "gcc-multilib"

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
