### ISSUE TITLE
My VDS can't see site. Sorry Intyre, but you are wrong)

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3449]
I turned to support and learned that their VDS can not see get.pocketmine.net. And so wget command can not be completed. Do not tell me how to fix it? Linux (Debian)

**Comment by shoghicp** [comment]
This place is only for PocketMine-MP bug tracking, not install scripts or website support
---
Seems like a problem with your DNS. You can also download the script manually and upload it to your server
