### ISSUE TITLE
My friend is at his house and cant connect to my server at my house

### ISSUE THREAD

**Issue by JordanFisher2000** [PocketMine/PocketMine-MP#3457]
I am playing on my server at my house. I want my friend to join my server. I gave him my server IP and port. It wont work for him. Please help! We really wanna play with eachother.

**Comment by TahaTheHacker** [comment]
did you port forward?

**Comment by JordanFisher2000** [comment]
Yes I specified my ip and added my source and destination ports as 19132.
And the protocols were set to both (TCP, UDP).

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
