### ISSUE TITLE
PM1.6 fails to start

### ISSUE THREAD

**Issue by Alicesonw** [PocketMine/PocketMine-MP#3459]
Parse error: syntax error, unexpected ')' in phar://E:/Pocketmine12.1/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream__32bit.php on line 197

**Comment by Pub4Game** [comment]
Parse error: syntax error, unexpected ')' in phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream__32bit.php on line 197

Call Stack:
    0.0236     435136   1. {main}() C:\PocketMine-MP\PocketMine-MP.phar:0
    0.0270     429896   2. require('phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\PocketMine-MP\PocketMine-MP.phar:1
   64.7475     596768   3. pocketmine\Server->__construct() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
   65.3703     810480   4. pocketmine\network\Network->__construct() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1588
   65.3703     810704   5. pocketmine\network\Network->registerPackets() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/Network__32bit.php:125
   65.3709     818048   6. pocketmine\network\Network->registerPacket() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/Network__32bit.php:308
   65.3709     818264   7. spl_autoload_call() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/Network__32bit.php:222
   65.3709     818312   8. BaseClassLoader->loadClass() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/Network__32bit.php:222
   65.3713     821672   9. include('phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/protocol/LoginPacket__32bit.php') phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:128
   65.3713     821888  10. spl_autoload_call() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:36
   65.3713     821936  11. BaseClassLoader->loadClass() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:36
   65.3717     825376  12. include('phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/protocol/DataPacket.php') phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:128
   65.3717     825576  13. spl_autoload_call() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:41
   65.3717     825616  14. BaseClassLoader->loadClass() phar://C:/PocketMine-MP/PocketMine-MP.phar/src/spl/BaseClassLoader.php:41

**Comment by TahaTheHacker** [comment]
This is 1.6. AND it's under Maintenance.

**Comment by KhaledCraft** [comment]
ابي احمله

**Comment by TahaTheHacker** [comment]
Please don't speak in Arabic (My language) here.

**Comment by Alicesonw** [comment]
When I use the 64-bit PHP,it still does not start.

**Comment by TahaTheHacker** [comment]
use PocketMine 1.5

**Comment by TahaTheHacker** [comment]
PocketMine 1.6 is under maintenance. so don't use it

**Comment by Alicesonw** [comment]
If you do not use it how you will know what will happen?

**Comment by TahaTheHacker** [comment]
i did. it just won't start.

**Comment by TahaTheHacker** [comment]
Use PocketMine-MP v1.5

**Comment by Alicesonw** [comment]
I waiting it.

**Comment by PEMapModder** [comment]
This is not a forum. Please stop commenting on an invalid issue.
