### ISSUE TITLE
Player::hasFirstPlayed returns a consistent value

### ISSUE THREAD

**Issue by PEMapModder** [PocketMine/PocketMine-MP#3463]
`Player->hasPlayedBefore()` returns whether the `Player->namedtag` property is an instance of `Compound`, which is always true as it already has a value assigned its constructor. As an API function, if this function is not expected to return whether the player is playing for the first time, this is misleading.

**Comment by shoghicp** [comment]
This is useful for the IPlayer interface, when you get an IPlayer that can be an OfflinePlayer or a Player

**Comment by PrimusLV** [comment]
[code]
Player->hasJoinedBefore()
[/code]
Add new function?

**Comment by SonyBravia** [comment]
Hi : p

**Comment by MagicDroidX** [comment]
In my opinion, since you've got an Player object, this player must has first played.

**Comment by PEMapModder** [comment]
@MagicDroidX the Player object is constructed when a connection is registered, even before the username is sent.
