### ISSUE TITLE
PocketMine-MP 1.6 Crash Dump

### ISSUE THREAD

**Issue by tylrng** [PocketMine/PocketMine-MP#3466]
PocketMine-MP Crash Dump Sat Sep 12 04:46:43 UTC 2015

Error: syntax error, unexpected ')'
File: /src/pocketmine/utils/BinaryStream__64bit
Line: 197
Type: notice

Code:
[188] 	public function getUUID(){
[189] 		return UUID::fromBinary($this->get(16));
[190] 	}
[191] 
[192] 	public function putUUID(UUID $uuid){
[193] 		$this->buffer .= $uuid->toBinary();
[194] 	}
[195] 
[196] 	public function getSlot(){
[197] 		$id = \true);
[198] 		
[199] 		if($id <= 0){
[200] 			return Item::get(0, 0, 0);
[201] 		}
[202] 		
[203] 		$cnt = \ord($this->get(1));
[204] 		
[205] 		$data = \unpack("n", $this->get(2))[1];
[206] 		
[207] 		$nbtLen = \unpack("n", $this->get(2))[1];

Backtrace:
#0 /src/pocketmine/network/protocol/DataPacket(41): spl_autoload_call(string pocketmine\utils\BinaryStream)
#1 /src/spl/BaseClassLoader(128): include(string phar:///root/download/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/protocol/DataPacket.php)
#2 (): BaseClassLoader->loadClass(string pocketmine\network\protocol\DataPacket)
#3 /src/pocketmine/network/protocol/LoginPacket__64bit(36): spl_autoload_call(string pocketmine\network\protocol\DataPacket)
#4 /src/spl/BaseClassLoader(128): include(string phar:///root/download/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/network/protocol/LoginPacket__64bit.php)
#5 (): BaseClassLoader->loadClass(string pocketmine\network\protocol\LoginPacket)
#6 /src/pocketmine/network/Network__64bit(222): spl_autoload_call(string pocketmine\network\protocol\LoginPacket)
#7 /src/pocketmine/network/Network__64bit(308): pocketmine\network\Network->registerPacket(integer 143, string pocketmine\network\protocol\LoginPacket)
#8 /src/pocketmine/network/Network__64bit(125): pocketmine\network\Network->registerPackets(boolean)
#9 /src/pocketmine/Server__64bit(1600): pocketmine\network\Network->__construct(pocketmine\Server object)
#10 /src/pocketmine/PocketMine(465): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/download/PocketMine-MP/PocketMine-MP.phar/, string /root/download/PocketMine-MP/, string /root/download/PocketMine-MP/plugins/)
#11 (1): require(string phar:///root/download/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #18 [Protocol 34; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vultr.guest 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64
PHP Version: 7.0.0RC2
Zend version: 3.0.0-dev
OS : Linux, linux

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWm1v28aW/isDuUDthah3yza7DpDrJrtZOI23dlBgq8IYkUOJNTlkOUPLapH/vs85M6QoxWmz
N13gfkiQtuJwzus8523YP3o2zVUvHM9mk9F0in/6vUwa+6qqiqoX/tGz2xKve7qwaaR6/V6ujJEr
WjJbbeWTULSzL2qtnkoVWRWLb0++xcakzrLXaUY7y7WswuFwWBWFHcbFRmeFjIc3RfSg7NtUq+Dt
zf7TgCiGpoqGJS/nWB7WNs3M8B+pltX21lZK5vf389kytdhdkkAn7LPJQJJhA2y/OOv3bCVhX/hz
72gkDlloZTdF9TAsq8IWUZENv5dW3kh6fzwbn4TClNm9rG1Bdt1HMsuOja1SvRI7JosFK7JYdDU5
gQ5HYycPPIb/kEZdwf3mGoxUdTyenIN7qqOsjlXL82/x5p/YRP5kzSbiGOIPlApekDxeeM5Kz3ex
aBgvFjvOzHX61/69LlapdiT+sI6n88/1819rMPvX8PjHVraeP/17PN+RwGznn3T9D+6/jbcnk8kX
uPtQ7Nnnip2OyPvPcvc7gxeVWqXGqsrHX6qtWqlKjGfTvvjn1Dv/XPXGk9P/o3rmeFkUmZKaBV18
JOhWVY+qavnPR6O/FHB/HxUahtaRPe7udKxEsfwVWdgllo8z2Q6lx7P5oTGOw6clXBV5KW26zLqg
9AL7z6W6tzLVcPaqs+vLIqql/1PCz9tVZjVgYIbOVWNxTIm8Ur/VafU3B/5uh4vvXz70e+rL6+sX
lDso4MzvhYnMjOr3oiJWpM74/BxMF7asl1kaiaTWkU0LLVbKvn//5vvjkz/AZ3x+wZsW4G/rSgt6
FYZJVeRO8PE3dp2a4AWoAOqTk++I6GLERB/49xi/+cfkWXFl7cTRv8Q3dZ3GTvDF1Av2ApZ1kgBd
g0u3KXhhC6+BlznryDxtZM4/ZeJtVlhv4sVZIymNxaVYwNZaeabn/hU/NK5Ik2Pa+u+XYsQcJqOR
f9O66Y1VeRiSU0Z9QX+Z32Q09hs/8NNkxx3tWKNFpC2rUVTxnndPPI9Zl+q0oYpR+Jis1iUS0vGi
pxe9vugwmJyc/Dz+xfGYd3m09uulvVb687h8+NpIfW2kvjZSXxupr43U10bq/7+R6vdWSqtKZtS6
wOUGdRxlazyYx+oR6izrNIvR8Zyj3/Go7YXTWb8nyxT7JoPRYIRtK3RHYW/0mX9AUMmHLF0SzeCM
OdRa0i1K7zrV9ZN4rDNbDVa1MlZMB2MICSaTC2ydDFR2Nng6nwOnAvXq9u2NuKuV+K9ai8lUTCbh
aB7Che/vrgTaglPhtkIAXXGEvTNS+MerCRZ+VxqW9aa0Ejhrsee+MI0WWOCHjB+o45MVlEREYfVn
uM4wSgdwTKkqmyrafHTTPomrQifpSlCfuagW+uhWWnGrSjGeiNEsnM3D2bRVlDbkhY0v6XCiSiY2
FDevhAsEeumEBWVR2Ut0f9MJLW7WqVVBhjC/LJKEVqTWBfoxFZSZ3GK/jNapelS50tZcFpo5lXKj
AzpOxX3b5XjO0uWTJzKXkxHzyrJiEyRZulq3/B2x1GmOtnePYV4sm4UV3JSjH75kNklRQZ92zTMC
OuOoqNrn8rH01HGaJGkEBGwvx8yNEWqLKjDKWgSDuaTlDGZlAcHmEukoi3drRqm4s4UGhMvvX71+
+f76jlaVlkgcwW+1qrZepF+qkG0afej3oERyAfP48t/4D1yCGhQY+ag8IYGmDa/BNs8IAoKyjYj4
9GtoTr0xgUDAE2IvSAEKcbdWRonGNCErJexaiUIDQXYNyER0plYsVdMMxPghPgIf8botclAmxOCQ
p5GJ6osCbypDLMUSbd+D2BZ15XmJNBE4oTRJWQIOpwJAsi0x/kFtWnbDWCUSx2PEptDfWiHLUslK
kGtyGEvVeQv1BTW3zu7NGu1vXa4qGYPBYKEJzo5ZuNDi6G5dKcAYS9Aik3pVY4ATNFGxyzz0TYrn
rAD/9Hd2KpFerVXkrdgnhAJra0uDpKn0YJM+pKWKUzkoqtWQnobXiJr7Irl/c/vufj69CCb3RAc3
toxCsegpvVr0SNBPa0W+E7aAPjoWsNIndxxTJbXJJI2W/Jq9yZpCD/xSlo8USQYjqlhLHWd8yDkY
u+jYieRxEutmXVvK84GfZ0kZX1ijrDAqdmq9pBgVlAG4SrhKIh5TKf6b8I0tjPPAvwkFTWFEeLsG
nSSUGrQFwktxRyU9I1EbgDBWJYDA1r28eYOddl3E5KfdiwBqLaHUjv0rjqiGDywWFOwCcAUiSNXl
VngcYbuPv/btzg1HP6VwdKEBKRnHqIrGIY/UBNYeoI40dcUJTgBvS0X+gNNRPmVGx7FKH7H3UWYo
E8deJFLuCZg7eYh7RWk1wGlShxDiLUn+oc6X1C8k4qXZ6uhOmgdBjQ8CaEDv3+MQGJ+NkbRrXRVI
wIAEdpu+4MwkfAYDZPtwQw6vGSq07JaNWtJaXmtEDm1h3rcMGdiD4KqKJ2Rbq+ACmMNQ161q5FWn
zpuEIpS2UCT2RWq/hedsxVSxomTPKDygFcewAOcsJuQRtiHwVobMiaKVUne15Vj9j6xYwrGmSKxw
y0BfnlrKSblayeXWQiFx61QZsfDU0PG6SIdNm5QVY2cLKjGOT+N/w35J0Pzgh0AK18wqQY5oJLrj
hzE1g3ZVwI6CQoN8BjkrVjJgxUIxWnCq4KxskWpk/C+ufg5N/0R5Kp1fpLyxRcnyfapq9fHcjEBI
Ue1DlvHakMxGpfFoMnNa3agqLbgcUSwaEhhxQvbatfE2hiikmpgwxjsCxINykcZpvNBIYIhQ+I2y
w6fc6tyJtifjDE+x7rYtuOASD0TfLpJdOiIJ7yiFUIXj7YOPN5PZLg/FcGGpIiqEht1CujofO9rW
AHhSlWZn5nTk7TQnzyrkrZ46q1eyWuL8AzTVmWvFKMKe9SrDiVTxNMLTIHZzqWsuuV0t0I7UwMJJ
v8kJB2DwaHB5NUma3JDvUDYQ71y94ycgYl3UWdwqkiKDbLTYqU64FSVrDgMxPjobxdFrjoSPciNj
xVG3RtH9Z5Niida/D7pZqXOmMMIf3SEUnsFPh4463Whd6wfj/H3NqKeEyIukGU1XZI1wHXGfw7NC
A2LcpoB6AOpldryIVXPMPlAu5l7P7wtHdnh8VASoU3JkXQ5Oit/2N9jMhSiIMA4oZ7XHQiOIXrTV
+09ZLbS/CWhbN0Ajc5VwKS3mDWpE3J1Dn0DssxIHoGtM/VuXjJaqrYmcbo666at5Q4FfbS3x7otg
3AEz1T4WG9hGFaSV07nLKrtay7MAFbrYpTt/gI4Wi16ngfhPjDtw7yV6YQD36uZ9H7TQYIn8s0lj
u3ZZm+O7ZR8w+1Cc+cZg1zIYdkxn60C8jBFPa5klQzT5rouJFXDmBUGkw1+huwHZVucOr06f9OqJ
go/aIJn1XWCT4J9SjS4SZgE2iqFNtf79jb5pOoVdz05NEBFtkOsX1LDrMvCP3Z4ME5pa1qvQNx0v
xJiaDV9ZqKvk101HaTiPrVXTaS78UaCM7PpEI4bGSlsDMMNV5FyLvBabjtBmttubG1TTRJLesMRN
TLzVw4vM5QOP4ETLCPMkgSMJRR7RVZmbJ2AQAZ36NA3IAaSclOQef2ROmshsRzycaT/WhmOUj+7o
h3d3r0LBWRd/oxrDlcZwxYzSvMy4g2X1vORWvfaIX+6dVoQ5ApnE28oo4pIETQg1lpAzGfkSQqnM
VSaCEQ2xtO7LkY/6/eUmh7le+JbClQxcSqM6wo7HCJRnpPTFBC/Gz71QNhqccNAa1dWC4XBHnGm0
8jcRQiExOXlU+t1J8hC7m24pEfAURN0TpQOZbeTWON6eTwdHe/mbYfQyL2rdLQDG92yNEqQ+caOR
AbmZfoZi9mlSWWE1dro7HvtVR4wvJs9SM7q0cnPkUjluS5VQJuJbFspYdAwtV3f30kl9LvPdykcU
XervUhqXFY1f5dZfDfha1DY0nCgSSXfFTVr0aSypM95WGEA1oBBNI1dKeASraB4HMMC2cdWvBU1C
LjaMzAkrOedKKjCt/QeHQQ5tDuOtfBLy0C+YgSKuDzs87J8Fg/RHGae16ZD5c5BeOw5SR+pxR/vR
rVBOokuuoC5jYHGnIEZtJZ0QvmXbVUGn+G6wa3QffKy8z38bmfKMjnm8Vv58PT2HPa8HBocVivN/
iltZlHXmufnfVJoOGC80x2QA75HS7iovYBwZ8iS5Mqdbd7py8atjnx7o5isUrrlrjpS+KdQlmh3X
8TlAcvJwjYbnBS5nROUFEtNTetxIEtQu8prMlymQ77b4Szc3o4cuGdF1QiXNWrhVV2M9SBx6fSff
JjfCdUAXPPsrbTnZWy3XZaqTYgeDdUFnzyIHnfs+NEKsny70Nqc2nyPEwL+mVZTmFv9a7F6zwvxt
Wa5WqD7+cqC9dqEekb4DPzxvjdOH2Jnn9CF/OSjzER9SAxPubegOoNKBL867DpBXi7JzYXRFd4Z8
iaWyoqRq1cczLKAbOtu0YuhMEnTKCs5GfdJU52mTL601nQ7iscNE+K8OnR6iRsNprCtwTcLz3OiE
3OuGvzlwymazec4lWYpy407l1ZOkeuseqGEBf69E2GjDrwB2mpRD8TP9DFBk+jw6/0IcXRZs2pDu
bSsb0cwLbmhrbrB5Gnvu8paHW65ihjsGMjtHI5FCUV/iO6qzVFaAfwm68KbQ5ZK0kxaK19cv78LJ
d2f904uncX/6NO1Pvht/F6MSu6x1bCuFB2SYy/ORWAHfxj3NTk/4cls9WaXJIYY+EF2hDu1/RCEU
7a+U0eEe81uWWjV1H3v8l5bf3defzq5lhNZmvb9GF6g6ltXBqv8/frpLdZXtryRpBvQfrNmDT0Cr
+OA5P9iwRsDz5zD6RPWr8d/GZvyYL9317z4FesltaQ8cYCVZcSDs9ub60HNoCA+4beE8/kzlf4lT
vBxPyIsi4A9Ho9noDD+/eQMEnKmzSXIxvxgtx7OLczleYmw4k/PpWTSdyvPpOBrFk2R+eiq+Ae+b
NTuWPuGx9MKkTwcK+dnffyUbY+lHlfi59cDEdV4c+M5wEJpnDEr312zxoDSq08FpbSV/TRkPJoOx
JNm/pyU/j6GMQ9H/UCF4d8OFyBPPyTWvX/U+fPhf6PLlnw==
===END CRASH DUMP===

**Comment by shoghicp** [comment]
Bleeding builds are not supported.
