### ISSUE TITLE
Undefined index on PM1.6 Bleeding #24

### ISSUE THREAD

**Issue by deotern** [PocketMine/PocketMine-MP#3477]
[Server] INFO Notice: Undefined index: 00000000779f487b00000000153d8dd2 in phar:///jar/PocketMine-Bleeding_1.6dev-24.phar/src/pocketmine/Server__64bit.php on line 1799
I got this error (x100000 times) on console... Please fix....

If I'm not wrong, this only happened after a server is full... And players will always get "Unable connect to world" error when this issue (undefined index) came up... :/

**Comment by shoghicp** [comment]
Bleeding builds are not supported
