### ISSUE TITLE
Can't connect to Minecraft PE v0.12.1 alpha

### ISSUE THREAD

**Issue by stephendeo** [PocketMine/PocketMine-MP#3480]
is there a latest update that lets me connect? I've set up a server for my kids/friends and now they all can't play. what should I do?

**Comment by TahaTheHacker** [comment]
This is not a forum.

**Comment by stephendeo** [comment]
sorry... figured i would get a fast answer here as to why it wasn't working... =( i'll see if i can find it on my own.

**Comment by TahaTheHacker** [comment]
you can, in this forum : forums.pocketmine.net
