### ISSUE TITLE
Argument 1 passed to pocketmine\Server::updatePlayerListData()

### ISSUE THREAD

**Issue by iJoshuaHD** [PocketMine/PocketMine-MP#3484]
The server is crashing frequently with it.

More logs:
http://pastebin.com/2pfY3QWF

**Comment by xpyctum** [comment]
UDID not works on 0.12.1

**Comment by Pub4Game** [comment]
Хех, тут uuid, udid это у Apple :)

**Comment by iJoshuaHD** [comment]
after 24 hours, i have over 500+ crash dump files regarding this.

**Comment by MajikalPayton** [comment]
I don't think you need to change anything containing "uuid" after this... But maybe try this when trying to access an object in any function: (now $this->uuid is the same as $uuid->function(). Just use $this->uuid()->function() instead.) http://pastebin.com/excqxuq4

Also, I do not know if uuid is a class or what it is exactly, so if I'm wrong... Sorry!
