### ISSUE TITLE
Can't craft anything

### ISSUE THREAD

**Issue by cyberjudge** [PocketMine/PocketMine-MP#3485]
I'm running PocketMine 1.6dev-27 (API 1.13.0) on a Windows 10 machine. I'm connecting to the server using latest version of Minecraft Pocket Edition on an Android Tablet as well as Minecraft for Windows 10 on a 2nd computer. Both tablet and PC connect fine to the server, however when we try crafting something (ie I have 6 wood in inventory and I try to craft them to be planks) it seems to show in the crafting window what correctly but when I click on the crafted product to put in inventory it disappears and I get the resources (ie wood logs) back. I tried deleting and reinstalling the server and still no luck. Any help on this. My installation process for the server was as follows: 

Installed Pocketmine-MP 1.4.1 for windows from http://www.pocketmine.net/. Then I downloaded the PocketMine-MP_1.6dev-27_mcpe-0.12_885fc07e_API-1.13.0.phar file from Jenkins, renamed it to be just PocketMine-MP.phar and replaced the phar file in the install folder for Pocketmine. I then ran the server setup and left it running.

Please let me know if I'm missing something, or if I should be installing the server differently (like using the files on GIT Hub). Thanks.

**Comment by SonyBravia** [comment]
Hello!!! Can you plz tell me how you got that devbuild plz link or email i really need it

**Comment by cyberjudge** [comment]
Just get the phar file from jenkins: http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/.

**Comment by shoghicp** [comment]
Bleeding builds are not supported

**Comment by cyberjudge** [comment]
So where do we get a supported version that works with the latest version of minecraft people?

**Comment by cyberjudge** [comment]
*pe not people

**Comment by cyberjudge** [comment]
Since this is closed with no guidance, can you tell me where to get a
supported version that works with Minecraft PE 0.12.1?

**Comment by gaoyichuan** [comment]
There isn't any supported version that works for 0.12.1
