### ISSUE TITLE
[PHP7] Unable to find the pthreads extension.

### ISSUE THREAD

**Issue by PlayFriik** [PocketMine/PocketMine-MP#3488]
Hello. I have got php7 working and pthreads installed, but for some reason the PocketMine "Bleeding" builds aren't recognizing it. Any help?

**Comment by PlayFriik** [comment]
Why no reply? :(

**Comment by TahaTheHacker** [comment]
PHP7 has no releases, it's still unstable.

**Comment by TahaTheHacker** [comment]
and under development
