### ISSUE TITLE
Crash pocketmine-mp1262

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3489]
PocketMine-MP Crash Dump Sat Sep 12 14:40:18 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1262 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux play.slpe.ru 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
MineReset 2.1 by Falk for API(s) 1.0.0
SaveInv 0.0.1 by Pub4Game for API(s) 1.12.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
PurePerms 1.1.11 by 64FF00 for API(s) 1.12.0
CustomChat 1.1.2 by Array for API(s) 1.7.1
Boat 1.0 by onebone for API(s) 1.12.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
ItemCasePE 1.0.5 by aliuly for API(s) 1.10.0
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
otu 1.2.6 by yf001, akaituki8126 for API(s) 1.6.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
SClan Beta_2.6 by Sergey_Dertan for API(s) 1.9.0
HotBarInfo 1.0.0 by Pub4Game for API(s) 1.0.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
RegionGuard 0.0.2 by Asyv3n for API(s) 1.6.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
MyZombie 2.7.4 by Zzm & boybook(Quit developing) for API(s) 1.0.0
ToyBox 1.2.1 by aliuly for API(s) 1.10.0, 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
MGMNTAGBlock 0.6-Alpha by MrTVesh for API(s) 1.12.0
SKits Final_0.5 by Sergey_Dertan for API(s) 1.12.0
ChatFilter 1.1_modified_by_mamayadesu by onebone for API(s) 1.1.0, 1.2.0, 1.2.1
iControlU 1.3 by Falkirks for API(s) 1.6.0
GoldStd 1.2.2 by aliuly for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNOw1z2zaWfwWjZG6drqhvy4467qzjONnM2Y02ci43W3Y8IAlKrEmCJUDbSq//fd97AElQdhIn
cWcu046FB+DhfX+A5B89nWSitxjPZpPR/PBwfNjvibKUZW/xR09vC5jqnV6evnv39l2v38uEUnyN
sBOepkxLxlkmskCULK7yUCcyZxuulqLMEqVgtPeMASiv0hR2x0mKW4eqDIeFDK+EzpJcDJcp34ry
8nI+CxINy1IA9haz6fM/+70irdZJ3lvEPFWi3wtlJJCw2XQEiHzt61LoqszZU71JlPdTAQd7PyUO
ASuh957mPBPPfgTUs+mY9v1Jvyfwm35MCTj84QcazWjEfmD/KHjJM1Y0yHy/Rfx/SpdJvmaEnPbt
2300mDdILIWBlCnNHNiZIY0OaVRUQZqEn5Khof8PWv/8M3zft4u4no1armdjy/Vs4nI9m+5wvSTJ
s6dWA7hkVzC7Epjt7yxAnhljT695WpkVc0dGs4NdGd0v6WOtebjJRK5p16Erv9nze+XHo6jdtddl
pW8IZkfM99Ew+5a+BgCSBsvTJQ/B1n7pPRmxvWcL1hqs769EeS1K76ew5GrzssqKvWe9X/u9tchF
yVM0UJhG0oG48WA/EtdAa1AlaQSONplPwK5LqWUIFrGYHPR7vEho5XgyGMHKNbjBojd64D/YUPKr
NAlwz+CAMFSkkkXvLMmrW1aAgw1UWohBWbHpAA7xZh7PovmMPRmz1fmSvRRBwnOamx96479HIjio
puz2cA5eCfiKTQHY9gfzwRjRfxQ5cNKDxXQazF5KVR8HABqkNGh8WKFYzkF874QSGgeWxhbWb8U2
GYxBLJXeyFKhEl7x9ApFTJL6BUQ1gpNhLHIepAKI0WUF8SESBZCGO2BOyVi/dAEZx1DSQx2WeKDv
u2enkiNTy7eriw9v3529BNCNCFSigUg0C+Bkxa/Fm/zaIb6GOKSDEkaDca9D/rIKZq9xh8sCafsb
ebDngik2BDyAfli4EsIh3wK+QL1W4aYE82d79a/xZPqPNZCSDkKZPXssxdTYfd/QVf/9AnO9jdbF
Yji8ubkZ1CgGOegUOD7ZcDgqhqNE6fDdAfc73jre5R5NLymvVIfL+bdzGVt8vh8CFZGlwvd3aHqA
Os+SDIbRSSm4Tq5dve7OdFkckdc6LAZcQUDayKJrn9+hygaj79+lxbK2ujh+d/F+eQ9jy6oUGP+V
w1ILu6OvHYXNZ69ejUaP5mqXBh9kpJoC5+dnuSHDVGCZENA3VYC+MqSdJiAOWyxoqZXSMkMjcO20
Be5yPekwDSGm5LdYDOTyOtzo3q8u+wdg09/IfRctWGlDEdhveM6pNHiArb6QHcZouGOVXS3KXATw
/6Op0eLz/UAi7Q+n/ERmAddncr3uhhAX3OVkssvLGc8C+WicEDbQhEPA1/CzSrIiFZiNMltN17ms
O/FZ7ZzzjG+PI6GqDlvfwVWGGDli9H1FlKwtJbvjB+Y6LbITrsTy1M13LXA3JO53GeRpUqXbR4uH
Bp3vA4VZCAQU4qtMMBW8POPrtWt/DewL2fvs5f922Dj8jqpDlGuxvXwpSs2hRF81NLi/ka1XMqWc
1oU+JPS/4kpflDxXccfbOuBd1XVDYU9t5HqThMWjOVyN0PddMrqjr04ENdJhBwtIQOrKYRxHu9Fl
3uV3G49GpPMrnujqKjmEFuOxihU43vcNDQ+w05fi+gJaPjdtN6Cd/HWnBllSf4UFObsQPOswMP32
/FWf7/sOJV+ZshvKhg0OYPb85PXB/PKDLNPoNEo6Hc3OTNdB93ftFfsR6CRjDf1jUqmD+WO5axau
D+a+b/ov379BggQQ5PsNbViKvHloCk9BEKdxLELtargD/kJUfZ19OH80t0Rkvu8e3x09MB2epDx3
syCNXT5eCM0v73hdJxZ2eHr+mAG2+bMTVg3gy7YMpnx9ZQJOVYiSa0lB5p9Sv+DlmzyWDusO8AsN
w7397Hekx/Zk3+9Q8QAFniolcp3wVHVSfQf8+eK5dybWSNLb+PxkeXo3/HyPkbpkQC8E7Hyxu7sv
BhkKDYHDDmsggXdiDay9rngZOQJwobslwg7/x2p7Pc0fK2dwwgZNUplccy0MHctSanBKWX4K7tr3
p1c8MFKVsAbKLN2pIVzojkHs+PbptUxXwN2jWYFz9G7d9xnHxQsNAaQg1oG+QlW/4DnWsC5XFuJy
NPlSDfgdrgqoIMyaQ7+mhj3f/hsalsRtOBpQl/aDwaxL/b8/Zuy/WCC3gZRXe/+qEs0icS1SWST5
+tFun2pqgKmWrgcwdiG3L+Stw5YF7FZt44c1GP3vNLW609AortsHaei+gMNT8RvPo1ICumHAI8/e
4g51KcQwI1MeWk5RCLy4kC/dZFJDurqd3He79mj3h7zQMoIU0p79EMN8ff7zxfFrqhxc43TB3fg5
947TYsN3OuLy4n+E2jxayLD4gBlLRPvrgYXNfyedOs2MXU5eJTlPL+8UaZ+ubL7rxnqntEFqjHV+
RUS8r5TBu6hXSarvXPBa4E6ov8xklMSJiC6D7WV76fCAyyfrnJPm7zc3JS115tq3ofQBak1OZK7B
Ld873LYwh1lom/7Se+wkNIdCg+ie/wAWXkOaX2m3VqkhuzFz8uWY+Qihcg2nKx09TqxsnxPeGzJr
TpuLuGNg784lHAG7wji480xpp2HuP/7FR0sMOKxL2Dc30A4WvOeXRVUcpxASOjf9DrQrg+lfXKY5
J39fmWZuye9w1gF3WfurK1D36PoWvyHkG3jE57r4jF+AUddH01PxQVFKiM46EfgQ+MmyGTEIEnGy
ZvgWiF/6+ZMV12wlCjaesPFsMRkvZvvs/cUJm4zG+7jA4PNQdkerlMPp4GTORCFLfTR+Pp5OEFjf
Dh+NcJTxW6+g90rU0WREIFXwm9wrTDcBYj/yxgi+2QCjXpoofSTjGCFGvN7vlSi3O7ASYl4NyqSO
jvxqNOIH0vxJf1lV5TW0LumvBvB8Zf5OU/N3xs3f/Wvzdy7txIGdOMzN35D45HkuqzwUlhOPh5sE
6l58p0EdyZyWpKm88eI0WW8a+g2jPE8y6BDtOgPLZFADYlkC4kZodusGmsVQls24uC7sesiZcRJW
qd4ekdjMuw6Qgj0ltIY6XB0hOMW63KiMrptamBIicpbgq0VHL09fHb8/u0AoSnZQcKVgW3T0A/0D
9iotPcWvhaUCXzZo4utgm6VoYgw9lYVkXRXQhC+AoJEx4JG1scc7X4LRsYuNUILVRDNeCqY3gkG2
V/ADTDJEsWsWCJbkYVpFIoIf7I5xI66VzGBnjAh2cSoeiz6TMFMqRMmCUvArtpVVaXGxJGZ1LYJH
ybIEw4R8BIh/FjcNumEkYg6CV+xG5n/TjBeF4CVD0WTAbAgmsMWXrPApneH7ZiNyVhXrkkeAYODn
6DIG2cLP2ZOLDSQkLwUQUAFOta74WjB8t4pEZt1LJTCGchOy5EcSKm492YjQctHdiC8t2cgv8sFN
cpUUIkr4QJbrIY6GZ+BhlzK+fLN6ezmfPvcml7gPxNggWjAfQtva7+FBHzYCZYevmCkIZgxfNzPv
G4Ga8LY85RrkRtMkTaIU6IBfQpNKoUdMQsE2EDVSUnIGiI3dt0fSi2UAV5tKRxJ9xLzihsSY13xY
mEolIkPWMfobw2iBbz7ZBM+uE87+heECllDYqFP/gmGIxo2rDezjaKVKAjX2FKMqbhGxSoERQjgH
QyDujpdvYCUkhQjl1E54QFYARLXoTyk+1XiAY4ZuzMBcwSKQ1GDLrB3BchvNmtlWDE8+JCBomYNJ
8ShiJVTGZHlIJtjaFZDDVVVSDGJgb4FAeYDQxe8VpxcC18k1rDVvVO3ZIyGkPwPk5jyIogJDtwfa
xGeXC5jFk3+u6D1CcKdjtc3DC66uwOLLK3CgAc6/ByWQfdZM4qpNKSFGgknAatVnFHOYjU1gsn0Q
QwZSo/fISCyQ2RCWVTl4Di4h3CsyGeAHnKuUtxA5tQARADtk6nlDGkrVkPMmRg+lVyDBE/ss0X/D
NyJL2hUJTDJkhTt72R5wAHpmE5QI8eBZLheECb0Vg3K5JV99ncoABIt5lxkwWF+WaIxJmVjzYKuB
ILYypIzo8ESheo2nA083CRFGwmaYLgyeWv6K5BInYC4QpiA454QqhhhRn2jUD8xUZLRrCXxIdA2U
GZyzJiI9ImzBRj6FCorKGkINj/6fk48l0meIx6T4XcRDrVXQ+TZUNfRYbIqBS2HugyhjqcEza5LG
o8nMULUUZSIpHaEvKjwwpIBsqWv8bQxHQaiJ0MZohQf+IIynURiHfi3JwUNBbhgdPiVWI04okVKK
8OjrZplPCRdxgPe1nmzCEZ7wFkMIZjhaPri7GNm2hSyIsBAhJkJFYkFajYzN3oYBkKQoVMvmdGT5
VM/uJchyPTVcr3kZgP69UKapKQHRw+6VKpkTkmL3MLsHfDfjeUUp16UCypEKbOFZv44JO8ZgrcHE
VXo6Rdiz1soG7K3JdzQCi9jIKo0aQhKIIDc5a0lHu8X3ZYFyYHA+Ghke2ZNX5Al3YiPZitndMBWX
MqtDLO61854blRydAhNWdbumcI/9OPuwFg83VX6ljLzphTAKiAREyrABQW6YqXT75J4lFCDKLPKw
BsBapsWFqGo1W0d5Prd0vpRm2676MAlgpWS2uRjMKXbZI/BMicgLoWIXhmtrC/VBONFk78+i8vNc
aNRFU7qBaaQmEwZcQ0uAhQjHKhcSINiTjUrkgKYwtbMmGAWiyYkUbp644aueQccvtxpx95k3dowZ
cx8d6+maFAgr+3MTVdpcS1U+JrrIhDurQLMXgJamAfsntC4g3iOohcFwT5bv+7AXKAgg/twkkd6Y
qE3+3aD3CP2CHdjCoC0ZFAnGWTpgxxH404an8RCKfFPFRALszB4ERxr7k7nrkE12dnA5ddLpLTof
lkE87RvHxoM/JDlUkcAWmI0g08Zc/36ZL+tKoa3ZsQjCTTcQ630s2PPCs0O3JoPeSwTVemGLjp/Y
GIsNm1mwqqTpuqJUFMc2oq40fasKSCNtnajYUGmuKzCY4To0ooW4Finn0Lpr6/QNoi4ikW7gxHRM
tNSaF7JLCg/xfU+yMLvFM1sWLIOpte0ngCG6xEByr/E2wgQl3sEPkRM7Mu0cD8LUd6khHyXVPfn5
7cXpglHUhf/CCpqrHJorQkR3UKg6Is+e3JDXqPi4o60Q+giIJJZXsiJKSUAJWo1Gy5mMbArBUGYy
E5oRNrEIt+nIen0XXMcwUwuv0F2RwYAr4Ry2NwZHueeUPpvAxPi+CaHDwTNyWiVcKsgcLhAztlb2
roQJCEzmPEz9RpPUxLbdLQYC6oKwesJwwNMbvlUGt8Xj2FEnfpMZHWeyyt0EoGzNVhOB5CM2n74I
IcQLNvv0Vl4CNDK0GxzdrMPGzyf37ibryoXpIwNhsAUixkhENyYYsVANDVZzj+KEPhP58C18MFqo
7xJslwW2X8XWXg3YXNQUNBQoYroOrsOiDWNxldIyqcBUPXTRJDSphFqwEvtxMAxAW4vqN4mdkPEN
hV+14NdcaNSYYBr+d5SBAq2Vcc5vGd+VC/RAIeWH1h66uiAjfcejpFLONqsHbqkjJzVbrd3heqhW
MCbhhZVXFRHYYksgtNqCm0PoRq7NgobwtrGraR/cJd7GvxueUI8O/XglrH7tfnJ7gnsKlLVgh9+E
rZBFlVps9jemph3Efk4+6YH0kGhzLeeRHSmUJIoyg1it8crFQsc2PODN14KZ4q5WKUgorwoodkzF
ZwySgocpNCwuwHKAu+yBiHQfhzccD2qABOP4sDvXZom9dDM9+sIEI7xOwE+dmIGaHGuNxFivreSb
4IZ27eEFTxfSpJMOtNgUSR7L1gw2EnVPRw6c+z4ohIi+XObbDMt88hAF8lUNodi32GnWThPBYGuc
8fUaso+9HGiuXbBGxA++ru7nxtCD6NR99KC8jCmTind3g02Y2YVRQJl7Njm3FSBBZeFcGJ3gnaGo
X3TAbNWHMXCAN3S6LsWgMomhUhYgbMhPOeZ5XGRTa4XaAX90kDD70MGpISooOJU2Ca4OeBYbashM
1/jVjlDwwcA9IkkTSDdGK6e3HPOtGWDBAvgtEYuaGpoCY8dOecF+wZ8ex0/zEPArYjRRsC5D3NtW
YqLuF0zTVt9NUzd23+UtNbeUxRRVDMh2BoVEAoTaFO+QTqcSAfSL4VU2ui6lpPa0BXt1dnyxmPx4
0N9/fjvuT2+n/cmP4x8jyMQmau3hk8AQI8zR4Yitwb6VGc32n9HltrjVIkeB0FOjE8hD7md3aEPu
GBLCuvk0tghxsR2o39NEi6n5ItAz3x9+NJ8ImsfXQQiVzab9rpan4Du8bAHm0996VJVpM4jts3ZA
PTbPxGNdNLPrqP2ZteANuHLzHcFvqvNSTBaYi91mMRSI20I3w9XyjE7Dh8FFCFVcy6bmSHXkCqWQ
KrltpWL7acO4+VTonYhtMwjQp29AlSKOD4MonO8Ho0Dw+DCe8UjM49E8Ppwdink0m0ZxdDiZs6f0
lDWTLWOKbF+1tG9B9vR1pP3F9ulcVALz8NnWZLQ/msJPOnkazg8Pg3kQhNNRNJ3zeMrD6SyOollw
EOwHB4cHsdiHf3TycoMaIkZQFlpeiRzSjNUFQD4IfgUBwUiLHiluOT0jqT9r+5gU9Yem+NIHkZjY
7X/++R88Qe8R
===END CRASH DUMP===

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.

- First, use the Issue Search to check if anyone has reported it.
- If your issue is related to a plugin, you must contact their original author instead of reporting it here.
