### ISSUE TITLE
Invalid name! Error

### ISSUE THREAD

**Issue by crestudio** [PocketMine/PocketMine-MP#3490]
My XBOX gametag is 'To SunSeT' and couldn't join my server.
And changing gamertag price is $9.9!! Oh my microsoft...

**Comment by MagicDroidX** [comment]
lol you can

**Comment by MagicDroidX** [comment]
you can change the regex in Player.php in order to allow the space in name :)

**Comment by shoghicp** [comment]
Spaces in name will break all commands. This is an Xbox Microsoft policy, which doesn't affect MCPE right now because of lack of commands.

**Comment by TahaTheHacker** [comment]
You're right :+1:

**Comment by Enzotech2** [comment]
If you have colour in your name it will this error.
