### ISSUE TITLE
 Uninitialized string offset: -1

### ISSUE THREAD

**Issue by McDrakon123** [PocketMine/PocketMine-MP#3496]
PocketMine-MP Crash Dump Tue Sep 15 22:22:29 UTC 2015

Error: Uninitialized string offset: -1
File: /src/pocketmine/level/format/mcregion/Chunk__64bit
Line: 121
Type: notice

Code:
[112] 		unset($this->nbt->Data);
[113] 		unset($this->nbt->SkyLight);
[114] 		unset($this->nbt->BlockLight);
[115] 		unset($this->nbt->BiomeColors);
[116] 		unset($this->nbt->HeightMap);
[117] 		unset($this->nbt->Biomes);
[118] 	}
[119] 
[120] 	public function getBlockId($x, $y, $z){
[121] 		return \ord($this->blocks{($x << 11) | ($z << 7) | $y});
[122] 	}
[123] 
[124] 	public function setBlockId($x, $y, $z, $id){
[125] 		$this->blocks{($x << 11) | ($z << 7) | $y} = \chr($id);
[126] 		$this->hasChanged = \true;
[127] 	}
[128] 
[129] 	public function getBlockData($x, $y, $z){
[130] 		$m = \ord($this->data{($x << 10) | ($z << 6) | ($y >> 1)});
[131] 		if(($y & 1) === 0){

Backtrace:
#0 /src/pocketmine/level/Level__64bit(2671): pocketmine\level\format\mcregion\Chunk->getBlockId(integer 11, integer -1, integer 13)
#1 /src/pocketmine/Player__64bit(740): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(68))
#2 /src/pocketmine/Player__64bit(720): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player__64bit(1561): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server__64bit(2485): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server__64bit(2222): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server__64bit(2100): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server__64bit(1701): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/tcagame/elitecra/728/PocketMine-MP.phar/, string /home/tcagame/elitecra/728/, string /home/tcagame/elitecra/728/plugins/)
#9 (1): require(string phar:///home/tcagame/elitecra/728/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Zulu.HostingItAll.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtW/9z2zay/1cwSuad/UaUREmWZfWcGT/HafPGTvRqZzLT8sYDkqDEmiRYArSs9PK/3+4C/Cbb
sZtk7t0P9TQ1CQK7n13sV5D+o6fjVPQW7nQ6nhwcHE6P+r2EK31WFLLoLf7o6W0Oj3uZ1HEgev1e
KpTiKxz6kMVZrGOexJ9EyJQu4mzFZBQpoRfMcWFuVCbJmzjByfmaF4vhcLiWqRjqgK84/BZJrEVQ
8OHheD5cyuBG6Is4E87FcoDzh6oIhjkNpzA8TMStSIaRLFKuh2lQiFUss+Hpusxurq9nUz/WsCxH
vobnn18PaxOYCeoYu/2eLjiIvPi192LEHqZ1jv+3a/fGs0N3f8GaSZ5HszzPsPS8iqfnEVPn1Uro
/0lg/ttwL860WImCuW6fVddO69qd7AO6F+49JMuEb0VRgTicjh7GQFCJ4yWPxGXON9lee5ohw8yv
vdl8n9iNn2I33mVnnjuvQvkmLpQ2jHwpE8EzIjl5gqR7MHMfoalEFr4Td5q01yE6vUf0UhS3DdHx
dH7wCNFgLYKbd0JvZNGlefAUTfjZoWkmOK/AV7q0Zk/RckejL9BaFjIAv5NFh+jhE0Tdw5H7CFGl
eaE7xOb3t6V2yL3pbPoIoevrQGbg+2WgO+Z0KtOc69hPxCmEE3UueQjWJf3fRKD7HUqljhPleRc8
zs7latWaZUPKV4WOevUXlj1nTp6UqzhTQ9LREdtDhRbi9zIuxN634HtU1xjC9nv/+Nzvie8Sgr9H
KAQwRg+9RcQTJfq9QIYCobnuGKh72tNlBkz3Xup1rJxXma+dV6+55vs/AB3XnTw66fJmex6v1tpO
nD46keJke+rB41Nj2IlTmchC2bmzR+f+JJDkBc/tzMMvU60IzmnaZ7o+gmu8GI9oMC/9JA5YVGaB
BqWyVox/eddnL7fw79P+H7TCtdwKocsiY54ni7Bi6uMi9QcsYn//O6SFffZPtvfyE94c4vXL7WcD
ZjxuwIwnFZjpg2DUQ2DgXxxaRJVWnw+CHQPuYF3sIREDaNYlsubqdM2zFZgozoVgIcy8wxbweQX8
6ItaRKO6p8fJqGKYEoeWFkOYX8MfteDPzPWWvXrF3H2rykm1IXG0h8/+Cx6x4+NjNgJGn/+qCP6q
CP6qCP6qCP5/KoJ+byUyUfAE8y5oWkHYgGjlDmahuAUsfhknYW8xhgYuL6SWgYSZk2m/x/OY5rmT
wQjmrSC3L3qjZ/7AgoLfJLGPawaHRKHMOLaMvfM4K+/YL2VSDn6SSoPkb/VJkgwCmbLJwB0NxhPn
Dn4cpUMnzm9nzmzKIF5dXizZVSnYBYcgNmfudDGdL8ZTdnp2xcYjd8ru5jMwWOCE7dyidzCYATW4
/QTeDvdjuB+Zp9dSVUBggG4SuqlLFoXqOkliThcWubnvd9Q4Jpq81GuoGzDG/8KDn3hwg5onFf6K
OsRZMCAyDoYMYDCZ9XuhyAEaroJnSkb6dXsg5Vg5GabGrMkDsMICJ4Any/eXVx/f/3z+GoY2wldg
KL1FBs0zSLEsC/Hj28sW+GqkC3+0C382ffNmNPpu6K8NPYiShn190YhxeXXy89WHZVuI3lrrXIEv
gNWtSx9NY4jrltaJKhooKBn8jyUvwrawrdG2wOMBiNMVGH0F/CvSovjf5buu4KOvF7xLFsTuIPrS
Dj4kfJfasEVsiEq44Nn2oyySsG2trcGuCsDDuiqARqBMtt9NdEMOqhQAsCEAxnyfa7lZmIiiY7lm
pGu508Hk37KRljsabgXjGVKcQTaT6fZk+bYlSGtwd0fmXVlkJnz41xHCuCoIY3+P698u/Z7Y+4m9
n9r7Kdx/pewWhucJgxyweF5HimeGoqUoUrUTjMxYd1Mx2DwdjybfKR4RgtblN8ckQwVkfi1ur6Am
aotcD+1IfC8CNymcXQmedkSffP1eVvw9r4XkT4pbIxvWNEBYCjJnYaxPCt0SuDN8L+tc+0Lza6hB
rl+MpjvWvzyDzvpChlDp3fOAr5Q+FynPUyLpeRSUBCCD2tXzdnD+2dDcAju8THmSOL+cOpVRQIsu
hilXEJOGHT5NiLhcy/x+jKDR3SAxezpIPJmr20HoT3i+Ajy161twz/D9C76KgyuRiKUstKlB6+zU
fdI1kMm/K0Xp/M/kpkp+kSQPbBmO/idtGeBptsyAe46MCrpjPBxUy7O2kO3h3aC9s1nnYoXo3kcX
p8uz+0HsW+rJNgzPM93gVzitQWgADjuigQZOS6VlelKITvHfHm3J73YkT8qAj+e50N9N4BbbZ1nq
Q9LWqIZtIarIvYS2D9rk3chdDXct+l6785hj9r9R7spDKVbnBsuuAp6ZtngifuNZWEgg2eqVnfyx
IF2JbouX0zXXO7ULDe2GrGd0Uu5Trt5UEfd003vD6VBTAbzeIxUN4mquvrmeISKghTbnRhHt0SfC
95XQa1GI8Pq7+UWLuefZm+cH8ss4zRNxAgBb8rQGu+Ic7vaMuyUawFzL1ToO8u8mXwPG8zrAvrpk
a1H5jOccvACxweYrIHQQNwBXy0WhY4GHIi+W9R07lVkUrxi+GfIKL3uBRzGXImfuARuPF+7RYjJl
H65O8SjmACcYeg7q9vgMD7FOTW/2qfUwh9x/7B65kzEOpiKVxdZJ4jSGUTxGwlE8BYPCTRybOfwO
/BYPXNXxxPDBg2HHRgjYsWN3hsObNbAEWkofExmzB87vpSi2xzJrDRWQIY9lFOEQXg9yrhSEnfD4
v+kHmEodHnvlaMQPE/NLml8+CWaueVs+nmWyzAJhsTo8WMfiVqSQZ5TlfhuLjRMCPg7zjue0Kknk
xokSfLdUITLi8SyG0rJaasZS6VcDkSyAV60pu3TNizCQRX2f3+Z2fhhHURyUid4eu6RjOiLUsnCU
0Hgip45xmE78zQ6CPTUjSoiwNQFfNB5HCUQelKHU0lH8VlhWeOBWh9zBNk3QrBh6KgvIokpgjK9q
0LAYCMI6h5xgaOxqLZRgFTLGC8EgmjCodRRccM0CVLdmvmBxFiQllPZwwe4ZNNK6lCmsjJDALk3F
I9FnEgOVQpLMhzR5w7ayLCwtFkcMFBxHMXEA3RZgc5ClgPA7sanJDUMRcdCuYhuZ/U0znueCFwxV
k4KwAezzFuAzfNdk5N6sRcbKfFXwEAgMvAxdxBBbeBl7cbWGHOUkMAQoEp6tSr4SDF+nksqsO6kY
7hMZ4ItdUiouPcXXEkaK7kIAUAUMkQ028U2cQ0/EB7JYDfFueA7GeS2j67eX769nkyNnfI3rQI01
oQXzILitvB4y+rimIM+0ZPh+hYGU9lwctqngmQILAb3RY9ImIQUccCU0bSm0g3Eg2JrjSQuOpEDY
GHfDkt4lw7halzqU6AjmxTaCMW8TWJBIJUID6wSdimEgoDN2k93YbczZ/2EsgCkUE6pqYMEwSONC
6HI2jKOVKgloLBezVdwSYqUCI4SADoZA0kGNDjMhUYSop+aBA7B8ANWQP6PoU9EBiRn6KgNzBYtA
qP6WWTuC6TZW1U8bNbz4GIOiZQYmxcOQFUIZy0OY+MoH4HAFuRxjDwN78wXqA5Qufi95gtuxim9h
7i1PIKLvWZYQxveBuOEHMVJgqHZgN/HFygKeIud3Zerja5aInahtFlxxdcPw7Rc40ACff4BNIPus
hMRZ6wIakhJMAmarPqP6jtkABCbbBzWkoDWF2ZfUAvkNx9IyA8/BKUT7kkwG5AHnKuQdhEctQAUg
Dpl6VkNDrRo4byP0UJyCnthnsf4baE4XtCoUmD/ICnfWsj2QAPaZjVEjJINjpVwQJfRWk7vIV39M
pA+KxcTOzDCjlIYxKRUr7m81AGKXBsqImMcKt9d4Osi0iQkYKZthTrCp0Q4p0ksUg7lAmIIYnBGp
CGJExdFsPwhTktGuJMgh0TVQZ8BnRSBNrl2wkUehgqKyhlDDw/9w+FgkfQE8Zr5vAg9dUk78baiq
8VhqioFLYZ0AUcaiQZ4VJHc0nhpUUMvHktIR+qJChvSeuEJX+5sLrCDUhGhjNMMBfxDG0yiMS2hR
M/BQ0BtGh8fUatQJ1U9CER593UzzKOEiDfC+xpNNOEIO7zGEYIaj6YP7k1FsW8qCCnMRYCJUpBbE
anRs1tYCgCZFrhoxJyMrp9p/EJCVemKkXvHCh/13ApkkprpDD3tQq2ROCMWuYXYN+G7Ks5JSbhsF
lCMl2MJ+v4oJO8ZgrcHE1SiqYkPaWNmAvTf5ju7AItayTMIaSAwRZJOxBjraLcsJOQg4w/I2I0Zv
yBPuxUayFbO6FioqZFqFWFxrnzvtqNTaUxDCbt2uKTxgP611WGUH+G2EMvo+J6vHgEiDiAzbEJSG
mQq3T+5ZQAGizCQHawCsZRpaSKraZusoRzOL87U0y3a3D5MAVkpmWZuC4WKnfQeZKRE5AVTqwkht
baFihA/q7P1FUl6Wma9A6tINTCMxmdDnGloBLEQ4VrkKv8thNiqRA5rC1D41wcgXdU6kcPOiHb6q
J+j4xVYj7T5z3JYxY+4jto6uoEBYOZiZqNLkWirmMdGFJtzZDTRrYdBiGrCfoD8B9R5DLQyGe7r8
0Ie1gMCH+LOJQ702UZv8uybvEPkFO7SFQVMyKFJMa+qAnYTgT2ueREMo8k0VEwqwM8sIWBr7k1nb
Ievs3KLVqpPO7tD5sAziSd84NjL+GGdQRYJYYDaCTBtz/YdltqwqhaZmxyIIF20g1ntYsGe5Y2/b
NRk0WMIvVwtbdLxi+PmVtpkFq0p6XFWUiuLYWlSVpme3AtJIUycqNoROUZdgMMNVYFQLcS1ULaZV
c9bpG0RVRDLz8ZjpmGiqNS8UlzY8ACVqsjC7xDFLFqz+3swIRMcYCBdMDoyUghLv0IfIiR2ZbrEH
Zer7aMhHaetevHt/dbZgFHXhv6CE5iqD5ooI0dEFbh3Bs5xrePUWn3R2K6CvBytZyYooJQEStBqN
ljMe2RSCocxkJjQjbGJx3KYj6/Xd4SqGmVr4Et0VBfS5Ei1mey44ygNc+mwMD9yHHggdDPbJaZVo
oyBzuELK2FrZUxAmIDAZfpj6zU5SE9t0txgIqAvC6gnDAU82fKsMbUunZUed+E1mdJLKMmsnAGVr
tgoEwkdq2DJAbMbLBZs+vpQXMBoa7IZGN+sw92j84GqyrkyYPtIXhpovIoxEdCyCEQu3oaZqDkta
oc9Evkt+C0kX67vqO+hA5lt7NGBzUV3QUKCI6IS4Cos2jEVlQtOkAlN10EXjwKQSasEK7MfBMIBs
parfJHZCxjcUT9FWUoqVmGBq+Xc2AxVabcYFv2N8Vy+5+bBPhI09dPeCjPRnHsalai2z+8AtOnJS
s9TaHc6HagVjEp5KOWUegi02AKHVFtwwocO2Jgsa4E1jV2Ef3Adv49+Gx9SjQz9eCru/dj25PY07
CjZrweZfRS2XeZlYavYaU9MOYS8jn3RAewjanL05ZEcKNYmqTPFjRTxysaOuDQ948rVgprirthQ/
jSxzKHZMxWcMkoKHKTQsLaByiKssQyR6gLcbjozqQRrjqR+D5Zsp9tDN9OgLE4zwOKHgas3MqMmx
1kiM9dpKvg5uaNcOHvB0R+p00hnN13mcRbIxg7XEvSeWg9Z5HxRChC+T2TbFMp88RIF+VQ0U+xb7
mDWPCTB+hs34agXZxx4O1McuWCPid9U3D0tj8CA59RAe1JcxZdri3dVgE+bpwmxAkTk2OTcVII3K
vHVgdIpnhnSIJRKZY7bqM/zKAQ9bAIktxaAyiaBSFqBsyE8Z5nmcZFNribsD/tgiwuyriFYNUULB
qbRJcFXAs9Rwh8zjir7aUcpms3lIJfiZoal8oVLimG/NDRYsQN+CWFRo6BEYO3bKC/YrXjqQZPrU
Ov8DKZooWJUh7dNWEqLqF0zTVh1AUzf20OEtNbeUxRRVDCh2CoVEDEBtim9BJ64EgK4Ynlij61JK
argt2Jvzk6vF+IfD/sHRnduf3E364x/cH0LIxCZq7eHLwQAjzPF8xFZg38rcTQ/26XBb3GmRoULo
XfEp5KH2p6doQ+17SAir+q9h8gAn2xv1O75KmJjvZR3zbe4n8wGteefqB1DZrJs/peEJ+A4vmgHz
9z7VXVkk9U0UJxq/qAPSrvl6LNJ5/XQVNpdpM7wGVzYf68D831T9uSu+Ckt9c7BbT4YCcZvrRhjN
EVvYFv1yeU4I8M1gHkBl1yzegvD0ia69YgcDRIpaYA6+UBqPDkYTuHz5FlvnYDaf+zPfDyajcDLj
0YQHk2kUhlP/0D/wD+eHkTiAH/YSOC3XqKL6o8dcqviu2QDbutsJLor2s4hs3wmjxE9E0dwPg9mB
P/IFj+bRlIdiFo1m0Xw6F7NwOgmjcD6eET+1TmWjQ0VuprqSxmYjYLKWNyKDrFPUIx8Fv4H4YBRF
H49sOb0yce2Hq5/i3NyNBwe9z5//BcsSRq0=
===END CRASH DUMP===

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
