### ISSUE TITLE
Call to a member function hasPermission() on null

### ISSUE THREAD

**Issue by McDrakon123** [PocketMine/PocketMine-MP#3497]
PocketMine-MP Crash Dump Wed Sep 16 13:13:25 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 449
Type: E_ERROR

Code:
[440] 		return $this->perm->isPermissionSet($name);
[441] 	}
[442] 
[443] 	/**
[444] 	 * @param permission\Permission|string $name
[445] 	 *
[446] 	 * @return bool
[447] 	 */
[448] 	public function hasPermission($name){
[449] 		return $this->perm->hasPermission($name);
[450] 	}
[451] 
[452] 	/**
[453] 	 * @param Plugin $plugin
[454] 	 * @param string $name
[455] 	 * @param bool   $value
[456] 	 *
[457] 	 * @return permission\PermissionAttachment
[458] 	 */
[459] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Zulu.HostingItAll.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

>===BEGIN CRASH DUMP===
eNrNWgtv20a2/isDJcAmhai3ZFuFizVcp80ibrSxgwAtF8aQHEqs+SqHtKz05r/f75wZPiQ7TZoE
iw1aWHM4c+Y77zND/tkro0T1luPZbDIbnUxG835PFUVW9JZ/9spdjke9i5uLN29ev+n1e4nSWq6J
di7jWJSZkCJRiacKEVapX0ZZKjZSr1SRRFpj9Oy5ACmt4hirwyimpUNd+MM8829VmUSpGq5iuVPF
zc1i5kUlpsUg9paz2cmHfi+Pq3WU9pahjLXq9/wsUARsNhuBkVu6ZaHKqkjF03ITaeeHHBs7P0Qd
AFeqfPY0lYl6/j1Yz2ZjXveBf0/wm39MmTj87jsezXgkvhP/zGUhE5E3zFy3Zfx/uiyidC2YOa+b
23U8WDRMLEIvy2J+cmSfDHl0zKO88uLI/5gODf4/ef7JX8j92CqWej5qpZ6PrdTzSVfq+fRA6hVr
Xjy1FqAph4o51MB8fjCBZBZCPL2TcWVmLDo6mh8d6uhxTZ+VpfQ3iUpLXnXc1d/85FH9ySBoVz3b
F6VvAItT4brkmH2LryFA0/C8spA+fO233pORePZ8KVqHdd0rVdypwvnBL6Te/Fgl+TOSVMn0ee8/
/d5apaqQMfkpZpEEwDgeLAJ1B8heFcVBbzk5gXMXWZn5cIvldNbvyTzieePpYIR5a8TCsjf6zH9Y
UMjbOPJozeCIOVRsl2XvVZRW9+LXKq4GP2e6hMlelmdxPPCzREwH49FgMnXu8c/RZeBE+d3CWczE
k7G4ulyJa+jlUhZifCzGs+XseDmZifOLazEZjWfi/niBoMVO+SbHPvPBAtwwfK9SSNibYDwyT28y
XQMBgQcxD5oQ16SusziS/MMiN+P+nhonzFNW5SYrNNnnV+n/LP1b0jyr8DfSIc0CQaXSixXAlEWF
9BGoHNBoFZ7pLCx/7BISSZnGbOq6lxidx1LT/nEmSaDV66vrd6/fvPoRpK3ydFQCJHkMpFhVhfrp
5VUHfE3Zhz86hL+YvXgxGn0z9DeGH+LHbN/8aMW4uj57c/121RWitynLXC+HQ3jdpvLINYa0zkSO
HtY8SFCOg58qWQRdYTvUrsCTAcTZF/gSIYTACUtV/Gv1y77goy8XfJ8txN5D9FcWfEz4fW7DDrMh
KeFSprt3WREHXW/tEPdVgAjbV4GMoyrefTPRDTvXTQBgywCM+36u56ZBrIo9zzWUfc+dDab/FUPa
3clxaxifIcWFn6VZsjtbvewI0iEeWuR4X5YsVR7+3xPChCqEsX8nzd8x/53a8dSOZ3Y8w/gLZbcw
XFcZ5MDiuntSfGYqouqpD5KRoe0blZLNp/PR9BvlI0bQ+fnVOclwgcw/qrtrlOCuyA3pQOIHGdgE
N3mzuFYy2RN9+uW2rPd33Q6Svylug2zY8ICwnGQugqg8K8qOwHvkB1XnxlOlvEEPcvNkNDvw/tXF
pcwvsyBAtB1GwBdKn6tE5gmzdF1OSgrIZFG67gHOv5uaO2CHVwmOIc6v507tFOiL1TCRGjlpuLdP
myKuNln+MEcw9TBJLD6dJD5Zq7tJ6G9EvgaeJvQtuM+I/Uu5jvxrFatVVpSmB22q0/6TfQeZ/rdK
VJn/ndpUy6/i+BGTqTj+nzIZ8LQmM+A+R0atcUiJcMBdXXSF7JIPk/aBsV6pNaF7HV6ery4eJrGv
6Se7MFz3FcT5ZEV+LGgNQgNwuCcaNHBe6TJLzgq11/x3qR35x3uSx5UvJ8e5Kr+ZwJ1tP8tTH5O2
QTXsClFn7hWOfcp/kLlr8r5HPzjufCww+18pdx2hnKtzg+VQAZ9ZtmSsfpdpUGRg2bnocfKPJela
dNu8nG9kedC7MOkwZX3GSWr8qVBvu4gHuum9kHyboAGv95GOhnC1v766n2Em0EJ351YRXeon0ve1
KjeqUMHNN4uLzuauawefn8ivoiSP1RkAduTpEPfFOTo8Mx62aIC5ydabyM+/mXwtGNfdA/bFLVuH
ywe656ArMQWfr4HwJdIAoZaroowUXYo8WTUjcZ6lYbQWdGnqFm765J0KxJXKxXghxpPl+Hg5mYq3
1+d0FTOnCYafQ7o9vYgB8Nyczd53Huao/afjk/F0QsREJVmxc+IoiUClaySiriXRA3Vq5sh7xC1d
0OrTqdknl9vUsRkCFjsdL4i83WBL8NLlKbMxNnD+qFSxO83SDqlAhTzNwpBI9HuQS62RdoLT7/gf
Ns3K4NStRiN5FJs/mfnjsWDmt+zKJ9M0q1JfWayO9DeRulN0/aft7neR2joB8EnMOz3mVXGcbZ0w
jtabskZkxJNphNayXmpoSebVhDArsFejKbt0I4vAz4pmnN/ldn4QhWHkV3G5Ox2zjvmKsMwKR6uS
buT0KZFjQI6NBeFPLUUrFXQm0LX8aRgj85AMVZk5Wt4puxVduDUpd7BLYnIrQZEqfPaoChvTHSk5
loAgonVZ53IFRxPXG6WVqJEJWSiBbCLQ62j8kKXwSd2l8JSIUj+u0Nrjh3jg0MTrKkuwMiQGhzy1
DFVfZJSoNLEUHsrkrdhlVWF5iSgUUHAURrwDdFvA51ClwPgXtW3YDQMVSmhXi22W/qMUMs+VLASp
JoGwPuy8o/cQdFlu5N5uVCqqfF3IAAwGbkohYpgt3VQ8ud6gRjkxSEARy3RdybUS9PqBVWbDSUcY
xxn4R+9ZqbT0fKN8K8X+QrrXtwlDpYNtdBvlOBPJQVashzQavoJz3mThzcur1zeL6YkzuaF1UGPD
aClcJLe126ON3m04ydNbGPRTgaA3MuZKHmYqZKrhIdAbP2ZtMlLgwC9VsklxHIx8JTaSblqIkoCx
ce52S373ArreVGWQUSCYt0AExtyECz/ONLZ6hvTlIcZ3Qgq+GxeF+j2Da+A/KUJYDE6pnxv4ZxR8
ghIGvUSwvYG4i6T4N+UMTOHcUXcNS0HJnBbiNLSlDVCMMqC2aIxJpWUkKg1nReKHw7AW0MtjJgpK
QPpsHziA7wF8y/6Cs1TNB5oRFNMCbg3PIajeTlh/w3Sb05qnrbqevItgkCwlbQQBNKGNhxJM+OQt
4EiNmk85SsAvPUX6gHHUH5Xkd2vr6A5zzcuJZ3ZLpPvnYG72Qy5VlNIdWH29VsUST2nnXyp+JYew
O9O71L+W+haRUdwi0Ab0/C0Zi/y4FpJmbQocXCq4DmbrvuA+UNhEBdfuQw0JtMavZFgtqINES6oU
EUZTmPcVuxbkQRAW2T3SaKmgAojDIZE20EirBs7LkCKZ3yYiYvsiKv9BLxcLXhUoqjPsrQdrxTNI
ADuLCWmEZXCslEvmRFFtahzH9E8xnBMhggZAGLLg0kfemai19HYlAIkrA2XEm0eazGsyAmTaRgyM
lS2odtgSakma9RJGcBekM+TqlFmFyCX1jsb8EKZip11nkCOjECKdYZ81gzQ1eSlGLqcUzt4lUpIM
/sfhUzP1F+CpQn4VeJymct7fprQGj+WmBUKK+gkV1GhozwNIaPijjGsWBaKm3XzO2hZaE2xj7IM8
E5CD8QwHwaBMmHGuz3COTRGeUBqlho/p1OgSLVLMZYAC3UxzuSoTD4ReG8YmF9EOryl/UBnk6YOH
k0lm2+9Cf7nyqVpq1glhNQo2axsBoEaV61bM6cjKqZ8/CshKPTVSr2XhwfiOn8WxaQEpvB7VKvsS
QbFrhF2DwE1kWnFd7qJAeajgCM/7dUI48ATrCiaphmGdGJLWxQbitSmKPII7bLIqDhogEdLHNhUt
dHJaeu8M5BBwQT1wyhu94DB4kBjZV8zqRqiwyJI6v9Ja+9zppqSOTSGENd2hKzziP5111Ir7myq9
1Ubfr9jlKRsykZDRWYWkEaYN7nNsFuhStJnkUKNADU/Li1jVZrZRMplPLNAfM7Pu0H5UAqifMuu6
LMw2dto3EJrLkOOjn1dGbOsM9Ub0oKndf8nKTVNVkjGaBg++EZs66MkSBwZqQyT1wih/cCibkzgC
Tftqn5pU5KmmInKyedJNXvUTivxiVxLvvnDGHW+mysfbOmUNhTS/MGmlrbTc8lOZC0yysxY0a0G0
mAbiZ5xioN5TdMzw3PPV2z7WAoGHBLSNgnJjcjYHeMPeYfZLcWTbgrZh0KyYztSBOAsQUBsZh0Mc
BUwPEyg4mt0IWxoHzNJuRDa1ucOr0yVd3FP0URMk476JbNr4XZSi14RYcBvFvk2V/u0qXdV9QtvZ
UwtEi7bI9C619Wnu2GG3I8MxTHnVemlbjh/EmFoNW1eop+THdT+pOZFtVN1nutYUSzFuu0QthjhP
lhUcZrj2jWqR2ALd2bQ+wu2dLlTdQhJuSGLOVTzVuheJywb3ocSSPcwuccySpUjwaG1PHRCILzsI
LlwOTspZSe7xR+qkc1vZ2R7KLB+i4Rhl0z355fX1xVJw2sV/foUjWIojGDPiCw4yHcOzOzfwGhOf
7VnLx2kDmcTKyl7ENQlIyGtK8pzJyNYQymWmNJEb0VGX6LYe2ajfJzdJbGRj0tRCT2rV2ezZGIHy
yC59McGD8WMPVOkPnnPQatVFwe5wTZzpAGbvSoRCYjL7Ue03luSjbnsGpkTAZyDqnSgdyHgrd9rw
tnw6frSXwNmNzpKsSrsVQNuOrQZB8Imby59WMeOlmH18qSxADQx2w2O/7IjxyeTR1exdqTKnTU8Z
bp4KKRPx5QllLDJDw9VcqXRSn8l8V/IOVZe6u4gO1YoOX/nOXiDYWtR0NJwoQr5HrtOiTWNhFfO0
TMNVHQrRyDelhA9gBZ3a4RhgW6uKj6nSxIamz8Pos0hyaiowjfwHxiCF1sa4lPdCHuoFJyCf60Pr
D/u2YCd9I4Oo0p1l1g7SouMgNUut39F8tCuUk+juyqnyAL7YAsSBXEmzCV/JtVXQAG+PdTX2wUPw
Nv9tZcQndJzGK2Xta9dz2DPd0TDWUhx/Ebc8y6vYcrO/qTQdMHZTjkkH2iPQ5obOYT/SpElSZYJc
XdLFjKWObXqg+7GlMN1dbVL6Xq/Kl+LEtHzGITl5mEbD8gKXI1plNySmcxpuJW3UEJkmEy+C55sp
9mrOnNCXJhnRZYK9FyGqqbHWSYz32la+SW7k1w5dA+1TmnKyR803eZSGWesGm4xsz1sOOreCaIQY
X5qlu4T6fI4QDf3qBigdXOxj0T5mwPA1KeR6jepjrwaaSxfqEenLydvHpTF4iJ1+DA/py7gym/hw
NXzCPF0aAxSpY4tz2wEyNcs710XndLPIV10qznKqVn1B30LQVQuQ2FYMnUmIVllB2ahPKdV5mmRL
a0XWQTx2mAj7wqLTQ1RoOHVpClyd8Cw3spB5XPPXB0rZbrePqYQ+RjSdLzolSfXWDKhhAX8LYlmj
4UdwdjonL8Vv9NOR9I0rEf5DHE0WrNuQ7p0sC1EfGMyprb6m5uPYY1e8fLrlKqa5YyCxEzQSEYDa
Et+BzrsyAP4l6F6bQpdLUrvbUrx4dXa9nHx/1J+f3I/70/tpf/L9+PsAldhkrWf0CtGnDHN6PBJr
+Lc2o9n8OV+Bq/tSpaQQfqN8jjrU/UCVfKg7RkFYN9+Y5z5NtgP9B71wmJqvah3zBe9785mteTPr
+ehsNu0H6jJG7MiiJZhv6OtRVcTNIIzikr67A+ux+cYsLPPm6TpofyYteYNQNp/0YP7vuvkoll6Y
JZ65/m0mo0Hc5WUrTCkJW9AV/Wr1ihHQ+8PcR2fXLt5BeP6Q1/4S8wEhJS0Ih147TUbz0RQ/n76k
s7O/OD72Fp7nT0fBdCHDqfSnszAIZt6RN/eOjo9CNcc/8RQ7rTakoubTyDzT0X1rAHt2txPGJNob
FdpzJ6i8nwrDYy/wF3Nv5CkZHoczGahFOFqEx7NjtQhm0yAMjicL3k9vkqzVoeYw0/uSRsYQmFxm
typF1Skayjslb5EfjKL4E5Od5BcrY/t56/soN6PJYN778OH/AQn0xlc=
===END CRASH DUMP===

**Comment by Intyre** [comment]
Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
