### ISSUE TITLE
Server crashes randomly [Error: Call to a member function hasPermission() on null]

### ISSUE THREAD

**Issue by McDrakon123** [PocketMine/PocketMine-MP#3498]
Server crashes randomly after the server has been running for about 30 minutes

>Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 449
Type: E_ERROR

>Code:
>[440] 		return $this->perm->isPermissionSet($name);
[441] 	}
[442] 
[443] 	/**
[444] 	 * @param permission\Permission|string $name
[445] 	 *
[446] 	 * @return bool
[447] 	 */
[448] 	public function hasPermission($name){
[449] 		return $this->perm->hasPermission($name);
[450] 	}
[451] 
[452] 	/**
[453] 	 * @param Plugin $plugin
[454] 	 * @param string $name
[455] 	 * @param bool   $value
[456] 	 *
[457] 	 * @return permission\PermissionAttachment
[458] 	 */
[459] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

>Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

>PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Zulu.HostingItAll.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

>Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
Pundler 1.4.3 by MinecrafterJPN for API(s) 1.10.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWg1v3DbS/ivEJsA5xWq/d+1s4eIM12lziJu92EGAVgeDkqhd1fqqKHm96Zv//j4zpD527TRp
EhzOSLvikBw+M5wvUvqzV0aJ6i3Hs9lkNj7B//s9VRRZ0Vv+2St3Obp6FzcXb968ftPr9xKltVwT
7VzGsSgzIUWiEk8VIqxSv4yyVGykXqkiibRG6+iZACmt4hizwyimqUNd+MM8829VmUSpGq5iuVPF
zc1i5kUlhsUg9paz2fMP/V4eV+so7S1DGWvV7/lZoAjYbDYCI7d0y0KVVZGKp+Um0s4PORZ2fog6
AK5UefQ0lYl69j1Yz2ZjnveBnyd45ocpE4fffcetGbfEd+KfuSxkIvKGmeu2jP9Pl0WUrgUz53lz
O48bi4aJRehlWcw9x7ZnyK0TbuWVF0f+x3Ro8P/J45//hdyPzWKp56NW6vnYSj2fdKWeTw+kXrHm
xVO7AzTkUDGHGpjPDwaQzEKIp3cyrsyIRUdH8+NDHT2u6bOylP4mUWnJs066+ps/f1R/MgjaWUf7
ovQNYHEqXJcMs2/xNQRoGpZXFtKHrf3WezISR8+WojVY171SxZ0qnB/8QurNj1WSH5GkSqbPev/p
99YqVYWMyU4xiiQAxvFgEag7QPaqKA56y8lzGHeRlZkPs1hOZ/2ezCMeN54ORhi3hi8se6PP/MOE
Qt7GkUdzBsfMoeJ9WfZeRWl1L36t4mrwc6ZLbNnL8iyOB36WiOlgPBpMps49/hxdBk6U3y2cxUw8
GYury5W4hl4uZSHGJ2I8W85OlpOZOL+4FpPReCbuTxZwWqyUb3KsMx8swA3N9yqFhL0J2iPTe5Pp
GggI3Ii50bi4JnWdxZHkB4vctPt7apwwT1mVm6zQtD+/Sv9n6d+S5lmFv5EOaRQIKpVerACmLCqE
j0DlgEaz0KezsPyxS0gkRRqzqOteonUeS03rx5kkgVavr67fvX7z6keQtsrTUQmQZDGQYlUV6qeX
Vx3wNWUf/ugQ/mL24sVo9M3Q3xh+8B+zfPPQinF1ffbm+u2qK0RvU5a5Xg6HsLpN5ZFpDGme8Rw9
rHmQoOwHP1WyCLrCdqhdgScDiLMv8CVcCI4Tlqr41+qXfcFHXy74PluIvYfor3bwMeH3uQ07zIak
hEuZ7t5lRRx0rbVD3FcBPGxfBTKOqnj3zUQ37Fw3AYAtAzDm+7mWmwaxKvYs11D2LXc2mP5XNtKu
ToZbw/gMKS78LM2S3dnqZUeQDvFwR072ZclS5eG/PSGMq0IY+ztpfsf8O7XtqW3PbHuG9hfKbmG4
rjLIgcV196T4zFBE2VMfBCND299UCjafjkfTbxSPGEHn8atjkuECmX9Ud9dIwV2RG9KBxA8isHFu
smZxrWSyJ/r0y/eyXt91O0j+prgNsmHDA8JykLkIovKsKDsC75EfZJ0bT5XyBjXIzZPR7MD6VxeX
Mr/MggDedugBXyh9rhKZJ8zSdTkoKSCTRem6Bzj/bmjugB1eJTiGOL+eO7VRoC5Ww0RqxKTh3jpt
iLjaZPnDGMHUwyCx+HSQ+GSu7gahv+H5Gnga17fgPsP3L+U68q9VrFZZUZoatMlO+z37BjL9b6Wo
Mv87uamWX8XxI1um4vh/asuAp90yA+5zZNQah5QIB9zVRVfILvkwaB9s1iu1JnSvw8vz1cXDIPY1
9WQXhuu+gjifzMiPOa1BaAAO90SDBs4rXWbJWaH2iv8utSP/eE/yuPLl5CRX5TcTuLPsZ1nqY9I2
qIZdIerIvcKxT/kPIndN3rfoB8edjzlm/yvlrj2UY3VusBwq4DPTlozV7zINigwsOxc9Tv6xIF2L
bouX840sD2oXJh2GrM84SY0/5eptFfFAN70Xkm8TNOD1PlLREK726avrGWYCLXRXbhXRpX4ifF+r
cqMKFdx8M7/oLO66tvH5gfwqSvJYnQFgR54OcV+c48Mz42GJBpibbL2J/PybydeCcd09YF9csnW4
fKB7DroSU7D5GghfIg3garkqykjRpciTVdMS51kaRmtBl6Zu4aZP3qlAXKlcjBdiPF9O58vJSLy9
PqermDkNMPwc0u3pRQyA5+Zs9r7TmSP3n46fj6cTIiYqyYqdE0dJBCpdIxF1LYkeqFMzRt7Db+mC
Vp9OzTq53KaOjRDYsdPxgsjbDZYEL12eMhuzB84flSp2p1naIRXIkKdZGBKJnge51BphJzj9jv+w
aFYGp241Gsnj2Pxk5sdjwcyz7Mon0zSrUl9ZrI70N5G6U3T9p+3qd5HaOgHwSYw7PeFZcZxtnTCO
1puyRmTEk2mE0rKeamhJ5tWEMCuwVqMpO3Uji8DPiqad3+V2fBCFYeRXcbk7HbOO+YqwzApHq5Ju
5PQpkWNAjs0Owp5ailYq6Ayga/nTMEbkIRmqMnO0vFN2Kbpwa0LuYJfEZFaCPFX4bFEVFqY7UjIs
AUFEa7LO5QqGJq43SitRIxOyUALRRKDW0XiQpfBJ3aXwlIhSP65Q2uNBPDBo4nWVJZgZEoNDnlqG
qi8yClSaWAoPafJW7LKqsLxEFAooOAojXgG6LWBzyFJg/IvaNuyGgQoltKvFNkv/UQqZ50oWglST
QFgf+7yj9xB0WW7k3m5UKqp8XcgADAZuSi5imC3dVDy53iBHOTFIQBHLdF3JtRL0+oFVZt1JR2jH
GfhH71mpNPV8o3wrxf5Eute3AUOlg210G+U4E8lBVqyH1Bq+gnHeZOHNy6vXN4vpc2dyQ/OgxobR
UrgIbmu3Rwu923CQp7cwqKcCQW9kzJU8tqmQqYaFQG/czdpkpMCBJ1XyluI4GPlKbCTdtBAlAWNj
3O2S/O4FdL2pyiAjRzBvgQiMuQkXfpxpLHWE8OXBx3dCCr4bF4X6PYNp4J8UIXYMRqmfGfhn5HyC
Aga9RLC1gbiLpPg3xQwM4dhRVw1LQcGcJuI0tKUFkIwyoLZozJZKy0hUGsaKwA+DYS2glsdIJJSA
9Nl2OIDvAXzL/oKjVM0HmhHk0wJmDcshqN5OWHvDcBvTmt5WXU/eRdiQLCVtBAE0oY2FEkzY5C3g
SI2cTzFKwC49RfrA5qg/Ksnv1tbRHcaalxNHdkmE+2dgbtZDLFUU0h3s+nqtiiV6aeVfKn4lB7c7
07vUv5b6Fp5R3MLRBtT/ljaL7LgWkkZtChxcKpgORuu+4DpQ2EAF0+5DDQm0xq9kWC3Ig0RLqhQe
RkOY9xWbFuSBExbZPcJoqaACiMMukTbQSKsGzsuQPJnfJsJj+yIq/0EvFwueFSjKM2ytB3PFESTA
PosJaYRlcKyUS+ZEXm1yHPv0TzGMEy6CAkAYsuDUR9aZqLX0diUAiSsDZcSLR5q210QEyLSNGBgr
W1DusCnUkjTrJYxgLghniNUpswoRS+oVzfZDmIqNdp1BjoxciHSGddYM0uTkpRi5HFI4epcISTL4
H4dPxdRfgKcM+VXgcZrKeX0b0ho8lpsWcCmqJ1RQo6E1DyCh4I8yzlnkiJpW8zlqW2iNs42xDuJM
QAbGIxw4gzJuxrE+wzk2hXtCaRQaPqZTo0uUSDGnAXJ0M8zlrEw84HqtG5tYRCu8pvhBaZCHDx4O
JpltvQv95cqnbKlZJ4TVKNjMbQSAGlWuWzGnIyunfvYoICv11Ei9loWHzXf8LI5NCUju9ahW2ZYI
ip0j7Bw4biLTivNyFwXSQwVDeNavA8KBJVhTMEE1DOvAkLQmNhCvTVLkFsxhk1Vx0ACJED62qWih
k9HSe2cgh4ALqoFTXugFu8GDwMi2YmY3QoVFltTxlebafqcbkjp7CiHs1h2awiP205lHpbi/qdJb
bfT9ik2eoiETCRmdVUgaYcrgPvtmgSpFm0EOFQpU8LS8iFW9zdZLJvOJBfpjZuYd7h+lAKqnzLwu
C7OMHfYNhOY05Pio55UR2xpDvRB1NLn7L1m5aapK2oymwINtxCYPerLEgYHKEEm1MNIfDMrGJPZA
U77aXhOKPNVkRA42T7rBq+4hzy92JfHuC2fcsWbKfLysU9ZQSPMLE1baTMslP6W5wAQ7u4NmLogW
00D8jFMM1HuKihmWe75628dcIPAQgLZRUG5MzGYHb9g7zH4pjm1Z0BYMmhXTGToQZwEcaiPjcIij
gKlhAgVDswthSWOAWdr1yCY3d3h1qqSLe/I+KoJk3DeeTQu/i1LUmhALZqPYtinTv12lq7pOaCt7
KoFo0haR3qWyPs0d2+xWZDiGKa9aL23J8YMYU6lh8wrVlNxd15OaA9lG1XWma7diKcZtlajFEOfJ
soLBDNe+US0CW6A7i9ZHuL3ThapLSMINScy5ioda8yJxecN9KLFkC7NTHDNlKRJ0re2pAwLxZQfB
hcnBSDkqyT3+CJ10bis7y0OZ5UM07KO8dU9+eX19sRQcdvHPr3AES3EEY0Z8wUFbx/Dsyg28ZovP
9nbLx2kDkcTKylbEOQlIyGpKspzJyOYQimUmNZEZ0VGX6DYfWa/fJzdBbGR90uRCT2rVWexoDEd5
ZJW+mKBj/FiHKv3BM3Zarboo2ByuiTMdwOxdiVAITGY9yv1mJ/mo256BKRDwGYhqJwoHMt7KnTa8
LZ+OHe0FcDajsySr0m4G0LZiq0EQfOLm8qdVzHgpZh+fKgtQA4Pd8NhPO2L8fPLobLauVJnTpqcM
N0+FFIn48oQiFm1Dw9VcqXRCn4l8V/IOWZequ4gO1YoOX/nOXiDYXNRUNBwoQr5HrsOiDWNhFfOw
TMNUHXLRyDephA9gBZ3aYRhgW6uKj6nS+Iamz8Pos0gyakowjfwHm0EKrTfjUt4LeagXnIB8zg+t
PezvBRvpGxlEle5Ms/sgLTp2UjPV2h2NR7lCMYnurpwqD2CLLUAcyJU0i/CVXJsFDfD2WFdjHzwE
b+PfVkZ8QsdpvFJ2f+18dnumOxqbtRQnX8Qtz/IqttzsM6WmA8Zuyj7pQHsE2tzQOWxHmjRJqkwQ
q0u6mLHUsQ0PdD+2FKa6q7eUvter8qV4bko+Y5AcPEyhYXmByzHNsgsS0zk1t5IWaohMk4kXwfLN
EHs1Z07oSxOM6DLB3osQ1eRYayTGem0p3wQ3smuHroH2KU062aPmmzxKw6w1g01Ge89LDjq3giiE
GF+apbuE6nz2EA396gYoHVxst2i7GTBsTQq5XiP72KuB5tKFakT6cvL2cWkMHmKnH8ND+jKmzFt8
OBs2YXqXZgOK1LHJua0AmZrlneuic7pZ5KsuFWc5Zau+oG8h6KoFSGwphsokRKmsoGzkp5TyPA2y
qbWi3YE/dpgI+8KiU0NUKDh1aRJcHfAsN9oh013z1wdK2W63j6mEPkY0lS8qJUn51jSoYAF/C2JZ
o+EuGDudk5fiN3p0JH3jSoT/EEcTBesypHsny0LUBwZzaquvqfk49tgVL59uOYtprhhI7ASFRASg
NsV3oPOqDICfBN1rk+tySmpXW4oXr86ul5Pvj/vz5/fj/vR+2p98P/4+QCY2UeuIXiH6FGFOT0Zi
DfvWpjWbP+MrcHVfqpQUwm+Uz5GHuh+okg1120gI6+Yb89ynwbah/6AXDlPzVa1jvuB9bz6zNW9m
PR+Vzab9QF3G8B1ZtATzDX3dqoq4aYRRXNJ3d2A9Nt+YhWXe9K6D9jFpyRu4svmkB+N/181HsfTC
LPHM9W8zGAXiLi9bYUpJ2IKu6FerV4yA3h/mPiq7dvIOwvOHvPZJzAeElLQgHHrtNBnNR1M8Pn1J
Z2d/cXLiLTzPn46C6UKGU+lPZ2EQzLxjb+4dnxyHao4/8RQrrTakoubTyDzT0X27AfbsbgeMSbQ3
KrTnTlB5PRWGJ17gL+beyFMyPAlnMlCLcLQIT2YnahHMpkEYnEwWvJ7eJFmrQ81upvcljcxGYHCZ
3aoUWadoKO+UvEV8MIriT0x2kl+sjO3nre+j3LQmg3nvw4f/B4JBxlk=
===END CRASH DUMP===

**Comment by Intyre** [comment]
This is NOT a PocketMine issue. Please search before creating a new issue.
