### ISSUE TITLE
StringOutOfBoundsException: "Uninitialized string offset: -1

### ISSUE THREAD

**Issue by FUGAMARU** [PocketMine/PocketMine-MP#3504]
CrashDump：https://app.box.com/s/b6pgnfpk4guqxnoljvwkixdq3m57pkap

OS:Windows10 64bit Home
PC:ASUS XX42-X550L
RAM:8GB

Server crashes without permission
Because use the Google translator, might English is wrong.

**Comment by astersx** [comment]
They dont care :/

**Comment by astersx** [comment]
Try using always spawn,  but will trigger bugs,  very rarely,  invisibility and god mode bug :(

**Comment by astersx** [comment]
Use Asr to avoid that ;)

**Comment by PEMapModder** [comment]
@astersx this is not a forum. And this issue not being closed means that it is being investigated at.

**Comment by Pub4Game** [comment]
My God, I have more than 30 CrashDump.... When this will fix? Can this be avoided? Causing this crash and how to do?

**Comment by TahaTheHacker** [comment]
The Best Way to Fix this is to Download AlwaysSpawn plugin.

**Comment by PEMapModder** [comment]
@TahaTheHacker this is a bug tracker for tracking PocketMine bugs, not for providing support. Using a plugin doesn't fix a bug in PocketMine itself.

**Comment by wrewolf** [comment]
why pocketmine\level\Level->getSafeSpawn call pocketmine\level\format\mcregion\Chunk->getBlockId(integer 5, integer -1, integer 9)
i try fix it localy, by edit getSafeSpawn code

**Comment by astersx** [comment]
Nobody cares!!!  This get fixed with always spawn :) . God bless creator of always spawn :)

**Comment by wrewolf** [comment]
Work for me
```
diff --git a/src/pocketmine/level/Level.php b/src/pocketmine/level/Level.php
index dec5d55..5569920 100644
--- a/src/pocketmine/level/Level.php
+++ b/src/pocketmine/level/Level.php
@@ -2664,7 +2664,8 @@ class Level implements ChunkManager, Metadatable{
                        $x = $v->x & 0x0f;
                        $z = $v->z & 0x0f;
                        if($chunk !== null){
-                               $y = (int) min(126, $v->y);
+                            $y = (int) min(126, $v->y);
+                            $y = (int) max(1, $y);
                                $wasAir = ($chunk->getBlockId($x, $y - 1, $z) === 0);
                                for(; $y > 0; --$y){
                                        $b = $chunk->getFullBlock($x, $y, $z);

```

**Comment by astersx** [comment]
If it work,  please give me link to phar.  I tryed to compress,  but pocketmine  break.  Other plugins was compreses succesfully....  :(

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
