### ISSUE TITLE
I cant change gamemode(i am op) It doesnt work in console either

### ISSUE THREAD

**Issue by GilbertMC** [PocketMine/PocketMine-MP#3510]

**Comment by TahaTheHacker** [comment]
This is not a forum.
And that's not a bug in PocketMine, it's EssentialsPE's fault, 
Close your issue and report this to the author of the plugin.

**Comment by iksaku** [comment]
@TahaTheHacker This doesn't have anything to do with EssentialsPE, you don't even know if @GilbertMC uses it

**Comment by jazzwhistle** [comment]
Check the ops.txt file permissions?

**Comment by TahaTheHacker** [comment]
QUESTION : is the problem the permission or just doesn't work?

**Comment by GilbertMC** [comment]
The pproblemmis it says i dont have permission

**Comment by TahaTheHacker** [comment]
if you have EssentialsPE, then it's EssentialsPE's fault.

**Comment by GilbertMC** [comment]
Essentials PE was working until i updated the server to 0.12

**Comment by TahaTheHacker** [comment]
when you updated it, did you update the plugin to 1.1.1 or farther?

**Comment by PEMapModder** [comment]
This is not a forum. Please do not create issues for help, and please do not comment like this is a forum. You are sending notifications to 200 watchers of this forum, where most of them only watched to see real issues and commits, not to see help requests and people trying to help.

**Comment by iksaku** [comment]
If you feel that this problem comes from a plugin, contact the plugin maker directly, don't bother people that can't help your with your "personal issue"
