### ISSUE TITLE
I can't get items from creative mode (0.12.1)

### ISSUE THREAD

**Issue by Kamtheslayer** [PocketMine/PocketMine-MP#3511]
Everytime I tap on an item in creative mode I can't get an item

**Comment by TahaTheHacker** [comment]
Use PocketMine 1.6 build #29 that fixed it here:
http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/29/

**Comment by Kamtheslayer** [comment]
Ty

**Comment by TahaTheHacker** [comment]
and close your issue
