### ISSUE TITLE
Big problem in PM 1.6

### ISSUE THREAD

**Issue by lucasvitegui** [PocketMine/PocketMine-MP#3513]
![pmtimeout 1](https://cloud.githubusercontent.com/assets/12215261/10009951/5e6b3a86-60ba-11e5-856e-4ba56d610f40.png)
I installed the latest build of Pocketmine 1.6 that don't use PHP 7. " PocketMine 1.6 build 30 ".
I could found ways to solve issues from plugins. But the biggest problem is:
Players connect, and in few minutes they are disconnected by Timeout (?) and can't join again while server don't restart. 
Note: This problem didn't happen in PM 1.5.
@shoghicp Is this a MCPE Bug or Pocketmine bug ? How i can solve it ? Thanks and Great work !

**Comment by iksaku** [comment]
Besides "master" branch, is not encourage to use PMMP code, it's just "experimental" so don't complain about it

**Comment by MajikalPayton** [comment]
Keep in mind that it could be due to latency

**Comment by lucasvitegui** [comment]
But also keep in mind it didn't happen when i ran in PM 1.5  ...
And it's not just some players... Everyone that try to play, are disconnected.

**Comment by MajikalPayton** [comment]
Don't rely too much on PocketMine 1.6

**Comment by lucasvitegui** [comment]
This is because my server are getting down.. And i just can not come back to 1.5 Because it would crash when someone that already joined in 1.6 join in 1.5 (I have tested it )... So i really would like if a new build would be release.

**Comment by MagicDroidX** [comment]
you should ask for help in pocketmine forum but not here.PocketMine 1.6 is still not stable,you should understand or just not use it.

**Comment by Gamecrafter** [comment]
Please stop, this isn't a help forum. You're spamming hundreds of watchers' notifications with useless comments.

**Comment by Gamecrafter** [comment]
@MajikalPayton @lucasvitegui @MagicDroidX Please stop, this isn't a help forum. You're spamming hundreds of watchers' notifications with useless comments.

**Comment by SkygridRex** [comment]
@Gamecrafter I don't like people like you who does not contribute to society and help when needed no one to help
@lucasvitegui download PM1.6 build 29 it's stable
