### ISSUE TITLE
Bugs with pocketmine 1.6

### ISSUE THREAD

**Issue by robotnikthingy** [PocketMine/PocketMine-MP#3516]
I'm not sure where else to post bugs for bleeding builds (how can you fix bugs if no one can report them), so if this isnt the right place please redirect me to where I can post bugs

1. In creative mode, player hotbars are not kept and are reset to default when a player rejoins a servers
2. Quartz pillars cannotbe placed sideways. When you try, they stay sideways for a second, and then revert back to standing upwards. In the recent patch they made them able to be placed sideways, so I think it has to do with that
3. The hotbar sometimes goes crazy when playing using a bluetooth controller. From testing I havent been able to reproduce it 100%, but it happens frequently. Basically, when using the left or right bumper buttons to switch between items, the selector for the hotbar will go crazy and rapidly switch between items for around 5 to 15 seconds. Tested in singleplayer and this does not happen.

**Comment by shoghicp** [comment]
Remember that bleeding builds are not supported, and they include workarounds for client-side bugs that degrade other features
