### ISSUE TITLE
Arrows do bounce back if shoot close to block

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3518]
When you shoot an arrow through a gap or next to blocks the arrow bounces back or does bounce back and then fly to the target.
Happens on the 1.5dev-1262 build.
How to recreate: build a 3 blocks high and 3 blocks wide wall
stand behind the wall
shoot close apart from the wall.
[+][+][+] /^
********P
P is the player, /^ the direction of the arrow, [+] are blocks.

**Comment by SkygridRex** [comment]
Bad implementation of the arrows

**Comment by thebigsmileXD** [comment]
Thats true, they are far too big (0.5 blocks..)

**Comment by shoghicp** [comment]
Don't reopen closed issues.

**Comment by thebigsmileXD** [comment]
I closed it by accident. The issue is not closed.

**Comment by thebigsmileXD** [comment]
GitHub had some trouble with mobile clients yesterday. not my fault.
