### ISSUE TITLE
There aren't some effects in PocketMine-MP 1.6 dev!

### ISSUE THREAD

**Issue by Johnmacrocraft** [PocketMine/PocketMine-MP#3520]
We don't have hunger, night vision, poisonous hunger effects!
If I try to apply them effects using /effect command, It says no effect that named "16". (Maybe in English).

**Comment by SkygridRex** [comment]
You use effects id's lol

**Comment by Johnmacrocraft** [comment]
So What?
Actually, I only use effect id for speed effect. It's id 1.

**Comment by shoghicp** [comment]
This is a place to report bugs, not non-implemented features. Check the code, we have comments there.

**Comment by XxDXM-hippiexX** [comment]
Speed is broke..doesn't work for me at all. Says i have the effect but no change in speed. Should i open a new issue?

**Comment by Johnmacrocraft** [comment]
@XxDXM-hippiexX Yes, you should open new issue.
