### ISSUE TITLE
a WHOLE LIST of bugs to make things more simple.

### ISSUE THREAD

**Issue by RagnarokkGaming** [PocketMine/PocketMine-MP#3524]
List of missing or wrong things (bugs) right now as of "PocketMine-MP_1.5dev-33_master_cbef0e25_API-1.12.0.phar" update with 0.12.1 alpha of Minecraft Pocket Editon:

Weather:
-No weather at all. Not even working with commands.

Mobs:
-Stay idle, only make sounds, appear to have no AI whatsoever. 

Terrain:
-Grass blocks generate underwater
-Terrain generation has massive oceans
-No new biomes, (Only desert, plains, spruce, oak & Birch)
-Uses very old terrain generation it would seem
-No mobs spawning
-No caves or structures, (only perfectly oval shaped lakes)

Enchanting:
-Missing all items 
-Uncraftable
-No XP bar or points

Nether:
-Not working (Cant even activate portal)
-Missing All Nether related mobs
-Missing Nether Brick Fence
-Missing Nether Quartz
-Missing (glowing NEW) lava
-Mob Spawners dont work and cant place egg inside

Rendering:
-Freezes screen until animation is complete (sometimes)
-chunk loading errors, (many times you have to exit the game and reenter the server)

Items (Missing):
-All enchanted items
-enchantment table
-potions
-brewing stand
-missing most brewing items
-creative inventory missing extra tools & weapons
-nether brick fence
-nether brick slab
-nether quartz
-all double tall plants
-(Not supposed to be in inventory but still is: Nether Reactor)
-Mushroom blocks
-redstone dust
-all mob eggs (except: Villager, Zombie & Squid)
-Arrows
-rails (all rail types)
(a few other various items)
-Apples
-All food aside from carrots, potatoes, eggs, cake and fish

Other:
-Egg throwing only makes sound
-new biome tree saplings spawn oak only.
-Nether frames dont work
-Fires dont die out
-lighting errors after TNT explosion
-lighting errors after morning
-lighting errors after placing torch or jack o' lantern
-cannot light leafs on fire
-fire does not spread
-Snow gollums dont spawn when created
-iron gollums dont spawn when created
-sometimes day and night sky errors after sleeping in bed
-items or placed blocks despawn
-WORLD regenerates into new or reset version of world.
-Deletes uploaded maps and loads its own maps, usually only a handful of seeds, quite often generating a previous seed)
-Kicks when player moves to fast, sprints or jumps to much
-Cannot place minecart
-Cannot place mob spawn egg in mob spawner
-zero to no AI in mobs. 
-No animation in mobs
-Hits dont always show hit animation
-Zombies drop feathers

I am using NetherBox as my host, and they have Multicraft as the panel. 

Feel free to add any more you find. 
Some new things do oddly work, like for instance snow particles do fall under leaves if snow is placed ontop. Its odd.... :D 
-Ragnarok 
@TheDrakonHorde (Twitter)

**Comment by JoahDave** [comment]
That's quite a list you have there...

**Comment by PEMapModder** [comment]
Please read the contribution guidelines: open one issue for each bug.
Some of the things listed above are unimplemented features, which should not be reported here.
Some of them are already reported.

**Comment by RagnarokkGaming** [comment]
Well, if you had the job of fixing an entire software platform mostly by yourself like Shoghi Cervantes does, would you rather see a bunch of bugs all on one page organized, or have to read through thousands individually, one by one? I'm just trying to make the guy's life easier mate. "Think smarter, not harder."

**Comment by gaoyichuan** [comment]
I think almost all of the list is the unimplemented features...

**Comment by Falkirks** [comment]
@RagnarokkGaming The issue tracker *is* a list of bugs.

**Comment by RogueMission1218** [comment]
A lot of this list was implemented and is simply not working. Irregardless, I'm pretty sure Shoghi appreciated someone taking the time to compile an organized list, trying to help him out, instead of  impatiently complaining about bugs not being resolved yet.

**Comment by SkygridRex** [comment]
PocketMine is a project that all your code is zero, you know your list if a contribution by allowing organized watch for bugs to fix.
There are ignorant people (@PEMapModder and @Falkirks) not seen something like that, we must be organized.

**Comment by RogueMission1218** [comment]
SkygridRex - well put!
