### ISSUE TITLE
/enchant bug.

### ISSUE THREAD

**Issue by PocketKiller** [PocketMine/PocketMine-MP#3528]
Hi, always when i use /enchant <player> fire-aspect 10 or other enchant it just gives me protection enchant, not fire-aspect or whatever else.

**Comment by SkygridRex** [comment]
Yes, when i enchant something with exampe: looting always give you Protection. I'll check 0.12 branch

**Comment by UltimateMcraft** [comment]
I don't think this is a bug, its probably unimplemented still apart from protection,I know what you mean though

**Comment by TahaTheHacker** [comment]
idk.. or maybe because pocketmine has no supports of what enchants do?

**Comment by MCPEGamerJPatGitHub** [comment]
Protection is the only one supported.

**Comment by kvetinac97** [comment]
No, it isn't. If you'll check the code, you'll find out that you can set all, but only /enchant <player> 0/1/2 <level> works.

**Comment by SkygridRex** [comment]
thanks a lot

**Comment by kvetinac97** [comment]
I'll push a commit that fixes that soon

**Comment by UltimateMcraft** [comment]
@kvetinac97 :+1:
