### ISSUE TITLE
I can't find ores.

### ISSUE THREAD

**Issue by MilkoIvanov** [PocketMine/PocketMine-MP#3531]
Ok i can find ,but they are too little.Can I fix that somehow or it is a bug from the server?

**Comment by UltimateMcraft** [comment]
It's world generation, not povketmine I think

**Comment by RandomAltThingy** [comment]
@UltimateMcraft World generation has **everything** to do with PocketMine. Generating worlds is server side, so shoghi has to code the generation himself.
