### ISSUE TITLE
Give command return unknown instead of id for many items/blocks

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3532]
The title says that.
for example:
/give player paper 1
/give player diamond_sword 1
..i guess this happens for all items/blocks that are not in the creative inventory

**Comment by SkygridRex** [comment]
Yes probably a bad implementation of some items and give command

**Comment by UltimateMcraft** [comment]
Yes sometimes it says Unknown and it doesn't give it so I have to do /give Ulti <item> 1
Probably its just pocketmine

**Comment by thebigsmileXD** [comment]
It always gives me the things. But they are named "unknown".

**Comment by Intyre** [comment]
Those items or blocks don't have classes What version are we talking about? If you guys wan't to help fixing this I can write a todo list with some instructions. We can pick a task, make it work and submit a pull request.

Maybe someone can finish the list with "Unknown" outputs already?
I'll start:
- paper

**Comment by thebigsmileXD** [comment]
Simply EVERY item you can only get via command. List them yourself ;)

**Comment by SkygridRex** [comment]
Or check items.php too

**Comment by Intyre** [comment]
It would be helpful if anyone would provide more information and maybe help finding all those items. But I guess that it is to much to ask for.

**Comment by UltimateMcraft** [comment]
@Intyre Quartz is one I think

**Comment by willowmaster66** [comment]
Most of these items are because they are new in 0.12 or they are used in not yet implemented features like rail and powered rail (and carts). Quartz and nether fence have been built in with the stone cutter pull request I made.

**Comment by thebigsmileXD** [comment]
All items are listed on Minecraftwiki.
Under the point data values.
Theres a section for mcpe and a legend. I guess the red ones are command only

**Comment by Intyre** [comment]
We can start on making it easier to add/remove items/blocks the next time. 
I'll make a new branch when I finish work for people that wants to help using the **mcpe-0.12 branch**

## src/pocketmine/item/Item.php

- [ ] add missing items
    - [ ] sort all items in ``public static function init(){}``
        - sort using ID
    - [ ] create list of missing items
- [ ] create seperate functions for views (maybe?)
    - [ ] sort everything in ``private static function initCreativeItems(){}``
        - the way it looks ingame using **MCPE 0.12.1**  
        
## src/pocketmine/block/Block.php

- [ ] add missing blocks
    - [ ] sort all blocks in init()
        - sort using ID
    - [ ] create a list of missing blocks

@thebigsmileXD Please stop replying if you don't have more information to add. This is not a forum.

**Comment by thebigsmileXD** [comment]
Thank you, i tried to help. THERE is the information on the website.

Just 1 more comment:
Adding them to the creative inventory works with a plugin called "CreativeItemsPlus" by mcpepig (or mcpig)

And i'll send you the list of the items and block this evening. I have awful connection.

**Comment by PEMapModder** [comment]
@Intyre I believe that making a Wiki page for that is more useful.

**Comment by PEMapModder** [comment]
I dumped the detected IDs using this script.

https://gist.github.com/PEMapModder/30858989dacc97d6b942

The output can be found in the gist as well.

**Comment by PEMapModder** [comment]
I have written a script to generate classes for each unnamed item. You can find the base64 of the zip created here. https://gist.github.com/PEMapModder/30858989dacc97d6b942/#file-gen-zip-base64

**Comment by Intyre** [comment]
@PEMapModder Good work!

**Comment by PEMapModder** [comment]
Fix in #3546

**Comment by thebigsmileXD** [comment]
@PEMapModder genius as always :) nice fix!

**Comment by PEMapModder** [comment]
@thebigsmileXD it is actually very easy.

**Comment by thebigsmileXD** [comment]
Thats why i like it :)

**Comment by Intyre** [comment]
Most if not all item names are fixed in the [0.12-items](/PocketMine/PocketMine-MP/tree/0.12-items) branch.
