### ISSUE TITLE
Arrow crash

### ISSUE THREAD

**Issue by CaptainKenji17** [PocketMine/PocketMine-MP#3537]
*Shoots bow*

Arrows hit block

5 sec after

*game client crash*

see's back again the arrow in block

crash again, whenever you are near at the arrow which is stuck on a block

**Comment by TahaTheHacker** [comment]
I have that bug too, but it's only when <i><strong>Picking It up</i></strong>

**Comment by PEMapModder** [comment]
So is this a confirmed issue, and is the source of the issue (PocketMine or MCPE) located?

**Comment by astersx** [comment]
This was a bug on 1.5 too...  But not always crashed in 1.5

**Comment by astersx** [comment]
Is pocketmine source of issue ;)

**Comment by PEMapModder** [comment]
Can no longer be reproduced
