### ISSUE TITLE
Error: Call to a member function hasPermission() on null

### ISSUE THREAD

**Issue by greckminas** [PocketMine/PocketMine-MP#3538]
Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 449
Type: E_ERROR

Code:
[440] 		return $this->perm->isPermissionSet($name);
[441] 	}
[442] 
[443] 	/**
[444] 	 * @param permission\Permission|string $name
[445] 	 *
[446] 	 * @return bool
[447] 	 */
[448] 	public function hasPermission($name){
[449] 		return $this->perm->hasPermission($name);
[450] 	}
[451] 
[452] 	/**
[453] 	 * @param Plugin $plugin
[454] 	 * @param string $name
[455] 	 * @param bool   $value
[456] 	 *
[457] 	 * @return permission\PermissionAttachment
[458] 	 */
[459] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Krustycraft.com 2.6.32-504.12.2.el6.i686 #1 SMP Wed Mar 11 19:05:53 UTC 2015 i686
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SignStatus 2.1 by xpyctum for API(s) 1.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
BanItem 2.1 by LDX for API(s) 1.0.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EasyMessages 1.1.0 by Gamecrafter for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleAuthHelper 2.0.3 by aliuly for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
LuckyBlock 1.0.0 by xionbig, xionbig for API(s) 1.12.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
1vs1 0.0.3 by  for API(s) 1.0.0, 1.1.0
PureChat 1.2.9 by 64FF00 for API(s) 1.11.0
ItemCasePE 1.0.6 by aliuly for API(s) 1.10.0, 1.13.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
ChestRefill 1.0.1 by Falkirks for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNO4ty27aWv4KRM3OTjqi3/FDHnXUdp81du9HaTrN7qzseiAQlxiTBEqBttdt/33MOQBKkldiO
fXc306mJQ+DgvB8g9GdHR4nozIaTyXg6mo73B92OyHOZd2Z/dvQmg1edk6uT8/MP551uJxFK8RXC
jnkcMy0ZZ4lIliJnYZH6OpIpW3M1F3kSKQWj128YgNIijmF1GMW4tK9yv59J/1roJEpFfx7zjciv
rsajZaRhWgzAzmwyOfir28niYhWlnVnIYyW6HV8GAgmbTAaAaKEXOhe6yFP2Sq8j5f2QwcbeD5FD
wIXQr1+lPBFvvgfUk8mQ1v1FzyN4pocxAfvffUejCY3Yd+zfMp7zhGUVssWiRvzfSudRumKEnNZN
7Toa7FZILIVLKWN6s2ff9Gm0T6OsWMaR/yUZGvr/pPkHX+F72yriejqouZ4OLdfTkcv1dNziek6S
Z6+sBnBKWzBtCUynrQnIM2Ps1Q2PCzNj15HRdK8to+2SPtKa++tEpJpW7bvymx5slR8PgnrV6yYr
XUMwO2SLBRpm19JXAUDSYHk65z7Y2m+dnQF7/WbGaoNdLC5EfiNy7wc/52r9tkiy18ip4Ombzj+7
nZVIRc5jtFOYhRwAjcPebiBugORlEcVBZzY6AOPOpZY+mMVsPOl2eBbRvOG4N4B5K/CFWWfwyH+w
IOfXcbTENb09wlCQXmad0ygt7ti/54XSG6A41D1fJmzU2+2NR950MOkNR71RT8S7vWh3f5ftDNnF
2Zx9EgE74zkbDtnwYDaYzqZj9vHymI0GwynDibBDts4A/xQwjWD0h0iBsQ4iHpiXV1KV+wOABjEN
Ks9WKKUfY5DtSRgKX9PY0t0AdxuyHPSmAOGFXstcoZJ+Sj6doexJiL+hFEdABABEypexALp0XkAA
CUQGVOISeKdkqN+6gIRjrCFki4W7fXOEMUpy5HX+4eLy04fz07cAuhVLFWkgHG0IGDyWsczPuPbX
Dk8OsMnRkETocHScCyAtf4dW+FKM1bsvFg1KHsHOPI/+EJ8QTcVMBWorZ7fJymkUH+eRyjYjedA/
SlciluzXKMgj2eRs8O2claQsFmecCHoER5eQ+I5lkvA0ELnDVhPu8DZqcvX2PxvkD8jqUZPm78j+
Hdu/k2/nDrZaLBpkPYXPTzKPgznEGrBdh80G2NXgyJLu8MrjqIg397XVfaZBGryLxS3Skhla2qxd
XB6dX36cu4x11lpnatbvQ5BcF0uMZ30ei88gmlwCSqe68Gyc6UPGFP2EKy3yfoN1kNCPOWzl0zs3
/jjQlrO2DPzkRsYXwOKLOaqz9WPFAdK4vb3tCSAFsfb0NXJ2ohRkwAiqp/mJw1oD/EAgOhUrpO9D
eHY8P2GXgicvxqZLxmJxCgySqL9m09tUbyg0BPYbrIEELqIki8UpmMZPlJe1dHW87W07mrV84eyj
CBR/MRlsocCo/DjmSn1V765/nwSRPsrv+XcJvsfT1VJofgUlydXOAIrQBofzkzOenckAtdGOcN/I
ZSYSniWE0nq7AMp4Dt7eovOpyneI7V8k0JV4/zj25l9y+nIfMoxVeqG5LlTDHiqgG/h7w4aA7rKN
r4vkpYRTbwqlpUvAI4L72UXGb1OXhRLSVPn0MRFr+O082F2fEry3hKsfefpei8QNwhbSTFDDzoOp
+Dmp1m76lCT7KySTc3HL88Ah3gF+xZqeUkg8h6uamqcwNhdQgYZFTPp1i78GvMHe5KvsjUl7z6+H
GgQ8haPjtVD6FCsENxO40KbrjB7hOvvPKMrrjZ/pPWc83VCUa4SDGtj0oUGbsS8Vec+s7aBg3VDE
V09R0jkkRJm0goEDdHiZ9P5vC/OaqqcweMZXkX8pYjGXuTanBZXGmm+a1jj+31Kbzp7CzglXmzNz
OuhaXwPcLjRbhdVPsITOJ1plx3OqKwH720NLMD+XmqP5+2+oNhwa+3NqMs6wydhWbzRYRwlh3wZB
K3d17QBbQac3bkrnv6RS6+jg4OCLtv2tRXhFwlP0bcrWI6DvXjVNwCY3e+2MXcvOdBRA3lqu1pGf
vXBhjcRgVeUQ9rS+sqa072BpSOBnEWci3yoH+6odeccPu/BDnLvCfoQ7r4mQR2n4ud31Pe5BWO84
HcwqaLodObnQB6LcpdBrkYvg6sXsw9l8sbCDx9v/URxxN9CZcduHWxHuH9z/mfvXL8YCbbq1W/xq
/VMoLZOjWOSN49YGuMnIv/q4w916sWgR8k3nHnOZFdk9Fl1oy97+xRw6Oz/vQOe08K83dBjt8OUA
Hzi8uIM3y2gFwPLppTisafjmIGNJ6jvsYJyNedYKrxbS9rZWj/tZfpZiD/+9GJPK7IxF7aNPmXl2
Kd+6Ua+EtM9cWynyHY+vX6qr1TzTMoA4V+/9mJ72/fwilg0PqkAu8UBYb9IkPvq7VOuC//z2xURf
YYRGtibiabk8+kw41kG/QoGxosgFfm1sRIoK1i5ah63EtDt5924waLL5jE79yuCD9rakwHl8evGC
K22KrrEAz8MbNXTYpWFbpc2Y+MJVJxRUURiBxy8WMhU3SuJ31Q+p+FXB/x55MgEMHa+5bqmNQO3Q
cPCw0h5ixrGJe3w1KpkvKBPpqp+erUpCAlLAvvOYK9E433eAD3yb++qXnfHz20jgJ/GBkkw8pbt4
B5XkZc5TFTYCfwPcZqzlly/eT5QIsVisyWiOnqzVEmm/gaU8pDoXYRTH7UMqC23zvyV9RPm1erET
XmdvqNEahDym6Iyhwzzlq5XLTQV74GTA/cDzUimx2vylPjzV3PyF1xvwAoyAdqgkg66M9LJcQv2g
Izwk6ezMqxE7lmkYrRhekVrki3TnshDsQmRsdMAGu7PJdDbZYydvL+n6BU5IpA4OF8VgwPdG+Ge5
ZGYUmz/C3Pcwg91jPLLAZYYML5O5PhweDMcjBN6ugUMvjpQ+lGGIEJ6mskh97O/wbpbH/XUkbgTe
plGHMiVMeOzq2W+2oLnD4WifCON3dpU6nA4IWRzLWy+Mo9W62sCs5mmU8LiJMZHLErACCSYyEIeE
JpQ5EFTBLKI1zwNf5tU4u8ns6iAKw8gvYr05HBK28vOap4TWUbpShwiOga/YQ4s8pFPKGqaECJwp
eBnu8O3Ju6OPp5cINUbn/V6IfGO3tKDcB3FYevC5l0FvBsiDw+/oH4ik0NJT/EbYhchTvgEVJBHo
ZUD84hWaqtHubZIYLYZhDGU+GUsB3OBlJ7QZBtJhzoHU2RxsiF2ClwpWsst4Lhh00QxyrYIHrpmP
itZsKViU+nERiAAe2D1bRVwXMoGVISJo41Q8FF0msUFXiJItc8Gv2UYWucXFopCB1iDj0w6gsBys
BvIDIP5F3Fbo+oEIOahMsVuZ/k0zrLZ5zlBcCTDrgylt8EIh3nozfN+uRcqKbJXzABD0FinauEE2
W6Rs53KdC7BtAAEVMU9XBV8JhvcISWTWH1QEY2g4IGv9QULFpRDjfMtFcyFe0LPBQKS92+g6ykQQ
8Z7MV30c9U/Bla5kePX+4sPV7vjAG13hOhBjhWjGFhC1VosObvRpTYcbeJ1SQTxheLXS3K0DNWFO
iLkGudFrkiZRCnTAk9Ck0kDcRL5ga54GMSk5AcTGY+ot6RIlwKEG1oFEXzPHk0iMudLG/FgqERiy
jtBvGYYFvOVnT3rYTcTZf6DNwxSy/fIMaMYw+uLCizWs42ilSgI1dhejKm4RsUKBEUKkBkMg7o7m
72EmhPwA5VS/8ICsJRBVoz8hLyvxAMcMAwADcwWLQFKXG2btCKZbn6ze1mLY+QTZC5QJJsWDgOVC
GctDMsHWroEcrqDSwqjHwN6WAuUBQhe/F5wuv66iG5hrbg++tltChH4DyM1+EAsExloPtLlaiXwG
b3HnXwq6MwvudKQ2qX/J1TVYfH4NDtTD9x9BCWSfJZM4a51LiMpgEjBbdRlFK2ajGphsF8SQgNTo
ziSJBXIXwpIiBc/BKYT7gkwG+AHnyuUdRGAtQATADpl6WpGGUjXkvA/RQ+m6L3hil0X6b3j7N6dV
gcAMQFbYWsteAwegZzZCiRAPnuVyRpjQW03oI1/9KZZLECxmbGbAjCIixqRErPhyo4EgdmFIGdDm
kUL1Gk8Hnm4jIoyEzTDt2MhqQYrkEkZgLhCmIKynhCqEGFHuaNQPzBRktCsJfEh0DZQZ7LMiIk2o
nrHBgkIFRWUNoYYH/8/Jx+rnK8RjOn0W8UrLjPa3oaqix2JTDFwK8yFEGUsN7lmSNByMJoYq6LQi
SekIfVHhhj4FZEtd5W9D2ApCTYA2RjM88AdhPI3CuEwhgIGHgtwwOnxJrEacUAvFFOHR1820BSVc
xAHeV3uyCUe4wwcMIZjhaHrv/mRk29aoIMJM+JgIFYkFaTUyNmsrBkCSIlM1m+OB5VO92UqQ5Xps
uF7xfAn693wZx6Y+Qw/bKlUyJyTFrmF2DfhuwtOCUq5LBZQjBdjCm24ZE1rGYK3BxFW6MEvYk9rK
euyDyXc0AotYyyIOKkIiiCC3KatJR7vFu+FAOTC4OxgYHtnOO/KEe7GRbMWsrpgKc5mUIRbX2vee
G5UcnQITVnVtU9hiP846rH79dZFeKyPvU7J6DIgERMqwyUBumKmSu+SeORQgykzysAbAWqbGhahK
NVtHOdi1dL6VZllbfZgEsFIyy1wMZhc77QV4pkTk+dAjCMO1tYVyI3xRZe+volqkqdCoi6p0A9OI
TSZc4lVlKkQ4VrmQAMGebFQiBzSFqX1rgtFSVDmRws2OG77KN+j4+UYj7i7zho4xY+6jbT1dkgJh
Zbprokqda6k/wEQXmHBnFWjWAtDS1GM/QwsE4j2EWhgM93j+sQtrgYIlxJ/bKNBrE7XJvyv0HqGf
sT1bGNQlgyLBOFN77CgAf1rzOOxDkW+qmECAndmNYEtjfzJ1HbLKzg4up046uUPnwzKIx13j2Ljx
pyiFKhLYArMRZNqY6z/O03lZKdQ1OxZBuIhuH2HBnmaeHbo1GXRtYlmsZrbo+IENsdiwmQWrSnpd
VpSK4thalJXmwqoC0khdJyrWV3Sfrsv6K9+IFu9QK2fTst9r9A2iLCKRbuDEdEw01ZoXsksK90GI
mizMLvHMkhlL4NXK9hPAEJ1PILk3+CXIBCXewA+REzsy7WwPwtT3qSEfJdXt/PLh8mTGKOrCf34B
zVUKzRUhom+xqDoiz+5ckVep+KihLR/6CIgklleyIkpJQAlajUbLGQ1sCsFQZjITmhE2tgi36ch6
fRNcxjBTC1+guyKDS66Es9nrITjKll26bAQvhtteCO333pDTKuFSQeZwiZixtbKnE0xAYDL7Yeo3
mqQmtu5uMRBQF4TVE4YDHt/yjTK4LR7Hjhrxm8zoKJFF6iYAZWu2kggkH7Et6NdPhHjGJl9eynOA
BoZ2g6OZddjwYLR1NVlXKkwfuRQG21KEGIno5AUjFqqhwmrOY5zQZyLfBb+BpIv1XYTtssD2K9vY
owGbi6qChgJFSPcCyrBow1hYxDRNKjBVD1008k0qoRYsx34cDAPQlqL6LLETMr6h8Bdc+MtFNGpM
MBX/LWWgQEtlnPE7xttygR7Ip/xQ20NTF2Sk5zyICuUss3rgljpyUrPU2h3Oh2oFYxIefHlFFoAt
1gRCqy242YSO3uosaAivG7uS9t594m38u+UR9ejQjxfC6teuJ7cnuKdAWTO2/03YMpkVscVmnzE1
tRAvUvJJD6SHRJvjPY/sSKEkUZQJxGqNRy4WOrThAU/DZswUd6VK8Sd1RQbFjqn4jEFS8DCFhsUF
WPZwld0QkU5xeMtxowpIMJ4sI7B8M8UexJkefWaCER4n4M/6mIGaHGuNxFivreSr4IZ27eEBTxNS
pZMGNFtnURrK2gzWEnVPW/ac8z4ohIi+VKabBMt88hAF8lUVodi32Nesfk0Eg61xxlcryD72cKA6
dsEaEX/ceL2dG0MPolPb6EF5GVMmFbdXg02YtzOjgDz1bHKuK0CCysw5MDrGM0M6xBKxzDBbdRn+
PgEPW4ASW4pBZRJCpSxA2JCfUszzOMmm1gK1A/7oIGH2o4JTQxRQcCptElwZ8Cw21JB5XeJXLaHg
dYwtIsFLOKbyhUqJY741AyxYAL8lYlZSQ6/A2LFTnrHf8NHj+DNUBPwTMZooWJYh7mkrMVH2C6Zp
K0+1qRvbdnhLzS1lMUUVA7KdQCERAaE2xTuk065EAD0xPARH16WUVO82Y+9Ojy5no+/3utODu2F3
fDfujr4ffh9AJjZR6zVeCfMxwhzuD9gK7FuZ0WT6hg63xZ0WKQqEvrsfQx5yfkuKJuQMIR2sqh+B
Zz5OtQP1exxpMTY/e/XMT2z/ML+DNdevlj7UNev6F+Q8Bs/heQ0wP3IvRwVez7SDMIrpF2GAemi+
SYU6q96ukvp5Dd5rPsPBpM+q+uyM3+SSpTnLrSZDTbjJdM2B5khQ4LB7MT+lXfE586GWq9dugGH6
ma19YlP89DdEzpmHX4dGg+lgDI+v3oPewvHeWPBpEEyn4/293eFksMv3B6MRnyz3+XhvMhnuL0eT
gWCvYKf5GsVS3QzPpIruaqHbZt1OGCKj5yK0nSZAab99MQ19DpXqBLYdhHt7/t7+/u50CluPD0Zj
MR4sD/YOgoD2U+tE1iJU5FiqyWlkhA+TtbwWKeSZvIJ8EvwaIoIRFN392XD6SEK3NNAMosyMRr1J
56+//gc2wcbk
===END CRASH DUMP===

**Comment by Intyre** [comment]
A plugin is the cause of the problem. Find the plugin and report the error to the author.
