### ISSUE TITLE
i cant make a server [Pocketmine]

### ISSUE THREAD

**Issue by tsuhakkun** [PocketMine/PocketMine-MP#3542]
i did a server, but i trew it in the trash can, i tried to do a new server, installing all again, but in the trash can was still some files from the last server, here a pic of what is showing
![captura de tela 2015-09-29 as 20 38 49](https://cloud.githubusercontent.com/assets/14898301/10181385/a67b5930-66ed-11e5-86ad-89e6573ecc2f.png)

**Comment by MagicDroidX** [comment]
read the log plz

**Comment by tsuhakkun** [comment]
PocketMine-MP Crash Dump Tue Sep 29 21:28:45 BRT 2015

Error: RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [48]: Address already in use
File: /src/raklib/server/UDPServerSocket
Line: 32
Type: error

Code:
[23] 
[24] class UDPServerSocket{
[25]     /** @var \Logger */
[26]     protected $logger;
[27]     protected $socket;
[28] 
[29]     public function __construct(\ThreadedLogger $logger, $port = 19132, $interface = "0.0.0.0"){
[30]         $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
[31]         //socket_set_option($this->socket, SOL_SOCKET, SO_BROADCAST, 1); //Allow sending broadcast messages
[32]         if(@socket_bind($this->socket, $interface, $port) === \true){
[33]             socket_set_option($this->socket, SOL_SOCKET, SO_REUSEADDR, 0);
[34]             $this->setSendBuffer(1024 * 1024 * 8)->setRecvBuffer(1024 * 1024 * 8);
[35]         }else{
[36]             $logger->critical("**** FAILED TO BIND TO " . $interface . ":" . $port . "!", \true, \true, 0);
[37]             $logger->critical("Perhaps a server is already running on that port?", \true, \true, 0);
[38]             exit(1);
[39]         }
[40]         socket_set_nonblock($this->socket);
[41]     }
[42] 

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(143): pocketmine\network\RakLibInterface->doTick()
#1 /src/pocketmine/Server(2216): pocketmine\network\RakLibInterface->process()
#2 /src/pocketmine/Server(2110): pocketmine\Server->tick()
#3 /src/pocketmine/Server(1986): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///Users/Luimar/Desktop/server/PocketMine-MP.phar/, string /Users/Luimar/Desktop/server/, string /Users/Luimar/Desktop/server/plugins/)
#6 (1): require(string phar:///Users/Luimar/Desktop/server/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Darwin MacBook-Pro-Ana-Tuyama.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Darwin, mac

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfQ134zaS4F/BOnkbd0bUt2RZWedGtuVu78i2YsndyURzfBAJSYwpkuGHbfXs3G+/qgJIghIl
27O59/bdGyctkahCAShUFQqFD/39KHbW4qjfaLdbnZPmabNTOXJ5FA/D0A+P+n8/ijcBgI8EvVeO
1iKK+BJT7vnjyJmz6SoU3GZWyKOVsNmvIX90nflsFonwSYSz2cPleEKPE996FPHf+iyiB3PuePbx
hz5LPD53BYt9himM23YIZbBf2z3AHag37mIpG+Z4LIkE1GORuO6V42JFghUP+7Va7QGKjGqjxFnz
sHYposfYD2qyGrUxlXnjeMK4GVcxRy0KrZqsbIq0VVVAC7AkWcrr+IDrQgFH/VazchSH3ILHX4++
qTPKGhDOGhBqnoif/fCxJjl47cUiXAD2caPdAn7kiLOZwpzNtlCNH21/6liPxx+g0G8aOyXIah03
m43umykGoW8BqyXJ5l6SjUZ9i6SEGD/GWYVa+3I3TnvdA7nHsgp+KMm095I5qbf2kIliHsYye2cn
ey4Fx+12cw8F07R8L4rDxIqPdfiFvw547ICsXoCCRCOf2yJk/vw3YcWVAqUkdtxoNrvhjjfyl0sN
C8g63pL9kxKb5T+Y8W1YgZssHS+qEae67LgB3AjF74kTiuP/Xi338hz16cPR3/5RUcbkf7Bx+SdU
HpoleXrUX3A3EpUjy7cFNrLZAlqA2WzDt4Wyw7bI/B2hHYAy+Kt9/z378xMP2WympOf7GsK7Cg56
GoMwATu+dQn+A0JPdqGSFQTtqRqcpljJ3HUstkg8K3Z8j+kyP5tJrgtbFa+KqbBvAz+M2RlrnDbA
xLFvndR4QNrsqF6l/2ZHH7A5rboqCv++jVdOBLpJFQJk1UkWFBOL48GVeX07nFbY5O7iL+blx/vB
DT6PTODSB6x+q6HRqtVU7gj++QFW/7hAX+ZFWpKmeX5/N7i8GEzgrfHhByAwcF3/mUXCs1HM5yFo
sgVDHlPiF2GRTa1IZ3H8Z12utorL+aBY9IGdnQFHZsBPIZnR0qjh33ubcD98mAwHl5f3FVaXLGlv
UUzzi3gC7TpPFgu0k/Vmm33P1FfvA8HvhfW0B06UOxrlfwiQZGpBd7s8KRTGj1bogOnm7vHs6Hv4
Y1eD69Hwkk3v2Pn1LX3PjlhVF5YqpPRlIgkUvv/b7KiiOJZ/q6aevKHosQhXPABVZlJRmZOrdZh4
HnY0yHm84jHDQv/XgfJ6W+WJFycG+0iwU505kNDWxVzrVc/35i68FvuVaLRTaab8KGdH//iXv/Av
f+Ff/kK5v1A5WgpPhNzFsRRoRGAuQWka1Xa1AZWZJ45rH/VPe3UYgGHw8y0fMJvwxgOH8BqNah0Q
l04Mr/U3/kEGOfJjnuoJUQBnAqdKR5c8fAZf4YZb577/aIAUGgOPG9Nkw9e8CmrPXdZoVzvVOlOo
fxGhJ1z2WdZeAfvsCwzT/5m4rHnK6s1+s9vvtNj4csqa9UbnBxb6ftx/8RKjedJrVtv16un/adTu
h6PhYDI0f+51zW6bvdAX1A3nKv2jTrVbbWBVv8IgAO9NeK9LqOlHWdUhhd7W3DrK/BZI+BWYHfAQ
Wglart5lx1WBtYEIY0dgvm/G2Ru78L2Fs2ToMs3CmffNNBFsIgJsU7PRb/b67Q47v5dtQgRJz0BW
nnk+KO868Wxfg6B5PiMXAxPXYu2HG8N11k581ux0bzBxyTHZFmd1QuEvRuDyDVT5rEkpUcCfPUO5
QsDws0YXk59XTiyAVBSf+R4mCPIOjd8TEW6KSSHo9Jm/WBB9P7bPUCDBDV3EfTYeMqn7COSe54MX
JVQNDG6tHPEk1sKLI0WSo7thLFxnuYpTmrKG3AMdcVM8mbb252nCwg+BcNZYlRV0xrb8MHsPngKF
bzuLhWMlbrw5axCbSG9iPzRgSIpBRaMzTHahfq7sADDtrp2nRULYGgp652eXw6vBw2iKqciUagC2
DLLZZ9/THzQviX0j4k9C1QLFLVPn6mbtosAwNG7MIllJoE6oBSgyDNrICkYBRAjcfhEJllaa8RA8
+JWAARzkjYZwC9kes7kAn91yE/BV0XnfEVWkNfHXkHOBBLZpRnwBo74PkDBCkuAKCv7INn4SZm7E
ggHvnYVDJQDbQ5AodzPzUFwlqf4MSl4lse1j70kXsg8ujZQRZrl+JOzZEWB9Ix1PFECyl1Lt2JPD
2U8ogoBComgoSJ+hX4IZJyvIx5F/kQ9MU6Ww55XwIFmi49wlYrYIoIocJwCD8TVgxivfBkZoAAOq
NYdK5eSHcpak6HCYKKGA4VwC+oh85A3kX3AQLUBXKpJB+4wmPADh9hMHXbANC9RA5OlJ4AUG9PQz
iG4hwzforEJngLu0WftJBEMRyAawx4pwziYnCNAwbGwo0DJgU9BzNxLJ57QJt8l6jgPngg2ijWdN
efTI0HGBrkXwl8H97fXtxz6IFniGz47rYncCeZCJpevPwWJLSyMLq7B5EjMnBhLedyRn2GlSylAS
Yz/mbhVbjIUZqqA+a6Bg2GKeLFEqvrlesB9Zo0KEsMgIu5HA2Vwjpai6FnKR7hGptGMicEyALwm2
xPLXa+igKONhrru5OH4DCpR2GGrYGlSG9IZQVftBXKQASS7bJCOUxZBZ+mwNoCWoqmqL9JKhpiBA
ccQWob8G6dPpA29RL2OteOjGeLc2oP4uOETUc3fToeoX+N9KQMU8UDEi5KwDl2wpVU+VnFUv44C1
SrxHQ03oiAEDkCYvRnEgWIQyQ3VRAwUDC8HQhQRkeDTwsc/amBX9NgwLoIkifiGnbMmqdM4oiVbZ
J7DpQOgMjAToy8X4oQJZYH4/hy56dux4JcVJ9ltK1VA93NtfUR5Cqs0EqJGqMeDiOCeR+gxGwrzh
WPm04Tf8hfFtmspVF4riTrub3Trmvee2AzqY51PV4KoO1JcyL34ZIeErtr29G2kgNJLABqnL5RgM
peCyQjRE73SvGs2AgdTQLyuBhhvrBBM8krEcA+WLMxwPRUgdL+NIMNb4EnXNSe8wFYl9zHOSbqDC
Yz8uXSe2VpuSXNJCELLLl9T/SOghQvGIpZGB7l9gXCEbh4k1YIVBh0GQiBkgWwYZkdyUQRdWd/sQ
2qnoiEx4YfDygMU4hmp0Uobm/dvQuGj1JcjxbcPxCAE6oVuvIw69GQBFJOmdGOSWYC8jCjQU5jpA
OE1FM4UeADoARAaRyPwb2KFeEvTZqSQu/Rvy5MhKpbSAygnmUgUi0Q6+PnMsKEukNL6eO9ChEkX5
HnJg6KfDiYwWpsMFMUfJP3RNNnzZGb9pNMFYXTEls6eFVHCkHfDLssSVj5JKJVY1rwdmzVn1pKAT
R7eLBlsgoX3Z3tAz1DiQochUP9CcgQv0VNCighXxA1QrEEYRcxRvGCegBByZwNqA8Ic4GK/AW0KD
I4HKmCckqVwnw9TsShuwEpiOggQjiaWUbMEUPWSJBKclRFtseX5+LmOK68CoK8ep4QtH0yBfcHQE
+qoS/bQ2BALpimAa2We/4qMBLjVOW/3gb0iRvNhs4NO9PGqED4RCxxa6jUBWibjUaST/h3z2iMYo
bPYahi4HKqoGUK3qVCpVgJ4YutCoK2QT89L67Go0mPabP5xUOqcvjUrrpVVp/tD4wQZjIA3PcRwK
eAGlP+vV2RIkKpJv7c4HcqrFSyw8ZEiEE+ELMDj6hA+lSH8Hu7fMItGBhcjqJfodjJpoyXmtAd2P
00U50W3SZHFuwei6ysPY3AXJ52GeIKP26VsSutkLOIQg6kRazboXcZBBl3b+uM6TV6A8NFFH/N8i
Nbtv0ux+PZfBhQwZXJJNEOeNiTnWzdabPhmPqAZNnIlYMAjlmTfQeJoYqycG03CoKXKBGThFbdY7
9RY8fnsNvdiyur3evDufW6263eryRYtbrfbCttvzk3lnftI7WYgO/LFvoaTxClmELJQF+5HzkneA
HDQihdDApt2LhSunp5BK5YnFoje3rW5nXp8Lvugt2twW3UW9u+i1e6Jrt1v2wu41u1RetFr7OQ9l
fDEqttSRHQHIsf8oPOdr2jWQ8gVmOmAhJKOqXUjZcJqqNaoNQvjqBPKtWe1QkEBaPlpvpadjEMvx
p3EW1Dj7kckuQJWcbMCyrzHtf1ywZOadY8gISoORFCr4nwmWQWTgu1+v9+unM+9CTVXBq5MeN6Ky
76q1dA4rvoNXw1CTIcfDdSADg/lr5ysp9HcIRivsvJypmJjjxZtQZDGxYF2bO14N+NkhZPEirPfl
QB/DQA18Dz4q+3vxDdsJ35MHhek9+FKt35MDLMh70ANv+d42LO3s2U9iwwM+w7hVSEOlxo7/ThOF
1GTpaakN1dOepQbqSamZoDTbiSgRwySob4VE6JKXtVtI2n63/XXhPSIvvCQXLfaF26nPIYwSxVRr
6RQpyvlMsVSc3RZSAtsv8CwQig9pgoPzuiKK7RtymNI60LEKrFoVuUmDkp6gLGIhCfII+8zzC4kY
cbDONmILFaxroVfB9Y/hH3ikX+NiB4HfApPSmC8LFL6SE+kswd8ppNOIpCeI9VzYMBkwpM0uFCpH
KU1NCOVMT1eoctAucKRIC+y5/grjsqbhWNen9dnHu+mdjuQH5MlLjl1cnC0t7IMLcGU+Ts6Muyag
LsbXF5hlzUNrdYZhoya9xoknzsj9kf228HyYe0TURXeEcjn5aXQ9HZqfBp+H5vXkdnCb4mFLDPDZ
ZEctEg8DdTJVN7BRio9cBv7B8OZnaXHIAximlkbKlsXC8TD8K8nAtCnFpDluAVOR5BjcMjyuCkL/
zHiCEdsPYSSlJB+mMsYC4+VG4NMCZ1rhZ5w3Gq4PjjslOU9Qc3pcd9v4hew6QAOGHMuPXgzlAxvg
QJ816lWyTj8lHkYkgMQyoTgzJn6BStM2ijMFVYEig8alFNXA4LHEw8nfIolpIPtudCn7FAm5FSMM
gBWVP7u0ZGXiS61arYHNwd4fjyUuPv/889nyT3+ST/+Siv+/pOI78OJkCBsDyeD9pI7QCPKybCF4
5n12wjgBL+7SCYkPGzZJArlV5Md0yps7VDLKglv32DGMt1Xg/wc2BiYj9qujMwrhzKO1VJuVkMxp
lK8/ZnTUAxYP7cTgPwVtwEWgiAG3bQepQrMQhdYqIqR+7PmeAM93UIoQ8BCjbBoeesiKf+BhthqN
elcmDtPpXAZqNgH0V4xgFGF7gdKPBRQoIMOqTCfbBRTwdLRLCkVnYM+feWrH1QR0K94UOpAKn5AG
sE8gB7QwsINwI6PoN9zjuJC9C8eZ9HwDrrcmJDD5fnKwR+cblrpPM+96/NQtFaXLKW6W0EFqKLZx
6nEvlhirh5GeIRsmoKF8TX2XxmCr6NFWGHR/hfqtQksAFQZzaF5hqzjGdPxAJ6PCYOQsUJUUmdy6
xaAuXiRDTVBEbEG2xMYPz3nBx2VZ3iuaJ1MOrEv1+wqTHjA92SJ7lryohn7caGVvsQ8txw1Z2bvr
P2vv+BWY6JBk0XqkhaEl0HcbGiooGIjcooAt8H8Jtoat+SMIMS4MyAUzJvvcAnK0YjXi3jLBtZgh
RoMw9iElkt7YE602V0Atg02IMV52bH1gjdPTnkGTK8KdQtEe1HdJy3P4HzP/mD9JrWATMEE6Rvh0
fnGDZiYqkSiQKTJezhOZkBHNSj9zN6HXG469J99TgtUIfXqE1umDIqzKy6d6qOc9xV1QvPjABPrt
9aFQlQlzQHPhB4LI3KlPHagWSgmwWKgvRHjmm8gM/CBxYUJshvwZXqLYRGXQmweDhRkJ3B0AJh5M
XpBQm/6dPrbB4MRvwyMpkTvlJ7FvwqAMzDIXyoJ7PntK25o+K0y5VheZvznxVkMRCtr9BkLz0H+G
3gv2Y6jFKtNaoT2nkpJ4YfTw4WF6ZfRylLWzFjj1IOUXL3FtFa/dwguuy5N1MmnvpxxG9pSrENN9
mYdRcVHGpFGb8CbTy7uHaf6U49AepyTQcBXfsANs3zIxeHKgKN+CeaoJ7XkV5zAhKf+m7Ra7TiVn
UmfiCKQGFw0LK59KitpxtL8kQgYr8xpKKjFvIyjXFBRifQvjxYlN3zPxOIUvZV+Xc/EC7YNGroKt
ZqWjtImux1tdIHyo5QHhGrh5NPHGuamRDvF/LLWZh1plJgHOCqJiI1Zg7WlVryqXtqj1/7Hw4SGK
N644mx1ZYPPDPvvm6qqHa0RHP6qn/6gh2o/vzqAXmq4t76WBG7rOz5GGfHq10D0Z9EJTPd9PQNZa
Pr2pxJIMeomPYoMbbw7RODlJaeDTGwotzaAXmitGOYnLy7Te8unVMvdkgDKBobqJ0pQHnE4YL1H9
aKfCG7EiPwktsQcLnBywJnM1MhcQ1oHrWKDMCzeJVkVBV4MoTYkxrdqXnwiBAc8UnuXbBw0JzeVg
1H0DKpivPS3NIeaav5iuHPVpG7f6xl1xjluFaYz5Yq4owLdNhBBoixma9pCb+c6//XWiTAftKlYI
A9kJDmBkDXUvAqHbdqRZl58SKhnpCdojZcoNGADutuWnjpQSNxryU4c9cdmMBohY+p3uJjRpDTrP
2Wj2bmYeOk/mnMP8TRri8uZJz8ac0wZ6fSSoZ7DXe1YhrnAWJQ4URkMitilyvhKodyM/AQTuoZO6
jQ3Z78AcGDpdFE6TAndZvkb3L+prByWOXcmDuvpCDDlfMcGps/DjqagFchg0gZmu4I9RKRBDiqbc
6rQld7hrGHrXBFN2qO243I7SZtI2o9fRUpWsJVFYi3B4S0HMiJnhsINA2n3qcBf4ZRZZeyI/AQHD
vCZJCTiy262a3EzH+EILWrj8XXiB3Os4MNOJQLMjPyH5d7eKcSwTd3hu04zAMY/FOjAPSiSeHHjc
YygSrVlQFXeOqOhd7icnFdNMFTWVoOaN/MwQ4tfqRRb2dQzHc6oFSWxJhW2hvmYYWBXcsUrmFlMp
6KK/zDxQeYe2y+WiNfw4vphkDzMPVzsCSzLL9OSWQU2BdfAOL1GiwdXALcUmTO6ttMMyyScE5cwu
rRLYOot9lJGOaJr9BushsSkQAzMUYT1uk4OZKE5JsgdWmE9os1BcOaTvh/tR6USVANee3HCnNOKk
2m5U68bl8PPMGyypbq2ZdwVjbhLinJ72X64ub4nvv2DKBUyjYF5OVuTWT8NO6uXjZGLciqUfO2o9
FhOvL2+zR4wCpZQew3k7BYzAMIl0pkdQcGW/Zi+309FNiorPX87Tt8n4dvjxLnubjLI8k4mM1GH6
dDQxJvfj9HWsjhYQC2XQaKHiRFEaM8JPoPJJab9cbjZgyoLrYrS23WhXW9W6LFSb9o99l4eQVmsA
GCaXf8Wzjxocd0PQfifc5ZF+12j4Kw0vHN25kQ9fbAooX31P4GI3x7FNp4pBmSqMGbtIAEz9FOwt
tZEzRcNA4hoj+Lw24b45Bqj/vpAFVj/12k0XJCtWkYlWo3rS7Z5oj9vIvrfMsTvVZqvV0h4VdpR4
oQOzLdAUR44Kp/Vqp9dSyNlLjo5ntt6IfZAPRU3FeaNYqqCkeGHQrSEPKax6nuDYbzNXJWlaKTfR
4NM1RVmAaY4t1Q/D7zJ2uB18vRdP2ZhFm0l6XRjL53Pe6fasTqdx2mjzVqfb6gqrXe8tGuJEdHFH
S5N9+76+k7XT51xyJQYjR8W3bVxwqFUAqNyuAX4c4NcVDKXlYbMlfX68LA0LQ7Im3XPF4ONmFcwV
xX7laawPgHl9xe4pzF1GBoAXcuN5GXh8+7E0HToSQQWt7VbRcfhyfjMuzfLz+U1p+nu6Y2lXfwvE
0lTTGtwtuOWVAs46UF+lbP0I1XvKq92lU7w4q+fRKv0uzfgJAFiYjP9Sz67tJvxrw78Oi1a8gR9N
mJbgV6eLX60evXUaTQbjnVjb4H2nT926ekJc+dQCv/R55YRu4Psu2KClCCFDpaUeu/Xs8bSZPQJC
O0do5whQtCcWYaK+sJglWmv8MCjo7jOOPjnohRVa6eecLbynBrzhF1ffMCOhV/j+zec8ZisOgiwr
Jx+pcvKRKkePwI3ssdPNEKjKWbZ2nq2dZ2vn2dp5tk6erZNn6+TZOnm2DsMOxT126XdpxxLgqTj+
0B7ifHFm5pWu5GQkcqiKIAi5SIBesTNfzxcwsnyagqLLSHLm9cS4nOJmzka+sKNyFavVqjb1arEs
iFVcypgdRbTuQqdcHrn3m8PIfZP2SR14oXUSsLtHFRQ4a8VoORAJzxM8+gH2BLddrwT7ePvARrif
PmRy47jLxvJA/cixoHyRVRJtT5FXx7/xgIOyiA8spDEhOsg8iXPse7imkaz5B4YuPLn8LPf9vMNZ
nvQFhlPpSbzdwqTMTX3fV+ZtGXrapeZWlxZiECkyeqgmbtTFuUUhYJBioHNlZssOr5RNyPkixNux
8SzvUxbUJ5P2v48plP9f6MfBWI/NqL1QYH/2J5gwfHgLjlbYOwJAWR43XXdDsEhilLj8UUPEL+gi
2VOH+B0l8ASOVCxokYNb8aE+hYxkHPOnUrGVIFNpVRmG7n1WO+jqDgIH/GvpjtabjSYOmMqegM5Z
TrBS8Si8ocHAsYIMduj8Bt6YcCklfvYXDoxRPLQWeHaPUNG2u/6jc3qiIZ826dBfGLhJxJ7BRLC5
6z9jZkM6CMyGTs/wacgCbIxog2XhGTa0yFmuOQutJsPFVmgc5NNrjvN5We+5xazFnFlxyIQ1Zx6+
eD584D9pl9g7NVIuD3N36Yfgsa6jw9NshU41OowJuLTBjEwWPl2Xb+Vw8QwGbWtI3VfNxPzBW6tB
RCRXxlgEsAFKHjmeDDvV0UfmB+Eqt570Ll4TQ6pyHZXiOWCE0llnPr8voAV5TcqQUnc4jRLt6bUi
ctoJrVa9m37vIj2/mV56F8sb0THK8ioyxaJTPj94FGWVu2GylwJukU+vZMBjU54HvbZj0xTcV+Et
35ORTdsMsDK7wREloNrjPhv1h4uyfrYQ6EepuZh5dOBWxSK0ZHJocGeMAuFpOg2cbsmS4WiWBuva
9dMuTgn5DqTVPOn2FEhbqWw1Oi15dusC2IiqAeOSdhY3i+TkUHVctohEgRMYTdJhrcazzVrpaeec
rRUKD5t080mFJ/HKlDgmwU2Po4Ka6XnzEgw6MZghgKqDQcp2PeUlOXpPF+sLhhd9psiMlBDW0wQQ
NwHF2yox4LSbWMdLk7YxVaCIvBlceQF7sRek2L9Tquk/mpJ+OVj4i4Nw3LWgln1ex1s4wrVN8Hj4
67ghmrcDSLiezmkRLgqgD8RBZDpVppbiCng6t00rP39RwnXg1D4IMGkfSOPPQZScNQfRgCv74NsM
2Yen8UKhQA4y1EAfbwVwRDp8eWDhDgBB3mzxYiZRJpJzEsKtxAhHqmJeaStw5VTEaVpSmhpE5p7k
cnxaSoUkDwPJbhkkiLYIKcZBHjwRqJYUcy3TEHyPljALcNziYy5ETOMAriCZcgOoqsFrWEGkY2Qt
IhSLvJ8SQqVoRUqFsgqEstxvRM/5/FoGra/egPouungixg91RA558fa5EvZkoCJLokcnCEozpJAM
3/KDDQ7vdDTFxIOgdikE/ApcsdCgZEEUG8zY980IynIzMPkVZpRYeEp4K3XBHRePgRVSHVJBTZsK
3gnKZzlR6aqaOZUtQO4RleCIF7Uxga4UUYnZbgU90XaitPwCLgycjm27woThI2WKjpCVsAiFUDZm
u5xdUJYritd7KrcDAe/BFNgHvmXSMdeSdHUEXgNYezJY+zLgWndpjhSwm4XaZ5Wm7iDvacC++u+p
/r7a76v83rqXVr285gImnp6dBDvo+9Ihwz787WRyc0wMiGR2w0sybSuBzp0DWcHZ3DiHaNO6/H4w
5JXbYvaCD1VseRBuC8vJjVYJwsL1+aH8fjJ3xQG4WhIth27A+z3Et/UrlA9jIBSc5XVwgPPZ3rA9
7HP9+X6o8JL1AdriAN+WwgefTC6klWPQpU4F8NzxeLjZL5Fb8G2Z3AKXSeUWyq5cbiHsSuYuwuEq
Ll/BKJPPLZRdCd2msSuj2xjbUroF35HTHV6uX6X/Gk65tG73yK68brN0W2K34Dsyu12COMjLUrnd
wtElF8+mZQN16uEWbG0BA12VLTiAwMl39FfKYs8LCCKrE77LWQ9ewqMlyluiihnt0A+KKSGOlHLX
pEpJr0bTkwpzcJWo7mjB6JqvF1twq3TER0fz4Nb5XrMULe9qfNUESGLjjUaoYuDxF5q5Mw/DVOgj
3HNpJ5mAEU25nb2YmDpe+dRe8kVtqYtc/iQKvADPSE1ltpNVj28n49Y12giRn9HQoLqXlSVCn4h4
l056+/A2hGSxwC1wILw9YQHwRuS2/YIHvxcryKOwdBQ6e9iz5I93l9BJmYv7ITsei9Bl+c2q7F4s
ExfMy/AljatFH8qX7TF7uv9CC/H1qq0uhvTaRv3UaHbfFxzGulWzBbl8W2lD7uHWHhUuEE6o6G3c
/InaupKHiPC7T6fYBqG1whqV8Qix2PDnqR6Ep2tIFAjDYoVV0wYu5k4+37Jwe9MI73UbvN5qd9sn
vCt6dTHndr3XaYh6o8dtIZqnLQAt5hjLRNoG7Zelc3K4+oJVLO4xm74B56/X41dxll+dQL9DrQCc
A7C5DU1Xjtkx6HiMs71AWG5t/rX5YebdBYL2YEW7RwhzfFzRw+2eUYQLeGl/MFlVHy/R4mENOsdU
nVNhfohDMsiLhTGJIMbzjJeg7xs2WfGF81hVJPDHKzYMdcL5Kk89fgQDgeHUc8Gf1Ir0DTAiidi5
L8KlCDErnj3B6SAezgMq2a1qcmm1eOyuWa+3DPg4xT1g7C84Y/9KF0O9Q7qhqmprZjoW7NmmjIh4
aIduIysseSgQ3RNs0kaSApi2ODsvcofUlix27GbdFicn3d7J/MQ+7TbmjU67U++dtBa82Zqfim6b
N1pdLjcwpVdn4PPnoh40GpJ+et1O8W1f7P+dN/LQBWd4aUT2sMeeqXsp6JIc+bhnD9BkPFJfpZSy
A9iRPJsNYz5CKuwOhozwOpb3TlXAQpLJeRJ50kSIR8TVUgL3bi5jX/QySegCalzqy46sDejoVZ5n
EIZ8s/V6p+6tPuf2ldpzegGqNHxBbaCbxQByQ3eSbqVf4MW53jKnd6G2K8vtbnl6dspcS/Lxdg6N
2HAdxBocT4ZHdCFRIa1A9iN4fvnbtSfvBdBTnnAb3kAdmdcKS3Fy3JHwlvFKQxmhsdfg/tKxNPCN
ul0sx7j178Wzo3MbevVucY6XEkRaTkq9R49FT4ReBLf+WUsac7wGUROKrSyZkGx1apa+0z0apLyf
MoSSDstgezPtMjUD0VbKkvRpKISeXMQC9QAPUGsySPklTm02uDIs7BFYOEpEYcEdz9lLKtP0+iJs
YhG9fhI8oIcbx8uf+Uv2LLNOoAZ0pyykjEMH1+w3PyUikSn50yTmeKUjPE3FOtCLfsCtR1td+oBx
NwqokrnOIGRj5BVvZD5+GuFjqQlJYWvfTlyh+wjqZrgURd+42qr2qo263Hf19rFE1ai6c9xx30aE
9GI3Kmbj8TXtrpK1KPXv8PhH7LPsXMfh0x7vOmCNO73iKs+w5aGhDDBXxWUnpWVyet7iwIlmiQiD
I3ji4omXUdE2dGbF4lFntRkL7/Ew5aW0kZ67uMyvH0rt1uXnzDt8sAbPjIdC3gJVTU9u8zMYZRcV
sCbqia4oOYtCq4IR97MKTR1hYnH2Pmx10gO0xIsPSUV2jx1dXZC+7BlA1RV36SOYBLoNFkfMV/Ym
0ZV4mA+vMcNvkLxfBjej8p2OUns+73jYaaYC4QbuuH+P9GEVqnhNpC1UqEDvZx1ajIHoCOneNrxn
G38wZR8CLhLKDmjSRxEqLzTGOVNdfmJD6HIM8OGdoMCU/PKRbZdqcbpoNDn8O2k3G8356aLZ7HVP
2idN0ea8cyL4vD2ft60FulRItThzoXMQwNivRQhdN0km6StdEKOOUJR1l7qB4wveBCTn+IVrQfq1
WoYjR6fskg7HW+AVCRX5Bhrm0mkMnI1i3GX7wEYPK4pDS+lJjrcLAJWW7U4szHEKZ4jK0fITlPkp
SR311TOIhatupKyT86rE/hY0Gl+H3pMT+h76RuSCq7NYSEu1Yzq8vzHH93f4+07Kn3SFORXh2qFz
JginYzPQ9jVuvaMTw9AZn4Yj2vtCZ9bntCl9ejO+vL6nxCeYhC1818Zj7r1mreW1o/jFbnS9k8VL
c/PU+t0Mn5/lJHzp1aY13HKIBY+TOXi5pvTBzXvhqb0AtSB0nuh4zTqoASOrdH6n6nLwZ1d2dRN+
/in+2QqjpCbzFBtmfh7eT67v6PRSq92qnsBcc3Q5/nL52s1EdBXI/YXalEIkJ8MJkjKvKfPV8OJi
WD8/NzrtbstoNy4GRq/ZaRu99mnjqts9HVyhTX+YDIktsgw8aPTJHDxMP9GPSb2heYP75PSnxfql
MaiNaCGS7s83zYsrE0mb0+HPU3N4e3F3eX37kTTvpXHV6ddf6vCvDa0dD6afsrGX9stht/XplR6y
t4ie8BNyvYVBo4EsMojN8/uquofj5/GFSTePycrUZQpU9fP1xdC8HdwMlZ37dCcfC2WgdI0+j9TA
Orr7mGZIweqGlvRk4R7RpvKG97/OjnRZmB39rUzOi8gKaVvocyQSf4WlaYBGhXQhxXi/OuSU9itG
Sv3dulHOmVRLFFmlKDmuVJm00INCkWci/VF5dgrOdUlhvE2dcioo/SprKhtaH+la9jZe7VG0jOQe
lVPEt7VO4wLoX1qDd6mgRuLdrEfNVFkKypljZGqaNaC+DdZ1NsXScVCBy+pVVBbQZoXUKNRQqvbe
HsQw3mQ4ulII1ZIfqiqUc3F/PZ7qVX1jjqvr0fAdubA3zen94HYyGkyHl2/MdXl38XAzvJ2a93d3
0xKNuB/+9DCcTM3p9c0QeuVukCJlPwLcrjZOuqf78uxg64h4XUBq+XCmPPOO8Rp7xn6tH6g8BVgL
RCytG4e3n99oW3PMfYZVYuyzqir/f9ekSjL/L+zpLiv2GFOJ+B5LKnNsmVGtvH/WhkoSZQZU9cUf
Zj0lvXeaTtXsf9puqvzv4/JeiynB5eYyh+2xlRLhgKFMhb9oJVWVSk2kdIDUubat6wId/A0gIVjk
L+JnmOX/gD+dRT+kFYr85Bz+mARMMmp+KH9KCywCpOSn6VBBo/TCQa0wxiP5O7X007/zTQb/GPpJ
gL+8Zhd+/Yt+ZSgtFSdIKg0Pa/QZGwG/bifDnTsPt075qUwrPxDqJ43i7CdhkkgsEreCG2Vj9uV6
+gnvWxvc/sK+DO7BRk9/+YGpG6wZTLokIdoChz8fxMEYevEGGgpzp+H9xSfIMDi/Hl1Pf8Ef7ri6
nt6CfrGru3s2YOPB/fT64mE0uGfjh/vx3WRIxwivF8Rh27HpIIBaXaUfBgs2OgtdyUJckcLDn4Di
Advp3hVaQeJzrGSO6XjLCgMFw8P/lu/F3IpTGn/GW1I9EUMFjv7xfwGPIlRR
===END CRASH DUMP===

**Comment by MagicDroidX** [comment]
i said read the log plz not give me the log plz

**Comment by tsuhakkun** [comment]
sorry, im not good with english, im Japanese, help me

**Comment by MagicDroidX** [comment]
Obviously, the port is already in use.
So you should find out which process is using the port and close it.Then it should be able to open the server. Or you can just change the port in server.properties.

**Comment by tsuhakkun** [comment]
okay, i will try, thx

**Comment by tsuhakkun** [comment]
Done! THANKS A LOT どうもありがとうございます
