### ISSUE TITLE
C mode Issues!

### ISSUE THREAD

**Issue by UltimateZeal** [PocketMine/PocketMine-MP#3543]
So made my server and ect. and i was done with the plugin but i don't get why when i press a block in the inventory in c-mode it doesn't appear in my inventory slots so i need help! I'm not in adventure mode or anything! 

Please need your guys help

**Comment by TahaTheHacker** [comment]
use this pocketmine bleeding that fixes it
http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/29/
and close your issue.

**Comment by UltimateZeal** [comment]
THANK YOU @TahaTheHacker Really Thank You very Much!
