### ISSUE TITLE
PocketMine and Multicraft ! 

### ISSUE THREAD

**Issue by Jackis16** [PocketMine/PocketMine-MP#3545]
There is an issue with Pocket Mine and Multicraft, all I get it this error

30.09 18:42:24 [Multicraft] Server shut down
30.09 18:42:24 [Server] INFO thrown in phar:///jar/pocketmine.phar/src/pocketmine/Server__64bit.php on line 1546
30.09 18:42:24 [Server] INFO #4 {main}
30.09 18:42:24 [Server] INFO #3 /jar/pocketmine.phar(1): require('phar:///home/mi...')
30.09 18:42:24 [Server] INFO #2 phar:///jar/pocketmine.phar/src/pocketmine/PocketMine.php(464): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'phar:///home/mi...', '"/home/minecraf...', '"/home/minecraf...')
30.09 18:42:24 [Server] INFO #1 phar:///jar/pocketmine.phar/src/pocketmine/Server__64bit.php(1546): mkdir('"/home/minecraf...', 511)
30.09 18:42:24 [Server] INFO #0 [internal function]: ExceptionHandler::handler(2, 'mkdir(): No suc...', 'phar:///home/mi...', 1546, Array)
30.09 18:42:24 [Server] INFO Stack trace:
30.09 18:42:24 [Server] INFO Fatal error: Uncaught exception 'RuntimeException' with message 'mkdir(): No such file or directory' in phar:///jar/pocketmine.phar/src/pocketmine/Server__64bit.php:1546
30.09 18:42:24 [Server] INFO Failed to run command '/pocketmine/bin/php5/bin/php': No such file or directory
30.09 18:42:24 [Multicraft] Loaded config for "Other: PocketMine-MP"

**Comment by SavionLegendZzz** [comment]
1. this isnt a forum 2. pocketmine dosent handle MultiCraft

**Comment by Jackis16** [comment]
On Multicraft, it says pocketmine..

**Comment by SavionLegendZzz** [comment]
*sighs* forget it just dont post here. tell your server host
