### ISSUE TITLE
Installer.php sleep(4) exception

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#3550]
![1241242131](https://cloud.githubusercontent.com/assets/8337568/10239942/5e907b4e-6910-11e5-8f52-8eae184e9929.png)

I downloaded bleeding version number 37,
(I applied php7RC3, using php7 build script to compile)
and i tried setup to using wizard, and crashed
so i can do only manually modified pocketmine.yml.

I think it might be php7 doesn't support sleep() method..'~'

**Comment by Intyre** [comment]
Don't use PocketMine with php7 yet. It is only for testing.
