### ISSUE TITLE
last git version from branch mcpe-0.12. user can't craft Furnace 

### ISSUE THREAD

**Issue by wrewolf** [PocketMine/PocketMine-MP#3552]
User can't craft Furnace not showing in craft menu in user or Crafting_Table

**Comment by Intyre** [comment]
Most crafting recipes are fixed by a7413dac92c21050539539ce878a1efc28bbf44a. You can get the phar from [Jenkins](http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/). Make sure to get the phar with ``0.12-items`` in the name.

**Comment by wrewolf** [comment]
@Intyre locally i merge 0.12-items into mcpe-0.12, but why fixies megre on github?
