### ISSUE TITLE
Max -1 Lower then 0

### ISSUE THREAD

**Issue by CailanRocks** [PocketMine/PocketMine-MP#3553]
-----CONSOLE------

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 23:39:36 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 23:39:36 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 23:39:36 [INFO] Loading pocketmine.yml...
[Server] 23:39:36 [INFO] Loading server properties...
[Server] 23:39:37 [INFO] Starting Minecraft PE server on 0.0.0.0:12345
[Server] 23:39:37 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 23:39:37 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 23:39:45 [INFO] ----- PocketMine-MP Auto Updater -----
[Server] 23:39:45 [INFO] It appears you're running a Stable build, when you've specified that you prefer to run Beta builds.
[Server] 23:39:45 [INFO] If you would like to be kept informed about new Stable builds only, it is recommended that you change 'preferred-channel' in your pocketmine.yml to 'stable'.
[Server] 23:39:45 [INFO] ----- -------------------------- -----
[Server] 23:39:46 [INFO] Preparing level "world"
[Server] 23:39:48 [WARNING] RuntimeException: "mt_rand(): max(-1) is smaller than min(0)" (E_WARNING) in "/src/pocketmine/scheduler/AsyncPool" at line 61
[Server] 23:39:48 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 23:39:48 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Fri_Oct_2-23.39.48-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 23:39:53 [INFO] Unloading level "world"

-----FILE-----
PocketMine-MP Crash Dump Fri Oct 2 23:39:48 UTC 2015

Error: mt_rand(): max(-1) is smaller than min(0)
File: /src/pocketmine/scheduler/AsyncPool
Line: 61
Type: warning

Code:
[52] 	}
[53] 
[54] 	public function submitTask(AsyncTask $task){
[55] 		if(isset($this->tasks[$task->getTaskId()]) or $task->isGarbage()){
[56] 			return;
[57] 		}
[58] 
[59] 		$this->tasks[$task->getTaskId()] = $task;
[60] 
[61] 		$selectedWorker = \mt_rand(0, $this->size - 1);
[62] 		$selectedTasks = $this->workerUsage[$selectedWorker];
[63] 		for($i = 0; $i < $this->size; ++$i){
[64] 			if($this->workerUsage[$i] < $selectedTasks){
[65] 				$selectedWorker = $i;
[66] 				$selectedTasks = $this->workerUsage[$i];
[67] 			}
[68] 		}
[69] 
[70] 		$this->workers[$selectedWorker]->stack($task);
[71] 		$this->workerUsage[$selectedWorker]++;

Backtrace:
#0 /src/pocketmine/scheduler/AsyncPool(61): mt_rand(integer 0, integer -1)
#1 /src/pocketmine/scheduler/ServerScheduler(78): pocketmine\scheduler\AsyncPool->submitTask(pocketmine\scheduler\SendUsageTask object)
#2 /src/pocketmine/Server(2189): pocketmine\scheduler\ServerScheduler->scheduleAsyncTask(pocketmine\scheduler\SendUsageTask object)
#3 /src/pocketmine/Server(1961): pocketmine\Server->sendUsage()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#6 (1): require(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.20-g42a90fd-dirty #1 SMP PREEMPT Tue May 5 15:23:39 CST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWmtv20a6/itz5AArb0VZ1M2yclycwOvsBkgan9pBPkRBMCKH0tS8lTO0rBb57/u87wwp2rG7
RXc/7IcaQUzOzHu/D/1rz+pM9ZbhdDpZjM/CxWLQS6Wxl1VVVL3lrz27L7Hd28kq1/mmN+hlyhi5
obXMfqlkHvePlyKT9/0gPBbaCJPJNFWVsFuZi0zn/dExoJI6TV/rlMDKrayWJycnxhYVEJ2orE6l
VfHJ6OSqiG6Vfadz1XkM3l0NCebEVNFJycsZnTDRVsU1SJ28Mvs8uiqKFOdKIuYI/Q4AHE6x1VvO
w0HPVjLC46fe0Uj8Dtj+PCTJvRJ0btUGYo8GonmEQoD/KPwNZNequlPVdfPeP10A5eHkatUeXa1a
wsH3pl5n2t5Ic9t/5vC1yuMPZCc6JIr1TyqyzM34G24cD/1xuDh7nvgjRsGCf2Su/hAnk+c4Cc9Y
s118bgdUG2R9RjF9FsXpaPIcCisr68Bn34AfvK4/nY6fwfDlS1TkxlZ1ZB8IfVFkpbR6naoLhJB5
W8gYXuAkHjzAVFudmtXqndT522Kz6ZwCWoSZ+MMx0mL4F6C/91yZ1hudmxPW11z0yTCV+rnWler/
u7w+q3sK4+Pe56+DnvpPp6E/khnAh1NDb5nI1KhBLypiRVzNxkC2sl9xeDbBI/2e8lJZr1MdiaTO
I6uLXHQito0Y8cLi/+NfCWrGUCurk742Rtn+C7vVJvieTphPfDD4fqMYwxvI+vlYFJXw69r8XVZr
jgqHbe6xrWylbF3lL2nx1C8ytwvP7Zlf/FfkxLkjRpjmIwc8Dxtgo1J4r4o/FtUtdH4uVqvGKsiH
HrfRvygRiPCYcYwfwxIpw2T49I5Rcax/eoT/MyOYeARJUfVfaACOXgr8/t8uuZfiu+9eaNbJfNrq
BDp+ioj+TMAP2HGQsxbyKVFfaGZn/tSh35JJOzFOWziyy3zRMdL8zOn5dPTQSA6N+UYtnNui275z
K8J+Gj4F+bRSv/vuZe/rn0XwzyL4ZxH8byqCg95G5aqSKdUbaN6gmiCow+F0GIKdda3TuLc8W4xQ
pKrCFhFK13KMN1lqPheGwxEObrTF6+h3/gCgkrepXhPM8JQx1LmkSaH3Vuf1vUiLSKbbwlgxGYaj
4XgUbKZjeTZK4iDWld0LhPz1uytx9ePl5burG3FTK/FO7sVMhLPleLKcnImL6xsxHoUzIavs7pQq
LrXvy95sOB+O8fYL/ByvY7yO3OaXwjQMYIFfkHaqQse9tkhj8RO0VsoK7FoozL0b9tshdFSqympF
sEdX7Zu4KPJEbwQ1CKtqlR+9rrR4H1kxFszscjoXH24umF/ad+gCUsk5WSuqZGKX4upSuADpnCmL
yp6H48mUATeAyNA+nIf0hoYlKFO5B5vn4xEDlXKXB2RKxZ3DeTin5d1WW5VqY8+LJKEFlUvEWPBz
rar9o7UKkdksxcpElS4Z01VRlcIWIlb5nokXNj7/qNKoyJT4P8cG7VOtEI75/+nIQS3YeV5UaKwY
GmJU+yDVSMIQb/GOFml0DOoyhus3HMg8L9AFKS9nIKOtVncqU7k1zZk7rXZwG2QlHDwPWRFo34pd
kKR6s22FdsqRuQYPAM4Pa1mxbhYQVXFUVC0D5V3pd2KdJDqqU7t32neRhYgN0HFZhLE5ZyHAXupM
i4KZxoc1o1TcOcIa+dvl61cf3t7QKil+WCLrASw+/yv/QJDaFoGRd8pzwaYMurZECwP9tJ7hV8nl
28Qw3GcpeaygdCkidtYavFNvST4rgEM8SC/wYXGzVUaJRjjEmYJxlShyODwaYysiso4Va4V6HaV1
rGI8iG9ihXBdk5cUCSF4jNPIRA1EgZ3KEEqxrpS8FfuirjwuoRMB2XSimQLMU8G90z0h/kHtWnQn
sUokDGTErsj/YoUsSyUrQSrMICxSTroH+85FWe7dVuWiLjeVjIFguMrJXx2y5SoXRzfbSkHbWAIX
qcw3NdKzoAaeVeZ922i8c0rTv7BSCfRiqyIvxUNAMLC1tjRI+Cof7vStLlWs5bCoNif0dvIWxv1S
JF/eXL//Mp+cBeMvBAc1toiWYtVT+WbVI0Ift4p0R7FHtV1ASl+ZYCY0VoZLidtmbTKniiYACMYm
jdWdjpTAsBOnbOQMiJ1fHUjy9IJ1s61tXFDUuCGKmHFpS0RpYVTs2HpFESjIUbnCuewq7rQU/09Z
B0c4+wR+Zwlea0J/dL0FnCQvNQW48VScqaRHJGoDJ4xVCUdg6V5dvcFJuy1i0tNhIwBbazB1QH/J
aa7BA4kFhbuAu8IjiNX1Xng/wnGfFNvdgxqOPmoousjhUjKOUdGN8zxiE752C3akqStOVTRSrhXp
A0pH6ZcpmWOj73D2TqYobn1PEiXiGMgdPSRjRfk/gDWpxVlilyj/UGdrangScZgGfVs/pP0PMAL7
ZyMkndpWBVIpXIKmioHg3CR8DoPLDqCGDFoz1CKwWnZqTWtZnSNy6AjjvmaXgTwIrqq4Ry5FZdmT
OOzqecsaadWx8yahCKUjFIlo7u1foDlb7V05oVLFXvgIVvQhAewsxqQRliHwUi4ZE0WrqyMcq39P
izUUa4rECrcsuLxQTsrURq73FgyJa8fKiIlrQ+Z1kQ6ZdpoZY2ULKiC+TPklw3pJ0LjhQSCJ54wq
QY5oKDrzQ5ianXZTQI7ijm8SNHnmhpl0dW8pRitOFZyVLVKNjP/L2c/A6W8wT8Xz32IeDXDJ9H2q
avnx2NBZ1BXVSGQZzw3RbFgKR+Op4+pKVbrgckSxaIhgxAnZc9fGWwhSSDUx+RifCBAPykUap/Ei
RwJDhEJvlB2eU6tTJ6pzyhmeYt0dW3HBJRyIvkMku3REFN5TCqEKx8eH3x4msV0eiqHCUkVUCA2r
hXh1OnawrQDQpCrNQczJyMtpjp9kyEs9cVJv3IVQgHEgdY0kRdiTWmV3IlY8jPAwiN1M5jWX3C4X
aEdq+MLxoMkJj5zBe4PLq0nS5Ibs4GVD8d7VO36DR2yLOo1bRjQyyC4XB9bJb0XJnEPAOeYTllEc
veZI+CY3sq846FaopCqyJsUSrN8PulmpY1MI4U332BWe8J8OHDX00bbOb43T91v2ekqIvEicpRiJ
SRrhGuIBh2eFBsS4QwH1ANTLHHARqsbMPlDO5p7PvxUO7LH5qAhQp+TAuhgcFX/sPyAzF6IgQmOv
nNTeFxpCtNFW799EtcpzZckWbesG10hdJVxLi8mBGhFJXa6hKybhsxIHoGtM/a5LRmvV1kRON0fd
9NXsUOBXe0u4ByIIO85MtY/JBrZhBWllNndZ5VBreRqgQhe7dOcN6GCx6Hkain9gmOFLw4walour
DwPAgoM18s9Ox3brsjbHd4s+YPRLceobg0PLYFgxnaND8SpGPG1lmpygyXddTKzgZ54QSDr/K/Ju
QLbVuYOr0ydd3lPwURsk04ELbCL8UefoIiEW3Eaxa1Ot/3CVXzWdwqFnpyaIgHbI9Stq2PMy8K/d
nowG1nW9Wfqm43sRUrPhKwt1lbzddJSG89hWNZ3mypsCZeTQJxq63ZG2hsOcbCKnWuS12HSINtPd
g7lBNU0k8Q1J3MTER717kbhs8AhKtOxhHiRwIEuRYWvj5wkIRI5OfVoOl4OTclKSD/Ajc9JEZjvk
eST/hhuOUTbd0Q/vby6XgrMu/kU1hqscwxUj0lmZcgfL7HnKLXutiV89sFaEOQKZxMvKXsQlCZyQ
11jynPHIlxBKZa4ykRvRsEvrvhz5qH+43OQw1wtfU7iSgGtpVIdYP0SgPEFlIMbYCJ/aUDYaHnPQ
GtXlgt3hhjDTaOUvXIRCYnL0qPQ7S/IQe5huKRHwFETdE6UDme7k3jjcHk/Hjx7kb3ajV1lR590C
YHzP1jBB7BM2GhnokgWPSzF9HlRWWI0d7w7Hw6ojwrPxk9DsXblyc+RaOWxrlVAm4jsUylhkhhar
u1nppD6X+a7lHYou9XeaxmVF41e591cDvha1DQ0nikQay1plvfg0ltQpHysMXDWgENWRKyU8glU0
j8MxgLZR1U8FTUIuNozMyFcyzpVUYFr5HxmDFNoY4528F/KxXjADRVwfDv7w0BbspD/KWNemA+bt
IEXn3syBer+j8+hWKCfRFZa/FTswiFFbSUeEL4MOVdAxfhjsGt6H3zLv899Oap7RMY/XytvXw3PY
83pAX8SWYvGHsJVF6S60STfumUrTI8SrnGMygPaIaXdRF7AfGdIkqTKjzwZ05eJXQ58e6IZsKVxz
15gUGsrrEs2O6/icQ3LycI2GxwUspwTlCRLSGb3uJBFqF3lNZmsNz3dH/OWcm9GXLhnRdUIlzVa4
VVdjvZM47/WdfJvcyK8DuuB5uNKWkwer5bbUeVIc3IDu0JeO5LBz34dGiPnLi3yfUZvPEWKgX9My
SnOL3xaHbWYYviaF3GxQffzlQHvtQj0ifeW7fVoaxw+hM0/xQ/pyrswmfgwNn3C7S2eAKg98cT50
gLxalJ0Lowu6M+RLLJUWJVWrAd4hAd3Q2aYVQ2eSoFNWUDbqU051ng750lqTdRCPHSTCfy/p9BA1
Gk5jXYFrEp7HRhZy2w1+80gpu93uKZWkGuXGWeXyXlK9dS/UsAC/Z2LZcMNbcHaalJfiEz0GKDID
Hp0/E0aXBZs2pHvbykI084Ib2po7bJ7Gnrq85eGWq5jhjoHEztBIaDDqS3yHdabKDPCToCtvCl0u
SQdqS/H67aub5fjl6WB2dh8OJveTwfhl+DJGJXZZq28rhRdkmPPFSGzg38a9TWfHfLmt7q3KSSGG
Pm1doA51vv2QC3VeUQ427V9flBEd9S/m51RbNXHfqQIYnz4cuQ9XY/5stI7Q12wPf7ohU0SOrA4L
7k9Lmre6StuXRKdwc0btv6Iltmx3N9nheYvo5a9tdOgn4z/RjfkTXbZ2d7ntYfSE+9IeJLCSGIo7
4l5fvWWq9FxG6OUOsHsIzJ/F/JOYDYk7klwE9HlqPJqNJnh88QZ2SyanEyVncTybTRan83A6msvF
aDyW0/VCTk6n03CxHk9HSrwApastqYXU5ggXRt8flO6HdX8gJEF/VImfNLHK9BZqlkQSneoUZEfJ
6Wl0uljMZzOQnpyNJ2oyWp+dnsUx0zPbrDio0HBgmYeSaqd8HLbFrcpRZ6p25aOSt8gITlHDGVb2
kj+ShMOQD/yiS/c2Hk57X7/+E5LxUzY=
===END CRASH DUMP===

**Comment by PEMapModder** [comment]
You are using an outdated version of PocketMine. Please only report issues in the development build.
