### ISSUE TITLE
Ground bug in spectator mode

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PocketMine/PocketMine-MP#3554]
If a player is put into spectator mode, the fly buttons become glitchy and the player can fly below he ground (player does not fall unless center left button is held)
![2015-10-03 01 12 30](https://cloud.githubusercontent.com/assets/7192775/10260858/54e6d5c4-6934-11e5-8667-b956076d6822.png)

**Comment by Subtleoliver** [comment]
You are supposed to be able to fly under the ground in spectator mode. The fly problem is probably cause of that oPE doesn't support actually have a spectator mode

**Comment by PEMapModder** [comment]
I believe this is a client issue, nothing to do with PocketMine.
Also, clients are expected to have noclip enabled in spectator mode.
