### ISSUE TITLE
Installation script not working on newer Raspberry pi(s) (+fix)

### ISSUE THREAD

**Issue by chtronche** [PocketMine/PocketMine-MP#3556]
This boils down to the detection being made with 
grep -q BCM2708 /proc/cpuinfo
(approx line 300 in the script), while newer RPIs report BCM2709, hence it may be fixed by changing to grep -q BCM270[89]

**Comment by Intyre** [comment]
Report issues with the installer [here](https://github.com/PocketMine/php-build-scripts).
