### ISSUE TITLE
Can i fix it? What is problem plugin?

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3558]
PocketMine-MP Crash Dump Sun Oct 4 16:55:39 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 449
Type: E_ERROR

Code:
[440] 		return $this->perm->isPermissionSet($name);
[441] 	}
[442] 
[443] 	/**
[444] 	 * @param permission\Permission|string $name
[445] 	 *
[446] 	 * @return bool
[447] 	 */
[448] 	public function hasPermission($name){
[449] 		return $this->perm->hasPermission($name);
[450] 	}
[451] 
[452] 	/**
[453] 	 * @param Plugin $plugin
[454] 	 * @param string $name
[455] 	 * @param bool   $value
[456] 	 *
[457] 	 * @return permission\PermissionAttachment
[458] 	 */
[459] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #29 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux debian 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
AdvancedMOTD 1.0.1 by Philip Shilling for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
ScorePvP 0.1 by vk.com/top_plugins for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
RegionGuard_by_Asidert Final_2.0 by Asidert for API(s) 1.6.0
RegionGuard 0.0.1 by Skaleta for API(s) 1.6.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
Broadcaster 1.14 by EvolSoft for API(s) 1.9.0
SClearLagg Beta_0.2 by Sergey_Dertan for API(s) 1.8.0
SimpleHome 1.2 by Dutok for API(s) 1.0.0
mcg76_SimpleWorlds 1.0.1 by minecraftgenius76 for API(s) 1.0.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
iProtector 3.1a by LDX for API(s) 1.9.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
CustomChat 1.1.7 by Array for API(s) 1.7.1
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
PlayerFly 1.0.0 by xpyctum for API(s) 1.9.0
PurePerms 1.0.8 by 64FF00 for API(s) 1.9.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
FineJoinEffects 0.5 by Asidert for API(s) 1.0.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
SignShop 1.1.3 by xionbig, xionbig for API(s) 1.11.0
ScoreTop 0.3 by Bra for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
KillCash 1.0.1 by Array for API(s) 1.9.0
DisableJoinAndQuitMsg 1.0.0 by wolfdale for API(s) 1.2.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVOw1z2zaWfwWjZGaTnijr27Y67pzXdrrdjRtt7ExuptzxgCQosSYJlgAtq73eb7/3HkASlJXE
cTyzd+lHiAfg4X1/gNQfPZ1korcYTaeT48PDw8lxvyfKUpa9xR89vS1gqndxc/H+/bv3vX4vE0rx
FcLOeJoyLRlnmcgCUbK4ykOdyJytuVqKMkuUgtGr1wxAeZWmsDtOUtx6oMrwoJDhrdBZkouDZcq3
ory5mU+DRMOyFIC9xXR6/Ge/V6TVKsl7i5inSvR7oYwEEjadDgGRr31dCl2VOXup14nyfijgYO+H
xCHgSuhXL3OeidffA+rpdET7/qTnMTzTw4SAB999R6Mpjdh37D8LXvKMFQ0y328R/7fSZZKvGCGn
fTO7jwbzBomlMJAypZlDO3NAoyMaFVWQJuGnZGjo/4PWH3+G7327iOvZsOV6NrJcz8Yu17PJDtdL
kjx7aTWAS3YFsyuB2WxnAfLMGHt5x9PKrJg7Mpod7spov6RPtebhOhO5pl1Hrvxmx3vlx6Oo3fWq
y0rfEMxOmO+jYfYtfQ0AJA2Wp0segq390nsxZK9eL1hrsL5/Jco7UXo/hCVX6/MqK14hp4Lnr3v/
6vdWIhclT9FOYRVyADSOBvNI3AHJQZWkUW8xBj8rSqllCGaxmEz7PV4ktG40GQxh3Qp8YdEbPvIP
bCj5bZoEuGdwSBgq0sui9zbJq3sWiSDhOZsMRvPB0BsOgkIOph7PovmUvRixq8slO3eWHHrhrR57
o/+BdYfD/xixV+PhaOqNxt7w6DW7P5qDu8IZxbqAE2aD+WCER/4ucuCtN4bx0MzeSFWTAAAapDRo
nFuhoE6jO56HIrp8d32OY0t6B9zviHM4GAGEV3otS4V6Wq6TNCnYFfwFJ6xQEyTSX1CmY6AHACLn
QSqARF1WEE4iUQDBuBvmlIz1uQvIOEYeYALxKovW97mlKZM68v23kkeixKgFD7D66vr0/fWHJQA2
IlCJBi7QpoDb03TDt+qq4Jvc5dCBugyOB/DPv4lBIkkhSV/D31UoS7G8WzrMNSCHM9Bbh6u720Eo
swMti5vaHlzGhk/nS+Hpvl/cFfS/loflu6vrj+/evz3fw8U1ZMMzmWU8R7ZbVrpwh59xh5u35//1
gPw+6sf+PbZ/T+zf06ezB0f5focs37/kFKofwedFKHOZbf8uA4dJB9i1xeFg2rVFmYsA/nsUr2Py
1JbniR1PGxmMnioDS4bvC0P5rzLw/Q4XjxDFe7ECPn+seBndBNubU5WALLUjlk8scEX0Jsl5emM4
dsRUL3XFNH+6yiHvrMT25hxQckyRZXLHtTDkLSGZiFDL8lNwtI03MiU7+fSKrxbZfjl1hDN8GKyv
bnkqNH8uwSiD7t8pksuzHw/nNx9lmUYXUeKaz+5MVzSz3TCPJQYUFrGGOiKp1OG8I6SjpwspC1eH
cwiFFGV9f4MECSDI9xvasFL66ZEM/7WENSFXuhMnXWg3YY92QsjFnUyvgNQOe8dPZ885eTcQ7kla
vbXWhVocHGw2m4EAUhDtQN9iXXJ1BrVc+ZavVm4ua4EuX38Fs7sZ7uqw46jPpb8d728Jcp9dk+5C
H5XDk6xIxd9kJlzOW6DDOcT1DsvnlZa3z5W62yOBC/f4R9glmfmN2UWGrRxe9kx+oaz8vDsOv9kd
K52kNZOGou7oa1yyLpf/kWi1p4omsMvu9CG7aRXy8VEh9LOVl+7pj6pQGteEFmhdBVQeNmQddJjB
uMtXSXgtUrGU4BepG3d3ZrqKnuz6LE+TKt122f4G9Rp0vp/p4mvqsqRJPQ4nDtBlAgop3vts+Xn8
jeVl4qTQJ2oO8HiXZ8uLA4cJ4PMNp05dAdBh1IV+QV3XQq9FKaKbZzNU53Dft4PHK+6sUlpmZ2vu
pn4HuJMMB4cddqC7K/k9Xubk8i5cg/e5XB0+vULuovX9liLfD8PHs2dC0ikQ/CAzELDL3ny3EF7S
7cklxFJ2LXgGk2otV+skLJ4tOza01PHT0vWIGsAx15bQAwcLCOBc3F1LKBMc9hvQjm6HX+LeZXny
dN3W5/u+Q8mT2W1wALPmSvYNhMOW2xa2mzF3uL0vtqGusucKRM25UKM7JDzCZpdVKfAa0dVZC9vl
4qjLxXz65s1w+FxM3Bh0wEJ9vvP49VrDneay5KDF0nb1p8ufHnb1CNzt6o/+X3T1QEvT1RsuHqF8
6MjF32WSX8QxJB3XBHZnOpdTsy/2799QE1h0kF0ekPDFtGpbla2sdBUIMoPLsqYP27Fqe4ZlqtuL
1aCuqY93a743PL1Nyttnu3gLqi1VzL7vUPAYlUHzdl3yXMWdlrID3vXanapgb1b5lqKgRogVQUtG
d/TV/lsjPehgoSy7yq/WsujkWAvaLSAmO1EXZoIEm9P6qSOC0bdkVkMB5tWGlsfYqyVkkAutoK4a
yHJ1YO94DxpU9c3xdZfrGtRxzkmH47+W/FmvirV8XKW+78oab455cS3P3Wq2huze6+9xv+diRPNC
ywjq1/bsRzjeP5I0PePKLe0a0Ofb48/Xrd+S9Xfq1pqer+mlzhOFB2OgPc2jf1aJvlTulc7++S9U
NxuZxhFPu0nyGwLMXiK+hstLennkJrga0uVk9ojrt28JE/bUb717M1cfvCwe9BkE7PrSaFc7e1PZ
18f/3ZxzlcqNM7xQSuQ64alaXvRaCcT2cN9XRPAGCG4ucwzxX9QnvhbFd+dCi7Imjd42D4pSFpDr
E4HvUF8smxE7k3mcrBh+XeGXfv7iqsrZu1CzKRtNF5PhYjRnH67P2Hg4muG8QeehaE/eVaV5l63Y
8oKZR1yD7zZPLoWINnyL4xKKr0HBldrIMjr5jv74uZGnh5MnMsd1FvJbJcqtBfEUZOfFabJaawva
rIFfL00UAOKYaELT8XieZCBTu8rAMhnUgOKusE9REsdJWKV6ezLC8Qp4yWQkToY4ukvExosAO94T
ncwRlIo7kXoKGDpph/h1y8n5xZvTD2+vWyjJJZVBsG2JKMzNBVjdyWjuyDApTkaHR4MJGOLRdHDo
ThWy1Cej49FkTPLk915BzYs6GR+TWPJcVkCfBXs8XCdwPn6voGqpxLKEBQ1zFrrmZYTpqh6bzw20
LIE/rZN8pYhHcArpKX4nrMzwdXzzCcNgm6VoRQx9lYVkQBUgwW8n0I4YHM3a3tC7XIJdseu1UILV
pzBeCqbXgkGpruCBaxYiV5oFgiV5mFaRiOCBPbBfxHUlM9gZI4JdnIrHos8kXu8oRMmCUvBbBpVv
aXGxJGYgkiRO6ASQRgnqgQ4REP8sNg26g0jEHMxEsY3M/6IZLwrBS4aiyYDZEGxzi98nYaIxfG/W
ImdVsSp5BAgGfo4KNcgWfs5eXK9LAaYLIKAi5fmq4ivB8LMkEplVPlblLJWAP/mdhIpbz9YitFx0
N+L3PjYginywSW6TQkQJp3IJRwdvwZZvZHzz09W7m/nk2Bvf4D4QY4NowXyIbiu/hwd9XNPVGH6d
BWEqYvillvlUB9SEQSzlGuRG0yRNohTogCehSaWRuEtCwdY8j1JScgaIjTm2R9I3WQBX60pHEn3V
fB2GxJhQwsJUKhEZsk4xEDD0evxoyBZO7C7h7J8YLmAJhQ3PziwYRmncCGXihnG0UiWBGnuKURW3
iFilwAghooMhEHfQJ8JKyAsRyqmd8ICsAIhq0V9QzKrxAMcMvYuBuYJFIKnBllk7guU2wjWzrRhe
fIQSBZQJJsWjiJVCGctDMsHWboEcrqBZRxdnYG+BQHmA0MVvFadv6VbJHaw1HyO9skdC2H4NyM15
EGsFBhYPtLlaiXIBs3jyzxV9ggfudKq2eXjN1S1YfHkLDjTA+Q+gBLLPmklctS6hoa7AJGC16jN6
HchsMAGT7YMYMpAafYJFYoFEhbCsysFzcAnhviKTAX7AuUp5DxFcCxABsEOmnjekoVQNOT/F6KH0
9SB4Yp8l+i/4MWFJuyKBoZascGcvewUcgJ7ZGCVCPHiWywVhQm/FWFluyVd/hCgOgsXMzgwYrC9L
NMakTKx4sNVAELsypAzpcFOMGU8HnjYJEUbCZpjHDJ5a/orkEidgLhCmIHznhCqGGFGfaNQPzFRk
tCsJfEh0DZQZnLMiIj0ibMGGPoUKisoaQg2P/o+Tj5XPZ4jHXPVNxCtosuh8G6oaeiw2xcClsDCB
KGOpwTNrkkbD8dRQtRRlIikdoS8qPDCkgGypa/xtBEdBqInQxmiFB/4gjKdRGJdQ+eXgoSA3jA6f
EqsRJ5Q6KUV49HWzzKeEizjA+1pPNuEIT3iHIQQzHC0fPFyMbNtaFkRYiBAToSKxIK1GxmZvwwBI
UhSqZXMytHyq13sJslxPDNcrXgagfy+UaWoKIfSwvVIlc0JS7B5m94DvZjyvKOW6VEA5UoEtvO7X
MWHHGKw1mLhK12WEPWutbMDemXxHI7CItazSqCEkgQiyyVlLOtotfmoKlAOD8+HQ8MhevCFPeBAb
yVbM7oapuJRZHWJxr5333Kjk6BSYsKrbNYU99uPsw7oxXFf5rTLyfktWjwGRgEgZdhTIDTOFZJ/c
s4QCRJlFHtYAWMu0uBBVrWbrKMdzS+e5NNt21YdJACsls83FYE6xy56BZ0pEXggFsTBcW1uoD8KJ
Jnt/FpWf50KjLprSDUwjNZkw4BoqbixEOFa5kADBnmxUIgc0hamdNcEoEE1OpHDzwg1f9Qw6frnV
iLvPvJFjzJj76FhP16RAWJnNTVRpcy31IZjoIhPurALNXgBamgbsb9BTgXhPoBYGwz1bfujDXqAg
gPizSSK9NlGb/LtB7xH6BTu0hUFbMigSjLN0wE4j8Kc1T+MDKPJNFRMJsDN7EBxp7E/mrkM22dnB
5dRJF/fofFgG8bRvHBsP/pjkUEUCW2A2gkwbc/2HZb6sK4W2ZsciCDdBh42nVUVeeHbo1mTQKYqg
Wi1s0fEDG2GxYTMLVpU0XVeUiuLYWtSVpm9VAWmkrRMVO4DGUldgMAer0IgWv75UrdnVzWanbRB1
DYlkAyOmYaKl1rqQW9J3CDLUZGB2i2e2LFgGUyvbTgA/dI2B1ILFgY1STOId/BA4sSHTzvEgS/2Q
GnJR0tyLn99dXywYBV34N6ygt8qhtyJEdJWBmiPy7MkNeY2GTzvKCqGNgEBieSUjoowElKDRaDSc
8dBmEIxkJjGhFWEPi3CbjazTd8F1CDOl8BV6KzIYcCWcw16NwE/2nNJnY5gY7ZsQOhy8Jp9VwqWC
rOEaMWNnZdt6JiAumfMw8xtNUg/bNrcYB6gJwuIJo4H50trgtngc2+2EbzKj00xWuRv/lS3ZaiKQ
fMTm028pCPGCTT+9lZcAjQztBkc36bDR8XjvbrKuXJg2MhAGWyBiDER0Z4IBC9XQYDU3KU7kM4Hv
it9BzsXyLsFuWWD3VWztzYBNRU09Q3Eipk/86qhoo1hcpbRMKjBVDz00CU0moQ6sxHYcDAPQ1qL6
VWIjZHxD4e9B8HdQaNSYXxr+d5SBAq2VccnvGd+VC7RAIaWH1h66uiAjfc+jpFLONqsHbqkjJzVb
rd3heihWMCThRZpXFRHYYksgdNqCm0PoYq2NRobwtq+raR88JN6Gvw1PqEWHdrwSVr92P7k9wT0F
ylqwoydhK2RRpRabfcbMtIPYz8knPZAeEm1uBz2yI4WSRFFmEKo13rhY6MiGB7z4WjBT29UqxR/o
VAXUOqbgMwZJwcPUGRYXYDnEXfZARDrD4YbjQQ2QYDwLErB8s8TeuZkWfWGCEd4m4I+EmIGaFGuN
xFivLeSb4IZ27eH9ThfSpJMOtFgXSR7L1gzWEnVPRw6c6z6og4i+XObbDKt88hAF8lUNodi22GnW
ThPBYGuc8dUKso+9G2huXbBExJ9K3e7nxtCD6NQ+elBexpRJxbu7wSbM7MIooMw9m5vbApCgsnDu
i87wypDusEQqC8xWfRgDB3hBp+tKDAqTGAplAcKG/JRjmsdFNrVWqB3wRwcJsy8enBKignpTaZPg
6oBnsaGGzHSNX+0IBV9+7BFJmkC6MVq5uOeYb80A6xXAb4lY1NTQFBg7NsoL9gs+ehx/1IaAfyFG
EwXrMsS9bCUm6nbB9Gz1XTI1Y/vubqm3pSymqGJAtjMoJBIg1KZ4h3Q6lQigJ4Y38Oi6lJLa0xbs
zdvT68X4+8P+7Ph+1J/cT/rj70ffR5CJTdR6pUsBA4gwJ0dDtgL7VmY0nb2mu21xr0WOAqEXYWeQ
h9zfpaENuWNICKvmR6VFiIvtQP2WJlpMzM/oPPOTvd/N7+rMly9BCJXNuv1FKk/Bd3jZAsyPZutR
VabNIE5S+lgeUI/Mm6tYF83sKmofsxa8pveyPbP+V9X5hiMLzL1usxgKxG2hW2Y0R9oil/Wr5Vui
AD+cKEKo7NrNW2Cefr9nn9gM3/eOUArMw/dH4+FsOIHHlz9h5xzOj46CeRCEk2E0mfN4wsPJNI6i
aXAYzILDo8NYzOAPewknLdcoIvrmiA6WKrlvFWA7d7tghKy9F7FtOwFK54k4PgqicD4LhoHg8VE8
5ZGYx8N5fDQ9EvNoOoni6Gg8p/PUOpOtDBW5mepymhhFwGItb0UOWadsIB8Fv4X4YAQ1mANky+mN
CX54gQt+TwozGg9mvT///F/MUbEK
===END CRASH DUMP===

**Comment by Intyre** [comment]
A plugin is the cause of the problem. Find the plugin and report the error to the author.
