### ISSUE TITLE
Arrow crash [real]

### ISSUE THREAD

**Issue by CaptainKenji17** [PocketMine/PocketMine-MP#3559]
I discovered now how the bug happens

it crashes your game client when you pick an arrow from block

**Comment by TahaTheHacker** [comment]
you didn't search if the issue is reported.
and yeah it crashes.

**Comment by Intyre** [comment]
Duplicated your own issue? #3537

**Comment by CaptainKenji17** [comment]
it might be duplicated but this new report says how the bug work

**Comment by PEMapModder** [comment]
@CaptainKenji17 then comment on the old issue.
