### ISSUE TITLE
Teleporting to player in different world while vanished caused crash

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3561]
PocketMine-MP Crash Dump Mon Oct 5 10:46:55 BST 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseSession(66): pocketmine\Player->hasPermission()
#2 /EssentialsPE.phar/src/EssentialsPE/Loader(832): EssentialsPE\BaseFiles\BaseSession->__construct()
#3 /EssentialsPE.phar/src/EssentialsPE/Loader(873): EssentialsPE\Loader->createSession()
#4 /EssentialsPE.phar/src/EssentialsPE/Loader(2148): EssentialsPE\Loader->getSession()
#5 /EssentialsPE.phar/src/EssentialsPE/Loader(2293): EssentialsPE\Loader->isVanished()
#6 /EssentialsPE.phar/src/EssentialsPE/EventHandlers/PlayerEvents(155): EssentialsPE\Loader->switchLevelVanish()
#7 /src/pocketmine/plugin/MethodEventExecutor(36): EssentialsPE\EventHandlers\PlayerEvents->onEntityLevelChange()
#8 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute()
#9 /src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\RegisteredListener->callEvent()
#10 /src/pocketmine/entity/Entity__32bit(1011): pocketmine\plugin\PluginManager->callEvent()
#11 /src/pocketmine/Player__32bit(600): pocketmine\entity\Entity->switchLevel()
#12 /src/pocketmine/entity/Entity__32bit(1357): pocketmine\Player->switchLevel()
#13 /src/pocketmine/entity/Entity__32bit(1307): pocketmine\entity\Entity->setPosition()
#14 /src/pocketmine/entity/Entity__32bit(1428): pocketmine\entity\Entity->setPositionAndRotation()
#15 /src/pocketmine/Player__32bit(3269): pocketmine\entity\Entity->teleport()
#16 /src/pocketmine/command/defaults/TeleportCommand(91): pocketmine\Player->teleport()
#17 /src/pocketmine/command/SimpleCommandMap(193): pocketmine\command\defaults\TeleportCommand->execute()
#18 /src/pocketmine/Server__32bit(2015): pocketmine\command\SimpleCommandMap->dispatch()
#19 /src/pocketmine/Player__32bit(2504): pocketmine\Server->dispatchCommand()
#20 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket()
#21 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated()
#22 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket()
#23 /src/pocketmine/network/Network(146): pocketmine\network\RakLibInterface->process()
#24 /src/pocketmine/Server__32bit(2485): pocketmine\network\Network->processInterfaces()
#25 /src/pocketmine/Server__32bit(2300): pocketmine\Server->tick()
#26 /src/pocketmine/Server__32bit(2178): pocketmine\Server->tickProcessor()
#27 /src/pocketmine/Server__32bit(1778): pocketmine\Server->start()
#28 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#29 (1): ()
#30 (0): {main}()

PocketMine-MP version: 1.5dev #1263 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT WIN-PPP21SHRN0I 6.3 build 9200 (Windows Server 2012 R2 Standard Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPYty2za2v4J1Onedjh7U07I6zqzrOIl37UTXcpreLXc8EAlJjCmSJUg72t7++z3nAKQAyoql
WO3dzm5NHhDnhfMEKfS3gyxYiINhq9vtOp1Bt9WrHYg0jdOD4W8H2TKBoYPz2/Pr6w/XB7WDhZCS
zxB2xsOQZTHjbCEWE5GyaR55WRBHbM7lSKSLQEq4O3zJABTlYQizp0GIU5sy9ZpJ7N2JbBFEojkK
+VKkt7ed9iTI4LEQgAfDbuf499pBEuazIDoYTnkoRe3Ai32BjHU7DiByMzdLRZanEfsumwey/ioB
wvVXgcHAWGSH30V8IV7+AKi7nRbN+52u23BNFx0CNr//nu66dMe+Z39LeMoXLCmRue4K8f/KLA2i
GSPkNK+n59FNv0SiOZzEcUgjR3qkSXcDukvySRh4m3So+P+Nnj/+ityPzSKpu85K6m5LS91tm1J3
OxWpR6R59p1eAXykqpiqBrq9ygMoM2Psu3se5uqJvqGj7lFVR49r+jTLuDdfiCijWQNTf93jR/XH
fX8169AWpaYYZifMddEwa5q/EgCaBsvLUu6Brf1y8MJhVYsdi/S+tNhD5+WQrQZdV43WX3kpl/PX
+SI5fAmsvmix5rmUwE8Atjw6byRznhJiE9r8kUvxBvxE0tVYqLXs9ys0lM9Ul5zotLeicxlzX6SH
g04bMJsjrluyoC41D/VXt7deHMGa516mKHV2onTUWaOkhlBTgmelsIS7uwvudqs72Ih8JjILc28n
zO3jzWwH8iceBXIufIW5vxXm83u4fscjPxSp1MGPYPKw1ettJCYfgsybX4p7ESqqiubRmnEqK29e
iWwe+4T4/Ivw8ixODzv9NfQWN4VdKXbqr+LoHJ7MlkT1bM6jmVBUB5uoXotZIDORCv8S/0agwuOq
7apHXfcRDuuvBF1pMsebyCiPvuIRJKP0sE+m9RiJdXbA2CBzEVHtluvuLUjoppK98PKW02ptoGJx
s06gxb6a8Q77TjWCKAZgceivtfYaZ3tLpju9ow2RYx1nZ1ucztFT/IpsFMsgK32u1d0Sd7c92B73
aeRfxxk3yPSeUHWn3T9+An8mQpHEabF4/TWMXrxYgL80fTHleZjJ5o2ecaYGDo9bG1ReQX20EfU4
WCSh0PiueHLYOq5auH7UdQs2XLfCR8WXWoMn0ljbafU2EakyVH/lBzLhYEAa+fETim/3nO6GNFlg
KtSnkti6V0Yie4jTu+Y1v7sMJhcRuPUUUjTYjLMxOWJYe80zPuI4qlFrf0z5XRhMmpLY0LrQgbDg
+riKWfMAgcVmoqB1Hnk8kXkI2awQpL21IAO0G8WV6yq2Ci1pvgoyljidjQTeq7+gof7WciRp7EG2
1Li7T9lMd9DbhFpTL1GWRArkvaeQd5xNpVUWeHcaS/8pLK2jwVewjBRzkBwVuqMn0LWONqKTGS98
u73ubCO6vILLw25/ky+slVjtY3aIZqELLodRtfnbggfR7wD7V+1ghlmNh9gVAQosc6AibjV6vriH
KZM8CH3o7tr9DjRTaZzFHrQhw/ZR7YAnAT3ZajcceHIGvdfwwNnyH5igLBXnNI4IQ059wPDgUxD5
8YNk72/Yp4v39dFo1G6N312/dy5Yv9FhxBI7bjsgTPGokp9BCGqz6zYbZ2DmPPXZuU+B/iULeoM+
kEjmCRDoNfqNLtz9W0Qg20Ebbh01eBtLZODi/fsbANDNAzQvZSMpUU2n/j2PPOH/I8joXrNtgWsr
ZXYaLVBWDrVKKrEfCHOPtweJyFD7pMRfCi0CQER8EgpgCxYRGlZfJMAkzoMxGU+z1yYAl7FCGcoi
Tu1WCHUfjI0+jG8+fbi+fA2gBzGBxIe8zrMskcNmExZtnk8aEKebJVtNSxAQ/TQMuCUo3dcsc1E2
YEj5T+69gyizPxmRqBLuLORSPiEh9mHE+gNfynHCHyJLgBXUFKMNYrRtMUbzIAwSNoY/IfSqexMn
IbxSo3VdTixJZKko2VcSjm9Or28+jh6TD4rej4kP6SI15TOg9jK1bOnO7+NwDBxaYg2esUgrwlU7
fESG0gofHh4aAlhBtI3sDm3uxxCi22U8m1mCmVBbMKdqf5dBeJZCZbBsx8fNU2g8wpj9FPhpENtr
6Hy7tAY3W3mdXjOYFvtvfrbFIkhlraoizeNlEC1a3YXH/oudLSciPcsnov7uH+xG8MXeTHNFxnUn
yNn0CzTyJYvbSJiHd7oaM+OGBa4sX52i+gvHOar43zlUi1exj/5gCth/huuJBU8WhBIEBJ50lYrb
FTaHu4ZQg9nmeAFdXP2fZ3XV3MlmlgrRXHDsJpsWHVDYGSgo5XBraGsFq6jKVhB01eHd6Hxvq+8h
PqjcC+quazLypEZAIYShkQgSbC5kdomFiunGJrSSRv7Y+GQQfmZ80qt3DUQqwbc6Uo1TlRAc3El+
l+9NQJv4LmFJTx0Hs0iui6PAhixtS4oxX+Qi/DxvWYI8I7aWCMH+DA5cd7G9QLgpGNyLi0wsJHih
JdXa2BPp5OpsdD66eLsv8TQ6EK7KyC5L9lrc38RgloZgJaiSS9YEWrUT69kDKtZvFayg77oGJ1u4
mBlFS86aJQ4Q9nyRZMtPcYrtSCmuAXxiAXkY5OFyb2FSoXNdgQw8IAO7BBRDWh6Kz2DdaQwIjXav
njySNi7evz7/qWnIjGqJINuMBE9DUy0rYLVM79hq+Z9YQhF6fHy8Ztk1XYJ8o4JWLOxi0ebesimP
Ca5WSZWccSlmyMyHKfrYfiujxzbWv6FMUBwqBq2tfVxPUd7fjAwNWOCv14n7ktYkCYZuM7DFWr4B
o71JeSSnVn60wFWnraylnMezeeAle1vBAqHrmmzYdzu7cIG0aWEBDbxN+eRHPjOELyDVrvPo6WBV
+mSruNhD+JoBPxM+++ZNg12iVyE7KOZd4IsbSzEFxFCMvWvyiUeZ8O+gX4ZxdnhKI7ipNRZRnJ7F
MBplMTvEHR8c2FeTZ9GFtKYZdV3F7VcVtpbUPvEUGtBUNudaXNBFgLyDAj8a2ljBTH00OpZG3kCZ
HaR3cl99UeApornrmvS38PSLSGagph+hlrkzpLDAtsWvtTF39yILIu4dH+3N11cot0jNWpJglMaZ
8LLYjFgG0JQCqiReST2vf7a4P/525gEVLENJ+JsdFPDUKc8YQuCKQbl5xqWwsqwBrMblwQ7xqfP8
sATiLDzgJBG7FA/I/zgCY8ONOlusEmwL1qma4dvFp6u9GSAic12T/C7S/D0Ookc2USywLU232luO
gi8ifJsvj3r76ltWGF3X5GQXwa54pMpXUywDaEcKp1qxbrK9Z5ociKHq+J1k+RCJd0H2D8gOhiwG
8Inmv99988Zx9hUzbhU6110xYF7vXNcodE0DA0g8Eimt0ynkQ+v1R2Vg933nZ0hu037m1k6B7GzO
s0fkI/Duu1bPsVGT9HOFC3n0oykV3T/xLuctPOulfJpVNmGfI1MChCf0qp3o75rXDJaMDYNHN1sV
CZSdnnub89TcQjCh1SKlYrZIQhP9++j93lRhowWdWBztqhkbW9NA1lwp4SqOxHJNCQpqKqG7HrMq
Sqj9UVoxWCpUUvC3F5UoZKSRJLE6VA14YkPpXfmapDbCz0+ExDprfy8IiQmUXDOzRTYa5anArzmt
sFzCqrsGLefJZPQcAcpsVHJgXO6+KYgztXOvsIDM14KHN/QFeilyCXrCnd/mkNN4vhCd3t72rQva
O7+phokyjj5d2nIokNUE2m3xGQQ6sI83+K3xvlYu1XR3KYSu6cux65uxxX8Bq5pepaSD1uQztCYX
0TSIgmy5t6rARotfc2qGjMvtxFPfl4A6zDrPAJoCOuv7WJn05ilEHXZYXLXanb/NgM8Qrfvlvqyv
wF58EIS8mddbvsHDuqFA1YhEhn6Gr1+uYj+YBlastMBPRMyHOJz6PBT7etdg0t7FVtXHiLiDZAlS
Am0xjta6qsqbk9r+tylXzBSfTmrGvvlNioGl1MAldG5v6esve7/jsdGnXo99FL7ke5bf4uDRgLp5
I2cM7Xb13dgKtnGX8Y98j1mS3+Ul5jjkleqkgFRr9p69Ip/jz7E4wn/2t3muKO/EfgIB2GZfQwz2
nW02Nndn3NhFNWRQ5GE1Sj62EAMz+hl9mGvWGSZ0rbg6WBNpXyZlkHVdm4dtRVG7Nta62PCNL/qr
W5zmm8Ja2TsWO2u4J/W8LVCLrV2CPE5Mf7S+qClBlbrQXipoCybwf0vKdindNycrjdZ18eeS6QQ/
rDH42UKgn+JMXIsHu3k1gOaSVYrEXRbtOYu14maXlaKtDXxtc5qa+y0WeC393E5Exm99cX/7wukO
tvtmzNnTN2O0TSiAM55mrlvh8w/7ZsyiU6hNb+pX1VaAq68ZnR228ffwdpEUlShe/oTPIyzRdcn6
iadJpVwlkG1QvWoQ2K9mqu+8LUbX1SaBSXCi5E95K1tqxCqM34mwUnVUh6q79N3nf25j1uBbWNec
GPmTlFSRXm+2VLeIC1C1Nus/vdPy1Kc2xkbOY/ZFP1uWYFMHG3Zg1N6xweHz9l8ISWkya15WAp94
7buvUq/iYOMwfjBurW9sVvqZauLocciw8jmL+W1+YpAKfj6dgitbv5EwoF/vnfbV+s/FJJjJRRCK
n1+7rkF/p49A5zxIxxn8y/4Ay4bbux1ri2qxcvDHyGcxtOtL4uvAX39FrIFPvCDeLNtzEmZFuBU7
O72LvLg5sxZNA/4/zE+R3oV7tVfx93gi115LEHBjR/Kc1w/We4+d39BovvbyNoJw0b7Fkn5WYm1b
aNATezB/imkWzGz/Sc1PuMk+EynEY9/snm34f0BIsRjarYEJ74V8E6dQMkhp1eLWQHWTuPUnOKLN
wvZS4S8e8QgWAVZaUKRt5AbU81ABZYHAH0e+GJV37CyOpsGM4SE9bupGL8Cr2AcvYz3WcoadwbDV
ZT+Ob/A3mj0cx7OBThy8UojrqLQTm18IIavxIDmBOv2o12i3+41Wp2MM4V7+Seu41WkjcCEWcbqs
h8EiyE4QMOMI8jW5Bf8CRR7+wluetBQD+LO7um5UYH1o0sMctAFIZKamqcWo/5qLdHkSRwYo9WBK
PJ0S8jjzT9zccfhRqP44+m9X/xUhUxeTqqzFr1g3zVN/UyTDoyjOI09oQercmwfiXuBpNbJgBXrJ
+KE+DYPZPNMMK0F5FECjWT6ngAsIQAVkGqeAutSahs6hr/fitLxP7hON1g+m08DLw2x50iJ9F5u2
dSmyDNKYPGn/cFTrt790au0f6JEQz41QSw5xcQWRQvgnq1sykjeXpzcIQj03Ei4l9JX+yff0D4iZ
Z3Fd8nuhmcEf8pbVfGO5CNFMGdo988hC85ROfCBDZSAqM74fuBqB4bKbuZCCFbwzngoGbsUgS0i4
4BnzUP8ZmwgWRF6Y+8KHC7bmIIhrHC9g5hQRVHFKPhU1FsNIKhElm+CXkmwZ56nGxYIpW6g3HEgB
tJ+ChULzA4jfi4cSXXmWBHuIo79mDPdpecpQNQsQFg8UWeI5WnjYk5L7YS4ilicziHWAoOFG6EsK
2dCN2IubObQ/9RBAwEXIo1kOoZHh8VmkMu13MoB7SAfQkv2blIpTz+bC01LYE/FcKp0ORdR4CO6C
RPgBb8TprIl3TTxj5Tae3l6MP9z2O8f19i3OAzWWiIbMhTCYuwdI6NNcoO7wFDGo732GJ4qpI6Vg
mbD6p2MU1DBpkzgFPuBKZLSkvrgPPMHUqQgIWQBiZf4rkhh9ASzneebH6CrqEDPkRbuom7eP+t3S
rwNQUAAMzUIReHP27zzFkann3f2FWTMKj3aj1zy6A9Wq51LgC+zpJ7CLDCGiG/lRIP+ixD5Fv2YY
mPDwLN2usvuAs//G2ASPUIwqGtmS/xfjOczj6AUyBmm1GMoUuEbEcglGDpkGDI20dzq6gCfxoB1c
h9VAHRQ6ieVKPS/OKRoWeECjDKMFA3cAi0NWJ0um7RQe17GzHB0yOqKN1hUSMRgLmCz3fQaxUVk2
soknLgA7XEILisGOgT1PBOoDFlX8mnM6U24W3MOz6lCuQ00S8s5LQK7oQcym9791sBb8+e4QRpHy
+5yOogN3PZXLyLvh8o7hGRSwEA0c/yhBI2j/hZD41DyNIRiDycHTssZo04vpEAguUQM1LJJUnSBF
aoFMi7BFHoFn4iOEe0wmCfKA86bxFwjRmQAVgDjkSlHJGmpVsXMxxQhAp+iBp9dYkP0VD9VLaZYv
MJuRlVfmskOQANaZtVEjJENdSzkkTBgNVBKlWPA2jCegWKw4mAIzyq0Y8xZixifLDBhiY8WKQ8QD
icurIgnI9BAQY6RshmlJ52gNkqSXaQDmAmFQ4NlHiGUKMaigqJYfhMnJaGcxyBGjU6POgM6MmFRJ
f8gcl0IRRf0MQhn3/8PZx+rtK8xj7n0W8zKLE6KvQ2HJj8YmGbgU5lbhF9wgzQpLI5EGMeU6dESJ
1DyK9pq10tlaQAfijI8GRk/UwRkgVrQcjQlfzQUR+CdoDWPDJqUqZUItFlL+QE9Xj7mUzhEH+N7K
j1UwQgofMIBg/qTHG+sPo9C6wgYFJsLDNCtJKcis0rCaW0oAehSJXMnZcbSg8uWjDGmxO0rqGU8n
sPp1Lw5DVWmifz2qVjImZEXPYXoOeO6CRzkldJMLKHZysISXtSIiVExB24KKqrQvRNgXKxtrsA8q
m9Id2MM8zkO/ZARyGuQ+tmIdrRYPXATOQcC+o1eWvXhDfrAWGclY1OxSqGkaL4oAi3P1eN2MScaa
ghB66aqm8Ij9GPOw4vfmeXQnlb4vyeYxHBIQOcOGCKVhqqCukXOmUN5I9VAdKwyslFa4EFWxzNpN
jvuaz9exmlZdPkwBWIepaSYGRUU/tgeZKQ3VPY4fJpLU2hYKQjhQ5u6vonIjfSRTWRiCaYQqD07w
y0cqQ+hEKUh/YE86JpEDqrJXj6pQNBFlRqRg88IMXsUIOn66zBB3jdVbhjFj5iOy9axgBdJ3r6+i
yirTUgOBac5XwU4voJoLQM1Tg72DBgnUewKVNhju2ehjDeYCBxOIPw+Bn81VzCb/LtHXCf2QHemy
YFUwSFKM8WiDnfrgT3MeTpvQQqgaxhdgZ5oQkFT2F0emQ5a52cBlVEnnX9D5sAjiYU05NhLWJyI1
GJiNINPGTP9xFI2KOmHVEWAJhJPojS22A1FS17dmRQYNnpjks6EuOV6xFpYaOq9gTUnDRT0pKY7N
RVFnunopKIkUVaJkTZnxLAeDac48pVr6IcnK7Ip+0GpKRFFBItsgiGrH6FFtXSgtrbc6E9SnopWm
1NWUIVvA0Ew3KyAPba4gt/f44wEVk7iFHwIntnuZQR50ma1zQy5KK/fi/Yeb8yGjoAv/83Lo3CLo
3AgRvWHAlSP2NOWSvXKFT63F8uj4zEJWMiLKSMAJGk2GhtN2dAbBSKYSE1oRdsgI19lIO70NLkKY
KoTH6K0o4IRLYRA7bIGfPEKlxtow0HpsQGRe4yX5rBQmFy1aUcSMfZvekGEC4pKih5lfrSR1yKvW
GeMAtUBYOmE0UGcnKdwaj2G7VvgmMzpdxHlkxn+pC7aCCWQfsbl0ojAhHrLu5qk8BaiveFc47KTD
WsftR2eTdUVCNakTobBNxBQDEW3LYMDCZSixqs0aI/KpwDfm95BzsbgLsBcX2HslS73voFNRWc9Q
nJjSm80iKuooNs1DeiyWYKp19NDAU5mE+q8Um30wDEBbqOpzjG2Q8g2JpyLj5y1o1JhfSvkri4EK
LRbjin9hvKoXfeKf8Ff2YK8FGek194NcGtP0OnDNHTmpmqrtDp+HYgVDEu6K1XM6q2rVInuh4IoG
bfytgpHie9XUFaw31nnX0e+BB9SfQy+eC728ej55PcHrEtZqyAbfhC2JE3VQJKpGXWNiqiB2I3LJ
OigPmVZ7f3UyI4mKRE0u8MxA3M7R0JaODrirNmSqtCtWFDQU5QmUOqreU/ZIsUOVGRoXYOnhrd5r
VMEfxEAyNowvJgGYPVDtIUKKSqo7H6pIhBsJeBI2U1CVX7WFKNPVVfxqpwbm1HHryIaUucSCJvMk
iKbxKu7OY1x5a6u5CfmNmIviaLnA+p58Q4JqZcklNix6mK2GiVuwMs74bAZ5R+8JlLstWBziUeF3
FVFsbhCfbBj7mlCSldpSVkzLuzYdDEIND5X+06iu8/Kq+CNonBg7RWe4GUm7YyKME8xUNYYfXOEu
C7CiqzAoSqZQJAvQNeSmCFO8GtSJNcflAW800DD9BsQoIHKoNmWm0lsR7jQ+XCI1XFBY8aj0gl+q
P6IVPCtQlb0QJ/EzrSH7BY25zvG4dgnNZJRNvGK/nZ4QGIhzql8hjWG7/K8iIIQcaqFf8IH8TrCr
eCLV0CPAeT6B+gJSU4KXyIuKnkX5Ym4Bk/hFm6F6vWLfnJq4x3aUqSem7Cep0kCFLaAACaCg0KWB
qg05lhhElRigK4ab6+jzlMpW1IYMd9iHuEXfO/7SqnXUNv0PPmRwFe4O8WMYD0PTycBhM/BGqe66
PUztdJLigwhRzaiFOMg8fSnz9D6456irfx3UDsSXTERoAPSa7AzynHEc58SDame++m81cFgmn6cr
gPrPSeg7NGpjMiSnWTk2DUL66hhfJap3idMsKUfnEEzKo9Tw1IP7cuizLL/ZwbdzUCkuk6wcHY8u
CSf+uiP2J16JJPHSFWPXYqpbPRj/7gI0PmnzjuP0Bv3BgHu9geNN2oNBx+u24V+t46nvCMfxe50e
+w5/TKAq/RKd1GeZGrIulvLXkI4u1VcQrVDSOngaq9MpqE7P6cAlkZ92jjqC93y/1+sMjvqtrtPn
A6fd5t3JgHeOut3WYNLuOoLIZ/GdiCB5aO3hKalBUpzzSoemqkNb1ceEcP0F37AUaxIvcMhxOq1W
+xjGR68/6JfVXXWe7GiOC0pfjKEW1cc2P19dltQefP9Lic/EDdfYFRmMAeQhDTID8knwOwhKapHo
qysovFcoSFtB+TTeZKKjTqCtK/4kBRO5mjJRbxRKwJLTG6XiG+9Eb5domeg3ddDL3Ppxhj+cKUgt
lM1pHP/EnPZhRBkVHjlC9SD9N/ixxhfqpvQHm/2D33//P/58+X8=
===END CRASH DUMP===

I am not sure if this is caused by essentialspe or pocketmine, but i'll report it on the threat for the plugin also.

**Comment by TahaTheHacker** [comment]
It's EssentialsPE's fault as i can see in the info code.
you might need to close this issue.

**Comment by thebigsmileXD** [comment]
@TahaTheHacker yea, i also think so.. i already posted it there, but thanks anyways ^^
