### ISSUE TITLE
Survival Inventory

### ISSUE THREAD

**Issue by Galang23** [PocketMine/PocketMine-MP#3563]
In LBSG or any server, my survival inventory only 27 slots!
Need help as fast as you can!

**Comment by SkygridRex** [comment]
I believe the inventory have 32 slots, not? Probably in the bleeding builds this is changed intentionally

**Comment by Pub4Game** [comment]
@Intyre How soon this will be fixed?

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
