### ISSUE TITLE
UUIDs are not always consistent length. 

### ISSUE THREAD

**Issue by Brvtvs** [PocketMine/PocketMine-MP#3566]
UUIDs are not always 36 characters when converted to a string. This is using an up-to-date mcpe-0.12 branch of PocketMine with actual UUID classes. 

In practice, I connected to my test server and one of my UUIDs was 37 characters, while others for different devices/usernames were 36 characters. This was the specific 37-character UUID: b6ea7f2f-fe1b-2151d-8557-da9e23ec93d4 (note that 2151d is longer than its normal length).

At this point I have not looked deeply enough into it point to a specific cause. I do not know if this is truly an "issue" to PocketMine's devs, but if the goal is to mirror a Java and MC PC version of UUIDs, this is an inconsistency.

**Comment by SkygridRex** [comment]
If you have a solution make a pull request

**Comment by PEMapModder** [comment]
Please provide steps to reproduce this issue?
