### ISSUE TITLE
Undwfined class content 'FENCE_NETHER_BRICK'

### ISSUE THREAD

**Issue by greckminas** [PocketMine/PocketMine-MP#3569]
PocketMine-MP Crash Dump Wed Oct 7 07:21:35 EDT 2015

Error: Undefined class constant 'FENCE_NETHER_BRICK'
File: /src/pocketmine/block/NetherBrickFence
Line: 66
Type: E_ERROR

Code:
[57] 	
[58] 	public function canConnect(Block $block){
[59] 		//TODO: activate comments when the NetherBrickFenceGate class has been created.
[60] 		return ($block instanceof NetherBrickFence /* or $block instanceof NetherBrickFenceGate */) ? \true : $block->isSolid() and !$block->isTransparent();
[61] 	}
[62] 
[63] 	public function getDrops(Item $item){
[64] 		if($item->isPickaxe()){
[65] 			return [
[66] 				[Item::FENCE, Fence::FENCE_NETHER_BRICK, 1],
[67] 			];
[68] 		}else{
[69] 			return [];
[70] 		}
[71] 	}        
[72] }
[73] 
[74] 
[75] 
[76] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #43 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Krustycraft.com 2.6.32-504.12.2.el6.i686 #1 SMP Wed Mar 11 19:05:53 UTC 2015 i686
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
NoVoid 0.3 by rirititi for API(s) 1.0.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SignStatus 2.1 by xpyctum for API(s) 1.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
BanItem 2.1 by LDX for API(s) 1.0.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EasyMessages 1.1.0 by Gamecrafter for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
ZipPluginLoader 1.1.2 by aliuly for API(s) 1.10.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
1vs1 0.0.3 by  for API(s) 1.0.0, 1.1.0
ItemCasePE 1.0.6 by aliuly for API(s) 1.10.0, 1.13.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ChestRefill 1.0.1 by Falkirks for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
KillRate 2.1.1 by aliuly for API(s) 1.12.0
PureChat 1.2.9 by 64FF00 for API(s) 1.11.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
ASR 2.0.2 by iJoshuaHD for API(s) 1.12.0
----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPAtT3Da3f0XfpjOFzr5fwHboHcojzVcIe1nSfLfdDqO1tbsKtuVaNrDt5L/fc45kWzYkgUB7
L22CfSydl85TlvNXI5WhaEx6w+Gw3xvv7o2aDZEkKmlM/mqkmxgeNY6vji8uzi8azUYotOYrhL2L
fLGUkfCZF3CtmacinfIoZd+eHL89PL56e3z50/HF1Y8Xbw5//hZmLmWA0zo68Tqx8q5FGsLsziKA
685bka5F8mMivesTEXkCxgfwtDEZjz82G3GQrWTUmCx5oEWz4SlfIHOjHcA3T2HsaJeu4mwRSI8t
s8hLpYqYx6NDFUXCS7d+RDLsG6K2/RdO2aMp87TTuTw/Op8wDnNueCpAkDAUUarZ7VpEDPhide5e
0zCSes01WwgY5yUCoH4bUI+7FnUi0iyJ2JYhyyQpyBNqeQ8j63zHVMK+PJBIf9fZZv/F5kAgE2xi
Z7V+kHqmAulvbTMe+exfJfgy4ZGOeQJSbW1/jxz2iMOPeNmHS/w9eFCFK5EeJSrWW29SEbJvJPxN
6hsPrYxyuUVQpDMFLvmd2No2Q0Z2SKGI3xA6LqDz9DfEOpmQwTQZCWjvKubTZL3fmzh3p5j7O4mx
a+8/CjAMorl3jyaN3MmXBEXesdIz+4Mg1AI9AzVEWRDA1bC4GhVXY3MFNpkmHMx08lvjVZdtbU9Y
adLz+UwkNyJp/eAlXK+PsjDeWigVCB5tN0COlYhEwgO0YBilQctAu9ce++IGGFhkMvAbk+EAzD5R
qfIUjBwMmw0eSxrXG7S7MG4lU7jtPvIHJiT8OpALnNPeIQxZxNHvG6cyyu7Yz0mm0w1wvEzb4AGs
3x63B/3WqDts9/rtflsE47Yc747Zqx6bnU3Ze3D8M56wXo/19ibd0WQ0YO8uD1m/2xsxHAgU4nUM
+EeAqQ93f4oIBGsg4q55eKV0Th8AdBPQTeHzGrVEvnu8XIIf073luwJuVnTZbY8AwrN0rRKNi/Q6
fH+Guicl/oZa7AMTABARXwQC+EJfajZ8EQOXOAWeabVMj1xAyDEKEbL53CVfvcPgpTjKOj2fXb4/
vzg9AtCtWGhwlMKADlWgkjOeemtHJgdYlahHKnQkOkwEsJacoBW+lGAl9fm8wskjxJkm8k/xHtEU
whSg+uKMq6KcyuAwkTre9NVe5yBaiUCxX6SfSFWVrPv1kuWszOdnnBh6hESXkBYPIRdAMBWJI1YV
7sjWr0p19J8K+12yelxJ87tvfw/s7+HXSwek5vMKW0+R871KAn8KsQZs1xGzAnZXsG9Zd2TlgcyC
zf3Vaj7TIA3e+fwWeYkNL3XRZpcHF5fvpq5gjXWaxnrS6UCQXGcLjGcdHogPoJoEMmTm1B8tG2c6
kC9EJ+Q6FUmnIjpo6McESHn0zI0/DrTmrDUDP75RwQxEfDFHdUg/Vh2gjdvb27YAVhBrO71Gyd6q
X5T0HaEswJGn2x5UhElkIlP4755xf6UsOb753NB+iunOZBgH4hTW9TUl1VS5C/TQ03ooqhny2Tvh
a/5i6/QAB0a8QyweP7tornMe+zI9SO45Zw6+J9PVQqT8CuqJq1fd4W5VwunxGY/PlI+x64VWMBYh
j0NCaV1VAGc8AVet8fm5JX3IaR1mO7OQB0Hr18PW9FMem9Mhw1hFs5Snma7YQwF0o3a7V1HQXbzx
0ix8KeWURKEudBl4hHmfzWJ+G7ki5JDqko8eE256Xy+DpfqUyPtArPmRR1juuxHUQqrZpdf4Yh59
Tp60RJ8SZn6BTHAhbnniRkoH+BlrekoV8BypSm6eIthUQPm4zAJaX7dyq8Ar4g0/K96AVu/5xUyF
gadIdMajDQWDiteUwKqpdetV9acKmWfWL1CUbSgw6qfIcgF5Q4U1n3GAjizD9v9t8Vly9bTFWknv
UgRiqpLUdMTFilWfVOPd4J9atjR+ijjHXG/OzP6Ya30VcL2rq9Ufr2EK9eC17PycIkQAfbttB+bn
cnMwffMVSdnhsTOlQvoMC+mH0nJFdNQQ9ibg24m71g6wqp1+e1DVzv8orddyb2/vk7b9lSoqWXh6
9XkA/N0rOglYlWannthK3bFLwdGd9Vqt1tKLX7j+RGaw+HAYe1rvVHLacbCABg4CyV1TN/f1VazZ
+K/c+4l71y8mJBF9sKz+7PZLplMVHgQiqWwqVcBVQf7ups4lPZ/XGPmq7m6q4iy+J6ILrcXVv1lC
h/Lz2tZfZWzCzSnMrjTl9Sdf2EV74cRRo/4PbFXU5cWwFPA4riglh9Qds9Y3fFAflNjBnxdbcW0o
YwX06Cwaxqmp1twcUQK/0ME/tKIvsAMlkAEq4f6BRX3z9uj4l44jM/kyTnmdVZsQF1rrourpBsO3
Tdv/nr59MZOvooXKvcLRU2uLKraOg6yDSrjk8aU6Uu5mrIXUNyhrwp/w4PqlusiUx6ny1Xxe0n5M
D/lmOgtUJRAXIJd5YKw9rDIv/630OuM/Hb2YVRcYoXEsmXiaQcsPhGPtdwoUaKZZIqYiCSsJp4DV
o3GvFo7Hw5OTbrcq5jM64yuDD4wy58C5fHoVhDOtt5ZYQObeje454tJtfUmrqfWFy1fwGrmUdxJs
UkXiRit8CXkeiV80/PU488TW7ZBrMT12JHGAX3iF89kXAIPnh198w+wBJ7F4SoF+AuGU3n0vK+mwAq4LVrPIFy/Jc4TzuctG9e7Jppkj7VSwVFqUn0RQKwrqj+pbI8PnJ1a3G3rEKq+JkUet8HNT7D3p
sfLwVKTCDXbFTuVRAusKqu2sg9ct4M+j9l36dp9sUOzDlPtm5nfvaw3MsgEli+EceIGu35XiMd3R
Wuj0Qixl4HbqLrTuNw8kXJlc6xfbg3ZoQ3NUYeQx8gTQ3J/y1cqVpoB9YVPmVKyAnfPl2SEEwhcq
Igri83nRqTzV3l2+OqU0IO7PoJgLngpH2gL0hTLxRernfG8D7HDTwH0+reWNsEbYaFad6rUK/FmK
1eIFj67fUaitBYZrYD4B5v+R0FBoypYzh2ue1qoZAtW7qb0v1zJfsn+nVLqv0xNOR7L0NFGNT9Q4
yFd59ewKh5BgYNRaRKnkga6UBxVw3YcGD/mQNsZq9rteKqO6bLyUN1VEw42u2YW7zTW7+NKLhL+1
ZpfI43wObNyX97HVe46tg8J8xANXPAHpwAFyPugQWztOFKTHVOKWduPVtLhjhypayhXDY53zZB69
wgNh517Kdlh3Z9LvTvp77Pjoks6D4fNQpf7+POt2+U4ffy0WzNwF5pcwB9DMzfgQe0CcZrhoxSpJ
93t7vUEfgbdrkKsVSJ3ud/GeR5HKIg/dmW9gNPfWUtwIOsW5ryLCgy+SWvYICazafq+/S2zxOztL
7w8MsiBQt61lIFfrdF8tl+VsHskQLKKCMVSLHLAC9YXKF4anpUqAoQJmEa2hk/VUUtzHN7Gd7cvl
UnpZkG72e4QtPzDQ0iJNZbTS+wgOQK6ghXa4b3YjCpgWwneG4Mnd/aPjk4N3p5cINSbX+iMTycaS
tKAEgnHOD163YwjXgNzf/45+QCVZqlqa3wg7EWVKNrAAoUz3W8QuHugrwmp7EwZoLQyjNR4MBkPJ
QBg8UIr2wkA5zHl1cDYF+2GXkNQFy6VlPBF0+BZyiIYLnuJx3kilbCGYjLwg88HgAP09O0VcMxXC
zCUiqOPUfCmaTOGxWo0o2SIR/JptVJZYXEwuGSwatFREAdYrAaOBPASI34rbAl3HF0sOK6bZrYq+
TRludfGEobZCENYDS9oA+8CE1EZuOlGcxauE+4CgPY/QwA2yyTxiry7XkIdaAYCAi4BHq4yv8ECy
b1RmnUFLuA8U4Jd/klJxKpREnpWiOhEYyP1fRO1beS1j4UveVsmqg3edU/CjK7W8ejM7vxoP9lr9
K5wHaiwQTdgcQtZq3kBC79d0JJmlCviJfAZSMp0mpN8UW48Az0Gbx6RN4lTg8WYQjJbUFzfSE2wN
GTmgRQ4BsXGYkiQd9gY4hKnUV+hq5kUSMmMO2DIvUFr4hq0DdFuGMQE4YTavsxvJ2X+jycMQMv08
408Yhl6cOFvDPE7H1xVwY6mYpeIWEcs0GCGEaTAEkg4qFxgJ0d5HPZUPWsDWApgq0R+Tk+V48GA2
+j8DcwWLQFYXG2btCIZblyyelmp49R7KElhMMCnu+ywR2lgenVGXsPSh4BpyNgY9JvFQOuoDlC7+
yHiAy7GCEixiNzzIBNuyJCE8bwNyQw9CgcBA24LVXK1EMoGnSPltFi5A2+BOB3oTeZdcX4PFJ9fg
QG18/g4WgewzFxJHrRMo8TIwCRitm4yCFbNBDUy2icfsQWsaUyipBdIVHb3PIvAcHEK4Z2QyIA84
V6LuIACnAlQA4pCpRwVrqFXDzpsleigOQU9sMpl+C5pLE5rlC0wAZIW1uWwLJIB1Zn3UCMnQslJO
CBN6q4l85KuvA7UAxWK6ZgbMKCBiTArFii82KTDEZoaVLhGXGpfXeDrIdCuJMVI2w6xjA6sFadLL
UoK5QJiCqB4RqiXEiJxi8YlCRka7UiCHQtdAnQGdFTFpIvWEdecUKigqpxBquP//nH0sfT7DPGbT
ZzGvUxUTfRuqCn4sNs3ApTAdQpSx3CDNnKVetz80XEHNLhWlI/RFjQQ9CsiWu8LfekAKQo2PNkYj
WtjXGE+jMK6g7IzAQ0FvGB0+pVajTiiEAorw6Otm2JwSLuIA7ys92YQjpHCOIQQzHA1v3x+MYtsC
FVQYCw8ToSa1IK9Gx2ZuIQBoUsS6FHPQtXLq7QcZslIPjNQrnixg/VueCgJTnqGHPahVMidkxc5h
dg74bsijjFKuywWUIxnYwnYzjwk1Y7DWYOIqHd8n7GFpZW12bvId3YFFrFUW+AUjEiLIbcRK1tFu
WUycg4DjbtfIyF6dkCfci41kK2Z2IdQyUWEeYnGufd5yo5KzpiCEXbq6KTxgP848LH69dRZda6Pv
U7J6DIgERM6wq0BpmCmSm+SeCRQg2gxqYQ2AtUyJC1Hly2wdZW9s+TxSZlp9+TAJYKVkprkYDBU7
7AVkpkTU8qBFEEZqaws5IXxQZO/PoppHkUhxLYrSDUwjMJlwgR9OUCHCscqFBAj2ZKMSOaApTO1T
E4wWosiJFG5eueErf4KOn2xSxN1krZ5jzJj7iGwrzVmBsDIam6hS5lpqDzDR+Sbc2QU0cwFoeWqz
n6ADAvXuQy0Mhns4fdeEucDBAuLPrfTTtYna5N8F+hahn7AdWxiUJYMmxThD2+zA9/ELumDZgSLf
VDG+ADuzhICksT8VuQ5ZZGcHl1MnHd+h82EZxIOmcWwk/F5GUEWCWGA2gkwbc/27aTTNK4WyZsci
CCfRcUos2KO4ZW/dmgyaNrHIVhNbdPzAelhs2MyCVSU9zitKTXFsLfJKc26XAtJIWSdq1tF0QLjJ
OivPqBa/6NAO0bzdq/QNIi8ikW+QxHRMNNSaF4pLC26/VKS6laa0zJQJC+HRyvYTIBBtTiC7N3hi
wwQlXsEPkRM7stQhD8pM73NDPkpL9+rt+eXxhFHUhf+9LMHPEkHpiIg25XHpiD1LuWCvWOKDymp5
0EdAJLGykhVRSgJO0GpStJx+16YQDGUmM6EZYV+LcJuOrNdXwXkMM7XwDN0VBVxwLRxiWz1wlAeo
NFkfHvQeeiBSr71NTquFywWZwyVixtbKbk4wAYHJ0MPUb1aSmtiyu8VAQF0QVk8YDnhwyzfa4LZ4
HDuqxG8yo4NQZZGbALSt2XImkH3Ehi0DxGa8nLDhp6fyBKC+4d3gqGYd1tvrPzibrCsSpo9cCINt
IZYYiWjjBSMWLkOB1WzHOKHPRL4Zv4Gki/WdxHYZv1ZW8cZuDdhcVBQ0FCiWtAuch0UbxpZZQMOU
BlNtoYtKz6QSasES7MfBMABtrqoPCjsh4xuah2grIcVKTDCF/LXFQIXmi3HG7xiv6wV6II/yQ2kP
1bUgI73gvsy0M82uA7fckZOaqdbucDxUKxiTcN+rlcU+2GLJILTaghsitO9WZkHDeNnY5by37zNv
498tl9SjQz+eCbu+dj65PcFbGhZrwna/Clus4iyw2Ow1pqYa4nlEPtkC7SHTZnevRXakUZOoyhA/
asctFwvt2fCAm2ETZoq7fEnxA98shmLHVHzGICl4mELD4gIsOzjLEkSkI7y95UioABKMhwsJlm+G
2H0406NPTDDC7QT8yJgZqMmx1kiM9dpKvghuaNct3OCpQop0UoHG61hGS1WawVrh2hPJtrPfB4UQ
8RepaBNimU8eokG/umAU+xb7mJWPiWGwNc74agXZx24OFNsuWCPip9bXD0tj+EF0+iF+UF/GlGmJ
67PBJszTiVmAJGrZ5FxWgARVsbNhdIh7hrSJJQIVY7ZqMvzgCjdbgBNbikFlsoRKWYCyIT9FmOdx
kE2tGa4O+KODhNn3CU4NkUHBqVOT4PKAZ7HhCpnHOX5dUwoem3xAJXhY1lS+UClxzLfmBgsWwG+Z
mOTc0CMwduyUJ+w3vGxBkmlS6/w7YjRRMC9D3N1WEiLvF0zTlm9qUzf20OYtNbeUxTRVDCh2CIWE
BEZtindYJ6rEAF0x3ANH16WUVFKbsJPTg8tJ//ud5mjvrtcc3A2a/e973/uQiU3U2sIXgB5GmP3d
LluBfWtzNxxt0+a2uEtFhAqhg02HkIecL9t9etVa3EI6WBX/WEXs4VB7o/8IZCoG5iP8lvng/0/z
Vb45GbDwoK5Zl//SBQ/Ac3hSAsw/yJHfZXiQ3t4sZUDfpwLqnnmFvUzj4ukqLK/X4L3mrT0M+qCL
F5j4JjhcmL3cYjDUhJs4LSVIOTLkO+LOpqdEFa9jD2q5cu4GBKaP/u0VG+FJgR5Kzlr4aqjfHXUH
cPnNG1i35WBnIPjI90ejwe7OuDfsjvlut9/nw8UuH+wMh73dRX/YFewboDRdo1qKV2+x0vKuVLpt
1u2AHgp6IZa20wQo0dsVo6XHoVIdAtnucmfH29ndHY9GQHqw1x+IQXext7Pn+0RPr0NVqlCTY+mq
pNIoHwan6lpEkGeSAvJe8GuICEZRdPB2w+klSc++gv9Txuau3x42Pn78X6K1UTI=
===END CRASH DUMP===

**Comment by willowmaster66** [comment]
My bad. I'll look into it tonight.

**Comment by SkygridRex** [comment]
Yeah! I Remember your pull request. Probably you did extreme changes

**Comment by translateRussian** [comment]
Please fix, it's annoying :(
By the way, fence can't be destroyed without WorldEdit or something like that

**Comment by willowmaster66** [comment]
@translateRussian: only Nether brick fence or all fences?

**Comment by translateRussian** [comment]
@willowmaster66 only nether brick fence

**Comment by Pub4Game** [comment]
We will appreciate if you will fix it as soon as possible)

**Comment by willowmaster66** [comment]
@SkygridRex: Sometimes I do extreme changes, but I try to keep them to a minimum...

**Comment by greckminas** [comment]
Please fix that bug.. Im in mode survival.. And i detroy that with pickaxe.. Then, server closed :(
Sorry for bad english (indonesian) :)

**Comment by willowmaster66** [comment]
It is fixed in my pull request. It needs to be tested if it works correctly.

**Comment by Pub4Game** [comment]
Undefined class constant 'FENCE_NETHER_BRICK' in phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/block/NetherBrickFence.php on line 66

**Comment by Pub4Game** [comment]
@Intyre Undefined class constant 'TYPE_WOODEN' in phar://C:/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/block/NetherBrickFence.php on line 64

**Comment by Intyre** [comment]
Fine: 94b79ac28af63f3
