### ISSUE TITLE
Crash when player gets kicked with custom message..

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3574]
PocketMine-MP Crash Dump Fri Oct 9 12:54:00 BST 2015

Error: Call to a member function setHeldItemSlot() on null
File: /src/pocketmine/Player__32bit
Line: 1772
Type: E_ERROR

Code:
[1763] 				if($ev->isCancelled()){
[1764] 					$this->close($this->getLeaveMessage(), $ev->getKickMessage());
[1765] 
[1766] 					break;
[1767] 				}
[1768] 
[1769] 				if($this->isCreative()){
[1770] 					$this->inventory->setHeldItemSlot(0);
[1771] 				}else{
[1772] 					$this->inventory->setHeldItemSlot($this->inventory->getHotbarSlotIndex(0));
[1773] 				}
[1774] 
[1775] 				$pk = new PlayStatusPacket();
[1776] 				$pk->status = PlayStatusPacket::LOGIN_SUCCESS;
[1777] 				$this->dataPacket($pk->setChannel(Network::CHANNEL_PRIORITY));
[1778] 
[1779] 				if($this->spawnPosition === \null and isset($this->namedtag->SpawnLevel) and ($level = $this->server->getLevelByName($this->namedtag["SpawnLevel"])) instanceof Level){
[1780] 					$this->spawnPosition = new Position($this->namedtag["SpawnX"], $this->namedtag["SpawnY"], $this->namedtag["SpawnZ"], $level);
[1781] 				}
[1782] 

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /src/pocketmine/network/Network(228): pocketmine\Player->handleDataPacket()
#2 /src/pocketmine/Player__32bit(1597): pocketmine\network\Network->processBatch()
#3 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket()
#4 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated()
#5 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket()
#6 /src/pocketmine/network/Network(146): pocketmine\network\RakLibInterface->process()
#7 /src/pocketmine/Server__32bit(2485): pocketmine\network\Network->processInterfaces()
#8 /src/pocketmine/Server__32bit(2300): pocketmine\Server->tick()
#9 /src/pocketmine/Server__32bit(2178): pocketmine\Server->tickProcessor()
#10 /src/pocketmine/Server__32bit(1778): pocketmine\Server->start()
#11 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#12 (1): ()
#13 (0): {main}()

PocketMine-MP version: 1.5dev #1264 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT WIN-PPP21SHRN0I 6.3 build 9200 (Windows Server 2012 R2 Standard Edition) i586
PHP Version: 5.6.4
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AdvancedKits 3.1 by luca28pet for API(s) 1.12.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
AutoUpdater 1.1 by EvolSoft for API(s) 1.8.0
BlockLogger 1.0.0 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
BulkCommands 1.0-build#007 by PEMapModder for API(s) 1.6.0
Cameraman 1.0 by ChalkPE for API(s) 1.12.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
CommandRepeater 1.0.1 by iksaku for API(s) 1.8.0
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
CreativeItemsPlus 1.0.0 by MCPEPIG for API(s) 1.0.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
EnderPearl 1.2.3 by Yosshi999 for API(s) 1.0.0, 1.1.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
HideTag 1 by Wantedkillers (Author), SenorContento (Editor) for API(s) 1.10.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
InstantBreak 2.1.0 by kvetinac97 for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
ItemSneaking 1.3.0 by GmWM for API(s) 1.12.0
JoinCommands 1.4.1 by PixelGuy75 for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
NameCorrector 1.0.0#build010 by PEMapModder for API(s) 1.8.0
OneHitKill 1.0.1 by 64FF00 for API(s) 1.9.0
PerWorldAlerts 1.1 by EvolSoft for API(s) 1.9.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
PlanB 1.2.0 by Gamecrafter for API(s) 1.10.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
PurePerms 1.1.10 by 64FF00 for API(s) 1.12.0
RealTime 2.1.1 by Guillaume351 for API(s) 1.0.0
ReasonWL 1.1 by CreeperFace for API(s) 1.12.0
ReportRTS 1.1.3 by ProjectInfinity for API(s) 1.9.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
SignModifier 1.0.0 by wolfdale for API(s) 1.3.1
SignShop 1.1.3 by xionbig, xionbig for API(s) 1.11.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
SkinTools 1 by Samueljh1 for API(s) 1.0.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
Specter 0.3 by Falkirks for API(s) 1.12.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.2.6 by 64FF00 for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
AreaEffects 1.0.0 by  for API(s) 1.0.0
ChairStairsPE 0.1.0 by thebigsmileXD for API(s) 1.0.0
ItemRiding 1.3.0 by thebigsmileXD for API(s) 1.12.0
OITCPE 1.0.0 by  for API(s) 1.0.0
ParcourPos 0.0.1 by thebigsmileXD for API(s) 1.0.0
PlayerStats 2.1 by xpyctum for API(s) 1.0.0
PocketJobs 2 by MinecrafterJPN for API(s) 1.10.0
SkyBlock 1.0.0 by thebigsmileXD for API(s) 1.12.0
SlapperWatch 0.1.0 by thebigsmileXD for API(s) 1.0.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0
VillagerTrade 0.1.0 by thebigsmileXD for API(s) 1.0.0
WolvesFortress 0.0.1 by  for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPQ1z2zayfwXndN45b/Qt2bLVcec5jpP46th6ltP0WnY8EAlJjPl1BGlb1+l/f7sLkAQoO5Zi
te9y14ZcEPuFxe5iAaG/72R+KHZG3cFg0D/s7g86jR2RpnG6M/p9J1sm0LRzenN6dXV5tdPYCYWU
fI6wEx4ELIsZZ6EIpyJlszxyMz+OmBTZBxF4Z5kIJ0Gc7b5mAIzyIID+Mz/Azm2Zuu0kdm9FFvqR
aI8DvhTpzU2/N/Uz+CwAILA0HPb+aOwkQT73o53RjAdSNHbc2BPIW3e43wdUTqb+5892vxN3zR98
ecIjVwSB8HZfv/4dkMGHA+NDJ/suW/iy+YMbxFLs6pe5yM4FvxMflYC7rxuM0AH8R9+9LcGvv1cY
9wCjetq3cE9TwW/1N0Oj5Q8FOii7HdZ4V2wA94Ag8+9Eyfyw8xjzfnQnoixOl80f6vruaB6HXZO+
AOVphL0NEa5+AVr5EGdTnmL7WeSJB6BakO2viD0cFGIP94zG75JbdsQicc9w/CcZz3I55mgUuwWu
fftz4I2+gm71LqPR+eX7s4ubyaeTk9PJRPc3h0CL4fGMayoKo8hOFjyKRLB7IbL7OL0djU4+HF9c
nJ7fjK/OLq/Orv9ZylaO3/Dx8ZMJv4/GsfRpJhwdHTHHQdNnPPKYL6UotRnxUHgZnzd/mGCfc3En
gtf02e53Ab6AjAVSkd6JVNsotLxZXkDnOqJfnZ0Kk7Pz2+vXzI9AXTAZ4hlT+JUBHDxqUTXW1bjo
16do/Qx0GuyJxn9+rfEX1UiSauUedFcM5wBNdQd8QJZyF2b9rzuvOqzuPCakHu08wA5HrGp0nIlW
nptyuXibh8nua0D9qruCJlKD39ZGsNvrHdRQKS/V/AGsxQvE28qOCGOPfdWr7Xb3Doc1hJqk42ia
zR+SNHbB1bzhmbtQaPtPMnrFb8/96VmUiXQG2tntDjobMTxQmFN+G/jTtjIyrcwP1KFk/bDzFOM1
HgpSp5HLE5kHPEMvjMT21hbjoAvEFFOOo7gqRlGzVVAxhdl/djy7g/21pdDDoFAPn7G43uBgb92B
LWlo3AfP4e53njLoDMKSQnL4HBKYSF9BMlasxameGc/NMHSDT6ADd5PqAemuzrAxPX6Ex93B/uAJ
FDc3bgxuK83dAlGP7aJJ6Lc+oyn+e8j96A+A/dbYmYtIpDzApABQSPBX4DW6rT1P3EGXae4HHiQT
vf0B5BJpnMVuDN/2ho0dnvj0ZbfX6sCXc8g9RjudNf9AB2Wl2Kc1JAw5ujl4/+xHXnwv2cU1+3x2
0RyPx73u5MPVReeM7bf6jFhih71Oh+0Wnyr5Wa8D8l71GIS2yOOpx0498sDgzPcO9oFEskiAwF5r
vzWAt3+LCGTb6cFrRzXexBIZOLu4uAYAvdxD9lTmURLVdOzdYVzwfvQzetdsW+BGpcx+qwvKyrNF
nEp0wkHu8t5BIjLUPinx10KLABARn0L2tTOCQYR8zRMJMIn9oE3Gs+ytCcBhrFF2nI8IhCww5ijc
+HJy/fny6vwtgO7FFCIS8rrIskSO2m0YtEU+bblx2C7ZaluCgOjHgc8tQem9YZmLsgFDyl+4+wE8
zPZkRKJKuJOAS/mMhJg2EOv3fCkpZloCVFBTjB6I0bPFGC/8wE/YBP6CtHq+NXESwis1WsfhxBJl
EY5zDoKJtJJwcn18df1p/Jh8eRZ/SiApE6kpnwG1h6lrS3d6FwcT4NAS6+AFg1QRrtvhIzKUVnh/
f98SwAqibWW3aHNvAvBu5/F8bglmQm3BOnX7O/eDk9SXybIXH7aPo7kIYvaT76V+bI9h59ulNbhZ
a9bpMYNusffuZ1ssgtTGqi7SIl76UdgdhC77L3ayhGXjST4VzQ8/smvBw62ZZkXGcabI2ezBcSoW
15EwD25P4jDkhLoS0wTXhq9JXv1VpzOszb/Tjzz5GHs4H0wB918w9UTIk5BQgoDAk6t5AiltDjd1
oQaz7UkIS/zmLyfNsQoc7SwVoh1yCXOjbdEBhZ2AglIOr4a2KlhNVbaCYPUV3I5Ptzb6LuJzHLeg
7jgmI89qBBRCGFqJIMEWQmbnmKiY09iE1sLIn+ufDMIv9E969K6ASM351lvqfqrmgv1byW/zrQlo
E9/ELemuE38eyVVxFNiQpWdJMeFhLoIvi64lyAt8a4kQ7M/gwHHC9QXStSCsxEiYhZZUK23PhJOP
J+PT8dn7bYmn0YFwdUY2GbK34u46BrM0BCtBtViyIlC1nFiNHpCxfqtgBX3HMThZY4qZXrTkrF3i
AGFPwyRbfo5TXI6U4hrAZwaQB34eLLfmJhU6xxHIwD0ysIlDMaTlgfgC1p3GgNBY7jWTR8LG2cXb
05/ahsyolgiizVjwNDDVUgHraXrfVss/YwlJ6OHh4YplN3QK8o0KqljYxKJPpRRR5vNAQkgz5DHB
9SypJtG5mCMzlzOcY9vNjEw2VrP0tdMExaFisG2JBhoQ5fv12NCABf56nrgtaU2SYOg2A2uM5Tsw
2uuUR3JmxUcLXJ+0tfgvF/F84bvJ1kawQOg4Jhv228ZTuEDatrCABt6nfPqGzw3hC0h91Tl83lmV
c7JbPGzBfc2Bnymff3PRYBPvVcgOivnge+LaUkwBMRRjV00+8ygT3i2sl6Gd7R5TCxa1JiKK05MY
WqMsZrtY8cGGbS3yLLoQ1jSjjqO4/arCVoLaZ57CAjSV7YUWF3ThI++gwE+GNiqYqY9W39LIO0iz
/fRWbmtd5LuKaO44Jv01ZvoZ7ZRkb3D3zpDCAtsWv7KMub0TmR9x93C4tbleoVwjNGtJ/HEaZ8LN
YtNjGUBTCsiSeC30vP3Z4v7w25kHVDAMJeFvnqCAp0lxxhACRwzSzRMuhRVlDWDdLx9s4J/6L3dL
IE7oAieJ2CR5oC3XCIwNC3W2WCXYFqxfN8P34eePWzNAROY4JvlNpPlH7EePFFEssC3NoL62HPsP
InifL4d721q3VBgdx+RkE8E+8kilr6ZYBtD2FJ16fveU7b3Q5EAMlcdvJAtuJZ/EaVp3GTZ8ZWny
iqpdnW5nvWLXCwoCFiOOU+drDREvI/HBz36EAGjIZwCfqW/sD96963S25RZvFDrHqRgwnzdO3RS6
toEBJB6LlEzxGEK+tcNTa9i8tP4CyW3aL6xeFchOFjx7RD4Cb16Ye8k0NEm/VLiAR29Mqej9me2q
9/Ctm/JZVpt6L5EpAcJTOkdA9DcN3QZLRk3k0XqyIoGy03fvc56aVRITWs/DamaLJDTRf4wvtqYK
Gy3oxOJoU83Y2NoGsnalhI9xJJYrSlBQUwmDVZ9VU0Ljz9KKwVKhkoK/rahEISONJIm1CNeAZ2pm
H8qdoMYYz9QIiank9vZAiQmUXDOzRjQa56kAXxFabrmE1Qsj9QD7SDB6iQBlNCo5MB43r3tiTz25
Kywg85XgwTUdMy1FLkHPTOf3kGcEPA9Ff29rpfmC9sab8dBRxtHnc1sOBbLWufbK/wQcHdjHOzzD
tq2RSzXdTXK9K5HEaXZ1PbH4L2DPVCVh9fUFkq6zaOZHfrbcWlZgo3WckiHjcT3x1BEaUIeZ5xlA
U8DOaqkuk+4iBa/Ddounbq//P3PgM0Drfr0t6yuwF2eekDfzec1NSswbClStSGQ4z3CHCbJvf+Zb
vtICP+Mx7+Ng5vFAbGs7xaS9ia1iv8kiTmpiEOgZS32AlqmPK+XiyZp0L9gSKDiA4ap4WWewNCM4
TjBrZStO5+2iwliiIqnDJBBYGrTkLoG25MOV5XJtS6yx/fpzxQwqwWDsm7fIDCylBs5hSf6ejvXZ
q9LHWp/b9/wkPMm3LL/FwaNh5OkK3eTWj+qbnhXsyfLxn7lBXZLfZHd6EvBaTlZA6iuVPXtEvsRf
YjHEP9vbFVGUN2I/gbBjs68hBvuddSrWmzNulMcNGRR5GI2SjzXEwDzmhA5bm9mVCV1JKXdWRNqW
SRlkHcfmYV1RVDnOGhcb/uQJjnrt2twCbpQr5qJkisXGl9W2LbY2CW3YMX1jHZUqQbVs2B4qWAxN
4R9Lyl4p3TeHaI3WcfCXYOkUT0wZ/Kwh0E9xJq7Evb1kN4DmkNVS400G7SWDVXGzyUhRQQf3445T
s8pkgVfCz81UZPzGE3c3rzqDg/Xqo50tHQak+q8AzniaOU6Nzz/tMKBFp1Cb3q2pq60A1/ePOxvs
z2xh25gUlShe/oJzL5boOrv9zNN6dksg26D26k5gu5qpH2awGF1VmwQmYRIlf8l2e6kRKzH+IIJa
1lFvqm+/DF5+jsrMwdewrgUx8hcpqSa9LjHVC+MFqJ6b7T9fX3puwWSUrx6zL/pVsASb2nmi7qQq
5gaHL6s6EZLSZFZmWQl8Zj9/W6lebYJNgvjeeLUOT1X6mWniOOOQYTXnLObX+e1IKvjpbAZT2frx
iwH9+tppWwWPhYC1rwz9QPz81nEM+hud7l1wP51k8C/7ZJ0Nt2s8K4NqsbLz58hnMbTp7v+V763u
/WvgMzv/T8v2koBZE65iZxPJLs+uT6xB04D/D/NTpDfhfsxTN87TcWyV7Ctgva7Y/ettruJmI8Ho
98H4K3pp7zaW0K9k7g/J0s3ycGvnMiqqxQ+XCxbWkYSC5D/iqVzZLyPgk4vGl+yLWRtyG28dar62
sk1GuKi0tKSfdFmVJQ16pkz2l3iPgpn1j7PpktJn3LxbrTQp8H+Azzf52ajKDfFczCzXWIK+ecC2
KJbmZRORfsL9urlIIcnxzJKUDf8PGDOLoc2qAsGdkO/iFPJwKa0FrtXw9bjw5whls7C+VPj7cJ6C
GOBXCoq0I9WCRTJYduYL/Cn5q3H5xk7iaObPGV7p46RO9Opd6rNLN2OHrNsb7XVH3T57M7nGX7Tv
YTveJXTUwSd9nwkq7cjmFyytaveTI1j8Dvdavd5+q9vvG024LXjUPez2ewgMRYi30gR+6GdHCJhz
BHmaXMgfYOWEAUUedRUD+CPlpl79w/hQp/sFaAOQyEx1U4PR/Fcu0uVRHBkgCLXRUTybEfI4846c
vNPhw0D91dF/D/TfImDqYQqJe5ZHc8nTqQBa0d/YUz3U3ykS4FEU55ErtAhN7i58cSdCWDXIggke
wKKiOQv8+SLTrCoReeSHsLQovlPAEIJFAZnFKaAu9aWhC556bpyW78ldotF6/mzmu3mQLY+6pOli
D6QpRZZBViiPet8PG/u9h36j9z19Qle8qMGGGFZBpBDeUfVK5vHu/PgaQajhVsKlvI9T7+i/6Q+I
mWdxU/I7oZnBCw/KxXFrGQZooAwtnrlkmzmwhpfZoIkyEJUZh5A+jsFk2fVCSMEK3hlPBYMJxSCi
S3jgGXNR/xmbCuZHbpB7woMHtjI1ENckDqHnDBHUcUo+Ew0WQ0sqESWja6LYElI2jYv5MxaqbVKk
4KoTjsESEV+I+xJd2xMzDvqX7D6O/p4xDDs8ZaiaEIR1wRSWeN8W3rqj5L5fiIjlyRy8HCBoORHO
IoVs5ETs1fUiFWD3AAIuAh7Nc3CKDG/ZIpXpGSd9eIfQzQP/36RU7HqyEK6Wwu4IDBSpi4ha9/6t
nwjP57TtiW/tc5hmN/Hs5mxyebPfP2z2brAfqLFENGIOOMDc2UFCnxcCdYf3jcFy2WN495jMUtJv
hotpumlGNZM2iVPgA55ERkPqiTvfFUzdHIOQEBAr869Iot8FsFzkmRfjVFHXfiEveoo6eW+4Pyhn
tA8K8oGheSB8d8H+nafYMnPd22Jy6x7FjHaitzy6BdWq71LgC+zpJ7CLDCFiEHmRL/+mxD7Gec3Q
JYGkTFd/2J3P2f+iV4JPyDsVdaGS/1eTBfTjOAtkDNJqMZQpcI2I5RKMHGIMGBpp73h8Bl9CePJw
HKqGJih0GstKPa9OyQ8WePDOKvQWDKYDWByyOl0ybafwufaaZeuI0U1uNK4QgsFYwGS55zGIAMqy
kU28mQbY4TJPydkxsOepQH3AoIp/5Zxun5v7d/DtHQ9ywXY1SYg4rwG5ogfemg6RNMFa8JqDEbQi
5YucLq2D6Xosl5F7zeUtw5t6YCBa2P5JgkbQ/gsh8atFGoMzBpODr2WDUQ2ZaRcIU6IBaggTjGPo
dFAtEGMRFuYRzEz8hHBPyCRBHpi8afwALjoToAIQh6ZSVLKGWlXsnM3QA9B9ezDTG8zP/o7X76XU
yxMYx8jKa33ZLkgA48x6qBGSoamlHBEm9AYqfJIveB/EU1As5hpMgRlFVfR5oZjz6TIDhthEsdIh
4r7E4VWeBGS694kxUjbDsKSjswZJ0svMB3MBNyjwRjnEMgMfVFBUww/C5GS08xjkiHFSo86AzpyY
VOF+xDoOuSLy+hm4Mu79h7OPedtXmMfY+yLmZRYnRF+7wpIfjU0ymFIYW4VXcIM0ayyNRerHFOtw
Ikqk5pK316yVk60LdMDPeGhg9EUTJgP4im5HY8Kdbj+C+QlaQ9/wlFKVMiELCyh+4ExXnzkUzhEH
zL1qHitnhBQu0YFg/KTPW6sfo9A6twYFJsLFMCtJKcis0rDqW0oAehSJrOTsd7Sg8vWjDGmx+0rq
OeR4MPpNNw4ClWPi/HpUrWRMyIruw3QfmLkhj3IK6CYXkOzkYAmvG4VHqJmCtgXlVanMStjDysZa
7FJFU3oDe1jEeeCVjEBMg9jHKtbRallCnIOA+x09suzVO5oHK56RjEX1LoWapXFYOFjsq9ubpk8y
xhSE0ENXN4VH7Mfoh7m+u8ijW6n0fU42j+6QgMgZLoVQGqYS6gZNzhTSG6k+amKGgZlShQtRFcOs
p8nhvubzbay61YcPQwDmYaqbiUFR0Z9tQWYKQ02X4+lmklrbQkEIG8rY/VVUTqQvrisTQzCNQMXB
KZY2KA2hW/cg/IE9aZ9EE1ClvbpVuaKpKCMiOZtXpvMqWnDip8sMcTdYs2sYM0Y+ItvMClYgfO/t
K69SRVp1XWaOEZucnR5A1ReAmqcW+wALJFDvEWTaYLgn408N6AscTMH/3PtetlA+m+Z3ib5J6Eds
qNOCKmGQpBjj0xY79mA+LXgwa8MSQuUwngA704SApLK/ODInZBmbDVxGlnT6gJMPkyAeNNTERsL6
5rgWA7MRZNoY6T+No3GRJ1QrAkyBsBMdgMDlQJQ09auZkcECT0zz+UinHD+wLqYaOq5gTknNRT4p
yY8tRJFnOnooKIgUWaJkbXVna4O1565SLf3grjK7Yj1oLUpEkUEi2yCIWo7Rp9q6UFoabxdvICED
012aqsuIhdA014sVkIfKKsjtHf4CSfkkbuEHx4nLvcwgD7rMVrmhKUoj9+ri8vp0xMjpwv/dHFZu
EazcCBFt2OHIEXuacsleOcLH1mC5sEgBR6JlJSOiiAScoNFkaDi9jo4g6MlUYEIrwhUywnU00pPe
BhcuTCXCE5ytKOCUS2EQ2+3CPHmESoP1oKH7WIPI3NZrmrNSmFx0aUQRM67bdCmGCfBLih5GfjWS
tEKuls7oB2gJhKkTegN1x5zCrfEYtmu5bzKj4zDOI9P/S52wFUwg+4gN1wvgmvFxxAZPd+UpQD3F
u8JhBx3WPew92pusKxJqkToVCttUzNARUVkGHRYOQ4lVFWsMz6cc34TfQczF5M7HtbjAtVey1HUH
HYrKfIb8xIwOChReUXuxWR7QZ7EEU23iDPVdFUlo/ZXiYh8MA9AWqvoS4zJIzQ3JQ7SVkFwlxpdS
/tpgoEKLwfjIHxiv60Xfiyq8yh7ssSAjveKen0ujmx4HrrmjSaq6arvD7yFZQZeEVbFmTnf6VUtk
NxBc0aCSX+WMFN/Voq5gvbXKu/Z+99yn9TmsxXOhh1f3p1lP8KaEsRqxg2/ClsSJuksXVaOeMTDV
EDsRTckmKA+ZVrW/JpmRREWiJkO8WxXLORra1d4Bq2ojplK7YkRBQ1GeQKqj8j1lj+Q7VJqhcQGW
PXzVtUbl/EEMJGPDeDj1weyB6h4iJK+kVucj5YmwkIDXNDMFVfFVW4gyXZ3FV5Ua6NPE0pENKWOJ
BU0WiR/N4srvLmIceavI3Ib4RsxFcbQMMb+nuSFBtbLkEhcsuplVzcQt3i7O+HwOcUfXBMpqCyaH
eI/1bU0UmxvEJ1tGXRNSslJbyoppeFe6g0Go5pHSfxo1dVyukj+CxolRKTrBYiRVx0QQJxipGgzP
L2KVBVjRWRgkJTNIkgXoWl2VPtKNOrDmODwwGw00TO99GAlEDtmmzFR4K9ydxodDpJoLChWPSi/4
c5dHtIJ3qqq0F/wknnocsV/RmJsQOGCFBIvJKJu6xe269IVAR5xT/gphDJfLv+GKLXRHrCiEq5TC
vxPUIBOziY5p07F/ajNb8vTOv+MBNXCjgXu4ts1Tha4zwn702MVHlx57+MjpsT9SRFH2fAoCQZ8G
CyEMJghoqNCATN/yNECBmWQ/wqOSCV5cemW3Od75citu5W+oLOXei/zKrFHT+BTrILUYLQr7tMp8
rORNi3YKz5JSIRzREDIkHzIenbuo5JVjDkRUiQF6Ylj9R6dEsbaiNmK4BTDCPYS9w4duo6/2Eb73
IMVQ/ngXD7+56DuPDjpsDu5CqrfBHuYedCXuvQjQDlBDsZ+5+rEYnuKV9jbxZaexIx4yEaG50nbe
CURl45LlqQu52aL6D1BwMCqPpxVA/Wcy9BtOQaMzhNJ52TbzA/rJAW55qj3PWZaUrQtwfeUFmXiX
zV3Z9EWWB/ZwFxHy2mWSla2T8TnhxB+0xd7ULZEkbloxdiVmemEK7d+dgfqnPd7vdPYO9g8OuLt3
0HGnvYODvjvowb+6hzOvIzodb6+/x77DXxKpdUmJTuobqg1Zw6X8V0AXUusn8K0oaRP8AmvS3dad
vU4fHon8rD/sC77neXt7/YPhfnfQ2ecHnV6PD6YHvD8cDLoH096gI4h8Ft+KCEKd1h7efe0nxe3d
dBW2uopbnSSG5wfcDyrGJA6xqdPpd7u9Q2gfv73Uu+oDdUv4eIEDSsdFUYvqpN3PH89Lavee91Di
M3HDM67hDMYAcp/6mQH5LPgtuFA1SHTkEpYJFQrSll9+jS+Z6Kt7xZuKP0muT1Zdpmr/owQsOe1/
FT/wSHRxR8tEPyOGldeNF2f4W8GCVKhsTuP4BSPw5ZjiP3wyRPUg/Xd4GOGB1n76tPb+zh9//B9z
iCgW
===END CRASH DUMP===

**Comment by Gamecrafter** [comment]
@thebigsmileXD Remove all your plugins except for the plugin that sets the custom message. See if you still get the error.

**Comment by MagicDroidX** [comment]
STOP opening issue about crash, this is not a forum, you can report it in forum, not here.

**Comment by thebigsmileXD** [comment]
Hue?! Crashes are bugs! And i'll check if its actually caused by the plugin, but i don't think so. I often see calculate on null errors.

**Comment by MagicDroidX** [comment]
Try delete all 32bit and 64bit php files.

**Comment by thebigsmileXD** [comment]
What the?!
What files??
The plugins are always for both versions, the server also and that isnt even the error!

**Comment by MagicDroidX** [comment]
Unpack the phar and delete files and pack it again or just run unpackaged software.

**Comment by PEMapModder** [comment]
@MagicDroidX this is not a forum. This issue has definitely nothing to do with 32/64-bit specific things.

**Comment by MagicDroidX** [comment]
@PEMapModder :)

**Comment by thebigsmileXD** [comment]
Thanks PEMapModder.

**Comment by SkygridRex** [comment]
This sounds EssentialsPE!
(If dont understand)
Caused by EssentialsPE!

**Comment by TahaTheHacker** [comment]
@SkygridRex No. Read the whole error and the backtrace.

**Comment by willowmaster66** [comment]
What command is used to kick the user? How can we reproduce this?

**Comment by thebigsmileXD** [comment]
They are kicked by ReasonWL (because the normal whitelist is ***)

I bet its Player $player->kick(reason)

**Comment by SkygridRex** [comment]
ReasonWL its for put a custom message in the whitelist not for kick people
