### ISSUE TITLE
nonexistent crafting recipes and unaccessible items in creative

### ISSUE THREAD

**Issue by Draco0le0** [PocketMine/PocketMine-MP#3577]
I have no idea what is going on I can't select items when in creative, I am opped and crafting recipes like a bed are nonexistent so please help

**Comment by TahaTheHacker** [comment]
This Bug is reported, search Please.

**Comment by SkygridRex** [comment]
CraftingManager.php its empyte this cause that problem

**Comment by Intyre** [comment]
Fixed with a7413dac92.
