### ISSUE TITLE
Multicraft don't work.

### ISSUE THREAD

**Issue by csilvestree** [PocketMine/PocketMine-MP#3592]
I Use this tutorial to put pocketmine in my centos machine:
https://www.youtube.com/watch?v=1bd-_s3KJ6E
But when i try to start i receive this problem:
Server executable "/pocketmine/bin/php5/bin/php" not found, server startup might fail!
But in the archive have this way to php...

**Comment by thebigsmileXD** [comment]
How often do we have to say:
Its not the fault of PocketMine.

**Comment by csilvestree** [comment]
And you what you are the PocketMine?
I have a problem I'm doing something wrong and have come to look for help if the team only fixes bugs and nothing else no support all well but want to hear this team and not a nobody.

**Comment by MajikalPayton** [comment]
Please read https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue

**Comment by MajikalPayton** [comment]
Sorry for not including this in the comment above! If your question has to do with Multicraft or anything that falls under the 'plugin' category, ask the plugin creator. :)

**Comment by thebigsmileXD** [comment]
@MajikalPayton :+1:
