### ISSUE TITLE
RAKLIB THERAD

### ISSUE THREAD

**Issue by challabala1** [PocketMine/PocketMine-MP#3593]
I am trying to make a PE server because using leet SUCKS. So i did all the steps, i port fowarded and i even used that website that shows if you are online or not and it says it can see it. So i press the start and i get this

7:23:22 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
17:23:22 [INFO] Loading pocketmine.yml...
17:23:22 [INFO] Loading server properties...
17:23:22 [INFO] Starting Minecraft PE server on 0.0.0.0:19144
17:23:22 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
17:23:22 [INFO] PocketMine-MP is distributed under the LGPL License
17:23:22 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19144!
17:23:22 [CRITICAL] Perhaps a server is already running on that port?
17:23:22 [EMERGENCY] [RakLib Thread #2076] RakLib crashed!
17:23:24 [INFO] Preparing level "world"
17:23:25 [INFO] Default game type: SURVIVAL
17:23:25 [INFO] Done (3.307s)! For help, type "help" or "?"
17:23:25 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [10048]: Only one usage of each" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32rmitted.
17:23:25 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
17:23:25 [EMERGENCY] Please submit the "C:\Users\Bala\Desktop\pockect mine\PocketMine-MP\CrashDump_Mon_Oct_12-17.23.25-ACT_2015.log" file to the Bug Reporting page. Give as much info as you can.
17:23:26 [INFO] Unloading level "world"
bin\php\php.exe: Exit 1

any ideas

**Comment by Pub4Game** [comment]
Read this line..... "Perhaps a server is already running on that port?"

**Comment by MajikalPayton** [comment]
You need to either 1. Stop running two+ instances of pocketmine-mp or 2. Stop blocking UDP ports (just in case you are, for whatever reason...)
