### ISSUE TITLE
Upper IronDoorBlock drops bucket

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3594]
When you destroy the upper IronDoorBlock, it drops an empty bucket, the lower IronDoorBlock remains.
When you destroy the lower IronDoorBlock you get an IronDoor item and the upper half is gone

**Comment by SkygridRex** [comment]
You are European?
Check IronDoor.php

**Comment by thebigsmileXD** [comment]
I checked it. Cant find any mistake.
The meta neither the dropped item get changed in any way

**Comment by SkygridRex** [comment]
Download another version

**Comment by thebigsmileXD** [comment]
You are so helpful :-1:

**Comment by SkygridRex** [comment]
?

**Comment by DiegoGTRatty** [comment]
SkygirdRex, have you tried breaking the TOP iron door?

**Comment by thebigsmileXD** [comment]
@SkygridRex I have the MOST LATEST build. I know it because its a build that was started because of my code. http://jenkins.pocketmine.net/job/PocketMine-MP-PR/371/?auto_refresh=false

**Comment by PEMapModder** [comment]
@skygridrex this is not a forum. Please stop commenting things irrelevant or not constructive to fixing the issue on PocketMine itself.

**Comment by SkygridRex** [comment]
@PEMapModder Let me in peace!
@ThebigsmileXD I'm not a soothsayer, did not know you were playing in PM 1.5, I thought you played in 1.6

**Comment by thebigsmileXD** [comment]
Dang it, haven't i said this?!
Also if not, you should already know it from the other issues by me..

**Comment by SkygridRex** [comment]
@thebigsmileXD you never say what version you are using and then, i try to guess the version you use

**Comment by thebigsmileXD** [comment]
@SkygridRex Actually.. @PEMapModder is right, this is not a forum! Your comments are never helpful.

**Comment by UltimateMcraft** [comment]
@thebigsmileXD  I'm not sure about this, maybe its the .php file???
Check it, I can't understand it.

Then do you make a pull request to fix it????

**Comment by thebigsmileXD** [comment]
Thats why i haven't made a pull request now.
I have no idea where the bug comes from.
Also the bottom block stays there.
