### ISSUE TITLE
Crafting items

### ISSUE THREAD

**Issue by Pub4Game** [PocketMine/PocketMine-MP#3605]
I can craft an unlimited number of picks,axes, armor resources aren't wasted.... PM 1.6 №48

The workbench is not crafted ID:5

**Comment by SkygridRex** [comment]
If you are playing in a bleeding build of PocketMine, please understand it's still develoment

**Comment by Pub4Game** [comment]
@SkygridRex I just reported the glitch! What would @Intyre fix it.

**Comment by UltimateMcraft** [comment]
@Pub4Game So if you craft, it won't take your resources away?

**Comment by Pub4Game** [comment]
@UltimateMcraft Yes, I can go to a workbench and craft there is unlimited pickaxe, but I should have a resources thing. 


Crafting a pickaxe for example, I have lost 2 sticks, and the iron will remain

**Comment by augesrob** [comment]
Yha there is a lot of craft bugs, any idea how long till its fixed?

**Comment by SkygridRex** [comment]
Not idea
