### ISSUE TITLE
Can't find server in MCPE 0.12.x

### ISSUE THREAD

**Issue by creeperboss900** [PocketMine/PocketMine-MP#3622]
I cannot find my server in the MCPE Server list on the same Wi-Fi and I have the 1.6 PocketMine-MP phar file 

Please help!

**Comment by thebigsmileXD** [comment]
Correct port? You have to add the server to the list like other servers. its not local multiplayer

**Comment by creeperboss900** [comment]
Yeah i port forwarded 19132 to my Wi-Fi and i tried to add it and it doesn't come up

**Comment by DJKai** [comment]
do you know where i can get pocket mine 1.6 with working creative and hunger?

**Comment by creeperboss900** [comment]
https://forums.pocketmine.net/threads/pocketmine-1-6-download-link-0-12-0-server.11189/ and override the other PocketMine-Mp.phar file
