### ISSUE TITLE
Can't Join my Pocketmine-MP server in MCPE 0.12.x (1.6 Dev) (PLEASE HELP BEFORE CLOSING!)

### ISSUE THREAD

**Issue by creeperboss900** [PocketMine/PocketMine-MP#3623]
I cannot Join my MCPE Server 0.12 1.6 Dev and I have Port Forwarded and have used my Public IP Address to add it...Please help!

**Comment by PEMapModder** [comment]
This is an issue tracker. If you need help, please use the forums or the IRC channel. Read https://GitHub.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue
