### ISSUE TITLE
Server crashes after a time...

### ISSUE THREAD

**Issue by Arken2013** [PocketMine/PocketMine-MP#3628]
Pls help! I don't know why its happening... Here is the crashl og! ===>(build48)
(The crash log is always the same...)

PocketMine-MP Crash Dump Mon Oct 19 01:35:15 CEST 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 448
Type: E_ERROR

Code:
[439] 		return $this->perm->isPermissionSet($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param permission\Permission|string $name
[444] 	 *
[445] 	 * @return bool
[446] 	 */
[447] 	public function hasPermission($name){
[448] 		return $this->perm->hasPermission($name);
[449] 	}
[450] 
[451] 	/**
[452] 	 * @param Plugin $plugin
[453] 	 * @param string $name
[454] 	 * @param bool   $value
[455] 	 *
[456] 	 * @return permission\PermissionAttachment
[457] 	 */
[458] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.0.31-ArchiKernel-g18e550e #1 SMP PREEMPT Thu Oct 1 04:14:08 CEST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
SexyMOTD 0.2 by hoyinm for API(s) 1.12.0
EssentialsPE 1.1.2 by LegendsOfMCPE Team for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
SimpleLandGenerator 1.0.0 by MUedsa for API(s) 1.12.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SignShop 1.1.3 by xionbig, xionbig for API(s) 1.11.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.8 by onebone for API(s) 1.12.0
EconomyProperty 2.0.5 by onebone for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
TimerBan 2.1 by onebone for API(s) 1.2.0, 1.2.1
BanItem 2.1 by LDX for API(s) 1.0.0
VoteBan 1.0.3 by GmWM for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
ReportRTS 1.1.3 by ProjectInfinity for API(s) 1.9.0
Rainbow_Effect 1.0.0 by LilCrispy2o9/Angelo Vidrio for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
Fireworks 1.2.0 by boybook for API(s) 1.8.0
OreBroadcast 0.0.1 by Falkirks for API(s) 1.9.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
Krypto 1.0.5 by XFuryMCPE for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
BlockLogger 1.0.0 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
FurnaceIndicator 1.2 by onebone for API(s) 1.6.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
Specter 0.3 by Falkirks for API(s) 1.12.0
PureChat 1.3.0 by 64FF00 for API(s) 1.11.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPIty4zaSv4KTp2pnUqKspx9KObVejyeZix3rLM/O1oVbLoiERIz5CkHaVnL59+tugCRIK2P5
sZXdqaRMNoBGv7vxoH7r5DISnelgPJ4MB4PRYNLtiCxLss70t06+TqGpc3p9enl5cdnpdiKhFF8h
7ISHIcsTxlkkooXI2LKIvVwmMQu4mokskkrB29t3DEBxEYYweilDHLqrMm83TbwbkUcyFruzkK9F
dn09Gi5kDt1CAHam4/HB791OGhYrGXemSx4q0e14iS+QsPHoEBC5uZtnIi+ymL3JA6mc71KY2PlO
WgTMRf72Tcwj8e5bQD0e92nc7/Q8gGd6GBJw95tv6G1Eb+wb9teUZzxiaYXMdWvE/6fyTMYrRshp
3NiMo5dJhcRQuEiSkFr2TMsuve3TW1osQun9kQw1/b9R/4Ov8L1plOb6sOZ60jdcTwY215Nhi+sZ
SZ69MRrALm3BtCUwGbc6IM+MsTe3PCx0j4klo8leW0abJX2c59wLIhHnNGrflt/kYKP8uO/Xo942
WelqgtkRc100zK6hrwKApMHy8ox7YGs/d3b67O27KasN1nXnIrsVmfOdl3EVvC+i9C1yKnj8rvPP
bmclYpHxEO0UeiEHQOOgt+eLWyB5UcjQB/M+AOPOkjzxwCymo3G3w1NJ/QajXh/6rcAXpp3+lv9g
QMZvQrnAMb19wlCQXqadMxkX9yxMPB4GicoZ4O+NBs5x5gXyR5HFInRWgwMxmfQF2xmw+fmMzS5P
T89nV+wqKNiFl7MB648hREz7B+zkdH7Fhv3BhPEsut1Hm06DFKaZ9PZ6Q3j7VcTAX2cIr33deJ2o
kgwA0AuP/SyRfqdycYXimov79fnF1Xt8NsRXoG4tzH5vCOIq8iDJFGooSNYyjlD0JMOfUYhDmBwA
IuaLUAA9eVZA/PBFCtThIGhTyTJ/bwMijqGmmhL1XE0eJhy5ml3Mrz5fXJ4h6E4slMyBSDQaYORU
KbA2CZFqdmpx0AB3GyYxIIFZnJyJFZJzsTw/mZ2yK8FfjyubDNc9A3ZE9ghfnSDPUzXd3QVbDIpF
z0uiXU2hJnC3wRpIYC6jNBTHwI+twRrY5H6/N2hyPyMXOwcX06wDM0GyCqSXvp5uK2JAuzZhRg7z
q+PLq0+zx6RQU7prYQEJ/ChE+jG+Bakk2doSQhPelMOQ/MSSwyJZQzy5aTDdfz7Pjbld95xTON/C
oGvWfhAhxOaNSjVNNkvAUG/cZImHsgjXT1OjbTlfYU+jdt2ACNmKv00q5aH4QlEJ0FnViWPC0y5k
XLEbcZWLbPcB95WwzgDF9xT/8+ShvJqtTSvot63g/JPwFX9ly29QoGV1EnKlvuoBZXzzkjiJ1sez
j3Z0q4FtEzho8pPEYgH/P7DqLgVC/XdY/R3Q35F5H5n3sXkfw/sz5WDIcF2hKQdaXLfBxVaesYrn
QZI2NGxA7RA/aorhHloWcgXA8qmh4cFLNKwpwMhW0fKoG4AXGEJ6schVEqtekq12S7OvUAHXf8sA
mUcuYDFuQ1u87zVZP71NwjkQ/2o2bU3d9vs/CuTA7t3dXU8AKYi1l98gZ3IGpZjwmj5rAW2+wBZ5
K2u//0eDpcPncwSoXLee+NnRDPA4lKItJiwXLqhM3uDGpqHtysM/z5XtCPMUt9ac1K5dcbZNJafH
nHAl4+ShlAz8P19IHjFSyajia3sR/XeyeCgfBD5SD/ybJoMvyaKShuZie1Fgan0oC4I+IzM+Xh09
T+Uh0FOxaIjbnkcIJlDu5OuHfFYtbV4nr8irofd5nKeGwop7i+QtJDArMoF7EsrivYa1k/6gFQz2
xh8+9PtNrkfPTxPXGp/rVhRYj09fzeBIk+9rLMDzSSBUfoa1sJ0XbWhrJbNFvj94PtfWxNume7U5
31/JSGR/43YGrEBNAx48br52nHppHMLN2GzBIW9Z9GxhndDxYy4iuywzkK+y065c+i+sXMykT1lk
/h3Kk6YmSkh7fdQqpL+PPp+/WiWJyFzXzFw9bM/Bpbjjmd9iwgAtPkABj8p/UwocvVAvNTVPUc1J
KHh2xlcr2/krWDvk9TdtZemNoteysWry19rAqrmpc9xchOHD/EbQdm7b+/PyuAJ6qkxmiNtCpZci
TbL88mpucVjDHlm6QsL8AkuJj/FSxjJfv9aap4XWdSuCrMct2QOMi+Tu+nS5BIw2j82GR7ZezmR4
kkmVrofJ4e5xvBJhwv4u/UwmrxZwDEGanqc4Zany5u6DDf13slLajmgStz2PV/z+IYsIbHM4+o9b
eeX8vpKL5mh7sXxSRbahAtfgtmUP/jzlF0hQxWVJ3hZ8vpdqVUglzoXFpQW0eBy0EuoHHt7I7EY1
GNx7vpv6ZtYI2GpQsE36TKIIFixXGW8X0M2GVtRtKmzuJXnOfoDuoWjtn78kkTYocN0HFD26Gfwx
vp0LWz8GYDPTf2h/ufKCDCp49rZ8GgxHf10BWSFm53evVSmU2F1X01X+3XJHFJcMJQrcFu3U6sQN
UfVQmRpsl3pNNfKoEOGXYPBaDFYIK+URBa4bbZ1JPshM3CXoLDU3NewZZ1QvWNpV87quTcIWXFxk
otoGthhpgB8xyo1B4wUFzdLgc90kE4uSCtdt0bQFc/JDJkVjW6mEtOP8+HkVzAuOGwwlT6ldfszW
aW5vqBpAm5nWntE/PkDqeLCOeEn1ped9irPgWe+lUMK2sRr2lSUeGtdrOT0eSGY4IQjdmnsbQzpJ
4jxLwk+2KVWwRkId/UsTqvT0pIXr2vNvowEerz8nWejb8coCPlIUbjqBfoEqylNniLzrOyLgKY5A
JJ/6Mj/ObINqgB+sUa4XIufXvri93umPW1vIs9Nznp4nPq6JX8nYUhHxNCKUrkssCqCMZ2B8LTqf
ugS3iN2dRzwMnf89cWYbztkb8+AuVwj5+CxZrZoHkBb0lRZ2LxCbRc1TLAJCXMw98TH2pde6O/Cg
6aubrpsq/Bf4a1XULzUVsqQCEvVDurZfxBzLDFf2G44gTcMzDpD+VQsZrkmqzxIrEre5KpDCAr95
d8ZAGjfatoi6T094VoivuVN6etet6djy+OMk4Hnr9INATXsctZ1u09nHY3WHdbTykKsPnM5y1SxL
On9wJoJ01U8vPhEhJLTNnueh+FHmqrHTXgEfqco2qvXJsaZ558ZcRQN7XVvCWBBNN0ATbspb9D2q
aryRiZd3BZhGOT1dd+2ZAzQp8ALnzqx6Y2BkS7lieL3bzdx4B4jRt0YPWb8/nRxOh+P62ij20Agd
lN8RFjJexpf5lM1Omb5Za/VBRzsaHA5GQwSuYASkJHHUx7eI3zspXR5XRyOCqJTfxU6qrzyAGo6c
AYLvAuAvlCo/SpZLBGhhO78UIlsfJbEFykC2ZS9fKC+TKSHShLGI+4IVCq8913cAnfMZkZPk/pHj
ON8nkCrj+c0ani1O8DL9UZxkkPCoNzCSrZ1QRjI/Gvb7/XOEhpD4nCL1eS5KKngcJ0XsCcOqw71A
iluBN5uVof1WijvHB/449DsiEUNWTe6cZShXQcW1lg6PJZBQDtWwKFmUgIBnvgfrlnJQepuaFl8u
l9Irwnx9NCJllPfIHChDcxCJOiIWgLhQ65aqhhqmhPCtLiSQ96cfjj+dXSEURd9LuVIwzD/6hv4B
I0WeOIrfCkMF6dIhZZLKl0kGsqkMw1CNF4+rO3y9dRSiyTJMx8wjay2AcrwpjkbLAEdLnfEOuwqg
vGYla4xnguWBYOBoCh54zjzUTM4WgsnYCwsoj+CBPXAWxDVPIhi5RARtnIovRZcl0JIpRMkWmeA3
bJ0UmcHF5JIBb3IpaQZQTgbWDcUnIP5J3FXodn2x5KAexe6S+C8542kqeMZQgBEw64FJrPFrDPxk
QPN9F4iYFekq4z4g6LkxGqtGNnVjtnMVQDHmhAACKkIerwq+Egw/wiCRGcNWEt7pern8lYSKQ08C
4RkumgPx6wYTcEXcu5M3MoW6ktOlM3zbPQPVXifL64/zi+u90aEzvMZxIMYK0ZS5EC5Xbgcn+hwI
lB1+i6IgQDL8LkV/mABqynisQvAlXzeTNIlSoAOeRE4qhZJaeoIFtMmGkAgQa7uqp6QvUACugiL3
E/QZ/S0MEmOCgxcmSvj/xWBdhnUyirTX01QeozsytFoMHeZyHbuVnP0PxiDoQrGovG06ZZgFcOA8
gHEcjVYlQJyZVGuOG0QQkMAmIWOAXRCzkBmgJ6QdH8VWNzhA5QJorNGfUtQr8YAAGPo+A+sFA0FS
F2tmzAq6mxhZtdZ4PksQexKDgXHfZ7BG1XaIVILl3QA1XEEexaDFwPoWAsUBKhC/FJy+I1rJW+ir
P8R4a2aEfPEOkOvpIDTTWZADusXiegqtOPNPBX1+BM51rNaxd8XVDcPtI3CnHrZ/ApWQtZY8Yq8g
gwxagIFAb9VlFKeYiWdgwF2QQgRCo89PSCqQIxEWFTHWugAl3HMyIOAHXC1L7iGuQppZIztk+HFF
GgpVk/Nxif5KX06BX3aZzP+CH1JlNMoXmLfIJltj2VvgANTMhigR4sExXE4JE/quTinkud+HyQIE
i4UD02BGmQYjVCRWfLHOgSA216T0aXKpULva74GnO0mEkbAZJhOTsQxIkVyWEqwFgpbA6+WIZQkR
o5xRqz/AhIk2u0qAjwQdBWUG86yISJ0Cp6zvUuCgGJ1D4OH+vzn5WGp9hXhMpC8iXuVJSvObwFXR
Y7ApBi6F+VL4JTU4Z0nSoD8ca6qgjpYJJSf0RYUTehSeDXWVvw1gKog0PtoY9XDAH4T2NArqsJqQ
MXgoyA2Dwx+JVYsTMnVI8R59XXdzKf0iDvC+2pN1FMEZLjCEYL6j7r2HnZFtUyqDCGEFg2lRkViQ
Vi1jPbZiACQpUlWzOeobPtW7jQQZrkea6xXPFqB/x0vCUFeV6GEbpUrmhKSYMcyMSbBwjAtKwDYV
UJwUYAvvumVMaBmDsQYdV+mkmLBHtZX12IXOfvQGFhEkRehXhEiIIHcxq0lHu8XP7IByYHAPyk7i
ke18IE94EBvJVvToiqlllkRliMWxpt2xo5KlU2DCqK5tChvsxxqH1b0XFPGN0vI+I6vHgEhApAwX
M8gN06Vxl9wzg3JE6U4OVgSYhmtciKpUs3GUwz1D5/tED2urD5MA1k16mI1Bz2K6VTXC05muB1Iq
cjwo8oXm21hDORU21MXIZglW2Nw4FjkqpKrmwD5CnQ5hhQgLCSxG8MwvhywIRmVCE3mhrlVNq45I
C1ElRoo5O3YMK1vQ+7N1jri7zBlYFo0JkKZ18pKUKfTQkaXOt7Q6wGTn65BnlKiHAtCQ1GM/wOIG
JHwE1TEY78nsUxfGAgELiEF30s8DHbnJxyv0DqGfsn1THNRlgyK5WF177NgHnwp4uNyFsl9XMr4A
WzMTwZTaBpPYdsoqQ1u4ap3tnN6jA2IpxMOudm6c+LOMoa4EtsByBJk35vtPs3hWVgt1FY+FEA6i
G11YwsepY16pLKsswBeLYjU1hcd3bIAFh8kuWFhSc1lUKoplgSiLTdeoAlJJXSoqtgvFbV6Aveyu
PC1aPH1UteeWi73GQkKUZSSSDYzoJRR1NcaF3JK+PZBhTvZlhjh6yJRF0LQyCwzgh3ZKkFowODBR
iku8gR+CJy7Rcmt6kGX+kBryUtLczk8XV6dTRoEX/vMKWG3FsNoiRPQNFWqOyDMzV+RVGj5uKMuD
hQUEE8MrGRFlJaAEjSZHwxn2TRbBaKaTE1oRrn0RbjKSqbab4DKM6XJ4js6KDC64EtZkbwfgJxtm
6bIhNAw2NYjc670jl1XCpoKs4Qox41rLbMAwAZFJz4fZX2uSVrX1chfDAK2DsIDCYMDDO75WGrfB
Y9luI4STGR1HSRHbOUCZsq0kAslHbC59S06Ip2z8x0N5BlBf065xNBMPGxwON44m64qFXlguhMa2
EEsMRLSlggEL1VBh1RstVuCb7JG++C3kXSzxJK6fBS7A0rXZKzDpqKppKE4s6WykjIomii2LkLol
CkzVQQ+Vns4ltArLcIEOhgFoS1F9SXAxpH1D4ffwePUYjRozTMV/6dNaFyjPUhfn/J7xtlhgFeRR
cqjNoakKstFL7stCWcOMGrghjnxUDzVmh/2hXsGIhBtaZoesNhZYeguuJ6GtoTbh9dKupL33kHgT
/e64pEU6LMgLYdRrxpPXE9xRoKspO3gWtjRJi9BgM8+YmFqI3Zhc0gHpIdF6284hM1IoSRRlBJE6
xy0YAx0QFOMD7phNmS7wSp3iLxQUKRQ8uurTFknRQ5caBhvg2adhZk7EO8HXO45zVUCC8WghwfZ1
F7NbpxfqUx2OcEsBfyaBaahOssZOtP2acr4Kb2jZDu75NCFVQmlA0yCV8TKpLQF/4mCqp+xZW4BQ
CBF9cRKvI6z1yUcUiFhVhOLixTSzupkIBnPjjK9WkH/MDkG19YKFIv5YxM1mbjQ9iE5togflpa2Z
tNweDWahW6daAVnsmOxcddHQJLU2jU5wG5H2tUSYpJivugwPj3HHBSgxpRiUJksolwUIGzJUjIke
O5nkqje5uY2EmcMNq4gooORUuU5xZcgz2FBDurnEr1pCwVtWG0QSSkg4Wiun9xwzrn7BigXwGyKm
JTXUBNaOy+Up+xkfHY4/64GAfyJGHQfLQsTegCUmykWDXrmVm9q0JNu0n0srXMpjimoGZDuCUkIC
oSbJW6TTrEQAPTHcA0fvpaRUzzZlH86Or6bDb/e7k8P7QXd0P+oOvx1860Mu1oHrLR6Mexhkjg76
bAX2rfTbePKO9rvFfS5iFAidTZ1AJrJ+lANNyHqFhLCqflQn9bCreVG/hDIXI/0zIo7+yZJf9e+K
6DtgCw8qm6D+RR4egufwrAboHw0q34osrF6WMqSTUEA90Pdwl3lata6i+jkA79VHaNDpi6ouoeHF
rWiht3erzlAVrtO85iDnSJBvsTufndGs+Jx6UM3VY9fAMP1eiXliE7wfNkDOmYMHVsP+pD+Cxzcf
QW/L0f5I8InvTyajg/29wbi/xw/6wyEfLw74aH88HhwshuO+YG/wZC5AsVSfhqaJkve10M2K3XQY
IKOXYmmWmwCl+Q7EZOlxqFXHMG1/ub/v7R8c7E0mMPXocDgSo/7icP/Q92k+FURJLUJFjqWanEot
fOicJzcihlSTVZDPgt9ARNCCoitYa07nJvQ9G5qBTPXbsDfu/P77/wOIMdDU
===END CRASH DUMP===

**Comment by TahaTheHacker** [comment]
Well i've fixed that crash but they did not merge it https://github.com/PocketMine/PocketMine-MP/pull/3603

**Comment by Arken2013** [comment]
Mmm OK THX!

**Comment by Arken2013** [comment]
Can you expal

**Comment by Arken2013** [comment]
!ssmms

**Comment by Arken2013** [comment]
Amam

**Comment by TahaTheHacker** [comment]
Don't Ropen issues! yo are spamming other's notifications.

**Comment by Arken2013** [comment]
Sry wasnt extra!

**Comment by Intyre** [comment]
One of your plugins is causing this.
