### ISSUE TITLE
plz i need help

### ISSUE THREAD

**Issue by yoeldoussou** [PocketMine/PocketMine-MP#3633]
i cant not enter in the server that i just created ...

i think that i did everythink good but still not working....

i downloaded pocketmine, 
i made my ip fix and opened the port of my internet 
everything is good until here 
i opened pocketmine and starter to install it and made all the setting ...
he gave me the ip and the port. 
i added the server in my mcpe in my phone 
it found the server , the server is green
but when i trie de enter inside it s not working. i see in my computer in the server [/xx.xx.xx.xx : 19132] logged out due to login timeout ....

someone can explain me if i did something wrong or if i forgot something ? 
thank you verry much

**Comment by yoeldoussou** [comment]
i forgot to say that when i open the server and that it give me the ip also it s writen 
02:18:38 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
02:18:38 [INFO] Loading pocketmine.yml...
02:18:38 [INFO] Loading server properties...
02:18:38 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
02:18:39 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
02:18:39 [INFO] PocketMine-MP is distributed under the LGPL License
02:18:41 [NOTICE] Level "world" not found
02:18:41 [INFO] Preparing level "world"
02:18:41 [NOTICE] Spawn terrain for level "world" is being generated in the background
02:18:41 [INFO] Starting GS4 status listener
02:18:41 [INFO] Setting query port to 19132
02:18:41 [INFO] Query running on 0.0.0.0:19132
02:18:41 [INFO] Default game type: SURVIVAL
02:18:41 [INFO] Done (114.626s)! For help, type "help" or "?"

**Comment by SavionLegendZzz** [comment]
please look at the console before posting the server is running MCPE 0.10.5. MCPE latest version is 0.12 please update your PocketMine-MP.phar :+1:
