### ISSUE TITLE
Crash /src/pocketmine/Server__64bit

### ISSUE THREAD

**Issue by Pub4Game** [PocketMine/PocketMine-MP#3634]
PocketMine-MP Crash Dump Wed Oct 21 21:34:19 AMT 2015

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 6743527 bytes)
File: /src/pocketmine/Server__64bit
Line: 1838
Type: E_ERROR

Code:
[1829] 	public function batchPackets(array $players, array $packets, $forceSync = \false, $channel = 0){
[1830] 		Timings::$playerNetworkTimer->startTiming();
[1831] 		$str = "";
[1832] 
[1833] 		foreach($packets as $p){
[1834] 			if($p instanceof DataPacket){
[1835] 				if(!$p->isEncoded){
[1836] 					$p->encode();
[1837] 				}
[1838] 				$str .= \pack("N", \strlen($p->buffer)) . $p->buffer;
[1839] 			}else{
[1840] 				$str .= \pack("N", \strlen($p)) . $p;
[1841] 			}
[1842] 		}
[1843] 
[1844] 		$targets = [];
[1845] 		foreach($players as $p){
[1846] 			if($p->isConnected()){
[1847] 				$targets[] = $this->identifiers[\spl_object_hash($p)];
[1848] 			}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux c1.24serv.pro 3.10.0-229.11.1.el7.x86_64 #1 SMP Thu Aug 6 01:06:18 UTC 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVWwtv20a2/itz5QBrL0RZb8kqXMB1nG52nUQ3dpALhIUxIkcSa77KIW2rRf77fufM8CW7jZvm
XuwNWogczpz3c2b8WycPItVZDMbjyXg8n09Ouh2VZUnWWfzWyXcpPnUubi7ev3/3vtPtREpruaGx
szBM7pUvIhUl2U7o4FclkrUY9Gej2XgwH47FapcrLdTDVhY6x8zDPAvwkydCYq0ncyWms/FoMpyZ
qUeAvw5CAn6sM+84TbxblUdBrI6vVHanspub6XgV5JgWYhAkz0fzz91OGhabIO4s1jLUqtvxEl8R
7aDhBKDcPC1WYeCJdRF7eZDEYiVzb7uUBFwfyiyTO/EiDeVOZborynfzuSterJPMU1e72BOnwnUN
DvHC28o4ViHG+ke/gSCQ0mdkbn4dgOSNXiws0Lcqv0+yWwyrzPle5zKzUw6PvjMrB3blC51nhKXj
duyXIb6Yp5GdA3KU9LaHJYVCalBb0jC2s9w8WGOKCGLgiz0FxbyUuTRMl5Mn1WSe/l8vUuf7QF/E
JEC/nDRtTAKFmKJ4QkX8rDHhsxmaN4aYpx6Jjgg+dDtv3U4XbxgOVXxIAFfFeq2yoyPRE/WrhX5S
gfqsIHlD1Lj/ZxBYwAbgeFADNANDO2BfR6XEx6UsX0BjG5L0qfj0k4UyeaQNYz8tbYynbW2QdM8T
mI0Hbzg8Kmc1BVji+vQTsL3It4HGIl/FABAA/CewlYY3yepnwLjZSk2Yj0qi5g3W4BZ5Jj04wqfO
QV8cHi1E7U6ua/zJ+d7LAONlEaWHqyQJlYyPOj91OxsVq0yG5ESYpeEzgDzoTX11B0yrIgj9zmI8
h+dlSZ54CWaOxt2OTAOeNxj1+pi3gacuOv1n/sOCTN6GwYrW9GYMoYglRabOZRAXD8Ib9IZjDcJ7
QCtGvUG/13eGw5PeACh7Kpz1HuZTRAhxMBBXb5bieluIs2IjpqI/WPSniBbiw/W5GPYHE2FmAkW6
TYFg0pv2hnj7VcXgrDPEa998vEl0SQAG+CXklyruaBLTWXgvd/oqlfcxvVq6m6PdhiiHvSGjk0W+
TTJNOlpugzBIxRV+AH9DWmBxfiJ5DkENBlQsV6ECgXlWIM75KgW5tBrfdLLOXzYHIkkhESwQXG3B
uq5kkjSR5LqXifRVRuEUD5h8dX32/vrDEgP3aqWDHDzERRiC1Qupd/9QYdpgrhpqcgaV9AZ7nBWr
8Y+05FuxVCJ23Tc0UFG/fHd1/fHd+8uXT9HvJXES7f6ZrJoc1INt7fR74zYPSaxW+L/FQp9NhEzP
/A6r3wH/juz7yL6P7fsY71/JuSXDdZWh/Odk5botLp4virPl68eioMF9UZz8vxAFaKlEYbh4hije
nP84m958TLLQv/ApWlXy2P/StvHJvvdSUEUoXeeInEGhZ9OWeOZfb+uRt5lNkdk40rjuPRGkQJDr
VrQt8e31M90Ai/wfUHrdNlitx/6vHbnCvO/Jvx+Hzvw7Kmf8fwW5bgba5nCDDRhci4Ww8ORwnqr8
m/HQxPysgNTZ5nmqF8fHSI/bYtXzkui4Iuu4xQj4paLxPIkiGVOgrhlujzc4Hrb4vXz5P89y1FHl
kF8tCKBy3RZZfyY+v85VdC61Wl40mGwMdluFSL83bZumDIMi3LWVWvE6+nqmDFzXBamRB0pS9WeY
MkXWGchsMNUYbEfawZ67Xdwl4RXoanM1+Hpmasxl/Wep+H2vY2OFrd7f3/cU6CHQvfyWLPMNQt57
pVUralZjTYvc88FXMrx9ZJRfGx6BMCOEUEsD9/MiYej/gADUcqvmaNvkjMc02LhO0sD7ZrppILah
vaLiGcy8TGKZqwYfdmDfa/rPCOh/IVn5jPXPeIjSmnob9NTXywb5reE/1sO3iuNNlCgq2gQ8g5Nr
tE96mSXNGF0OfUENH4sMfcU38ggGhkBc434G8e/VBtT9WMjMb9DfHP0aS/oLXDRQu26bjmewsywy
tVRZ1KwQ6rE2K8P9Kmc6fvWq3/9m9cGNgee6FQGNxy/H3r1CgVearvO4hkKppljFKv9BNrvPeuyP
tfeNdPZSZrdvRxr8ATGwlr/P09l5qGR2KTebBgP12Bdi8aVC3e2/W785R6nwjdipkD9uk59d1zXp
Oq65qZuwq22SPu7CeHS/DZt9uQ37op0227w/0Vtp0FM1V5a4Z6j0hwxzUDXlrRTbHN1T6/Q5BdBf
8MUG6md0HH9Q+5wXOk+is1BlrS6kNdzm7X+btSZq190j5Kt4LNWtwvAJC6XR/yQLBT21hRrinpko
zrcy38sTPNTW32i/438qTXyp/mskoUe8oSzmwwlO2r+TPoiu+ukvJw8G8pn2MWUG5uEVpZFxc0C7
rCksKFC06XmwrN7EeRKvg42goxo3PviofPHPIhRzMegvBqPF4EScvbnmbVY3NqAcEu4pRUE3jpLc
P3WLfl/OQvOjrszvoDC/68z8emv7XZrfE8/8TpX59c/tdzt/YueN7TqZC/OwqtANJ/2hHZx9sliu
iuwuuJNhORm9q330lndLO/mnipU0yfLTwclgNHTj+y2E7YSBzk+T9dqNZRwnBdp3x5wGONLbBupO
RagltZnBG68ObZsrVvfpdAyRyAe7Qp8O+wBDJ2vOOgw227y5TMZBhJL0NInLkShZmdeNpGM4X51i
OR9YOdUIA9iiePKSzL6ldymv8oP1OvCKMN+dDgCDd/3zJHPQReV0hHXqxiHoD43+ePOpHNFK+dVn
OiU8fXnx6uzD5bUbG/t3filUtmM0diCDe/I7PfRSqTUg+qd/53/gusgTR8s70EiBuT6t6O2ikCxQ
UMgWHhtfAULpKI9sUIBhseTp1AQ6b5awSnG9RTMoSk6EzJTIt0ogamg8wDY80lYuVkoEsRcWPswY
4B/ZPsG6SiI+28wfw9RyrboiwZdME0ixypS8FbukyCwsEawFFEEHOIQBWsig+3BHgN+q+wrcsa/W
ErrQ4j6J/5YLmaYoGASJJQKzHqxiB/IFHQoZvu+3KhZFusmkDwA9l8zCAlu4sTi43mYK5okhUBHK
eFPIjRJ0eMciswatA7zTcWwY/MpCpaXnW+VZLtoLQUAZWlTcuw9ug1T5gewl2eaY3o4v4Q03yfrm
9dW7m+noxBne0DqIsQK0EG4nK7TbIUQft4pkR4fCaLl8OhkWOs9YvnkmYx3K3JwZW2kypaADTypn
lfrqLvCU2MJxQ1ZyBMDGCWqUFIsxrLdF7ifkOeYcm2gxeyHCCxOtfEMVn20LcmwQIuw5j7gLpPhv
smpMYet27JcK/AGqo3shyUh1AmIsFqMpaQGJQsMGkRZgB8wckh1mIrX4JKb6gwOyViCqBn/BnlTC
oUhFTi1grTAIInW1E9aMMN36XfW1hvMxgJiTGAYlfV9kShu7IyphabegRmpkCApcAta2UiQOiFz9
UiBQQhmb4A5zETULJQ4tRoT8IwA36ODuikKlA11uNipbCEoH4uBtEa0gbDjTmd7F3rXUt4JOx+E+
Pfr+ATpg6yx5pFnbDIm9gEFgtu4KDkTChisYbBdSiCA0TemapYI8SGNREcNvaArDvmKDAT9wrSx5
QDDNFUQAdtjQ44o0Eqoh5/Wa/JOvLMAPuyLI/wbJ5Rmv8hVFcbbBvbXiEBxAzWJIEmEeHMvlQszJ
Uc2tCXbTH8NkBalSPVBepgiDKMgpHEVqI/luRE9cGTr6jDnQpFrj5GDoPmCqWNKCkoeBUwpfs1DW
AUwFEQohO2ZQa4SHEqPRPTgp2GA3CZhIyC1IYMCzYSIdJmwBTY+ZC3HAMTlHoJH+fzgHVFGV9A/6
w7GhH+VYkHDkJ8PXBNTj2GehVsY9gCHArX1SKM9wYHyKRGEAoShCsIA7gEjyxN/jwdCOyiHkYEqO
Zaa5nNsIBky9dhvjsoThHfkrJROe3ns8mVzVFp8Qdqo8yjmaZUK0Gm2YtRUDCLYq1TWbo77lUx89
SZDlemS43shsBWE7XhKGpqAhi35Sqqw7IsWuEXYNHCWSccHZrUkFMn9Bd4K6pQPumY21GxPE1uvS
EaPaHnvinUkt/KYR+5Mi9CtCArjrfSxq0slIRMqUg8Fpv294FAev2OweBSK2FbO6YmqdJVEZz2it
/e40Q0BDp2DCqm7fFJ6wn8Y6qhi9bRHfaiPvS/Y2ij48SJRRb0DcCFNZdtkXMuR6bSY5lG6pbKhh
EahSzdZRTqaWzpeJWbavPoq4VJSYZU0IBoud9g145qjveKipleHa2kKJiD5UGe4PQblxbK5kVVUS
TCM0aYfvhnHSLy+AwZ5s/GIHNDVgefmKw9ZKVQkIBUSZaKzFll/I8bNdTrC7whk0jJkSDaN18pIU
hJXJ1ESVOrFxrU1ZxTexzirQrMWgpakn/oHGQdFFsoiKg/Plhy7WggJqbe4DP9+aEMn+XYF3GPxC
zGwWrvOzZsE0pvbEmQ9/2spwfYx62pQMvoKdWURAaewviZsOWaXCBqxGbfNAvkclhwy7xq8J78cg
RsEGrmA1ii2b8uqHZbwss3JdHVPBQYvuad+YSuM4dewrlz98eY/076tVsVnYBP+9GFBiN7rUVMDx
57J40xzGtqos6lyrCWSRuiTT4ljnMi9gL8cbz0iWTkF1bXVl39Qq0FVZrhHZYMS0JjzVGhdxy+r2
IMKc7csuccyShYjwaWMLd/DD2w5E7R3t/5iQJFvwETep9ckb6CHL/DE17KGsuIO3764vFoJjLv7z
CnQxMboYBhREacjFIpNnMVfkWamjqm4pi25QIo5YXtmGOCGBErKZnOxm2LcJhAKZyUtkRNQp0rhN
RtaC2sNlBJtYhzR5cCW1auA6HMBLnkDSFUN8GDz1QeVe74g9VqsmEWwM1wSZWpjyOiBdDjT4KO8b
RXKzWHeRFAW43aA6hWKBuaJlYFs4DdNtBW+2orMoKeJm9Ne2OiqJIPIJGhXnCMz0aOqW31srM4z6
hngDpJ1zxOBk+ORqtq5YmYZtpQy0laJbkoJ3LChekR4qqGYfoxH4TNy7kndIudTzBdSXKmp00p3t
wW0mqsoZjhNr3tctg6INYusi5GmJhqk65KGBZxIJdzsZNb6wDIAtZfVzQk2H8Q0tIzKWiCMlpZeK
/z1tkERLbbyRD0LuywXthsfZoTaIljJYF+/Rxhe6scqqQVri2EfNSmt3NB+lCkUk2ityitSHLdb0
oadV0uDgXao6GBm66xaqJL33mHYb/e5lwM0wGt9CWfXa9ez1PO7QLfCFGH8VtDRJi9BCs8+Ul5qA
uelgn3QgPCLa7Ik5bEZgfExFG/QdkzFUowMbHWh3aSFMZVdqlC69FikqHVPuGXvk2GGqDAsLUGa0
yiLUtp8FI4SoGuQxGa0CGL6ZYje2TDe8MMGI+na6eCvMqEmw1kaM8doyvt63wBqHNlLaI1U2aY2m
2zSI10ltBtuEdM8oe419NVRBTF+cxLuIanx2EA356opQalrsZ1F/ZoJha1LIzQbJx7bh1f4GFYh0
/fj2aW4MPQROP0UPycuYMqu4Wl2yA6MwnxdGA1ns2NxczzHDSdpwhoNz2p7j/SIVJinlqy7ewQRt
huVlKYbKZI1KWUHe5o7/gifZ5FqQguCSDSDCHhQ0iogCBafOTYorQ56FRkoyn0v4el9RdBrzhFjC
ACnHaObiQVLKNS9UsgCBpWJRkkOIYO86T2Ddn+jRQZ5BO4WBnwigiYNlIdLc2GQmyn7BNG3l3jB3
Y0/tk3Jzy4lMc81AbEcoJQLQaZN8g3LGygTwk6DtZPJejhw1toV4dXl2vRh+N+tOTh4G3dHDqDv8
bvCdj2RsAtdhnim8IMiczvtiAxPX5m08QZbudDvqIVcxyYNP6s6RiRr3vX2+NlO9IiFsqj8jST2a
al/0L2GQq5G5m+6Ye/C/msvq5g7dykNls63/BkWGcB6Z1QPmL2nKtyILq5d1EPIRKUAPzNH2Ok+r
r5uofqYL/+YIH5N+1q0rDNHKbJtWk1EV7tK85iCXRJDfYPdqeclY6Tn1UM3Va3dgmK/C2ycxofug
A+JcOHS2M+xP+iM8vnhNjjmajZSc+P5kMprPpoNxfyrn/eFQjldzOZqNx4P5ajjuK/ECmJZbEguf
GDLiRAcPtdBts24nDIjR92ptO02MMr65mqw9iVp1DLT99Wzmzebz6WQC1KOT4UiN+quT2YnvMz69
jZJahJr9Src5DYzwMTlPblWMVJNVIx+VvEVEMILqTTCyk3weQfcQaMKvQWrehr1x5/PnfwPLuePj
===END CRASH DUMP===

What's the problem?

**Comment by Gamecrafter** [comment]
@Pub4Game **Allowed memory size of 1073741824 bytes exhausted (tried to allocate 6743527 bytes)** did you not read the crash dump?
