### ISSUE TITLE
PocketMine Server Hung Up

### ISSUE THREAD

**Issue by SahrulGamerz** [PocketMine/PocketMine-MP#3635]
Hi,

I Have Host My Server On My PC with 512 MB RAM 1.6Ghz 2Core 4 Thread
When I Leave The Server For 30 Minutes / 1-2 Hours or more..The Server Hung Up

Can SomeOne Tell Me What Is The Prob.
------------------------------------------------------------------------------------------------------------------------------
If You say my pc cant host the server..i can use my other pc to host...

thanks..

-------------------------------------------------------------------------------------------------------------------------------
Sorry For My Bad English

Have A Nice Day! :)

**Comment by Gamecrafter** [comment]
@SahrulGamerz This not a forum to ask for help. Please read the contribution guidelines before creating an issue.
