### ISSUE TITLE
Hotbar Does Not Keep Items

### ISSUE THREAD

**Issue by pmicznik** [PocketMine/PocketMine-MP#3636]
My son's server has several bugs... we will write them in separate comments

Hello! My servers’ (Running on PocketMine-MP and MCProHosting) here is the first bug: 

In creative when I try to put items in my hotbar all it does is the selected hotbar slot flashes and doesn't give me the item
Here is what happens:
I select the Hotbar slot - then I select the item - the selected Hotbar slot flashes and does not display in the Hotbar nor does it give the item.

**Comment by ZombiePower** [comment]
download the latest pocketmine build on your server
http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/lastBuild/
