### ISSUE TITLE
Crafted Items “Uncraft”

### ISSUE THREAD

**Issue by pmicznik** [PocketMine/PocketMine-MP#3639]
My server is running on PocketMine-MP and MCProHosting

Sometimes when I craft items in both Survival and Adventure modes, they "uncraft". For example, when I try to craft a wooden pickaxe it crafts it but almost immediately gives me back the 2 sticks and 3 wooden planks.

**Comment by TahaTheHacker** [comment]
there is another PM version for it, close your issue :smile:

**Comment by Pub4Game** [comment]
@TahaTheHacker What do you mean?

**Comment by DRedDogPE** [comment]
@Pub4Game He means that there is another build where this bug is fixed and that @pmicznik should close this issue as it is already fixed.
