### ISSUE TITLE
API Version not Compatible / Development Build Server version downgrades to 0.11.0

### ISSUE THREAD

**Issue by djnerraw** [PocketMine/PocketMine-MP#3653]
Hi,

I downloaded PocketMine v1.4.1 and Im trying to start a server in my own computer (Windows 10).
So I started to install plugin, but I'm receiving error that my API Version is not Compatible and it doesn't let my server start.

Thanks.

**Comment by PEMapModder** [comment]
Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue - plugins are not supported here.
Anwyay, try using the development build.

**Comment by djnerraw** [comment]
I tried looking for a same problem but I can't find one.
Where can I see that Development Build and do you have a link for tutorial?
I am new to this.

Thanks.

**Comment by djnerraw** [comment]
Nevermind I found it.
Thank you.

**Comment by gaoyichuan** [comment]
It's not a forum here.

**Comment by djnerraw** [comment]
I noticed also that in the Development Build, the Server Version is downgraded to 0.11.0

**Comment by PEMapModder** [comment]
MCPE 0.12 support is being developed on another branch. Please do not open invalid issues.
