### ISSUE TITLE
Event does not have a handler list

### ISSUE THREAD

**Issue by Tee7even** [PocketMine/PocketMine-MP#3654]
Server crashes if a plugin declares a handler for an inherited event such as EntityDamageByEntityEvent (EntityDamageEvent) or EntityCombustByEntityEvent (EntityCombustEvent):
```
[Server thread/CRITICAL]: pocketmine\utils\PluginException: "pocketmine\event\entity\EntityCombustByEntityEvent does not have a handler list" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 759
```

I guess the problem itself is at [line 758](https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/plugin/PluginManager.php#L758):
```
if($class->getProperty("handlerList")->getDeclaringClass()->getName() !== $event)
```
I don't know exactly what it does, but I think that getDeclaringClass() returns the parrent class and comparing it to the derrived class returns false.
Could you please fix it in the next build? Thanks.

**Comment by DRedDogPE** [comment]
@Tee7even What plugin is using EntityCombustByEntityEvent?

**Comment by Tee7even** [comment]
@DRedDogPE This is just an example to show the common pattern - all inherited events don't work.

**Comment by DRedDogPE** [comment]
@Tee7even ok

**Comment by PEMapModder** [comment]
The inherited events are not supposed to be declared with. Plugins should declare handlers with the event class with the $handlerList.

**Comment by Tee7even** [comment]
So why there are inherited events in PocketMine itself? And how should I make my plugin to trace if someone hits someone? EntityDamageByEntityEvent "is not supposed to be declared with"!

**Comment by PEMapModder** [comment]
@Tee7even you should declare a handler for EntityDamageEvent. You can use it like this:


```php
public function eventDamage(EntityDamageEvent $event){
    if($event instanceof EntityDamageByEntityEvent){
        // etc.
    }
}
```

A developer who creates a handler for `EntityDamageEvent` expects to listen to all kinds of entity damages, including those from and not from another entity.

It is exactly the same theory that you wouldn't expect to have a plugin that handles `Event` and listen to all kinds of events.

**Comment by Tee7even** [comment]
Thanks, I already did that, but it's not supposed to be used that way. Let's just say: there is a bug that doesn't let EntityDamageByEntityEvent  to work.

**Comment by PEMapModder** [comment]
EntityDamageByEntityEvent isn't supposed to be used by plugins.

**Comment by Tee7even** [comment]
Well, yeah, I didn't know about this, thanks. But why it did work before?

**Comment by PEMapModder** [comment]
@Tee7even it didn't work before. If you try to register an EntityDamageByEntityEvent listener, it did not generate a warning, but when an EntityDamageEvent occurs, it will still be passed to the listener and result in an E_RECOVERABLE_ERROR (not sure about the exception name) because of incompatible parameter types.
