### ISSUE TITLE
FEATURE REQUEST: Overwrite server.properties settings via CLI

### ISSUE THREAD

**Issue by jantede** [PocketMine/PocketMine-MP#3659]
It would be a very nice feature to override specific configuration flags via CLI parameters to force them.

If you want to e.g. bind a server to port 1234 with 256MB of RAM and 10 slots you would start it using ```php PocketMine-MP.phar --server-port=1234 --max-players=10 --ram=256M```

**Comment by TahaTheHacker** [comment]
this isn't a place for requesting, close your issue.

**Comment by PEMapModder** [comment]
I don't think feature requests are not allowed here.

**Comment by 202831820** [comment]
Hi, guys, this feature seems implemented already? and tested working,  see 

in Server.php

public function getConfigInt($variable, $defaultValue = 0){
		$v = getopt("", ["$variable::"]);
		if(isset($v[$variable])){
			return (int) $v[$variable];
		}

		return $this->properties->exists($variable) ? (int) $this->properties->get($variable) : (int) $defaultValue;
	}

**Comment by iksaku** [comment]
@202831820 He's asking for _Comand Line_ properties, like when starting the server using `./start.sh` in Linux.

I know there are some properties already implemented, like `--disable-ansi` and `--no-wizard`, but not for your request

**Comment by 202831820** [comment]
@iksaku these --server-port=1234 --max-players=10 could be set and override the default server.properties file on startup.  your can try and launch the server with args. 

the server.php implemented it in 
getConfigInt method

$v = getopt("", ["$variable::"]);
		if(isset($v[$variable])){
			return (int) $v[$variable];
		}

firstly will get params from commandline args then file

**Comment by PEMapModder** [comment]
This is already implemented for both `pocketmine.yml` and `server.properties`.
