### ISSUE TITLE
PocketMine on XP?

### ISSUE THREAD

**Issue by Rigenkr** [PocketMine/PocketMine-MP#3660]
Hello. I know this has been asked several times, but I just can't get myself to understand the solution. So I'm kindly asking, how do I work with PocketMine on a Windows XP computer?
Thanks in advance.

**Comment by Tee7even** [comment]
Why would you use Windows XP? Why not Windows 95, huh?
P.s. Close your issue, you should use forum for your questions - forums.pocketmine.net
