### ISSUE TITLE
Doesn`t work on XP

### ISSUE THREAD

**Issue by NanoRayYT** [PocketMine/PocketMine-MP#3669]
http://prntscr.com/8yfxzt

**Comment by Tee7even** [comment]
What's not clear? That's not an issue, the issue is you using too old system

**Comment by NanoRayYT** [comment]
lol
on pocketmine write WinXp, Vista, 7,8

**Comment by RandomAltThingy** [comment]
Microsoft no longer support Windows XP, and most softwares don't either. I suggest upgrading to **Windows Vista** or **Windows 7**.

There are various tutorials on how to upgrade from XP found online.

**Comment by NanoRayYT** [comment]
Luke, on G432 vista going?
