### ISSUE TITLE
Connecting to server

### ISSUE THREAD

**Issue by Axelbro** [PocketMine/PocketMine-MP#3673]
Pocketmine 1.4.1 issue (linux and windows versions)

I onw a linux vps server built by a friend of mine.
The server (apparently) is online when i do ./start.sh, but we can't connect to the server form mcpe 0.12.1 and 0.12.3
We have forwarded port 19132 but nothing has changed, why?
I tried pocketmine on my laptop too, over 3G and over my wifi connection, same port forwarded, same result. I added an exception on firewall, same result, still can't connect to server.
What should i do?
Someone can help me?

Thanks... and sorry if i made language mistakes (i'm italian).

**Comment by SkygridRex** [comment]
PockeyMine 1.4.1 only work with MCPE 0.10.5 close your issue
Download Link to PocketMine 1.6 jenkins.pocketmine.net/view/PocketMine/job/PocketMine-MP-Bleeding/ this version work with MCPE 0.12.X

**Comment by Axelbro** [comment]
It works perfectly, thank you :dancer:
