### ISSUE TITLE
Crashdump isPopulated

### ISSUE THREAD

**Issue by reidq7** [PocketMine/PocketMine-MP#3674]
PocketMine-MP Crash Dump Wed Nov 4 08:27:19 ACT 2015

Error: Call to a member function isPopulated() on null
File: /src/pocketmine/level/Level__64bit
Line: 2797
Type: E_ERROR

Code:
[2788] 	}
[2789] 
[2790] 
[2791] 	public function populateChunk($x, $z, $force = \false){
[2792] 		if(isset($this->chunkPopulationQueue[$index = ((($x) & 0xFFFFFFFF) << 32) | (( $z) & 0xFFFFFFFF)]) or (\count($this->chunkPopulationQueue) >= $this->chunkPopulationQueueSize and !$force)){
[2793] 			return \false;
[2794] 		}
[2795] 
[2796] 		$chunk = $this->getChunk($x, $z, \true);
[2797] 		if(!$chunk->isPopulated()){
[2798] 			Timings::$populationTimer->startTiming();
[2799] 			$populate = \true;
[2800] 			for($xx = -1; $xx <= 1; ++$xx){
[2801] 				for($zz = -1; $zz <= 1; ++$zz){
[2802] 					if(isset($this->chunkPopulationLock[((($x + $xx) & 0xFFFFFFFF) << 32) | (( $z + $zz) & 0xFFFFFFFF)])){
[2803] 						$populate = \false;
[2804] 						break;
[2805] 					}
[2806] 				}
[2807] 			}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #43 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux kingdomscraft 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
SnowHalation 1.8-alpha by hm for API(s) 1.13.0, 2.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
Treasure 0.3 by  for API(s) 1.11.0, 1.12.0
AdvancedKits 2.2 by luca28pet for API(s) 1.12.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
EasyMessages 1.1.0 by Gamecrafter for API(s) 1.12.0
CombinedSlots 1.0.0 by basprohop for API(s) 1.10.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
Lightning 1 by XFuryMCPE for API(s) 1.13.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
ManyWorlds 2.0.2 by aliuly for API(s) 1.10.0
xyz 1.0.1 by unerds for API(s) 1.0.0
LaunchPads 1.0.0 by Philip Shilling for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
GoldStd 1.2.2 by aliuly for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
RodGuns 1.5 by XFuryMCPE for API(s) 1.12.0
CrateKeys 0.3 by  for API(s) 1.11.0
NoArrowPick 1 by CapainKenji17 for API(s) 1.12.0
PlayHarder 1.0-TEST by hm for API(s) 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
PureChat 1.2.9 by 64FF00 for API(s) 1.11.0
KillRate 1.2.3 by aliuly for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNPIty3DaSv4KMXbfSZThvvSaRq3SynGQj27MeJd66MKXCkJgZWiTBEKCkUc7/ft0NkAQp2ZYs
JXeu3ZhsAI1+P0CM/+zoKBGd6XAy2d2djHfHB92OyHOZd6Z/dvQmg6HOyfnJu3dv33W6nUQoxVcI
O+ZxzLRknCUiWYicLYs00JFMWaRmMitirkW4tc0AkBZxDGuXUYwL+yoP+pkMLoROolT0Y3Ep4v4p
/vf8fHeyiDTMjWGkMx3tHex97HayuFhFaWe65LES3U4gQ4HEjfb29wGfrz/CAng5gBd6OhhUT0Oa
kBWLOApqCjNL3/G6SC+2nl932fMb+P9S5oFgh8z3aaftPw2OEeHwdbTcipQSeuu5XkfKexHgassq
YP1XIQrx2/MoDcU1INnaAsTb7D/Y4PqV/bPNvv+ejUfb7H9gFLZsjf4OwsrZlu8Hskg/u8s2e3HI
PjM+j24E42nIvjE8bZesjC0rvs6FLvK0ZPU7Mzyxw0agBzuVGHftwHPajVWbr4RuytAHzECfxbdX
S+4bs9R70bCOkq79iq6zCIxipabT51nFE8BE7r1Qmud2fKvc4aBaWM43CkQqaMr+YFBNAVkAoagc
b/gdw6fvDxk8ffstPBtS9gfDarpdcHNTLoCnasHNTblg5Cz4opGcgt3/RqbBvkUKPm8gOOfmtpmU
O48bO7dFUCt2fzBpzVzkgl/YsZ3G2EcD3HWAFrRXgT52wCl1zgNww986zwZsa3vKao/2/bnIL1Fj
Qc7V+mWRZFsLKWPB0+3O793OSqQi5zG6MMxSIBXAPOzthuISdloUURx2ppMx+H0utQwkzBxPuh2e
RTRvOO4NYN4K4sS0M7jnH1iQ84s4WuCa3h5hKFKOga9zGqXFNbsAswplooDmpWbj3nDSG4+8a/jj
rXLlRdnlrrc7Yc922Pz1jL0XIZuLjB2w4d50NAEC2fHJ/IyNBsMddr2/C4EMdsjWGeDf6e32RvB2
I1JgrDOC14EZPJeq3B8A9BLTSxX0FEppnsqrH7kxIHy3dDfA3YYs9z0eZ2sOUF7otcwVKmqdoPRJ
jL/Vchz1BvA3DIiUL2IBFKLvdDuhyIBeXAhjSi71SxeQcAzInWipBU9A4Q4pzTeM5ZIj37O387P3
b9+dvgTQlVioSAMTmBqA2XmUZLE4Alpd/mpgk7u93rDJ2Yxs7zXYHjsDemBQreVqHQVZk+PR13Na
EwP8uYRZ7uZnR+/Ofpm5vHXWWmdq2u+Dqa6LRS+QSb+mtO9gAQkcrznsu4R9Re7IoAFuSmHYlsIr
Hl9E+YVq8Lz79SwvLT5ISEBFaKnw/RZN91Dve5nH4UkY6aNcO8w1wE3mwCbPF0LzcwgK588Gk/2W
wk9e8+y1DJECl9tHmHImEp4lhNL3r5AyAZRBxvH9Fp2fY/hOndfE9ucJlE3efx97M+PefUjEop9w
pWGwsQ+I7QyitCpy4YisAjniGvTGrnAaFj8kH3+c6c/yKCnACpy976Hzo/CSp4EIf460chhogB0m
Rr1RQ8NxEfDRfib0k3mwu7Pvv0bgw3VZkdVvMAL8Yo7PjmKRN9h1oU0LHzct+uRSxnOg/MnYdXZu
c/upWAWsXl1d9QSQglh7+oIYE5Dol0U8z/iVm36a8IYqJw3WTl/+u8HVmALXsDf5euYApe83CLiX
Rq1pnnC1eW0aGVdXDXA71g6a6voBllCl0ApAj9EYeNfG9legMpeao9lPX2GrDo1O3rkz8jRYx2wk
kwXMDeexbJhzE34rZDdltOAKKri1bCXhR8ToCiMkoRYlnzZtq/RfpRbvxBXPQ4cfB9gw4OFnDXhQ
BlX798j+PX6kQdfUPMSaX/NVFJyJWMxkrk1Zbblrj7QCEBWlDps8jop482TKMuh8P9HZQ9g5jVZr
nUIx7jBSwxwWmjr696si37w+np3crnG/tiCwaU8/hPofcr74L+7SXkJc4UOy6+3dT/jdp8ripTpW
QM+Cr746A/JYfOBpmEvA5xzjeNkdYaXkHSv8mGdZo7QtIU2rHPV2moL5ID9IsYd/nizQKrMzmOa9
9XpcKC2TW+m9AW4ysvsX53d3awiHTUK+KtG/AqWd5TxVy4aeGuB2yG+FkCdvu0qEvu+S0Xx7cBNW
Iu03sGCpk0c34n3UqHJKUJvzln5Po/g4j1S2GcmD/lG6ErFkv0ZhHsknC6glKQ+JRy/F5ZkELTsc
VaBWiXMrf7e76nYN95VslPv7vkPJV3fRFQ7KhOmGeijVSIIVsBmCB39X/gMCqJ9UD1Hc9ebGYQLf
2gbY6v6LVOSheqpu2GDzfdiY/vOlROEoxxKCqZwXabCe8YY+HOAX6sfZOoqjjM3hrxhz/1PFlIzw
KovW92OiKOPI7ykw+YWIYhU0g054JvKk0e1VsFtHNS1b2528ejUYPFmtcm7wQU9UUuA8Pty9cKVN
5zUW6nHR734omkW0C2262K0jKnRZ25L8c/bmyVytiRZYb1D00Aqnia3vIOujEKBNEqmOeKzOZo4U
GuDPd49P1jA6W/p+i4D7HsvNcug6glvHciW4XbYOHlC2PkG1SoEzM7Tc9xjjEQVrg3Us52UczrVr
7CWkXbXeI5c8RfEOuysd/j3Fu+W0cTz/o4hbVXx7qJ1kJ48XjPsl4B5CWhMhf4uMbnGPB5/xFd+o
9mmZC2371Oj/Ju9xIkmZ07P7J77I+od0zcAButxBmdj6CNU+Szl45JlJvfFXKxzweHhy0HeYAD7f
yfCHInXTewlxDyF6O/c5hniE1uymvl/vfp9+Neda/Cw2jWa1gj3g48FXUh3gXhew10Oa7DfyKM/l
1SwKLhyyXegnj3+OeQbb/CzSD9Hw6Q4KnK0fUrvPYr75EcqFRqB0gK261zs7mZ/95Z9q6/2hPnJp
uY81xYLnp3zlnmvVsC8clZ+KFRDzdnnLKx7BTLX57cB1f7d36OrX3NBBCF0TUhAOGucgNfQLJ6ln
Qq9FLsLzJ7NEZ3M8/KCXBxikbJ29WcAXGrAf5SZKk+EkCbozroO1UE8a2TJpTuEqYu7DCbQj+P25
1XQRqF2SHXy55fpShHM6uluMNAziE60Y0lU/PboRIyQghZ8hhb/j2v0wXIHaUhj/BYcc5dGQTMWm
g+cuSkWX4iSQqUwQYJ/MZ6uyjrxdqF0AzZgn/pZSrRLQR7xcw3MQG4BL9ujCUg8aDbBEHeFnwc6z
WfXGjmW6jFYMbzD6uZ8+w+s/b+Qlm7DB/nQwmA6G7OjY3P7BcYPOQ9Ucngml8T6UA89krg+HB8Px
CIF4x/JwgE+J1OGhR39+treR2PT7F1N2jN2oGaB5IpH5xoujJNKH45F7z+k1jl+tQWIwrLTBy9NU
FmmAcuEb2J8H60hcigTaRXUol0siDctAz3ZaYD2Hw4GhiV/bZaoE8TiWV94yxo8yzeU8jRLoP5vA
RC4qyIoj7aHll+4mehXMzllDYgpkXr1nl9mhTPEpjJbLKChivTkcEza6SAblmqeE1nht8BDBdKHU
CJ/axxqmhAidKST5lyevjn45PUOocQDvj0LkG7ulBeVg0CU9+NwjFY5G4/GkBoEXwH7h4X/SH5BT
oaWn+KWwuPDOV2WjvU0So5ExNH0WkH0VOV2ZIjNjIBzmfLV9PQOzY2cQgwUruWU8FwwyDQM/VPDA
NQtQ15otBIvSIC5CsFNAf8u8EddcJrByiQjaOBVfii6TmMQUomR0X5BtZJFbXCxaMlBatIxoB9BX
DnYDTg2I34irCl0/FEsOGlPsSqb/0Aw/vPCcoWgSYDYAW9rgFWG8LGn4vlqLlBXZKuchIOj5KbqN
QTb1U/bsbA1O7cUAAipinq4KvhIM7wSTyKyLqQjeYwn4oxtzKw2WHq9FYLloLgQCyugi0t5VdBFl
Iox4T+arPr71T8GXzuXy/Kf52/Pd8YE3Osd1IMYK0ZT5EEBXfgc3er+mAgCvRysImQyvSiudk3w1
fm+g669mmKRJlAq8/guMkUpDcRkFgq0hvMWk5AQQG4ept6QrngBX60KHEn3NfMNHYv5ZKBA3+6OA
4pW9E8tcqPU3Pkz+NYKAysoAg9+ce/riG0P4Ebo2w8gBw8yGUXYZcfYvdAqYQs5RBtgpw1SBC+dr
WMfRjpUEei0dRpncImKFAjOFtAKmQvxDfoCZkJpClGQ94IFIFlKJGv0JuWGJB282Y4RgYNBgM0jq
YsOspcF067TVaC2oZ+8hC4C6weh4GDKQibFNJFOjoBJzxQlDIwOLXAiUB6hF/FFwuu6+gkSXskse
F4Jt2S0h7m8DcrMfBAuB0cEDfa9WIp/CKO78pqBb8uBwR2qTBmdcXYBP5BfgYj0c/0WBRNCCSyZx
1jqHRFqA0cBs1WUUzpgNe2DUXRBDAlJTmO9JLJAuEZYUKfgWTiHcczIq4AfcL5fXEKS1ABEAO+QM
aUUaStWQ89MSfZgu+IOvdlmk/4H3/XNaFQrMEmSnrbVsCzgAPbMRSoR48CyXU8KE/mzyF3nzD7Fc
gGCxvGAGzCitYdRKxIovNhoIYnNDyoA2jxSq18QC4OkqIsJI2Awzk02PFqRILssoxxvxDOJ+SqjA
H0S5o1E/MFOQ0a4k8CHRLVFmsM+KiDT5dsoGPgUTitsaghEP/5+Tj1XXZ4jHfPso4pWWGe1vg1lF
j8WmGLgUZkcRltTgni2SoMqOJGUrdESFuwUUry1plbMNYR+IMyEaGM3wsIacsl2LCGo1iF7gniA0
DA2fkqmRJdRKMSUAdHQzzad8jDjA9Wo3NrEId3iL8QMTIE3v3Z6MPNtqGuSXiQDzpCKZIK1GwGZt
xQCIUWSqZnM8sHyq7TsJanK94vkClO8FMo5NAYfudadUyZaQFLuG2TXguAlPC8rILhVQrRRgCNvd
MiC0LMGaggmqy2UZGJLaxHrsrUmH9AbmsJZFHFaERBA+rlJWk45GyzKifMrGuwPDInv2irzgVlwk
UzGLK56WuUzK8Ipr7bjnRiRHpcCD1VzbEu4wH2cdVsf0Cw9lxH1KFo/BkIBIGfY0yAwzVXSXXDOH
8kSZSR5WCFjp1LgQVall6ySTA0vnS2mWtbWHCQDrKLPMxWB2sdOegGdKQl7A8TyAuLamUG6EA1Xm
/iwqP02FRl1UhR1YRmyy4AIPHKgI4VgDQ/IDc7IRifzPlK121ASihajyIYWaZ27oKkfQ7/ONRtxd
5g0dW8a8R9t6uiQFkvfOrgkqdZ6l5gGTXGhCnVWgWQtAS1OP/QgdEoj3ECplMNzj2S9dWAsULCD8
XEWhXpuITe5dofcI/ZTt2aKgLhcUCcaZ2mNHIbjTmsfLPrQApoIJBdiZ3Qi2NPYnU9cfq8zs4HJq
pJNr9D0sgXjcNX6NG7+PUqgxgS0wG0GmjXn+l1k6K6uEuqLHAggX0V1GLOfTzLOvbj0GLZ1YFKup
LThesCEWGjarYEVJw2U1qSiMrUVZZfpWFZRCyhpRsb7SXBdgMP1VYEQLYS1UtdmVvWCjqRBl/Yhk
AyOmnaKp1rqQW9J3ADLUZGB2iWeWTFkCQyvbbAA/dI6C1F7itSwTk3gDP8RNbNe0sz3IUt+mhlyU
NPfszduzkymjmAv/CwrovFLovAgRfY5CzRF5dueKvErDRw1lBdBkQCCxvJIRUUICStBoNBrOaGAT
CEYyk5fQirDDRbhNRtbpm+AyhJkyeI7eigwuuBLOZltD8JM7dumyEQwM7xoQOuhtk88q4VIxIo0i
Zuy77OEFExCXzH6Y+I0mqcOtW1+MA9QAYeGE0cB8ITO4LZ7ajBrRm6zoKMEfbjrhX9lqraQBqUdk
2CxAZMZHE9o/tZbnAA0N7QZJM+mwu9eSbaXCtJgLYXAtxBLDEB3KYLhCJVQ4zVGNE/cI8ZxfQsLF
ui7CRlpg25Vt7KGBzUNVLUNBYkmHbWVItCFsWcQ0TSqwUw/dMwpMGqHWK8dOHawC0JaC+iCxAzKO
oXiChpJQnMTkUjFfRRGjChRnqYrX/Jrxtlig9wkoN9TG0NDE0B6iIYJ3PIwK5Sy2quCWRvJTg8Ca
Hs4HHBiV8GTMK7IQzLEmkwX4jcEYE3bYbUuq27qSg95tFmwEvOIRdeh/4K99rZLtevJ8gnsKVGY1
+WBs5U9JEVv9S1yvhdhPyS09kCESbc7/PDImRfJEc4VorfFIpgHFGIFnY1jBDmrN4o9Eiwxwm6LP
mCUFEFNrWGTKxHy7Yfl2xXGfJowniwis37YZFJlMfz410QiPEvBXqsxATY61hmIs2BbyVXRD2/bw
+KcJqfJJA5qtsyhdytoI1hI1T1v2nNNAKISIvlSmmwSrfPISBdJVFaHYtthhVg8TwWBpnPHVCtKP
PRiojlywRsTf6l7czY2hB9Gpu+hBeRlDJgVXq0t2wCTM8NQoIE89m53rEpCgMnNOi47xSJHOuEQs
M8xXXYa/9sOTFiDF1mJQmiyhVBYgbchQKSZ6nGSTa4HqAXd0kDD75cMpIgqoOJU2Ka4MehYbqsgM
l/hVSyp4R/oOmcQRJByjlpNrjhnXvGDFAvgtEdOSGhoCS8c2ecp+w0cP0kyX+ubfEaMJhWUh4h7G
EhNlw2CatvLMm7qxu852qbmlPKaoZkC2EyglIiDUJnmHdNqVCKAnhkfkkJMGE3qrdpuyV6dHZ9PR
d3vdnYPrYXd8Pe6Ovht+F0IuNkFrCz+20L9ccLg/YCswcGXeJjvbdPYtrrVIUSB0J+FY4u8aq99G
h/Q1q3qFnLCq/r2HLMCp9kX9EUdajM3PuD3zk/Eb87tuczltEUBls67/sQgeg+vwvAaYf9OifCvy
uHpZRjH+ngtR259cLHVWja6S+nkN7mu+mcKkD6r62IbXHZOFOeqtJkNVuMl0zYHmSFDosDufndKu
+JwFUM3VazfAMP1s3D6xHbz6O0TOmYcfnEaDncEYHp//hG453hsLvhOGOzvj/b3d4WSwy/cHoxGf
LPb5eG8yGe4vRpOBYM9hp9kaxVLdhM6kiq5rodtm3U4YIqPvxNK2mgCl/fbFzjLgUKtOYNvBcm8v
2Nvf393Zga3HB6OxGA8WB3sHYUj7qXUiaxEqcizV5DQywofJWl6IFNJMXkHeC34BEcEIin4lsuH0
DaX8KfRNlJm3UW/S+fjxfwEGsSTT
===END CRASH DUMP===

Help please happens hourly

**Comment by xxFlare** [comment]
You have way too many plugins on your server!

**Comment by reidq7** [comment]
Thank you for that very non-helpful comment that has nothing to do with what I asked. I need a lot of plugins and it does not take as much load as you think.

**Comment by xxFlare** [comment]
Try to disable some plugins, having that many plugins will kill the main thread/make it very heavy.

Also what level format are you using?

P.s Many plugins will cause issues like this, so it has abundantly very much to do with what you asked.

**Comment by reidq7** [comment]
LevelDB and okay I removed snow, it was a catalyst of the crashes and it rarely happens without it, but it still shows up.

**Comment by Intyre** [comment]
Only report errors that are reproducible without any plugins. If you have plugins then try to find a plugin that can be the cause and report it to the plugin author. 

Nobody is going to create a server with the same plugins as you and wait for the error to happen. Help us and everyone by trying to figure out the cause.
