### ISSUE TITLE
Crash chunk always

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3675]
PocketMine-MP Crash Dump Wed Nov 4 12:10:13 MSK 2015

Error: Uninitialized string offset: -1
File: /src/pocketmine/level/format/mcregion/Chunk
Line: 121
Type: notice

Code:
[112] 		unset($this->nbt->Data);
[113] 		unset($this->nbt->SkyLight);
[114] 		unset($this->nbt->BlockLight);
[115] 		unset($this->nbt->BiomeColors);
[116] 		unset($this->nbt->HeightMap);
[117] 		unset($this->nbt->Biomes);
[118] 	}
[119] 
[120] 	public function getBlockId($x, $y, $z){
[121] 		return ord($this->blocks{($x << 11) | ($z << 7) | $y});
[122] 	}
[123] 
[124] 	public function setBlockId($x, $y, $z, $id){
[125] 		$this->blocks{($x << 11) | ($z << 7) | $y} = chr($id);
[126] 		$this->hasChanged = true;
[127] 	}
[128] 
[129] 	public function getBlockData($x, $y, $z){
[130] 		$m = ord($this->data{($x << 10) | ($z << 6) | ($y >> 1)});
[131] 		if(($y & 1) === 0){

Backtrace:
#0 /src/pocketmine/level/Level(2668): pocketmine\level\format\mcregion\Chunk->getBlockId(integer 6, integer -1, integer 15)
#1 /src/pocketmine/Player(739): pocketmine\level\Level->getSafeSpawn(pocketmine\Player Player(45))
#2 /src/pocketmine/Player(719): pocketmine\Player->doFirstSpawn(boolean)
#3 /src/pocketmine/Player(1560): pocketmine\Player->sendNextChunk(boolean)
#4 /src/pocketmine/Server(2485): pocketmine\Player->checkNetwork(boolean)
#5 /src/pocketmine/Server(2222): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2100): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1701): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/1/PocketMine-MP.phar/, string /home/1/, string /home/1/plugins/)
#9 (1): require(string phar:///home/1/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #396 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux kvm14539 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u5 (2015-10-09) x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
CustomChat 1.1.2 by Array for API(s) 1.7.1
ClearLagg 0.0.1 by LDX for API(s) 1.8.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
BanItem 2.1 by LDX for API(s) 1.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
SKits Final_0.5 by Sergey_Dertan for API(s) 1.12.0
SClan Beta_2.6 by Sergey_Dertan for API(s) 1.9.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
WorldBorder 1.1.0 by Topic for API(s) 1.11.0
MineReset 2.1 by Falk for API(s) 1.0.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
RegionGuard 0.0.2 by Asyv3n for API(s) 1.6.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
EconomyAPI 2.0.8 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PurePerms 1.2.1 by 64FF00 for API(s) 1.12.0
EconomyShop 2.0.6 by onebone for API(s) 1.12.0
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
1vs1 0.0.3 by  for API(s) 1.0.0, 1.1.0
HotBarInfo 1.0.0 by Pub4Game for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
EconomySell 2.0.6 by onebone for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO4tu28aWvzKrBHvtXVEW9bKt1gFcx2mDayfa2NksUBbGkBxKrEkOyxlaVnrz73vOmeFLthPH
9QIX2Bu0Fud15rwfw+GfPR2nojd3J5PZbHQwcsf9XsKVPi0KWfTmf/b0JofhXiZ1HIhev5cKpfgS
uz5mcRbrmCfxZxEypYs4WzIZRUroOXNcmBuVSfImTnByvuLFfG9vbyVTsefuLWRwLfR5nAnnfDHA
wT1VBHs5dafQvZeIG5HsRbJIud5Lg0IsY5ntnazK7Brm5wjdQP6OhbAogSlA7cjt93TBgaL5r70X
Q3Y/kDP8uzOazQ5256wZ9Twa9jyziedVu3gebeO8Wgr9UwLz34Y7cabFUhRs1mfVo+M2z+50F7B6
4d7BYJHwjSh29seH9+9NuNFOFzwSFzlfZzvtaWY9s2Am013aZ/TgPu72PmbAeRXKN3GhtNnBlzIR
PCNY44dgudPZ8AFgSmThO3GriU8daJM70C5EcQPQRpOD6QPQgpUIrt8JvZZFF9j0QWDwbwuYGXFe
gX53gcweBOIOh18BsihkAEYiiw60/YeguftD9wFoSvNCd6Ac3OV5bUk7k9nkAUBXV4HMwELLQHeU
5ESmOdexn4gTMHp1JnkIOiP930Wg+x1IpY4T5XnnPM7O5HLZmmUN/9sGXk+t5tzpyJNyGWdqj0g9
ZDvIl0L8UcaF2Hn0Ng/yB93Gbu+3L/2eeBbn9pfcD2BhqO3NI54o0e8FMhSIk+uOAKynPV1msNvO
S72KlfMq87Xz6jXXfPcHgOO64wcnXVxvzuLlStuJkwcnkotqT50+PDUGfp/IRBbKzp09OPcXgSDP
eW5n7n8dagXwgKZ9oedDeMaH0ZA689JP4oBFZRZo4CZrudeXt332cgP/f979k1a4drdC6LLImCzC
aksfl6g/YQn78UfmurvsH2zn5Wds7OPzy80Xg8po1KAyGleoTO5FRd2HCvwfhxafiqePR4IdsWBV
7CAIg86sC2LF1cmKZ0vQyyMGNi3MrP0W0gcV0odf5R+q0x0OjofVdinAb/EvhNk14sMW4jPzvGGv
XjF31zJxXAkijnZw7N9hiB0dHbEhbPPlX9H3X9H3X9H3/2H07feWIhMFTzDUAXcUGC44CncwC8UN
bOyXcRL25uPDGQTIQmoZSJg6nvR7PI9pojseDGHiMtbQHD7yHywo+HUS+7hmsE8Qyoxj5dM7i7Py
ll3fpO5kOj5k44E7GwydicPTcDZh4BwuzhfstfBjnpnBfSe41q7ruP8ZCv+gnLKd0dCdOu7QGR7u
stuD2dVsAvCxSpn3poPZwMXtPoPxQXsE7aEZvZKq2h46qJFQo04OFHLppFRapuDyNbYs0q3OfoeP
7mAEPbzUK4jV4F9/7S0KfosePJM3wUr3fvvN8vJXmL0/cFEmIuOghYAehpN+LxQ5IIurYUzJSL9u
d6Qcs5YtsKDNNUaeFwSoqpjvgE7j3PcXl5/efzh7DV1r4atYAw0ZVIdA6QmYV3HGl8s2dXVfm7jh
YDhwO8T1zl7/T69NzwHw9on0gLUuxebqtSg0h1hyUePQfkay3sgE7HS7tyH24vL4w+XHxT2knp/8
vD+7+iSLJDwN47Y4t0e6ZE+3ZNpD2woKHmkwprhU+7PnYkIaLPdnnme0z/PWiJAAhDyvxm0BY28f
KdufePZWi7RFaNXTJnD0LakOn04QgPI8u6lxoI/UStLm4wS0Qd0xO9vdNbxZl4bTG5lcAFIdQtzR
0ylpb11ZW43Iw6rXW2mdg89er9cDATgh+IG+Rh8Tn8hMFzL52CKw6WtR5w7GHdre8OQ6Lq5Vh7bZ
00mLA7Np6Xnt/R+jYAXMCbjSomgrWat3yzv+X0uptfW2un2fcFBhT7gSi9MWYa3OLl3DwUGXMChc
y2TTJWtIgcdG0CfSZ+CCnAATIBNmfI9VXfw97piTabdJeRNnPLkCl9clp+Ocn01Y2y4fsTHkfIfs
bq4HgUz3VJlDWqNlgcKD0ABotuikdpvOn4TmV6Ntp/EwmYfPGdjqn61wZjqeTPWpggIDz0xUR2k7
3dvJynjL80NZBvi/j85PFqfsUvD02YTdRgMKOEq2v6G1RKwCaiHZXJU+UWwwNAjudUhDd4Rl52kU
QWreVvNO97bhbmn6z+mn82ejGYFB+Gtt3209zmop9P8ki7DjZNu921Iddmm6lHkcdIlyn05Ua2Ob
ltRYPIIYrEU+CCU62Vfd1yIEspI7Qe+5shLM3wrcEPxMa+/HeFCqKY8BrbZ7aTq38ir3MeHO/Uu+
xe5clbsWiyfFvA90jvNzyYuwRV27d7sc2MqLj9XmZpw9V1rCCZrnLYr4hmth8FhAUQqmI4uH+ts+
9eEZj8xCZepzbUr+dhba7u7a3mjb9s546stncygEjU4uagS+J/6fQqIn083x4m07PjSdXe29k9TI
TPjw/x0r7NdOp2IA/rr0O7btsW1PbHvy9MrXouF5wmAOuHheh4pHsGJRFmIhirQdJ5q+baFu2fFs
8ubNcPhsUr0y8EBfKwRaj9825q0ISSvtWVIDpZH+xUrmd8VPvdvyn31b/t+ku61f3yFUBfjUUrXI
PcY/x2meiJ+BtNS+z6l8dHdgKwvo0nnOU745DoUqO6T+BQmnCJEjRM9ThMnSYrLdfhyZ7o1yW8RR
c9s3d1O7h2z2iQRB2Iyj+DYGZwRSu1EkuveZ+G8Ffx5Hwy9S/8SLt1kkW5S0OrcTtS0hLUp/guJ8
rpyg2dnzOlg8gpRLnl/K1206qp6uRd1xJM+Z1GieaxkC9s3ej0D9LE6hGZ4Uguv4pm0x2yPfkIfP
VV5INNQ7Re8TCaohQrlwB5dvHvZVrkMkyT3eDnv/mbwd4NN4O4Pco73dJ17kdzwddW5lo9siu/cc
6fsDGcBR+rLgmYooH7pI5LrV7BRpDQsiu3nlANeAMCSxbeQfzYGFhNo6UXeYUPV/3TU+wIdvaW6b
0V8R9TaducGpIrVB8ZvU4msJXgB9WlQuXVHOPwAzyUWhY4HvMF4s6hY7kVkULxnelfAKL3vxSYTs
nbxhE+aO5sPDuTth5xd/Z/j+BMcNOAd5eKSF0q0+RPvIPXTHI+ysotXREFspv3VyeiupjtwhdSl8
YerkJuUGxh85LnavV0COk8RKm5WGuc4fpSg2RzJrdRVgC7YHHwc5V2oNdebRf9A/2FTq8Mgrh0O+
L81PYn4OL8zv2LYn3PxOb8zvTNqBfTtwkJnfIGR2xqtXFlR1zJJwqJR4FtrxH39EvHiWyTILhKXd
4cEqFjciBW1XFnWegC04UYI3Mo5kFDWs4VmcgtztPNOXSr/qiGQBgGs226UrqMECWdTt/Ca388M4
iuKgTPTmiBht3vJBseNAaavjbKmOsJtenxv50ruFpk8JEbam4M2co9enb44/nl0SIaWWjuI3wu6H
b9Dq14yDTZqg4jGsRFhAOlfC7njXAVWPATWs87ISVJFdrqDsZhV6jBeC6ZVg4BYVPHDNAmSwZr5g
cRYkZQi6G+ONjy2VR1gXMoWVEQLYhql4JPpMwkihECTzIYhcs40sCwuLxREDLkM+QzsAgwtQ2mSD
gN+JdQ1uLxQRBxYrtpbZ3zTjeS54wZA1KRAbgLA3gD7Dt3KG7vVKZKzMlwUPAcDAy9CcDLC5l7EX
l6tCgDlAF2AB+rUs+VIwvIlELLOmp2JoJzLAy1DEVFx6gm//DRXdhYBAVRSIbLCOr+NchDEfyGK5
h629M7C+Kxldvb14fzUbHzqjK1wHbKwBzZnXK0rl9XCjTyuBvGNaMry/wIBK++YaxIRePoEKOzTD
xE3CFPCAJ6FJpKG4iQPBVmBACQk5BcBGw5st6RoW9KtVqUOJ1mAugyEy1pDhZzJy8e+Y01+BfydD
88zoZ9Qa9mnYTNqnngP6G/ybIe0YrZOhN6KX66ZmYjcxZ/+FDgmmkGNy7MicbvvgQqhH1oyjpisJ
FFlMjbi5BcRKBYoM4QKUiTgEKQHMhKATIq+bAQeY5kslGvCn5AIrOMA1hkbPQOVBqxBVf8OsLsJ0
6zDr0YaVLz7FICyZgVryMGQFlB+kvYgm3tUAdLiCChE9FgOd9QXyAwQn/ih5giJdQrKVsRuelILt
2C0hWuwCcLMfOGqKaA5oBJ5GzGEUd35Xpj5ek4jYsdpkwSVX1wwvqoARDnD8owKOoI5XROKsVQH5
TwlqBbNVn5GHYtaTgdr3gQ0pcE1hJCe2QHzEvrTMwPpwCsG+ILUDesBAC3kLflYLYAGQQ+aS1agh
Vw06byO0cpyC1txnsf4bcE4XtCoUGMRIk7fWsh2gAOTMRsgRosGxVM4JElo8uvBiQ/b+cyJ9YCym
Csx0g/ZBZot+LYUS0N9A1B2wC4PKkDaPFYrXeAugaR0TYsRshsHFwKn4r4gvUQzqAq4OXHlGoCLw
M9WORvxATElKu5RAh0TDRZ7BPktC0iHE5mzokbshz67BXfHwnxx9TLu+gjyG0L+EvNIyp/2tu6vx
sdAUA5PCbEWEFTa45xZKC1HEkuIZGqLC3eg+V4VabWwu7AN+JkQFoxkOGIMwZkZxQEJunYF5AtPQ
NTzEU8NLyL8SChFo6GaaRxEbYYDpNWZsfBHu8B79B4ZImj64Oxlptlky8C8XAUZSRTxBXA2Dzdqa
AGCjyFVD5nho6VS79yJkqR4bqpe88EH4TiCTxOSXaF73cpV0CVGxa5hdA4ab8qykmN3GAvKZEhRh
t185hC1NsKpgnCq9xSHoaaNiA/beBExqgTqsZJmENSIxuI91xhrUUWlZTpgDgbPh0NDIXrwhM7jj
GElXzOqaqKiQaeVfca0dd9ouqSVTIMKKblsV7tGf1jpM9AO8vKgMv6ksJ29InYgZVjFIDTNJcZ9s
s4AMRplJDiYRmAw1sBBUJWZrJYczi+draZZtiw8jAKZaZlkbgtnFTnsGmikKOQEk98JQbXWh2ggH
6tD9VVBelpnbmnXuB6qRmDDocw3VA2YhHNNkhXdkmXVJZIAms7WjxhP5og6I5GtetH1XNYKGX2w0
wu4zx20pMwY+2tbRFSrgVqYz41WaQEsFAUa50Pg6K0CzFjotTgP2C1Q5wN4jSKZBcU8WH/uwFjDw
wf+s41CvjMsm+67BOwR+zvZtVtDkC4oY05o6YMch2NOKJ9EeVAkmhQkF6JndCLY0+ieztkHWobkF
q5Uknd6i8WEOxJO+MWzc+FOcQRoKZIHaCFJtDPQfF9miShOapB8zIFy0BkfvYcaf5Y5tthMyKNOE
Xy7nNuN4xfAqtLZhBVNKGq7SSUV+bCWqNNOzopgzt0kSFdtTmusSFGZvGRjWgl8LVaN2VX3XqTtE
lUAyc43bVFw01WoXUkvyDvDQjRTMLnHMkjmrb34beuiABLG9wVtRxifxDnxwnFjR6db2wEt9Fxsy
UZLci3fvL0/njJwu/BeUUJxlUJwRIDpBQckRenbnGr1awscdYQV0eb+ilZSIIhJggkqjUXFGQxtB
0JOZwIRahEUw9ttoZI2+2125MJMHX6C1IoE+V6K12Y4LdnLPLn02ggH3vgGhg8Eu2awSbSxIGy4R
MpZm9hyGCfBLZj+M/EaSVAQ31TH6AaqAMHNCb8CTNd8oA9vCaelux32TGh2nssza/l/ZfK1CAtFH
aFgugGvGxzmbPLyUF9AbGtwNjG7QYe7h6N7VpF2ZMHWoLww0X0ToiOhsBR0WiqGGak5cWp7POL4L
fgMxF3O76tujQOYbe7RgQ1Gdz5CfiOiyWeUVrReLyoSmSQWq6qCFxoGJJFR+FVjPg2IA2IpVv0us
goxtKJ6irqTkKjG+1PRvCQMZWgnjnN8yvs2X3NzGF2GjD11ZkJJ+4GFcqtYyKwdusSMjNUut3uF8
SFbQJeHRllPmIehigyAL8G6u0SSsrxtvZBBviroK98Fd5K37W/OY6nOoxUth5WvXk9lTv6NAWHN2
8CRouczLxEKzzxiZtgB7GdmkA9xDpM0BnkN6pJCTyMoUPzTAIxvb61r3gCdnc2Zyu0qk+FlDmUOu
YxI+o5DkPEyeYWEBlH1cZTdEoFNsrjluVHdSH0/9GDTfTLGHdqY+nxtnhEcJBVcrZnpNiLVKYrTX
JvK1c0O9dvCAqNtTh5NOb77K4yySjRqsJMqethy0zgshDyL8MpltUszyyUIU8FfViGLZYodZM0wI
45dQjC+XEH3swUB95IIpIn7adH0/NQYfBKfuwwf5ZVSZRLy9GnTCjM6NAIrMsbG5SQCpV+atw6IT
PHOkQzCRyByjVR/aQAGe8OkqE4PEJIJEWQCzIT5lGOZxkg2tJUoH7LEFhNlXGq0UooR8U2kT4CqH
Z6GhhMxwBV9tMQXvA93DkiSGcGOkcnrLMd6aBuYrAN8iMa+woSFQdqyS5+xXfHQgyPSpbP4NIRov
WKUh7dNaIqIqF0zNVp1iUzF23+Ev1bYUxRRlDEh2ColEDIjaEN9CnXYlBOiJ4aE3mi6FpGa3OXtz
dnw5H/2w358e3rr98e24P/rB/SGESGy81o4uBDTAwxwdDNkS9FuZ1mS6S4fj4laLDBliPiGBONT+
FgV1qN2GgLCsP0TNA5xsG+qPJNZibD6bccw3Op/NdzTmpo0fQGazar5i5QnYDi+aDvONbdUqi6Ru
RHFC97YBtGveDUY6r0eXYfOYNt0rMOX6zsTvqnNDhvgdmm983MHUopv65ri4BgFp4ybXDYmaI8Zh
myEXizOCgvfL8gDyvWbxBlhCX/LYJzbFz1Jc3Iw5+CZrNJwOx/D48i3W08Hs4MCf+X4wHobjGY/G
PBhPojCc+Pv+1N8/2I/EFP6xl7DTYoWMo3fBtLFU8W0jFlvP2wl0te+DiGwxCr20n4iiAz8MZlN/
6AseHUQTHopZNJxFB5MDMQsn4zAKD0Yz2k+tUtlwVpHxqS6lsWEmTNbyWmQQi4q655Pg1+A1DKPo
7fWG04sYvNmBEz7HuWmNBtPely//CySWdJA=
===END CRASH DUMP===

**Comment by flash586** [comment]
on all versions of cores

**Comment by flash586** [comment]
even when unistall map

**Comment by Pub4Game** [comment]
dublicate #3500
