### ISSUE TITLE
:) problem :)

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3676]
Sorry... Can u help me with my plugin?
I try write Kitpvp plugin.
Sorry :) my english is not very well.
By the way.... I know... Its offtop
Nobody wants create kitpvp plugin
I try.... Idk.... Who help me?

class main extends PluginBase implements Listener,CommandExecutor {
   public $red = array();
   public $blue = array();
   public $world;
     
   public function onEnable() {
    $server = $this->getServer();
    $server->getPluginManager()->registerEvents($this,$this);
    $this->getLogger()->info(TextFormat::GREEN."CastleFlags включен");
    }

    public function onCommand(CommandSender $sender, Command $cmd, $label, array $args) {
     switch($cmd->getName()){
            case "teampvp":
            $player = $this->getServer()->getPlayer($sender->getName());
            $play = $sender->getName();
            $world = $this->getServer()->getLevelByName("world");
            $x = 128;
            $y = 5;
            $z = 128;
     switch(array_shift($args)){
                    default:
                        $player->teleport(new Position($x,$y,$z,$world));
                        $player->setGamemode(0);
                        $player->sendMessage(TextFormat::RED."[Ctf] Вы вошли в лобби. Выберите цвет комманды");
                        $player->getInventory()->clearAll();
                        break;

                    case "red":
                        //unset($this->red[array_search($play,$this->red)]);
                        $player->sendMessage("Вы вошли в красную команду");
                        array_push($this->red, "$play");
                        unset($this->blue[array_search($play,$this->blue)]);
                        break;

                    case "blue":
                        //unset($this->blue[array_search($play,$this->blue)]);
                        $player->sendMessage("Вы вошли в синию команду");
                        $this->blue[] = $play;
                        unset($this->red[array_search($play,$this->red)]);
                        break;
                    case "status":
                        $playerStat = $sender->getName();
                        $countR = var_dump($this->red);
                        $countB = var_dump($this->blue);
                        $reds = count($this->red);
                        $blues = count($this->blue);
                        $player->sendMessage("Привет $playerStat! Ниже инфо об игре");
                        $player->sendMessage("В команде красных: {$reds} игроков");
                        $player->sendMessage("В команде синих: {$blues} игроков");
                        $player->sendMessage("Синие: {$countR} Красные: {$countB}");
                        break;
                }
                break;
        }
       return true;
    }
 public function isEnemy($player1, $player2){	
    	if(in_array($player1,$this->red and $player2,$this->red)){		
	      return true;
          }	else  {
     return false;
          }
     	}
     
     public function onEntityDamageByEntity(EntityDamageEvent $event){ 
     if($event instanceof EntityDamageByEntityEvent){ 
        $victim = $event->getEntity();
        $attacker = $event->getDamager(); 
        if($victim instanceof Player && $attacker instanceof Player){ 
      		$event->setKnockBack(1);		 
	   	  if($this->isEnemy($victim,$attacker) == true){			
	   		$event->setCancelled();	
               			}		          		
                }

ERROR:  In_array() expects parameter to be array, boolean given.

Pls help me!!! I tried TO 7 DAYS!!!
PLS HELP ME!!!
I TRIED: In_array, array_search... Does not works

**Comment by darkspive** [comment]
Oh sry... Team pvp plugin

**Comment by tiNsLeY799** [comment]
This is not a forum. It's only open to PocketMine-MP related errors.

**Comment by sekjun9878** [comment]
In `if(in_array($player1,$this->red and $player2,$this->red)){`
`$this->red and $player2` is a boolean expression, which is causing your bug.

You need to learn PHP to write plugins, because hacking snippets up is not going to make the expected behaviour. It's not English!
