### ISSUE TITLE
When you fix crash chunk?

### ISSUE THREAD

**Issue by flash586** [PocketMine/PocketMine-MP#3681]
Why not recently issued new kernel version. Accumulated a lot of mistakes. In particular error coordinates that makes use of plug AlwaysSpawn to server did not stop. I see that the new kernel version released under version 1.5 but it is not relevant. Many people agree with me. So which version will be following kernel 1.5, 1.6 or 1.7 may even? And when we see other creatures with intelligence?

**Comment by flash586** [comment]
There had long been stable versions and when lifting boom error occurs and the game is closed.

**Comment by thebigsmileXD** [comment]
I just can not understand this.. English..
Can someone clarify?

**Comment by Charelene** [comment]
Never, it is D-E-A-D. ![image](https://cloud.githubusercontent.com/assets/12827721/11326733/e07e865a-9179-11e5-9702-821fd1aee5e7.png)

**Comment by MarcPow** [comment]
Charlene, I think shoghicp is just busy with his new job - good for him! :)  But there are new builds coming out over here:  https://github.com/ImagicalCorp/PocketMine-0.13.0
