### ISSUE TITLE
Add the PocketMine 0.12.3 and if 0.13.X releases in its time in the Android PocketMine App

### ISSUE THREAD

**Issue by sero583** [PocketMine/PocketMine-MP#3682]
0.12.3 were never listed in the PocketMine App, so could you guys please list it and 0.13 in its time please too?
- Thanks!

**Comment by RandomAltThingy** [comment]
You can do this manually by building the code from GitHub, (Or downloading a 0.12 phar).
Next, rename the file to PocketMine-MP.phar.
Finally, copy the phar to your PocketMine folder where the plugins folder, player folder etc is.

**Comment by sero583** [comment]
Thanks!
