### ISSUE TITLE
Placing slabs

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3685]
When you place a lower slab and a block is above it, you cant add the other (top) half when you press on top of the slab, but you can if you press a block attached left/right/behind/in front of the slab

**Comment by PEMapModder** [comment]
I am unable to reproduce this issue.

**Comment by thebigsmileXD** [comment]
PHP7 !== PHP5

**Comment by PEMapModder** [comment]
It is merged into the master branch anyway.

**Comment by thebigsmileXD** [comment]
@PEMapModder hmm.. i wonder how this can be fixed when the file wasn't changed.

**Comment by PEMapModder** [comment]
@thebigsmileXD but this issue is no longer reproducible, right? That may mean a change related to MCPE version, or a change at other parts of PocketMine core, or other things. As long as it is no longer reproducible, it doesn't really matter :P

**Comment by thebigsmileXD** [comment]
I'll test it and send you information if it works.
