### ISSUE TITLE
Blocks acting 'undeleteable'

### ISSUE THREAD

**Issue by UltimateMcraft** [PocketMine/PocketMine-MP#3687]
Sometime when I break a block then rejoin the block is still there.

**Comment by TahaTheHacker** [comment]
i have that bug with slabs too..

**Comment by Shaddock-intl** [comment]
Maybe cause is your network is not stable. May not a bug.

**Comment by TahaTheHacker** [comment]
@Shaddock-intl no, it's a PM bug,

**Comment by UltimateMcraft** [comment]
@Shaddock-intl My network is stable, anyway this only happens on one server I have, the other is fine, so I think its a bug with the server files

**Comment by DRedDogPE** [comment]
What blocks? or is it random?

**Comment by Charelene** [comment]
PocketMine is dead, delete it. That is a solution.

**Comment by PEMapModder** [comment]
@Charelene please stop spamming. This project is still watched by 208 people, and we are still working on it, just that you don't see it.

**Comment by UltimateMcraft** [comment]
Random. But I keep getting it with slabs and planks more often

**Comment by PEMapModder** [comment]
Cannot reproduce. Please comment here if issue persists.
