### ISSUE TITLE
When you place a slab it adds another slab

### ISSUE THREAD

**Issue by Ultie0** [PocketMine/PocketMine-MP#3688]
For example (doesnt happen all the time)
Place a slab it turn into a full block
Two slabs turns into 3 slabs (block and a half)

**Comment by ArKh4n** [comment]
You can use WorldEditArt then use command // pos 1 and  // pos 2 and then // set (id:slab what is you want) 
Ok thank's  :)

**Comment by PEMapModder** [comment]
@ArKh4n this place is for reporting issues, not for providing alternative solutions that do not correctly fix the issue.

**Comment by PEMapModder** [comment]
@UltimateMcraft could you provide screenshots to explain the issue?
