### ISSUE TITLE
Tools do not break

### ISSUE THREAD

**Issue by Guirobrine13** [PocketMine/PocketMine-MP#3690]
On PocketMine 1.6 pre-development build #396, MCPE 0.12.1, the tools do not break, please fix it!
My server hosting is Bisect Hosting

**Comment by Guirobrine13** [comment]
Anyone answer me, exist an plugin bug fixer?

**Comment by RandomAltThingy** [comment]
This has not been implemented yet.

**Comment by elw124** [comment]
I found this issue as well.

**Comment by RandomAltThingy** [comment]
It ISINT AN ISSUE.

**Comment by PEMapModder** [comment]
@RandomAltThingy this **has** been implemented.

**Comment by PEMapModder** [comment]
I have reproduced this only with flint and steel.
