### ISSUE TITLE
Clear the Lag on Android Devices

### ISSUE THREAD

**Issue by iamstewpeed** [PocketMine/PocketMine-MP#3691]
How do I Clear the Lag on My Android Device Cuz my PC just got broken.So I run a Server on my Tablet and it Lags So Much. ClearLagg Plugin doesn't Even help me to Clear The Lagg

**Comment by Subtleoliver** [comment]
This is not a support forum. 
Try giving more ram or wait for the php 7 version of pocket mine which will be faster.

**Comment by thedeibo** [comment]
Something you may need to learn about PocketMine GitHub Issues:

* Issues are only for PocketMIne Related
* If it is a problem with a Plugin, Go to the Plugin's Issue / Bug finder, or contact the plugin maker|(s)
* ALTERNATELY
 - Search Google. (Not bing, Because It's Not Google)

**Comment by iksaku** [comment]
Also, a mobile phone doesn't have enough power to keep a server, I strongly recommend you to rent either a `Dedicated Server` or a `Virtual Private Server (VPS)`

**Comment by RandomAltThingy** [comment]
For the benefit of the OP:
If you do not know what a VPS is, click [here](lmgtfy.com/?q=what+is+a+vps)

**Comment by tiNsLeY799** [comment]
Heh. That was actually pretty funny, @luke

**Comment by RandomAltThingy** [comment]
It's @RandomAltThingy lol
