### ISSUE TITLE
Fire block age

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3692]
Maybe you should add a tag to the fire block, that contains its "age"
on random tick the age increases by 1, if its 15, the fire will "die".
See http://minecraft.gamepedia.com/Block_states#Fire

**Comment by ZombiePower** [comment]
I am unsure, what you mean by a "fireblock", but I do know that the ageing system exists in PM. As, when you alight Grass blocks on fire (by a fint&steel), they do die, after a while

**Comment by thebigsmileXD** [comment]
Fire. Just fire. And yes, they die, but via random tick

**Comment by PEMapModder** [comment]
@thebigsmileXD PocketMine does not use block states.
Block states are only used in the Minecraft game engine. According to Minecraft wiki:

> 14w11a	Added block states. Only used in the game engine, not saved in world files or used in commands yet.

**Comment by thebigsmileXD** [comment]
"Yet"
How about tiles? They do

**Comment by PEMapModder** [comment]
@thebigsmileXD block states are an internal mechanism in Minecraft introduced in Minecraft 1.8. As far as I know, it doesn't exist in MCPE at all.

But indeed, PocketMine needs a way to properly handle fire ticking. But this shall not be done with block states.
Perhaps with block damage? idk.

**Comment by thebigsmileXD** [comment]
Block damage should work

**Comment by thebigsmileXD** [comment]
The arrows are related to this?

**Comment by PEMapModder** [comment]
@thebigsmileXD nope. Just too lazy to separate them into two commits as I already wrote the changes and they're in the same file, making it less easy to separate the changes :stuck_out_tongue: but anyway, there are two issues being fixed in this commit.
