### ISSUE TITLE
Help :D

### ISSUE THREAD

**Issue by misha1** [PocketMine/PocketMine-MP#3693]
RuntimeException: "Declaration of MineBlock\BlockPet\BlockPetEntity::attack() 
should be compatible with pocketmine\entity\Entity::attack($damage, pocketmine\event\entity\EntityDamageEvent $source)" 
(E_STRICT) in "/plugins/▒▒▒▒▒▒▒▒▒/src/MineBlock/BlockPet/BlockPet" at line 0

	public function attack($damage, $source = EntityDamageEvent::CAUSE_MAGIC){
		if($source instanceof EntityDamageEvent && $source instanceof EntityDamageByEntityEvent){
			$damager = $source->getDamager();
			if(!$player = $this->player) return;
			if($player->getName() == $damager->getName()){
				$i = $damager->getInventory()->getItemInHand();
				$b = $i->getBlock();
				if($i->isPlaceable() && ($this->blockId !== $b->getID() || $this->damage !== $b->getDamage())){
					$this->blockId = $b->getID();
					$this->damage = $b->getDamage();
 					$this->despawnFromAll();
					if(!$this->dead){
						$this->spawnToAll();
					}
					$player->sendMessage("[Няша] Спасибо , я превратился =) !");
				}else{
					switch($i->getID()){
						case 259:
							$player->sendMessage("[Няша]  Я милаха !");
						break;
						case 325:
							$player->sendMessage("[Няша] ".($i->getDamage() !== 0 ? ($i->getDamage() == 8 ? "물" : "용암으") : "공기")."Не надо мне , не надо !!!!");
						break;
						case 268:
						case 272:
						case 267:
						case 283:
						case 276:
						break;
						default:
							$this->isFallow = !$this->isFallow;
 							$player->sendMessage("[Няша] ".($this->isFallow ? "Я пойду с тобой =) !" : " Я останусь здесь :( !"));
						break;
					}
				}
			}else{
				$damager->sendMessage("[Няша] Владелец ".$player->getName()." Меня зовёт . не бейте !");			
				$player->sendMessage("[Няша] ".$damager->getName()." Меня бьёт :( . Спасайте !!!");
			}
		}
	}

**Comment by willowmaster66** [comment]
This is a plug-in error not a pocketmine error. Please report it with the plug-in maker.
