### ISSUE TITLE
Couldn't find a working PHP binary, please use the installer

### ISSUE THREAD

**Issue by bronch** [PocketMine/PocketMine-MP#3695]
I upgraded PocketMine on my Ubuntu VPS. Before upgrading, everything worked, now when I run ./start.sh I get the error "Couldn't find a working PHP binary, please use the installer." I tried to fresh reinstall other two times, and nothing. I tried also to change in start.sh the PHP binary path to my VPS' one, but I get always the same error.
Sorry for bad English :)

**Comment by iksaku** [comment]
You need to "re-install" PocketMine, I will suggest you to make a backup of your `players`, `plugins` and `worlds` folders before the new installation ;)

**Comment by bronch** [comment]
@iksaku I did, two times, it didn't work

**Comment by AndreyNazarchuk** [comment]
Delete everything from the pocketmine directory first.

**Comment by bronch** [comment]
@AndreyNazarchuk I did. Same error

**Comment by AndreyNazarchuk** [comment]
Same thing happened to me once, I don't remember how I fixed it but I made
a post about it in the forums. If you can find it, you will find the answer.

**Comment by iksaku** [comment]
Then there's a problem with the compilation problem for your machine, try manually installing the binaries (Use google to get them)

**Comment by bronch** [comment]
@iksaku you mean PHP binaries?

**Comment by bronch** [comment]
ops

**Comment by RandomAltThingy** [comment]
You need a bin folder (Use the pocketmine installer to get it) that contains all the libs and php binaries. It should be in the same directory as your pocketmine phar.

**Comment by iksaku** [comment]
For linux machines, you should compile the PHP binaries for your own VPS with some kind of `apt-get` command, Pocketmine is designed to use either `user pre-installed` or `self-compiled` binaries, it shouldn't be a big deal...
BTW: Keep in mind that you need to have `PHP 5.6` for Pocketmine to work... Either it will _refuse_ the binaries and return an error like: `Couldn't find a working PHP binary, please use the installer` :stuck_out_tongue_winking_eye:

**Comment by bronch** [comment]
@iksaku on my VPS is installed PHP 5.6.10, should I recompile it anyway? Everything else that needs PHP works, so why doesn't pocketmine? (Sorry for bad English part 2)

**Comment by RandomAltThingy** [comment]
I told you. You need the bin folder than comes with the pocketmine
installer.

**Comment by PEMapModder** [comment]
This is not a forum. If you need help, please use the [IRC channel](//webchat.freenode.net/?channels=#pocketmine) or the [forums](//forums.pocketmine.net).
