### ISSUE TITLE
My server crash every 10 minutes!

### ISSUE THREAD

**Issue by SoyPro** [PocketMine/PocketMine-MP#3699]
PocketMine-MP Crash Dump Fri Nov 13 22:25:24 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 449
Type: E_ERROR

Code:
[440] 		return $this->perm->isPermissionSet($name);
[441] 	}
[442] 
[443] 	/**
[444] 	 * @param permission\Permission|string $name
[445] 	 *
[446] 	 * @return bool
[447] 	 */
[448] 	public function hasPermission($name){
[449] 		return $this->perm->hasPermission($name);
[450] 	}
[451] 
[452] 	/**
[453] 	 * @param Plugin $plugin
[454] 	 * @param string $name
[455] 	 * @param bool   $value
[456] 	 *
[457] 	 * @return permission\PermissionAttachment
[458] 	 */
[459] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #30 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Tue Sep 2 23:33:35 CST 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
BouncyBlocks 1.1 by Darunia18 for API(s) 1.9.0
FoodEffect 1.0.0 by MUedsa for API(s) 1.12.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
VoteBan 1.0.3 by GmWM for API(s) 1.12.0
GetInEffects 1.6 by TonyDroidd for API(s) 1.12.0
RestartMe 1.1.0 by Gamecrafter for API(s) 1.10.0
iProtector 3.1a by LDX for API(s) 1.9.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ItemCloud 1.3 by onebone for API(s) 1.4.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
CombatLogger 1.2.0 by Lambo for API(s) 1.12.0
WalkingParticles 2.0.0 beta by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
ChatFilter 1.1 by onebone for API(s) 1.1.0, 1.2.0, 1.2.1
DamageIndicator 1.5 by CreeperFace for API(s) 1.12.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
MultiTP 1.0.0 by Minifixio for API(s) 1.8.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
MineReset 2.1 by Falk for API(s) 1.0.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
KillRate 2.1.1 by aliuly for API(s) 1.12.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVXAtz2za2/iu4SmY36ej98EMdd9e1nTStnehazmZnyx0PREISY5JgCdK22tv/fs85AEmQUmLZ
1m53O+mYPCQOznfeAEn91kj9UDTGveFwfzgajPrDZkMkiUwa498a6SqGS42z67PLyw+XjWYjFErx
BdJOeBCwVDLOQhHORMLmWeSmvozYkquJSEJfKTh79ZoBKcqCAEbP/QCHdlTidmLp3og09CPRmQR8
JZLr60F/5qdwWwDExng4PPy92YiDbOFHjfGcB0o0G670BAo2HHaBkZM6aSLSLInYy3Tpq9Z3MUzc
+s63BJiK9NXLiIfi9bfAejjs0bjf6bgPx3QwIGLnm2/obEhn7Bv215gnPGRxwcxxSsb/p9LEjxaM
mNO4kRlHJ3sFEyPhTMqAruybKx06O6CzOJsFvvslHWr5f6P7D7+Ce9MoQj3qlqhHPYN61LdRjwY1
1BPSPHtpLIC31BVT18BoVLsBMTPGXt7yINN37Fk6Gu3XdbRZ08dpyt1lKKKURh3Y+hsdbtQf97xy
1KsqlKYWmB0xx0HHbBr5CgJoGjwvTbgLvvZz40WXvXo9ZqXDOs5UJLciaX3nJlwtT7MwfoVIBY9e
N/7ZbCxEJBIeoJ/CXYgAZOy19zxxCyLPMj/wGuNBF5w7kal0wS3GA4g6Hvt0X2/Q7sJ9C4iFcaO7
5X8wIOE3gT/DMe194pCRXcaNcz/K7lkgXR4spUrZoD1s7+2zFz02vZiwyeXZ2cXkil2BBqYiZn3W
H4wH8G/ETqZXrN/tDRlPwtt99N54GQPDUXuv3YezX0UESBp9OO3qi9dS5RMCgU545CXS9xpFMCtU
zLEHmvxRYmj/1jBylrRmRXGDdg8oPEuXMlFokX9w9wfu3qCuSWk/o9b6IAMQRMRngQCx0iSDhOGJ
GITEUXBNyXl6ahNCjgKUEzvOBVBOAq4U5iHJEd7kw/Tq04fL81Mg3YmZ8lMQFv0EEE39RTSRSaqt
bXBYxCqQHmnNAnJ4GAgZuUseLSpgEPETsRQMDw/BTwtJNLIHQDWWaRqrcacDvrfMZm1Xhh1LxI4F
DLB/kkngnXl+epykFvoKuYq/2+5ez0TKryESrl90IfdVtDE5u+DxhfQ8kVS00X26ZWMR8jgklo5z
h5IJkIwnqePU5HysXixhO9MQimHrHyctnWhUB7Kz6IRcpXCxMg+o7XsJSWr1PYTjjbLUViFbagOv
qSjplCdZ5PPeQUVFh09XUcHQcWwZqmdPUFDBt1NhBBp4I6V3Np8L13Ybi7jmNFU3ufgoPMV3Fvzl
xNtHP+EFuHd3d22Xp2DmVduNyLoBsHvzd9uwhlJPBTVUS7nyo7A3DF32J3aygo7qJJuJ1g8/sSvB
w52hLadxnBlKNr8HSxcibpXywjgQxyB5JeUVxCrO/XrunlAZvYAyqoGBqEu5WPpuvDOMpTCYAS3B
DLrp1fHl1cfJgxFeSNqxuIAGJlkisDuxw7ekVfH36yl/b/jmTbe7M6zXmh+0S7kA1uHjIeNIk8NK
LgD5bzIV33O7WOeUerAOqnDfhp8udgYWmTmOmbk42M5t34r0XaTj3LZbhVxJu3sVHFcyWp1iH+Pt
DM2V5uc4tgxPrtOlgJ0KJoB+KRSWvAth4S5pD+Slt3A/tLnztFaUe8+oyomePIRO2pbjcb5qCWaF
6sYSXE4C2vAn0HWDavQK16jDItr6gD6MV9Vxfvr3XRVeYOU45cRPtjzwaV2cTM46FgjMUqSTtxlP
PDtPWVQbaR8sX8vUqE6j4B8n73dm/CpbyFYViR4LvsqtYzHroBJOxe0VrMzsiC9INcdf6zPqlWpH
DXo+v+NYkjy5MhU8MEm/m0wDWUlvBckGC0jbwypW/0eplhn/4XRn2a3gCHm6FOJxOP3PxGPpdQoW
2GLx6F0qQrvFMpSaQ389crvPjFwz6VZha2rQBY9WtBywTWQRq/Kv1VIe+Fmw2lkganaOE4IAtDRS
j8IyjfldVAFiKNW4GlUxnN3KYAoCVVH0npFO9Kx10b/mYdi1C5ADWbbTm7y/uRR31VxpES1M/dqC
bJNfNYtKih2g/jt4pr+V0jzGTFd+KE5kCDbGVXWJrUq34T0ZHP4dPhNkRazH4DwJBE/O+WJhYSxp
D/Q452IB4nyYYxXdVY4oJneccxCflPzoym7J1SnRAFzMPCeBzGx3LWm17bMqWBmJGfxfwfkMsxl2
0MnA9C5O//hltOHRDkXHbBF2/qIPjgqujWLpeaGfQai15WdxodLHVx36NEvlza5sXJ02X2xaYmzh
uLT3+CZb2wdF0gMbIeVafr1qN8uN5P5zIOayOI4l1TbxKMMZT8/lYlFJOxVyfaVcj0oezuTO+hHi
5ji2AI/JL594cONHiwksI3w3qDjf2qV6Ge8y3PSsglvb4WF/Yl+y5w7MWJfRcTZIvYUa3kW3U2Gv
Iw2h3l7Weq9UucsEmlb2Kj/q9Qd/XYBwASa617sKyJy742i58r+P2M7LWbQjQdu1phrh1reqOnJJ
/mL5nPIwE8HnZW9nGSdnSJ5cSIBN3NaVMlOpDI8DkVRWChVyNTL3tmnhnhGa9tSAqyrIA/3c5nau
3K/7QQRxJQOtXapH6/DhpvshrPZ26BYN+JIEefL6nwfiMz1kA3bWY/VWvGEnZA09rqcSmNCl6/aa
yqLW2qd/tT9YU2/b1m92g/ciXUKWXQpVcfUKud4a9p5v/i1MHgkXp/+32LwCFxPAkqdv/KBqbotY
08jD3WN9MdB/+uZIKQYkAlukLRLbKQ+h7XoXeb7Lq7t79SuV/nBUrcugOIiLN/jsf1dG98JFMbfj
eGvCbIPNV4vMV6Kyh2sRv/LA8A0W+uRGVeDsPQONmRV3bysSbAEDk86H2IJgCPVGd7ip0d3Vvqvm
5jh67vzvY574Ye/mYu+2vMFoxKA6c2Ukw9Xx5J2FziLWq8zhw2H1pbW23tkq19wDcz4s1uC9Zy/m
hJYcZHGcCootjJzfn9GrOBvUYS7UVdL/41RiW+ox6tFIShUVyLZX0wlXfiTXtWTo//1KcglIoaMC
1/Yq+lHO1vWDxAdat//QoPosZ4U2NIrtVXHOI29dF0R9QoZ5uJF9mskDkKeAaITbHuMkkVCB09U6
zuJKHeveDrEaeZ+GPDYSFugtkR+hgelSxhvgE/kJGeE5zcsaQgVClPCMSNtjm4ogWIdG1Dqy/T/O
gxXIU4A0wj0C40bzbbTeH4nRNuSj7XjF79chIvGBh1j/BRUr5feFXjSibZ6HZUHqX03s52GG8tDr
bH7kz/17v7rVefCsB+yaoeOEKEIKVi5l2eaZEY+v5Kndk+SUqm3XHrHiUmNnW3k8TqUHGMq5t3FO
pUSU+jxQkzPbPW1yfcU/2PQwSOmnLrt9+c4WY1ePhSrQ0A/9SFwKJex3K0vaV55j7tJ4uBeR4ITg
edbcj1g8+EksK68V1y48ofX7V+VRrkUqVwGFiFvgxbfscKOj9iohkepvwQ8efpPwoQfp1nuKawjB
A2j5oqBnaXzhDUOUqzx69vuFxAS08JMfBJc8tTc3CtIDbyntZIMuf9cHzIqd2gVXyr8Vxp7VZrDZ
eCsDb5pij3jJo5uPcWN9e+8GhE9A+H/L/l6hKXo3Jk0D8ZNf2e+0iA9stGzcK3p0Hqiqy1ZtqakZ
yXTj445/Rb4HYwa/I8GPiwRgz6enz3Hapvn28elc48WkOGMnMpr7C4afnzmJE714k/jsvbxlvQHr
98ajvTEcfLw6wW9dRniD5tdC9R1NU56c4Atm1gUM76PeYW/QR+ICbgulJ466eBbye7ASftCmjgZE
UfiCSivW7+aB6o9aPSTfLQFT4Kv0SM7nSNAKbv2SiWR1JCOLlIA+87s8odzEj4mR/gyJhVBHWKbw
UyzrRciLCYkjU6/EwP7HQoEf9x1FMgl5QHcCiGTVCvzQB3CjbvcCqQH4WCuLPfCvXAIeRfhCvzAw
W9xd+uJW4JdWysh964u7lgfYONx31CM18CCQd6154C+WBWStGh75IEM+VtNCOcsJS554rkyK+ePb
2Fzx/Pncd6G1WR2RSvWHV6lMWlBvUtCHOiIMIF2grUnvOZU0JYRn3UIaeXN+fIUkVHo7hkwAY7yj
b+g/QJGlsqX4rTAikBVbZEZCOZcJaKZwCSMyfhxVBHF7FQbooAxzA3PJNzMQG79bQxdlwKNmyOgF
u1pCEWU5LsYTwdKlYBBWCg54yly0S8pmgvmRG2Se8OCArYUG8prKEEbOkUGdp+Jz0WQSnxgoZMlm
ieA3bCWzxPBi/pwBNmgxaQawTAJ+DVkPGL8XdwW7jifmHGyj2J2M/pwyHseCJwwVGAJYF/xhhd+G
4geMGvfdUkQsixcJ94BB24nQVTWzsROxF1dLyHqtQOD3Fizg0SLjC8Hwk1BSmXFr5cM5fezm/0pK
xaEnS+EaFNWB+K2lSb8iat/5N34sPJ+3ZbLo4FnnHEx7LefX76YfrvcGh63+NY4DNRaMxsyB5Lhw
GjjRpyU9bcEvY6Ev8xh+Jas/kwQzJTxSAUSSpy+TNklSkAOOREom9cSt7wq2hPwfkJFDYKz9qpyS
vocFulpmqScxYPRbJyiMSQtuIJXwtFjHGHwM3RSzhKki7Nbn7H8x3cAtlHby+jJmmORxIKwL7xhH
L1USpDGzaFNxwwhyDzghFARwBEIHiR/uhKrioZ7KCy0QawZClezPKMHlfAAxw0hn4K7gESjqbMWM
H8HtJh0WV0s1vPgERRCMCS7FPY9B76k9D8UEX7sBcbiChgOTFAN/mwnUByhd/JJx+o55AQU/YvpD
0FdmSigIr4G5ng/SsMDE3wJr4tsjY7iKM7/P6PNnCKdjtYrcK65uwOOTGwigNl7/CEYg/8xB4l3L
BCpkBi4Bd6smo7TETPoCl22CGkLQGn3+SmqBGoi0MIvwsRFQifeUXAbwQHAl8h7SKJSUFcIhV48K
0VCrWpx3c4xQ+nIbIrHJ/PTP+CF3QqM8gTWKvLA2lr0CBGBn1keNEIaWQTkmThituoRQrL4N5AwU
i40B02RGlQVzUigWfLZKQSA21aJ0aXJfoXl1pAOmO58EI2UzrB2mQhmSIr3MfXAXSFOQvyNiNYcc
kc+ozb/E4ohOu5CAQ2JooM5gngUJqUvemHUdShWUlVNINdz7DxcfW6mvCI9181nCq1TGNL9JVYU8
hptiEFJYISHLGGlwzlykXrc/1FLBgsOXVI4wFhVO6FJCNtIV8daDqSDVeOhjdEcLu2gdaZTGJSx1
I4hQ0Btmhy+pVasTanNAGR5jXd/mUMFFHhB9ZSTrdIQzfMAUghWObm+v34ywTSsMKoyFi4VQkVpQ
Vq1jPbYAAJoUsSphDroGp3q9USCDeqBRL3gyA/u3XBkEuoPECNuoVXInFMWMYWaMxCYxyqjk2lJA
O5KBL7xu5jmh5gzGG3RepQ+KiHtYelmbfdD1js7AI5YyC7xCEB8yyF3EStHRb/Ezf5AcAO51uxoj
e/GGImEtN5Kv6NEFqHkiwzzF4lhzvWVnJcumAMKYru4KG/zHGoedvLvMohul9X1OXo8JkYgoGS5W
EA3TrXCTwjOBBkTpm1rYA2AvU/JCVrmZTaAc7hk5T6UeVjcfFgHslPQwm4Oexdy2A8xUiFoux7dT
CLXxhXwivFBU76+ycqJIpGiLonUD1wh0JYTFH6wZsBHh2OVCAQR/MlmJAlA3puaqTkYzUdRESjcv
7PSVX8HAT1Yp8m6yVs9yZqx9NG0rzUWBtDLa01mlrLW0EMBC5+l0ZwyoxwLRyNRmP8A6BtR7BL0w
OO7J5GMTxoIEM8g/d76XLnXWpvgu2LeI/Zjtm8agbBkUKca6tc2OPYinJQ/m+H607mI8AX5mJoIp
tf/JyA7IojpbvKw+6ewegw/bIB40dWDjxJ/8CLpIgAVuI8i1sdZ/nESTvFMoe3ZsgnAQfYqADXsU
t8yp3ZPhUnWWLcam6fiO9bDZMJUFu0q6nHeUivLYUuSdpmNMAWWk7BMV68CSMs3AYToLV6sW34FU
1qT5wq6ybhB5E4lyAxK9YqJbjXshXDK4C0pMycPMkJYeMmYhXFqY9QQAom0QFPcW31TUSYlX+EPm
xBVZak0PykzXpaEYJdO9eP/h6mzMKOvCPzeDxVUEiytiRO/uoelIPDNzIV5h4uOKteiXG0SOlbyI
ShJIgl6Touf0u6aEYCrTlQndCJe6SDflyER9lZznMN0LTzFcEeCMK2FN9qoHgbJhlibrw4Xepgsi
dduvKWiVsKUgd7hCzri0MjstTEBi0vNh6deWpEVsubrFRECrIOyeMB3w4I6vlOZt+Fh+VMnf5EbH
ocwiuwAo07PlQqD4yM2hH7IhxmM2/PJQngDV07JrHtWqw3qH/Y2jybsiodeRM6G5zcQcMxFtn2DG
QjMUXPWmipX6dOab8lsoutjf+bhcFrj8ildma8DUoqKhoUQxpz3HPC2aNDbPArpNKnDVFoao7+pS
QkuwBNfj4BjANlfVZ4krIR0bCn+MB3+ECp0aC0yBv2YMVGhujAt+z3hdL7AGcqk+lP5QtQU56SX3
/ExZw4wduJGOglQPNX6H90O3gjkJd6/MflgpICy1BdeT0FZQWQW14OXCLpe9vS68yX933Kc1OqzH
M2Hsa8ZT2BO9pcBYY3bwJG6xjLPAcDPHWJpqjJ2IYrIF2kOh9R5di/xIoSZRlSHk6hS3XAy1Z9ID
7o+NmW7ucpPiryNlMTQ7uuPTDknJQzcahhdw2cdRZkJkOsLTO44TFUSi8XDmg+frW8zWnF6jj3Uy
wu0E/IUmpqm6xhon0d5rOvkiuaFft3CDp0opykmFGi9jP5rL0g3w15XGesq2td8HjRDJF8loFWKb
TxGiQL+qEBTXLeYyKy+TwOBrnPHFAqqP2Rwotl2wR8TfqbrZjEbLg+zUJnlQX9qVycT10eAT+upY
GyCJWqY4lx0gUWVsbRid4J4hbWKJQMZYrZr0+QtutoAkphWDzmQOnbIAZUN9irDO402mtOq9bG4z
Yea5hdVDZNBwqlQXuDzhGW5oIX05569qSsH3ODeoJPCh3GirnN1zrLf6BBsW4G+EGOfS0CVwdlwp
j9nPeNji+ItiSPgnctRZMG9D7N1WApGvF/SiLd++ptXYps1bWtxSFVPUMSBsesYPgpoSb4lOs5IA
dMRwtxtDl0pSOduY4Zb3uP/tfnN0eN9rDu4Hzf63vW89qMQ6a73Cx00uZpijgy5bgH8rfTYcvabN
bXGfiggVQo+dTqAOWb8S5tGDveIUysGi+D2/2MVbzYn6JfBTMdC/YNbSv5b2q/5JM/1GyMyFvmZZ
/hggDyByeFIS9O8V5mdZEhQnc/PCO7Du6ddM5mlcXF2E5fESolc/HYObPqvi6zR87hjO9F5ucTP0
hKs4LRGkHAXyLLjTyTnNisexC71cOXYFgOkH1MwRG+GXUz1Ezlr4MKrfHXUHcPjyHdhtPtgfCD7y
vNFocLC/1xt29/hBt9/nw9kBH+wPh72DWX/YFewlPnRbolqK98Niqfz7UulmsW5u6CHQSzE3K02g
0nwHYjR3OXSqQ5i2O9/fd/cPDvZGI5h6cNgfiEF3drh/6Hk0n1qGslShosBSVaS+Vj7cnMobEUGd
SQrKJ8FvICNoRdEn4ytOD0nyLzJ+9WN91m8PG7///v8g+pLS
===END CRASH DUMP===

**Comment by Gamecrafter** [comment]
@SoyPro This is a duplicated issue. Please read the **contributing guidelines** before opening an issue.

**Comment by SkygridRex** [comment]
Caused By Plugin?

**Comment by AndreyNazarchuk** [comment]
Its caused by a plugin, because he's running so many of them that they start conflicting.

**Comment by Intyre** [comment]
Make sure this is not a plugin issue. If you can reproduce this error without any plugins let us know!
