### ISSUE TITLE
Server RAM

### ISSUE THREAD

**Issue by DevCraftProductions** [PocketMine/PocketMine-MP#3700]
Hi, before recent PocketMine builds, we were able to control the RAM limit in the server.properties file, however I see that it has been removed. My server starts to lag while .5 GB of RAM is being used and my current host machine has 3.5 GB of RAM that is left unused. (It never uses any more RAM) I never had this problem while I could still change the limit. And I see that its compatibility for it was removed as I have tried to enter "memory-limit" manually. Is this option still here and it is just relocated? Or was it removed?

**Comment by SkygridRex** [comment]
change those configurations on PocketMine.yml

**Comment by DevCraftProductions** [comment]
@SkygridRex I have tried that before and it still stays on 512 MB
