### ISSUE TITLE
Player::teleport() doesn't return boolean but nothing

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3702]
Player::teleport() return value incompatible with that in Entity::teleport()

**Comment by PEMapModder** [comment]
Please specify the teleport() in which class?

(I just looked: Entity::teleport() returns bool, it is correct. But the implementation in Player::teleport() doesn't.)

**Comment by thebigsmileXD** [comment]
Player.php. Sorry, i forgot :fearful:

**Comment by Charelene** [comment]
Don't use PocketMine, it is dead. Nukkit would be better, anyway.

**Comment by PEMapModder** [comment]
Fixed in c1a484ee5cb8705f03e5021a64fe824796dfee14. No idea why it didn't auto close this issue.
