### ISSUE TITLE
Another player "crash" server.

### ISSUE THREAD

**Issue by gistrec** [PocketMine/PocketMine-MP#3725]
All player disconnect: TimeOut
And server work! But no one can join! 
http://pastebin.com/QKc9D6Hf

**Comment by gistrec** [comment]
![image](https://cloud.githubusercontent.com/assets/15942162/11299848/cafecede-8fbc-11e5-820c-c9b96b013990.png)
ooops

**Comment by Charelene** [comment]
Chill out, devs are afk and PocketMine is dead. ![image](https://cloud.githubusercontent.com/assets/12827721/11326694/8ce0c928-9178-11e5-9ac9-da509c6f6757.png)
