### ISSUE TITLE
Couldn't find a working PHP binary, please use the installer.

### ISSUE THREAD

**Issue by KeramxD** [PocketMine/PocketMine-MP#3727]
Hi,
I have a problem with "Couldn't find a working PHP binary, please use the installer."

I just tried every option of install and I have still the same problem.

**Comment by KeramxD** [comment]
[URL=http://imgur.com/YHyh5Qq][IMG]http://i.imgur.com/YHyh5Qq.jpg[/IMG][/URL]

**Comment by KeramxD** [comment]
http://i.imgur.com/YHyh5Qq.jpg

**Comment by DRedDogPE** [comment]
i could help you set it up on linux

**Comment by KeramxD** [comment]
Ok, please.

**Comment by DRedDogPE** [comment]
Gitter Chat?

**Comment by KeramxD** [comment]
I don't know how it works. But give me a link.

**Comment by PEMapModder** [comment]
This is not a forum.
