### ISSUE TITLE
Error when i try unload level

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3728]
Error when i try unload level

PocketMine-MP Crash Dump Sat Nov 21 15:03:31 UTC 2015

Error: Call to a member function getName() on null
File: /src/pocketmine/level/Level__32bit
Line: 2734
Type: E_ERROR

Code:
[2725] 		return (int) $this->time;
[2726] 	}
[2727] 
[2728] 	/**
[2729] 	 * Returns the Level name
[2730] 	 *
[2731] 	 * @return string
[2732] 	 */
[2733] 	public function getName(){
[2734] 		return $this->provider->getName();
[2735] 	}
[2736] 
[2737] 	/**
[2738] 	 * Returns the Level folder name
[2739] 	 *
[2740] 	 * @return string
[2741] 	 */
[2742] 	public function getFolderName(){
[2743] 		return $this->folderName;
[2744] 	}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #48 [Protocol 34; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.67 #2 SMP PREEMPT Fri Sep 26 14:22:08 HKT 2014 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
SoldierGame 1.0-alpha by ifteam for API(s) 1.4.1, 1.12.0, 1.13.0, 2.0.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
SignShop 1.1.3 by xionbig, xionbig for API(s) 1.11.0
Lightning Final by FoxLIFE for API(s) 1.13.0
ctf 0.0.1 by Darkspive for API(s) 1.13
Particler 0.3 by Dark for API(s) 1.3.1

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWmtv20YW/SuzcoGNC1EPSrJsFS7WSJzd7DqJ1naQD9UiGJFDiWuSw3JIy2rR/77n3hk+pLhp
kfbDGkGged25577vSD/3yjhVvcV4Oj0fj8/98bjfU0Whi97i5165z7HUu/50fXv7/rbX76XKGLmh
uZcySUSphRSpSteqEFGVBWWsM7FR5TuZqhenAoOsShKci+KEDg1NEQxzHTyoMo0zNUzUo0qGN/T/
p08Tfx2X2Jtgpbfw55PpL/1enlSbOOstIpkY1e8FOlTEmD/3Z6C3KldlocqqyMSLOCtPxTflNjbe
9wTpO5DCtjPe9osdzDGwn855evjtt3Z4wUPxrbhlakaUWyWYL5EBC2+ajNwmOxrXR/7mODBlEWcb
u+i7xaEdTniYV+skDp4R1M921/QQkcOSF/oxDlXhfd/st9Amsw60yVkNbTI/gDY5/3VokU5AuIPw
ootwOvoCwun4AOHU/zWEr/mOLs7p5FmcUbPRwptOHTxYQVnIAHr/oXcyEi9OF6I1odXqThWPJJ2g
kGb7qkrzF2utEyWz095/+r2NylQhE7IZ7DJgClTHg7NQPeKWdRUnYW8xPYehFbrUgcbOybTfk3nM
+8aTwQj7NjDMRW/0O/9woJAPSbymM4M5U6hYyIveTZxVTyLRgUy22pRiMpgOzubixBd3b5dieXt9
/XZ5L14XsbhTufDPxHi68P3F6Fz841/3wh+Np0IW6eOcnCrf5qA4G5wNfIx+Uhmg9HwMR3bxkzb1
jZjggczCQsdhr/EsQ5J5pR7vITP+7PhspvoHchuPmLisyq0uDGlkyap4C1WIeyVTkjkL7wfsngzG
NFaZXCcKzJVFBR8OVQ5W6TDWjI7KV92JVJK7N/evVh1OEi0J4t391e39hyUmdmpt4pL43ZZlbhbD
ITS1rdaDQKfDlrNhQwO47xEbXsrcVInq4O3OHkEGiAPEr2XycACTZPKVMDvXrlaHPDiwy/d39x/f
39686sKlqAood3CZWBV/ZwgNlO7sIZSRJ5N8Kw/hxFF5rLcpQwZwn7XduIH/R6Dae+CvLXsHgy/q
1wFG9lFZGSMX3C87iA+mj7V3aK9dmAzvK9F0r1ytjhj4Hapzxqkzte8A6c52cUwh+CMrJLtGyINQ
i38u32HtaOIA6B9QW4el1eqQvy/BfM4hDzkcdomRMceb7G6r864l11PHOp0cyuIJK+uYElP96QD9
+OvR1xzAUltefhM3YDtGBpkqjc7MQBeboYu4w4YUUN/Em22ZUVZtYbdzXdyv40wmR5FIP928eX19
iHby9Wibi1erLg9fxPtueEU4gjLqIKBRl/fR5/b7ShYPJo8fVcs9Mf+VnAcSmYI//z7vk0UZB4kq
ur7XzHU4Hw0mn3H9Z6W4vL4QftW5+zeCIGVuWYBleFF9AVdAA1QwuQIdRYn+ZNmMxEudRfFGUA2+
KlbZyZ0sxTv9KPyxGM8WI3/hT8SH+5dUXcxog6XnkVwuG59diOW1sLVWZ0+ui/JyfDGe+DS5wYkU
FfrliEapfPLyRO7B56XPMyaXu8yjSktxfXjpjWl6twW8JDblpY4imrDS9H6sVLG/1Flnqghwyu0K
lQmKOGdCljGRylCJysBsRZv9vbdLZkeX4eVHlSASKfE3yxg1MFR9CgvnLx1k1PpcZrpIZcKnAazY
e0mcxgCMIu8tzSbSlF6Vh7JUNVcyyzTKX+WgezLYxii2U+QH47A8xmrnhcArse9yzqeSRO+8KCGv
qylZacksBgv1UTuX6nU9sZVFGOiiuT5/zN1KGEdRHFRJub9kKdtKuNSFZ1RZQkTmkiFQJ2B1nej1
et/OGaXCzhYWyKvr11cfbu5pllQxyKUxO12El9/yH4BUpfaMfFSOC9at11VupAtIpzEVN0sVa1PU
D/ZpQjYs3sJTRMDmW4F3ainIitG4FEcKzk7E/VYZJWpwKJMVtzrIL9TzwOYD0k0p1krEWZBUoQrx
QXzmPUTrjoxER0TgmKaRkeoLjZXCEEmxLpR8EHtdFY6WiCMBbHEU8w1QTwF7T/ZE+J3aNeSGoYok
FGTETmd/LYXMcyULQSJMARYtQrKnHpotlHHvtioTVb4pZAgCg1VG5mqJLVaZOLnfFgrSxhS4SGS2
qdCsC2qaWWTOtA3aSduCxD+xUOnoy60KHIrDg2CgzuUqG+zihzhXYSw5o9FoeAPlftLRpzd37z+d
TS48/xOdgxgbQguxQoTcrHp00cetItmR66FoCgW9I9jGEmoqZGYSeFNol1mazCn4wCdVskrRvMWB
Elt0MwkrOQVha1ftlfxigHmzrcpQk9fYtwtixoWLINFGhZatK/JAQYZK0cOlavEYS/FvCkPYwuHI
cysLQZGeDiKT74QkKzVoO4W7xapKOkKISTBCZAUYAqO7Wr7BTqSVkOTULnhgaw2mWvLXHPhqOkAs
yN0FzBUWQayu98LZEba7MNmstmI4+RhD0DqDSckwFIUy1vKITdjaA9iRpio4UAnY21qRPCB09WMl
+aVng2SdiUeZVEq8cFciZ5yCuL0P4VlRQvCgzc1GFQus0s3vKn4ggjtdmX0W3EvzAIsvHuBAA1r/
ACWwfdYgade20AikMAnsNn3an4TCxTCYbB9iSCE1Q3maxYI0SXNplcFzaAvTvmOTAR44V6GfEEuR
avYEh009a1gjqVp23kTkofy2BU/si7j8Kz11FXwqVJS72AqPzooXQAA9C58kwhg8h3LBlMhbbRph
X/07wi0ES9WBsNOCswvFpFRt5HpfgiFxZ1kZ8eWxIfVaTwemXcyMsbAFJRCXpdyUYblEMcwFYQpB
PGNSEWJEfaNV/5aSJhntRgOHJtcgmeGeDTNp095CjFYcKjgqlwg1Mvw/Z58qrS8wT8nzDzFvSp3z
/S5UNfw4aigsqoJyJKKM44burFkaj/yp5WqpilhzOiJfNHRhwAHZcdf42xhXIdSEZGO8w4M/KOtp
HMY1+tAMHgq5UXT4NbFacSI7JxzhydftthUnXKIB72s92YYjuuE9hRDKcLx98Plmgu3qYYgwVwEl
QvvsSLxaGduzDQBIUuWmhTkZOZzm9FmGHOqJRb2RxRr69wKdJLayJA97VqpsTsSKOyPcGU3FY1Zx
yu1ygXKkgi2c9uuYcGQMzhpsXI2iOjakrZUNxHub73gEi9jqKgkbRmJEkF0mWtbJbkXOnAPgGUpN
xihOXrMnfBYb2Vbs6QZUVOi0DrF01q173ajU0SlAONUdm8Iz9tM5RxV+sK2yB2PlfcNWTwGRJ4kz
6mYIjbDlcJ/ds0ABYuwmj2oAqmVaWkSqVrNzlIszx+crbY8dq4+SAFVK9liXgr3FbfsTMHMi8gKU
9cqidrZQX0QLTfb+IqlVlqmSdNGUbjCNxGbCtSzRN1AhIqnKRQKEPbmoxA5oC1O3aoPRWjU5kcPN
STd81Svk+MW+JNp94Y07xky5j6/1ypoVhJXZmY0qba7lboASXWjDnVOgPYtJx9NA/APNDMR7iVoY
hvty+aGPs+Bgjfizi8Nya6M2+3dD3mPyCzF3hUFbMhgWTGfrQFyF8KetTKIhinxbxYQKduYuwpXW
/nTWdcgmO3dodeqk6ydyPiqDZNK3jk0Xf4wzVJGABbNRbNqU6z8ss2VdKbQ1OxVBdGiHWL+igj3L
PTfs1mTUwq6rzcIVHd+LMRUbLrNQVcnLdUVpOI5tVV1prpwqkEbaOtGIIdrKsoLBDDeBFS3iWmha
s6ubu4O2QdU1JLENILZh4q3Ouggt6zuADEs2MHfEs0cWIsXSxrUTwMNPIcQtLA42yjFJHtBH4KSG
rOxczw35Z9ywi7LmTt69v79eCA66+BdU6K0y9FZMKE7zhAtYZs/d3LDXaPjqQFkB2ggEEoeVjYgz
EjghoynJcPyRyyAUyWxiIiuiXpfmXTZyTn84XYcwWwrfkbcSwLU0qnPZizH85Jlb+sLHwvi5BVUG
g1P2WaO6XLA13BNl6qzcA4xQiEv2Psr8VpPcw7bNLcUBboKoeKJoIJOd3BtL29Hp2O5B+GYzukp1
lXXjv3ElW80EsU/UqGOgJxZ8XIjprx+VBWZDy7ulcZh0xPjCf/Y0W1embBu5VpbaWkUUiPgJhQIW
qaGhah9WOpHPBr47+YicS+VdTN2you4r37uXAZeKmnqG40QkTclSZbm4KBZVCW/TBqbqkYfGgc0k
3IEV1I7DMEC2FtV/NTVC1jeMTMlWUg6VlF8a/EfKIIHWyngrn4Q8lgtaoIDTQ2sPh7pgI72VYVyZ
zjGnByk6r2b2qLM72o9ihUISvWC5J7GWQXTaStpL+C2ojUaW8bavq3kffM68C387GXOLjna8Uk6/
7jy7Pc97BspaiPOvopbrvEocNfeZMtMR4VXGPulBesS0fafz2I4MSZJEmSJUl/Ti4mbHLjzQA9lC
2NquVil9ZV3lqHVswWcNkoOHrTMcLVCZ0yl3IRGd0XAn6aJmkudkuo5h+XaLe5uzLfrCBiN6TaCv
zYWdtSnWGYm1XlfIN8GN7Nqj953DmSadHMzm2zzOIt2aAX3lvbBXDjrPfaiDmL9MZ/uUqnz2EAP5
moZRalvcsmiXmWHYmhRys0H2cW8DzasLlYj044GH59FYfoiceY4fkpc1ZVbx8WnYhF1dWAUUmedy
c1sA8qzOO+9FL+nJkN+wVKJzylZ9jIGAHujKuhJDYRKhUFYQNvJTRmmeNrnUap+4ZZeIcN9ZdEqI
CvWmKW2CqwOeo0Yasss1fXMklN1u95xIkhjpxmrl+klSvrUDqldA3zGxqLnhJRg7NcoL8QN99JBk
+tw5/4co2ihYlyHdx1YGUbcLtmern7C5GXvu7ZZ7W85ihisGgp2ikIjBqEvxHdb5VmaAPwl68SbX
5ZTU3rYQr2+u7hf+d/P+7OJp3J88Tfr+d+PvQmRiG7VelIXCABHm8nwkNrBvY0fT2Sm/baunUmUk
EP6NxUvkoc4vN8iEOkOkg03zg6c8oK1uYH5M4lJN7M9KPPsTlp/s70zsN/XrAHXNtv21lEzgObJo
J+wPuupRVSTNIIqTkr4PA+mx/dI8KvNmdZO2n7fwXvtzAmz6r3Ffyvr8BV+6dr8RqjejJtznZYug
lMRQ2IF7t7zhW+lzHqCWa8/uAZh/1OI+iRl9jzgm5MKjr6v80Ww0wcdv3kBv0WQ+UXIWhrPZ5Hx+
Np6OzuT5yPfldH0uJ/PpdHy+9qcjJb7BTcstiYV/0cAXaxM/tUJ3vbrbMCagtypyjSZm+b5zNYsC
iUp1imtH0XwezM/Pz2YzXD258CdqMlpfzC/CkO8z21S3IjTsWOYQaWyFj82lflAZ8kzRzHxU8gER
wQpqMMPMXvJ3JPXvU36KczvyB9PeL7/8D5fyq9k=
===END CRASH DUMP===

**Comment by Tee7even** [comment]
No one cares, PM is dead, use something else ![4head](http://static-cdn.jtvnw.net/emoticons/v1/354/1.0)
