### ISSUE TITLE
Raspberry Pi 2 Model B

### ISSUE THREAD

**Issue by Bruce-G** [PocketMine/PocketMine-MP#3730]
I am attempting to setup pockemine-MP on a new, clean raspberry pi 2 model B and have run into a dead end. (See attached screen shot).  
![mine error](https://cloud.githubusercontent.com/assets/15968464/11324810/e8e25296-910a-11e5-83d2-8fe75543f83a.png)

Notable errors: 
1. invalid build detected, please upgrade your OS (it's a fully updated version of raspbian jessie.)
2. "Please install 'libtool'" (It is installed.)

Prior to libtool, I was instructed by the installer to install autoconf, which I did uneventfully. 

I should probably add that I have attempted to install PHP5 from the default raspbian repositories and several dependencies failed to download.  The installer did not suggest that I install PHP, but the website help did.

Any help would be appreciated.  I am guessing that installing pocketmine-MP on a raspberry pi would be quite popular.

**Comment by Intyre** [comment]
Read http://pocketmine-mp.readthedocs.org/en/latest/installation.html#installing-on-linux-macos and use the alternative url.

**Comment by Bruce-G** [comment]
Success, thanks!
It looked to me like the separate URLs were mirrors, so when the shorter one downloaded, I didn't try the longer one.
