### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by Tee7even** [PocketMine/PocketMine-MP#3731]
![Updates?](http://i.imgur.com/hwVkKHw.gif)

**Comment by Charelene** [comment]
It is.
![EleGiggle](https://cloud.githubusercontent.com/assets/12827721/11326478/7719bc6c-9173-11e5-95ef-2429fbfcd732.png)

**Comment by tiNsLeY799** [comment]
This is not a forum. Please only post PocketMine-MP related issues

**Comment by Tee7even** [comment]
There is an issue with PocketMine-MP - it's dead.
![kappa](http://res.cloudinary.com/urbandictionary/image/upload/a_exif,c_fit,h_200,w_200/v1395991705/gjn81wvxqsq6yzcwubok.png)

**Comment by tiNsLeY799** [comment]
This is not a forum. Please read the community guidelines or state your
issue other than that, please post PocketMine-MP related issues

**Comment by Charelene** [comment]
The degree of PocketMine's aliveness is also an issue, y'know.

**Comment by tiNsLeY799** [comment]
Please only state PocketMine-MP code related issue.

**Comment by Charelene** [comment]
@Tee7even, let's go storm some forums 
![Kappa](https://cloud.githubusercontent.com/assets/12827721/11326524/696c4b1a-9174-11e5-83b9-5746d3fb3ab6.png)

**Comment by Tee7even** [comment]
@Charelene There won't be any results, you can't resurrect the dead.
![kappa](https://cloud.githubusercontent.com/assets/12827721/11326524/696c4b1a-9174-11e5-83b9-5746d3fb3ab6.png)

**Comment by tiNsLeY799** [comment]
Please read the community guidelines before posting

**Comment by Charelene** [comment]
We've read them, but decided not to pay attention to them, just like PocketMine developers.
![image](https://cloud.githubusercontent.com/assets/12827721/11326573/baf8e438-9175-11e5-8ff8-016bfc3a68db.png)

**Comment by tiNsLeY799** [comment]
Please post only PocketMine-MP related issues

**Comment by Charelene** [comment]
Nope. It IS an issue.

**Comment by Tee7even** [comment]
Please post only PocketMine-MP related issues ![bot](http://images.akamai.steamusercontent.com/ugc/704037974368409427/AC7EDDAE7F45D1FEB9DAEF0EEEA3CB77FB9DD10E/)

**Comment by tiNsLeY799** [comment]
Irrelevant. It is not present, nor relevant to the issues. Go spam someone else's threads.

**Comment by Charelene** [comment]
Irrelevant. It is not present, nor relevant to the issues. Go spam someone else's threads. ![image](https://cloud.githubusercontent.com/assets/12827721/11326601/59be1a2a-9176-11e5-8078-d0ea67f6fcbf.png)

**Comment by tiNsLeY799** [comment]
@Intyre Do something

**Comment by Charelene** [comment]
Just close the Issues section! ![image](https://cloud.githubusercontent.com/assets/12827721/11326623/b85a6b9c-9176-11e5-9994-bad2349c04c4.png)

**Comment by Tee7even** [comment]
There's no issues, it's perfect ![bot](https://cloud.githubusercontent.com/assets/12827721/11326623/b85a6b9c-9176-11e5-9994-bad2349c04c4.png)

**Comment by Charelene** [comment]
PocketMine is life, PocketMine is love. ![image](https://cloud.githubusercontent.com/assets/12827721/11326632/ef889620-9176-11e5-9fc7-08e310d589a9.png)
