### ISSUE TITLE
@tiNsLeY799's battery is down!

### ISSUE THREAD

**Issue by Charelene** [PocketMine/PocketMine-MP#3732]
Do something! He doesn't answer with his templated phrases! ![image](https://cloud.githubusercontent.com/assets/12827721/11326659/78353ff0-9177-11e5-9f1f-4f1cd1d4f1ca.png)

**Comment by Tee7even** [comment]
Oh no, we are losing our bots! ![bot](https://cloud.githubusercontent.com/assets/12827721/11326659/78353ff0-9177-11e5-9f1f-4f1cd1d4f1ca.png)
