### ISSUE TITLE
[revived] PocketMine-MP is dead?

### ISSUE THREAD

**Issue by Charelene** [PocketMine/PocketMine-MP#3735]
#RIPPocketMine
![:(](https://cloud.githubusercontent.com/assets/12827721/11337255/46d74214-91f4-11e5-97e4-4df5242c5289.jpg)

**Comment by PEMapModder** [comment]
Please stop spamming. You are annoying.

**Comment by Charelene** [comment]
Well, there's no other way to make it seen by devs or something, unless you have a better idea.
And it's annoying to us, that no one gives a shit about PocketMine.

**Comment by Intyre** [comment]
Stop or you will be reported!
