### ISSUE TITLE
Crash on Connect with some maps

### ISSUE THREAD

**Issue by 3rdIteration** [PocketMine/PocketMine-MP#3740]
Hi

I was just experimenting with the latest bleeding build of 0.13 and noticed that on some maps the server will crash when a player connects with the following error:

 ClassNotFoundException: "Class pocketmine\network\protocol\TileEntityDataPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

Crash dump below
--------------------------
PocketMine-MP Crash Dump Wed Nov 25 09:08:07 AEDT 2015

Error: Class pocketmine\network\protocol\TileEntityDataPacket not found
File: /src/spl/BaseClassLoader
Line: 144
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[135] 
[136] 	        if(\method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 		        $name::onClassLoaded();
[138] 	        }
[139] 	        
[140] 	        $this->classes[] = $name;
[141] 
[142]             return \true;
[143]         }elseif($this->getParent() === \null){
[144] 	        throw new ClassNotFoundException("Class $name not found");
[145]         }
[146] 
[147]         return \false;
[148]     }
[149] 
[150]     /**
[151]      * Returns the path for the class, if any
[152]      *
[153]      * @param string $name
[154]      *

Backtrace:
#0 /src/pocketmine/tile/Spawnable(40): spl_autoload_call(string pocketmine\network\protocol\TileEntityDataPacket)
#1 /src/pocketmine/tile/Spawnable(67): pocketmine\tile\Spawnable->spawnTo(pocketmine\Player Player(1))
#2 /src/pocketmine/tile/Spawnable(57): pocketmine\tile\Spawnable->spawnToAll(boolean)
#3 /src/pocketmine/tile/Chest(46): pocketmine\tile\Spawnable->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.}.pocketmine\nbt\tag\String:Chest.pocketmine\nbt\tag\Int:83.pocketmine\nbt\tag\Int:67.pocketmine\nbt\tag\Int:131.})
#4 /src/pocketmine/tile/Tile(81): pocketmine\tile\Chest->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.}.pocketmine\nbt\tag\String:Chest.pocketmine\nbt\tag\Int:83.pocketmine\nbt\tag\Int:67.pocketmine\nbt\tag\Int:131.})
#5 /src/pocketmine/level/format/generic/BaseFullChunk(171): pocketmine\tile\Tile::createTile(string Chest, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Enum:pocketmine\nbt\tag\Enum{.}.pocketmine\nbt\tag\String:Chest.pocketmine\nbt\tag\Int:83.pocketmine\nbt\tag\Int:67.pocketmine\nbt\tag\Int:131.})
#6 /src/pocketmine/level/Level__32bit(2522): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#7 /src/pocketmine/level/Level__32bit(2183): pocketmine\level\Level->loadChunk(integer 5, integer 8, boolean 1)
#8 /src/pocketmine/level/Level__32bit(2796): pocketmine\level\Level->getChunk(integer 5, integer 8, boolean 1)
#9 /src/pocketmine/Player__32bit(706): pocketmine\level\Level->populateChunk(integer 5, integer 8)
#10 /src/pocketmine/Player__32bit(1560): pocketmine\Player->sendNextChunk(boolean)
#11 /src/pocketmine/Server__32bit(2485): pocketmine\Player->checkNetwork(boolean)
#12 /src/pocketmine/Server__32bit(2222): pocketmine\Server->tick(boolean)
#13 /src/pocketmine/Server__32bit(2100): pocketmine\Server->tickProcessor(boolean)
#14 /src/pocketmine/Server__32bit(1701): pocketmine\Server->start(boolean)
#15 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Users/Stephen/Desktop/Minecraft-PE.slapperdev/PocketMine-MP.phar/, string C:\Users\Stephen\Desktop\Minecraft-PE.slapperdev\, string C:\Users\Stephen\Desktop\Minecraft-PE.slapperdev\plugins\)
#16 (1): require(string phar://C:/Users/Stephen/Desktop/Minecraft-PE.slapperdev/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #49 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT STEPHEN-PC 6.2 build 9200 (Windows 8 Business Edition) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWntv28aW/yoDpcCVC1ES9bLMwsHmus7eAInjvXaRxVaFMSKHEmuKZDlDy7pBvvv+zpkhRfmR
BL3FYv+wUTSc13k/Z/S5Y5KN6gT+ZDKfDEfz+XGvk0ptzssyLzvB547ZFVjuZLlJQtXpdTZKa7mi
qTPs06LIw1tlNkmmFotMmW1e3i4WRZmbPMzTxeI6SdV5ZhKz+1kaeSlpswAwEedVFgFeXKXpW2wC
wGIty2AwOAsGv2hV6sGVUcVaZYOflb41eTH4ACRhKWPjXZ73dSqLQpWRuhtcMgm06n247BOUgS7D
gS7Swd+lVkzn+1xGqsRiQTgtvud2YUcKYCyUXseUEowHv3ZeDQWf2HM8MAA0uCrkNpPLVHUnw6NA
AOCNrEyeAtZNKNO0q02ZZKs/I6kjkPLK/xba2THQtqHT+mLRbPBea/q8zrvtTZep3KlS2H+6/hHj
Gn0L1/R7cb0B48s8T5XMGPL4achna6VNdzL7FtSbmzDPIMgqNAdcpOpOQXhxXm6kWSw2YalWSZ4t
FmfrKrsV+fJ3FZreoeyX2GjkCnvyTUFm+I3lz/2n18+zahM8v/S5/+WZg1dsEAHz/syWd5kJ5uOv
LM6Ov7Loj/3+Fxb75Gmxk7F15/6TUmeyXiT+ZyU+fSRxltjACmywUpkqk5BjzlvEPpZa1z9+Whek
pyCAiKVRrDMXS5iRQyG/6OXrepk9o5f39P+bm/FomZjuaDoaPVDEA7k6/S0WBwr0XidZYqwu21Hv
+LuQ+vPx00h5m/eaUomFnWRGrRC1pz1Rf857wmEUPuOcfxfO45PZV3GulPl+lCePUNq0UmM7Hn4d
WZEXVQoTfx6jzYTDb+Dxp7PhA0R2A9KSyqILdf+EjvzHCfZKlXd7qKPJfPoM1HCtwtsLm8wPgY6+
BXT0yNLsBu81Kq0HwMbfAuYPh18BdlnmIcq2vDyEOvkGVP946D8DVRtZmkNoj+Pevi5Dgp88A+m5
NEMhR5oEyb9VmT0ZxSqESr1YfJBJ9j5frVq76sLrr6srG5hnwWLB0CiGMbjFwsEDKU8DXCz+zeNF
Wq2SDGesxGeiS/op1R9VUjap4S+uop/UJ9XRR53fvvQ66v+sT/j+mh1kWUl1AtiV6nXCPFJEoz+e
AgS2+uMZPhZGuL8k7iJjKrPOoxt1n2ijuz9kcqN6YtHJsz2aaNE5EhJpspuprfinilPYWeJ22CNH
Rxw7PzCw7uPjyBT6ysCyw+7R0Wem5Zhp2VPDcILg4GT36CfeOz+g+wvPnRzM0dRkeDD1g1knGsGK
wCn962/i1OJgkBPfyWQywodo/ZXKVGUmkE0hRbt33NryRaVaQXIOOpi+lKXKTPdInJ6e4liG7GhZ
nEwO6DHrMt8KEiFzeJGbt6Tl8/tQFSROiM0aDVO5NwOIz5IxbZPBM7OaiePWUsNALEGqPTp36/bY
iTs2HbrpwY8/8tivwfwINRMUDaqVQEhag5aSByxP5KgYJrHjU40ELZDxHsh/FLKUm9r9mS/eMtmf
+PLSa770mi+95ovEX3rNl17zpdd86TVfes2XXvOl13S9Zq/D0VCm1MhBmxr5BrWz358BIEhcVkka
dYLJCZo/V+d2gvG815FFwvv8cX+IfavEYDj8zj8cKOVtmizpTP+YIVRcvAedT0kW5VstLq7F1fX5
5T/OL7zLMzHrjwTTIk5Gw6Ho1rvm4u+VBjvoas6jhLqcI5FM5zMApEepoDPtz/o0+heCB4YjDId2
8SbXhO7dxcU1JniwRXPbtLmY+BXy4Q5DGYjGjjVbfR/SgNRNoujcq8tmJM7yLE5WghrrRbnIXn1S
kbjI78RoKoYnwfA4mPrizfnP12I09Ke0wwL0iP3TRrOBuDwX1sFae4q8NKf+iT8e0eQKJzbowU99
Gm3kvVdwTNOnkyEfotrbI7XZdvrUn9H0dp0Y5aVox0/zOKYZZSv0PypV7k5Rb+ynSni2m6HPfgE/
RqCMTn/kP2DNTfQs1TLLUHKEytHlyXCdIFts0M1qBxXNVb714jRZrRtyLN0ySzboL90+O7fJl/UE
kjkANyKwk7D4KMxLVUMq7or6M0riOAmr1OysuKzZm7z0tDIGXqdPaZqTmtUF+Eyj/ZxWKmptoYuZ
0yWOqjKjuiJlbtA0elre1fSQoTXO199tUrIVQWFOhGwmFUiAZthauAE+cGFYj7hGXaVETaOQpeIm
OYfJ40MaEZKUjVgqZNowrSKYG8A/slKCdZWj7c9jAvAQppax6okcK6UmkGKJgvVW7PKqdLCoIYeo
kzhhDBBzCbNKdwT4Qm0bcINIxRJy1mKbZ38zgqKTLAWJZkP3M9D4DuQLut6wfG8R20RVrEoZAUB/
kZG9W2DBIhOvrtelgsGyrEUqs1UlV0rQ7ROLzPmGTjBOc8BP/sVCpaNnlNwtF4cHQcDamEIjzKqs
v01uk0JFiezn5WpAo8F7+MdNHt+8u/p4MxufeKMbOgcxNoACseiobLXoEKJPa0WyEyYXVKYIcOkS
BdRUykxTbRTZZZYmUwo68KUMqxQBNwmVWMssSlnJGwC2Zr5HyVcumNfryiAAwiXshSARYx1PhGmu
6U6MyHpD7iXI1zmv2Lgm7hIp/oucHVvY6T23Egi6k6KDV2uck2SlGgWCcFisqqQDJCoNI4xUAUNg
7t5cvhP2uo/ktF/wQNYSRO3Bn3N4qeHQ1R+5rYC5wiKI1OVOODvCdheMmtU9nE8J5JxnsCgZRUij
2hoeUUlVE6iRuio54giY21KROCBz5FuZkjZWyR323sm0UqLrMCIyHwG4RYcYqCjselAmVSYBVgnz
RbVZUp0Sizd6l4XXUt8KKiHhP31aR+aO2DxrHmnXuswREWER2K17giOMcJEIFtuDFDYQmqYszFLZ
qiXNbaoMjkNbGPYVWwz4gW+V+T3ipFEQAdhhS88a0kiolpx3MTkobSFHRFVu/gbJmZJPRYoyBBvh
g7OiCw6gZjEiiTAPnuMyYEjkrBSCyx276n+m+RKC1XlshJ2G8W0SQyFpo1ZyuTMgSFxZUoaMPNGk
Xevo4GmbMGEsbEHJwcKp5a9ZLjGqJXwIhOKMQcUIETVGq34wU7HNrnLwkZNnkMyAZ8VEekxYIIYL
jhQclA0ijYz+n5O/AaVfIZ5y4L9FvEaJyfhdpGrocdC0gEtRIYAg46ghnDVJ/nA0sVRdosvOORuR
L2pCyM1WTV3jbz5QIdJEZGO8w4M/KOtpHMXzDPELHgq5UXB4TqxWnKhvUg7w5Ot224LzLcGA9+09
2UYRwvCRQgglON7ef7yZ2LZhKIIICxVSHrSX10SrlbE92zAASapC79kcDx2f+uhJghzXY8v1SpZL
6N9Dxe2eQ8jDnpQqmxOR4s4Idwa+u5FZxRm3TQWqkQq2cNSrY8IDY3DWYONqHNexYbO3sr74aNMd
j2AR67xKo4aQBBFkm4k96WS3omDKweAMLQDzKF69ZU94FBvZVuzphqm4zDd1iKWzbt1rR6WWTsGE
U91DU3jCflrnqI4O6YZBW3m/Z6ungMiTRBld5hA3wta1PXbPEvWHtps8KgGolNnDIlC1mp2jnMwc
nT/n9thD9VESoELJHmtDsFjctr+AZ05EXoj6XFmunS3UiGihSbpfBbXI3LtIU7nBNFKbCZfSoAGg
OoRfRuiNB3WmjUrsgLYudas2GC1VkxM53Lxqh696hRy/3BmC3ROe3zJmyn2M1jM1KQgr05mNKvtc
yzU9JbrIhjunQHsWk46mvvgHGhWI9xSlMAz37PKXHs6CgiXizzaJzNpGbfbvBrzH4ANx7AqDfcmg
WTCtrX3xJoI/rWUaD1Dj2yomUrAzhwgorf3lWdshm+zcgrWvFl+d35PzURkk0551bELsuui+gNko
Nm3K9b9cZpd1pbAv2akIokNbxPoF1etZ4bkhl2QOFzottaxWgSs6Xgufig2XWaio5OW6oNQcx+jR
zxaaC6cKpJF9majFQBtpKhjMYBVa0SKuRbqFtO7RDtoGVdeQwl792oaJtzrzInZZ4fZ+PuKylY94
9kggmlt4yxA/fRO5MDkYKQcleQAfkZMaMtNCD2Gax9Swj7LqXl18vD4PBEdd/BdWJb34QugEKNkU
KVewTJ7D3JDXqPjNgbZCtBGIJI5XtiJOSaCErMaQ5YyGLoVQKLOZicyIeliad+nIef3hdB3DbC18
Re5KDC6lVi1kXR+O8gSWnhhhwX9qQZmwf8ROq1WbCjaHa4JMnZW75xAKgcnio9RvNck97L65pUDA
TRBVTxQOZLqVO21hOzgtOzqI32xGbzZ5lbUTgHY1W00EkU/QqGVAbKbPQEyePypLfqZh2i2Mw6wj
/JPRk6fZujJl28ilstCWKqZIxPcjFLH4Ob2Gam9NWqHPRr4reYekS/VdQt2you6r2LmbAZeLmoKG
A0UstWGpslxcGIurlLflGqbqaf71hU0l3IKV1I7DMAC2FtXvOXVC1jc0/QaBfiVPRk0JpuH/gTJI
oLUyPsh7IR/KpbB34yra28OhLthI/ymjpNKtY04P0lHHTmqPOruj/ahWKCbR9ZRXFRFscU8gOm0l
LRK+TttnQUv4vrGrae8/Jt7Fv61MuEVHO14pp193nt2e5z0NZQVi/qeg1Q80BM19U2p6AHiRsU96
kB4RbS/hPLYjTZIkUW7otp9uXNys78IDXXwFwhZ3tUrpcaEqUOzYis8aJAcPW2g4WIByTKccQgI6
peFWEqJmkufkZpnA8u0Wd+dme/TABiO6TSilXgs7a3OsMxJrva6Sb4Ib2bVH9zuHM006OZgt1kWS
xfneDNY56Z5Rtp4x+yiEmL4sz3YbKvPZQzTkqxtCqW9xy2K/zATD1qSQqxWyj7scaG5dqEak37Tc
Ps2NpYfA6afoIXlZU2YVPzwNm7CrgVVAmXkuOe8rQJ7Ni9Z90RldGfIdlkrzgrJVD2NwQBd0pi7F
UJnEqJQVhI38lFGep00utdJF/gr+2AIi3JNEq4aoUHBqYxNcHfAcNNKQXa7h6wdC2W63T4kkTZBu
rFbO7yXlWzugggXwHRFBTQ0vwdipUw7Er/TpIcn0uHX+jSDaKFiXIe3LVmai7hds01bfRHM39tTd
LTe3nMU0VwzE9gaFRAJCXYpvkc5YmQD+EnRxTa7LKWmPLRBv37+5DkY/HfemJ/d+b3w/7o1+8n+K
kIlt1OqaUmGACHM6H4oV7Fvb0WR6xHfb6t6ojASi6fXoDHmo9eCyDFGNrDsBe0mvQ7edWSTL/YT9
aaMbkcG1DiN5rJq1OElhq/xU5Pv8ehObolldw+34JYoWEiqPmqXftXvMGvV9+u1kWO4K06xeXb5n
mCN6/YmWYQOkCMs9YftfI2L9h3eQpIrj+TIKZ9PlcKlkPI8nMlKzeDiL55O5mkWTcRRH89FM/NCh
1yJtn9QcOPgCSSFq8brZ6T9SfpxyX2LaJ049+IHw6JloNJwOx/hk9ONwNp8vZ8tlOB5G45mMxzIc
T+IomiyPl9Pl8fw4VlP8MXqT36oMsd1Jj97BksK+2436ExraR7gRM47ve3qjqHWSb2hpOBz7/ugE
65c/f7RC6k/s6+DlmhRKp1mKV1yq/veH9w22bRTdN/DasPFNbUuLMMxsy8S0Zj4peYuAYZXEokJh
vAfB0kqa3TQwamxfFD1Ln2ZX1/sjS3sn30zsJL/JQBwMo3D3GY4nn4SCZuMmyg1CRYNqY23Owfgf
SjgfLznhYcsxiYfwvz0nrrjdYXjEwpcv/wtXfbzS
===END CRASH DUMP===

**Comment by 3rdIteration** [comment]
I have since resolved this and submitted back to the master.

Was simply a case of updating references to TileEntityDataPacket to reflect renaming of BlockEntityDataPacket

**Comment by SURVAml** [comment]
I'm trying to update ManyWorlds and SignWarp but I don't unterstand what I must change that it works. I can't find TileEntityDataPacket or BlockEntityDataPacket in those plugins. Do you know how?

**Comment by Intyre** [comment]
Fixed with 2e5490fb5bad38610b6d6d76f10758e5baeae8dd

**Comment by SURVAml** [comment]
Hallo PocketMine/PocketMine-MP, 
   
 Please no notifications to this email, thanks. 
   
 ______________________ 
   
 SURVA.ml - Dein MCPE Server Netzwerk. 
  Wir hoffen wir konnten dir helfen. 
   
 Du schreibst mit . 
   
 Mit freundlichen Grüßen, 
 SURVA.ml Support. 
   
 
 
 
    
 
  
         Am Mi, 25 Nov at  5:24 PM
          ,  PocketMine/PocketMine-MP <reply@reply.github.com>  schrieb:
           Closed #3740.

**Comment by SURVAml** [comment]
Hallo PocketMine/PocketMine-MP, 
   
 
 Please no notifications to this email, thanks. 
   
 ______________________ 
   
 SURVA.ml - Dein MCPE Server Netzwerk. 
  Wir hoffen wir konnten dir helfen. 
   
 Du schreibst mit . 
   
 Mit freundlichen Grüßen, 
 SURVA.ml Support. 
   
 
 
 
    
 
  
         Am Mi, 25 Nov at  5:24 PM
          ,  PocketMine/PocketMine-MP <reply@reply.github.com>  schrieb:
           Fixed with 2e5490f
