### ISSUE TITLE
furnace bug

### ISSUE THREAD

**Issue by Creeperface01** [PocketMine/PocketMine-MP#3749]
if i place furnace and go away and then go back and open furnace, so it crash the game

**Comment by blindahl** [comment]
Same bug as issue #3814

**Comment by Creeperface01** [comment]
Yes but my was first :D and this bug is due to furnace should be spawnable

**Comment by rick123159** [comment]
This BUG is existence on the new version now. 
(
VERSION = "1.6dev"
API_VERSION = "2.0.0"
)

**Comment by thebigsmileXD** [comment]
Hasnt this been fixed for ages?

**Comment by gillouz** [comment]
Hi everyone 

I am running this version and this bug is still open (crash client IOS and Android)

This server is running PocketMine-MP 1.6dev-23 「[REDACTED]」 implementing API version 2.0.0 for Minecraft: PE v0.14.0.0 alpha (protocol version 45)

**Comment by amaax** [comment]
Hello
I have same bug
PocketMine-MP version 1.6dev "[REDACTED]"

**Comment by PEMapModder** [comment]
Not confirmed existent or nonexistent yet.

**Comment by amaax** [comment]
How I got bug:
1. Put furnace in survival and make it work
2. Switch to creative
3. Reconnect server
4. Try to tap the furnace

**Comment by amaax** [comment]
3.5 Switch to survival

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
