### ISSUE TITLE
No stack limit on cactus

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [PocketMine/PocketMine-MP#3752]
There is no stack limit on cactus and if you stack it a few high and break the bottom it craches the server due to..

Maximum function nesting level of '100' reached, aborting!

**Comment by thebigsmileXD** [comment]
Lol.. due to BlockUpdate when broken

**Comment by XxDXM-hippiexX** [comment]
yuo

**Comment by thebigsmileXD** [comment]
Same for sugar cane?

**Comment by thebigsmileXD** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/da15fe2ef0c90e88083fd2cfd378e1b23d3f8b78
This fixes it on Sugarcane and Cacti

**Comment by thebigsmileXD** [comment]
DON'T USE MY FIX! It makes it worse .-."

**Comment by PEMapModder** [comment]
I'm thinking about Level::scheduleUpdate($pos, 0)

**Comment by thebigsmileXD** [comment]
Just wrote the code. :p because i saw your post on the redstone commit

**Comment by thebigsmileXD** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/3eaa032c72c7a35ad6be2ea399a06c3bc4115d03
Thanks @PEMapModder , it works just perfect.

**Comment by PocketKiller** [comment]
xdebug?

**Comment by thebigsmileXD** [comment]
You. This is PM. PocketMine won't disable xdebug because it shows backtrace for API + Debug for Plugins

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
