### ISSUE TITLE
Simple Auth crashing server

### ISSUE THREAD

**Issue by HittmanA** [PocketMine/PocketMine-MP#3759]
[CrashDump_Sun_Dec_6-19.20.14-ACT_2015-2.log.zip](https://github.com/PocketMine/PocketMine-MP/files/53335/CrashDump_Sun_Dec_6-19.20.14-ACT_2015-2.log.zip)

**Comment by UltimateMcraft** [comment]
Ahem, Plugin Issue should not be reported here, use the plugins repo
