### ISSUE TITLE
ifconfig not found

### ISSUE THREAD

**Issue by StylusEater** [PocketMine/PocketMine-MP#3772]
Seems to be a path related issue when installed as a non-root user:

09:15:12 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
09:15:12 [INFO] Loading pocketmine.yml...
09:15:12 [INFO] Loading server properties...
09:15:12 [INFO] Starting remote control listener
09:15:12 [INFO] RCON running on 0.0.0.0:19132
09:15:12 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
sh: 1: ifconfig: not found

Search the PocketMine-MP.phar file and there is an ifconfig ... not /sbin/ifconfig present.

**Comment by PEMapModder** [comment]
Fixed in #3723

**Comment by StylusEater** [comment]
@PEMapModder why would you just silence it? I believe /sbin is a universal location for ifconfig on various distributions, no?

**Comment by Intyre** [comment]
On arch linux ifconfig is located in /usr/bin, so it's not always /sbin. 
Make sure that the location of ifconfig is in your $PATH

**Comment by StylusEater** [comment]
@Intyre sounds good. I was just thinking of whether there might be a standard location but I guess that's a dream with distributions. But since we're on the topic of ifconfig ... should we look at switching to 'ip addr' in lieu of ifconfig?

http://www.linuxfoundation.org/collaborate/workgroups/networking/net-tools

**Comment by PEMapModder** [comment]
It appears that ifconfig is not found if you are not running with root.

**Comment by StylusEater** [comment]
Correct. That was with my original bug report. Thank you for investigating.

>Seems to be a path related issue when installed as a non-root user:

**Comment by Intyre** [comment]
We can switch to ``ip addr`` but you still get the same error as long as the $PATH variable doesn't contain the location of ``ifconfig`` or ``ip``.

It should be safe to give non-root users access to ifconfig.
``export PATH=$PATH:/sbin`` or ``ln -s /sbin/ifconfig /usr/bin/ifconfig``
