### ISSUE TITLE
PurePerms Error 

### ISSUE THREAD

**Issue by marcossanchezbajo** [PocketMine/PocketMine-MP#3773]
[Server] [18:10:02] [Server thread/CRITICAL]: Unhandled exception executing command 'setgperm Soldier help' in setgperm: Argument 1 passed to _64FF00\PurePerms\data\UserDataManager::setData() must implement interface pocketmine\IPlayer, array given, called in phar:///storage/emulated/0/PocketMine/plugins/plugin-862.phar/src/_64FF00/PurePerms/data/UserDataManager.php on line 108 and defined
[Server] [18:10:02] [Server thread/NOTICE]: RuntimeException: "Argument 1 passed to _64FF00\PurePerms\data\UserDataManager::setData() must implement interface pocketmine\IPlayer, array given, called in phar:///storage/emulated/0/PocketMine/plugins/plugin-862.phar/src/_64FF00/PurePerms/data/UserDataManager.php on line 108 and defined" (E_RECOVERABLE_ERROR) in "/plugin-862.phar/src/_64FF00/PurePerms/data/UserDataManager" at line 130

**Comment by marcossanchezbajo** [comment]
This happens with all permissions

**Comment by Intyre** [comment]
Please read: https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue

- If your issue is related to a plugin, you must contact their original author instead of reporting it here.
