### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SensenmannGaming** [PocketMine/PocketMine-MP#3774]
The Server crashes very often because "[Server] [21:54:38] [CRITICAL]: **** FAILED TO BIND TO 0.0.0.0:19132!
[Server] [21:54:38] [CRITICAL]: Perhaps a server is already running on that port?
[Server] [21:54:38] [EMERGENCY]: [RakLib Thread #-1255293656] RakLib crashed!
[Server] [21:54:38] [INFO]: Preparing level "New Lobby"
[Server] [21:54:38] [INFO]: Enabling ManyWorlds v2.0.3
[Server] [21:54:38] [INFO]: Enabling EasyMessages v1.1.0
[Server] [21:54:38] [INFO]: Enabling EasyMessages v1.1.0...
[Server] [21:54:39] [INFO]: Starting GS4 status listener
[Server] [21:54:39] [INFO]: Setting query port to 19132
[Server] [21:54:39] [INFO]: Query running on 0.0.0.0:19132
[Server] [21:54:39] [INFO]: Default game type: Survival Mode
[Server] [21:54:39] [INFO]: Done (3.066s)! For help, type "help" or "?"
[Server] [21:54:39] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use
[PocketMine] Stopping server...
[Server] [21:54:47] [INFO]: [CONSOLE: Stopping the server]
[Server] [21:54:48] [INFO]: Disabling ManyWorlds v2.0.3
[Server] [21:54:48] [INFO]: Disabling EasyMessages v1.1.0
[Server] [21:54:48] [INFO]: Disabling EasyMessages v1.1.0...
[Server] [21:54:48] [INFO]: Unloading level "New Lobby"
[Server] [21:54:48] [INFO]: Stopping other threads
[PocketMine] Server was stopped."
I don't know why this happened because i'm running my Server in my android nexus 5. I didn't opened any mcpe worlds

**Comment by Subtleoliver** [comment]
There is already a server running on the network/device with that port.
