### ISSUE TITLE
Invalid or Corrupt skin join error

### ISSUE THREAD

**Issue by HittmanA** [PocketMine/PocketMine-MP#3777]
Whenever I or any of my server users try to join my server it says "Invalid or corrupt skin" I have mcpe 0.13.1 and pocketmine v	[0.10.4] PocketMine 1.4 dev 878. I NEED THIS ISSUE FIXED ASAP!

**Comment by tiNsLeY799** [comment]
Um, PocketMine-MP is currently in 1.6.. And in O.13. Try using the bleeding
builds

**Comment by HittmanA** [comment]
ok I will try this
