### ISSUE TITLE
can I run pocketmine on IOS9

### ISSUE THREAD

**Issue by CRQM** [PocketMine/PocketMine-MP#3779]
I want to run pocketmine on IOS9, but the website provides cydia version is very old.

how can I cross compile the PHP's extends whate pocketmine needed   on the IOS9 ?

or Do you know the feasibility?

thank you ,very much!!!

**Comment by Intyre** [comment]
Don't run PocketMine on a mobile device.
This is a issue tracker, not a forum.

Please read the [contributing guide](https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md) before creating issues.
