### ISSUE TITLE
Trapdoor rotation

### ISSUE THREAD

**Issue by OfficialJoey** [PocketMine/PocketMine-MP#3786]
Trapdoor's when placed are completely fine, but when tapped to make it close it just glitches out, and the trapdoor will be facing the other way, or it will be on its side.

**Comment by HittmanA** [comment]
I have this problem to!

**Comment by CyberPowerCrazii** [comment]
Same

**Comment by jingz2007** [comment]
This is a problem when you tap and occupy the block under it. It has to do with the block rules or something I believe. Just stand above it and tap it again. It is an issue, but for now there are bigger problems, like item id lag.

**Comment by PEMapModder** [comment]
Fixed in e2f7d65
