### ISSUE TITLE
Can't compile in source. Need threaded factory file.It's missing.

### ISSUE THREAD

**Issue by Lucario2** [PocketMine/PocketMine-MP#3788]

**Comment by PEMapModder** [comment]
Use https://github.com/PocketMine/PocketMine-SPL/tree/d59c0f673455f02b2620853f3fa6290d63ffd960 instead of the HEAD of PocketMine-SPL in that submodule.

**Comment by Intyre** [comment]
http://pocketmine-mp.readthedocs.org/en/latest/installation.html#using-github
