### ISSUE TITLE
Unlimited axe, pickaxe, shovel etc etc...

### ISSUE THREAD

**Issue by Jelly9912** [PocketMine/PocketMine-MP#3789]
And somoetimes bugs with crafting

**Comment by HittmanA** [comment]
I have this problem to! All the tools on my server take no damage whatsoever! Even wooden ones!!

**Comment by Jelly9912** [comment]
Update: if i hit players or mobs then tool in hand get some damage. Tested only on diamond axe, can someone test it on other tools? 
Thanks

**Comment by HittmanA** [comment]
I will test it later today.

**Comment by EpicnessTwo** [comment]
Can confirm that all tools only take damage when using them to harm mobs. Block damage is not working at all

**Comment by 19kestier** [comment]
Duplicate of #3555

**Comment by PEMapModder** [comment]
Cannot be reproduced
