### ISSUE TITLE
Crash 0.13.1 server

### ISSUE THREAD

**Issue by 112kutiko** [PocketMine/PocketMine-MP#3799]
[CrashDump_Wed_Dec_23-22.21.57-UTC_2015.zip](https://github.com/PocketMine/PocketMine-MP/files/71296/CrashDump_Wed_Dec_23-22.21.57-UTC_2015.zip)
Pls fix this

**Comment by Intyre** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue
Pls read this.
