### ISSUE TITLE
Looks like a memory crash on build 1266 - wont stay up for more than 24 hrs

### ISSUE THREAD

**Issue by mgnyc11** [PocketMine/PocketMine-MP#3804]
PocketMine-MP version: 1.6dev #52 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ip-172-31-16-45 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

http://pastebin.com/sFP9QNBy

I have changed the memory from 256-512 to see if that will help

**Comment by jojoe77777** [comment]
That is not build 1266.


> PocketMine-MP version: 1.6dev #52 [Protocol 38; API 1.13.1]

**Comment by mgnyc11** [comment]
How is not 1266.  I downloaded it from here and it states its 1266

http://jenkins.pocketmine.net/job/PocketMine-MP/Development/artifact/PocketMine-MP_1.6dev-1266_fb87165c_API-1.13.1.phar
