### ISSUE TITLE
Player can repeat dead

### ISSUE THREAD

**Issue by HmHmmHm** [PocketMine/PocketMine-MP#3809]
if player not click "respawn" button,
and someone hit that player

so player can repeat death in mc:pe 0.13.1
(and death message is repeat same)
i used newst version about pocketmine bleeding

**Comment by PEMapModder** [comment]
This is not relevant, but the newest version is the development version.

**Comment by HmHmmHm** [comment]
yep not important problem (∩´﹏`∩);

**Comment by PEMapModder** [comment]
Just to ensure that you are reporting from the latest version.

**Comment by PEMapModder** [comment]
Should have been resolved in #3978
