### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by dterweij** [PocketMine/PocketMine-MP#3812]
Can sombody clean up the plugins on the website?
Outdated can be deleted in my eyes.

And a lot plugins not working anymore. Seems a lot is not maintained anymore. It looks like a graveyard :) Pitty, there are useable plugins but unusable because they dont work.

Its kind of crazy for newly minecraft users to see such a mess :) So please clean it up and all the plugin maintainers, please update your plugins to work with latest versions.

And yes this is a real issue.. Many plugins I tried crashes the server, shows a lot errors, just dont do anything anymore etc etc,

**Comment by PEMapModder** [comment]
Please make this comment on the forums. This is not related to the code, which is what this issue tracker is for.
