### ISSUE TITLE
Cannot Download Channel/Version of 1.3.1 on MCPE.

### ISSUE THREAD

**Issue by HudsonTheNoob** [PocketMine/PocketMine-MP#3813]
It cannot download my version! Last time it works! Now doesn't work! Hate this! I would move on to a new better app called "leet mine craft pe server". Please then I would stay on this app.

**Comment by VortexScribe** [comment]
Ok, First Off, LEET Servers Run The Same Software You Are Trying To Find, They Are NOT Different, Secondly Download It From Here: http://jenkins.pocketmine.net/job/PocketMine-MP-Bleeding/

**Comment by PEMapModder** [comment]
What? Version 1.3.1?

**Comment by VortexScribe** [comment]
I Think Hudson Means 1.13.1
