### ISSUE TITLE
FURNACE CRASHES GAME (CLIENT)

### ISSUE THREAD

**Issue by Caier** [PocketMine/PocketMine-MP#3814]
When furnace is placed I can use it but when i disconnect from server and connect and try to open furnace it crashes whole game.

**Comment by elw124** [comment]
Agreed.  I found this same issue.

**Comment by Jorti1** [comment]
I also found that problem , maybe it is the PocketMine-MP.phar ??

I havent gotten bleeding phar 55 cause the website is down

**Comment by PEMapModder** [comment]
@Jorti1 PocketMine newest updates are development builds, not bleeding builds.

**Comment by robske110** [comment]
And where can we get them?

**Comment by PEMapModder** [comment]
http://www.pocketmine.net/api/?channel=development

> `"alternate_download_url": "http://cdn.pocketmine.net/api/update-development.phar"`

**Comment by robske110** [comment]
Because jenins is still down :(

**Comment by PEMapModder** [comment]
@robske110 that has nothing to do with Jenkins...

**Comment by robske110** [comment]
http://jenkins.pocketmine.net/job/PocketMine-MP/1266/",?

**Comment by PEMapModder** [comment]
Duplicate of #3749
