### ISSUE TITLE
Trying To Make A Server

### ISSUE THREAD

**Issue by UltimateZeal** [PocketMine/PocketMine-MP#3817]
So recently i just created a pocket-mine server.. I followed every instructions on a video but there was one thing i want to do. The thing I wanted to do is just make a server and get my friends to join from anywhere instead of my WiFi! I followed every direction of port forwarding and other stuff.. still no use. I just need help into fixing this.. I tried to follow tons of directions from videos and the pocket-mine and still no use! I want to make my server public so my friends can join that is all i want! I tried port forwarding too.

Please, reply back and thank you

Sincerely,
Zeal

**Comment by Caier** [comment]
Did you gave them your public IP?

**Comment by UltimateZeal** [comment]
what do you mean? I looked up my ip on the google thing, just like how they said in forum.

**Comment by Caier** [comment]
I had the same problem but i realised that i added port to "port filtering" instead of "port forwarding" :P

**Comment by UltimateZeal** [comment]
So how can i fix this problem?

**Comment by PEMapModder** [comment]
This is not a help forum. Please use the forums or the IRC channel for support.
