### ISSUE TITLE
Lake generation

### ISSUE THREAD

**Issue by James76931** [PocketMine/PocketMine-MP#3818]
Lakes will generate with grass below them instead of dirt now and then. Not all the time, just now and then.

**Comment by James76931** [comment]
Never mind, it is all the time and it also includes the sea - not just lakes.

**Comment by PEMapModder** [comment]
Duplicate of #3173

**Comment by James76931** [comment]
Whoops, didn't notice that :P

**Comment by PEMapModder** [comment]
Close the issue.
