### ISSUE TITLE
Can't get thrower of item

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3821]
\pocketmine\entity\Item->getThrower() always returns null because when throwing the items the thrower isn't set
```php
			case ProtocolInfo::DROP_ITEM_PACKET:
				if($this->spawned === false or $this->blocked === true or !$this->isAlive()){
					break;
				}
				$item = $this->inventory->getItemInHand();
				$ev = new PlayerDropItemEvent($this, $item);
				$this->server->getPluginManager()->callEvent($ev);
				if($ev->isCancelled()){
					$this->inventory->sendContents($this);
					break;
				}

				$this->inventory->setItemInHand(Item::get(Item::AIR, 0, 1));
				$motion = $this->getDirectionVector()->multiply(0.4);

				$this->level->dropItem($this->add(0, 1.3, 0), $item, $motion, 40);

				$this->setDataFlag(self::DATA_FLAGS, self::DATA_FLAG_ACTION, false);
				break;
```
Also, it would be nice to get the thrown ItemEntity that gets spawned *after* PlayerDropItemEvent
Because now theres no way to get who threw the item..

**Comment by PEMapModder** [comment]
But the item is not spawned in PlayerDropItemEvent. How could you get the entity?

**Comment by thebigsmileXD** [comment]
But in the ItemSpawnEvent the items should atleast get the thrower set.

**Comment by PEMapModder** [comment]
Is there an ItemSpawnEvent?
Also please read my edited comment.

**Comment by PEMapModder** [comment]
I'd just like to remind you that Item::getThrower() is supposed to return a string.

**Comment by thebigsmileXD** [comment]
Edited mine also
And yea, but there is no setThrower when the Item is spawned

**Comment by thebigsmileXD** [comment]
May be meaningless now. (But in bukkit you can get the thrower!)
