### ISSUE TITLE
Can't download Linux ARM from Jenkins

### ISSUE THREAD

**Issue by wpmjones** [PocketMine/PocketMine-MP#3823]
I was able to download the stable build and it ran perfectly, but all of our clients are running MC v0.13.1 alpha so I wanted to install the dev build.  When I run wget, it says "Couldn't download PocketMine-MP automatically from http://jenkins.pocketmine.net/job/PocketMine-MP/1266/artifact/PocketMine-MP_1.6dev-1266_fb87165c_API-1.13.1.phar

I see that the last few ARM builds have failed, but is there a viable build for the Raspberry Pi that works v0.13.1 alpha?  Thanks!

**Comment by PocketKiller** [comment]
jenkins.pocketmine.net is down.

**Comment by gaoyichuan** [comment]
Yes, jenkins server is down.

**Comment by PEMapModder** [comment]
Replace `download_url` in the output of `wget -O - get.pocketmine.net` with `alternate_download_url`; it should work.

**Comment by boomtownxcs** [comment]
@PEMapModder Can you elaborate on doing this? I downloaded the index.html file and modified the line but it returned the following: 

bash-4.1$  sh index.html | bash -s - -v development
bash: line 1: syntax error near unexpected token `('
bash: line 1: `[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0'

**Comment by gld1982ltd** [comment]
Now the whole pocketmine site is down.

**Comment by PocketKiller** [comment]
@gld1982ltd Nope, you're going on it with HTTPS, there is a problem with it's HTTPS host, but HTTP is alright.

**Comment by gld1982ltd** [comment]
@PocketKiller I see. Thanks.
