### ISSUE TITLE
Jenkins website is malfunctioning

### ISSUE THREAD

**Issue by Zafpyr** [PocketMine/PocketMine-MP#3825]
When you goto http://jenkins.pocketmine.net/job/PocketMine-MP/ and click PocketMine-MP_1.6dev-1267_78525e1f_API-1.13.1.phar
It won't download http://jenkins.pocketmine.net/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.6dev-1267_78525e1f_API-1.13.1.phar

Just shows a cloudflare error Error 521 Ray ID: 25dbe6b7a75f0b26 • 2016-01-01 05:42:31 UTC
Web server is down.

**Comment by PEMapModder** [comment]
The issue is duplicated.
