### ISSUE TITLE
setHealth() kills player when player's health is not full

### ISSUE THREAD

**Issue by TigerHix** [PocketMine/PocketMine-MP#3830]
When player has a health under 20.0, using `setHealth()` on that player would cause PocketMine to send a `SetHealthPacket` with following content:

    pocketmine\network\protocol\SetHealthPacket Object
    (
        [health] => 20
        [isEncoded] => 
        [channel] => 0
        [offset] => 0
        [buffer] => 
    )

Which results the client to render the death screen and the buttons would show up. The respawn button remains gray and cannot be pressed. The main menu button does nothing. Other players in the world will see the target player as normal (standing on ground statically).

**Comment by TigerHix** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/3412

**Comment by TigerHix** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/3412

Shouldn't this issue be high-prioritized? It seems like this one is months old.

**Comment by thebigsmileXD** [comment]
And fixed by so many third party builds..

**Comment by TigerHix** [comment]
I thought PocketMine could implement a simple fix to this though. Third party builds like the popular one implements a whole attribute system.

**Comment by thebigsmileXD** [comment]
Actually not, ImagicalMine fixed it with a simple check if the health is lower than 0, then killing the player

Y U NO do it, @PocketMine ?

**Comment by PEMapModder** [comment]
@thebigsmileXD then why you no PR it?

**Comment by thebigsmileXD** [comment]
We did.

**Comment by thebigsmileXD** [comment]
Or didn't? @keithkfng

**Comment by keithkfng** [comment]
We never make pull requests from IM to PM because the code is messed up ;)

**Comment by thebigsmileXD** [comment]
xD :p okay.

**Comment by iksaku** [comment]
BTW @TigerHix: Use `Integers` instead of `Floats` next time. #GeneralKnowledge ;D

**Comment by PEMapModder** [comment]
Should have been resolved in #3978
