### ISSUE TITLE
Using these insructions to install Pocketmine Dev 

### ISSUE THREAD

**Issue by kth-xx** [PocketMine/PocketMine-MP#3831]
For anyone who's unable to install the Dev version using "wget -q -O - http://get.pocketmine.net/ | bash -s - -v development'

Use this:

wget -q -O - http://get.pocketmine.net/ | bash
wget https://transfer.sh/17asl/pocketmine-mp-1.6dev-1266-fb87165c-api-1.13.1.phar -O PocketMine-MP.phar

Taken from this post on Reddit 

https://www.reddit.com/r/MCPE/comments/3yxts6/how_to_install_and_run_pocketmine_server_on/.compact

**Comment by Intyre** [comment]
or http://forums.pocketmine.net/threads/pocketmine-mp-1-6dev-1266-is-now-available.13832/
or http://pocketmine-mp.readthedocs.org/en/latest/installation.html
or http://pocketmine-mp.readthedocs.org/en/latest/installation.html#installing-manually

This is an issue tracker, not a forum!
