### ISSUE TITLE
Error Cannot allocate memory

### ISSUE THREAD

**Issue by hendrikator** [PocketMine/PocketMine-MP#3833]
Mon Jan  4 09:37:24 2016 (140170940966656): Fatal Error Unable to allocate shared memory segment of 134217728 bytes: mmap: Cannot allocate memory (12)

Wenn i will start the server with ./start then cam this error

**Comment by robske110** [comment]
Does it come always. And how much ram have defined in pocketmine.yml and how much RAM do you have at all...

**Comment by hendrikator** [comment]
i have no pocketmine.yml it wars the first start the v-server has 4 GB Ram
