### ISSUE TITLE
Not seeing server

### ISSUE THREAD

**Issue by wschlotter** [PocketMine/PocketMine-MP#3853]
I have the server up and running, it says that it has started on 0.0.0.0:19132. When i go to connect on my tablet it just keeps on loading and nothing happens. When i try to port forward for outside my network the port is not sending anything. Not sure what is going on.

**Comment by robske110** [comment]
Try localhost:19132

**Comment by tiNsLeY799** [comment]
You need an internal IP. As host name, it should say Minecraft PE: Server
with UDP or both protocols. You should use internal IPs such as 192.168.1.x
etc. You'll normally find it on MCPE and if it doesn't show, the Server
name is not present on server.yml

**Comment by wschlotter** [comment]
@robske110 localhost:19132 will only work if I'm hosting the server on the tablet. I am running the PocketMine server on OSX trying to access it from my tablet.

@tiNsLeY799 no sure i follow. i have a local IP, 192.168.1.105. I have changed the server.properties to different settings (blank, 0.0.0.0, 192.168.1.105, localhost) and still no go.

**Comment by robske110** [comment]
So I'm running an server too on MacOSX it is public and it works too with localhost:

**Comment by wschlotter** [comment]
@robske110 k, maybe i'm missing something. Are you putting localhost in on the tablet or in the server preferences?

**Comment by robske110** [comment]
In server preferences there are NO settings for that:
´´´
motd=robskeBuebaPocketServer2.0.1
server-port=3114
white-list=off
announce-player-achievements=on
spawn-protection=50
redstone-calculation=on
max-players=50
allow-flight=off
spawn-animals=on
spawn-mobs=off
gamemode=1
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=null
auto-save=on
```
AND PLEASE MOVE THIS TO THE POCKETMINE FORUMS! http://forums.pocketmine.net/
