### ISSUE TITLE
Website Issue

### ISSUE THREAD

**Issue by jamiechapman** [PocketMine/PocketMine-MP#3859]
Just a heads up, the SSL certificate on the Pocketmine website appears to be invalid.  Internal links to the forums etc all fail and inbound links from Google fail too without manually removing the `s` from `https://`.

It fails for all pages, including Plugin URLs.

Hope this helps!

![screen shot 2016-01-08 at 10 38 00](https://cloud.githubusercontent.com/assets/688026/12196093/eb71716e-b5f3-11e5-9058-60d5017f5421.png)

**Comment by PEMapModder** [comment]
Duplicate.
