### ISSUE TITLE
Unknown crash! please help! player error?

### ISSUE THREAD

**Issue by barnseyminesuk** [PocketMine/PocketMine-MP#3860]
PocketMine-MP Crash Dump Sat Jan 9 14:08:39 UTC 2016

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 449
Type: E_ERROR

Code:

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #52 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux 521d23c45eb9 3.19.8-031908-generic #201505110938 SMP Mon May 11 13:39:59 UTC 2015 x86_64
PHP Version: 5.6.9
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
ArrowSound 1 by CaptainKenji17 for API(s) 1.12.0
PvPWorlds 1 by  for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
NoFallDamage 0.0.1 by thebigsmileXD for API(s) 1.0.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
AutoInv 1.0.1 by HotshotHD for API(s) 1.12.0, 1.13.0
DropParty 1.0.0 by HotshotHD for API(s) 1.12.0, 1.13.0
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0
Jail 2.0.3 by hoyinm14mc for API(s) 1.13.0, 1.13.1

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrFWVFv2zgS/iuCug8t4NiSZTu2HxbIxSm2t/HFiNPtYleHgJIoiw0lakXKjlv0v9+QkiVKTje2
k9sGaC2OKPL7ZoYzQ/KrKUiMzak9GPadwXhoTzomzjKWmdOvptim8Mq8ur+6vb25NTtmjDlHKym7
RJQaghnIiHHs4cwI88QXhCVGhPgCZzHhHFpv3xkgSnJK4euQUPlpj2d+L2X+AxYxSXBvQdEWZ/f3
o4FHBHSjIDSng8HkW8dMab4iiTkNEeW4Y/osgFd//rdjigz58tF8Yxlv302NejzXXeJsjbOzn/0M
8WiWx+lbjzGKUfLOhC9XOMEZopIf9JIgAZPdHQV4DZN7OaGBOR32Ye6MCeYz6OmMOyZKiepnO10b
+q0A6tS0DvyDDzL0QIknv+med6UgT5BUvHlNkvzRGPbtoO/4gyH2JgZMMemOzyzHnljjMwWY+Mab
vmUPraFtWxNnbCznC2MOup2jrWHbhu1Mncl0ODE+3l0asqPxOB6BSmGiNEphmmF31J1A6wtOgJ/Z
h6ZVvLxnfAcDBKpBVaPSP5fKugCv2CxZLj//apbgNWGnVqcN6spFxDIuLXSJUoFI8itOPhP7XJpA
6fJPqcw+gAABTpBHMQwsshzMHOAUUPLC0pyFYqYLYiQ9QpvadedSBJ7DkOS2uFnefbq5vZ6BaIM9
TgRAlT4IhBbrxSeW0YBrJGrZ9zjomK3TIS9RnGP6ObJdt5rTdeODwZMFuCT2RbE6S/SaUINvgg8h
s2GH69nvDeVPTicCQ7luPfFBBjAjIVI+7fVg6US51/VZ3INxzuaXi6ueRgJ4XuZcsPiC4kzodmqI
O83V26R6tWZ0Cdhfzdn0qV23BaRkvby7uL37uNjjDJQ3m00XAyY5fFc8SI5FkLoAzBpDTajz63dt
+xCC9gtcs5p5Fz9LFCeRu0PpHZsxjdlO0qTV77Z4vUf0wXyl1SYg7rCAuW499yEBIs+wzF+NAFHJ
ml4HBJrwR4P37y3r1bzuvhgPosUOgPb4vG1ai019WcTzXj0KUJ7h9R0kSJ1xJWoSti2VNDTGC5V3
55B3jTuM4gZ1mSlPZL6b33U1JEfSrZD1qjGA7BXnOBEE6onFlUa4IW6R7jqtQIpXEvBNKEPXPu2X
WFyH4brXQBhnp8RVhbAA2GtQAw2ovHMVEHGRCU0DDXFTA2D1ew8LdA810v0bazBu+cDVHKVzFkis
r7R2UxyjNFZDuu5GIsOADGXCdVs4j1WNBra3jKGKPfvj8my3LESGcS9GXMDLxjygtjlKtnulgyZs
Rjar7TSIkpxum47yAgUVw8niIdluykLi8CroN0i2t3iDMr2W04QaFwjRf1tFFBFBrpLit1/+Oi+s
Lmo0xxD7D4MMQmcoVruUilpDrBsK0LdTkIiwR1Y8hs3K77NXy0X6oK6r4zmG3pKskgXLRLF92RUN
tbAduFrpaTKhmCV+hJLVawXqasDJBAqHCsnJFaEGsacRA+4XdIO2fJmiTaJvQDRpu7ZosV9EhJLU
WMIP7G9WrxazUzUuL4d1XaQgcQlpP4Q/kbxK2/4rgx6+ij0aP13asu7/u+bVpm6b87hq8MpnCYu3
F4sPesKthe3IOWkSYwn24N9BUacoKIvo0yk9W/4OyvbgdE8vYbguLpADFtdtsDhgAZf9r1FjF61L
T1DGs0bWlX0EQ4rk3roJ7nCOsKNLYYO03edZvWlzHb0i1xLvaczTEmHFXoN8hAaWEUufoK/Ebe79
V+B+DEMOIGp6JaTDuS0xpfvUlLTN7PzHeTAHPBXJEtwRHJ8035PW+5EcdUMebcc79LhPUQqfKWf/
yaB8omIEeqz0UjA6XC0feZ49EbkKcXtzZP844+cSUMVyB+8Anhe5YB+StV5JlZJn2P3CBHic+GW2
z69THI+fvqcBBCRZu24N5QAmMwjNC9RMNLVsbyP7j7EJAEOKVBLR4RzAyF5zWyOjmu1Ny9D8u/Pp
3So8EfqcJCQkj4S5LjjbmiuPu0nwbxz+O/wY7TJConWKpkRNmzjt0PLUIdpzZLQjuj1e5nukbqY4
JHHzO4drElf99OKjNTWIrOmREBT/ShrH2Jqw7Z2D/dNQkj3wl+1Cm6V2eSwGJt1qyvAUpgciT7cb
+A4w9b8R0UsB1Xwme0RsS5LYHsR+08xOve6OrNNhFxynFJeH1g3Gc8Q5WeNS9l0V1Jhc9zNwcN2S
ybNb2HLXo/mDv/Vw5ucePoseenIw85u8TKvuKLvbGFRmwkhcnbV3y4KTYF6IIXCANmHnVZLFjwIn
Up/KkS5ZhrUrvQAJvYkzvKpuTFNfdi0b/C8KqJ3iEvKsuPD8UtxKFhHP82MkLyR2162IgnpRVguK
G+FdK89o1QgJVTtXGNouCoBQpNXbVVA/xrU4QjwqXB/6f+bVsbqMdxSvMQ2KG1O7Oyzhxh4Xmdy9
74aI/WybipqiQBJxoOljubhWg8gKO/UTUWOG4ukvqq5DyydjKBOeLecyzuQ1at8aWg48/vQhmBqO
PxqPvZHn+Y4VOCMUOsh3BmEQDLxzb+idj89DPIQ/4yfpZJHUW1Xap4yTx9oqIsowko6rOqjbnVsc
UqwCFUjVfDgMx17gj4ae5WEUjsMBCvAotEbheDDGo2DgBGEw7o/UfDyKWa1YrlyNN5mSQpfQWbAH
nJAvO3uB5BNGDxkOC0WpjdgWKR+ViUR2+ELSotWH3PPt2/8AlspLTw==
===END CRASH DUMP===

**Comment by PEMapModder** [comment]
This is caused by a plugin, although it is unsure which plugin caused it.
