### ISSUE TITLE
date() crash - URGENT

### ISSUE THREAD

**Issue by AndreyNazarchuk** [PocketMine/PocketMine-MP#3862]
![2016-01-09](https://cloud.githubusercontent.com/assets/7192775/12218815/e6d6062e-b6de-11e5-8fac-65d5a9700167.png)

This happens all the time, and it crashes the server and the vps becomes unresponsive.

**Comment by PEMapModder** [comment]
Set the date.timezone property in php.ini, as the message says.
Also, please don't tag your issues with things like `URGENT`, as mentioned in the contribution guidelines.
This issue may spam the console, but it doesn't crash the server.

**Comment by AndreyNazarchuk** [comment]
It froze my vps.

**Comment by PEMapModder** [comment]
If it is, it is caused by something else. This warning related to timezone settings does not freeze or crash you.

**Comment by AndreyNazarchuk** [comment]
Ok.
