### ISSUE TITLE
$this->getServer()->getLevels() only returns the loaded levels

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#3863]
This is an annoying bug..
I was about to use my classic world adding method like i did on instantrespawn, oitc, spleef..
Now on hotpotato..
```$this->getServer()->getLevels()``` only returns the loaded levels and i wondered 1 hour what the problem might be..
Shouldn't it return all levels?

**Comment by PEMapModder** [comment]
If the level isn't loaded, the server has no knowledge that that level exists.
`getLevels()` returns `Level[]` -> there must be a `Level` object for that.
If the level isn't loaded, how come there is a `Level` object for it? That is the definition of "loaded". The server has nothing in memory about that at all if it is not loaded.

**Comment by thebigsmileXD** [comment]
In 0.11 it returned all worlds existing in the /worlds folder. I know it because my OITC-plugin was able to add every world. Now it isn't anymore

**Comment by PEMapModder** [comment]
Autoloading worlds in the folder isn't an official functionality of PocketMine

**Comment by iksaku** [comment]
You can pretty easily get all "World folders", just do a `scandir()` within `$this->getServer()->getDataPath() . DIRECTORY_SEPARATOR . "worlds"`

**Comment by thebigsmileXD** [comment]
Thats what it should by default

**Comment by iksaku** [comment]
@thebigsmileXD Not really, while you ask for a "level" it should be ready-for-use, if you need to load them beforehand then add them to the list of 'worlds-to-be-loaded', instead use a plugin to load them at `startup`

**Comment by PEMapModder** [comment]
Loading  every world in the folder is **not** a PocketMine functionality and had never been one, as I said. 

Also, there has never been limitation that a level must be in the worlds folder. Crazy idea this is, one may load a level from a mongo database if a plugin adds that.

**Comment by thebigsmileXD** [comment]
Quote by https://github.com/MCDad:

> @legoboy0215 - I'm not sure your comment is true.

> SimplePortals v0.0.3 onEnable used to construct a map of all the portals on a server, regardless of whether they were loaded.  It called getLevelByName which in turn calls getLevels.  Everything worked fine until approximately the 3xx builds when SimplePortals started crashing the server.

> Someone called JamJam raised an issue at https://github.com/Falkirks/SimplePortals/issues/5.  I've done some digging and added more detail.  It looks like SimplePortals fails because it can't build the portal store, because it can't get the level information.

> SimplePortals has been static since November but obviously IM is in flux.

> I think bigsmile is right, there's something up with getLevels.  My crash dump and server log posted again for reference.


> [CrashDump_Tue_Jan_12-01.01.07-UTC_2016.log.pdf](https://github.com/ImagicalCorp/ImagicalMine/files/87281/CrashDump_Tue_Jan_12-01.01.07-UTC_2016.log.pdf)
[server.log.pdf](https://github.com/ImagicalCorp/ImagicalMine/files/87283/server.log.pdf)

**Comment by thebigsmileXD** [comment]
https://github.com/MCDad

**Comment by thebigsmileXD** [comment]
I am now 100% sure this is an issue that appeared after 0.11.
Its one of the reasons MyPlot doesn't work any longer.

**Comment by PEMapModder** [comment]
@thebigsmileXD can you elaborate more on the issue?
For discussion, let's go to a chat channel like IRC or Gitter.

**Comment by legoboy0215** [comment]
Also, getTiles on a world returns null if a player did not join the world.

**Comment by PEMapModder** [comment]
@legoboy0215 are you sure it returns null rather than an empty array?
Just like it is unreasonable to load all worlds in the worlds/ folder when nobody asked to load it, it is unreasonable to load all chunks in a world when nobody is using it.

@thebigsmileXD I still don't understand how this happens to be a PocketMine issue rather than a plugin issue, when PocketMine is not in charge of loading all worlds in the folder, as a matter of fact. 
If your call to getLevels() doesn't work, might it just be that your plugin is loaded _before_ the plugin that loads the worlds?

**Comment by thebigsmileXD** [comment]
The plugin hasn't changed in ANY way.

**Comment by PEMapModder** [comment]
But the loading order might be changed...
And please go to IRC for discussion.

**Comment by legoboy0215** [comment]
It is null... Sorry, IRC does work for me ATM.
