### ISSUE TITLE
Unable to import map

### ISSUE THREAD

**Issue by lightvortex** [PocketMine/PocketMine-MP#3866]
Hi I'm unable to import my existing Minecraft pocket editon map in pocketmine mp Android 
But I  able to use a Minecraft pc map pls guid me on how to import mcpe map

**Comment by PEMapModder** [comment]
MCPE maps are not supported on Android. They are only supported on Linux platforms (that do not include Android)

**Comment by lightvortex** [comment]
OK is there any way to convert mcpe maps to pc map

**Comment by PEMapModder** [comment]
This is not a support channel. Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md).
