### ISSUE TITLE
missing IPv6-support

### ISSUE THREAD

**Issue by thomasschaeferm** [PocketMine/PocketMine-MP#3869]
Millions of users  don't have public IPv4-addresses. (e.g. Vodafone Germany)
Therefore support of IPv6 is essential.

**Comment by Intyre** [comment]
Does MCPE even support IPv6?

**Comment by thomasschaeferm** [comment]
I don't know what MCPE is, but I know a lot of user, who have trouble with bad programmed game networks.
The FAQ regarding IPv4-TCP-Forwarding is not helpful. They cannot use IPv4 listen ports because they are behind CGNAT.

Here is one (german) example:
https://www.gutefrage.net/frage/kann-unity-media-router-tc7200-ports-freigeben

**Comment by Intyre** [comment]
MCPE is MineCraft Pocket Edition.
Just checked and it looks like MCPE doesn't support IPv6. Until then it's not needed or useful.

Maybe time for a better ISP :+1:

**Comment by thomasschaeferm** [comment]
"Maybe time for a better ISP" is a little bit arrogant. 

All good ISPs without IPv4-Adresses provide IPv6-Adresses. That is the best, what they can do.
