### ISSUE TITLE
PLUG POCKETMINE! CANT DOWNLOAD ECONOMY PLUGIN ON IT!

### ISSUE THREAD

**Issue by PlayingWithMiner** [PocketMine/PocketMine-MP#3884]
When I do /plugins install €¢onom¥$  (that's the name of the plugin) it says: [15:24:59] [INFO]: "â-Â¢onomÂ¥$" is outdated WHY ?FIX THIS ON THE APP

**Comment by gaoyichuan** [comment]
Please don't report plugin issue here.

**Comment by PEMapModder** [comment]
Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. Plugins are not supported here.
