### ISSUE TITLE
Player Hit Issue

### ISSUE THREAD

**Issue by ClanEmo** [PocketMine/PocketMine-MP#3894]
When I am trying to hit a player they can't take any damage but they sure take the falling damage, Like PvP is disabled but not

**Comment by PocketKiller** [comment]
remove all plugins, then test

**Comment by MilkoIvanov** [comment]
Maybe the difficulty is not 1?

**Comment by PEMapModder** [comment]
Probably fixed by #3978. Cannot reproduce.
