### ISSUE TITLE
Client does not reply BatchPacket

### ISSUE THREAD

**Issue by PeratX** [PocketMine/PocketMine-MP#3904]
If you batch a packet,this packet will be ignored by client.

**Comment by robske110** [comment]
Isn't that already fixed by the commit (0.14) on the pocketmine repo (offical)

**Comment by Intyre** [comment]
Are you sure about that? Doesn't PocketMine send chunk data in BatchPackets?

**Comment by robske110** [comment]
@Intyre I think he says, that the client does not reply to them but it, however, recieves them...

**Comment by PEMapModder** [comment]
@robske110 

> this packet will be ignored by client.

And the client does not need to reply to packets except for ACK response.

**Comment by PeratX** [comment]
@Intyre Try to set batch-threshold: 0 and you cannot join the server!

**Comment by robske110** [comment]
Is this fixed in 0.14.0.Build3?

**Comment by xpyctum** [comment]
What give BatchPacket?

**Comment by PeratX** [comment]
Fixed in b3. Thanks you guys.
