### ISSUE TITLE
bug server is full 

### ISSUE THREAD

**Issue by semihstyle** [PocketMine/PocketMine-MP#3907]
hi can anywon help me i create a server when i join to the server says the server is full

**Comment by CyberPowerCrazii** [comment]
Are you using Windows 10 edition to join in your own home hosted server? Its not gonna work. But if your using in android, try reinstalling MCPE or deleting unused files in your directory.

**Comment by CyberPowerCrazii** [comment]
Or try connecting to other wifi connections (if you port forwarded) and connecting to the server.
