### ISSUE TITLE
Pack to phar php7

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3908]
I cant pack pm by devtools
Jenkins down
What will i do?

**Comment by CyberPowerCrazii** [comment]
Are you sure you have your src files and plugin.yml?

**Comment by CyberPowerCrazii** [comment]
and this is not place for reporting plugin. instead in Pocketmine forums

**Comment by HmHmmHm** [comment]
DevTools not compatible php7
but ifteam already patched DevTools PHP7

https://github.com/organization/PocketMine-Windows-x86-PHP7-launcher/blob/master/plugins/DevTools-api200.phar
