### ISSUE TITLE
Client cannot connect to PHP 7 servers of ports ≥32768

### ISSUE THREAD

**Issue by ZizzyZizzy** [PocketMine/PocketMine-MP#3912]
Let me explain. I thoroughly tested PHP 7.0.2 and this version of the source code. It was working perfectly on my dev system on port 25567. I was even able to patch some plugins so they are compatible and working (with warnings) with the new API. (Feel free to contact me and I'll tell you how.)

When I went to test in production, Multicraft assigned port 55756 and I was unable to connect with my client. Sometimes the console would show a connection, but the client was still spinning its wheels. Sometimes the console showed my character drowned, but the client never actually connected. Other times I could finally join, only to have it lag out and not really be connected, even though my character was running around and breaking blocks (but no drops appeared).

I have not tested to see at which port the issue begins, but it does not like 55756 at all. I'm not certain if this is a Pocketmine issue or perhaps a raklib issue, but it's easy to reproduce either way.

Compile php7 using the compile.sh build script here:
https://github.com/PocketMine/php-build-scripts/tree/php7

Then use the github PocketMine-MP source from this repo. Run the setup wizard, select port 55756, let it build the world for a couple of minutes, then try to connect with your client.

**Comment by robske110** [comment]
I don't even understand what you are trying to point out ;)

**Comment by ZizzyZizzy** [comment]
Start pocketmine on low ports, like 19132 and 25567, and it works fine. Clients can connect and play normally.

Start pocketmine on a high port, like 55756, and it no workie. Clients cannot connect and other issues mentioned above.

Older builds before this php 7 version do not have this problem.

**Comment by PEMapModder** [comment]
Do you mean any ports higher than 32767?

**Comment by ZizzyZizzy** [comment]
Oh, good catch. 35566 works, 35568 does not. It shoes up as green in the client list, but I cannot connect.

Integer size issue?

**Comment by jazzwhistle** [comment]
I'm having the same problem. I run 10 MCPE servers using Multicraft - everything works fine on 7 of the servers I updated to use PHP7 PM builds, but 3 of them will not allow any connections (despite starting and seemingly running correctly), however the same servers when configured to use PHP5 work perfectly.

I'm running CentOS7 CLI on a dedicated server, and have tried reconfiguring and disabling firewalld to no avail. If I change the port of a broken server to that of a working server everything starts working... so I've been trying to figure out how the switch to use PHP7 causes connections on these ports to fail. I've run netstat etc to see if anything is interfering, but everything looks identical whether they are running PHP5 or PHP7.

The only pattern I can see is that those that don't work are the three highest ports:

Ports that allow connections on PHP5 and PHP7: 19132, 19133, 17171, 20000, 25252, 11111, 12321, 23456

Ports working with PHP5 but not working with PHP7: 33333, 55555, 41414

**Comment by PEMapModder** [comment]
So:
When greater than 32767, no warnings, but clients cannot connect to server?

**Comment by jazzwhistle** [comment]
Exactly that

**Comment by Jorti1** [comment]
How do you set-up php7 on Android? I have downloaded the files already

**Comment by PEMapModder** [comment]
This issue should be reported in RakLib.

PocketMine/RakLib#16
