### ISSUE TITLE
Arrow doesn't shoot when player jumps

### ISSUE THREAD

**Issue by CaptainKenji17** [PocketMine/PocketMine-MP#3913]
well I found the causes of this ;)

it dont shoot arrow when you jump and shoot

**Comment by PEMapModder** [comment]
I am experiencing deja vu reading this. Is this duplicated?

**Comment by PocketKiller** [comment]
confirmed.

**Comment by thebigsmileXD** [comment]
#4029

**Comment by GlitchPlayer** [comment]
This issue existed on my server.

**Comment by GlitchPlayer** [comment]
Also when sneaking, you cant shoot also.

**Comment by PrimusLV** [comment]
After player jumps or sneaks data flag ```DATA_FLAG_ACTION``` is removed

**Comment by thebigsmileXD** [comment]
So a client issue?

**Comment by CaptainKenji17** [comment]
No its PocketMine issue

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
