### ISSUE TITLE
Adding "getter" for inAirTicks?

### ISSUE THREAD

**Issue by legoboy0215** [PocketMine/PocketMine-MP#3914]
Hello all PocketMine contributers:
    Can you someone add a "getter" for inAirTicks like getInAirTicks()?

IDK this kind of PRs will be accepted or not.

```php
public function getInAirTicks(){
    return $this->inAirTicks;
}
```

**Comment by xpyctum** [comment]
```php
$this->inAirTicks;
```

**Comment by PEMapModder** [comment]
I think it is more meaningful to directly create the pull request than creating an issue to ask if the pull request can be created.

**Comment by legoboy0215** [comment]
Ok. And @xpyctum, that property is *protected*
