### ISSUE TITLE
Block keeps reappearing.

### ISSUE THREAD

**Issue by OnlyZeNo** [PocketMine/PocketMine-MP#3916]
I was casually building my server spawn, and when I tried to replace blocks. They would always just reappear. According to my console, RakLib is constantly banning my ip for 5 seconds everytime I try to remove the block. This is driving me insane, because my spawn is jacked up. 

Console Info:

31.01 22:24:00 [Server] Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
31.01 22:24:00 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': Illegal offset type in unset on SimpleAuth\EventListener
31.01 22:23:37 [Server] Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
31.01 22:23:37 [Server] Server thread/CRITICAL Unhandled exception executing command 'login getShrekt' in login: Illegal offset type in unset
31.01 22:23:25 [Server] Server thread/INFO ZeNo joined the game
31.01 22:23:25 [Server] Server thread/WARNING RuntimeException: "Illegal offset type" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 42
31.01 22:23:25 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'SimpleAuth v1.7.1': Illegal offset type on SimpleAuth\EventListener
31.01 22:23:24 [Multicraft] ZeNo ran command Message of the Day
31.01 22:23:24 [Connect] User ZeNo, IP xx.xx.xxx.xx
31.01 22:23:21 [Disconnect] User ZeNo has disconnected, reason: Kicked
31.01 22:23:21 [Server] Server thread/INFO ZeNo left the game
31.01 22:23:21 [Server] Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
31.01 22:23:21 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': Illegal offset type in unset on SimpleAuth\EventListener
31.01 22:23:15 [Server] Server thread/INFO [ZeNo: Saved the world]
31.01 22:23:15 [Server] Server thread/INFO [ZeNo: Saving...]
31.01 22:23:04 [Server] RakLibServer thread/NOTICE Blocked xxx.x.x.x..xx for 5 seconds
31.01 22:22:59 [Server] RakLibServer thread/NOTICE Blocked xx.xxxx.xxx for 5 seconds

Current Plugins:
DevTools
SimpleAuth
SimpleAuthHelper
PurePerms
PureChat

**Comment by jojoe77777** [comment]
Does that happen with any block?

**Comment by OnlyZeNo** [comment]
Indeed it does.

**Comment by OnlyZeNo** [comment]
It's mostly oak and source wood that I've had the issue with. I just cannot get rid of them.

**Comment by SalmonGER** [comment]
Try to remove it with WorldEditArt. (//set 0)

**Comment by OnlyZeNo** [comment]
I'll give it a try, could it be SimpleAuth causing the issue? There are so many errors because of Simple Auth.

**Comment by OnlyZeNo** [comment]
So I added WorldEditArt + NameCorrector ( a plugin I was planning to add), but now I have no permission to use SimpleAuth anymore?

**Comment by OnlyZeNo** [comment]
There has been no hope with WorldEditArt. This is really frustrating.

**Comment by OnlyZeNo** [comment]
31.01 22:58:37 [Server] Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
31.01 22:58:37 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerQuitEvent' to 'SimpleAuth v1.7.1': Illegal offset type in unset on SimpleAuth\EventListener

This & RakLibSever banning my ip everytime I delete the block is happening.

**Comment by PEMapModder** [comment]
This issue is caused by the SimpleAuth plugin. Please do not submit plugin related issues here.

**Comment by OnlyZeNo** [comment]
If so then how did I fix it because deleting SimpleAuth doesn't fix the issue?

**Comment by PEMapModder** [comment]
@OnlyZeNo this issue is entirely caused by SimpleAuth, and by uninstalling SimpleAuth properly it can be resolved.
Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue or commenting on an issue.

**Comment by GODLIKE5** [comment]
@PEMapModder No Not at all and i have proof. I have tested the Pocketmine and ImagicalMine and it gives me this error and i do not have SimpleAuth installed. 2-3 weeks ago i had made 8 generated worlds with mcedit and sure they worked fine until i installed the update of Pocketmine and then when i ran it the whole world whats without chunks and i just fell out of the map. This same thing happened while using ImagicalMine but later than the official Pocketmine.

**Comment by OnlyZeNo** [comment]
If the fix was that easy, this would have been fixed a long time ago. Removing SimpleAuth does not change anything. I STILL NEED A FIX

**Comment by PEMapModder** [comment]
> 31.01 22:24:00 [Server] Server thread/WARNING RuntimeException: "Illegal offset type in unset" (E_WARNING) in "/SimpleAuth_v1.7.1.phar/src/SimpleAuth/task/ShowMessageTask" at line 46
Explain how there would even be a message about SimpleAuth if you removed it properly?

**Comment by OnlyZeNo** [comment]
@PEMapModder Clearly, I showed that before I removed SimpleAuth. As you suggested I removed SimpleAuth thinking the problem was going to be fixed and now there is even more jacked up reappearing blocks.

**Comment by OnlyZeNo** [comment]
@PEMapModder If you believe this is a SimpleAuth error, then how do I "properly" uninstall it?

**Comment by PEMapModder** [comment]
@OnlyZeNo when you execute /plugins, is SimpleAuth there?
