### ISSUE TITLE
Crash Dump

### ISSUE THREAD

**Issue by Podracky** [PocketMine/PocketMine-MP#3917]
I am trying to set-up a Server for my son.  I am non-technical.  I followed the directions as best I can.  After I set up a first server, I went to install Lucky Block - there was an API version issue.  I also remember that when I installed the first server I inadvertently forgot to type in the port number.  So decided to deleted the file I created and started to create a new server.  While creating it, I received the following errors:

04:57:08 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
04:57:08 [INFO] Loading pocketmine.yml...
04:57:08 [INFO] Loading server properties...
04:57:08 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
04:57:08 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
04:57:08 [INFO] PocketMine-MP is distributed under the LGPL License
04:57:08 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
04:57:08 [CRITICAL] Perhaps a server is already running on that port?
04:57:08 [EMERGENCY] [RakLib Thread #123145304449024] RakLib crashed!
04:57:09 [NOTICE] Level "world" not found
04:57:09 [INFO] Preparing level "world"
04:57:09 [NOTICE] Spawn terrain for level "world" is being generated in the background
04:57:09 [INFO] Starting GS4 status listener
04:57:09 [INFO] Setting query port to 19132
04:57:09 [INFO] Query running on 0.0.0.0:19132
04:57:09 [INFO] Default game type: SURVIVAL
04:57:09 [INFO] Done (77.053s)! For help, type "help" or "?"
04:57:09 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [48]: Address already in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
04:57:09 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
04:57:09 [EMERGENCY] Please submit the "/Users/jenniferpodracky/Desktop/My Minecraft Server/CrashDump_Tue_Feb_2-04.57.09-UTC_2016.log" file to the Bug Reporting page. Give as much info as you can.
04:57:09 [INFO] Unloading level "world"
Killed: 9
Jennifers-iMac-2:My Minecraft Server jenniferpodracky$ 

What do I need to do to fix this?

Thanks,

Adam

**Comment by robske110** [comment]
Please go to http://forums.pocketmine.net with this!

**Comment by PEMapModder** [comment]
There is another server on the same port. Please read the message. This is not a PocketMine issue. To get support, please refer to the [contribution guidelines](../blob/master/CONTRIBUTING.md).
