### ISSUE TITLE
Crash FactionsPro

### ISSUE THREAD

**Issue by SamyR0** [PocketMine/PocketMine-MP#3921]
ImagicalMine Crash Dump Wed Feb 3 19:54:58 UTC 2016

Error: Call to a member function getName() on null
File: /plugin-848.phar/src/FactionsPro/FactionCommands
Line: 217
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: FactionsPro v1.3.2

Code:
[208] 						}
[209] 						if($this->plugin->isLeader($player) == false) {
[210] 							$sender->sendMessage($this->plugin->formatMessage("You must be leader to use this"));
[211] 							return true;
[212] 						}
[213] 						if($this->plugin->getPlayerFaction($player) != $this->plugin->getPlayerFaction($args[1])) {
[214] 							$sender->sendMessage($this->plugin->formatMessage("Player is not in this faction!"));
[215] 							return true;
[216] 						}
[217] 						if(!$this->plugin->isOfficer($this->plugin->getServer()->getPlayer($args[1])->getName())) {
[218] 							$sender->sendMessage($this->plugin->formatMessage("Player is already Member"));
[219] 							return true;
[220] 						}
[221] 						$factionName = $this->plugin->getPlayerFaction($player);
[222] 						$stmt = $this->plugin->db->prepare("INSERT OR REPLACE INTO master (player, faction, rank) VALUES (:player, :faction, :rank);");
[223] 						$stmt->bindValue(":player", strtolower($args[1]));
[224] 						$stmt->bindValue(":faction", $factionName);
[225] 						$stmt->bindValue(":rank", "Member");
[226] 						$result = $stmt->execute();
[227] 						$player = $this->plugin->getServer()->getPlayer($args[1]);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux hms03 2.6.32-44-pve #1 SMP Wed Jan 13 11:07:55 CET 2016 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
SexyMOTD 0.2 by hoyinm for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
ChatLogin 1.3 by EvolSoft for API(s) 1.11.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
Slapper 1.2.9 by jojoe77777 for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ScoreBoardStats 1 by TutoGamerWalid for API(s) 1.13.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
BanItem 2.1 by LDX for API(s) 1.0.0
ColorMatch 1.1.2 by CreeperFace for API(s) 1.12.0
LightningOnDeath 1 by MichaelM04 for API(s) 1.13.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
iProtector 3.1a by LDX for API(s) 1.9.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPIly20aWv9KhXDXSFEHx0kWXUquRZceJZGktOt6dIKVqAA0SEYBG0IAkJpV/3/deN07SFiUx
2YnnEPDQ/e5+RxON3ztZEInOZDDeG+8Nj4ZHh92OSFOZdia/d7JFAo86ZzdnHz9efux0O5FQis8Q
dsrDkGWScRaJyBEp8/PYzQIZs5nIPvBIbO8wuInzMIR5fhDipN0kzGdBbB2OD3vJnKe7KnV333Ka
p65SWVyfyijisadgZhjEMHM4OPij29GzAU9tCgxxpSeQ22H/EJ7ZWfWfP+DpsH/Uggb+9qtsHijr
W8POt4E6F9wT6farJOQLke6w42Pm81CJHfY74hj0Wzjs7JUSMUyxvsW/F1ovbby+TCOeFQ/tzv/K
nEW5ypgjWEgUUYW5Egzn2Z2dnddEbbBELRVZnsYsS3OhhwxXiToYPSoqWOeKZDQ6rET+5pg9Opan
M/XT4OedQi3jjahFE2GBYrHMWBCTNkD/RPSbSi17j6tlf6VaDpbV8s2SC1z6fuCiDywp4Vqkd/Bg
p6aRShUE1A5fquVww2rhYQresmAXtNQqhRw9qpBhf5VChm0He2WUjXKwNfzA+Iwm0XbFVyqLsmUs
ngPXqUh4isK9/3B99nHKLj+yj2dX5yenZ+z9h+kli7jKQOZtTaBbOEGXpTy+3WE/npx/Ortm25Pi
+aQcMKERr0E5mqvRKq6sb50g9n7kYY48GCx2p8tUlmYylPd1yxpE4zUQGS4QU12VBsPeGhiQe5xu
d0oj68ltj36VCpWHpF+NRjwIN8/A/fT4tq8bW6206lcd+3UHQm6WcheC60+drT7b3pmwRLq3Iosg
KNu2nm1966Zczd/kUbLtSAlhLd7p/NztzEQsUh5iYIZRCjQCjA16fU/cAZ9OHoReZ9KHoJ7KTLoS
Bo4g9fAkoGGDca8Pw2ZBBrf9Nf/BhJTfhoGDc3oHhCGPOaa3znkQ5w9sHqn+iA17+73R0BqPreRO
sK0Bu764Yp+Fx77nMRuM2GAw6R9M9vbY6dmUDfuDffZwuH+zPwZ0yTwBZHuAYIDYf4PVDPeIsK+f
3khVUAMA3YR0U+YvhSo5CQNOF4Y9fd9tqGpIOHmezWWq0Ab/5u533L1F7ZKefkJF4SgAiJg7oQBm
cOl3O55IBCbQyU/wTEk/e1MHRJzSKBG17Qu4Ow25onQrOQp0dXk9/Xz58fwNgO6Fo4IMmMRcDlKc
gonTcz6b1divYE0RBm0RzgX4hXfpX5xenTXk6D9fjJK4bZ9LTKqPyNGZZ1miJru74F3z3Om5Mtqt
87VbSQPivs9EdMqVAH4reWvApsD93mFTYB4GebhomqxPWoGL0fOF1nhtGySKXOAkEdqQ69nwR5mJ
j+Kep15NqBqwJtSoab83/7PsfhB2XmI/wGnbFfG15CAbggnvYFpK03qRm4geCALi/SBE8j6+E3Em
00VNwib8kdXmyAXEs9tNeWmD9lNsdR3M4uu5TGpylKC6CGQDiqujpiAP8NwJcGkWV5sKIAUfkAsq
jtYxm2GkF4tMQR3fk+nM9AZqt0QFsr8Rd1PIKfVIWYJakabftt8VpaoLSFVsKnjUEHrUGzxX5oK+
bdc4MTJfT08+Tj9dPRZsKs52Sxwg7OBODWqC0m1dSJCwt9eQse2aXRNynykacBT4AdjGtmUs7sAy
EFQuY/Gjgv9b01mpJvghyOomqwGbRms56tmdDK+Bt6Z/vkCginB7wX3JUmCo+/v7ngBOEGkvu0XL
XPB48VmmoVeXqgZsL8PRejnghaEfWuTFPTHwlHByOufZqYiV7vCL/F0BmxYar2Ghoxek7pLuugZS
qy00DSJhdg1EXbAmvCbb8Ktprb6YumVywLih/45fmO0abD3Fejp0vMubmbsObfoiiNC0IEYdKNh9
SJvfX33YmE820dp2k6OnVmNNbLs1ZLudMsicgFBLQYaALRUM/pIog5SLnshw8axYcy0eFheX0zcN
0QyoJli/1/TguVwEcbS5zG5IokQl8XX8M0/Fu/fXdd80kHad3MrW++O3b/v9jfF/o/GBI2ry5cXT
kzXMuzKlSYEDBP1XCE555vvCbaS6BrgtcjN5d95Fny82JjAis+06+ebdmuYT0O77eXid8Pu4bsQG
vB5Ge+OvBtIRxZ+XB8wGA08JmGdKQckd8FA1GrgGuN2zjlb1rEo3h8u15EusVmdjU91rQzTUgCtj
GS2uWj1EA9wuYIZNDUAh6MD/Nia2wWfbQjORKGoiWiytWcycS/pRoFHLaNhfW2yWdF9Ya56+O9i/
ocLyzMPtr6rgbD1p9gZ7baNFRRIF3whydbDfkPTw+YJG7uxg37Z1v2bbVIIKYMi2S94wYL5fc4V+
J8Lksu6ZBtCOnq1SdEXCe0EhqrHZtqZd/F2zm0UrugtHpG7uCGt+i2uyYzr3K5lmehe01rsbYDvu
tAx4dBQKGbtzHs821byWCI+OdM+uOVl/y6UVeGos7tYEQ9lDniSNUryAtLddjppS/yJ/keIA/20s
3ChNGTumtetszPoijVSrktGwtgjDv66WIQZqly+uZzSWYp8p41mu2jtNGlgXerRcwD0kCzfLo01t
l1WEzeZSwcQ6OV/nkZOr98v5DoHtbHf0eLb7UkM4NPXNqGwQq3pH/x1sKkkCL2WK1FKssx/jylT8
S0LnhApsWLb1pKaUQUMd0zyT72BO+pmHgdf06hdsYBN9p6T/lJruxANWs0AF8eyHwL2t/4zSevL1
pmNDrvqGp7cfRgpEaJFfAjzJfb+XzrL7IrDtvuO/hfv+Ip3SfbUUa28ngmeES50+Advbo61AnCl3
nkIPxLaLq8Fw9F8z4DDEWLizqWBVYC/6f+Stfv2EOqJAhVvjGJXrr7pUKmi+ANOocts6mIpsLlLh
3WwsH9WI27a5eUJDpl1gdTeyshk52EAzUg//T3DaRl+yfltS1sEnab2Ab4CXQtONIzJ+44m7m63+
uPUr4tXZBU8upIft4YZ8NhERTyJCWavheVov4zWfTy0Ka8zuXkc8DK1/n1pFyZGlQuzqtzx2G3Rw
T4XH+MNqfTvFQFo7ep1HN29fstdgiD5pU12GElZ65tZ3JGvARyr9U1BKQq/XbK7HrqjbdoOTNcQ5
D2bzLIakdRm/Ebyxzbr06It1w0UAfYEIL/rjjdUMbeJPMdEFnwXuVIRiqSNrP3kkoP5Zv+ZkyVPE
mfJkKt/Uc0IBaa6VpdXylocb+00740kmPcgCFe0nlOc5ZY4VJbp58IxNqT+rznlm+uBakqpsLyVb
swXFPaVWB0qgtouOHm9AH9vZqrW3SxI26o0vNKbIV3X14raUkIAWAiCZCTdr/FxZAza70gH/emo4
emFqqAg/e8sE8Fi0T1sToloUn1TeeGOlAW6XDIP/v8IoR4ZKvy7YW3/xT/nDspQIfOSn9L/Bos/4
Q6kYLdH6ajnnsbesF4I+Y9PizzJ+CPyUIhrm1pfxlEM7LJelNPC/f9R3SZBSQaVc66sIIgOUg9mK
QFA+aatpf4PuYEz6POkTw2H1c07F8hPaQxGGK9pDEYb/Ue0h8FO1h5q5JxRAQZrIRoPYevCMjZ4/
S1KuWaoqmZLFtd5gjJJQfOZp8x3GEth+ZaW/XLEG6a16YWsEeFQ2TXmsfPoV4jqU97Xbxs+mlSJ8
Q9y2FTF8DwzjjnSN+bU1oPsLtaSEAt7ezRqto4fHyve6or9i8LacieapELVi8VFp8UV3noJ80OIX
hqCdsJ4JDYHAt+K3rso7dipjP5gxPCVmp3a8he/ivxUOG7HB0WR0MBmO2afpKb2Kj88jmXnHeFzh
5u30MwI0fgt5Ph4cDUZ7NEpEMl1YYRAFAO0Pxxf/QvD9HFgFqMqOpe8jhMexzGNXWPqkhMXdeSDu
RATuoI6hekcC+NqBleiCDQwE+PpEgz+YWep4sKdhPATHsvwQe9XGdB4HEeiwAYukUwBmHDn2xDFh
8WUKHJUww+qcpx7umxf3yV1iZnsBHl/Kw2xxPCJsdPwCiktLiSyDllkdIzgEwUILve+Y9nwqmBLC
qw3Bo3/Hb87ennw6nyJU+5f1ay7ShSFpQClEBAPBy17ClQLc3vE/6R8oJM+kpfidKCTX1gqSY5Xe
DXrzCAE9kRMG4akMAo/l8hCk4aTsQkJF9EI5Q0cpVIDHLspDKb1FFKJvMSzOmUtulaeEhbyLgVpZ
9fqtdXEF3samc6EEK/TEeIrn8QQDNhRc8Iy56CJ0ai+I3TD3wD0B/ZJXI65rGcFMHxG0cSruiy6T
uB2rECVzUsFv2ULmqcHFAp+BuQM/IApg6RT8LVwg4g/ivkS36wmfg60Vu5fxPzKGP2/ylKGiIxAW
dBcu8PSlPkeHct/PRczyZJZyDxD07JihHTS2CdxtTeepAN0CCNiAAm+W85lgeLSSdGZspgK4DyUQ
CH4jreLU07lwjRjNicBB0QCJuHcf3AaJ8AJOb3vj3e45rMIb6d+8v7682R8dWcMbnAd6LBFNmA2h
bWZ3kNDnOe1l45lJPEbH8AiqylJScIaRHPwFFEePSZ3EKfABVyIjm3riLnAFm0OFE5KVI0Cs11pF
kk5+AlzN88yTuEr1mTxkxs77fX4w1n9CcwQqBz4szmSSBhmYOWeceeg2eDAKLJ2JOw52xYAitCQn
GCMYBiFgnpk339ldwNl/4wKDIbTQLPNkQgf6cOL1HOZx9GwlQQDDmDYvN4jwQKkCSRNwHlII5HoY
CXnEQ9VWDyzg3ZFKVOjPaEkXeEBJDKMNAxcHL0JWnQUzvgfDTQAon1aa2/ocgG1kDG7IPY/pI2tK
swn+eQvscOgZKcbiAUdHoD7ATuLXnNO54llwB2Pv8Hgc2zYkIQHsAHJNDwIPJSkLHGA2E+kEniLl
DzkdR4YleKIWsTvl6hZWSXoLiw7dfuuTAo2gSxdC4qh5ClVNDl4Eo1WXUWhkJoTS6ULo3EFrCpMz
qQVSHsKiPIbVhkMI9zV5GR7YTIDJBwj3mQAVgDi0OuKSNdSqZue9j6uaTlLD6u2yIPsHHqxOaZYn
MN+Q47bmsm2QAA8OD1EjJINlpJwQJlrhOgXS+n4XSgc0i+mfaTCjzIiBLBIz7iwy4Ihda176RF0H
XB0dQKj7gDgjbTPMcSbDGpAixfgB+AvENoEnXRCLD3GloKjtD9Lk5LUzCYJIXKh0/DlmM2JSp+wJ
65MMbItieTbHI7D/4fxjLfU17jF9v4h7yI0JMWACXMmQwaYYrCpMwMIr2EGabZ6uRBpIymG4GBWS
cymIG97KBTcAQhBrPHQyGmHBghBmqVHsl1Azx7BGQW8YH76kVq1OqL1CSgu42vUwm9I04oD1V63l
IpAgjUsMI5gZaUJveTjKbepf0GEiXEygivSC7Gol67mlDKBKkahK0lHfiKp2VrJkBB8ZwWc8dcAF
LFeGoS4JcZWt1Cx5FPJi5jAzBxZwxOOccnWdDahjcvCGnW4RGFruYPxBB1d6uZewR5Wf9dilzpN0
Bz4xl3nolYwEEEbuY1axjq7LEuK89BG29ZZWwlJ0JGfRU0uJ/FRGRZDFuea5VY9LZZLRIhjLtX1h
hQPVJ2K97c7z+FZpdZ+T22NQJCDyhv0JCsOKI+K4QFOoW5QeZGHpgDVQhQtRFWY2K2VQMPpG6mlt
62EiwApLT6tj0FTMsBdIXVsClI+gJAb31YIXtbChhQ+qCY9hs+NYZGiUsvADBwl1UnTwR0KqSTgW
yZALwatMdKJ1qOta81QHJUeU6ZHCzlY9jBVPMAKkiwxxd5k1qLk0pkEia2UFKxMYoaNLlXWpLcGU
5+moZ8yopwLQsNRj30HjRefdIyxdTq8+dWEuMOBAHLoPvGyuozet8hK9Rei13bFEqIoHRXqpDe2x
Ew8W1ZyH/i60CLqe8QR4myEEJLUXyri+Kss8XcNVq5jOHnAFYkHEw65e3Uj4cxBDCQpige8IVXwu
5NNVfFXUDFXFj+UQTqJTtFjux4llbhvVGfRSwslnE1N/fMsGWHeYDIMFJj0uikulv8ghiqLTNrYw
ytIlo2K7it7Q67Ldmat1S59wqS2Aos9sdB2iqCeZ/vyFbrhoqHEvlJcs7oIWM/IwM8XSUyYsgkcz
042AQLQFguziy1dKRyfewG8+NZLVyIM2s2VuaKWS7bY+XE7PJoxiL/zXzaE3i6E3098swT0Squ89
nT2QcsleaeOThrnotVlRyEpuRJkJOEG3ydB1hn2TSDCi6QSFfoQdNcJNVjIqboKLUKbL4mtcriig
w5WoEdsewEpZQaXLhvBgsOqByNzeDi1aJepckDtMETM2ZmZbhAkITpoe1gDaktQDV80xBgJqiLCM
wnDAw3u+UBq3wVP33kYcJz86iWQe1xOBMtVbwQXyj+iwfYAYjZeG4dVTeQpQTzNvvhLSyD5fmEvO
FQvdhDpC43KEj5GINnwwYqEVSpx6G6gW+QjxNb+D3ItVXoCttsA+LFmYfQWTkMqqhuKErz+cYpRi
opgPjSkOkwoc1cIFGrg6mVAvlmIvD24BaAs9/SKxJdIrQ+HHYPDrUOjSmGJK4cslrS2B2iwsccEf
GG+rBZohl7JD5Q3LhvjIvSBXtVnGBtwwRytUzzROh+P1ZNpss/IEum5RcxUXP+Sg3Qh77SXGqw6v
4L23zLyJfvc8oGYdGvNcGPOa+bToCW4pMJaR58nYEpnkocFmrjEztRHbMS1JC9SHXOtdRYv8CEQf
44dQ0FchWGe4Y2PgAw3GEIFbcRO2rwHGsPjZljyZsKO+rv+0W1IE0RWHwQeYDvREQxhR72nAPUeC
JdhAeeQEsApwGGGmIKVb94kOTLjLQDslGqoTrnEZ7cumuC/th15u4VZRE1KmlgY0mSdB7MvKK+YS
XYFI9mpbh1AUaQZjGS8iLP1pwSjQtio5xW7GPGbVY+IYfI8zPptBKjKbBuV2DNaN+CWd29XiaIYQ
nVrJEGpM+zZZvD0dfEQ/nWgrpLFlUnU5RENlUttJOsUNSNoQE6FMMHd1Gb6BiLswwIopzKBQ8aF8
FqBuyFYxZn0cZBJtjvbBza4KCTM/YdQqihwqUJXpdFfEP4MNbaQfF/hVSyv4TuwqneCna3QxDJUT
x/Srb7B+AQKGi0nBDj0Cv8cGesJ+wksLck6XOuqfCaWOi0VZUt+8JTGKNkK3csXuOvVoq/aCqeul
rKaogkDBIygsAuDUpPwa70SVGKArhpvxuJbHdFdSm7C35yfTyfD1QXfv6GHQHT2MusPXg9ceZGYd
x7bx/UoXY87xYZ/NwMeVvhvv7XS6HViaM6w+qr1yWhTdjnjIRIyKol+nTiFf1T9zhM5Vv4fMMSun
Ji4ONjfq1zDIxEh/gMnS33r6TX+RSf8q77gRvVBoxuP+bOzxtALobw4Wd3la8egHYYYnigD1QP9I
6GdJ+XTmVZdRBZ7DKtevy8D4X1R5ZAffBIgcvXtcDoY6cpFklTAZR968uujXV+fEAb6WkLhQAFaT
FyA8fQ7KXLE9fEdngFpgFv54Nezv9Udw+eo9GHfk7h8eOvuO44763mif+yPujsa+542dA2fPOTg8
8MUe/GOvgNLVHFVUvg+RSBU8VAYwfb4ZQOfdPwrfdKkAJXrC9

**Comment by PocketKiller** [comment]
This is a plugin issue, report it to the plugin's author, also you're using ImagicalMine not PocketMine. close your issue.

**Comment by SamyR0** [comment]
Why i need to use pocketmine.mp?,if i use, will works FactionsPro?

**Comment by PocketKiller** [comment]
no, please close this issue and report it to the author.
