### ISSUE TITLE
upon death, i cant respawn, or go to main menu.

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#3922]
![image](https://cloud.githubusercontent.com/assets/10010369/12798480/9326a9ec-cac1-11e5-805f-7f0ebe714d20.png)
Upon death, player can not press Respawn, or Main Menu. This is quite annoying.
(Not my server, but it does run on PocketMine. They tried the PocketMine alternative, and it works.) Just letting ya know.

**Comment by gaoyichuan** [comment]
Maybe you have enabled the hardcore mode. Check your configure

**Comment by robske110** [comment]
No, thats an bug and if hardcore mode would be activated, the server would just ban you.

**Comment by UltimateMcraft** [comment]
It is the **server** having different data then the **client**

Here's an example:
Client data says you are dead
Server data says you have 5HP

**Comment by thedeibo** [comment]
maybe... its not hardcore problem... so maybe UltimateMcraft is right

**Comment by PocketKiller** [comment]
@UltimateMcraft is right.

**Comment by PEMapModder** [comment]
Should have been resolved in #3978
