### ISSUE TITLE
Maximum Memory

### ISSUE THREAD

**Issue by bbaker28050** [PocketMine/PocketMine-MP#3935]
Hello. I am running a server with 100+ players at a time on a 32 GB Dedicated Server with 4.4 GHz. I have noticed my server slowing down and overloading and when I looked at /status, the maximum memory was 1GB (1024 MB). I've done some research and I have successfully changed my maximum memory to 20 GB in the manager, however, the maximum memory is still coming up as "Maximum Memory (System): 1024M. Is it possible to increase this limit in PHP 5? Thank you for helping me out

**Comment by robske110** [comment]
You have to set mem limits in pocketmine.yml
anyways please transfer this to forums.pocketmine.net

**Comment by bbaker28050** [comment]
Ok, but I also do have the memory set to twenty GB in there
