### ISSUE TITLE
[Question] Can u add loadbalancing proxy system based on changing of sockets? 

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3940]
Sry it is not issue.I know it. I have server with 150 players and i need loadbalancing. Your pocketmime cant keep up my players. I cant setup roundrobin bind dns. It is very hard.
Can u create new branch with proxy system?

**Comment by darkspive** [comment]
Pocketmine also cant

**Comment by PEMapModder** [comment]
A proxy system cannot be created from PocketMine itself. It is unreasonable to create a branch or submodule for that in this repository.
