### ISSUE TITLE
Cool.... Very cool

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3949]
![screenshot_2016-02-15-22-47-50](https://cloud.githubusercontent.com/assets/14966273/13056312/7337d74a-d436-11e5-9a14-414a3fb29fb9.png)

**Comment by PocketKiller** [comment]
Duplicate

**Comment by PEMapModder** [comment]
Please follow the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue).

* Do not submit duplicated issues
* Please submit issues with _descriptive_ titles.
