### ISSUE TITLE
No Sword PvP

### ISSUE THREAD

**Issue by SuperDude36** [PocketMine/PocketMine-MP#3965]
So on my factions server, any PvP thats not a projectile (bow, snowball, ect.) does not work :(

I even deleted iProtector… Heres my plugin list:

BlockSniffer v1.0.0, ClearLagg v1.1.0, CrateKeys v1.0.5, CustomChat vINDEV, DevBAN v1, DevTools v1.10.0, EconomyAPI v2.0.9, EconomySell v2.0.7, EconomyShop v2.0.7, EmptyWorld v1.0.0, EssentialsPE v1.1.3, FactionsPro v1.3.2, FastTransfer v1.0.2, ManyWorlds v2.0.3, MSpawns v1.5, NetherChests v1.1.1, PeacefulSpawn v2.4, PurePerms v1.1.12, SimpleAuth v1.7.1, SimpleAuthHelper v2.0.4, TapToDo v2.2.1, TierLoot v1.0.0, TimeCommander v2, VanishNP v1.0.0, VIPSlots v0.0.4, VoteReward v2.1, WorldEditArt v1.0.0_beta_dev_#048, WorldProtect v2.2.0, xyz v1.0.1, PureChat v1.3.0, BattleKits v1.0.4, SimpleWarp v2.1.0, SimplePortals v0.0.3

The person is NOT in my faction nor in a world where PvP is disabled (they are not in god mode with EssentialsPE either. Wow lots of protection plugins… Also not in peaceful spawn area). This NEEDS to be fixed because factions with bows only isn't very fun.

Thanks!

**Comment by PocketKiller** [comment]
Peaceful spawn... this is not the forums, use the forums. and read the contirubuting guidelines.

**Comment by SuperDude36** [comment]
Uh ok
