### ISSUE TITLE
Pocketmine and Pufferpanel problems :(

### ISSUE THREAD

**Issue by zacimac** [PocketMine/PocketMine-MP#3966]
So I have a Minecraft PC edition server that we can all access the console by PufferPanel. But Yesturday (19 - Feb - 2016) I was looking through the plugins installed on the PufferPanel and saw the PocketMine support plugin. So we created the server but when we launch it it gives us this...
`Server is starting...

---------Running Pre-Flight, this might take a moment or two...---------

No directory, logging in with HOME=/-su: line 0: cd: ./public: No such file or directory
[Scales] [WARNING] This server has been detected as crashed by the management daemon. Restarting now...

---------Running Pre-Flight, this might take a moment or two...---------

No directory, logging in with HOME=/
-su: line 0: cd: ./public: No such file or directory
[Scales] [WARNING] This server has been detected as crashed by the management daemon. The restart process is being skipped due to the frequency at which this server is crashing (< 60 seconds between crashes).
`

I don't know what is wrong with it...

**Comment by robske110** [comment]
No pocketmine issue close this

**Comment by CyberPowerCrazii** [comment]
Contact PufferPanel, They have support than reporting to this.
