### ISSUE TITLE
Cannot use "Float"

### ISSUE THREAD

**Issue by CyberPowerCrazii** [PocketMine/PocketMine-MP#3969]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/MEEP/Documents/Hidden Server/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80

**Comment by darkspive** [comment]
It is php5

**Comment by PEMapModder** [comment]
It appears you are using the PHP 5 version but running PHP 7.
