### ISSUE TITLE
Download of branch

### ISSUE THREAD

**Issue by darkspive** [PocketMine/PocketMine-MP#3970]
When i download php7-0.14 my folder without raklib and spl...
Can u fix it?

**Comment by PEMapModder** [comment]
Please read the [contribution guidelines](CONTRIBUTING.md) before creating an issue; please don't use the issue tracker to ask questions.
The PocketMine repo uses submodules for RakLib and SPL. The Download ZIP button only downloads PocketMine core source code without downloading the libraries (the submodules). You have to [git clone recursively](https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/event/entity/EntityArmorChangeEvent.php) to do that.
