### ISSUE TITLE
Is it possible to install PHP 7 on Android?

### ISSUE THREAD

**Issue by ItzJavaCraft** [PocketMine/PocketMine-MP#3971]
Hey, I was wondering if it was possible to install PHP 7 on Android for the PocketMine MP app for Android to run 0.14 on my server. When I try with PHP that I have (5.6 I think) I get this error message
`[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [CRITICAL] You must use PHP >= 7.0
[Server] [CRITICAL] Please use the installer provided on the homepage.
[PocketMine] Server was stopped.`
Any help would be appreciated!
P.S: Sorry if this is the wrong place to post for help (I'm not sure)

**Comment by PEMapModder** [comment]
Do not use the issue tracker as a support hotline m
