### ISSUE TITLE
CrashDump_Sun_Feb_21-16.32.47-EET_2016.log

### ISSUE THREAD

**Issue by AlexNe** [PocketMine/PocketMine-MP#3974]
Ветка мастер состоянием на сегодняшний день (слим пхп7 в мастер)
Ошибка сразу при первом запуске и больше не стартует уже.
Крашдамп:
PocketMine-MP Crash Dump Sun Feb 21 16:32:47 EET 2016

Error: Return value of pocketmine\level\Level::getSeed() must be of the type integer, string returned
File: /src/pocketmine/level/Level
Line: 2710
Type: notice

Code:
[2701]          $this->sendTime();
[2702]  }
[2703]
[2704]  /**
[2705]   * Gets the level seed
[2706]   *
[2707]   * @return int
[2708]   */
[2709]  public function getSeed() : int{
[2710]          return $this->provider->getSeed();
[2711]  }
[2712]
[2713]  /**
[2714]   * Sets the seed for the level
[2715]   *
[2716]   * @param int $seed
[2717]   */
[2718]  public function setSeed(int $seed){
[2719]          $this->provider->setSeed($seed);
[2720]  }

Backtrace:
#0 /src/pocketmine/level/Level(387): pocketmine\level\generator\GeneratorRegisterTask->__construct(pocketmine\level\Level object, pocketmine\level\generator\normal\Normal object)
#1 /src/pocketmine/level/generator/PopulationTask(159): pocketmine\level\Level->registerGenerator(boolean)
#2 /src/pocketmine/scheduler/AsyncPool(148): pocketmine\level\generator\PopulationTask->onCompletion(pocketmine\Server object)
#3 /src/pocketmine/scheduler/ServerScheduler(265): pocketmine\scheduler\AsyncPool->collectTasks(boolean)
#4 /src/pocketmine/Server(2404): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 326)
#5 /src/pocketmine/Server(2151): pocketmine\Server->tick(boolean)
#6 /src/pocketmine/Server(2031): pocketmine\Server->tickProcessor(boolean)
#7 /src/pocketmine/Server(1650): pocketmine\Server->start(boolean)
#8 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/xfile/mcraft/pm/, string /home/xfile/mcraft/pm/, string /home/xfile/mcraft/pm/plugins/)

PocketMine-MP version: 1.6dev #0 [Protocol 45; API 2.0.0]
Git commit: b6361d6b30819e5fde5e822173f46f85ab8899b4
uname -a: FreeBSD php7 10.1-STABLE FreeBSD 10.1-STABLE #1 r281616: Tue Apr 21 01:26:29 EEST 2015     xfile@xfile.in.ua:/usr/obj/usr/src/sys/xfile2 i386
PHP Version: 7.0.3
Zend version: 3.0.0
OS : FreeBSD, bsd

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWgtv3DYS/ivEukDtYrUrad8qHNSXOm0Bp/HF7rVAXQSURO2ylkRVpLzeFvnvNzOktNq13eKu
d8AdUCOJxde8OPPNkMxvAyMLMYiC6Wzuz2fBfDEc5Fyby7pW9SD6bWB2FQwPSmVkIgbDQSG05mvs
ei9MU5fsgeeNYCpjlUruhSlkKe7ucvEg8ru7K/wVRWthboRIT89Y0WjDYppuNoIhcSZLI9aiHjJt
almuWU10RQrMsibP38gcuY03qhDjxwxa4yKpeWbGVTHWdTLe8x0T2zFxHVWbCim41S9PhEk5dA2i
cBH4w4GpOegZ/Tg48dnvrDqdLBdn0XM6r0Upam5UfXf3Vfv5XqylNqK+5free/XhQ6JKULZJzOlL
RmMq/lkkZvgHHEpVFxy6vqXfbtEZqHQSvCB9t3h8raom50aqEsU6DWar5xUiebxXtdOhU+o0VioX
vCR24RN2OtmItMlFPb7QuzK5hsmnwXT5h0Y7FMt7pcrXqqhygT0H5roR9YOo+zpPfkcIO/umbZ+G
89mRKN3cu7tOYu9VovIc6KMs+kDj6RNmlsVpOPWnL5M+ksN7VXBZ3m5qwdOvBa9NLLg5dSHBJuGc
eM1e5BXMgiNedsR7BfF6fyDw/EUi/uT3iFzXKoGgP9rwxUvUgvnMf4GaNqDgAZXlEyrX9PkWPk+n
8+kLhF6KIPQUcJ04F68BxPSV4mnnIYeh1BiZ67u7t2D8K7Ve92Y5FHoeb/7ccJU3a1nq8dngp4/D
gfjfgNh/DSBBbqvFIMp4rsVwkKhUoBbhwg+A0J25M5+YjdSw3aJMbyG7nJ59DjRgPKTxj7YxgYb9
mlL3+LPPbHNGTfYZ+0oYTTqQMEwLEhhmzN0M21q087+waqG2dmTpRsa2uaJm1cS5TFjWlAlCCttb
LsKVv9HcwHeqOJJOo6pWDzJFD+xWWdWCoKdaELaqBZMD1YJpK+pNqxoqxTJV7/W0M2d9FYN5p2LF
a16gnOyTzh7B4kDPYPmsntpJ3K09c6quDndtr2O7ws62ioa+U/TjX6nyr1T5V6r8K1X+11PlcGBd
PscsAzpp8G4AoWA0T8UDWCZuZJ4OIqjdAbqMAi8cRNPZcMArCdPCkT/yYdZaGmjF88k8SOfxxF8G
KzHLUjETyzAMFpNsOs+WMx4vl6tVPIUFNb/PZQxr/NGSKDQlx5PS4E0txN9uvmRwwFiwwB8F3s3t
xd+uLlk70O8DcKnDZTAP5hG7hSR+UdUsDJgfROE8Clfs8vLmloV+MGP4Q1b4gv4dyXLU8Gjc6HoM
9qbfuP96p62xQiYnyznIhQedaLAAPSfQ+hWSLjQnTm0Y/KD0Xmroomas00GXy6HjRzAz5RYBuOXa
mlxoBFatRG2kwHUn112LvVZlJtcMhbmr78qTm6Zkb0SM+oG6kzCaBKAfqTfHCZaeh2Y8/4HdXL7/
x+V7dnp9edYbrFRtzoNVMAmxcw1TC6gvzn1sFfzRq3K+AwHPQ+rRFd+WHm67oCR3bhltN9IILwcM
PldZhj2i5ODp3i+NqHfnqux11RAe7axCmfQc44ncMGLXl8yGEQ7yslSQS4UTwePJRgIiF6I02pHk
ea62XpbL9abjbEXkpYSk086zfYWK2w4oAIBwp61buuF1mqi6a1cPlZufyiyTSZOb3XlAdmpzggc5
20BU6XPspoxh7b1VdZ7u+zCj96ZgkXj+5eWbi++ubrEXjTKqABZgWXr+Gf2Aeo1RnuYPwkmB7tXh
xGhX5OgfDHGCJeQaTU3JiTyEipw9Ynlvr8ln2O1GaCyDrNiM14JKIVUKLJC4YQkanipaWSZ5k0K9
JLGaOfJNS+0GsMRVvsdUNc/EkCkYqTUSZTEkknu2U03tqDGZMbC/zCTxANPX4Fb5zpL+Vmw7guNU
ZBzMr9lWlZ8axqsKEhJDAxWgcgKOsAMVGFZUVvvtRpSsqdY1T4HACElar7cEI2ywE0xu4LjQCdLk
vFw3cA5gWGGT+VyMaCjPWK6Ai/yVDGwXv96IxOlzuBQE2RhT6Wg8FuVoK+9lJVLJR6pej7E1voJI
+aCyD9/cvPswn6y88AOuI5N2pCJ2NxDl+m5gmX2/EWhJZhTDMp+Bxg7QYdtqXmqoS8CKNEy2JXlB
FvgShrYY0BvOO2zDyzSnTS+ItI2FPVs6ZtCI3jQmVRg59oCEIrnKJsmVFmkr3AXGIcP4xwTjMI49
SM7+jgBAkwgKPDcWgcyNZXJys4G1HD1YQ/JljpfdQO6IsUaDe6aiAgchPS+uv4GZZqNSa7X9kAfi
xSBcn8UlQU9LC/RnGOYMnBl8BUWOd8x5GC1wUNWN941y8r0E06sSHI6nKZzstPVLFBdLEhCL66Ym
nGLgjbFA28A2iF8aKINhg9byQbRnzFPHFjCbUNnJBDApEJk92GGsACJm8ZedfNsUMVYEGaNCEGs/
iIn6HoJsZGd8p90Jp1UX521qBWgKroK14pAROjGHYuDQQzBIARbUmOvJQFvIK9BXNCVEF05x1G/I
mUAvCMFaPQLKGgGmALUoEMpOPLRwK9I3GUYyTsKIHTJpPgUbmprWpQKTCXno0Wp2ClrAzrPQ2oY0
8Zy2EdFq4xqBvN65qP4qVzGYWqvMMDsAvllIgzhWiDWPdwZEYzdWJJ+EkBq3vEUF0G8rSUQyP8M0
Yym1O6LJSpkENwJoA1AviVgGeNLytC4BajXk0GsFGikMHrQfcVqToB4JFzG/VYadEKYbqrz/D9TA
Y8IfKIGp9U8qoY2q3BGeIKiTy9HTDMIOc6hI91Ih31a0wA+ne+muRS0VpTaMWo2MEwJ0J2UXmQEw
BHBKrQ/SHA+iRrQx6ZKBKgH8IKLBlogoL5namhgKppzyBGKDnWapWyoQqfvIb2HM8nmHwIN5kxaN
ni5AQ1j8SsGslUgwvdq7D5Ta2t2u7VQB24pK71We+E5nffaCWM4Ck70F1ryOwT88dygFxLDR+Kyl
yeFQJLeKuVUQ7wUvG0rnfWmg4GnAT86GLY48cRTnKRaXs6xFlGLvgyP2zmZQaoG3bFSTp50oEnBn
W7K9+Na3WUXSg6pz399ry07eUMw8wVbyI0ujUy6rVdGCtF3tZnh9RDvaaVDIbehTN3nGu45WY+me
bJryXre7cEVRgtBK3ShnDmdQ1I/ZCntIYV1DsaPtJA8rDaye9tQssdYJXGCt5j2pv1R28fHWYmLB
Cs0uPaRjubmJ/1E7UKLzEjg7iNYSzmtapjjUqxX+kCT+LYXBPesVkeBMuc26MTdwUMEyiGPtDckW
PNChHAWvLZXdqIW2WHT514HXSR8Q2zEEj3pnkPqQeUEvBGyeJdaeacUBgJrNW3TaZ3d7udtglUAQ
6jbZroZOJ9mIfQ3HKjD7OdTo4Oqvr78bwlqQIgYc28rUbGxGcAjRMfCIQcQWXTmyL1U0mag3ecQu
UojFDc+zMRxBbAWVCvBHxwzYWj9VZT+Ye/VAj9pBnXb5iKGLZRjPhxYYkPn3soSaFtQDtxIUBlhh
fHddXrf1yf5EgSUYLtpCFiGiTVVWnus4rAvplCjiZt06hXIozDAj1eT+4lEkjS23EMbw5mDUjWr0
E6qhqk01kqVEcYKufnrFAqybXCrEkpm4teUyrUbAc2W0PUrYjQj6RbBmY224acAvx+uk3TsA3VQf
adMeXI8OTKKtlNEwYCp7aKTJzpvRnuRZCeyUcQ7tFnl2UcSKBC9t26MUKIgxhmVoCT4OcUGYyQ94
ALzjwdT0RAATmacSEVA4Hzn59t3tZcQoOcCfpIEzZglnTCIl8fIWPcQJ6bh3Qva86eLAMRI4RK1F
qzU5LeVRkAed1KCjhr7Ld4iwNp1ar8VTPY64HNpBz+FAC65t4d+9YMRcix7L0wAi9BleQxbCQPDc
gDDJ6MwhhhZ9WZyr3CJ1PGG62x8mACUtT6xf7O7SyX5/5EckomMgloUWj3i+5Ttt6TtKRz52kGac
i10Uqin7mUq7orQVBlVBmva8BOkDGxGb/t5yXkNvavWwdI7TJAtW4QsUyPtKYY/XsbAUY5EhLNLV
EsInbk2Psr1y6mFxC8U3/AEwAYtYifcJAs+i1a59PbSps6vRCLEyjm8bLU53qJo1OU1UGtzZw6CW
ic13dBqt8coCXAZfMZ3hflZ4HLQRpHmBXlQ4+MYs2FnimS1CE++36C1/ZPzYSpW9ixfp3luOd8i5
8nueykb3lrrd4U5SCut2ufNOXAFFmMU1vO/zmioFn+2Ly5JccMuMLiMPE7dVZH/m3esyeqqMQ9Mt
l3Sl8UsjGuF231FwkEEjnoaNjNjy36RY2WclR7HqHpm8J8TxL8WzB1a1CtibTo/8TaONrZELfITA
uyvXH3QQgxeKEWur2Xbr8dmjqaCW2xe51oUJhtrayVEFegu72rFHBjPbseXItut2vbyIJURNO40u
bxHu7DVH1EIc3szUXG+Y7bflgnOs1vfd4aYHnBgZHt6gHfd1yeuoHzKsLDPVd52NQn8h5qPeJStU
ep28pSp3BZ6BKNY07IPuCY7HOzeB7SeQAuCnnPH1GjKeu23pbrWwQMZn3fuXtbOSIUn9kmRoSRsO
zimeUgFvsjOidpvq0nPFQr/8pX5VHdzQvcbLW7o/FLmqMF8OoQ064RWp2defUIZlcIAQsBmQH0us
PXBal+Ib3EOI8h4h5t6XerVNAzW3NjbFtsDq6NkdtBNaHvqJqbbb7UuGyiUkvHbXLh855v+2iUUV
8HICRa1kbhCCBi8gIvYjfnqQ6oZ0I/FTS9si775M6l+Hk2Lt4cqee9sHBKoEn7tfp9sCyqiaqhk0
RQFFjgSRXeFxoIbjTGK4b/rPDggJLjXuuUbszdXFbRR+vhjOVo/BcPI4GYafB5+nUCFYdDw1tYAG
YNj50mdriAttW9PZmXuLEI9GlGgijQ+FryEb9p7F0NV6zVzGj/Re0XZUycH09yJzh8Re5831Va+1
gdCkZ0h8ZtO24O8NxwmUZ5t+x69hr5W4//TTtZu6L06qCny79P1JEIQrZGDA/lDl9+bgvSzChhVi
NLNdEHO9Oev+gjW+KzyaXk8R2zv7XpfEorPX/lm719YpKSoeZWab7JNvYDOXcZr4yTILF0mYrNI0
yBazWZAF2SoTEx7PFtyf82kcsE+QXVLvqgP+O/1LTu+V7ovNYCQIPQhJ5tG7qD/1F/BJzLLZSsSL
+SITwYLP54vVbLmKZ4m/mKerjC+X6SSdQrL3iRk4bql136jXX77r73iqPhDXo75q/bQPeuSB/xxP
+tU+FXfDSsvHYz1l35Wo1P/hbd+hNGGE7vcQ2wm9QS88+9pt1L0oIQP3d/nQlaGFR9LjGdtaHvrG
44FxKncPRW/HwQgflq83vHYv6CE0d5zY0IP6+9eLwceP/wR0ZGjt
===END CRASH DUMP===

**Comment by FuxonPlayz** [comment]
Are You Using PHP7 Build ?

**Comment by FuxonPlayz** [comment]
if u are using PHP7 Build Try To Use Other PHP7 Maype ur Build is corrupted

**Comment by FuxonPlayz** [comment]
lol i typed a lot of "build"

**Comment by AlexNe** [comment]
> Are You Using PHP7 Build ?
Yes))
```
# uname -a
FreeBSD php7 10.1-STABLE FreeBSD 10.1-STABLE #1 r281616: Tue Apr 21 01:26:29 EEST 2015     xfile@xfile.in.ua:/usr/obj/usr/src/sys/xfile2  i386

root@php7:/usr/ports/www/mod_php70 # pkg info |grep php
mod_php70-7.0.3_4              PHP Scripting Language
php70-7.0.3_4                  PHP Scripting Language
php70-bcmath-7.0.3_4           The bcmath shared extension for php
php70-bz2-7.0.3_4              The bz2 shared extension for php
php70-ctype-7.0.3_4            The ctype shared extension for php
php70-curl-7.0.3_4             The curl shared extension for php
php70-dom-7.0.3_4              The dom shared extension for php
php70-exif-7.0.3_4             The exif shared extension for php
php70-extensions-1.1           "meta-port" to install PHP extensions
php70-fileinfo-7.0.3_4         The fileinfo shared extension for php
php70-filter-7.0.3_4           The filter shared extension for php
php70-gd-7.0.3_4               The gd shared extension for php
php70-gettext-7.0.3_4          The gettext shared extension for php
php70-hash-7.0.3_4             The hash shared extension for php
php70-iconv-7.0.3_4            The iconv shared extension for php
php70-json-7.0.3_4             The json shared extension for php
php70-mbstring-7.0.3_4         The mbstring shared extension for php
php70-mcrypt-7.0.3_4           The mcrypt shared extension for php
php70-mysqli-7.0.3_4           The mysqli shared extension for php
php70-opcache-7.0.3_4          The opcache shared extension for php
php70-openssl-7.0.3_4          The openssl shared extension for php
php70-pdo-7.0.3_4              The pdo shared extension for php
php70-pdo_mysql-7.0.3_4        The pdo_mysql shared extension for php
php70-pdo_pgsql-7.0.3_4        The pdo_pgsql shared extension for php
php70-pdo_sqlite-7.0.3_4       The pdo_sqlite shared extension for php
php70-pgsql-7.0.3_4            The pgsql shared extension for php
php70-phar-7.0.3_4             The phar shared extension for php
php70-posix-7.0.3_4            The posix shared extension for php
php70-session-7.0.3_4          The session shared extension for php
php70-simplexml-7.0.3_4        The simplexml shared extension for php
php70-sockets-7.0.3_4          The sockets shared extension for php
php70-sqlite3-7.0.3_4          The sqlite3 shared extension for php
php70-tokenizer-7.0.3_4        The tokenizer shared extension for php
php70-xml-7.0.3_4              The xml shared extension for php
php70-xmlreader-7.0.3_4        The xmlreader shared extension for php
php70-xmlwriter-7.0.3_4        The xmlwriter shared extension for php
php70-xsl-7.0.3_4              The xsl shared extension for php
php70-zlib-7.0.3_4             The zlib shared extension for php

```

**Comment by PocketKiller** [comment]
English please, this issue is duplicated, close

**Comment by AlexNe** [comment]
ok
