### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fdfdffdf** [PocketMine/PocketMine-MP#3984]
I get this error when running the server:

Error: Threaded members previously set to Threaded objects are immutable, cannot overwrite targets
File: /src/pocketmine/network/CompressBatchedTask
Line: 36
Type: notice

Code:
[27] class CompressBatchedTask extends AsyncTask{
[28] 
[29] 	public $level = 7;
[30] 	public $data;
[31] 	public $final;
[32] 	public $targets = [];
[33] 
[34] 	public function __construct($data, array $targets, $level = 7){
[35] 		$this->data = $data;
[36] 		$this->targets = $targets;
[37] 		$this->level = $level;
[38] 	}
[39] 
[40] 	public function onRun(){
[41] 		try{
[42] 			$this->final = \zlib_encode($this->data, ZLIB_ENCODING_DEFLATE, $this->level);
[43] 			$this->data = \null;
[44] 		}catch(\Throwable $e){
[45] 
[46] 		}

Backtrace:
#0 /src/pocketmine/Player__64bit(1525): pocketmine\Server->batchPackets(array Array(), array Array(), boolean )
#1 /src/pocketmine/Server__64bit(2408): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server__64bit(2149): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server__64bit(2029): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server__64bit(1648): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Users/carlf_000/Desktop/PocketMine-MP/PocketMine-MP.phar/, string C:\Users\carlf_000\Desktop\PocketMine-MP\, string C:\Users\carlf_000\Desktop\PocketMine-MP\plugins\)
#6 (1): require(string phar://C:/Users/carlf_000/Desktop/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #0 [Protocol 45; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT MYLAPTOP 10.0 build 10586 (Windows 10) AMD64
PHP Version: 7.0.4RC1
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfYty4kiy6K9UePqc495jMOJl7D6euBjjbnbAsIC758GGQkgFaCwkjSRs0xtzv/1mZpWkkpCw
e2Yj7o0b0xGNpMysrFdWPurlf51E9pafXGnNVlu7qHcu2mcnjhFG/SDwgpOrf51Eex/QJ64X2SY/
OTvZ8jA01giabwJuWNxiW75d8iBkfsCfbG8XOnsW8ohFHktIvOWv3IxCZgSc2dvtLjKWDj9jpuEC
Y+Y98eA5sCPOIiNY8yiEfFY7x7mzHczI3xjB1fl57+r8IYR8zk0jcFZ6rVY7v+XhY+T55xPPfOTR
yHZ5ZTTJflUx9XkYmOc+gbcAPnd59OwFj+c9bwuFDsMbIzI33Job4SPQ+5i9yPobEkIiB0hOrhrQ
hFFgQGtd/XLyXY3leUwcY88DXW83l3Z0qrXqrfdXLMUvFjMeQINUvl8i84mBiPDUCAJjz7r4e/r+
jOU+l57ncMNl76EU32kHWQqOcZb1Zq2Ty1KUqfI9VMZ8vBeVPJVMiWf9NZ5a87KkGiA4WV6N13jV
6sd4TQLPhKb3ggzT5itMtXazU8I0BKmLMsxah52WyNRps90sYaTrpueGUbAzo1MVj9JiRDaIfA/G
Vjj0YEwEckycZTjtItsJF4uRYbtDb71WqICt7a7Zv2EsJLx6V4sFcVksEjaLheQDMqEmXSz+YDLf
2a1tF2ipYdvsVIPGC/hvOzvgp/++SpV2F47n9yf//P3shP9fV2l/RqdABURTnlytDCfkZyemZ3Gs
Tv0CmJooWKyABeMvEXetkHXDvWsi5F/Atd6BNPi8hOci8ndLxzbZO4c/cYdds4sPgGvUMjjLiAwC
axnwynYNh+D1DFxWG5j98k9CN0SOjaZKttq5ZmR7LlOHDmUVq7iY0ZlSuvdYhUaLGC2id9HGDivf
YyJApuVsZ/FpgWKWRHWRpYrzEJkRRYcofsfXS1GHZq2wDp473bmnVLimJtlGwZ6+6/I7yYjaDTJa
LL469lLnLnbnqVKXM/bzcHCj9+9749vB/Uf9tn837M770A5KSd9jCZuNPHPZFouFC1aUSJqS5HcT
ReN0sQA59p5RZNk7LorckpWL2+33k9//MmR/GbK/DNn/U4bs7GTNXR4YDqp+6KwQNA8MWK3atvgT
lGy5sx3r5KoG5iLwIs/0gLDZOjsxfBvI6tVatQZUazuCr9ob/0GCwHgENYVpqh3isHMNjBtOvtiu
5T2H7H7ORj8Nu5P5eMI0yIRRQeC11YG2iqm02nvWHd22m8ABHe2rkwsoUXPa0wDwFewUQBqyjIDX
vRCzGNzfzwFAH89gARNbCIBfoEV8I4DCRNAY4jskMa5CA/g8iGyO6b6bJF9gJt2VvWZojxfBwv1u
BMr7ji9Zvc7qtav6BTQYe5j34ENrI8HWi6xr7AMzMFbRFZv0mRgpiBSZVXwviK61S61RR+DzBkx/
xbHD6NpbrRCCbgEYCl7xhYYyzI0NGnzL3Si89lzi5BvPbgW7jZNBuZa5Gy8yUXhdrxEvx/GeKyvH
Xm8S/iKx4dpb8A4yDLfeMgasoZm2YGeuic3KC6A8CUwyAiG0TC9Ivv0nX6a27NXKNndOtL/WiBsJ
YuQFFfCNIpD/8BrBZJgqKB7XoH0dK4WFnFsKCfph12DWug/DOUK5i/ao8tuOB3uZpQQFoI7i8uB7
1QftA8yt67/RP2iSXeRVQuOJy4QoP8koqu63jjBu5AzhkAlx+PSgmlkRXJpbI9pkYabhgGAaQQ4q
vUgFBFY3BwEJA6nMwjZGuKEBizJuQ2WesvhfQzmgm0SxNYO9H2VJZpNhFuCb+YpM+coRUpSFh2Bw
DoGRgRW0stDtPvzNoREp31gLkFq9AoqGVXBwtGrN2gW8vhtYV2zVuuTLi/bFimsXRrt9cdnqXC5b
Zu2ibV2ujE7HalhNbpg19g54R94jd+2v+bb5avtUda1Bdf8qVI5CAIAX6ku12b0tarZaraFp4M+e
nUxux1mKyYZ6D5VfHZvP3voO/3GUa8QDxs+W9XJAQt5/cAAmXz8vIrsgx9GPKHoIScuBygbQ3qBs
STFPexfYGyS3Ya6LfnMggwYp4AvsAVKCG9+GUUxTJPR2+n7hTj5N2GdhF9j19yzmsXAX7mwfRnyL
0D+otRfuDeFvQdKRDSpNrU16kmmdK61+VbtYuOglgGoNkGI0+9zTmuz0sx3uwN/t/fd/k+BAObuB
iUrSjHYB8XpB9kIzIwSYbEEqEWOGZmD7ETt3Pcdbe8yMiaq/howtTioVqSZC1/DDjRdVqBaLExVn
8eVuXfHBCZXwZzvaVHzLq3imfW2CKwBtWAmtx8XCA58XLMMCS7QAIwOjIzIdGzS1rtV1bbEAqrMQ
ZIpbKi/g06lodfPPMpMFFv5SxdtFFcsOrqvVc4CcZ2lMb1uxvAgiyOvD8gjNcQ05grOpIJCjATZk
D8Mv0xZrb3ECQkL2jHUnA2z7uBuGoEbZwAUZX0FAsHA/20GEHXoL3o8JJmDPZjsfbSAmEqWz0u40
KD7C6Tx2Ci1TtV37PZuApqUsoLnAxN+Ov8wWLrmUFitIKCnf7rAtbZf6gX4wS6gbROcMQyQGTcrA
/jHDsmzMA6qCJOQThJjXqeu5HMW0kAA8jpBbKh0OO9lmKOBaTasLYD82OVnUz2BTsrhGKVIMOiCB
DBKqs/nsDMdWPheV+JD2FodBSuN6C1fMaLCZseLRPtN9VIyZvcbKfwIpcNDHBQLLDlWKEfgPIAAj
EKq1GPVZDiNwGezlHlSGIiMpj8HkqV0oPbdzDD6LEy3cKV+De8VB6Bk2wCyCWmyp66C7z6ifztja
8ZZnTITTmyhCOP6AnTkDNSImS6poZs7Id89wFRzZjKSKQVnAn4JyUBaRCQx2ll+U4I6MPpGhdQef
s0pmvvq3MybGJL1ZPHkX0UMVHD+tkXxFHtSbB8o3OH3KNz58PTLW4VmSz9/oNdxtuQW15uZm5z5C
baF+1b9hm81R9MHBXIO/zLbGI0jyLuTMW8Gg4Ex0N+la7Oih4a530KOs74Krza9isaQv9kRu+hmM
VH8foCPKTs33TLu87FTIHBDtHIpAShu8bsx/gRM9/5Z/gltGTSBA+G/4dtMboX4JC+QKJIu0lv1E
WmXogYfHPhvOjj5HBnan+I4ZVkN0AhFbox/kEbuFVA75XpId+pn4PGKa314icv51cC30FQQ0xGgs
f1Wk7ZrOzqL049VKPoAgWOshx4AJlDYoNH9Hhf1P+smjwVLk8eBm6wbIpWvpK6mVXY89xUWN3yUl
Dj8IR/Rf7ShXTsTC6HsDo2UALohp+OUUFl8ZoGJ0c4NamXLaRatKB18e5neVTkqytSFOBMedxjAE
A+ebaOtkPjDMISWj05SqMAYl+UrCeALwOCmGcDrNQRPdbH47fpinbykNzeLsfIU2bTfLM/XA86Ij
OXkQC6x0qM6rNMcZCfnVLScvQhLhe2Gko2bV0XxIy5CWlEofi4qcHinPi4hBT7xGEovM2xgCMQxG
SVgTNhYiFEC/2JHuuTqufXpCwjM1fIHKQQ03fq5OsZHV0X3AMS5aGR4QTYMU6zvfAQcm12kbUI8U
q1fB5GDAj4j/WXnwEkZ7h18vTkxQksEV++7uroM+zcn38u1/zpHs+29OoGYqZb+cB07x3NwgD/H2
aqYlCdRM43FVzkCUWry9KceCBGqOj3yPMwLHeFxcxDzw7Q2ZFiZQM03lsJjF7W1cbvH2ap4lCSBP
aFBVJSjiCg4aGBiUdg5xmfVGqtDbBSYvoQKvAAbvUpqyDAHEzrYJw2fl7MJNVtClzdF96dlXP/Su
YhecG0EBCNOAiRHLH0dHtI2xB9i3N5CCHilUnilc3xovuiOMp1arN+MnTrbZThWCAv1F31Ckn2VB
aJo3Qw0bGHo69VheHkp0VLlhcfgLN3doRkgrqb4GYvPapV4TvwIrGtHlISo7Xa5hfc/aTfGrEsXM
K5r4VXFPhqiGBoIXPwFP7r3u2FthxUVKrd4ZLVz0QPSlAbGQUIjF1RN+hL7crVY8UNVxLcG93quS
cINxCD+SGdklrFNofyVUZyR+AQU+lh17X5rodWgcsF8OiqxuGuaGJ+m09g/ycUASRY5og5p8IIWI
A3RwoUz8ecpKjrBFOjSmw43HsBCJE+A6TVTkRx2uM0Dv6qDgRN0/TsQvzj+7FkqYvgq8bXmzJGTx
4CwjC2zDgRbQs411IX6BYIMlpX6H2CNfztloTgVz0IPdQE9kPiD1NvL12EOut8QvgH9zqiHEnzpO
ROd5hvtQj/jW14/KGC5UPhYO+51SKSiIs0RC9NnKmYmBpscDL5aI+kj8JgTRa6UiPfo6he3a1Yxk
NcQAbOD4SyiwKDitTnoUoTQhoX4sXBjCNrpnoSoqvVn8XLjPYk6vCv34rJvQlc9G4Mbem9LqONXp
m6JBdXeH2yHUYauiD0wNynEVnecgcYuFzpAoi+O8n75zbTPu76S3iEC6mGuzALdNZhOKchVThW9Q
JxDAYSCQvLCMF68EbziLS8+H6bAwviPEAFdTtmK6ikK7ZrsKzdRdU7aNhXsHVncXYBhMGzE2t/fU
KT8hpAeBC4SypDHuvXiSRn58nM0q93ztRbacdEXg4PY+SU3zJ/HHY7BsxkRD3OYQB1eEdezl1+Tj
fj4cZT6+3MQpZ5P7/sdxgpzNhsq7mOSij/lwVplNJ3GyT/P5pK6UW86H4ddELkaGYhoHF4LFDM1K
TsqEZ2zt+Ruc4BATNfgLQHtr+OIXPhwLP3zPb4hfAAVRCKAQ52NC4oUqRvwCNuKOyyGvCFBQPqmQ
Xjptvd2s+GYFRkOjLiqoBOZj0G4AOtdwwQAk6+ehvVTxWrVe7VBrzmafVARAwnBTh4TU+xBpQZ/F
z3MyvYUzBCdjJ/TgweZA8tVzOc6wG2hXVe44r1KFMXRIBMjYP0LpEf5+FJNRGNz7tlkGLHAcOegO
yHUkJxMaWvWi3b5QXvPEnrtOqVvVeqPRUF4ldbhzAxtiLBi0trBHl7Vqq9OQxMlHSg6R/VupczXP
D3zL21JjjEfnP46G2SlHCUPJzbS8WFyiPgfVl8FVL6sNlH1IVjSL+SPNcxdjPOq1QuQMrMHWKERN
uWO83H8sxFEcCjzxbUCzO9ChtiUUE07ki9lJqRoVlk+JrafVPM1qG1rbvGg1GxdNswPhj9VZ8Wan
Za3MtlFf8ou60dGaLfbu2+RKlE6NSaFn0fIHxnP2K08LAYexDo8pdFxZjZ+F4+wTILDmYgqTeG2t
Ovxvwv8WCzeGhj91CAjw0Wrjo9Ghr5ZWZ2Ba+NYCzzd+a9fkG9KKtwb4hM8bO3B8z3NgDK55AAnO
GvK1XUteL+vJKxA0U4JmSgBZu3wV7OQDs1mjEsOfCs0fe8xAf7hRZ2Zgxr9LtnKfNPjChyGfEA3Q
Jzx/9QwjYhsDmk4UTrxS4cQrFY5eoTWS11Y7IaAiJ8maabJmmqyZJmumyVppslaarJUma6XJWgw7
dPSpC3pW6dF+3KMCkxutfXARMMSNBwiyoBn45KVQOgSG1oZxkiax5QtcdRbpT2IqgARGsGdPqlHA
WOJbxoJYFXhzACyp3xwGiwRvjq8WLu48iJ+FLUSITJWbwswJrSjfUH8qqQ1qjAQjF4etAhUqKeQS
YEb9XtZSfJiu9ChqT6yspG+FFRAoXSiWQopMqVpo5bu+DR6MtAJ1rY5BkBQsKKVpo88iFnugcyuo
HGiEBvavYIy4Q5Do2VvZoJSIBAex4z3alxcK0WWdoeILfGcXsmfjkbOl4z1jIlzkhZiNWaCwEnrS
TUCNk4kvETcSaqiJvQa7EZh1hgtEUCmOe5TNlbcLmFpyDLVEuZcmM1dLZkYB4+aSufjhevCD/0Vr
s2+TbLnMZThrLwCDvQ2Px0CSnEp0nBJoxV4U5bWs//7Nu1bEvoZA7J9B/mHclBACeAFn0ktWwGLr
NSoigcKN4Qo6XlsX8yIsjjKbtcs2WmTjAIOz1x2JUqauG1qr0aapmp7n0K4fGOe07B9GthmmYUaK
FXM6RUS45hrriXMjWZCX++2Udj2jiQqdNgifGbtoowsanfC6a6Ck6PFGrQIK0+FGkBDAQAMtnixj
U05M7eVsWQGFMWCoh3I+vRYDQEY55GxJoC+2Hat0MShPKUMUHffu4+QfBN2lKNn0B7nq3qMu+Bej
ubc6iscFLDnz+DrdyuaOpW95ZLxOG0C4f4wIV1YMmh8OfWh+fpTY3BjuWs4SZ+jU1tbNdAtPQatD
S5VhoJHKUEr7HCVJm+YoGbRKGT7fIGV0SltIEkiB/iryx72MtlCzgHA9Vz+CBHmz+AtyittsSUKY
A4a4xJtNK/QETurzKIbtCqF+qJeAi+lplh9ALs5uOEUYP8wxkg0HaThuWxfz2ukoUwg8l+bRM3hc
7dVXnM6v0JSmLjbYyhK8RuWHKkVSIyKR264OGRWSZTll8sowSlK/kTxt59cSKH31BtJv4mvugtAL
VEID0ppR0tOFqGyThI+27xcmiDEJven5e1xvpV2SOm7TtQoxPg9wGk3BkgaRzaBHnqeHkJeToF0X
JxLDnYkHKXLQlWE7cm9hCrVpCCqjCcaxwMTyWcxUeLF6yiWH8NHvABeI1F6ehr/INTPT8RJFkiyk
qUDLDuP8M7RgM20L4jwdzEfcKCpBksMq4FzqmHw+h6gkVRhtSwp3gAHPQefYB54JJdklRlWFG9s8
wixJYJYlwAWXwhQx4jAJ1c8shB4Ql1SgrPwlxS8rfVnhS8teWPTiknNwyF1r5x+Ql8EhQRl9Hkxu
jo5bYRK9gQfIyrFL+0hScDT39jHetJRUjoa0YmW2FH2sYOujeIubdqq0CghWjmccS+/tlg4/gpdz
9cXYvVwML2u37Sucj1MgFpzlrX+k5ZNtCyXN53jLcix3d9sjvPmRdltzD3yyYF9O4UUbnm2cpe0a
wb5cInP4vEzm0EVSmSM5lMscwaFkHhIcL+L6FYoi+cyRHEponsehjOYp8lKawx/I6UFbbl/l/xpN
sbTme+RQXnMUNDV1rMnzEp3DH8h0vgT8aFsXynWORpVs27WT+CjxgDO6OEOBrkwODygIAmz1k5JY
ywwBT8qE3yIqwmNpCtAMcENQNqEVeH4WEqAlFRt+JCTc7CLLe3ZVUCZGl0BfHHPV8YCKmm3G7VIJ
H23Fw9umGyJislQU8FMRMEGNR+VwCOLys5rfQZyGUOgj3BZk7RIBJJ5i62MWGDtmaegv2kXu+wgd
44ln2gI8Jxnq5MGyx/Ng3KNB62e6OMCdxapeWAKEPuHRIR/coRHPX6sYksVMa4GD4ZZMG4C3IjZ4
Zjz8UqrE20cnWm547k377HTCA4elR4fZlK93DmiW/ks8nRa+L1zMouRDOdWuzOx1qo0OzeRVNK1S
b0jCvw/mJUtib5+4xIJXcYOI2E6S7HnSxLZD5VXSyp3N8fYGgkFmOyprPn36Ro1zO5aPwplohFuB
/SRnl2kubLIR+83xeUXHHugU1VPxsjJSsf6Pc3XKns7ASRROuGUXMHB1efb5ngX55cAatxpNa7ky
rVrrom1YZq1+2WlYvH1Z5w3DanYuGlqrZTZwmhR5V2hPGJ2pwMlnLGJ2wn7+BpqfB5NXadZfbT85
ySFLnCCXgKznsfEZEnZKp7FA1fjcdM6XX+vvF65c+Veb85Aet4rjBqgwdN6LcwjUnKKokAlubDyH
ztFl55wxL0CLD2Jn4pSHH7Hlnt2Cutiz2cZY2Y9VyQIvPdozHFL2V+AFVB9Bv+BM7Q038FQWTqeN
oCF2IbvxeLDmASb15D4bPMcBXHJLWNkTGriUXYGfS9xrwH7ACYGvDq9+0yCBosrtSrEpKdmKh4S4
O9xznX12K49E0el5nRZsM2ggkEcl8V0Z+nRsUhz/iQ+4Zr/KVgNIjFs1q7Y0arV6o1m3mhpfGRet
xmX9ot7WeIvXLlf1yxY3V5diVVuelaWTk1J+ipfjkxNAOLPB5A5FklNxWoxsTpYw3pEWZMjxyHuC
wi+CCD+C4XHUb1yHkTWo0nELOldwsLlOUoju5C++LayV1qnJR56GdFq8AZNAyqtC7HmPNthQb2uI
afSy/YYZctz0kwhLUTEFmWOveH6XbI4k3uZ4Tj8H6BB1NC/LBgZFgBNTx0+m5Kkd7q5FpvkyrU3d
skGliim37PZahWZrvKg105rNWvzM0IGjtDSWtmOL83qx8YkpcDhhGBTirBSdijFM2WO047KVI00u
sCkouWN83YvJuewAjfHxfkRQd7P+bDa4zXykdOA+guBjabj5+HqT4kBSt/omxzLpJUf32o5WSZps
AlX4yiMeuB89IZR7O+mYHB4PxHUqd+cX1z9PLLXC24jBo/6N+u4/xG855dZ29YQ61915WqVLdOqG
8b3+MBmOu7f6ZDr+OAXQK+hy3mBIV/YLbdTJYvQimMInxPktHHlhSdMAAQ7816kwFgQvvHCnsEIW
4XlNPbSt7Km95Ox/+oH7ucJCvZ5zgtpaq87N2qresZrLVm2prXirXge3Z2nWlvXOqmN16jWwJ2g9
5Pat4vOA8oQ/FUG8ljius8lQPgo5JeexQ3FUG6JDcQnZGIKLYBCJ2znOwOEmh/SJp6AZ549Iq0B8
Z7wUqyj0MdvRAfSF20vPwXXpOFeahq5tyn2O5T0/N4Z1JxVLD7ym/gs6PvBBmBGPNp6Vg/fwThR3
nfLryd3aYs9aCk8OnSsgsjMKs/7WjxQ8HiEP6fqDDCzD9qPjLdOvgbvCgJqrkCfcS9cN1jv0rpTM
YpqUdki2QCEZotlU8N7aNhU0nZH21f6496YcN2unEOjV8eoGetkKlZQEnWJsqwKhF1eO96yAJhCH
ukoJ8kkSIcl1agI/6B4FU9xPCUFBhyW40kSHjZqgwJPiLwXwecC5Cs5SwfAAy6pUGaT8FifJ9kPb
feTWELwzAqKw4Ibu5COWafp84RY1EX1+4rgjGV5Gtpu+Gy/Ju0g6gxIYa06QSWDjrpj9P3Z8JyDp
2yyCZqS3Od/6atYPrnXQpQ+4gkNLc+TvJRjSMeLCEFIf/xjia6EKiXGgTnfg6yjhoLxnJCZJ4nBy
wjtVjeLIb3JGRYmqB6coy7b6xNfSUDZ7MGu2mZRiVqYOMcqaybMuCRXe9BBfZvJHpwbEeYaqkVDH
dlgilpihYmskOD5xcuSktCDkce8lvFMmECbxSOdPRlEOygGOpEjo78tTFniBpA4NgvczqanjbbXC
GKlHYds18btwjx8pwmPmARc331QjuTnXuIa4bXUGyka+rfCA3HUYmGe005HecJH3emU8cnSd938w
mTwZA8PKjY6JUXLXEN2AEH+UWFwMsvD55fb2x0ISgYjDwTSMy7KRuyF/zO4Jj7dCIvgeqhf6ufst
lL2SwKFesEdSnLyh/S8yg2myGSabv+gXSfQliGM2hQivHsInjKmfuiW710dCL3zOziDhTUVpus+q
0tCq37gLFktRtTieBIojXUVKVax01otQ2VUElUDufzUN13NtMzuAVALcZiPkiE6w1LPYZ9sSMYYI
izvkS361fXz8bPuZJkuvYslPP3QapgaeY6fRvtRqjQvtwuo0LrVWx6pdNi80o7lcXtTa/II21SPX
7ORcA/faQpt/zWNqVbpCAq/5oPLgaZXCIwViK+eXAE/lB+J+EuUKlKvz84RGGGUkoctDbHeFO6rl
VSKgORw611K0l1eejREWtQDxLaJBucUdmJ3Fyxz8KiZLz8GmZ11V0ldPkmYu/xEDgXx2OSZwBONn
332yA89Fl5Amq+QJPOQl69EdDh9m/ekM4qu7wbAfX2U0ERex4Cke3P04ue3Ou+XXHIHvTZSLqQeW
0F2j/k+OFd/S0V+a77umaw1pc6nnyizu4vBZyVa4xHSn51besRQWJTt96bTfF6ZlhDrK4Uu72ai/
LePxaPIw70/vuyNqoPhaMmI4Ay8nf1XUQrjzjTq00tYC8wmVvpvM9JspYPtTHRpUlw2uz+bTwf1H
5CB8BB7h4oPjBagg1UTYTQWp5JEqpNXvx/qn8Wyu9z71e3RA+H68cD+NR/3b6eBz3LcEmHTnn+gA
wWFvusNxrzt8e5/TMMFUH8f3UMTP/algvFiMbDPwQm8VdU1aHly49w+jG6jF+A4r0oNwfjylgB/0
8thFbwBv+LLNOMZGCItBQDJT7ofT7+cLV72nSxXZxVhebfZ34wm+foVfnIn5UNhJKjRLMUu68cuS
b0txokATvAJptuGOs1g8geZbLD6UimXs8A3RpC5mdD9aOXV3PsheV4SQarfXR0ENeGVG16i9ntsP
NgT2C/CPU9BE7GozXDD2c89zHu2oqNxKXzLwueMrRheaBtXEdEBxY7vusTorHG5/APr53ufiRifg
U9xcpdnW357tP3a2+YjHEuF1LjrtGPnsEU/eLiYbD68KLqeb7CMgAXqqQfgW0g9vGkgxjzBNODR2
rrnBioPEw8DFdTM8Wg166UO1/2P/Q/WmO/9Q7Y1uP1Q/38zwB2B/n+F/ePkyu8OfTx+qo1kPFyRv
pt17MRlqPNkOBWWTT5NpT5wowpNEOAF3M7jvTn9CWPa2OtJmE7CyKDiIvrm/AcC490N/Phrc9/XY
jhzeIAxk8bDXu9Pep8G835s/TIlaXuKYEgxu+/fzwd1A6BNCszswL84eL8MFQwcGtMZmEfdp1V07
Y91dtAFLZ5tArHIa9j/36ZBDva6Cp/3PA5xiJI+rVtMWrqJCCg3h6ybr28zTG0wRlnc0of5+N3n3
Eb5nwsYXXVGo2J1SpRQ7CyhLDzfDQS+n4id0czx4W2L+NbZ5Pc8NPTTeYgjdBtJJQoMiQFN5ZVPm
zsR5fzTJZdDrTod3+v/WDiUf5xUgyTenQMt4Ox51B/dZ65zC9em4C7L5UfFysmRxNRUziOCcV3Ro
Kz/fjH/UR7OBPrifzcGX0mPDWqDLYpsk76e88V6wEz7PQInCSL6fj8fD2VFnJlWG8srSWbSzbI9p
1LHCZ7lIFCOxrv9Z1vVi1jj7J2ZIMt0t75GLL3oo8Tnf6cJP+OW/ct7nf/2zcNgp9MIrSene4oum
ycErxZu8RPJDvzQlPHQ1D4pW7CoeY0FNXcKn2F8t4Ubq4tsLpHixInE6BDIZoUebcj/m06bJjnu3
gluBf1vMoMDTjbtM+rpquqzXKwjR701pEg84qVUOiYNW4IrGeEqresZvkkHpG6scEi85zrDIT04T
FHnMImVTJct6z4LgwH9WyCUP1ZdOsWhaiofiX371X371/59+tSL9wsMWA+AP+tgKN+FtC26pv60Q
oOctdQH53hmU9MIFvsAPV4ilRy5IySdXkFnvXJamwD9XkhR66iKl9NWLiFOvXSH9Jr+9iCt58IIh
+vBFJLE3L6iEP6/QpUrsVSfjLWa/hPwNJv4w5VFznq0rRAKCUMQCCk6JCo7a7rfEBQpbihAOTF0c
I6SESrQgqeN4QaFJI4ciQ5xGEYcVUMgwojgo0GsRgpL8T6VOI4pyD6o06jieJG26QtdDiUaOeB5K
gsLIpNRpLI5NFG6ZKOUVJ/Zb45RMNvU/n039tWxE9HJUzMQWpOHdW1TlrDcdTOZ62oNvIseufGsS
7Dt9DoZkhn9n7fYtSW7HvYcR6GIQwrFUGip62v/HQx+c5vlgBDZhOO5KmviPrbbr1YuGppUlyRNn
oqxg/SSVP+5FWLinC5fBv19qpcWmvcoZDjIC0eKYcggurBvy3D3x8IpHERlKwTM4ex/Y3tvh3zlk
4PjZuB1riWcZ7Ah3J597Ae4lsFdQJIDscNcCXS4PYck2jG+aVzJjBuSEqg4Pk+OO5xj/MfB2Pv7d
JIvJe2XxhdBJrrgYJGEYXV4xBpq0D77/wWX39Ccf4rImjDaeDyXbGBGW/hmPnSw57tZd7ZwzPFUf
sS+D+Se8p7t7/xP70p2CdMx/+sDkn9Fg/IkLRnReFvg+45+zc6M9VHThjvpg1CFB92YwHMx/YtA0
d4P5Pe6/uxtPWZdNutP5oPcw7E7Z5GE6Gc/6Vbq3a0UtbNkW3Rgij1owg+FhabUJHdGEuL8cr0wC
EheanW4Kpf3gxhILmVKCK3DGfIfjlXGm50aGGcU8/hd6OxA3QgFOfv8/EqgR0A==
===END CRASH DUMP===

**Comment by PEMapModder** [comment]
Please use the latest development build.
