### ISSUE TITLE
Stuck at CommandReader thread on Windows

### ISSUE THREAD

**Issue by PEMapModder** [PocketMine/PocketMine-MP#3990]
On Windows, running the server with PHP directly (without using MinTTY), when running `stop` on console, the server finalizes normally until it is stuck at `Stopping other threads`. If debug is enabled, it seems that it is stuck at the `CommandReader` thread. Clicking the return button on the keyboard can make the server continue finalizing.

Also reproduced by PhpStorm running PocketMine.php

Have not tried to reproduce this on other operating systems.

**Comment by PEMapModder** [comment]
I have also found out that it doesn't have a problem if I do `echo stop | php PocketMine-MP.phar`. It stops gracefully without getting stuck.

**Comment by CyberPowerCrazii** [comment]
Wow, thanks for this, now i can gracefully clam when saving
btw, how to stop it gracefully?

**Comment by PocketKiller** [comment]
I am having this, but I can make it success by pressing Enter, then it'll continue stopping other threads... strange

**Comment by PEMapModder** [comment]
Appears to be an issue with fgets

**Comment by legoboy0215** [comment]
Yes, but mine stops after about a minute.

**Comment by dterweij** [comment]
On linux it is waiting forever :(
```
CentOS 6.7 64Bit
# php -v
PHP 7.0.5RC1 (cli) (built: Mar 16 2016 10:45:22) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by PEMapModder** [comment]
I suspect that when joining the CommandReader thread, it waits for the next fgets() to complete before checking whether the thread should be stopped.

I was just wondering, why can't you directly kill the thread, terminate it or whatever? The commands entered at server stop won't be executed anyway.

**Comment by dktapps** [comment]
This has been "fixed" (see the referenced issue for PR information) in PMMP's PocketMine-MP.
