### ISSUE TITLE
Could not tick level

### ISSUE THREAD

**Issue by GlitchPlayer** [PocketMine/PocketMine-MP#3991]
[Server thread/CRITICAL]: Could not tick level "Spawn": mt_rand() expects parameter 1 to be integer, float given
[Server thread/CRITICAL]: TypeError: "mt_rand() expects parameter 1 to be integer, float given" (EXCEPTION) in "/src/pocketmine/level/Level__32bit" at line 872

**Comment by CyberPowerCrazii** [comment]
Reply soon

**Comment by robske110** [comment]
Php7. Mess

**Comment by CyberPowerCrazii** [comment]
What???
What do you mean?

**Comment by PEMapModder** [comment]
Please don't use this as a forum. If you do not have anything that contributes to the issue, please do not post comments like "Reply soon", "Mess", etc.

**Comment by PEMapModder** [comment]
Please provide steps to reproduce this issue.

**Comment by GlitchPlayer** [comment]
Start server, Join the server, loading building terrain on client, message shows up on console, infinite loop of messsages until client exits mcpe

**Comment by robske110** [comment]
Maybe level corruption? Try to install an completly vanilla server (no plugins, no worlds) and test it there!

**Comment by GlitchPlayer** [comment]
I tried the vanilla server before I posted so I can find where the issue was.
