### ISSUE TITLE
ChunkRadiusUpdate stuff?

### ISSUE THREAD

**Issue by legoboy0215** [PocketMine/PocketMine-MP#3994]
Hello. I just saw this commit: https://github.com/ClearSkyTeam/ClearSky/commit/df6227a6f11fdf237cdab202bc7713e82f21ddae
Seems like this is quite important.

**Comment by jazzwhistle** [comment]
I've been testing that, and it doesn't fix the problem

**Comment by PEMapModder** [comment]
This issue is invalid until you add proper elaboration instead of "this seems quite imporatnt".
