### ISSUE TITLE
Cannot use pocketmine\nbt\tag\Float as Float

### ISSUE THREAD

**Issue by MMCraftin** [PocketMine/PocketMine-MP#4000]
When I Try To Start The Sever I Get This Error

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/Joey/Dropbox/Server/Other_Servers/PE/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by PEMapModder** [comment]
You are using an outdated version with PHP 7.
