### ISSUE TITLE
mac 1.4.1 start up on server not working

### ISSUE THREAD

**Issue by tennisshoewar** [PocketMine/PocketMine-MP#4001]
![screen shot 2016-02-26 at 8 30 55 pm](https://cloud.githubusercontent.com/assets/17507201/13370251/013bfdde-dcc8-11e5-9b51-0c264e3e396a.png)
It just keeps saying "Couldn't find a working PHP 7 binary, please use the installer." don't know what to do please help

**Comment by PEMapModder** [comment]
Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. For questions, please visit the IRC channel as stated in the contribution guidelines.
