### ISSUE TITLE
Fatal: Can't use method return value in write context

### ISSUE THREAD

**Issue by jazzwhistle** [PocketMine/PocketMine-MP#4006]
Hi, I'm getting this on startup with the latest build
```
28.02 11:49:57 [Multicraft] Server shut down
28.02 11:49:57 [Server] INFO Fatal error: Can't use method return value in write context in phar:///jar/pocketmineOFFICIAL14PHP7.phar/src/pocketmine/utils/Config.php on line 332
28.02 11:49:57 [Server] Server thread/INFO Loading pocketmine.yml...
28.02 11:49:57 [Multicraft] Loaded config for "OFFICIALPHP7_1.6_0.14"
28.02 11:49:57 [Multicraft] Starting server!
```
Thanks

**Comment by jazzwhistle** [comment]
If this is closed because I was running it in Multicraft... the same error happens on a clean PM install

[myuser@myserver PM]# ./start.sh
[16:32:01] [Server thread/INFO]: Loading pocketmine.yml...

Fatal error: Can't use method return value in write context in phar:///home/minecraft/PM/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 332

**Comment by Intyre** [comment]
> It is the issue submitter's responsibility to provide us an issue that is **trackable**, **debuggable**, **reproducible**, reported professionally and is an actual bug.

>  If you do not provide us with a summary or instructions on how to reproduce the issue, it is a support request until the actual bug has been found and therefore the issue is closed.

https://github.com/PocketMine/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue

**Comment by jazzwhistle** [comment]
Ok... To reproduce download the latest .phar from http://pmt.mcpe.me/pmb/... install, run, crash.

**Comment by Intyre** [comment]
Thats why you shouldn't get a .phar from a unofficial source. Blame @PEMapModder 
https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar/view#files

**Comment by jazzwhistle** [comment]
Fair enough, I'll try source now. Thanks

**Comment by Intyre** [comment]
Hehe, blame @PEMapModder :-1:

**Comment by legoboy0215** [comment]
LOL What a mistake...
