### ISSUE TITLE
Innstalation fail on ubuntu 15.10

### ISSUE THREAD

**Issue by Ubuntu1510** [PocketMine/PocketMine-MP#4010]
### Issue description
i tryed to install pocketmine-mp on ubuntu 15.20 an if i try to open its only saying :"Couldn't find a working PHP 7 binary, please use the installer."

* PocketMine-MP:PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
* PHP: 7
* OS: ubuntu 15.10

Here the history:
enderdragon@enderdragon:~$ cd /home/enderdragon/Schreibtisch
enderdragon@enderdragon:~/Schreibtisch$ wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Di 17. Mär 18:00:47 CET 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Unterschrift vom Di 17 Mär 2015 18:16:17 CET mittels RSA-Schlüssel ID A7837F89
gpg: Korrekte Unterschrift von »Shoghi Cervantes <shoghicp@gmail.com>«
gpg:                 alias "keybase.io/shoghicp <shoghicp@keybase.io>"
[+] Signature valid and checked!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 32-bit PHP build available, downloading PHP_5.6.10_x86_Linux.tar.gz... checking... regenerating php.ini... done
[*] Everything done! Run ./start.sh to start PocketMine-MP
enderdragon@enderdragon:~/Schreibtisch$ ./start.sh
Couldn't find a working PHP 7 binary, please use the installer.
enderdragon@enderdragon:~/Schreibtisch$ please help....

sorry for my bad english -~-

**Comment by PEMapModder** [comment]
Incorrect installation. Please visit forums or IRC channel for support.
