### ISSUE TITLE
Incorrect type for Level::blockHash()

### ISSUE THREAD

**Issue by Samueljh1** [PocketMine/PocketMine-MP#4012]
### Issue description

Type hinting error [php7]

### Steps to reproduce the issue

float being passed to pocketmine\level\Level::blockHash(), int required.

### OS and versions
* PocketMine-MP:
* PHP: 7
* OS: Centos 6 64bit

### Crashdump, backtrace or other files
```
"Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'DHSkywars v3': Argument 1 passed to pocketmine\level\Level::blockHash() must be of the type integer, float given, called in phar:///home/server/server/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 1383 on Samueljh1\DarkHammer\DHSkywars\Events\EventListener
[23:57:21] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\level\Level::blockHash() must be of the type integer, float given, called in phar:///home/server/server/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 1383" (EXCEPTION) in "/src/pocketmine/level/Level" at line 271

**Comment by CyberPowerCrazii** [comment]
looks like your using plugin DHSkywars v3. try removing it first

**Comment by Samueljh1** [comment]
Nothing to do with that, it's just an onInteractEvent that runs code based on the item ID.

**Comment by PEMapModder** [comment]
Please show the stack trace.

**Comment by Samueljh1** [comment]
There is a stack trace

**Comment by PEMapModder** [comment]
I can't find any backtrace in your issue description. If you can't find one, enable debug in pocketmine.yml

**Comment by Samueljh1** [comment]
I didn't do anything. It was something internal.

And, here is what debug printed:

"Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'DHSkywars v3': Argument 1 passed to pocketmine\level\Level::blockHash() must be of the type integer, float given, called in phar:///home/server/server/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 1383 on Samueljh1\DarkHammer\DHSkywars\Events\EventListener
[23:57:21] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\level\Level::blockHash() must be of the type integer, float given, called in phar:///home/server/server/PocketMine-MP.phar/src/pocketmine/level/Level.php on line 1383" (EXCEPTION) in "/src/pocketmine/level/Level" at line 271

**Comment by robske110** [comment]
It would be nice to get an stack trace
Enable xdebug (should already be enabled) , and set debug level to 2 (in pocketmine.yml)

**Comment by Samueljh1** [comment]
Debug is on 2, lol

**Comment by PEMapModder** [comment]
@Samueljh1 you still fail to provide a full stack trace. From the error message, you apparently did something in the PlayerInteractEvent handler that indirectly led to this error.

And error message ≠ backtrace
