### ISSUE TITLE
After running `installer.sh` the script `start.sh` is empty.

### ISSUE THREAD

**Issue by CodeBrauer** [PocketMine/PocketMine-MP#4013]
### Issue description
After running `installer.sh` the script `start.sh` is empty.

### Steps to reproduce the issue
```
$ wget https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/installer.sh
$ chmod +x installer.sh
$ ./installer.sh
$ wc -c start.sh # returns "0"
```

### OS and versions
* PocketMine-MP: `Final_1.4.1 (build 980) using API 1.11.0`
* PHP: `7.0.3-13+deb.sury.org~trusty+1 (cli) ( NTS )`
* OS: `Ubuntu 14.04.4 LTS`

### Crashdump, backtrace or other files
```
./installer.sh
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Di 17. Mär 18:00:47 CET 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Unterschrift vom Di 17 Mär 2015 18:16:17 CET mittels RSA-Schlüssel ID A7837F89
gpg: Korrekte Unterschrift von »Shoghi Cervantes <shoghicp@gmail.com>«
gpg:                 alias "keybase.io/shoghicp <shoghicp@keybase.io>"
[+] Signature valid and checked!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 64-bit PHP build available, downloading PHP_7.0.0RC3_x86-64_Linux.tar.gz... checking... regenerating php.ini... done
[*] Everything done! Run ./start.sh to start PocketMine-MP
```

**Comment by robske110** [comment]
So the contents of start.sh are empty?
try nano start.sh (If it exists in ubunt)

**Comment by CodeBrauer** [comment]
@robske110 yes - it has 0 chars in it.

**Comment by robske110** [comment]
hmm
You can copy it from the repo, but et this issue open we need to investigate this further

**Comment by CodeBrauer** [comment]
I found the bug!

[installer.sh#4](https://github.com/PocketMine/php-build-scripts/blob/master/installer.sh#L4) `BRANCH="php7"`

So the [url to download the start.sh](https://github.com/PocketMine/php-build-scripts/blob/master/installer.sh#L228) file would be:
`https://raw.githubusercontent.com/PocketMine/PocketMine-MP/php7/start.sh``

But this file does not exists. (The branch neither)
