### ISSUE TITLE
When to upgrade?

### ISSUE THREAD

**Issue by hawkao** [PocketMine/PocketMine-MP#4018]
### Issue description
When to upgrade the version of the support of MCPE?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by PocketKiller** [comment]
No steps or things provided, we do support the latest version, you might be using an old version.

**Comment by PEMapModder** [comment]
Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue. Please do not use the issue tracker to request for help. Please only report **issues** here.
