### ISSUE TITLE
Error on startup (clean install)

### ISSUE THREAD

**Issue by slebu** [PocketMine/PocketMine-MP#4019]
### Issue description
Error on startup (clean install)

### Steps to reproduce the issue
1. I just made a clean install of PocketMine-MP and this happened.
### OS and versions

* PocketMine-MP: 1.4.1
* PHP: 5
* OS: Debian Wheezy

### Crashdump, backtrace or other files

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/pocket/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by TheClimbing** [comment]
You  are using php7 with php5 core

**Comment by slebu** [comment]
Hmm, ok.

Should I go with php5 or php7 full install?

**Comment by thedeibo** [comment]
What version of Minecraft Pocket Edition are you doing this for?

**Comment by thedeibo** [comment]
That would help people to help you.

**Comment by slebu** [comment]
1.4.1 - I just grabbed it from the site.

**Comment by TheClimbing** [comment]
I prefer php7

**Comment by slebu** [comment]
Thank you.
