### ISSUE TITLE
An unrecoverable error has occurred and the server has crashed

### ISSUE THREAD

**Issue by Fightingfire** [PocketMine/PocketMine-MP#4025]
### Issue description

Write a short description about the issue
Crash but no reason

### Steps to reproduce the issue

1.Launch server
2.Wait
3.Crash

### OS and versions

This server is running ClearSky 1.1-#22 「Sunrise-#22」 implementing API version 1.13.1 for Minecraft: PE v0.14 (protocol version 40)
* OS: Linux ubuntu 14.04 
[CrashDump_Sun_Mar_6-11.13.15-CET_2016.txt](https://github.com/PocketMine/PocketMine-MP/files/160262/CrashDump_Sun_Mar_6-11.13.15-CET_2016.txt)

### Crashdump, backtrace or other files

* ...

**Comment by PEMapModder** [comment]
This is not a PocketMine issue. This is a ClearSky issue.
