### ISSUE TITLE
0.14.0.0 protocol change 0x8e

### ISSUE THREAD

**Issue by forthxu** [PocketMine/PocketMine-MP#4052]
### Issue description
you write  'blameshoghi':

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/network/Network.php#L223

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/network/RakLibInterface.php#L235

in 0.14.0.0 the pocketmine network protocols add '0x8e' at top of the buffer.
but i test,packets of (BatchPacket unzip) client didn't do this?

### OS and versions

* PocketMine-MP:0.14.0.0
* PHP:php7
* OS:linux

**Comment by jingz2007** [comment]
Does this result in the server not working correctly? It may just be outdated legacy code. Can you explain what the effect is to the user (i.e. a player on the server), or is it just a useless line of code?

**Comment by thebigsmileXD** [comment]
Just a question:
