### ISSUE TITLE
Error - Commands

### ISSUE THREAD

**Issue by fdfdffdf** [PocketMine/PocketMine-MP#4053]
I get this error when typing a command or in chat:
[RakLibServer thread/NOTICE]: Blocked [player] for 5 seconds

**Comment by KnownUnown** [comment]
Please use the issue template. What version of PocketMine are you running? What MCPE?

**Comment by fdfdffdf** [comment]
0.14.0

**Comment by fdfdffdf** [comment]
@KnownUnown PocketMine-MP 1.6dev ÒÇî[REDACTED]ÒÇì implementing API version 2.0.0 for Minecraft: PE v0.14.0.0 alpha (protocol version 45)
