### ISSUE TITLE
Error - Commands

### ISSUE THREAD

**Issue by fdfdffdf** [PocketMine/PocketMine-MP#4054]
### Issue description:

I can't type commands or chat
### Steps to reproduce the issue:

1. ...I typed in /stop and /help and /tp and the console said [RakLibServer thread/NOTICE]: Blocked XXX.XXX.X.XX for 5 seconds
2. ...I typed in hi and bye and the console said [RakLibServer thread/NOTICE]: Blocked XXX.XXX.X.XX for 5 seconds

### OS and versions:

* PocketMine-MP: PocketMine-MP 1.6dev ÒÇî[REDACTED]ÒÇì implementing API version 2.0.0 for Minecraft: PE v0.14.0.0 alpha (protocol version 45)
* PHP: 7.0.4
* OS: Windows 10

### Crashdump, backtrace or other files:

* ...[RakLibServer thread/NOTICE]: Blocked XXX.XXX.X.XXX for 5 seconds

**Comment by PEMapModder** [comment]
Set debug to 2 in pocketmine.yml to find out why.

**Comment by fdfdffdf** [comment]
@PEMapModder http://pastebin.com/iS3krgjd that's the problem

**Comment by fdfdffdf** [comment]
@PEMapModder you can lock and limit this to collaborators now

**Comment by PEMapModder** [comment]
This issue is caused by invalid installation, where the multibyte extension is missing.

**Comment by fdfdffdf** [comment]
@PEMapModder You can lock and limit this to collaborators now @PEMapModder

**Comment by fdfdffdf** [comment]
well?

**Comment by fdfdffdf** [comment]
lock and limit collaborators

**Comment by willotheblessed** [comment]
I do not believe this is fixed because I'm getting same errors and it's Jan 19, 2017. It's a misleading error - and installing pocketmine is never easy - hasn't been for 3 years or more, since I never tried it before that.

**Comment by dktapps** [comment]
@willotheblessed This is not an issue with PocketMine-MP, it is an indication that the `mbstring` extension is not present. There is nothing to "fix".

**Comment by willotheblessed** [comment]
Ok, why does the genisys source work and not pocketmine? Both seem to have an mbstring file - but not sure where it came from or if it's the right one. it's called php_mbstring.php

**Comment by dktapps** [comment]
it is an _extension_, not php code.

**Comment by Momibelle** [comment]
So I'm wondering ... how can we avoid this error? I am getting it too.
: /
