### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by AndreyR0** [PocketMine/PocketMine-MP#4056]
Hey.I have the error
Warning: require_once(/mnt/sdcard/Genisys/src/spl/ClassLoader.php): failed to open stream: No such file or directory in /mnt/sdcard/Genisys/src/pocketmine/PocketMine.php on line 107

Fatal error: require_once(): Failed opening required '/mnt/sdcard/Genisys/src/spl/ClassLoader.php' (include_path='.:') in /mnt/sdcard/Genisys/src/pocketmine/PocketMine.php on line 107

What is the problem?

PocketMine: 1.6 dev (0.14.0)
PHP:7
OS:Ubuntu

**Comment by Subtleoliver** [comment]
You are running Genisys. Report on their issue tracker instead.

**Comment by AndreyR0** [comment]
Is the app Genisys.This is a test on Android

**Comment by AndreyR0** [comment]
But the software is PocketMine

**Comment by PEMapModder** [comment]
Wrong installation of server. (Seems like the app has problems installing? Not our fault) The issue tracker is not for support. Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) before creating an issue.
