### ISSUE TITLE
date_timezone console output on debug level 2

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#4058]
### Issue description

> date.timezone not set

### Steps to reproduce the issue

1. Debug level 2
2. Watch console?

### OS and versions

* PocketMine-MP: 0.14
* PHP: 7
* OS: Windows Server 2012

### Crashdump, backtrace or other files

Adding this to php.ini fixes it:
```date.timezone = "Europe/Berlin"``` // see code here: http://php.net/manual/en/timezones.php
This will also fix time based events in plugins. Like: Ban until <time>, realtime time calculation
Maybe just add this to php.ini by default, thanks.

**Comment by Intyre** [comment]
Wrong place and invalid. https://github.com/PocketMine/php-build-scripts/blob/master/compile.sh#L966

**Comment by thebigsmileXD** [comment]
@Intyre If this is invalid: Why isn't it generated? May it be an issue with the code?

**Comment by robske110** [comment]
And i just found the error!
There is an > instead of an >>

**Comment by thebigsmileXD** [comment]
@robske110 :o Eagle Eyes.

**Comment by Intyre** [comment]
The `date.timezone` is set in Linux/Mac PHP7 archives on BinTray but not in Windows... 
When I remove `date.timezone` from the `php.ini` it still works without any errors.

Create a pull request for the `date.timezone` for https://github.com/PocketMine/php-build-scripts/blob/master/windows-binaries.sh

Start debugging from https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/PocketMine.php#L148 and find out why it doesn't work without `date.timezone` on windows.

**Comment by thebigsmileXD** [comment]
@Intyre Maybe you haven't seen the issue that Robske found. @robske110 Will you PR or should i?

**Comment by robske110** [comment]
You can do it

**Comment by Intyre** [comment]
@robske110 Check the difference between `>` and `>>`

**Comment by thebigsmileXD** [comment]
@Intyre in this case its correct. Its writing the value to the file.

**Comment by PEMapModder** [comment]
@thebigsmileXD That is the **first** line of `php.ini`.

**Comment by thebigsmileXD** [comment]
@PEMapModder The first line can also be set via ```>>```
