### ISSUE TITLE
Startup error float

### ISSUE THREAD

**Issue by Dakado** [PocketMine/PocketMine-MP#4062]
Every time I try to start the server via ./start.sh it gives me this error:

`Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/mcpe/PocketMine-MP.phar/src/pocketmine/Server.php on line 71
`

But when I replace the phar with this one: https://github.com/iTXTech/Genisys it works like a charm, so why you are distributing unchecked and corrupted software as a stable version ?

**Comment by jojoe77777** [comment]
You are using an old version of PocketMine with a new version of php. Update your PocketMine!
