### ISSUE TITLE
Startup error float

### ISSUE THREAD

**Issue by Dakado** [PocketMine/PocketMine-MP#4063]
Sorry that I am opening another issue, but me previous one has not been resolved and sombody closed it: https://github.com/PocketMine/PocketMine-MP/issues/4062

How can I use old version, if I have downloaded the stable one from https://www.pocketmine.net/, so the official page is outdated or what ? Where should I get even more new version ?

I have used this command: `"wget -q -O - http://get.pocketmine.net/ | bash"` to get the version and compile libraries, later I have also tried to manually download newest dev phar version available and I have still this float error...

**Comment by PEMapModder** [comment]
It is your own problem installing the server. This is not an issue. Please stop duplicating.
