### ISSUE TITLE
1.4.1 attempting to load on Multicraft x64. Cannot load

### ISSUE THREAD

**Issue by djoveryde** [PocketMine/PocketMine-MP#4064]
I'm having issues trying to load the server on my multicraft installation.
I use other multicraft servers so require 64 bit however the server is constantly failing to load.
This is the error i get:

27:46 [Multicraft] Loaded config for "Other: PocketMine-MP"
12.03 11:27:46 [Multicraft] Failed to start server: [Errno 13] Permission denied
12.03 11:27:46 [Multicraft] Is Java installed and in the PATH environment variable?
12.03 11:27:46 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 0
12.03 11:27:46 [Multicraft] Restarting crashed server in 5 seconds

**Comment by fdfdffdf** [comment]
please use the issue template

**Comment by fdfdffdf** [comment]
close this issue

**Comment by fdfdffdf** [comment]
and use the issue template next time

**Comment by PEMapModder** [comment]
@fdfdffdf you can choose to or not to use the issue template. The template is only for reference; if it is not applicable for your issue, you can choose not to use it. Please don't spam comments (three comments in two minutes, and two of them have the same meaning; and you should use the edit button. This is not a forum. Nor a chat platform.

It seems that you are configuring multicraft wrongly. This is not the place to ask for help. Please refer to the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue).
