### ISSUE TITLE
1.4.1 attempting to load on Multicraft x64. Cannot load

### ISSUE THREAD

**Issue by djoveryde** [PocketMine/PocketMine-MP#4065]
You are aware I could have just edited that last one...nevermind...

### Issue description:
I'm having issues trying to load the server on my multicraft installation.
I use other multicraft servers so require 64 bit however the server is constantly failing to load.

### Steps to reproduce the issue:
Load the server on Multicraft 2.0 with Java 8 x64

### OS and versions

* PocketMine-MP: 1.4.1
* PHP: Unknown
* OS: Ubuntu 14.04 (Multicraft 2)

### Crashdump, backtrace or other files:
27:46 [Multicraft] Loaded config for "Other: PocketMine-MP"
12.03 11:27:46 [Multicraft] Failed to start server: [Errno 13] Permission denied
12.03 11:27:46 [Multicraft] Is Java installed and in the PATH environment variable?
12.03 11:27:46 [Multicraft] Failed to obtain process information: NoSuchProcess no process found with pid 0
12.03 11:27:46 [Multicraft] Restarting crashed server in 5 seconds

**Comment by PEMapModder** [comment]
Please do not duplicate issues.

**Comment by djoveryde** [comment]
You just told me to redo it using the template? 
This is being contradictive??

**Comment by djoveryde** [comment]
At least point me in the right direction instead of having someone lock one issue telling me to use the template and then you telling me not to duplicate it. I don't see where the same issue is posted?

**Comment by PEMapModder** [comment]
@djoveryde I did not tell you to redo the issue using a template. It was someone else who is not even a contributor to the PocketMine repo. Please refer to my comment in #4064.

**Comment by fdfdffdf** [comment]
@djoveryde do you have a pocketmine.yml?

**Comment by PEMapModder** [comment]
@fdfdffdf please stop using the issue tracker as a forum or chatroom, or you may be blocked.
