### ISSUE TITLE
Soartan Master glitch

### ISSUE THREAD

**Issue by YoutubeESG12** [PocketMine/PocketMine-MP#4076]
So I got spartan master, and I extracted everything, but it comes up with this! [I use Android].

[Genisys Android v0.2.5 alpha
Powered by iTX Technologies

Workspace: /sdcard/Genisys/

a. Init Genisys Android from zips
[NOTICE] Put php.zip and Genisys.zip into /sdcard/Genisys/
b. Launch Genisys
c. Set workspace
d. Edit php.ini
e. Rewrite php.ini

i. About Genisys Android

Select: b

[NOTICE] Now loading ...

Warning: require_once(/storage/emulated/legacy/Genisys/src/spl/ThreadedFactory.php): failed to open stream: No such file or directory in /storage/emulated/legacy/Genisys/src/pocketmine/PocketMine.php on line 104

Fatal error: require_once(): Failed opening required '/storage/emulated/legacy/Genisys/src/spl/ThreadedFactory.php' (include_path='.:') in /storage/emulated/legacy/Genisys/src/pocketmine/PocketMine.php on line 104

Press enter to continue ...

**Comment by thedeibo** [comment]
Im affraid we cant help you, because you are using  a third-party version of PocketMine. SOrry

**Comment by PEMapModder** [comment]
Incorrect installation of PcoketMine.
Or is it even PocketMine?

This is not a PocketMine issue. What you need is support, not bug fixing. Please read the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue) for details.
