### ISSUE TITLE
Server start ERROR

### ISSUE THREAD

**Issue by AlexinnoSB** [PocketMine/PocketMine-MP#4077]
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [01:05:47] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [01:05:47] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [01:05:47] [Server thread/INFO]: Loading server properties...
[Server] [01:05:47] [Server thread/INFO]: Enable MainLogger to file
[Server] [01:05:47] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [01:05:47] [Server thread/INFO]: Starting Minecraft: PE server version v0.14.x beta/alpha
[Server] [01:05:48] [Server thread/INFO]: Starting remote control listener
[Server] [01:05:48] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[Server] [01:05:48] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [01:05:48] [Server thread/INFO]: This server is running ClearSky-Sunrise version 1.1 (API 1.13.1) Build 153
[Server] [01:05:48] [Server thread/INFO]: ClearSky is distributed under the LGPL License
[Server] [01:05:50] [Server thread/INFO]: Loading HealthStats v1.1.1
[Server] [01:05:50] [Server thread/INFO]: Loading Jail v2.1.2
[Server] [01:05:50] [Server thread/INFO]: Loading HealthBar v1.0.0
[Server] [01:05:50] [Server thread/ERROR]: Could not load level "world": zlib_decode(): data error
[Server] [01:05:50] [Server thread/WARNING]: RuntimeException: "zlib_decode(): data error" (E_WARNING) in "/src/pocketmine/nbt/NBT" at line 2
[Server] [01:05:50] [Server thread/EMERGENCY]: No default level has been loaded
[Server] [01:05:52] [Server thread/INFO]: Stopping other threads
[PocketMine] Server was stopped.

This is the error. Help me.

**Comment by RekkuzaRage** [comment]
This is not even PocketMine, this is a third party modded version of PocketMine... Please don't post issues about ClearSky or third party builds here.
