### ISSUE TITLE
Client/server time out of sync (can only sleep at night)

### ISSUE THREAD

**Issue by dengarrett** [PocketMine/PocketMine-MP#4081]
### Issue description

Get message saying "can only sleep at night" when it appears to be night time.  Also, can sleep during the daytime.

The problem is the code below in Level.php is adding 1.25 at each tick.  When I change this to 1, the problem goes away.

```
public function checkTime(){
    if($this->stopTime == true){
        return;
    }else{
        $this->time += 1.25;
    }
}
```
### Steps to reproduce the issue

Just let the world run for a few day/night cycles, and then attempt to go to bed
### OS and versions

- PocketMine-MP: 1.6
- PHP: 7
- OS: Win 7

**Comment by PEMapModder** [comment]
Which PocketMine-MP build are you using?

**Comment by dengarrett** [comment]
It could be - I am somehow not running with that change.  I pulled everything seven days ago, so figured I was using the current code.  I am new to github, so I'm sure I somehow just didn't know what I was doing :)  I will make sure I have everything pulled and back out my change and test again.  Thank you.
