### ISSUE TITLE
Placing blocks

### ISSUE THREAD

**Issue by GlitchPlayer** [PocketMine/PocketMine-MP#4082]
### Issue description

When you try to place blocks, you cannot saying unknown command. Destroying blocks good but not for placing.

### Steps to reproduce the issue

1. Place blocks
2. Unknow command message.

### OS and versions

* PocketMine-MP: 1.6 API: 2.0.0
* PHP: 7
* OS: Windows 10

### Crashdump, backtrace or other files

* None

**Comment by PEMapModder** [comment]
Cannot be reproduced. Most likely you are using a plugin like TapToDo and misconfigured it. If you need help, please use the methods mentioned in the [contribution guidelines](../blob/master/CONTRIBUTING.md#creating-an-issue).
