### ISSUE TITLE
Slash at the end of motd breaks the string

### ISSUE THREAD

**Issue by amaax** [PocketMine/PocketMine-MP#4083]
\ slash break the string by escaping semicolon in RakLibInterface.php:172

**Comment by PEMapModder** [comment]
Please elaborate the issue. For example, how to reproduce? What's the result?

**Comment by amaax** [comment]
1. Put "\" slash to the end of motd in server.properties
![scr1](https://cloud.githubusercontent.com/assets/3604532/13960308/ddab32c2-f068-11e5-8b6d-0706c7855566.png)
2. Open Minecraft PE's worlds list
3. Here it is
![scr2](https://cloud.githubusercontent.com/assets/3604532/13960378/2f09320e-f069-11e5-9f71-dbf267d8c34b.jpg)

**Comment by Intyre** [comment]
I think this can't be fixed.
- ```motd=\``` shows ```\;45``` ```20/-1``` and ```0```

There is only one place in the code that changes the motd. [RakLibInterface.php#L173](https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/network/RakLibInterface.php#L173)
- ```motd=\;``` shows ```\\;``` and correct info
- ```motd=;``` shows ```\;``` and correct info

### Solutions
1. rtrim
2. @shoghicp

**Comment by amaax** [comment]
`"MCPE;".addcslashes($name, ";") .";".` ->
`"MCPE;".addcslashes($name, ";") ." ;".`
