### ISSUE TITLE
Stable Release 1.4.1 both requires and ignores php7 on linux, start.sh fails to run

### ISSUE THREAD

**Issue by sophiaIAF** [PocketMine/PocketMine-MP#4084]
### Issue description

Opening this bug on behalf of my daughter.  Platform is a Lenovo T420, i5 dual core processor, intel HD graphics, with 16G of RAM.  The OS is Ubuntu 15.10.  Also, php7 was added after originally receiving an error that php7 was desired.  php7 is in the user path, but appears to be ignored by the installer.  The following instructions were followed:

Install the dependencies needed to compile. You may have to install perl gcc g++ make automake libtool autoconf m4. If you want to compile from x86_64, you might have to install gcc-multilib.

Navigate where you want to install/update PocketMine-MP.

Run the following code. It will download PocketMine-MP, download the PHP binaries or compile it if binaries are not available.

wget -q -O - http://get.pocketmine.net/ | bash

Run ./start.sh, PocketMine-MP will now start.

### Steps to reproduce the issue

1. Follow the instructions from the pocket-mine home page.
2. Script gives an error about not having a php7 build.
3. Script downloads its own php5.x
4. Running ./start.sh fails, even after php7.0 is provided, here is the output:

sophia@sophias-laptop:~/bin$ wget -q -O - http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 10:00:47 PDT 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[*] Checking signature of PocketMine-MP.phar
gpg: Signature made Tue 17 Mar 2015 10:16:17 AM PDT using RSA key ID A7837F89
gpg: Good signature from "Shoghi Cervantes <shoghicp@gmail.com>"
gpg:                 aka "keybase.io/shoghicp <shoghicp@keybase.io>"
[+] Signature valid and checked!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] Linux 64-bit PHP build available, downloading PHP_5.6.10_x86-64_Linux.tar.gz... checking... regenerating php.ini... done
[*] Everything done! Run ./start.sh to start PocketMine-MP
sophia@sophias-laptop:~/bin$ ./start.sh
Couldn't find a working PHP 7 binary, please use the installer.
sophia@sophias-laptop:~/bin$ which php
/usr/bin/php
sophia@sophias-laptop:~/bin$ php --version
PHP 7.0.4-6+deb.sury.org~wily+5 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
sophia@sophias-laptop:~/bin$ 

### OS and versions

* PocketMine-MP: 1.4.1
* PHP: php7.0
* OS: Ubuntu 15.10, Linux sophias-laptop 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Crashdump, backtrace or other files

* ...

**Comment by Intyre** [comment]
https://forums.pocketmine.net/threads/16037
http://pocketmine-mp.readthedocs.org/en/latest/installation.html#installing-on-linux-macos
