### ISSUE TITLE
Can't install PocketMIne on a Raspberry Pi 3 model B

### ISSUE THREAD

**Issue by HittmanA** [PocketMine/PocketMine-MP#4088]
### Issue description

Using wget -q -O - http://get.pocketmine.net/ | bash
in my terminal I am trying to install POcketMine. Whenevr I do this it downloads evrything, however when I run the command ./start.sh it says: Couldn't find a working PHP 7 binary, please use the installer.
How can I fix this?

**Comment by robske110** [comment]
http://forums.pocketmine.net/link-forums/bugs.8/

**Comment by robske110** [comment]
You have to read the installation totourials:
http://forums.pocketmine.net/threads/latest-phar-and-php-binaries.16037/

**Comment by Yuns92** [comment]
There is no php 7 binary in pocketmine.net for the Raspberry Pi.

You should use this one from [Rotzbouf](https://forums.pocketmine.net/members/rotzbouf.43501/): https://drive.google.com/file/d/0B60O0ROCfeCmVW1idWx1WFY5RXM/view?usp=sharing

You jus have to put the php7 folder in your_pocketmine_folder/bin.

(https://forums.pocketmine.net/threads/php7-with-pthreads-for-raspberry-pi.15424/ | https://forums.pocketmine.net/threads/latest-phar-and-php-binaries.16037/)
