### ISSUE TITLE
Can't send commands on the console when left for a hour or more

### ISSUE THREAD

**Issue by GlitchPlayer** [PocketMine/PocketMine-MP#4090]
### Issue description

Write a short description about the issue
You can't send any commands when you left the server for an hour or more. Even the default commands.

### Steps to reproduce the issue

1. Start the server  Wait an hour or more 
2. Try to send commands

### OS and versions

* PocketMine-MP: 1.6 [REDACTED]
* PHP: 7
* OS: Windows 10

### Crashdump, backtrace or other files

* ...

**Comment by jazzwhistle** [comment]
I'm on the latest build and it's been running for 1 day and 17 hours, still running fine, and still taking console commands. Sure you don't have a plugin that's causing a problem?
