### ISSUE TITLE
No water, lava bucket or villager in creative inventory

### ISSUE THREAD

**Issue by kabluinc** [PocketMine/PocketMine-MP#4091]
I look in my inventory and there is no water bucket, empty bucket or villager. im using php7 and latest pocketmine phar 0.14.0.

leet servers don't have water, empty bucker or villager in the inventory either. 

0.13.1 did

**Comment by jingz2007** [comment]
I am running a PHP 7 build for the current MC:PE (v14). In creative there are two lava buckets in different parts of the inventory (another dupe is cooked and raw fish, but IDK what type of fish I have for dinner, though being able to put out a fire would be nice). Luckily, I found a very inconvenient way to get around this! While NOT flying (feet firmly planted on ground) do '/gamemode 0' to go into survival. Next, do '/give _yourusername_ water' Now look in your inventory and see you have 64 of a block called water with a missing icon (yours may have one but mine sometimes does sometimes doesnt). Click on it. Click where u wanna place water BEFORE going back into creative mode. Sadly you cant fly while doing this. This should work for the others too but i dont have those issues. When ur done placing them, do '/gamemode 1' IK this may not be the right place to put this but im just trying to help @kabluinc
