### ISSUE TITLE
Placing blocks bug

### ISSUE THREAD

**Issue by AndreyR0** [PocketMine/PocketMine-MP#4095]
Hey.In Gamemode creative the blocks cannot be placing.....and they disappear from hotbar...fix?This is happening only in gmc.in gms it's work perfect(Soory for my english,i'm romanian)

PocketMine:1.8
OS:Windows

**Comment by PEMapModder** [comment]
There is not a PocketMine version called 1.8

**Comment by AndreyR0** [comment]
@PEMapModder http://imgur.com/9Hijp5f

**Comment by PEMapModder** [comment]
Then this is not PocketMine.

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/PocketMine.php#L75
