### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by fdfdffdf** [PocketMine/PocketMine-MP#4098]
### Issue description

Write a short description about the issue
When I run my checkgm command with an arg where that player is not online it doesn't work
### Steps to reproduce the issue

1. ...I typed /checkgm d

2. ...and then came with an error(second link at bottom)

### OS and versions

* PocketMine-MP: 1.6dev-23
* PHP: 7.0.4
* OS: Windows 10

### Crashdump, backtrace or other files

* ...http://pastebin.com/8yWwyf98 the plugin code
http://pastebin.com/H5KfFUQ3 as mentioned earlier

**Comment by thedeibo** [comment]
the POCKETMINE-MP issues is for PocketMine issues only. 
Please result to the IRC ( as you are using now ) or the forum for help

**Comment by fdfdffdf** [comment]
ok
