### ISSUE TITLE
Chunks won't load

### ISSUE THREAD

**Issue by HydraGaming** [PocketMine/PocketMine-MP#4101]
Chunks will not load or will stop loading in some areas of the world

**Comment by PEMapModder** [comment]
Are you sure you are using the latest version? What is the version you are using?

**Comment by HydraGaming** [comment]
The pocket mine version? 1.6dev API version 1.13.1

**Comment by PEMapModder** [comment]
This is not the latest development version. You can get the build for the latest development build at http://pmt.mcpe.me

**Comment by HydraGaming** [comment]
I'm using 1.6dev

**Comment by HydraGaming** [comment]
I visited your website, I can't find where the download is for the latest build

**Comment by HydraGaming** [comment]
I downloaded the master.phar is this it?

**Comment by HydraGaming** [comment]
I pasted the file into my server folder and renamed it PocketMine-MP.phar and removed the old phar I had and now my server won't even show up online

**Comment by PEMapModder** [comment]
http://pmt.MCPE.me/pmb/dl/master.phar
Only 0.14.0 is supported. And please use PHP 7.

Please don't use the issue tracker for asking questions. Read the contribution guidelines.
