### ISSUE TITLE
my server wont enable

### ISSUE THREAD

**Issue by thethrill999** [PocketMine/PocketMine-MP#4103]
### Issue description

Pocketmine won't enable my server

### Steps to reproduce the issue

1. ..
*PocketMine-MP: latest version
* PHP:
* OS:

### Crashdump, backtrace or other files

* ..PocketMine-MP Crash Dump Wed Mar 30 09:41:11 UTC 2016

Error: RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use
File: /src/raklib/server/UDPServerSocket
Line: 32
Type: error

Code:
[23] 
[24] class UDPServerSocket{
[25]     /** @var \Logger */
[26]     protected $logger;
[27]     protected $socket;
[28] 
[29]     public function __construct(\ThreadedLogger $logger, $port = 19132, $interface = "0.0.0.0"){
[30]         $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
[31]         //socket_set_option($this->socket, SOL_SOCKET, SO_BROADCAST, 1); //Allow sending broadcast messages
[32]         if(@socket_bind($this->socket, $interface, $port) === \true){
[33]             socket_set_option($this->socket, SOL_SOCKET, SO_REUSEADDR, 0);
[34]             $this->setSendBuffer(1024 * 1024 * 8)->setRecvBuffer(1024 * 1024 * 8);
[35]         }else{
[36]             $logger->critical("**** FAILED TO BIND TO " . $interface . ":" . $port . "!", \true, \true, 0);
[37]             $logger->critical("Perhaps a server is already running on that port?", \true, \true, 0);
[38]             exit(1);
[39]         }
[40]         socket_set_nonblock($this->socket);
[41]     }
[42] 

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(143): pocketmine\network\RakLibInterface->doTick()
#1 /src/pocketmine/Server(2216): pocketmine\network\RakLibInterface->process()
#2 /src/pocketmine/Server(2110): pocketmine\Server->tick()
#3 /src/pocketmine/Server(1986): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/, string /storage/sdcard0/PocketMine/, string /storage/sdcard0/PocketMine/plugins/)
#6 (1): require(string phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.10.17 #1 SMP PREEMPT Fri Oct 16 15:04:57 CST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtfYt24zaS6K9gnZyNOyPq/c46d9S2uttnZFsjyd2TiebyUCQksU2RHD5sq2fz71tVAEmQomR3
Njdn79k4aYlEFQpAoVBVKDz0r7PI3vGzYaPdGbRa9X6vUTlzjDAaB4EXnA3/dRbtfQCfcXqvnO14
GBobTJkZDxN7xRbbgBsWMwMj3HKL/RwYD469Wi5DHjzyYLm8v5rO6XHumQ88+seQhfSgr2zXOn8z
ZLFrrBzOIo9hCjMsK4Ay2M+DPuCO5JvtsjjkUP46dpx3toMV8LdGMKzVamHkBVClWmiZRmDVa1Oi
f2O7XHnUbqZVzFALA7Mm6lgTVawVaghoPhYkCnkZH3AdKOBs2GpWzqLAMOHx57Nv6oyy+oSzw8q4
PHrygoeaYNy1G/FgDdjnjXYL2JAhLpcSc7ksoGo/Wt7CNh/O30Ch3zQOShDVOm82G91XU/QDzwQO
C5LNoyQbjXqBpIBoP0ZphVrHcjcG/e6J3FNRBS8QZNpHyfTqrSNkwsgIIpG9c5A9k4Lzdrt5hIKu
m54bRkFsRucq/NLb+UZkg4hewrgIJ55h8YB5q8/cjCo5SnFkO+FyeWPY7sTbbBQsIGu7G/brBDbN
firfq5B8J97YblgjNnXZeQNYEfB/xnbAz/9bVTzKbxxLb87+8UtF6o//gfrkVwxzaI5g5dlwbTgh
r5yZnsWxcc0W0ALMZhu+TZQXViDzL4R2AMrgr/b99+zPj0bAlkspMd/XEN6VcBibEQgQsOFbh+A/
ILR3CBUsIGhf1mCQYMUrxzbZOnbNyPZcpsr5cim4zS1ZvCymwr71vSBiF6wxaIBaY9/aicKAtOVZ
vUr/Lc/eYHNadVkU/n0bbe0QxiNVCJBl55hQTMTPR+/069vxosLmd5d/0a/ez0Y3+DzRgUtvsPqt
hkILxFDkDuGf52P1z3P0RV6kJWjqb2d3o6vL0RzeGm9+AAIjx/GeWMhdC6V7FcDoNcG6MSl2IRbZ
VIq01+d/VuWpUFzGB8miN+ziAjiyBH5ywYyWQg3/vrYJs/H9fDy6uppVWF2wpF2gmOTn0Rza9TZe
r1E31ptt9j2TX/03BJ9x8/EInCh3FMq/cJBkakG3WJ4QCu1HM7BBXRvO+fLse/hj70bXk/EVW9yx
t9e39L08Y1VVWKqQMhSJJFD4/m/Ls4rkWPYtm9p7RdFTHmwNP2QGEwOV2fDsoBjvWRC7LnY0yHm0
NSKGhf6fE+X1C+XxZzsCtUiwgcocSGirYq70quu5Kwde8/1KNNqJNFN+lLOzX/7wEf7wEf7wEQ59
hMrZhrs8MBy0o8DtEFQlDJhGtV1tQF1Wse1YZ8NBvw7GFwyfZ3qA2YQ3w7cJr9Go1gFxY0fwWn/l
H2QQVh/zVHtEARwInBGdTWw3fmYwtA1n64HNaFUb9Wqjx2BQzW+mbDobj2+mC/YusNmdGbFGlzU6
w3p72Omxy/mCNeuNDjOC3WPPAaI4qRiedardahPevoDihtcmvNYFUPfCpEhIoBfDtQLPts5SdyNE
1lzxx4XnOfQsK5omVXKMg9oicSOOtl4QosLJmM4W3Ngh04l7PwM2tA7fOXlPUDnSk2cW96GqmBlg
obeOrtSEnYE+UFr+cqnUxIFBALD5YjRb3E8h4YmvQjvC+m6jyA9BgqCrtvGqano7VXZSGtBueyp8
HOE6yuYqiWqDoQGrfHMnV3/LNXFA/Gii6/Jrmwokl8usAmIkZ62d3s0Xn+5mk6uX2gt0tJvL6bim
NOYX7GgjgEaC4k3qQZqnChLv8yCyOcrFN9P0jV167treMPRil8HS/eYTeIM34FC26qw+GLYbw0ad
3S8uURi7iCDoacjJC+Q2uNnraMimDjdCHNtjy0YfRUFFE3pBbiAmbiDjDpzdizq+7YxnzXeMPVT3
okEpoW88uZr0TIHQhdbA5KctcMKxw+jCW68xQfBe+2fMg/2FKE8mBaBiZYrFQ7D75DRdCBXMdqBZ
2dqDB2rvzousi0/cAZZy9mdRFfT80RJL9+DflLbg3OPC9YKd4VBuaEqw1xx7Z0MTm/0bTMTghxb7
FrirSWUN1/XAfeayrZphbm3+yHfcjUJZ1UebP2kWNNAAPMkLA31Pbe3Ym23absEfw7WhCklekbbz
VkkCqEvL9IK0fP/RTzhir9e2GTvR/kJ0B6lMEB4NPJEIOjC8oDZA7RzRyWDRHStLCzm3FBRiyNX4
3eh+ssBUZH7VBxMG2ayL7+kPGhJHnhYaj1zWgnpTU7sTegTYkwqHTEXNlmr86n7noPAyHDHMJLmN
oe44J0HxpV7N2Q0QZ5gN8pCzpHGgTmFit+Xg34Hsk4dnYudEbMVhSmc6MUxlcG53MGyQ1hyFxFsj
gSLN0FiDU+gBJAiRJMwUuPHA9l4cpF7mmkHb7LVNJUD3BCDhzn7ponQJUsMllLyNI8vD/hQzjCF4
vFJ2TccLubU8A6xvxLwEWUgWVah39mgb7K84JACFhoYmIUOGOgozzreQz0D+hR4wTZbCnrbchWSB
jlPbkIE+gyoaOD8cTa8BE/SiBYxQABpUawWVysiPxeRZ0gELxFAQcaoJfURTqD3kXxsggoAuh2wK
HTKaDwPEsB5xJFiaCYOFZ+mx7/oa9PQTiHguwzc4l4HOAG96v/NiGL0RyAawxwxxQIv5IzQMGxtw
VErYFJzYabHgc9KE23i3Qr9qzUbh3jUXRvjA0K+FrkXwp9Hs9vr2/RBEC3TEk+042J1AHmRi43gr
w2FCL4jCKmwVR8yOgIT7HckZdpqQMpTEyIsMp4otxsI0WdCQNVAwLL6KNygV31yv2Y+sUSFCWGSI
3UjgdCqaUJRdC7lojBKppGNC9N2MKMaWgM7bQQeFKQ+zMZ6J4zcwgJIOwxG2gyFD44ZQZftBXIQA
CS5bJCOURRNZhmwHoA0aBtEWMYmCmoIARSFbB94OpE+lD7zFcRkpxZNePqgNDH80ntRzd4ux7Bf4
34xhiLkwxIiQvfMd0rhUPVlyWr2UA+Y2dh80Od8nBoxAmtwIxYFgaBZcqos0XMxHkwEzDED20UbA
45C1MSu69RgtQhVF/EJOWYJVSUhBEK2yD6DlgdAFKAkYL5fT+wpkCUO2gi56sq1oK8RJ9FtCVZM9
3D9eUSOAVItxGEayxoCLdlcgDVmz080ajpVPGn5jPDOjSFPO5LikeNDuZreOeWeGZcMYzPLJahhM
sbEiL35pAeFLtr2+G8k0SmObyTEoSm6ICpGROeheafWAgdTQT1uOihvrBPN/krEMA+XLYGg3eUAd
L8KLYGs8gYqOnUxFYu+znDQ2cMBjP24cOzK3+5JcQkMQsmNsqP+R0D35U5FQMtD9aww7pfaaWANa
GMYwCBIxA2RLIyWSqTLowuphH0I7JR2eCi8YLxdYjDZUoZMwNOvfhsJFcyhAtmdptksI0Andeh1x
6E0DKCIJf0UjRwV7GVGgoTAVBsJJKqop9BTQUSAyiETqX8MOdWN/yAaCuPB4yO8iLZXQAio9zCUL
RKIdfH0ysKA0kdKM3cqGDhUo0kcRhmGYmBMRRE7MBTFHyj90TWq+rJTfZE0wlJtPSfVpLhXmbDb4
PWkiThGHosSq4vW4PEqrJwSdOFosGnSBgA5FewNXk3YgRRGpnq84A5foqaBGBS3i+TisQBh5ZKB4
g52AEtAygbYB4Q/QGG/BW0KFI4BSmcckqYZKhslplWKw4g3YKPC3gMRGSDZnkh6yRICTEsICW56e
nsqY4thgdYWdGj8bqBrEC1pHoC8rMUxqQyCQrjDyQJZ+xkcNnGyMa3j+P5Aiebup4VO9PGqEB4QC
2+KqjkBW8ajUaST/h7z4kGwUNnsHpsuGikoDqlSdSqUK0BNDVxvHCunErLQhezcZLYbNH3qVzuC5
UWk9tyrNHxo/WKAMhOI5jwIOLzDoL/p1tgGJCsVbu/OGnGr+HHEXGUJBgEtQOEpoAYVIeQWtt0mX
KXwTUeVL+E9QabwlAh8adD7GJUQkpEkT5ZUJtnWbrXEYDsi9EWQJYikneYsDJ30BdxAEnUjLsMw6
8lPoZpc9b2G8ULQCkT6HMnTRpJjPbiUiTikyeCF7P8paALMtqJClNHc+nVCp+OybYHayvHtoMEVd
5BPrVLF22HKm4QS5We/UW/D47TX027rVa3GjY1mdTqvf6zba9a7RrzebRnvVN1q9drvRXzXbdc6+
hZKmW2QLRRaoYC+0nzOmCzMRSoQGNnTG146YIEMqldfnnbUJk9t1G4qtr3s9s9fvdzsdKLo1aLZ4
q74a9AaWReWF252XsVAEnMN8S23BfECOvAfu2l+S7oCUTzC3AZ0gGFXtQMreoMlZo9oghC+2L96a
1TaFn4SuozV3ejoHQZx+mLKPYmCyix8Z9QCOwfkeVPkOk367ANrSfYvxP3aFNg8oE3oPMdqs0Ri2
O8PWYOleykkl+F/CN0ZU9l21lsw2+Xfwqmly2mK7uKCn4arMzv5CQ+87BKO+tJ8vao9GUMP1wM/c
fcCQ6GeYodeg1ZoySx2JGF0N/X6waiavoXsH09maGXg4bsWLDOVp1JraynZrwMgOlcafufk7F4n+
iIbj9XctEHXL716gZtnB71oojqTftUChE3/XIkF//57leXGkuSCu4Crk0lCr4gj+ThnTiclQ0xLD
paY9CRWoJiV6mtIsO6REjEyhwsslQrOfd04uqfhuebvce0gTn5JctPweFFOfAjDN+VRzY+cpiilk
vlQMKORSfMvL8cznkg9Jgo1T6TyK5WnCN8h63LfNHKu2eW6SJ6AmSJOUS4I83LpwvVwiBnnMiz0v
oIJ5y/UqzLYi+AeTgC9RvoPAVQwiLTI2OQpfyG+3N+Bi5tLJJVAT+G7FLZh/acJo5goVboIy0gjl
Qk2XqMJTynEkTwsMqvoKzpCiprCuj7uL93eLO0pFW3kBYwHkDOyntotDmD6t7EO+IcJDjhu2/9hV
8TyfJmCC60hXJ5+7nPrlZUk6TBOx6y/BaX0/v9BCIH7XxCLW0+tL/BZVyT8JjKv5XyfXi7H+YfRx
rF/Pb0e3lM/1NOSWBq64EIZ17GL8VaSq1jhM8LEnoY/Ah/HStCgwfPBFNlrC+vXadjEuLcjAbDjB
pNBFDlOSNDBmqbmGLAjdbu2R1mLAXaIkD2ao2hqXZDTfo20NSYWfMBygOR7MxyjJfoSah2pzEFbS
HDD1lg2uH8xdcPbvuVJbrWlbQJDVhPLbpEbWAcdgvoYxOJonU6L5LKbQwJkAJmX8O0idXCUdlXTG
5Prt/ALQHanfMKtj0SAA5QMzzEfMd/m3v5V2/p/+JIB/dP//B90PvrdYacB4P7i+iRc8wQXfdDvH
0v1oB1FsOOzKDqi5ezaPfbHh68ckMpF50yIYhntu2TnY5Sqw+Q2bAi8R+/+9G4DUly5tqbBYSZ2g
Eueu53KYkcxx5YYibuD1UbjHsMR6JjQW600LTaGaZVSK4BsBhkgVPJzsSK7CpKPVaNS7InGczMVT
ULMJoL9j+CkPOwoUUxtAgQJSrMpiXiwgh6eiXdE6Qgp2vaUrd1HOQRKjfa5bqfA5iT/7ACynVZ0D
hBuxBHJjuAZuUjmEYxhktYfZmCI6fuA92thNqz1LHLGlez197KpY0lYBpasFynw5bOnOpLQDPeTD
HEaFsaPOSyLoVfTwKwykpEIdV6EFnAqzjMioMFx1h3T8QH+lwsAI56gKikzsy2RQFzcUgUIoIjIh
W2zhh2s/4+OmLO87inNQDqxL9fsKE/44PVk8fRbMqAZe1Gilb5EHLcfdlum74z0p7/jl6+jbpGst
SAsDg/GOW9BQTqFc5BaF26EDNqCt2M54ACnGZR2x3MlEp4vFdOjuCeiLGFfSxhjLw8iVEEl6Y4+0
LaUCg83fBxihZ+fmG9YYDPoaTbgJdwFFu1DfDS2u4n9M/23+BLXcSMcE4WPh09vLG9Q+YYnOApki
nQbqlQIQGHpgHw0nptcbA3tPvCcEqyFODxBapw+Kj8sJA9VDPh8p7pKi/ceDIa+vDsUZdZiU62vP
50TlTn6qQLnKTYD1Wn4hwpOxD3Xf82PHiLgeGE/wAv4ejgW1dUaw0UOO20xA8YPK82Nq0r/TRxEM
04EiPBQCeVB+HHk6WGTglb6Watn12GPS1uRZYoqF1lD/bEeFhiIUBvcrCK0C7wk6zz+OIVcadXOL
+pxKiqO11seH+8U7rZ+h7Owdx0kMjX3+HNW20c7JveDmC1JOOu3rFmbkSLkSMdlzfRoVV9R02g5P
ePPF1d39InvKcGj/YuwruJJv2AGWZ+qB50UnivJMmPHq0J4XcU4TEuKvW06+62RyKnU6WiBpXBQs
rHwiKXJD4fGSCBmUzEsoicS8jqBYEJKI9QLGsx3pnqvjqShPyL4q5/wZ2geN3PqFZiVWWkfX43dz
jPChli0H1MCzpRgATpO1xEf4H1adpYvjWo99XFIJ82zcgrmhReGqWBkl/v/H2oOHMNo7/GJ5ZoLR
CYbsm3fv+rjEePajfPqPGqL9+NUZ1EKTrQlHaeCW0bdvkYZ4erHQIxnUQhNNc5yAqLV4elWJJRnU
Eh/4Hvd3naLR6yU08OkVhZZmUAvNhmY5iaurpN7i6cUyj2SAMoGhqpJUhi+4vWCwUQHQRpdXYoVe
HJj8CBZ4WaDPVtI1yCHsfMc2QZ2snTjc5gVdmnHdl/Oo6lB8IgRMrs5d07NOqjKajoLdfwUqKNAj
Lc0g+s541h3hd9AhEfmNmzxtpwoTKf1Z31KwskiEEGgHIBqXwNCzTazH60SZTmp2rBAujsRoQkkf
q34MQot6pFkXnwIqGOly2mKni/07AO62xaeKlBDXGuJThYHiDAUz6vXkO9k6qtMEPMtJe0hddN/0
lQEzSGEKypsnfCt9RcdzVFtUT2Ev96xE3OI8jp8ojIwytim0vxCofyM+AQQOqp34rQ3R78AcMN4O
CqdOAcQ0X6P7F/l1gBJFjuBBXX4hhpgw6eBWmvjxmB8FwhDrwEyHGw9hKRDDo7rYKVeQOzyWAL2r
gyo71XbcrYHSptMutZfRkiHJtIhpNlMeaR+xbTjACz3Ptp74BAQMR+skAeAmF2s8v1lM8SVbElVf
IPcu8vVkltHsiE9I/qdTxZiSjptrizRDcPsjvvP1k9KG0aWHI0ogVpoFVXFWiIq+63FyYtDpySBM
pKN5Iz5ThOilepH2fBnDdu1qTspaYjC2cCymGFgVDJSRKsVUCumoL0sXhrNNOykzsRm/n17O04el
i6syvimYpbtiN6kyOFXwAS9RWsGNwN3veuzaZtJhqVQTgnSVN2YJbJdGVspIiw3xr9AMApvCPDD/
4eZDkRxMc3HCkz6w3GxFmeLiQjF9388mpbNgAly7Yi+mHBG9aqtfrWtX449Ld7ShurWW7juwp3GA
AQPamru9uiW+/4QplzBJg0k/aYhbLwlqyZf387l2yzdeZMsNAJh4fXWbPmKMST4/BKt28jwBncOT
aSQVA17ql/TldjG5SVDx+dPb5G0+vR2/v0vf5pM0z3wuwoCYvpjMtflsmrxO5bkk4qAISK1lDCpM
4lF0FmTpfpCDH2PusfvgerQfTo29i1KVmMLUc4wA0mp4Vgemrn/H09IKHHfN9GnXMfAo+a6RaSuN
XZzdOaEHX2wBKF88l+PuCgPtlkoVIz5VUGyHSABMfBDsLbnHN0GjKfbl14VAsMKJD647IEuRjHS0
GtVet9tTHovInrvJsDvVZqvVUh4ldhi7gQ2zNxgbttDxg3q1029J5PQlQ8fzna/ELrQ8Pxpx5sk3
MqrJnxl0XWAEFJh9G6Pttpgjk5SRJ3ZR4dM1xWmATbYlhhiG9UXwsRi+nfHH1C7RzqK21eoPBrze
H/Aub3dWjU5v0OuYnK+bhtkDy9rlA6vXbbJvv663RO3UOZNY+cDYU/6tiAsOsQwhlesuwI98/HoH
5rI87rbZ+fKrFOH9zTTZNEjeHp1Wx/mlEW6T79KMHwBA56AoFEp13FlN+NeGfx0Wbo0GfjTBQcav
The/Wn166zSaDLQz31ngByZP3bp8Qlzx1AIP6WlrB47veQ6MmA0PIEOlJR+79fRx0EwfAaGdIbQz
BCja5esgll9YzAaVC35oFH/2mIHeYavJzMBMPlds7T424A2/DPkNvjG9wvdnzzAitjWgS0TlxCNV
TjxS5egRuJE+dropAlU5zdbOsrWzbO0sWzvL1smydbJsnSxbJ8vWYdihuHMw+S7tWAI85rUlbYbO
FiqWbumqRkoig8q5LBfxcvTh7NVutQY9+GEBIiuiqqmNjnBlwUlNY7bGIXPlq9USgeOkWiwNp+Sj
+suzkJYg6LjOg+F+thk5G2KkyZM7tGQAGuSsggJnbhktjSHhVYxnWED14P7xLWfvb+/ZBA8GBEzs
gHfYVFwcMbFNKJ+nlQS2VfO8Ov9s+AYMFv6GBaTdwpPMEzjnnovh/XhnvGHocJKDyjJPxT2d5VGN
tQ+qna9TXQlzE0/thRlEip50qV7o0txsOEFGf0rHHcfoCeemrgkG+gJ6GoJ/oWxCzgLyr8fGM+uP
aYCbVNr/Paew9n8aPkYoqBm1ZwpyL/8E7u2b1+AohX1FKCLN4yRLUAjmcYQSlz0qiPgFXSR66hS/
wxiewAmIOAX8DTM61aeQkZRj9lQqtgKky1FVhqH6StUOemAj3wZ3UDhP9WajifNCqU9gzJm2v5WR
EbyJRENbQQo7sD+DJ8EdSomevLUNNsoIzDUeQiRU1O2O92APegryoEmnFwPfiUP2BCqCrRzvCTPj
BgOYzDILOj3FJ5MF2BhbBc1ipNjQInuzM1hgNhmuO0LjIJ9ac5x9inqvTGauV8yMAsbNFXPxxfXg
A/8JvcS+ckSKlVLD2XgBeFu78PSkUKJTjU5jAi5t2yKVhU/X5ZsdHDxMQkv8iSOmqJjfeMc4iIjg
yhSLADZAyRPbFQGQOnp7xkm4zK0mfRWviSFVsaZI0QdQQskkKZuN5tD8rCZlSIljl8Q0jvRaHjnp
hFar3k2+D5GeXk0vuXPolegYE3gRmaKiCZ/vXbnhJveSw83z6YUMeP7LdaHXDnSahHsyGOO5IsZm
6T5W5nAqLwVUeTymo35zUVYPSQL9MFEXS5dODsups5JMDg3uEpEgPBaogJNNSyIwypLQUrs+6OLk
xjiAtJq9bl+ClFW7VqPTEofQLoGNODTALimHitO4QwaV537zSDTPB2uSmLWake5GSo5tZ2ytUKBS
p71cFbyJQhc4OsF118ABqicH7Esw6OhjigBDHRRSugMoK8lWezpfX1C86DOFeiiFsJ4kgLhxKN6S
ib5Be3RVvCSpiCnjGuTN4BoA6IujIMn+g1J170EX9MvB3FufhOMKvlyAeBlvbXPH0sHjMV7GDVC9
nUDCtWWDloNCH/qAn0Sm43FyUSiHp3JbN7PjKSVcB04dgwCTjoEU/pxEyVhzEg24cgxeZMgxPIUX
EgVykKIG+ni9gc0T8+WChjsBBHmz+LMeh6lIrkgIC4khWqp8XqErcA2PR0laXJrqh/qR5HJ8WtSD
JHGdSBnEDwuEJOMgDx5tlItb2ShTEDyXFtNycNzuoq95RHYA1zJ0cWBR1uAlLD9UMdIWEYpJ3k8J
oVK0PKVcWTlCae5Xomd8fimD0levQP0qunjOxAtURAPy4i2LJexJQXmWhA+275dmSCApvun5ezTv
dOBDxxOtVikE/AqMrytQ0iCSDXrkeXoIZTkpmPwKPYxNPO5cSF0btoOn5HKpNg1BZTTlvBOUz3Ki
wlXVMyoFQOYRleDwZ7lETnejyMR03VxNtOwwKT+HC4bTtiyH62A+EqaoCGkJ64BzqWOK5RyC0lxh
tDtSuQMIeA86xz7wTJ3O65aky7P8CsA8ksE8lgFXXUtzJIDDLNQ+szT1APlIA47V/0j1j9X+WOWP
1r206uU15zDxdK3YP0A/lg4ZjuEXk8nN0TEgkuoNN05HWwl0ZZ/ICs7m3j5Fm1aRj4Mhr9igcRR8
qmKbk3CLm3amtEoQ1o5nnMrvxSuHn4DLBbxy6B6831N8271A+TQGQsFZ3vknOJ/uUjrCPsdbHYdy
N96doM1P8G3DPfDJxJJQOQbdTpUDr2zXCPbHJbIAL8pkAVwmlQWUQ7ksIBxK5iHC6SpuXsAok88C
yqGEFmkcymgRoyilBfiBnB7wcvci/ZdwyqW12COH8lpkaVFiC/ADmS2WwE/yslRuCziq5OIhrdRQ
Jx5uTtfmMNBVKcABBE6+rb5SFmuVQ+BpnfBdzHrwNiElUVx3lc9oBZ6fTwnQUor9ezIlueNNTcrN
wWWivGwGo2ueWmzOrVIRH2zFg9tlu54StKyr8VURIIGNVzPhEAOPP9fMg3kYpkIf4e4/K04FjGiK
rd35xMTxyqb2gi9yc1foGI88xwvwjORUppgse7yYjJuvaBE/O6+gQFUvK02EPuHRIZ3klu0ihGQx
xy1wINwjYQHwRsQW9pwHfxTLz6KwdMA4fTiyeI3XsNChkcvZmJ1PeeCw7AZhNuOb2AH1Mn5O4mrh
m9KYNWVPdhIoIb5+tdWmo2hao6k1vnJpDOtWTRfksg2ODbGbWHmUuEA4pqKLuNkTtXUrztPg95AO
dI0Cc4s1KuMRYrHx3xZqEJ5uV5EgDIvlVk0buJg7/3jLguL2h85qvWr2+v1+o7Fq9Ru83zebPau5
ajTNZn3QWA9apsWtjomxTKSt0c5NOjKGqy9YxfyOqMUrcP5+PX0RZ/PF9tXL4HLAFQCbRWiycszO
YYxHONvzuenUVl+ab5bunc9px1B4eJouw8cVPdycGIa4gJf0BxNV9fA2MCPAUwG67JwK8wI0ySAv
JsYk/AjP9l3BeN+z+dZY2w9VSQJ/l2XPcEzYX8QJwPegIDCc+pYbj3JF+gYYEYfsrceDDQ8wK57D
wOkgnlMDKun1cGJpNX8CrVmvtzT4GOCOJfYXnLF/oRuuvkK6oapyI2FiC45smEVEPMBC16rlljwk
iK7E1mkjSQ5Mm23tZ7HXpyCLDWttDAaDHrd63X69zTstc9DgdZP3u811q1fvdRu9VRd/0IHoyAsp
8Pljfhw06oJ+cotQ/u1Y7P8rLxqim9rwKob04Yg+k7c90OU/4rFUX+Guuon8KqWUHlEOxellsPkI
qbA7MBnBdSQu0KqAhiSV88izpDnnD4irpPjO3UrEvuhlHtNF67jUlx7fGtExpCzPKAiMfeH1Tt7P
/taw3skdkpcwlMbPOBroijSA3NDlqoX0S7wn2N1k9C7l5lqxcStLT89hK0ke3nmhEBvv/EiB49Hn
kC5ayqXlyL4Hzy97u3bFAXk15RE3lI2CTYxDTikswclwJ9zdRFsFZYLKXoF7G9tUwDfymrQM49ab
8Sdb5Tb06t36LZ7OD5WclDpDj0VNhF4Et/5JSZoaeJ+jIhSFLKmQFDo1TT/oHgVS3k8pQkmHpbCj
mQ6ZmoJoU2BJ+iLgXE3OY8HwAA9QaTJI+RVObfa4MsytCWg4SkRhwf256Usi0/T6zC1iEb1+4IZP
Dze2mz0bz+mzyDoXV/9TyjSwcc1+/9eYxyIle5pHBt5NCU8LvvPVou9x61GhS+8x7kYBVVLXKYR0
jLitjtTHXyf4WKpCEtjOs2KHqz6CvOQuQVG3YLaq/Wq72vo6R0lWqHpw8u/YPoTktjoqZu8aO9pc
JSpR6t7hOYTIY8nBhNxBhK86WYzbuqKqkWKLsyopYCWJp0eERXJyFODEUV6BCJYQ3G7+aJRRwUsr
5bQlLRbP+MqdV3h/ky6u0g3V3Pk1ffU0ZrcuPpfu6fMceFg64OIipWpyZNm4AJO6roDqkE90ucdF
GJgVDK9fVGieCLOIi6/DlocQYEi40SkZSO/ioyP7ycsRaymv6UseYfzTHbZoHl/YiETX+mE+vI0M
v0HOfhrdTMq3NYqh8vHAnU4y5Qg3qu2vkz6sQhUvt7S4jAuo/axC8wEPFSHZyIa3g+OvAB1DwBVB
0QFN+shDxTXMOEGqi09sCF0KAQ677eeYkt26UfSfjIG1anS7Zr81WDXb5oqvTHCnBp1Gs76yOq0O
76Gf2l+j/4RU89OUJrIPGPslD6FrMmnf5xe67kTu7i/rLnnzxCe8/0ZM6HPXYQxrtRRHmKL0cgrb
XePdABXxBiPMoYMCl+JYr1VylkDYkdJDBq8XACot3YqYm9DkjreUo2UH97LDeSrqi0ffcne8CFkn
T1WK/S2MaHwdu4924LnoCJG/LY8JIS3ZjtHt1ezu+kqf3d3R8fya8L+AS+P3o8uf9PnibjZ6PxYg
+dM4fEfXMVg1h28Mcw/F3NxPRovxVYKtz+/uZ5ci086NauGWO06aDWjf3U31m7v728X07vp2keJ5
q1UJscVo9n68KK1BVv+3UP/JnTjcgqP8Sp9cv52NZj/p09HigzgsDhrZo/PiQ9lKcQsPzMjHs9vR
pLSt8meAQK/dTK+uZ2Uw9WdeItzBn9RJ/P6Z/mW/8URwaJDBrkaLERHDWAuYxaSSIWiTYVJVepZV
DdUX9fkZXjK6o/l8vJgrPVmDEQXg+fiyjOMwRTaXLjLvcgJZs2qIvGQa6Ke7cNtT9TP+RFIJyA3F
zsVyuPeA+3aPZg649jkGH/4Iwgp/pGSPO0WdYxUAZ+UIJH16Cd48ghBxh/tbz93Le62OoD16tn8a
Y7cLTyPI+weqvufY5v4IEs78bDCVx2j4dDH5M1iHcoQnvsLfdDG34GTY8Q6xMtGZzu6m49niJ/3T
3ewvIApiAPcrIPwgPXe3VziaysZIslM6VMZjCV56o0xyWPGIStLn49nH8ezn5ZmqnJZn/8jppwwr
r6lSvGPKKst4RG0lFMo0l1JqXoepmUiNnShGKLRjFS1jQKLdZJ5GriJ5VZeQPabtlHoV9F6xQqnq
y7IIJXgE8UAPHrYjpxElmUEZIqrHpBihITMctZW/Vl0eligUZ17KhO5UcPNaVO1zoUgz1JxKLVD9
Q6v+L9CqhxJ2qF+lXJCKzfAPlG1xvKn6tmSMlWbKDaAPU3iZvHvFOD78ycNcTS9n19OFfju6Gf9W
tN5dT8a/CT0cd/piNrqdk/L9b9O7uru8vxnfLlRjpMJn47/ej+cLfXF9M9bfTe5GCVLyG/SdbrVd
b/WO5TnAVhHxkgmJQFGtpXuOv53B2M/1X9UsWibJkTcV0zK+/fiS8RUoX2t5Ra5fY3ZleS/Z3CMF
vGhw8y0usbay/K80tbI6r7azAv8rjWy+7scsbB6rxLwKhN/EtubLOmFYJeKLVlXg/WFS/7eb1Lxg
vWBPBfLXGdPCWDpiScU0Rh4hLlxSauPvxnHO8KdWn4yA/4A/t0g/vohXJCeHlPEHiICPNfzJT/z5
RVCOkJIdXIYq7cLkmlOlMGZASXiCGbfi43J0An8feLGPv+lp5X4xkn6ZLikVw1MyDc/FDRmbXF+O
b+fjg5tWCweqZaat53P5M3hR+jNiccjXsVPBMwkR+3S9+IDXPI5uf2KfRjMwvouffmDyCn7GQZUQ
IdptjD85Z4Atc6M9NHTp3oxnlx8gw+jt9eR68RP+2NO768XteD5n7+5mbMSmo9ni+hI0+4xN72fT
u/mYTmxfr4nDlm3RmSu5kYV+TNLfqyx0BAtx8R/P2QOKC2yny5Zosd5YYSUzTNvdVJjv0E8oguaI
DDNKaPwZb4x2eQQVOPvlvwAhXI7H
===END CRASH DUMP===

**Comment by robske110** [comment]
There is another server running
Stop that server and close this issue
If you're on an VPS, try to completely restart it or kill any php processes

**Comment by thethrill999** [comment]
How do stop the server your saying I just made my first server

**Comment by robske110** [comment]
reboot your OS

**Comment by thethrill999** [comment]
Can you make more detailed cause I'm just a kid and I don't understand what your saying

**Comment by thethrill999** [comment]
And sir why can't I join my server?

**Comment by robske110** [comment]
Please open a thread on forums.pocketmine.net

**Comment by robske110** [comment]
And keep this issue closed

**Comment by PEMapModder** [comment]
Please don't use the issue tracker as a forum. If you need any conversation that are not about a valid issue, please do it somewhere else.
