### ISSUE TITLE
pocketmine does not open!

### ISSUE THREAD

**Issue by leem919** [PocketMine/PocketMine-MP#4106]
### Issue description
whenever I type ./start.sh, it will say Couldn't find a working PHP 7 binary, please use the installer.

### Steps to reproduce the issue
none
### OS and versions

* PocketMine-MP:1.4.1
* PHP:?
* OS:Mac OSX el capitan
### Crashdump, backtrace or other files
none

**Comment by Yuns92** [comment]
You have download the PHP 7 binary.

https://dl.bintray.com/pocketmine/PocketMine/

Download the latest version for your system and put the php7 folder in your_pocketmine_folder/bin.
