### ISSUE TITLE
Sword glitch

### ISSUE THREAD

**Issue by duyphuoc123234** [PocketMine/PocketMine-MP#4110]
I can't use swords to hit players in my server. HELP!!

**Comment by robske110** [comment]
Is this occurring on a vanilla server (without plugins) too

**Comment by duyphuoc123234** [comment]
Dia swords don't  work on normal server and the other plugins like SG, 1vs1, too

**Comment by jojoe77777** [comment]
Are you using the latest version of PocketMine?

**Comment by GlitchPlayer** [comment]
Yep, this occurred to me only bow and arrows are working. Tested on vanilla PvP server

**Comment by jojoe77777** [comment]
> Yep, this occurred to me only bow and arrows are working. Tested on vanilla PvP server

Is pvp set to true in server.properties? Are you in the spawn-protection radius?

**Comment by GlitchPlayer** [comment]
PVP is on and spawnraduis is set to 0.

**Comment by icsmoke-mcpe** [comment]
Set difficult to 3

**Comment by GlitchPlayer** [comment]
then it will set to adventure mode.

**Comment by GlitchPlayer** [comment]
Ok, So in a leet server where PVP is enabled is swords are working.
