### ISSUE TITLE
Unknown. Nobody was in game.

### ISSUE THREAD

**Issue by HalcyonLeuthcorps** [PocketMine/PocketMine-MP#4111]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files
PocketMine-MP Crash Dump Tue Apr 5 03:01:20 CDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 90112 bytes)
File: /src/pocketmine/nbt/NBT__64bit
Line: 509
Type: E_ERROR

Code:
[500] 			}
[501] 			return $this->buffer;
[502] 		}
[503] 
[504] 		return \false;
[505] 	}
[506] 
[507] 	public function writeCompressed($compression = ZLIB_ENCODING_GZIP, $level = 7){
[508] 		if(($write = $this->write()) !== \false){
[509] 			return \zlib_encode($write, $compression, $level);
[510] 		}
[511] 
[512] 		return \false;
[513] 	}
[514] 
[515] 	public function readTag(){
[516] 		switch(\ord($this->get(1))){
[517] 			case NBT::TAG_Byte:
[518] 				$tag = new ByteTag($this->getString());
[519] 				$tag->read($this);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #23 [Protocol 45; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT WIN-TI5CJTKGA7Q 6.1 build 7601 (Windows Server 2008 R2 Enterprise Edition Service Pack 1) AMD64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWWtv20iW/Su1SoCxB6IsSpZkq+EG3LY745nE8cQKsujWwCiRRYljksVmFS0rjfz3PfdWkaId
92CxOx8mCRDV6z7PfVTx955Nc9Wbh8eT05Pj8ehk2O+pqtJVb/57z+5KLPWu7q8+ffr4qdfv5coY
uaa58yzTWxWLXOW62gmTflVCJyIczsaz4/BkdCxWO6uMUE8bWRuLnQe2SvGf1ULibCStEqfDMBy5
jYegnqQZkT4yVXRU6uhB2Twt1FGxskc3Py3u76fHq9RiX4bZ3nwyPP3W75VZvU6L3jyRmVH9XqRj
RZJPhkNQWlr6+w1HJsOwHVfK1lUh3tpNaoIfV3WSqOoH3jPye9yJMUb849hP+4PLJTNzRya85g5M
mwMznizrVZZGIqmLyKa6ENsqtepC52UFK6r44G3kf9Pimfjl/fVP91c3Fx8vr2/e3b/75fq2L95m
6lFlWJwd/s6UT7woaXJw8JYJYtFrwsODw0PxX2dnjZD+2OlL5ZfLr1m6ulcFGcxTAruORA3zQ9Yz
HHZNE4Ze03D0x6YJx3vThMfNgcmrpqmUjBdyfeDEDaeeqtmmNtocLJe6grmclmtlD8LDQ79z1ioW
SaMEYDKfL87f3f8ETM15x0m7Y2nfWrmGvQq1FbSBOO6p3gGfBUTwCp++OBf8SEK6/dgC6NlKRgDb
r703Q3FwOBd7yC6Xd6p6VFXwY1RJs7ms8/JgpXWmZHHY+0e/t1aFqmRGQMUusjaYhYNprB7Be1Wn
Wdybj8ZAd6WtjjR2Hk/6PVmm2DcaDAdDbFsjFua94f/yDw5U8gE+pzODE6ZQF5JCv/clLWK9NeJm
Ib5c3wSL68nFXxd/e3c++7uYDkLB8ojZdBiKg2ar00+MhsMT8WkkrgqrqrJK4YKrOGWX0o40UuJW
Rg8iPBTnHy6nx2BabkqwnEGJMUZfVQFVe2OvExbvtSGRrm9uFpjgwRYB3oa6IatdqscF7Mm/vRLt
VP+ZTUNHWNZ2oytD3rplN32Am8RCyZz8wYb91VsWY1XIVaYgmK1qJJVYlRCTDmPN6MRedidySfmn
5b9cdiTJtCT17hbnnxafbzGxVSuDUMPcxtrSzI+O4MZNvRog8o72kh21NL6R4rKCjrBwIwIbfwBw
lKqyqSIbvbltR+JCF0m6FpROl9WyePMB7jgvK3EswtP5+ATIEheXCzgvnNK6IxeQHc8+FzHcutjA
j+BXyExc6lx1dpW6smfhaTge0eRaUv6P1dmQRrl8CspM7iDo2YhnTCm3RUAoVhzoZ47jdgMbBFlq
7JlOEppxFg9+q1W1ezFXRTinC5qhn4NSGrNFQjj7M/8BW23jM7Iagi2xc3F75eFJR2RRaGQZ5QUL
ZLRJkdZyVVjjqVI52gZJlq431k85uWWR5khnz+ZyvWomEl2BbmsCL/VGVnGkq3ZcPpbNzzhNkjSq
M7s7c9bjNGB1FRhlLZKPOaNpTrvOHdAzi/dzRqm4s4XK89nl1c/nn98vWJHa6sDIR+UFpIBqc9Jg
l2eEE/EBeBURQ6QGd4pVQoqAOmKPwODDLZBDSEBMN+IJWSlhAQ5dAGZ2I62IyMBWrJRIiyirY1R4
kP8OoUTrDkiiHsF+T9PIBOVHY6UyRFKskGwfxE7Xlacl0kTAzGmSMgdYuAKksh0RvkE+b8gdxSqR
MLERW138yQpZlkpWgkyTQ9kIzt5BfEFp3Om93ahC1OW6kjEIDJYFYd0Rmy8L8WaxqRTAiilIkcli
XaMDElQ32WQ+LkyKMbU1WfqVjUpHLzYq8lo8PwgBmvhXxWCbPqSlilM50NX6iEZH7xEb9zq5v777
eD8dnwajezoHM7aE5mKJPLVe9ojRl40i21FzZZCZqMMShusZ3FTJwmTSut7LW5MlhRz4pSy7FLWH
0vVGFnHGTs5B2EF8z5KrO+bNpraoAwgH1xCSML4kRJlGc+PE4iZRUJxDEuHzt3hMpfg7BTq2cMAH
fmUuKN/SwbsNzklCqUHVFJ6Lc5X0hERtAELkZgCBtTu/vcZO5PmY7LRfCCDWCkLtyV9xZmnoQGNB
ESsAVyCCRF3thMcRtvs81K7uzfDmSwpD6wKQknGMLsY45JGYwNoDxJGmrjjbCOBtpcgeMLr6rUZq
hTvW6SP2PsqsVuLAs0RiPgRxxw/5T1HODeDN9VpVc6wS55s6X8HaCKdzsyuihTQPQHz1gAAa0Ppn
OIHx2ShJuzaVRjYEJLDb9AVnF+GzELd83Y6UzIJyRXN5XSByaAvTvmPIQB8EV6WfkCStggmgDkO9
aEUjqzpxrhOKUG7+EYl9kdo/wXK24lOxovLAKHxxVhxAA/hZjMgirEPgtZwzJYpWdwXhWH2X6RUM
SzW6uZlkaZ5aykm5Wku+agzEnRNlyMxTQ+51kQ6dtikLxsYWVBgcncb+hu2SpIAL0hTScMGkEuSI
hqNzP5SpGbRrDT00hQbZDHzWLGTAgs3FcMmpgrOy3VCP+R8uPvU7/0J4qn//L+GN1SXz96mqlcdT
MwIhRU0AsoyXhng2IoXD0bGT6lZVqeZyRLFoiGHECdlL18ZbCFZINTFhjHcEiAflIo3TuC6QwBCh
sBtlhz8yqzMnmpuMMzzFutu25IJLNBB9+0h26Yg4fKQUQhWOtw++30xq+64UJixVRIXQsFlIVmdj
d7ZVAJZUpdmrOR56Pc3hqwJ5rcdO67WsVvB/gNtH5po3irBXrcpwIlH8GeHPIHZzWdRccrtSoB2p
6crfb3LCCzB4NLi8itu5zw35HmUD8dHVOx4BERtdZ3ErSIoMsi3EXnTCrShZcig4xX2IdRRvfuZI
+C43Mlbc6VappNJ5k2LprF8Pulmp41Mo4V33Egqv4KdzjproaFMXD8bZ+z2jnhIiT5JkdKsgbYTr
afscnhUaEOM2BdQDUC+zp0WkGjf7QDmdejkvtTv20n1UBKhTcse6FBwXv+3foDMXoiBCb66c1h4L
DSNaaKv3vyS1LAplyRdt6wZoZK4SrqRF80+NiKQuFwUQePJZiQPQNaZ+1SWjlWprIqebN9301axQ
4Fc7S7T7Igg7YKbax2wD24iCtDKZuqyyr7Xumaemms3pzjvQncWkl2kg/oJLCsx7hl4YwL24/dzH
WUiwQv7ZprHduKzN8d2SD5j8XMx8Y7BvGQwbprN1IM5jxNNGZskRmnzXxcQKOPOMwNLhTxfdgGyr
c4dWp0+6eqLgozZIZn0X2MTYvyYMBGCjGNpU6z/fFrdNp7Dv2akJokNb5PolNexFGfhhtyfDLUut
6rVzv/Y5U1C1qBjQ6klFtWt2KPnQ+8OgXTWECO5hyk05SIuUxAh9//KjCKlv8UWKGlTm1DSnfJbS
lG9al96rc0fAtZxGHBkrbQ3sHa0j5yWkyNh05G+ues+uIKrpR8kEMIq7fPFWj1SyHGMngj8sg9Uf
CdyRucixtPZXEyjEjxskLtALvHN+k8/oIwnT5c522MMg9ntpONwZBW9uPi6u5oITOP5FNe5pBe5p
TCjNy4ybYRbPc27Fa9Fy/szxEa4kSEpeVwYkVzdIQgC0BMLR0FcjyoquyBEi6T5M876y+QTyfLpJ
h66tvqPIJwVX9Jy4Z3YQIuZe4dIXIyyEry0oGw0OOf6N6krBcFgQZbql+fcSoZDjHD/qIpwn+T68
vyhTTuELFTVilFlktpU742h7Oh0cPSsFDKPzXNdFt5YY3/41QpD4RI1uH0jz9HMujv/4qKwwGzvZ
HY3nBUyEp6NXTzO6CuWupCvlqK1UQkmN31ko+ZEbWqru9aWTRV0SvZOPiG5qFVO6eSu6yZU7/8rg
y1rbG3HOSaSxbFW2i8+ISZ3xNm0A1YBCNI1cVeLbXEVXewADZBtT/VPTpcrFhpE5YSXntEu1qtX/
hTPIoI0zPsgnIV/aBdepiEvNHg/PfcEg/STjtDadY94P0kvHQeqOetzRfjQ+lJPolSuoyxhY3AuI
W7uSjgk/y+0LqhN8f0dsZB98L7zPf1uZ8nUfV/taef/68xz2PB/QB6O5OPk/USt1WWeemv9NVe4F
4WXBMRnAeiS0e8wLGEeGLEmmzJGrLb3e+NnQpwd6RJsL1yc2LqXX+7pE3+SaRwdITh6uZ/G0QGVG
pzxDIjqh4VYSo3aS52S+SoF8t8W/37nr/twlI3qZoC8Iws26cu1B4tDrLwVtciNcB/RW9HymLSfP
ZlHl0iLRexhsNPmeWQ46T4foqVi+Qhe7nG4MHCEG9jWtoHQF8stiv8wCA2tSyPUa1ce/M7QvONRu
0neUh9e1cfIQOfOaPGQvB2V28cvTwIRbnTsHVEXgi/O+meRZXXbeni7o+ZHfw1SmS6pWfYyhAT32
2aarQ5OToOlWMDbqU0F1njb50lqTdxCPHSLCf5Xo9BA1eldjXYFrEp6nRh5yyw1988Io2+32NZNk
KcqN88rVk6R66wbUsIC+F2LeSMNLADtduufiV/oZoMj0+Rb+D6LosmDThnQfblmJ5urh7n/Ngzb3
Vq+9A/M9mauY4Y6B1M7RSKQQ1Jf4jujMlQXgX4Levyl0uSTtuc3Fz+/PF/PRD7P+5PQp7I+fxv3R
D+EPMSqxy1oHtlIYIMOcnQzFGvg2bnQ8OeR3cvVkVUEG4U9KF6hDnY9UqwjdyKYzQW+nRSyr7pT/
Vt6MCXadYZJmAGlnYoMQ4w9U9HUqpVaos/hP479eHfMy+rZdaTvrd7fvO6MyeibtJ5X421tn0riW
vDtjJakQd6bynfkt4+9x/peYYCUcBYCxCOh70WR4PJzh59tr+CGZnKrVbDpLVDiT0+nsdHJyuppE
w9k0Pk3kyUk8jo9RxobiLWhb/aAKpOauDb6mpftGN2Y1v7qvk80qRk/8yaI1qc7p8+dwOA7D0Skm
bi8/dpZvN+wQ+og3Ihtxs/nfH7qWek5vG8dPzxfpJvNMQszxp/Hu3BclHxD8/B11zKzQ5GYvzZh2
TY2hVWM+MQvcR17DoWu6x1buxb4ztZMsMH+X/HQxI1/7Fw/+ZhoOpsRd5/extkgAnZPrrl9/oTry
8ZbrmJ+ekhg/X/W+ffsfFHSuRw==
===END CRASH DUMP===

**Comment by GlitchPlayer** [comment]
Memory Leak

**Comment by PEMapModder** [comment]
Allocate more memory to your server. Please, read the error message before creating an issue.
