### ISSUE TITLE
Water Bucket Missing From Creative Inventory

### ISSUE THREAD

**Issue by jellyfishcoder** [PocketMine/PocketMine-MP#4116]
### Issue description

Though several items are not supported (redstone related items, which is understandable), the water bucket has previously been supported and is necessary in many instances (you know, when you wanna make a lake, but out a fire without having to coat the world in a layer of blocks, etc). In survival mode I believe the same issue is present, but have only tested it using /give command. The only workaround is lengthy, going into survival mode, running /give yourname water, which gives you 64 water blocks (cant even get it to give me a waterbucket with command).
### Steps to reproduce the issue

1. Set your gamemode to creative
   `/gamemode creative`
2. Open your inventory
3. The water bucket should be under tools next to the lava bucket
### OS and versions

- PocketMine-MP: 1.6dev [REDACTED]
- API: 2.0.0
- Protocol: Version 46 (also in previous ones)
- PHP: 7
- OS: Raspbian 4.1.13-v7+ (armv7)
- Plugins: Irrelevant, this issue occurs with or without plugins
### Evidence

Photos:
![img_1735](https://cloud.githubusercontent.com/assets/6530647/14336076/32cd9182-fc26-11e5-86a3-667dd4478e1e.jpg)
![img_1734](https://cloud.githubusercontent.com/assets/6530647/14336085/51b99442-fc26-11e5-81ce-c79a1b2609af.jpg)
### Note

This is not a duplicate of the issue #4091 because I am not missing the villager nor the lava bucket in the creative inventory.

**Comment by Subtleoliver** [comment]
Water isn't the id for a water bucket..... Water_bucket is the water bucket id

**Comment by jellyfishcoder** [comment]
@Subtleoliver I used water because in survival, you have to refill the bucket each time and water gives you 64 blocks to use.

**Comment by wildhuman** [comment]
@jellyfishcoder Just ran into the same issue, thanks for posting.
