### ISSUE TITLE
PocketMine Segfaults on any dedicated machine with more than 32GB ram.

### ISSUE THREAD

**Issue by Renual1337** [PocketMine/PocketMine-MP#4117]
### Issue description
Okay so basically on any dedicated server I try with more than 32GB ram PocketMine segmentation faults, I tried it on a Virtual machine with 64GB ram and that seemed to work. I've tried both boxes at LimestoneNetworks & OVH, same issue.

### Steps to reproduce the issue
1. Well all you really do is run it, check the run log below.
2. It instantly crashes.

### OS and versions

* PocketMine-MP: The newest one that the build scripts installs (I'd do version but it doesn't stay on long enough for me to do it)
* PHP: 7.0.3
* OS: Ubuntu Twisty 

### Crashdump, backtrace or other files

https://gist.github.com/Renual1337/2f020058cd844145e16f1a6b5f3754a0

**Comment by PEMapModder** [comment]
So your decision is, it segfaults on 64GB RAM or doesn't segfault on 64GB RAM?

**Comment by Renual1337** [comment]
Hello,

On a 64GB ram dedicated machine it does, on a 64GB virtual machine it doesn't.

I know it sounds extremely weird, if you'd like I can email you the root login for a machine and you can check it out yourself.

**Comment by Renual1337** [comment]
Would that be okay?

**Comment by PEMapModder** [comment]
"Dedicated machine" and "Virtual machine" do not really have any difference. It seems that it is just a random PHP installation problem rather than a systems-specific issue. Try reinstalling PHP on your virtual machine, using installer scripts provided by PocketMine.

**Comment by Renual1337** [comment]
Hello,

This is on a clean install with the installer scripts, please do not close it, it's a serious problem.

Can I give you a login so you can see it for yourself?

**Comment by PEMapModder** [comment]
Try running the server with `gdb bin/php7/bin/php` `r PocketMine-MP.phar`. This will show more details about the segfault.

**Comment by deotern** [comment]
Yeah... I'm having this issue with a Dedicated Server too... But no with VPS...

**Comment by deotern** [comment]
What does this mean? I got this error:

> Program received signal SIGSEGV, Segmentation fault.
> 0x0000631c1e829a9a in malloc_consolidate () from /lib64/libc.so.6
> Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.4.x86_64 nss-softokn-freebl-3.16.2.3-13.el7_1.x86_64
> I tried `debuginfo-install glibc-2.17-106.el7_2.4.x86_64 nss-softokn-freebl-3.16.2.3-

13.el7_1.x86_64`, although it solved the above segmentation fault, it gives me new error:
Program received signal SIGSEGV, Segmentation fault.

> malloc_consolidate (av=av@entry=0x6dba1bbbe760 <main_arena>) at malloc.c:4149
> 4149              size = p->size & ~(PREV_INUSE|NON_MAIN_ARENA);
