### ISSUE TITLE
NPC are immortals

### ISSUE THREAD

**Issue by GlitchPlayer** [PocketMine/PocketMine-MP#4120]
### Issue description

Write a short description about the issue
NPC are immortals, meaning, they can't be killed.
### Steps to reproduce the issue

1. Spawn a squid
2. Try killing it.

### OS and versions

* PocketMine-MP: PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
* PHP: 7
* OS: Windows 10 PRO 32-bit

### Crashdump, backtrace or other files

* ...

**Comment by Subtleoliver** [comment]
Mob AI isn't implemented yet. It doesn't handle health and such.

**Comment by GlitchPlayer** [comment]
Yes i know but in previous version on pocketmine, you can kill animals.
Like since 0.13.0

**Comment by jojoe77777** [comment]
I assume you have Slapper installed; it's a glitch in the current Slapper versions.

**Comment by GlitchPlayer** [comment]
Oh yes, i have slapper

**Comment by GlitchPlayer** [comment]
I just report this on right section

**Comment by jojoe77777** [comment]
(You can get a fixed version of Slapper from https://github.com/PMPlugins/Slapper )

**Comment by GlitchPlayer** [comment]
Thanks
