### ISSUE TITLE
MCPE 0.14.1 not supported

### ISSUE THREAD

**Issue by skywalker-z** [PocketMine/PocketMine-MP#4127]
logged out due to Outdated server!

**Comment by jimtbob** [comment]
This issue was brought up before and closed, I installed PocketMine-MP 1.6dev-23 phar per the previous issue - still can't get onto the server (MCPE v0.14.1 on iOS or Android says outdated server)

**Comment by jellyfishcoder** [comment]
Here is a phar http://pmt.mcpe.me/pmb/dl/pr:4115.phar Its from a closed pull request but it works. They denied the pull request because they said it didnt make all the changes for 0.14.1 BUT ATLEAST IT ALLOWED IT TO BE SUPPORTED.

**Comment by jellyfishcoder** [comment]
Just realised that is old link. You have to compile it yourself. https://github.com/PocketMine/PocketMine-MP/pull/4115 is the pull request. Ill upload a phar when I get a chance.

**Comment by skywalker-z** [comment]
@jellyfishcoder  As you pointed out the link no longer works. Can you upload a phar please? Kids are waiting ... Or can you share instructions about how to compile the pull request? Thanks.

**Comment by jellyfishcoder** [comment]
@skywalker-z Here it is: https://drive.google.com/file/d/0B0wvRQEqnhujN1k4eTBBbFhHWmc/view?usp=sharing Be sure to rename it to PocketMine-MP.phar before usingit.

**Comment by jellyfishcoder** [comment]
Also the water bucket is missing in creative in it.

**Comment by jellyfishcoder** [comment]
When I figure out how to compile PocketMine from the source into a phar I will put together a bunch of pullrequests and and make a phar with all the features I can fix in it. Ive found fix for the creative water bucket and for some other issues, and made them into one resp, but dont know how to compile a phar,.

**Comment by skywalker-z** [comment]
@jellyfishcoder Thanks for the help, but the phar file doesn't work for me. Any idea?

.\start.cmd
Warning: require_once(phar://C:\PocketMine-MP\PocketMine-MP.phar/src/pocketmine/PocketMine
.php): failed to open stream: phar "C:\PocketMine-MP\PocketMine-MP.phar" SHA1 signature co
uld not be verified: broken signature in C:\PocketMine-MP\PocketMine-MP.phar on line 1
Fatal error: require_once(): Failed opening required 'phar://C:\PocketMine-MP\PocketMine-M
P.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in C:\PocketMine-MP\PocketM
ine-MP.phar on line 1

**Comment by jellyfishcoder** [comment]
Hm, ive not used windows but it may be an issue because it has "/" in the phar instead of \. Though I dont think so since its supposed to be the same phar no mater which system. Do you have PHP7 installed or PHP5?

**Comment by jellyfishcoder** [comment]
@skywalker-z I can try to email it to you if you would like. Its a exact copy of the PHAR my raspi is running.

**Comment by skywalker-z** [comment]
I have PHP7 installed and I am using Windows. I'm also puzzled by the error message " SHA1 signature could not be verified". My email is forumwalker@gmail.com. Let's give it another try. Thanks.

**Comment by skywalker-z** [comment]
@jellyfishcoder How did you generate the phar? It is 2810kb, much smaller than the v0.14.0 file (3869kb) downloaded from https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar/view#files.

**Comment by jellyfishcoder** [comment]
I got it from this link on a pull request. The request was closed because there were "more changes" than what was in it, but working mostly is better than not working at all. Im not sure why it is smaller. I wish I knew how to generate the phars, but I dont sadly.
https://github.com/PocketMine/PocketMine-MP/pull/4115
http://pmt.mcpe.me/pmb/dl/pr:4115.phar

**Comment by skywalker-z** [comment]
I made it to work by removing the phar file and putting the src folder in PocketMine-MP root directory. Need to clone PocketMine-MP, raklib, and spl repos. Then make the a few changes in the pull request manually. After that start.cmd works. Kid can join the server now. 

I am still hoping for the official release. This is just a hack. Thanks @jellyfishcoder for all the help.

**Comment by jellyfishcoder** [comment]
Thats cool. IDK you could run it without a phar. And I doubt it will be official any time soon sadly.

**Comment by TheEpicCooldeal** [comment]
I'm using Genisys which is a "fork" of PocketMine, it updates the server for 0.14.1 and also allows you to edit some cool shtuff! :D

**Comment by jellyfishcoder** [comment]
@TheEpicCooldeal Just wonderin ,can I just replace the pocketmine phar with genisys phar and it will work?

**Comment by robske110** [comment]
yes as long as its php7

**Comment by jellyfishcoder** [comment]
@robeske110 thanks, ill try it now

**Comment by jellyfishcoder** [comment]
@robske110, Thanks so much, this is great. @skywalker-z you should try genisys phar also. It has mobs and evrerything, even redstone!

**Comment by robske110** [comment]
And if you want compatibility with old plugins, use ClearSky, it's php5 (you need php5 bin folder then)

**Comment by PrimusLV** [comment]
This is PocketMine!

**Comment by TheEpicCooldeal** [comment]
It is....

**Comment by PrimusLV** [comment]
Keep PocketMine forks away from here

**Comment by TheEpicCooldeal** [comment]
.... They work at least .....

**Comment by jellyfishcoder** [comment]
Yeah, when pocket mine works Illstop looking for a working alternative, until then, nah😌

**Comment by robske110** [comment]
And why?
Ok, they destroyed this project.
Thats true.
But as they already destroyed this project, what can we do now?

**Comment by TheEpicCooldeal** [comment]
They didn't... Funny story .... I just got it yesterday ;)

**Comment by robske110** [comment]
They did

**Comment by TheEpicCooldeal** [comment]
You're getting the wrong one.....
