### ISSUE TITLE
Mac/Linux server not starting

### ISSUE THREAD

**Issue by Artemis-E** [PocketMine/PocketMine-MP#4134]
### Issue description

Server will not start on mac/linux ./start.sh calls for /mcpe/bin/php7 folder. The download contains bin/php5 folder.

### Steps to reproduce the issue

1. ... renamed folder to php7 and started, will not bind IP address. 
2. ...reinstalled and changed the calls in ./start.sh to php5 starts but will not bind Ip address.
3. ... tested on hosted server same results
4. ... even when server starts I'm not able to connect with any devices

### OS and versions

* PocketMine-MP:1.4.1-9800
* PHP:
* OS:Mac OS X 10.10
not sure which linux host is using.

### Crashdump, backtrace or other files

* ...

**Comment by robske110** [comment]
Download PHP7 builds
