### ISSUE TITLE
Plugin commands sometimes not working on iOS 

### ISSUE THREAD

**Issue by NoBakaCookies4U** [PocketMine/PocketMine-MP#4135]
### Issue description

Issue with plugin commands on pocketmine for iPad.

### Steps to reproduce the issue

1. Download a plugin from the Pocketmine website.
2. Start your server.
3. Watch in frustration as some plugin commands do not work.

### OS and versions

* PocketMine-MP: dunno
* PHP:dunno 
* OS: dunno

### Crashdump, backtrace or other files

* Nothing else to add, some commands just say "unknown command use /help for a list of commands"

**Comment by GlitchPlayer** [comment]
Lol, please do not report plugin issues in here. Report the plugin instead in their plugin repository.

**Comment by jellyfishcoder** [comment]
Do /plugins to see if it is even loaded

**Comment by robot56** [comment]
A server log would be helpful to clarify if the plug-in is loaded properly in the first place. Also going to assume that it applies to all plug-ins and not just specific ones based on your description.

**Comment by NoBakaCookies4U** [comment]
The plugins are all loaded in, it is just that some of the plugins'
commands do not work

**Comment by extremeheat** [comment]
In that case the plugin in question is probably not registering the commands properly. Should not be an issue with PocketMine, talk to the plugin developers.

**Comment by Survingo** [comment]
pocketmine doesn't support iOS
