### ISSUE TITLE
PocketMine is DEAD because working PR's never get merged

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#4137]
Its one reason noone creates PR's anymore:
They never get merged.
I have pull requests that are more than a half year old.
There are even pr's THAT WORK PERFECTLY which are way older.

@PocketMine Really.. Start approving the work of friendly people who want to help you.
@PEMapModder Left because of this reason.

What do you think why many players prefer forks like Genisys, ImagicalMine and ClearSky (sure, there are more!)? Because they have way more features, the joining (for example with 0.14.1) works, worlds load better, light bugs are mostly fixed, Performance is sometimes way better and almost all blocks are implemented.

I really like PocketMine. The API is great, and its fun to play with others, but not, if the core is way too outdated.

We, the guys from the ClearSky Team, are currently trying to figure out what would be usefull to PR to PocketMine. For example: 0.14.* joining, windows 10 drop item bugs, crafting fixes, light issues improvements and even more. But it is useless, until the PocketMine team will finally merge PR's again.

I hope i could make up your mind. Or isn't this a community project anymore? :smirk::stuck_out_tongue_winking_eye:

**Comment by PrimusLV** [comment]
Thanks for not forgetting PocketMine
