### ISSUE TITLE
Intre Blocks Off All Opinions by Users #2

### ISSUE THREAD

**Issue by jellyfishcoder** [PocketMine/PocketMine-MP#4143]
> Thanks` @Intyre, YOU are causing PM to die, because you don't accept users oppinions. Same in thw Forums. You always act like a ######. 

SO TRUE!!! But you should listen to reasonable comments and helpful discussants, don't just lock everything that people care enough to comment on. But, without the descriptive word about you.

**Comment by robske110** [comment]
Go to forums, please
