### ISSUE TITLE
Servers issue for Pocket edition on iPad

### ISSUE THREAD

**Issue by NoBakaCookies4U** [PocketMine/PocketMine-MP#4152]
### Issue description

I cannot join Pocketmine servers on my iPad

### Steps to reproduce the issue

1. ...Connect to a server using _Plug_ _PE_
2. ...The server does not show in _Minecraft:PE_

### OS and versions

* PocketMine-MP: PlugPocketmine (1.6.54)
* PHP: I don't know
* OS: iOS iPad

### Crashdump, backtrace or other files

* ...nope

**Comment by jojoe77777** [comment]
Most likely a problem with Plug Pocketmine, which is not related to PocketMine.
