### ISSUE TITLE
Sever crash

### ISSUE THREAD

**Issue by shanethegamer142** [PocketMine/PocketMine-MP#4155]
In the log it said
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Stopping server...
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 20:38:29 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 20:38:29 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 20:38:29 [INFO] Loading pocketmine.yml...
[Server] 20:38:29 [INFO] Loading server properties...
[Server] 20:38:29 [INFO] Starting remote control listener
[Server] 20:38:29 [INFO] RCON running on 0.0.0.0:19132
[Server] 20:38:29 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 20:38:29 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 20:38:29 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 20:38:29 [CRITICAL] **** FAILED TO BIND TO 0.0.0.0:19132!
[Server] 20:38:29 [CRITICAL] Perhaps a server is already running on that port?
[Server] 20:38:29 [EMERGENCY] [RakLib Thread #1081130280] RakLib crashed!
[Server] 20:38:30 [INFO] Loading JoinCommands v1.4.1
[Server] 20:38:30 [INFO] Loading Lightning_Strike v2
[Server] 20:38:30 [INFO] [Lightning_Strike] Preparing For StartUp... STAND BY
[Server] 20:38:30 [INFO] Loading MoreHealth v1.0.3
[Server] 20:38:30 [INFO] Loading RealTime v2.1.1
[Server] 20:38:30 [INFO] Loading RestartMe v1.2.0
[Server] 20:38:31 [INFO] Enabling RestartMe v1.2.0
[Server] 20:38:31 [NOTICE] Memory overload restarts are enabled. If memory usage goes above 1200M, the server will restart.
[Server] 20:38:32 [INFO] Preparing level "sever"
[Server] 20:38:32 [INFO] Enabling JoinCommands v1.4.1
[Server] 20:38:32 [INFO] Enabling Lightning_Strike v2
[Server] 20:38:32 [INFO] [Lightning_Strike] Lightning Strike RUNNING Made By MichaelM04
[Server] 20:38:32 [INFO] Enabling MoreHealth v1.0.3
[Server] 20:38:32 [INFO] Enabling RealTime v2.1.1
[Server] 20:38:32 [INFO] [RealTime] RealTime enabled.
[Server] 20:38:32 [INFO] [RealTime] [RealTime] It is 20 (20h is same as 8pm)
[Server] 20:38:32 [INFO] [RealTime] 6000
[Server] 20:38:32 [INFO] Default game type: SURVIVAL
[Server] 20:38:32 [INFO] Done (3.779s)! For help, type "help" or "?"
[Server] 20:38:32 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [98]: Address in use" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32
[Server] 20:38:32 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 20:38:32 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Wed_Apr_27-20.38.32-UTC_2016.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 20:38:33 [INFO] Disabling JoinCommands v1.4.1
[Server] 20:38:33 [INFO] Disabling Lightning_Strike v2
[Server] 20:38:33 [INFO] Disabling MoreHealth v1.0.3
[Server] 20:38:33 [INFO] Disabling RealTime v2.1.1
[Server] 20:38:33 [INFO] [RealTime] RealTime disabled.
[Server] 20:38:33 [INFO] Disabling RestartMe v1.2.0
[Server] 20:38:33 [INFO] Unloading level "sever"

**Comment by shanethegamer142** [comment]
Also my mcpe version is 1.4.0

**Comment by TheDeibo** [comment]
You are attempting to join a server for 0.10.5, with a 0.14.0 device? 

A big no no. 
It simply won't work.

And also you can't use Win10 with a 19132 server ( Win10 runs with 19132.... )

**Comment by shanethegamer142** [comment]
How do I change sever version?

**Comment by TheDeibo** [comment]
If your device is 0.14.0, then look at this --> https://bintray.com/pocketmine/PocketMine/download_file?file_path=PocketMine-MP_1.6dev-23_6ba0abf5_API-2.0.0.phar

If your device is 0.14.1, then look at this --> http://notpocketmine.tk/pmb/dl/pr-4115.phar

Change the name of the file to "PocketMine-MP.phar"

**Comment by shanethegamer142** [comment]
Thanks now I just have to fix the IP 0.0.0.0 glitch

**Comment by TheDeibo** [comment]
and if you wish to join on Windows 10, then I suggest putting the port on any port other than 19132. ( I would choose 19133 or 25565 )  
You will also need to port forward too.
