### ISSUE TITLE
Signs / Item Frames placed incorrectly...

### ISSUE THREAD

**Issue by TheEpicCooldeal** [PocketMine/PocketMine-MP#4156]
### Issue description

Signs and item frames for some reason are always placed incorrectly, no matter where the player is facing, for example if a user places when he's facing north, the sign will face south. I have tested this on regular minecraft and it placed the sign where it should've...
### Steps to reproduce the issue
1. Placing a sign..
2. Placing an Item frame
3. Placing an anvil
### OS and versions

- PocketMine-MP: 0.14.0 (I'm not running 0.14.1 or 0.14.2)
- PHP: 7
- OS: iOS // Windows 10 Edition
### Crashdump, backtrace or other files

- ...

**Comment by GlitchPlayer** [comment]
Also, Anvils....

**Comment by thebigsmileXD** [comment]
Deeper details what exactly is wrong maybe?

**Comment by KairusDarkSeeker** [comment]
The Developers are already working on it.This hasn't been changed since 12.0

**Comment by TheEpicCooldeal** [comment]
Ahem.... the signs and item frames (including anvils) place correctly on Android devices it doesn't work on Windows 10 or any iOS devices. This issue is really starting to get annoying.

**Comment by thebigsmileXD** [comment]
I don't get it.. they always placed correctly for me, i use iOS and Win10.. can you provide some screenshots?

**Comment by thebigsmileXD** [comment]
I think signs are fixed
