### ISSUE TITLE
How can i update pocketmine to 0.14.2

### ISSUE THREAD

**Issue by super1030** [PocketMine/PocketMine-MP#4160]
I updated the phr but i got this

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [CRITICAL] You must use PHP >= 7.0
[Server] [CRITICAL] Please use the installer provided on the homepage.
[PocketMine] Server was stopped.

Can some one help me

**Comment by extremeheat** [comment]
All the things you need are available at https://bintray.com/pocketmine/PocketMine/.

Download the appropriate PHP binaries and put them into the server directory. If you need help, ask on the [forums](https://forums.pocketmine.net/forums/help/). This issue tracker is only for issues with the source code.

**Comment by super1030** [comment]
How do i put it in the server director

**Comment by Survingo** [comment]
All PHP binaries are in \bin\

Also don't forget to update the plugins!

**Comment by LordOfQwerty** [comment]
How do you install the php7 file "PHP_7.0.3_x86_Windows.tar.gz"

**Comment by garet90** [comment]
Download WinRAR from http://www.rarlab.com/download.htm, then you will be able to extract it into \bin\php.
