### ISSUE TITLE
Server overloaded issue?

### ISSUE THREAD

**Issue by NoBakaCookies4U** [PocketMine/PocketMine-MP#4163]
### Issue description

1. ...Join a server with PlugPE
2. ...Says 'Sorry this server is overloaded/c/line'

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...
![image](https://cloud.githubusercontent.com/assets/18544814/15037447/6017d1f0-12da-11e6-95a4-b0e87b49a551.png)

**Comment by GlitchPlayer** [comment]
PlugPE is not a PocketMine property.

**Comment by NoBakaCookies4U** [comment]
I don't care, it is still a Plug Pocketmine server

**Comment by jojoe77777** [comment]
> I don't care, it is still a Plug Pocketmine server

Nothing to do with PocketMine, PocketMine doesn't even make those messages.

**Comment by legoboy0215** [comment]
@NoBakaCookies4U Why do they call it Plug Pocketmine? It is not even pocketmine. IT'S an APP

**Comment by KairusDarkSeeker** [comment]
@legoboy0215 becuz it uses pocketmine's api!

**Comment by jojoe77777** [comment]
> @legoboy0215 becuz it uses pocketmine's api!

It is **based** on PocketMine but has been edited.

**Comment by legoboy0215** [comment]
@KairusDarkSeeker What @jojoe77777 said is true. They **HEAVILY ** modified it.

**Comment by GlitchPlayer** [comment]
Instead, contact the developers

**Comment by NoBakaCookies4U** [comment]
How?

**Comment by QwertyPrism** [comment]
@GlitchPlayer How do you contact them?
