### ISSUE TITLE
14.2 Help

### ISSUE THREAD

**Issue by YanSoo123** [PocketMine/PocketMine-MP#4164]
Im sorry if I'm spaming, but I'm a noob. Basicaly I have 14.2 and I want to install Pocketmine for it, but when I get pocketmine its always 11.0 or something old. So basically I have no support and that is my issue, please guide me through the full process of windows 7

**Comment by robske110** [comment]
https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar/view#files/

**Comment by YanSoo123** [comment]
Thanks, so if I install it on Windows it should work? =)

**Comment by vnguyen972** [comment]
Yeah, that and PHP 7 and it should work

**Comment by YanSoo123** [comment]
PHP 7 is on the same webpage as he suggested

**Comment by YanSoo123** [comment]
Along with the installer and these files?

**Comment by robske110** [comment]
Look:
-Close this issue
-Install pocketmine with the old installer on pocketmine.net
-replace pocketmine-mp.phar
-replace the bin folder with the php7 bins

**Comment by acemtp** [comment]
Easiest way is:

`wget -q -O - https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/installer.sh | bash`

It'll get the phar, install php7 and so on.
