### ISSUE TITLE
Crash on Furnace/Furnace not Working Correctly/Doors Not Appearing

### ISSUE THREAD

**Issue by p4rsec** [PocketMine/PocketMine-MP#4170]
This is sort of a multi-part issue. So I was running a server for someone on my ThinkServer at home; easy to connect, ops work, everything works thus far. However I was informed that once a furnace was place, and attempted to be used, that it crashed the player's game. I was also informed that doors would place, but when closed would only show the top, and when open only the bottom, and then they would disappear entirely. Upon further investigation, it appears that using anything but coal and a cookable meat yields the furnace to not even begin "cooking". As for the doors, from my POV, everything seemed fine. I tested on a separate world using MultiWorlds. I also noticed that my game began crashing upon entering the furnace interface after we began testing. 

**Steps to Reproduce:** 
1. Place furnace
2. Attempt to add coal
3. Attempt to add say cobblestone or a log
4. Nothing happens
1. Add furnace
2. Leave game
3. Rejoin
4. Attempt to use furnace
- PocketMine-MP: Latest
- PHP: 7.0
- OS: Ubuntu Server 16.04 LTS on two quad core Xeons with 20GB of RAM (ThinkServer RD120)

No crashdump available from the server-side. Thus far no further testing has been done, however if need be I can do so.

**Comment by TheIcyStar** [comment]
I can back up the furnace issue. The lag with adding items into the furnace is occasional, and the crash happens when you try to access a furnace **after** rejoining the game. The only way to fix this is to break the furnace and place it back down.

Pocketmine-MP: last three versions I worked with (0.12.0, 0.12.1, 0.12.2)
Server hosted on Windows 10, 8GB ram, i7
Client: iOS

**Comment by p4rsec** [comment]
Ah, Client.  I forgot to mention that the only tested client was iOS 9.x and that I am hosting PocketMine 14.2.0 (if it follows minecraft version numbers). On another note however, no issues with the doors? I'm wondering, because the user who was reporting the door issue as well as the furnace issue (however the latter is reproducible) is on an older iPad that happened to get iOS 9.x and I was unsure if it would be a client side issue or not.

**Comment by p4rsec** [comment]
I'm under the impression no one really cares about this issue?

**Comment by TheIcyStar** [comment]
Pocketmine is horrendously slow at merging things. It's sad, really.

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
