### ISSUE TITLE
Regarding the PocketMine website

### ISSUE THREAD

**Issue by DiegoGTRatty** [PocketMine/PocketMine-MP#4171]
So https://www.pocketmine.net/ hasn't been updated in quite a while, both in the stable installer aspect, and the current development build files. Is that site still being worked on, or is there somewhere else I can install a dev. build for PocketMine?

I am aware this will be deleted because it's a question but I can't seem to create an account at the PocketMine forums.

**Comment by RocoWayne** [comment]
im migrating my server to imagicalmine 0.14.2 php7 and updating all my plugins to php7 (downloaded from github and the pocketmine community)

**Comment by andrewwipf** [comment]
I agree, the web site needs some serious updating!

**Comment by gaoyichuan** [comment]
Use iTXTech/Genisys xD
