### ISSUE TITLE
error when setup 1.4.1 on windows xp

### ISSUE THREAD

**Issue by enight0000** [PocketMine/PocketMine-MP#4176]
alert windows vista or above required

pocketmine does not support winxp ? Or it's a bug?

**Comment by extremeheat** [comment]
- You're running a really old version of PocketMine
- Windows XP is no longer supported by Microsoft and PHP dropped support for Windows XP since 5.5, PocketMine now requires PHP 7.

Upgrade to Windows 7+ or use Linux.

**Comment by enight0000** [comment]
thx
PocketMine-MP 1.4.1 "Zekkou Cake"
@shoghicp shoghicp released this on 18 Mar 2015 · 690 commits to master since this release

this is a old version?Where can i find the new one?

**Comment by extremeheat** [comment]
https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar/view#files

**Comment by enight0000** [comment]
Wow, thx really!
Is it development version? Where can I get source code?

**Comment by extremeheat** [comment]
... the source code is on this repository; click the Code tab.

The phar on bintray contains the latest changes which may not be 'completely' stable, but stable enough for most uses.

**Comment by enight0000** [comment]
Alright, I will try to run PocketMine on my Win2003 Server, wish me good luck......
