### ISSUE TITLE
Cannot connect to server due to difference in protocol.

### ISSUE THREAD

**Issue by loveyanbei** [PocketMine/PocketMine-MP#4177]
### Issue description

Write a short description about the issue
I created a server on my computer but cannot reach the server.
My phone kept showing me generating the world and then disconnected due to time out.
Console output says:00:56:50 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
00:56:50 [INFO] Loading pocketmine.yml...
00:56:50 [INFO] Loading server properties...
00:56:50 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
00:56:51 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
00:56:51 [INFO] PocketMine-MP is distributed under the LGPL License
00:56:55 [INFO] Preparing level "world"
00:56:56 [INFO] Starting GS4 status listener
00:56:56 [INFO] Setting query port to 19132
00:56:56 [INFO] Query running on 0.0.0.0:19132
00:56:56 [INFO] Default game type: SURVIVAL
00:56:56 [INFO] Done (5.9s)! For help, type "help" or "?"
01:00:20 [INFO] [/10.0.0.29:19132] logged out due to timeout
01:04:22 [INFO] [/10.0.0.29:19132] logged out due to client disconnect
version
01:10:23 [INFO] This server is running PocketMine-MP version 1.4.1-980 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)

The version of my MCPE on iphone is v 0.14.3
Looks like the protocol version of server was left behind
But how can i solve it? Downgrade in Appstore?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:1.4.1-980 
* PHP:5
* OS:Windows 10

### Crashdump, backtrace or other files

* ...

**Comment by samalero** [comment]
you must update server to 1.6...

**Comment by GlitchPlayer** [comment]
Also, look your PocketMine version and your mcpe version... They are different!!!!
Your Pocketmine = Mcpe 0.10.4
Your MCPE = 0.14.3

What the hell man??

**Comment by Subtleoliver** [comment]
You're running an old version of pocket mine. Go here: https://forums.pocketmine.net/threads/latest-phar-and-php-binaries.16037/ and follow the instructions on how to update(watch the animated gif)

**Comment by DiegoGTRatty** [comment]
@Subtleoliver The instructions are helpful and everything, but since when have non-animated GIFs existed as well, or what is the reason for saying that the GIF is animated, or why did I bring this up in the first place?

**Comment by PrimusLV** [comment]
He is just trying to help, be respectful.

**Comment by TheDeibo** [comment]
@DiegoGTRatty Non animated gif http://i875.photobucket.com/albums/ab317/Springlight620/Restless%20Nights/Beach-Ball.gif
Animated Gif
http://www.animatedimages.org/data/media/418/animated-ball-image-0049.gif

theres your answer.

Back on topic. 

if you want a nice upgrade tool to upgrade from old PocketMIne to new, look at this awesome tool, by this awesome guy I kinda know.

http://forums.pocketmine.net/threads/pocketmine-1-6-php7-installer-windows.15493/

The PocketMine.phar is either 0.14.0 or 0.14.1 on there, but you can easily fix that by replacing it with the latest of https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar#files
