### ISSUE TITLE
DoubleTag Chest

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#4180]
```
    static::$default[static::DOUBLE_CHEST] = new InventoryType(27 + 27, "DoubleTag Chest", 0);
```

in InventoryType.php

**Comment by legoboy0215** [comment]
I believe this happened because shog tried replacing all NBT tags from Double to DoubleTag, but he forgot to revert this.

**Comment by jojoe77777** [comment]
There's also EndTag Stone somewhere ;)

**Comment by legoboy0215** [comment]
Yah. I actually made a program so it actually fixes all of that.

**Comment by thebigsmileXD** [comment]
There is even DoubleTag Plant :P

**Comment by PrimusLV** [comment]
Naughty "search n replace" function.

**Comment by SOF3** [comment]
That's confusing. He could have used PhpStorm of older versions (that do not support PHP 7 yet) to refactor class `Double` into `DoubleTag` directly :confused:
