### ISSUE TITLE
unused / useless $pk 

### ISSUE THREAD

**Issue by thebigsmileXD** [PocketMine/PocketMine-MP#4181]
$pk = new MobArmorEquipmentPacket();
        $pk->eid = $this->getHolder()->getId();
        $pk->slots = $armor;
        $pk->encode();
        _$pk;_
        $pk->isEncoded = true;

in PlayerInventory.php

**Comment by SkygridRex** [comment]
you dumb

**Comment by legoboy0215** [comment]
@SkygridRex What? Are you kidding?

**Comment by thebigsmileXD** [comment]
I am dumb because i didnt even make that mistake?

**Comment by SkygridRex** [comment]
2 words Third Reich
@thebigsmileXD you are funny because criticism to PocketMine, Genisys, ImagicalMine, etc ... when ClearSky uses code taken from these projects, still ClearSky is the most incomplete server software

**Comment by extremeheat** [comment]
How is any of this relevant to the issue?

**Comment by SkygridRex** [comment]
@extremeheat it's not of your business ;) (my apologies if i make you feel bad, its because i have bad feelings to thebigsmile)

**Comment by thebigsmileXD** [comment]
@PocketMineTeam Can maybe someone ban @SkygridRex ? I feel offended and this is no chat.

**Comment by extremeheat** [comment]
Github issues is not a forum. _Do not use it as a form_. It is for issues with the actual source code. 

Comments should be make relevant to the issue at hand so contributors can resolve the issues brought forward.

**Comment by SkygridRex** [comment]
Ok i will delete this ;)

**Comment by SkygridRex** [comment]
Be happy
