### ISSUE TITLE
install fails on OSX

### ISSUE THREAD

**Issue by jeffrey-guy-lyon** [PocketMine/PocketMine-MP#4186]
Following installations instructions fails:

/var/minecraft$: sudo curl -sL http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Tue Mar 17 10:00:47 MST 2015
[+] The build was signed, will check signature
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar...bash: line 202: PocketMine-MP.phar: Permission denied
 failed!
[!] Couldn't download PocketMine-MP automatically from http://cdn.pocketmine.net/api/update-stable.phar

### OS and versions
* PHP: PHP 5.5.34
* OS: OSX El Capitan 10.11.5

**Comment by SkygridRex** [comment]
I think this could help you:
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#installing-on-linux-macos
Need more info? Visit PocketMine forum
https://forums.pocketmine.net/threads/latest-phar-and-php-binaries.16037/
