### ISSUE TITLE
Cant join my server by myself

### ISSUE THREAD

**Issue by boerke123** [PocketMine/PocketMine-MP#4187]
### Issue description

Write a short description about the issue
I cant join my plug pocketmine server everybady can join but when i join the server says server closed thanks for playing plug pocketmine servers

### Steps to reproduce the issue

1. ...
2. .

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by robske110** [comment]
Please close this issue
