### ISSUE TITLE
install fails on win2008

### ISSUE THREAD

**Issue by enight0000** [PocketMine/PocketMine-MP#4189]
After the install program as well as the micro setup, I open the start.bat, and see
"
Unable to fork [wmic timezone get Caption] in phar://E:/PE/PocketMine-MP.phar/src/pocketmine/PocketMine.php on line 202
"

How?

**Comment by enight0000** [comment]
Warning: exec(): Unable to fork [wmic timezone get Caption] in phar://E:/PE/PocketMine-MP.phar/src/pocketmine/PocketMine.php on line 202

**Comment by PrimusLV** [comment]
PocketMine, PHP to be exact, doesn't support Windows XP and lower.

**Comment by SkygridRex** [comment]
@PrimusLV It's windows server 2008 theoretically it works

**Comment by PrimusLV** [comment]
My apologies, I'm not windows user.

**Comment by enight0000** [comment]
I've got it, it's seems only a warning, server continue start up after waiting a  few seconds

**Comment by enight0000** [comment]
well, how to close the issue?

**Comment by SkygridRex** [comment]
With close issue button
