### ISSUE TITLE
Chests cannot open in Creative (not in line with latest Minecraft PE)

### ISSUE THREAD

**Issue by eddiegalvez** [PocketMine/PocketMine-MP#4190]
### Issue description

In creative, players cannot open chests. This used to be the case for Minecraft, but in the latest official PE release, they can be.
### Steps to reproduce the issue

Run latest dev build, creative mode
Chests cannot be opened
### OS and versions
- PocketMine-MP: latest dev build at time of writing
- PHP: php7
- OS: osx
### Crashdump, backtrace or other files

n/a

**Comment by SkygridRex** [comment]
It doesn't implemented yet

**Comment by TheDeibo** [comment]
Just because it is implemented within the app, doesn't mean it is implemented in PocketMine. :)
Remember that.

**Comment by eddiegalvez** [comment]
Right... so isn't this then a feature request to get that implemented? (isn't it technically a bug if PM doesn't match MCPE?)

**Comment by TheDeibo** [comment]
No. It simply is a idea to see if PocketMine will or will not implement it. 

You see, some people think, doing that is cheating, which I can sort of agree. So, Its up to the Pull Requesters and PocketMine staff to decide.

**Comment by eddiegalvez** [comment]
I see. Guess I see PM as an open source, minecraft pe server implementation, and as such needs to line up.

For data points, my users look at it as a bug, because of course official behaviour is the standard, right. I did research enough to understand this is a recent change, didn't use to be this way.

**Comment by TheDeibo** [comment]
I guess you could say that. But I am no representative of PocketMine, I am just making my own point.

**Comment by daniktheboss** [comment]
Genisys is able to open them

**Comment by dktapps** [comment]
This has long since been fixed on PMMP's PocketMine-MP.
