### ISSUE TITLE
Where is latest pocket mine .phar download?

### ISSUE THREAD

**Issue by Pandaken** [PocketMine/PocketMine-MP#4192]
Where is latest pocket mine .phar download for version 0.14.3?????

**Comment by Pandaken** [comment]
If possible can you comment the link/download right here

**Comment by Addison118** [comment]
https://bintray.com/pocketmine/PocketMine/

**Comment by Pandaken** [comment]
what do you do on this website?

**Comment by extremeheat** [comment]
Github Issues is only for issues with the source code. Use the PocketMine forum for other things. This is not the place to ask how to install PocketMine. There are many other places that tell you how to do that.
