### ISSUE TITLE
ARM_7 PHP7 build is missing

### ISSUE THREAD

**Issue by marcdraco** [PocketMine/PocketMine-MP#4197]
In the main installer, when a (generic) ARM_7 board is detected it tries to d/l:

ARMV7_BUILD="PHP_7.0.0RC3_ARMv7

But that build is not available on the server.

Right now I'm having "issues" building PHP7 too - but I'll file a separate report about that with a relevenat logs.

**Comment by SkygridRex** [comment]
Did you need it for your pc or android device?
