### ISSUE TITLE
Compile fails on some ARM boards

### ISSUE THREAD

**Issue by marcdraco** [PocketMine/PocketMine-MP#4198]
Using:

`wget -q -O - https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/compile.sh | bash`

Incorrectly identifies my Armbian (Orange PI PC) as a generic Intel 32bit. I have managed to compile PHP7 using overrides suggested in the forum.

`wget -q -O - https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/compile.sh | bash -s - -t arm7 -j 4 -l -c -f arm`

Full log here: 

Linux orangepipc 3.4.112-sun8i #8 SMP PREEMPT Mon May 23 22:19:17 CEST 2016 armv7l GNU/Linux
make is /usr/bin/make
autoconf is /usr/bin/autoconf
automake is /usr/bin/automake
libtool is /usr/bin/libtool
m4 is /usr/bin/m4
wget is /usr/bin/wget
getconf is /usr/bin/getconf
gzip is /bin/gzip
bzip2 is /bin/bzip2
bison is /usr/bin/bison
g++ is /usr/bin/g++
wget is /usr/bin/wget
gcc is /usr/bin/gcc
gcc: error: unrecognized command line option ‘-m32’
rm: cannot remove ‘test’: No such file or directory
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting

**Comment by Intyre** [comment]
Something about wrong repository issue tracker.
