### ISSUE TITLE
player movement bugged and most players crash when attempting to join

### ISSUE THREAD

**Issue by XFuryMCPE** [PocketMine/PocketMine-MP#4207]
No one appears to be moving.. And almost everyone is crashing when they try to join .-.

**Comment by XtremePlayzCODE** [comment]
Have you updated Minecraft: Pocket Edition or PocketMine-MP?

**Comment by robske110** [comment]
I can confirm this with latest commit and 0.15

**Comment by dktapps** [comment]
Same issues on Genisys. We've collected together a list of issues [here](https://github.com/iTXTech/Genisys/issues/1180)

**Comment by TheDeibo** [comment]
I have a way to temporary fix this issue (It may also work for Third Party Versions of PocketMine too.)

All you need to do, is delete ALL player date from the /players directory/folder. 

If anyone wants to confirm this, you are welcome to

**Comment by Awzaw** [comment]
I checked that, it doesn't help

**Comment by MichaelM04** [comment]
CustomAlerts causes a issue too, when it was enabled it would make the players crash on join(error listed below appears), once I disabled the plugin it would only show a "Disconnected From Server" screen. Still doesn't allow anyone to join :/ . The issue with CustomAlerts is that it uses $protocol1 when $protocol1 was removed and its now just $protocol. Should be a easy fix I'll experiment once I can get it working.

**Comment by MichaelM04** [comment]
Okay my phone finally let me connect on 0.15 on a test server I had to sign out of Xbox live for it to work (clue?). Indeed all you have to do is change the $protocol1 to $protocol and customalerts works fine :) . Bug wise all I see is a hand glitch
![screenshot_2016-06-17-06-48-29](https://cloud.githubusercontent.com/assets/16037546/16149839/03964560-3459-11e6-8726-7958d302c6a5.png)

**Comment by TheDeibo** [comment]
Hmm. Im connected via xbox live, and that works for me. The thing that triggered the server to work for me was deleting player data. :/

**Comment by trekinsanity** [comment]
I just updated PocketMine to version 0.15 (on a Mac OS 10.11.5). Every time players join, they get booted out (on login). I have removed the players folder, stopped, and started the server. Same results. Any suggestions?

**Comment by ctalbot2004** [comment]
It's probably because there are mobs near your spawn point, which crashes Minecraft.

**Comment by MichaelM04** [comment]
@ctalbot2004 Indeed, after further testing mobs are what causes crash on join. Is in no relations to Xbox live. And also mobs do not update on move and leashed. All already referenced, backing those up.

**Comment by XFuryMCPE** [comment]
These have all been fixed on Genisys, check them out

**Comment by MichaelM04** [comment]
Even running latest Genisys (2 hours ago build) I still get client crash due to slapper's

**Comment by craftyc0der** [comment]
We are still crashing constantly. Our world works for about 10 minutes before our app crashes whenever we enter the world. Deleting the player and sometimes the world is required to get it working again. Also, we generally do not see the other players moving. Each player is basically alone in world even though other players are also logged in.

**Comment by btarno** [comment]
I don't notice any crashing.  In fact it seems stable to me but none of the players are moving even though they actually are.  Running pocketmine 0.15 on a linux server.  Connecting with ipads clients.

**Comment by ChaostixZix** [comment]
I Have The Same Issue, Player Disconected When Trying To Join, I Solved That By Deleting EssentialsPE Plugin, But None Of The Player Are Moving 

Im Running Pocketmine-MP 1.6Dev For MCPE 0.15 Alpha , And Connecting With Minecraft Windows 10 Edition

**Comment by ChaostixZix** [comment]
![screenshot_14](https://cloud.githubusercontent.com/assets/19998246/16339997/d4b89598-3a4f-11e6-9a54-7640161e4e12.png)
This Is The ScreenShot Of An Indonesian Server, Player With Lead Are Not Moving, But Player Without Lead Is Moving, 

My Question Is ,How To Remove The Lead Automatically?
Because The Lead Came Automatically Too When Player Join
