### ISSUE TITLE
FloatingTextParticle not working

### ISSUE THREAD

**Issue by 0929hitoshi** [PocketMine/PocketMine-MP#4209]

**Comment by PrimusLV** [comment]
Pictures, proof, way to reproduce the bug?

**Comment by 0929hitoshi** [comment]
@PrimusLV  

![screenshot](https://cloud.githubusercontent.com/assets/11427110/16114166/d675dbf8-33fa-11e6-866a-5c1def15acf8.png)

**Comment by Gamecrafter** [comment]
Tested and confirmed. The particle spawns (hence the shadow in the picture), but the text does not show. @0929hitoshi is this correct? The particle spawns, but the text is not visible?

**Comment by jojoe77777** [comment]
Just did some testing with other entities and it seems that the name is visible only when you look at it. Don't know if it can be fixed server-side.

**Comment by Muqsit** [comment]
Same problem over here, just like @Gamecrafter mentioned.

**Comment by jojoe77777** [comment]
@Muqsit Everyone has the problem. Don't think anything can be done server-side to fix it.

/lock?

**Comment by PrimusLV** [comment]
Maybe packet isn't decoded in correct way on client-side?

**Comment by Guillaume351** [comment]
MiNET has fixed the issue. (Try play.inpvp.net). So there is a way to fix

**Comment by AirLinesCraft** [comment]
Is this already fixed?

**Comment by Driesboy** [comment]
NO : IS IT CLOSED?

**Comment by thebigsmileXD** [comment]
Well, there is a "hack" to do it: AddEntityPacket, and using Renamed items ^^"

**Comment by iksaku** [comment]
`FloatingTextParticle` is kinda hacky with the client, but somehow got fixed with 0.15... Your only solution is to mess with invisible entity types

**Comment by Driesboy** [comment]
it work on genisys

**Comment by AirLinesCraft** [comment]
It works on genisys but only you can see the FloatingTextParticles and when you leave the server and join again you cant see anymore the FloatingTextParticle

**Comment by Driesboy** [comment]
It work for me
Op 4-jul.-2016 12:10 schreef "AirLinesCraft" <notifications@github.com>:

**Comment by AirLinesCraft** [comment]
Which is your plugin?

**Comment by LCraftPE** [comment]
For me, FloatingTextParticle are visible in all worlds... Can you fix this ?

**Comment by Guillaume351** [comment]
@LCraftPE It's normal, once the particle is sent, it won't move. You have to code yourself to make it appear/disappear depending on the world

**Comment by LCraftPE** [comment]
Vous pouvez parler en Français avec moi... Ok pas de problème, je vais essayer de me débrouiller pour faire cela... Vous avez réussi pour CookieBuild ?

**Comment by LCraftPE** [comment]
@Guillaume351 Vous pouvez parler en Français avec moi... Ok pas de problème, je vais essayer de me débrouiller pour faire cela... Vous avez réussi pour CookieBuild ?

**Comment by Guillaume351** [comment]
@LCraftPE Sur Cookie Build je ne la fait pas disparaître car elle n'est pas trop visible une fois téléporté sur l'autre monde, mais je crois savoir comment faire

**Comment by LCraftPE** [comment]
Ah oui comment ? J'ai trouvé cela aussi : https://github.com/Samueljh1/Darkhammer-Open-Source-Classes/blob/master/Hologram/Hologram.php...
