### ISSUE TITLE
I cant run pocketmine with the command ./start.sh

### ISSUE THREAD

**Issue by elifrogg** [PocketMine/PocketMine-MP#4210]
### Issue description

when i run the startup command, i get a message that looks like this; Couldn't find a working PHP 7 binary, please use the installer. What should I do?

### Steps to reproduce the issue

1. Run the install command
2. Run the startup command

### OS and versions

OS: MacBook Pro OSX El Captain 10.11.3 (15D21)

**Comment by MichaelM04** [comment]
Sounds simply like your php7 binarys aren't there. Our you attempting to use a php7 build with old php5 binarys?
