### ISSUE TITLE
Player Not Moving

### ISSUE THREAD

**Issue by ChaostixZix** [PocketMine/PocketMine-MP#4212]
Me And My Friend Joined The Server, My Friend Is Moving, But I Can't See Him Moving,And He Can't See Me Moving

### OS and versions

* PocketMine-MP:1.6dev
* PHP:7
* OS:Centos 7 64 Bit

**Comment by robske110** [comment]
I don't know if PM is gonna fix that, I gonna make a PR
In the meantime (until the pr is merged) you can try out a fork of PM [estimated time of merge: INF]

**Comment by extremeheat** [comment]
Duplicate of #4207.

**Comment by robske110** [comment]
Fixed
