### ISSUE TITLE
Incorrect MCPE version

### ISSUE THREAD

**Issue by jasonwynn10** [PocketMine/PocketMine-MP#4214]
This applies to iOS at least...
when I was digging through some iOS code in minecraft, I found the true build version of mcpe which is 0.15.0.3 not 0.15.0.0
I am not sure if this change would really effect anything, but I am just pointing it out.

**Comment by Addison118** [comment]
This isn't an issue. Also last I checked the version was 0.15.1

**Comment by jasonwynn10** [comment]
http://imgur.com/GgvyoWw
here's a screen shot of what I found. look at the CFBundleVersion

**Comment by jasonwynn10** [comment]
that was in a property list viewer
