### ISSUE TITLE
I can't change max-players in server.properties

### ISSUE THREAD

**Issue by dino147** [PocketMine/PocketMine-MP#4217]
I have my own VPS with a pufferpanel instalation and when I try to change max-players from 20 to 50,save the file and restart the server,max players returns to default value(20).
Please help,Can I cange max-players ?

**Comment by dino147** [comment]
And also I can't change my server-MOTD.

**Comment by dino147** [comment]
I use PocketMine for minecraft 0.15.0,the last version

**Comment by robske110** [comment]
First stop the server, then change stuff, then start it again

**Comment by robske110** [comment]
close this issue

**Comment by dino147** [comment]
Ok,thanks
