### ISSUE TITLE
Raspberry pi

### ISSUE THREAD

**Issue by daniktheboss** [PocketMine/PocketMine-MP#4218]
### Issue description
Ok I got myself a raspberry pi to test stuff out. When I got to pocketmine I followed all instructions gave perms to start.sh 777 and then when I try to start it it says can't Find a working php file! I looked all around and couldn't find any info about this.

### Steps to reproduce the issue
Just get a raspberry pi and try to install using pocketmine instructions.

### OS and versions

* PocketMine-MP: 1.6?
* PHP: 7
* OS: raspberian

**Comment by robske110** [comment]
you need binarys get them from here https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/7.0.3/view

**Comment by robske110** [comment]
Close this issue

**Comment by daniktheboss** [comment]
Thank you!! Not like those genisys people... blocked me as soon as a asked about linux... smh

**Comment by GlitchPlayer** [comment]
Tatsuki is a bish who dont care about his reputation

**Comment by daniktheboss** [comment]
Ikr! For real tho! They just make good software that's it! Most dev are not nice

**Comment by daniktheboss** [comment]
Ok I downloaded the 32bit bin file and do ./start.sh but it says "cannot execute binary file: exec format error"

**Comment by robske110** [comment]
Try this: https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/7.0.6

**Comment by daniktheboss** [comment]
Thanks!! Got it working! Nether works no problem now! Better then chuwi hi8! LOL

**Comment by daniktheboss** [comment]
Just curious... how much people can raspberry pi 3 b hold? 25 max?
