### ISSUE TITLE
SimpleAuth

### ISSUE THREAD

**Issue by dino147** [PocketMine/PocketMine-MP#4219]
I use SimpleAuth and PurePerms,and I have added to the default group permissions:
simpleauth.command.login
simpleauth.command.register

**Comment by dino147** [comment]
And players don't have permission to register

**Comment by daniktheboss** [comment]
Hmm I also use that but I never had to give perms to register.

**Comment by dino147** [comment]
But it says 'You don't have permission to use the register command!'

**Comment by robske110** [comment]
Plugin issue, please report this on SimpleAuth or PurePerms

**Comment by robske110** [comment]
and close this issue
