### ISSUE TITLE
Player not moving and automatic changed model to alex

### ISSUE THREAD

**Issue by AbangGibran** [PocketMine/PocketMine-MP#4221]
### Issue description

Why player not moving and changed into alex model pls fix it this is a big problem need fixed

**Comment by robske110** [comment]
Fixed in last commits

**Comment by adamprato** [comment]
I'm seeing a similar issue. It didn't change to alex but:
* I'm running [22:49:56] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
* I have a Samsung tablet and a Galaxy S5 both running the latest MinecraftPE
* Both players see eachother at the last spawn point, and there's some weird brown line between both players, If either player moves the player's position is not updated on the other player's view..

**Comment by ChaostixZix** [comment]
Yes , Still Not Moving

**Comment by adamprato** [comment]
Should #4220 or #4207 be re-opened? Or a new ticket opened?
