### ISSUE TITLE
Players are unable to build anything

### ISSUE THREAD

**Issue by btarno** [PocketMine/PocketMine-MP#4231]
### Issue description

Users can't build. The character is shown dropping a block, but it immediately disapears.

### Steps to reproduce the issue

1. Join server
2. Start to build something.

### OS and versions

* PocketMine-MP: server version v0.15.0.0 alpha
* PHP: 7.0.6
* OS: Linux Ubuntu 13.10

### Crashdump, backtrace or other files

* No crash

**Comment by LieLowSpark** [comment]
We are having the same issue with our server.
