### ISSUE TITLE
Rename tile -> blockentity

### ISSUE THREAD

**Issue by mixailenko5** [PocketMine/PocketMine-MP#4232]
Rename tiles to blockentity as https://github.com/iTXTech/Genisys/commit/a2f4995ce17c859d617baa7b8ba664202244b3e0 please.
For my opinion it's important fo plugin developers, because they like support of their plugins on all popular nucleis.

**Comment by robske110** [comment]
Then they should just continue to use tile. Is that do hard?

**Comment by thebigsmileXD** [comment]
Genisys fault. They renamed it because they think its correct. In MCPE they are actually also called BlockEntity, or me its not an entity and should not be a supported change.

**Comment by robske110** [comment]
And they even reverted it
