### ISSUE TITLE
HELP! MCPE v0.15.0 alpha

### ISSUE THREAD

**Issue by simba399** [PocketMine/PocketMine-MP#4234]
### Issue description

When I log on to my server using the latest development version of PocketMine from Minecraft PE v0.15.0 on iOS, I see this weird brown string going through my body. Also, when my friends come on, they have the same string going through their body. In fact, when more than one player is on, the string connects between the two of them.

Also, I cannot see players move. My friends cannot see me move. We all appear to be standing still. I can, however, see them change the current block in their hands. Please help!!

**Comment by adamprato** [comment]
Yup, same as #4220 / #4221 / #4207 / #4224 (possibly) / #4212

**Comment by ChaostixZix** [comment]
Same To Me, They Said It Has Been Fixed, But Still not fixed Yet

**Comment by Intyre** [comment]
I give up....
