### ISSUE TITLE
Player not moving from other players perspective

### ISSUE THREAD

**Issue by btarno** [PocketMine/PocketMine-MP#4235]
I'm not sure why this issue keeps getting closed but it is definitely NOT fixed as some have claimed and I am not the only one with the problem.

### Issue description
As title mentions.  Two or more players in a world.  Players can all move from their own point of view, but do not see any other players in the same world moving at all.  Also players exist in the same world but environmental conditions are NOT the same.  For example, one player see's it as a sunny day, and another player observes the same world as raining and night time.

### Steps to reproduce the issue
1. Build a linux Ubuntu server (14.04 Trusty)
2. Install git and pull down master branch for PocketMine
3. Install latest phar and php files from bintray
4. start server
5. join server from one mobile device
6. join server from an additional mobile device
7. Move the players around and observe that they do not show as moving to the other player

### OS and versions

* PocketMine-MP: server is running PocketMine-MP 1.6dev-# 「[REDACTED]」 implementing API version 2.0.0 for Minecraft: PE v0.15.0.0 alpha (protocol version 81)
* PHP: 7.0.6
* OS: Linux Ubuntu 14.04

### Crashdump, backtrace or other files
no crashing

**Comment by Intyre** [comment]
So df8e1e87 from **8 days ago** didn't fix it?
![doesntwork](https://cloud.githubusercontent.com/assets/1076578/16468929/96dd23d0-3e4e-11e6-8ac9-d8631a9b81e5.png)

**Comment by robske110** [comment]
6dev-# 「[REDACTED]」 
Redacted. Got you. Intyre changed it to 'Unleashed'
