### ISSUE TITLE
How should people be properly fixing the "Player doesn't move" issue?

### ISSUE THREAD

**Issue by adamprato** [PocketMine/PocketMine-MP#4236]
### Issue description

According to #4220 #4221 #4207 #4224 #4230  #4234  #4235 users can't move.

According to #4235 this is fixed in df8e1e8

However, the latest available phar (1.6dev-27) does not seem to have this fix: https://dl.bintray.com/pocketmine/PocketMine/:PocketMine-MP_1.6dev-27_ef8227a0_API-2.0.0.phar

What is the appropriate way to fix the 'players dont move' issue since most users are familiar with installing the phar? Hopefully with that answer we can just refer to it instead of opening new issues that this problem still exists.

### Steps to reproduce the issue

Run installer.sh

### OS and versions

* PocketMine-MP: 1.6dev-27
* PHP: 7.03
* OS: Linux

**Comment by Intyre** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/README.md
http://pocketmine-mp.readthedocs.org/
http://pocketmine-mp.readthedocs.io/en/latest/installation.html
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#installing-manually
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#using-github
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#getting-php-and-the-start-script
http://pocketmine-mp.readthedocs.io/en/latest/links.html
https://forums.pocketmine.net
https://raw.githubusercontent.com/PocketMine/PocketMine-MP/master/.github/ISSUE_TEMPLATE.md
```<!--- use our forum https://forums.pocketmine.net for questions -->```

**Comment by adamprato** [comment]
You spent more effort finding the assorted links rather than saying which of the above methods actually work. I'm guessing the '#using-github' will work. I'll try that and if I succeed I'll reply with more succinct direction that someone can refer to for the next time the 'users cant move' issue is reopened.

**Comment by adamprato** [comment]
I can confirm that installing from github does fix the player moving problem. The 1.6dev-27 phar still has the issues so running the installer is probably not a good idea until it's updated. The steps I followed were these 3:

http://pocketmine-mp.readthedocs.io/en/latest/installation.html#using-github
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#getting-php-and-the-start-script
http://pocketmine-mp.readthedocs.io/en/latest/installation.html#starting-for-the-first-time
