### ISSUE TITLE
Freeze When Joining Server 0.15.1 build 2

### ISSUE THREAD

**Issue by bobys16** [PocketMine/PocketMine-MP#4238]
why im and my friend freeze when join my server .
i change the vps 3 TIME!!! and the problem is not fixed .
we can move but we see the other player is freeze . all player is see that too .
why ? is that bug or something??

thanks :)

**Comment by bobys16** [comment]
LEAD ON PLAYER.

**Comment by robske110** [comment]
please use the latest version and close this issue

**Comment by bobys16** [comment]
already fixed by update the php binary .

one question why cant spawn a mob . if spawning the server is crashing :(
