### ISSUE TITLE
Control app?

### ISSUE THREAD

**Issue by daniktheboss** [PocketMine/PocketMine-MP#4242]
Hello, can someone make a app for android and ios like leet... not hosting app, app like control panel. So you can control everything!

**Comment by GlitchPlayer** [comment]
Hey Kid, Leet a group of developers who developed the app and only maintains it. Pocketmine is a server software that Leet uses.

**Comment by daniktheboss** [comment]
Well first please don't call me a kid. I'm not a kid. And I am asking for a app to control the server!

**Comment by robske110** [comment]
There is almost noone around here who can code apps. Especially for iOS it's a pain in the ass (Swift = brainfuck).
And secoundly, if you want to just have the terminal from your pc on your device use RCON/PocketDockConsole. Rcon apps can be found

**Comment by robske110** [comment]
And this is a place for issues and btw this project is dead

**Comment by daniktheboss** [comment]
Ok nvm then thanks tho

**Comment by zxl777** [comment]
Hi,daniktheboss

We have plan to make this app for control pocketmine server.

You can check out MineServer on App Store at first.

Search "minecraft" on App Store, The First is Minecraft PE ,The Second is
our MineServer!

Now app can import a lot of new players to your MCPE server.

I look forward to your suggestions.

*Sky*
MineServer Team

2016-07-06 13:22 GMT+08:00 daniktheboss <notifications@github.com>:

**Comment by daniktheboss** [comment]
It would be aweasome if you had android version.

**Comment by extremeheat** [comment]
This is somewhat already possible with the use of RCON. It will allow you to remotely control the console, and there are plenty of RCON tools that already exist for Minecraft.

Run the installer and it'll give you the option to setup rcon with the port and your selected password.

@robske110 Objective-C or Mono from Xamarin are both viable alternatives, no need to use Swift. Either way, this is irrelevant.

**Comment by robske110** [comment]
@extremeheat Already pointed out RCON is being usable.
to that swift thingy: I was aware that iOS supports Objective-C but Mono sounds new

**Comment by iksaku** [comment]
Swift is pretty easy to manage
Mono is the unix compiler for .NET projects, I don't think you will need it for iOS apps

**Comment by extremeheat** [comment]
Ah, yes -- it's just Xamarin.

**Comment by SkygridRex** [comment]
@iksaku It's PocketMine dead? Because Intyre has gone
PocketMine esta muerto?

**Comment by iksaku** [comment]
PocketMine is `not dead`, but not as alive as it was before... It's just `Idle`... Intyre is providing Protocol Updates, which are essential for other PocketMine forks.
