### ISSUE TITLE
logged out due to Login timeout

### ISSUE THREAD

**Issue by BloodMoonWolf** [PocketMine/PocketMine-MP#4243]
basically, everything runs fine, but when anyone tries joining, including myself, it says "Disconnected from Server"
- PocketMine-MP: 0.14.3
- OS: 9.3.2

In the command pannel it says: "[Server thread//INFO]: [/192.168.0.124:60501] logged out due to login timeout

**Comment by SkygridRex** [comment]
Cause you are using an incorrect version

**Comment by BloodMoonWolf** [comment]
@SkygridRex incorrect version of?

**Comment by SkygridRex** [comment]
PocketMine

**Comment by BloodMoonWolf** [comment]
@SkygridRex 
Thanks!

**Comment by SkygridRex** [comment]
I am proud of having helped

**Comment by amerhacker60** [comment]
Remove Plugin Custom Alert And Update SimpleAuth !!!

**Comment by DarkYusuf13** [comment]
Is this your map downloaded? If yes, It will crash.
