### ISSUE TITLE
PocketMine-MP Problems arise

### ISSUE THREAD

**Issue by Fuhuang** [PocketMine/PocketMine-MP#4245]
Write in front：I am a Chinese, the statement is a translation, please do not care about Machine Translation's syntax errors
feedback：
[admin@vpn-454310-376263ff-ep5jv ~]$ wget -q -O - http://get.pocketmine.net/ | bash
gpg: keyring `/home/admin/.gnupg/secring.gpg' created
gpg: key 2280B75B marked as ultimately trusted
gpg: key 2280B75B: public key "PocketMine (PocketMine Signing Key) <security@pocketmine.
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
[_] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[_] This stable build was released on Wed Mar 18 01:00:47 CST 2015
[+] The build was signed, will check signature
[_] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[_] Checking signature of PocketMine-MP.phar
gpg: verify signatures failed: Unknown system error
[!] Invalid signature! Please check for file corruption or a wrongly imported public key48E7E52280B75B)

**Comment by Fuhuang** [comment]
Execute “. /start.sh” output
[admin@vpn-454310-376263ff-ep5jv ~]$ ./start.sh
Couldn't find a working PHP 7 binary, please use the installer.

**Comment by SkygridRex** [comment]
@Fuhuang https://forums.pocketmine.net/threads/latest-phar-and-php-binaries.16037/ you are using an incorrect version
