### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Zelentor** [PocketMine/PocketMine-MP#4246]
### Issue description

Write a short description about the issue
### Steps to reproduce the issue

1. ...
2. ...
### OS and versions

- PocketMine-MP:
- PHP:
- OS:
### Crashdump, backtrace or other files

- ...

**Comment by robske110** [comment]
Such descrpitive issue

**Comment by thebigsmileXD** [comment]
Who do i have to slap to get more information?

**Comment by dktapps** [comment]
Wow. You must really want this fixed since you're providing so much information.

**Comment by SkygridRex** [comment]
@robske110 "descrpitive" is considered an insult in my country

**Comment by SkygridRex** [comment]
@Zelentor Dan(m) it! Shoghi Cervantes will be back only for help you

**Comment by ZedCee** [comment]
_Opps.
User error._

**Comment by thebigsmileXD** [comment]
@SkygridRex you always post confusing and dumb comments

**Comment by SkygridRex** [comment]
@thebigsmileXD Escribo comentarios sin sentido? Si. Soy un pendejo como tu que solo molesta a alguien que quiere entretenerse? No. 
#4243
#4241
No todo el tiempo digo tonterias

**Comment by thebigsmileXD** [comment]
@thebigsmileXD I write meaningless comments ? Yes. I'm a fool like you who just bothers someone who wants to be entertained ? Do not.
# 4243
# 4241
Not all the time say stupid things

**Comment by thebigsmileXD** [comment]
Can anyone finally lock this?

**Comment by SkygridRex** [comment]
@thebigsmileXD 
"No Shelter"

The main attraction - distraction
got ya number than nnumber than numb 
Empty ya pockets son; they got you thinkin that
What ya need is what they sellin
Make you think that buyin is rebellin
From the theaters to malls on every shore
Tha thin line between entertainment and war
The frontline is everywhere, there be no shelter here 
Speilberg the nightmare works so push it far
Amistad was a whip, the truth was feathered and tarred
Memory erased, burned and scarred
Trade in ya history for a VCR

Cinema, simulated life, ill drama
Fourth Reich culture - Americana 
Chained to the dream they got ya searchin for 
Tha thin line between entertainment and war

There be no shelter here 
Tha frontline is everywhere

Hospitals not profit full
Yet market bulls got pockets full
To advertise some hip disguise
View tha world from American eyes
Tha poor adore keep fiendin for more 
Tha thin line between entertainment and war
They fix the need, develop the taste
Buy their products or get laid to waste
Coca-Cola is back in the veins of Saigon 
And Rambo too, he got a dope pair of Nikes on
And Godzilla pure muthafuckin filler
To keep ya eyes off the real killer 

Cinema, simulated life, ill drama
Fourth Reich culture - Americana 
Chained to the dream they got ya searchin for 
Tha thin line between entertainment and war

American eyes, American eyes....
View the world from American eyes
Bury the past, rob us blind
And leave nothin behind 

Just stare
Relive the nightmare.

**Comment by Tee7even** [comment]
@SkygridRex Ну, давайте теперь каждый будет писать на своём языке, ага. :+1:

**Comment by SkygridRex** [comment]
@Tee7even то есть отношение

**Comment by thebigsmileXD** [comment]
@Tee7even Gute Idee :) :+1:

**Comment by iPocket** [comment]
This issue has turned into a chatroom.
@Intyre, where are you? this issue is spamming my inbox.

**Comment by daniktheboss** [comment]
Хаха давай 😂😂
