### ISSUE TITLE
PocketMine-MP MultiPlayer Glitch

### ISSUE THREAD

**Issue by DreamKnights** [PocketMine/PocketMine-MP#4248]
### Issue description

Write a short description about the issue
There is a connection glitch While trying to host Multiple connections on my PM server.  Currents server Config:
# Properties Config file
# Sun Jul 17 08:40:22 CDT 2016

server-name=Cop Zone
server-port=19132
memory-limit=256M
gamemode=1
max-players=20
spawn-protection=16
white-list=off
enable-query=off
enable-rcon=off
motd=MCPE Server1
announce-player-achievements=on
allow-flight=on
spawn-animals=on
spawn-mobs=on
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=Highlander
level-seed=
level-type=DEFAULT
rcon.password=######
auto-save=on

When 2 or more players join  the world, I can see the player at first contact but there position is not updated as they move. they appear frozen in place and locked in there direction.  Their avatar's arm moves while they interact with the environment. and I can tell that they are moving around the environment because I can see the dirt kicking up at their feet even thought from my view they are frozen in place.  
I like the tethered line but wish we had the option to turn it off at will.
Also the time of day is synced but the weather for the exact same position is different for each player.  I could see a clear sunny sky while the player next to me has rain and fog.
Interacting test:
Placing and removing block in the world at the exact same position does not update to the other players screen.  example: P1 Creates a hole in the ground. P2 can not see the hole or fall in unless P2 logs off then rejoins the world.  Placing blocks does not update using the same method. Sometimes it does if they are not placed in the same spot as the blocks that P2 has placed.
It's like we are in the same world but different Dimension!!!
Chat does work.
### Steps to reproduce the issue

1. ...Connect 2 or more players
2. ...Verify position on both screens
3. ...Watch movement of other player
4. ...Perform block modify test
### OS and versions

- PocketMine-MP: 1.6dev "Redacted" API 2.0.0
- PHP: 7.1.0alpha3
- OS: Windows 10
### Crashdump, backtrace or other files

- ...

**Comment by GlitchPlayer** [comment]
This project is outdated. Use third-party like Genisys.
