### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by ArcLich** [PocketMine/PocketMine-MP#4249]
So I just tried to make my first server and I keep getting this message.
Help.
![image](https://cloud.githubusercontent.com/assets/20550372/16974883/485e8f16-4e0f-11e6-8958-2b57a2b26598.png)

**Comment by jojoe77777** [comment]
Not related to PocketMine.

**Comment by Franklau1212** [comment]
Wow!you are so amazing! youcan use pocket mine on iPad!Can you teach me how to do it?来自新浪邮箱触屏版
----- 原始邮件 -----
发件人：ArcLich <notifications@github.com>
收件人：PocketMine/PocketMine-MP <PocketMine-MP@noreply.github.com>
主题：[PocketMine/PocketMine-MP] Runtime Exception (#4249)
日期：2016年07月20日 12点18分

So I just tried to make my first server and I keep getting this message.

Help.

a

&mdash;

**Comment by GlitchPlayer** [comment]
Not recommended to use plug pocketmine tho. Not supported by pocketmine
team.

**Comment by ArcLich** [comment]
So can anyone suggest anything that I can use to make servers?

**Comment by Galang23** [comment]
mkdir command error: No Such File or Directory in phar:///private/*/*/*/*.php

**Comment by ArcLich** [comment]
So what do I use?

**Comment by robske110** [comment]
phar:/// seems weird
I think ios is too stupid for opening phar

**Comment by legoboy0215** [comment]
Don't use plug pocketmine.
