### ISSUE TITLE
update the version

### ISSUE THREAD

**Issue by zhiyan114** [PocketMine/PocketMine-MP#4250]
### Issue description

many (like mine) have upgrade to a higher version of mcpe and unable to use the server
### Steps to reproduce the issue

1. update the version of the pocketmine server
### OS and versions

- PocketMine-MP: 1.11.0
- PHP: UNKNOWN
- OS: 1.15.1
### Crashdump, backtrace or other files

- ...

**Comment by westlyroots** [comment]
OS is the operating system you use when you are running the server. for instance, you use windows 10 and no other OS, it would be logical to put windows 10.

**Comment by GlitchPlayer** [comment]
Use forks for awhile, PM is outdated
