### ISSUE TITLE
Players cannot move

### ISSUE THREAD

**Issue by YanSoo123** [PocketMine/PocketMine-MP#4253]
Players can actually move but I cannot see them move UNTILL after a short while where they disappear and appear in another place... Also leads are connected to other players to show where they are in a small distance. Windows, API 2.0.0, PHP7.

**Comment by Demon1driver** [comment]
I am having the same problem

**Comment by daniktheboss** [comment]
Update to latest version.

**Comment by KairusDarkSeeker** [comment]
[LbCore](https://github.com/KairusDarkSeeker/LbCore)
