### ISSUE TITLE
Help Me !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Unknown-AnonOP** [PocketMine/PocketMine-MP#4255]
Hi Huys + Staff When I find the last version of PocketMine-MP.phar for Last MCPE Like Mcpe 15.4 pls help me !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by amerhacker60** [comment]
And This Problem plz help me :
[13:44:26] [Server thread/INFO]: Done (6.702s)! For help, type "help" or "?"
[13:44:26] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed

**Comment by ImagicalGamer** [comment]
The error is because MCPE or another server is running on that port on your network and PocketMine hasn't been updated yet.
