### ISSUE TITLE
Help Me Please I need Code Permission

### ISSUE THREAD

**Issue by XxKYuMAxX** [PocketMine/PocketMine-MP#4256]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by XxKYuMAxX** [comment]
<?php

namespace DevlKitsPro;

use pocketmine\plugin\PluginBase;
use pocketmine\Player;
use pocketmine\command\CommandSender;
use pocketmine\command\Command;
use pocketmine\utils\TextFormat as Color;
use pocketmine\inventory\InventoryBase;
use pocketmine\item\Item;
use pocketmien\permission\Permission;

class Main extends PluginBase{
	
	public function onEnable(){
		$this->getServer()->getLogger()->info(Color::GREEN."[DevlKitsPro] Plugin has been Enable");
		}
	public function onDisable(){
		$this->getServer()->getLogger()->info(Color::RED."[DevlKitsPro] Plugin has been Disable");
}
public function onCommand(CommandSender $sender, Command $cmd, $label, array $args){
	   	switch($cmd->getName()){ /* switch == case || $cmd->getName() == command */
		  case 'kitvip':
		   $sender->sendMessage(Color::GOLD."[DevlKitsPro] You Have A Kit VIP");
		   $sender->getInventory()->additem(item::get(313, 0, 1));
		   $sender->getInventory()->additem(item::get(312, 0, 1));
		   $sender->getInventory()->additem(item::get(311, 0, 1));
		   $sender->getInventory()->additem(item::get(310, 0, 1));
		   $sender->getInventory()->additem(item::get(276, 0, 1));
		   $sender->getInventory()->additem(item::get(261, 0, 1));
		   $sender->getInventory()->additem(item::get(262, 0, 64));
		   $sender->getInventory()->additem(item::get(466, 0, 32));
		   $sender->getInventory()->additem(item::get(346, 0, 64));
		   $sender->sendTip("§eYou Have Kit VIP");
		   break;
				case 'kityout':
					$sender->sendMessage(Color::RED."[DevlKitsPro] You Have A YouTuber KIT");
					$sender->getInventory()->additem(item::get(267, 0, 1));
					$sender->getInventory()->additem(item::get(306, 0, 1));
					$sender->getInventory()->additem(item::get(307, 0, 1));
					$sender->getInventory()->additem(item::get(308, 0, 1));
					$sender->getInventory()->additem(item::get(309, 0, 1));
					$sender->getInventory()->additem(item::get(261, 0, 1));
					$sender->getInventory()->additem(item::get(262, 0, 64));
					$sender->getInventory()->additem(item::get(366, 0, 64));
					$sender->sendTip("§4You Have Kit YouTuber");
					break;
				 case 'kitmember':
					$sender->sendMessage(Color::BLUE."[DevlKitsPro] You Have A Member KIT");
					$sender->getInventory()->additem(item::get(272, 0, 1));
					$sender->getInventory()->additem(item::get(302, 0, 1)); 
					$sender->getInventory()->additem(item::get(303, 0, 1));
					$sender->getInventory()->additem(item::get(304, 0, 1));
					$sender->getInventory()->additem(item::get(305, 0, 1));
					$sender->getInventory()->additem(item::get(260, 0, 64));
					$sender->sendTip("§1You Have Kit Member");
					break;
				case 'devlkitsby':
					$sender->sendMessage(Color::GREEN."DevlKits Plugin By Xx_KYuMA_xX");
					break;
				case 'devlkitshelp':
					$sender->sendMessage(Color::GOLD."]=========================[");
					$sender->sendMessage(Color::GREEN."/kitvip: Give VIP KIT");
					$sender->sendMessage(Color::YELLOW."/kityout: Give YouTuber KIT");
					$sender->sendMessage(Color::RED."/devlkitsby: see Name make DevlKits Plugin");
					$sender->sendMessage(Color::YELLOW."/kitmember: Give Member KIT");
					$sender->sendMessage(Color::GREEN."/devlkitshelp: see Commands DevlKits Plugin");
					$sender->sendMessage(Color::GOLD."]=========================[");
					
			  }
			
  }
   
}

}

**Comment by SOF3** [comment]
This is not the plugin development forum...

**Comment by KairusDarkSeeker** [comment]
true
