### ISSUE TITLE
Minecraft client crash!!!

### ISSUE THREAD

**Issue by HeXXitTheGamer** [PocketMine/PocketMine-MP#4257]
### Issue descrdescription
1. I have played on my server and crash 
2. In console say Player kicked:reason login timer expired
  Help !!!
* PocketMine-MP:
* PHP

**Comment by ibookcc** [comment]
maybe it's timeout

**Comment by SOF3** [comment]
Using the wrong PocketMine version?

**Comment by RocoWayne** [comment]
i think that maybe is the map, maybe one of yours map crash the cliente of the player (if he is using 0.15 im sure)
