### ISSUE TITLE
I have Proplem With My Event Plugin

### ISSUE THREAD

**Issue by khavmc** [PocketMine/PocketMine-MP#4259]
Hello guys

I am making eventplugin

And i am making event join

When join he is making sound anvil

But he is not work

He is write in console:

[Server] [12:36:58] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'NobadWordsKHAV v1.0.2': Call to a member function getName() on unknown on NobadWordsKHAV\Main
[Server] [12:36:58] [Server thread/CRITICAL]: Error: "Call to a member function getName() on unknown" (EXCEPTION) in "/NobadWordsKHAV/src/NobadWordsKHAV/Main" at line 81
[Server] [12:36:58] [Server thread/INFO]: » KHAV Joined .

And i have proplem in eventdeath

I want to make deathmessage

$player killer by $killer

But when i kill the message is not work

He is write for me in console:

Server] [12:37:59] [Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'NobadWordsKHAV v1.0.2': Call to a member function getKiller() on float on NobadWordsKHAV\Main
[Server] [12:37:59] [Server thread/CRITICAL]: Error: "Call to a member function getKiller() on float" (EXCEPTION) in "/NobadWordsKHAV/src/NobadWordsKHAV/Main" at line 106
[Server] [12:37:59] [Server thread/INFO]: KHAV was shot by KHAV

**Comment by FuxonPlayz** [comment]
you shouldn't upload plugins helps here!
you should upload it in the forums.
