### ISSUE TITLE
development build not working

### ISSUE THREAD

**Issue by xbossman24** [PocketMine/PocketMine-MP#4267]
### Issue description

Write a short description about the issue
 it says jenkins.pocketmine.net Host error for the windows development build
### Steps to reproduce the issue

1. ...
2. ...
### OS and versions

- PocketMine-MP:
- PHP:
- OS:
### Crashdump, backtrace or other files

- ...

**Comment by iPocket** [comment]
What a descriptive issue

**Comment by KairusDarkSeeker** [comment]
The Jenkins is down

**Comment by xbossman24** [comment]
Will it come back up later?

**Comment by KairusDarkSeeker** [comment]
@xbossman24 I don't know about that.

**Comment by archie426** [comment]
Is this for the .phar? You can download it from a mirror or the link supplied by TheDeibo (On the forums)
Jenkins is going to be down a long time. I think shoghicp has the hosting controls. Just swap the phar with the one that you have downloaded. Try this one aswell https://bintray.com/pocketmine/PocketMine/PocketMine-MP-phar#files
If you want 0.15.6 follow the instructions supplied by Survingo at https://forums.pocketmine.net/threads/version-issues.18015/
