### ISSUE TITLE
Couldn't install the Slapper plugin HELP PLEASE

### ISSUE THREAD

**Issue by fathergorgi1** [PocketMine/PocketMine-MP#4268]
Whenever I try to download the slapper plugin into my server it would say something about a crash dump and uninstall the rest of the plugins on the server PLEASE HELP
1. Put in the command /plugins install Slapper

Version: 2.00

Crashdump

**Comment by iPocket** [comment]
This is not a forum, ask help for Slapper or Pudler in the forums.

**Comment by HeXXitTheGamer** [comment]
I think the solution :
Download the phar for 0.15.4 this will work!!! ✔

**Comment by GlitchPlayer** [comment]
@HeXXitTheGamer Are you dumb? Even if you are upgrading, it won't work -.- DUMB! @fathergorgi1 Get the repo of Slapper form github. It has latest version of it :3

**Comment by HeXXitTheGamer** [comment]
GlitchPlayer , for me this solution work!!

**Comment by GlitchPlayer** [comment]
@fathergorgi1 Also, the slapper is outdated from pocketmine plugin repo.

**Comment by KairusDarkSeeker** [comment]
👏 Close this issue

**Comment by GlitchPlayer** [comment]
Yup! 👏

**Comment by LargeArt7338551** [comment]
Well I am running genisis php7 and it reconizes all php5 plugins except for the ones you download as a folder. And slapper you download as a folder... And I really want slapper.

**Comment by TheDeibo** [comment]
https://github.com/PMPlugins/Slapper

That's the official GITHUB for the Slapper plugin. 

honestly, has anyone heard of Google?

**Comment by DiegoGTRatty** [comment]
@TheDeibo I've only heard of Bing, Yahoo and Ask.

**Comment by TheDeibo** [comment]
try http://google.com. much more efficient xD
