### ISSUE TITLE
SimpleAuth ShowMessageTask.phar

### ISSUE THREAD

**Issue by HeXXitTheGamer** [PocketMine/PocketMine-MP#4271]
### Issue description

Write a short descriptio
### OS and versions

- PocketMine-MP:
- PHP:
- OS:
### Crashdump, backtrace or other files

Genisys Crash Dump Wed Aug 24 20:59:09 EEST 2016

Error: Illegal offset type in unset
File: /plugin-4.phar/src/SimpleAuth/task/ShowMessageTask
Line: 46
Type: E_WARNING

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN : SimpleAuth v1.7.1

Code:
[37]    public function getPlugin(){
[38]        return $this->owner;
[39]    }
[40] 
[41]    public function addPlayer(Player $player){
[42]        $this->playerList[$player->getUniqueId()] = $player;
[43]    }
[44] 
[45]    public function removePlayer(Player $player){
[46]        unset($this->playerList[$player->getUniqueId()]);
[47]    }
[48] 
[49]    public function onRun($currentTick){
[50]        $plugin = $this->getPlugin();
[51]        if($plugin->isDisabled()){
[52]            return;
[53]        }
[54] 
[55]        foreach($this->playerList as $player){
[56]            $player->sendPopup(TextFormat::ITALIC . TextFormat::GRAY . $this->getPlugin()->getMessage("join.popup"));

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: e28d63b9b9d3965bd225349679f645d1fd250896 [Protocol 82; API 2.0.0]
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Thu Aug 13 14:14:15 CST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 2 hours 59 minutes 47 seconds
Number of loaded worlds: 3
Players online: 3/200

Loaded plugins:
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
BasicHUD 1.0.6 by aliuly for API(s) 2.0.0
Universe 1.0.0 by Comedyman937 for API(s) 1.9.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
Nick 1.0.1 by AryToNeX for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
EssentialsPE 1.1.3.vgphp7 by LegendsOfMCPE Team for API(s) 1.13.0
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
Broadcaster 1.16 by EvolSoft for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 2.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
ParticlesPlus 0.0.2 by ImagicalGamer for API(s) 1.0.0, 2.0.0, 3.0.0
PurePerms 1.3.5 by 64FF00 for API(s) 1.13.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 2.0.0
WorldEdit 2.1.0 TRANSLATE BY ZIKEN by ikenusi / ByZikenPE, hmy2001(Plug- source reference) for API(s) 1.13.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
automaticDoor 1.0-alpha by hm for API(s) 1.4.1
Alias 1.2.0 by ZacHack for API(s) 1.12.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
CheckID 1.0-Alpha by XxD7omGamer for API(s) 2.0.0
SkyWarsDoDo 1.0.0 Reloaded_ENGLISH by KaitoDoDo for API(s) 1.0.0, 1.1.0, 2.0.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
OreInstantDrop 1.0 by ScandiePlay for API(s) 1.12.0
WorldGM 1.1.0 by Vaivez66 for API(s) 1.12.0, 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
essentialsTP 1.1.0 by  for API(s) 1.12.0
SurvivalGames_GS 1.0.0 by GamesLoad for API(s) 1.1.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 2.0.0

**Comment by iPocket** [comment]
That's Genisys,not PocketMine-MP.
And that's a plugin issue, not a server issue.

**Comment by GlitchPlayer** [comment]
Error: Illegal offset type in unset
File: /plugin-4.phar/src/SimpleAuth/task/ShowMessageTask
Line: 46
Type: E_WARNING

-.-

Are you reading???? IT says plugin! Not pocketmine issue

**Comment by HeXXitTheGamer** [comment]
How can i resolveeee , this warnig crash the server!!!!

**Comment by iPocket** [comment]
I said:
> Invalid issue, please close and **report it on SimpleAuth's github repo.**

So do it, and get the latest version from PocketMine/SimpleAuth.

**Comment by dktapps** [comment]
Nice, you know how to spam unrelated issues and not read. That's an amazing talent.

**Comment by KairusDarkSeeker** [comment]
It can only be done by editing the plugin

**Comment by HeXXitTheGamer** [comment]
+KairusDarkSeeker Download the plugin , edit and give me pleaseee!

**Comment by KairusDarkSeeker** [comment]
@HeXXitTheGamer I will later

**Comment by GlitchPlayer** [comment]
@HeXXitTheGamer Please do not spam the pocketmine issues and BIG PLEASE! READ THE FREAKING CRASH DUMP!

**Comment by TristonStuart** [comment]
Someone close this issue....

**Comment by TristonStuart** [comment]
Or kick this guy he posted another unrelated question...

**Comment by iPocket** [comment]
@TristonStuart Stop spamming everywhere!

**Comment by KairusDarkSeeker** [comment]
Umm wtf this is useless, close this issue its only a plugin issue not on the server software.
