### ISSUE TITLE
Api Injector 2.0.0 Down? >:(

### ISSUE THREAD

**Issue by KeksbyteYT** [PocketMine/PocketMine-MP#4274]
Hey i have Buyed on Nitrado Pocketmine i need a working api injector

**Comment by flaxues** [comment]
API Injector? I think you should contact Nitrado???

And next time follow the issues rules :)

**Comment by archie426** [comment]
I have noticed that aswell. Try using the plugin DevTools with the recompiling method. You may want to change string as well.
