### ISSUE TITLE
Inventory gets cleared when players login or rejoin the server

### ISSUE THREAD

**Issue by AbandonedSoul71** [PocketMine/PocketMine-MP#4276]
When i tested my server i tried on survival and get some items from shop, but when i re-joined, all my items were gone, this happens to my brother on my server and even to other accounts?
This is really annoying and i cant work on the server with this issue.

**Comment by KairusDarkSeeker** [comment]
@AbandonedSoul71 You need a custom plugin

**Comment by AbandonedSoul71** [comment]
Ok ty, i have already fixed this now, but now i have another problem, when
my server is done loading and says done my minecraft automatic quit

Op 29-aug.-2016 12:48 schreef "Harvey Hans" <notifications@github.com>:

**Comment by KairusDarkSeeker** [comment]
@AbandonedSoul71 @Legoboy0215

**Comment by ibookcc** [comment]
额

**Comment by legoboy0215** [comment]
WTF...

**Comment by MetalMinurz** [comment]
Wait...How did you fix it? I have the same problem...
