### ISSUE TITLE
0.10.4 server!!!

### ISSUE THREAD

**Issue by hihihoholalalolo1227** [PocketMine/PocketMine-MP#4277]
Guys Can you help I don't know how (??¿¿) to make the server is 0.15.9?? Please help…🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by hihihoholalalolo1227** [comment]
and is said the server will sleep phar:///private/var/mobile/Containers/Data/Application/64A9162A-BEOF-41E4-9F6B-FC852636BC40/Documents/1.bin/arc/pocket mine/server.php

**Comment by westlyroots** [comment]
for some odd reasons all official phars that are 'updated' only reach up to 0.11.0 in dev version.

[here's one that is updated to 0.15.4 but IS unnoficial, and windows 10 clients can't connect from what i've seen.](http://download1997.mediafire.com/h9307228xdag/97aun4agqru4f6n/PocketMine-MP%28Raghavs13%29.phar)

(uses the actual mediafire download link, so you don't load up adds.

**Comment by hihihoholalalolo1227** [comment]
Thanks

**Comment by iPocket** [comment]
Close the issue...

On 5 September 2016 at 15:24, hihihoholalalolo1227 <notifications@github.com

**Comment by hihihoholalalolo1227** [comment]
I need to give other see !!!!

**Comment by jasonwynn10** [comment]
this issue is invalid due to the issue template being removed

**Comment by iPocket** [comment]
@jasonwynn10 Not just that.

**Comment by TristonStuart** [comment]
Closed Issue
-------------
Reason:
-------------
Invalid Issue
Issue Template Deleted
(Over use of emojis)
-------------
Tag : Solved
Tag : Closed
