### ISSUE TITLE
World failed to open stream

### ISSUE THREAD

**Issue by YanSoo123** [PocketMine/PocketMine-MP#4278]
These messages spam in console everytime I save the world... I have renamed the world "NewSurvival" to "world and these messages started appearing :/  🎱 

> Warning: file_put_contents(C:\Users\Yan\Desktop\My Server\worlds/NewSurvival/level.dat): failed to open stream: No such file or directory in phar://C:/Users/Yan/Desktop/My Server/PocketMine-MP.phar/src/pocketmine/level/format/generic/BaseLevelProvider.php on line 126

**Comment by iPocket** [comment]
You should restart the server.

**Comment by jasonwynn10** [comment]
invalid post

**Comment by iPocket** [comment]
@jasonwynn10 We know!
