### ISSUE TITLE
windows 10 clients cannot connect to my server.

### ISSUE THREAD

**Issue by red-star-fighter** [PocketMine/PocketMine-MP#4279]
### Issue description

using 0.15.4 phars, pocket edition can connect fine but windows 10 clients just try to find the server and then fail, giving the same error as if the server doesnt exist (it's showing both IPs VIA LAN)
### Steps to reproduce the issue

1. start a 0.15.4 server
2. attempt to join using windows 10 edition
### OS and versions

- PocketMine-MP: Clearsky 1.1 - latest official version found was 0.14.0, forced to use third party
- PHP: php7
- OS: Windows 10
### Crashdump, backtrace or other files

- no crashes found

**Comment by dktapps** [comment]
I'd recommend you submit an issue to ClearSky, not here. Third-party builds aren't supported.

**Comment by GlitchPlayer** [comment]
Post this on clearsky, also Win10 clients whose servers are hosted on the same PC can't find any LAN servers since Win10 is very strict with connections.

Follow robske fix to fix your issue.

**Comment by GlitchPlayer** [comment]
Post this on clearsky, also Win10 clients whose servers are hosted on the same PC can't find any LAN servers since Win10 is very strict with connections.

Follow robske fix to fix your issue.

**Comment by robske110** [comment]
This is not a PM/CS/Gsys issue. Please follow these instructions:
![image](https://cloud.githubusercontent.com/assets/16020100/18224362/2d3adc68-71db-11e6-9c61-507401d567f1.png)

**Comment by robske110** [comment]
Close this issue and use the CS bug tracker: https://github.com/ClearSkyTeam/ClearSky/issues

**Comment by dktapps** [comment]
@jasonwynn10 yet another spam comment...

**Comment by jasonwynn10** [comment]
XD sorry
