### ISSUE TITLE
Sleep error? WTF

### ISSUE THREAD

**Issue by HeXXitTheGamer** [PocketMine/PocketMine-MP#4280]
Genisys Crash Dump Mon Sep 5 16:39:34 EEST 2016

Error: time_sleep_until(): Sleep until to time is less than current time
File: /src/pocketmine/Server
Line: 2680
Type: E_WARNING

Code:
[2671]      return [];
[2672]  }
[2673] 
[2674]  private function tickProcessor(){
[2675]      $this->nextTick = microtime(true);
[2676]      while($this->isRunning){
[2677]          $this->tick();
[2678]          $next = $this->nextTick - 0.0001;
[2679]          if($next > microtime(true)){
[2680]              @time_sleep_until($next);
[2681]          }
[2682]      }
[2683]  }
[2684] 
[2685]  public function onPlayerLogin(Player $player){
[2686]      if($this->sendUsageTicker > 0){
[2687]          $this->uniquePlayers[$player->getRawUniqueId()] = $player->getRawUniqueId();
[2688]      }
[2689] 
[2690]      $this->sendFullPlayerListData($player);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: e28d63b9b9d3965bd225349679f645d1fd250896 [Protocol 82; API 2.0.0]
uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Thu Aug 13 14:14:15 CST 2015 armv7l
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, android

Server uptime: 23 minutes 2 seconds
Number of loaded worlds: 2
Players online: 3/30

Loaded plugins:
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 2.0.0
AntiSpam 1.3 by xBeastMode for API(s) 2.0.0
BasicHUD 1.0.6 by aliuly for API(s) 2.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
EssentialsPE 1.1.3.vgphp7 by LegendsOfMCPE Team for API(s) 1.13.0
Broadcaster 1.16 by EvolSoft for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
PurePerms 1.3.5 by 64FF00 for API(s) 1.13.0, 2.0.0
TapToDo 2.2.1 by Falk for API(s) 2.0.0
WorldEdit 2.1.0 TRANSLATE BY ZIKEN by ikenusi / ByZikenPE, hmy2001(Plug- source reference) for API(s) 1.13.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
CheckID 1.0-Alpha by XxD7omGamer for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimpleWarp 2.1.0 by Falkirks for API(s) 2.0.0

**Comment by dktapps** [comment]
Dude. You spam Genisys crash dumps at PocketMine. Are you stupid or what?

**Comment by HeXXitTheGamer** [comment]
#dktapps What?? Say the solutin please

**Comment by dktapps** [comment]
THIS IS NOT THE GENISYS REPOSITORY. (^_^)

**Comment by HeXXitTheGamer** [comment]
@dktapps  But?

**Comment by iPocket** [comment]
...

**Comment by dktapps** [comment]
(^_^)

**Comment by hihihoholalalolo1227** [comment]
I have too :(

**Comment by dktapps** [comment]
# THIS IS NOT THE GENISYS REPOSITORY. (^_^)

I hope you got it this time, because Markdown won't allow me to make it bigger afaik.

**Comment by remotevase** [comment]
# _**WRONG REPOSITORY!!! POST YOUR ISSUE [HERE](https://github.com/ITXTech/Genysis/issues) INSTEAD**_

**Comment by iPocket** [comment]
@remove_vase Advertiements...

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by remotevase** [comment]
oh that counts as ads? oops... was just trying to be helpful by providing him the link

**Comment by iPocket** [comment]
STOP

**Comment by GlitchPlayer** [comment]
@iPocket @HeXXitTheGamer How much dumb are you? Have you read the comments or even the crash dump? Well...
# Genisys version: e28d63b9b9d3965bd225349679f645d1fd250896 [Protocol 82; API 2.0.0]
 uname -a: Linux localhost 3.4.67 #1 SMP PREEMPT Thu Aug 13 14:14:15 CST 2015 armv7l
 PHP version: 7.0.3
 Zend version: 3.0.0
 OS : Linux, android

# GENISYS!

Biggest dumb I ever saw. @iPocket That counts as advertisements? Wow. good job. (claps)

**Comment by jasonwynn10** [comment]
LOL what is up with all the invalid issue posts recently?

**Comment by hihihoholalalolo1227** [comment]
BRARARARARARARARARARRA
