### ISSUE TITLE
cant join my pocketmine server for 0.15.x

### ISSUE THREAD

**Issue by crazykids2800** [PocketMine/PocketMine-MP#4282]
### Issue description

Write a short description about the issue
### Steps to reproduce the issue

1. ...
2. ...
### OS and versions

- PocketMine-MP:
- PHP:
- OS:
### Crashdump, backtrace or other files

- ...

**Comment by iPocket** [comment]
Oh! that's more information than needed!

**Comment by legoboy0215** [comment]
I got a solution for you. Go to school and learn how to READ. 
![capture](https://cloud.githubusercontent.com/assets/12031248/18414168/950aa39c-77f2-11e6-8eda-ede4825a5cd0.PNG)

**Comment by DiegoGTRatty** [comment]
@legoboy0215 

I don't wanna be that guy but... if he can't read how can we expect him to understand us...?

**Comment by archie426** [comment]
I have made a pull request bumping the version. Look out for it. When it is checked and accepted (hopefully)

**Comment by iPocket** [comment]
@archie426 (hopeless)

**Comment by GlitchPlayer** [comment]
@archie426 As @iPocket said. It's hopeless

**Comment by jasonwynn10** [comment]
this post is definitely invalid

**Comment by LargeArt7338551** [comment]
are you using php7?
Because that is only way to run pocketmine 0.15
