### ISSUE TITLE
Downloaded PC worlds cause crash on my device

### ISSUE THREAD

**Issue by RocoWayne** [PocketMine/PocketMine-MP#4283]
I want to use some of my PC maps in my PE server and some of this crash the client when i enter. It cause to the minecraft clients to close and i dont find the solution. In PE 14 servers the maps works just fine.

**Comment by iPocket** [comment]
Why did you delete the issue template?
Do not delete it, just write all the information. such as OS, PHP version, reproducing this issue, etc.

**Comment by GlitchPlayer** [comment]
Use blocklauncher to remove the PC blocks

**Comment by RocoWayne** [comment]
@GlitchPlayer  i will try it, but, can someone, just put in one thread which PC blocks i need to remove with McEdit to make my pc maps 0.15.x compatible?

**Comment by DiegoGTRatty** [comment]
Probably porting maps correctly. Remember that PE updates come in a different order than PC updates so some unexisting blocks/items may be causing the issue.

**Comment by RocoWayne** [comment]
Yeah, i know @DiegoGTRatty , but i cant find wich block is causing the problem. No one has a solution i see

**Comment by jasonwynn10** [comment]
there is no issue template here so this issue post is invalid

**Comment by RocoWayne** [comment]
@jasonwynn10 there is no crashlog for share , because the server dont crash, only closes

**Comment by jasonwynn10** [comment]
i'm not asking for the crash log, I am looking for the issue template which was deleted before you put in the first message

**Comment by dktapps** [comment]
@jasonwynn10 You don't run this place and you're spamming my notifications. This repository is dead, you might as well stop wasting your breath here. (Sorry... typing.)

**Comment by jasonwynn10** [comment]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and Versions

* PocketMine-MP: 
* PHP: 
* OS:

**Comment by jasonwynn10** [comment]
fine @dktapps

**Comment by PrimusLV** [comment]
@dktapps "Unsubscribe" is on right side of the screen. If it is dead, why are you still here watching this repo?

@RocoWayne use common sense, for example: have you seen stained glass in PE?

**Comment by dktapps** [comment]
@PrimusLV I have hope that someone may come back to it.

**Comment by RocoWayne** [comment]
hi! 

I made a PE map in PC but its crashing my MCPE 15 client when i enter (it closes and i need to open the app again, the server do not crash or nothing)

This are the block that contain , i think that is nothing wrong with this, so...  what is wrong? 

Number,Type,ID
16777216,<Blocks>,
16709524,Air,(0:0)
430,Polished Granite,(1:2)
572,Polished Diorite,(1:4)
1113,Polished Andesite,(1:6)
674,Grass Block,(2:0)
281,Cobblestone,(4:0)
10,Oak Wood Planks,(5:0)
1572,Spruce Wood Planks,(5:1)
4,Dark Oak Wood Planks,(5:5)
13,Oak Wood (Upright),(17:0)
86,Oak Wood (Bark Only),(17:12)
50,Jungle Wood (Bark Only),(17:15)
2054,Oak Leaves (No Decay),(18:4)
251,Jungle Leaves (No Decay),(18:7)
75,Glass,(20:0)
5011,Lapis Lazuli Block,(22:0)
896,Sandstone,(24:0)
82,Cobweb,(30:0)
210,Grass,(31:1)
2778,Wool (White),(35:0)
4,Orange Wool,(35:1)
5,Light Blue Wool,(35:3)
38,Yellow Wool,(35:4)
10568,Lime Wool,(35:5)
246,Gray Wool,(35:7)
15978,Light Gray Wool,(35:8)
5296,Cyan Wool,(35:9)
290,Blue Wool,(35:11)
221,Brown Wool,(35:12)
5,Green Wool,(35:13)
563,Red Wool,(35:14)
455,Black Wool,(35:15)
6,Block of Iron,(42:0)
3,Quartz Stone Double Slab (Seamed),(43:7)
473,Stone Double Slab (Seamless),(43:8)
334,Stone Slab (Bottom),(44:0)
16,Stone Brick Slab (Bottom),(44:5)
309,Quartz Slab (Bottom),(44:7)
140,Stone Slab (Top),(44:8)
12,Stone Brick Slab (Top),(44:13)
3312,Quartz Slab (Top),(44:15)
2,Torch (South),(50:3)
2,Torch (North),(50:4)
7,Torch (Up),(50:5)
17,"Oak Wood Stairs (Bottom, East)",(53:0)
14,"Oak Wood Stairs (Bottom, West)",(53:1)
6,"Oak Wood Stairs (Bottom, South)",(53:2)
3,"Oak Wood Stairs (Bottom, North)",(53:3)
18,Block of Diamond,(57:0)
4,Stone Pressure Plate,(70:0)
291,Clay,(82:0)
4,Oak Fence,(85:0)
2,Stone Bricks,(98:0)
829,Iron Bars,(101:0)
44,"Brick Stairs (Bottom, East)",(108:0)
14,"Brick Stairs (Bottom, West)",(108:1)
33,"Brick Stairs (Bottom, South)",(108:2)
21,"Brick Stairs (Bottom, North)",(108:3)
1,"Brick Stairs (Top, East)",(108:4)
1,"Brick Stairs (Top, North)",(108:7)
59,"Stone Brick Stairs (Bottom, East)",(109:0)
19,"Stone Brick Stairs (Bottom, West)",(109:1)
9,"Stone Brick Stairs (Bottom, South)",(109:2)
11,"Stone Brick Stairs (Bottom, North)",(109:3)
4,"Stone Brick Stairs (Top, East)",(109:4)
48,"Stone Brick Stairs (Top, West)",(109:5)
6,"Stone Brick Stairs (Top, South)",(109:6)
14,Oak Wood Slab (Bottom),(126:0)
2,"Spruce Wood Stairs (Top, East)",(134:4)
1,"Spruce Wood Stairs (Top, West)",(134:5)
4,"Spruce Wood Stairs (Top, South)",(134:6)
33,Cobblestone Wall,(139:0)
10397,Block of Quartz,(155:0)
200,"Quartz Stairs (Bottom, South)",(156:2)
199,"Quartz Stairs (Bottom, North)",(156:3)
5,"Quartz Stairs (Top, South)",(156:6)
6,"Quartz Stairs (Top, North)",(156:7)
3,Yellow Carpet,(171:4)
2,Lime Carpet,(171:5)
4,Cyan Carpet,(171:9)
901,Block of Coal,(173:0)
16,Spruce Fence,(188:0)

**Comment by RocoWayne** [comment]
no one? :(

**Comment by dktapps** [comment]
This bug has been fixed by Mojang in the 0.16.0 beta (0.15.90.8). Please close this issue and wait for release.
