### ISSUE TITLE
My server restart itself when i enter to a PC ported map

### ISSUE THREAD

**Issue by RocoWayne** [PocketMine/PocketMine-MP#4287]
### Issue description

When i enter to a map in my server it reset itself.

### Steps to reproduce the issue

1. I tp from hub to a map with /mw tp MAPNAME

### OS and versions

* PocketMine-MP: 1.6dev #0 [Protocol 81; API 2.0.0]
* PHP: 7.0.3
* OS: Linux, linux

### Crashdump, backtrace or other files

PocketMine-MP Crash Dump Mon Sep 19 15:20:13 UTC 2016

Error: Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, string given, called in /opt/minecraft/multicraft/servers/druocco/repo-git/src/server/src/pocketmine/nbt/NBT__64bit.php on line 121
File: /repo-git/src/server/src/pocketmine/item/Item
Line: 695
Type: notice

Code:
[686] 		foreach(Item::$creative as $i => $d){
[687] 			if($item->equals($d, !$item->isTool())){
[688] 				return $i;
[689] 			}
[690] 		}
[691] 
[692] 		return -1;
[693] 	}
[694] 
[695] 	public static function get(int $id, $meta = 0, int $count = 1, $tags = "") : Item{
[696] 		try{
[697] 			$class = self::$list[$id];
[698] 			if($class === \null){
[699] 				return (new Item($id, $meta, $count))->setCompoundTag($tags);
[700] 			}elseif($id < 256){
[701] 				return (new ItemBlock(new $class($meta), $meta, $count))->setCompoundTag($tags);
[702] 			}else{
[703] 				return (new $class($meta, $count))->setCompoundTag($tags);
[704] 			}
[705] 		}catch(\RuntimeException $e){

Backtrace:
#0 /repo-git/src/server/src/pocketmine/entity/Item(83): pocketmine\nbt\NBT::getItemHelper(pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.})
#1 /repo-git/src/server/src/pocketmine/entity/Entity__64bit(273): pocketmine\entity\Item->initEntity(boolean)
#2 /repo-git/src/server/src/pocketmine/entity/Entity__64bit(425): pocketmine\entity\Entity->__construct(pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:4.515169124848E-286.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:-1.5153202040557E-285.}.pocketmine\nbt\tag\LongTag:-7334971955026034892.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:81.61555480957.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.}.pocketmine\nbt\tag\LongTag:1761335983691874945.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:89.738001019006.pocketmine\nbt\tag\DoubleTag:11.pocketmine\nbt\tag\DoubleTag:15.748380071693.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:1240.})
#3 /repo-git/src/server/src/pocketmine/level/format/generic/BaseFullChunk(148): pocketmine\entity\Entity::createEntity(string Item, pocketmine\level\format\anvil\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:4.515169124848E-286.pocketmine\nbt\tag\DoubleTag:-0.pocketmine\nbt\tag\DoubleTag:-1.5153202040557E-285.}.pocketmine\nbt\tag\LongTag:-7334971955026034892.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:0.pocketmine\nbt\tag\ShortTag:300.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\IntTag:0.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\FloatTag:81.61555480957.pocketmine\nbt\tag\FloatTag:0.}.pocketmine\nbt\tag\FloatTag:0.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:minecraft:sapling.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.}.pocketmine\nbt\tag\LongTag:1761335983691874945.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\DoubleTag:89.738001019006.pocketmine\nbt\tag\DoubleTag:11.pocketmine\nbt\tag\DoubleTag:15.748380071693.}.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ShortTag:65535.pocketmine\nbt\tag\StringTag:Item.pocketmine\nbt\tag\ShortTag:1240.})
#4 /repo-git/src/server/src/pocketmine/level/Level__64bit(2475): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#5 /repo-git/src/server/src/pocketmine/level/Level__64bit(2147): pocketmine\level\Level->loadChunk(integer 5, integer 0, boolean 1)
#6 /repo-git/src/server/src/pocketmine/level/Level__64bit(2726): pocketmine\level\Level->getChunk(integer 5, integer 0, boolean 1)
#7 /repo-git/src/server/src/pocketmine/Player__64bit(707): pocketmine\level\Level->populateChunk(integer 5, integer 0)
#8 /repo-git/src/server/src/pocketmine/Player__64bit(1546): pocketmine\Player->sendNextChunk(boolean)
#9 /repo-git/src/server/src/pocketmine/Server__64bit(2413): pocketmine\Player->checkNetwork(boolean)
#10 /repo-git/src/server/src/pocketmine/Server__64bit(2154): pocketmine\Server->tick(boolean)
#11 /repo-git/src/server/src/pocketmine/Server__64bit(2034): pocketmine\Server->tickProcessor(boolean)
#12 /repo-git/src/server/src/pocketmine/Server__64bit(1653): pocketmine\Server->start(boolean)
#13 /repo-git/src/server/src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /opt/minecraft/multicraft/servers/druocco/, string /opt/minecraft/multicraft/servers/druocco/, string /opt/minecraft/multicraft/servers/druocco/plugins/)

**Comment by iPocket** [comment]
crashes*

**Comment by iPocket** [comment]
Please, Please, Please and please close this issue, reason:
This is a PC Map related issue, MCPC saves block IDs as a string not int like MCPE.
like instead of 2, it's "dirt".
You should use some world editing programs and fix it.

**Comment by RocoWayne** [comment]
Can you explain some more @iPocket ? What i need to change with mcedit to fix this?

**Comment by iPocket** [comment]
The block IDs.

**Comment by RocoWayne** [comment]
So, i open the map with mcedit, select each block and replace it with the same block? Im lost here, please help me!

**Comment by iPocket** [comment]
@RocoWayne Yes, but change the ID, you will find it for example Dirt, change it to 3.

**Comment by RocoWayne** [comment]
@iPocket  i select all the map, and analyze it, and i find DIRT (3:0)

I need to replace  DIRT (3:0) with  DIRT (3:0)? Im kind off lost here :(

**Comment by iPocket** [comment]
Replace DIRT with only 3.

**Comment by RocoWayne** [comment]
Well, i remove entities and the map work just fine, but, i have another maps that does not work and i dont kwow that to do

Because, i dont understand how relace for example DIRT with only 3.
