### ISSUE TITLE
Server Crashed Every 20 Hours

### ISSUE THREAD

**Issue by BintangPutra606** [PocketMine/PocketMine-MP#4288]
### Issue description

My Pocketmine Crashed Every 20 Hours And Give Me The Same Crash Dump.
### OS and versions

- Genisys: 16
- PHP:7
- OS:Ubuntu
### Crashdump, backtrace or other files

Genisys Crash Dump Wed Sep 21 03:59:50 EDT 2016

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)
File: /src/pocketmine/network/RakLibInterface
Line: 203
Type: E_ERROR

Code:
[194]       );
[195]   }
[196] 
[197]   public function setPortCheck($name){
[198]       $this->interface->sendOption("portChecking", (bool) $name);
[199]   }
[200] 
[201]   public function handleOption($name, $value){
[202]       if($name === "bandwidth"){
[203]           $v = unserialize($value);
[204]           $this->network->addStatistics($v["up"], $v["down"]);
[205]       }
[206]   }
[207] 
[208]   public function putPacket(Player $player, DataPacket $packet, $needACK = false, $immediate = false){
[209]       if(isset($this->identifiers[$h = spl_object_hash($player)])){
[210]           $identifier = $this->identifiers[$h];
[211]           $pk = null;
[212]           if(!$packet->isEncoded){
[213]               $packet->encode();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: c19e850903e1b39beaa352489651d271b4a32d44 [Protocol 82; API 2.0.0]
uname -a: Linux zkiller 2.6.32-042stab113.21 #1 SMP Wed Mar 23 11:05:25 MSK 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 20 hours 1 minutes 30 seconds
Number of loaded worlds: 4
Players online: 0/20

Loaded plugins:
DevTools 1.11.0 by PocketMine Team for API(s) 2.0.0
TapToDo 2.2.1 by Falk for API(s) 2.0.0
BetterRaw 2.0_BUILD_#5 by Ad5001 for API(s) 1.14.0, 2.0.0
ManyWorlds 2.1.0 by aliuly for API(s) 2.0.0
PlayerSelector 1 by Ad5001 for API(s) 2.0.0, 1.13.0
Chaostix 0.1 by Chaostix404 for API(s) 1.14.0, 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0, 2.0.0
SanteRia-Core 1.7.2 by PocketMine Team, shoghicp for API(s) 2.0.0
Slapper 1.2.9.7 by jojoe77777 for API(s) 2.0.0
ServerAPI 1 by Ad5001 for API(s) 2.0.0
ItemCasePE 1.1.0 by aliuly for API(s) 1.10.0, 1.13.0, 2.0.0
PurePerms 1.3.7 by 64FF00 & ProjectInfinity for API(s) 1.13.0, 2.0.0
XeviousPE-Factions INDEV by 64FF00 for API(s) 1.12.0, 2.0.0
Mentions 1 by Ad5001 for API(s) 2.0.0
EconomyAPI 2.0.9 by onebone for API(s) 2.0.0
WinAPI 1.0.0 by BoxOfDevs Team for API(s) 1.14.0, 2.0.0
SimpleMacros 0.4_dev_#001 by PEMapModder for API(s) 1.0.0, 2.0.0
superBAR 1.4.10 by FaigerSYS for API(s) 1.13.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 2.0.0
MagicWE 0.1.13 by thebigsmileXD for API(s) 1.13.0, 2.0.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 2.0.0
MyPlot 1 by Wies and Exxarion for API(s) 2.0.0
SimpleWarp 2.1.1 by Falkirks for API(s) 1.12.0, 2.0.0
PureChat 1.4.0 by 64FF00 for API(s) 1.13.0, 2.0.0
SimplePortals 0.0.3 by Falkirks for API(s) 2.0.0

**Comment by iPocket** [comment]
STOP POSTING GENISYS CRASH DUMPS!

**Comment by robske110** [comment]
Not genisys specific though. Looks like a ddos
