### ISSUE TITLE
help

### ISSUE THREAD

**Issue by funny076** [PocketMine/PocketMine-MP#4291]
20:01:25 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
20:01:25 [INFO] Loading pocketmine.yml...
20:01:25 [INFO] Loading server properties...
20:01:25 [INFO] Starting Minecraft PE server on 88.141.213.40:19132
20:01:25 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
20:01:25 [INFO] PocketMine-MP is distributed under the LGPL License
20:01:26 [CRITICAL] ***\* FAILED TO BIND TO 88.141.213.40:19132!
20:01:26 [CRITICAL] Perhaps a server is already running on that port?
20:01:26 [EMERGENCY] [RakLib Thread #2988] RakLib crashed!
20:01:28 [INFO] Loading PeacefulSpawn v2.5
20:01:28 [CRITICAL] Could not load plugin 'SimplePortals': Unknown dependency
20:01:28 [INFO] Loading TimeCommander v2.1
20:01:28 [CRITICAL] Could not load plugin 'SimplePortals': Unknown dependency
20:01:28 [CRITICAL] Could not load plugin 'SimplePortals': circular dependency detected
20:01:29 [INFO] Preparing level "world"
20:01:29 [INFO] Enabling PeacefulSpawn v2.5
20:01:29 [INFO] Enabling TimeCommander v2.1
20:01:32 [INFO] Starting GS4 status listener
20:01:32 [INFO] Setting query port to 19132
20:01:32 [INFO] Query running on 88.141.213.40:19132
20:01:32 [INFO] Default game type: SURVIVAL
20:01:32 [INFO] Done (8.485s)! For help, type "help" or "?"
20:01:32 [ERROR] RuntimeException: "RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind addr" (E_ERROR) in "/src/raklib/server/UDPServerSocket" at line 32exte.
20:01:32 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
20:01:33 [EMERGENCY] Please submit the "C:\Users\cococinelle\Desktop\SERVEUR\PocketMine-MP\CrashDump_Tue_Sep_27-20.01.32-BST_2016.log" file to the Bug Reporting page. Give as much info as you can.
20:01:33 [INFO] Disabling PeacefulSpawn v2.5
20:01:34 [INFO] Disabling TimeCommander v2.1
20:01:34 [INFO] Unloading level "world"
bin\php\php.exe: Exit 1

CrashDump_Tue_Sep_27-20.01.32-BST_2016

PocketMine-MP Crash Dump Tue Sep 27 20:01:32 BST 2016

Error: RakLib Thread crashed [raklib\server\UDPServerSocket]: socket_bind(): unable to bind address [10049]: L’adresse demandée n’est pas valide dans son contexte.

File: /src/raklib/server/UDPServerSocket
Line: 32
Type: error

Code:
[23] 
[24] class UDPServerSocket{
[25]     /*\* @var \Logger _/
[26]     protected $logger;
[27]     protected $socket;
[28] 
[29]     public function __construct(\ThreadedLogger $logger, $port = 19132, $interface = "0.0.0.0"){
[30]         $this->socket = socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);
[31]         //socket_set_option($this->socket, SOL_SOCKET, SO_BROADCAST, 1); //Allow sending broadcast messages
[32]         if(@socket_bind($this->socket, $interface, $port) === \true){
[33]             socket_set_option($this->socket, SOL_SOCKET, SO_REUSEADDR, 0);
[34]             $this->setSendBuffer(1024 \* 1024 \* 8)->setRecvBuffer(1024 \* 1024 \* 8);
[35]         }else{
[36]             $logger->critical("_**\* FAILED TO BIND TO " . $interface . ":" . $port . "!", \true, \true, 0);
[37]             $logger->critical("Perhaps a server is already running on that port?", \true, \true, 0);
[38]             exit(1);
[39]         }
[40]         socket_set_nonblock($this->socket);
[41]     }
[42] 

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(143): pocketmine\network\RakLibInterface->doTick()
#1 /src/pocketmine/Server(2216): pocketmine\network\RakLibInterface->process()
#2 /src/pocketmine/Server(2110): pocketmine\Server->tick()
#3 /src/pocketmine/Server(1986): pocketmine\Server->tickProcessor()
#4 /src/pocketmine/Server(1703): pocketmine\Server->start()
#5 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:/Users/cococinelle/Desktop/SERVEUR/PocketMine-MP/PocketMine-MP.phar/, string C:\Users\cococinelle\Desktop\SERVEUR\PocketMine-MP\, string C:\Users\cococinelle\Desktop\SERVEUR\PocketMine-MP\plugins)
#6 (1): require(string phar://C:/Users/cococinelle/Desktop/SERVEUR/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.4.1 #980 [Protocol 20; API 1.11.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT PC 6.1 build 7601 (Windows 7 Home Premium Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
PeacefulSpawn 2.5 by LDX for API(s) 1.0.0, 2.0.0
TimeCommander 2.1 by LDX for API(s) 1.0.0, 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNoDAAAAAAE=
===END CRASH DUMP===

server 
# Properties Config file
# Tue Sep 27 20:01:34 BST 2016

server-name=SERVEUR
server-ip=88.141.213.40
server-port=19132
memory-limit=256M
gamemode=0
max-players=20
spawn-protection=16
white-list=on
enable-query=on
enable-rcon=off
motd=Minecraft: PE Server
announce-player-achievements=on
allow-flight=off
spawn-animals=on
spawn-mobs=on
force-gamemode=on
hardcore=off
pvp=off
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
rcon.password=
auto-save=on

**Comment by Sandertv** [comment]
You have a very outdated pocketmine version, try a newer one.

**Comment by archie426** [comment]
I think, if I am not mistaken, you are running two servers, on the same port at once.

**Comment by TheAppleGamer** [comment]
There are multiple servers running on the same port. If you want to run multiple servers run them on different ports

**Comment by GlitchPlayer** [comment]
@TheAppleGamer @funny076  @archie426 Pretty sure. He is using his public IP to host... Pretty sure you guys are not investigating properly.

**Comment by archie426** [comment]
Yeah i totally knew that, wait, public ip, you should take that off the internet, edit your post.

**Comment by DiegoGTRatty** [comment]
@archie426 as if no one knew it to begin with aka the goverment.
