### ISSUE TITLE
Server Crash Allowed memory size error

### ISSUE THREAD

**Issue by brentb2529** [PocketMine/PocketMine-MP#4293]
### Issue description

Server Crash while running with 0 users actively connected.
### Steps to reproduce the issue

Server running for about 72 hours under very low usage load.
### OS and versions

PocketMine-MP version: 1.6dev #0 [Protocol 83; API 2.0.0]
PHP Version: 7.0.3
OS : Linux, linux
### Crashdump, backtrace or other files

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 131072 bytes)
File: /src/pocketmine/nbt/NBT
Line: 499
Type: E_ERROR

Code:
[490]           }
[491]           return $this->buffer;
[492]       }
[493] 
[494]       return false;
[495]   }
[496] 
[497]   public function writeCompressed($compression = ZLIB_ENCODING_GZIP, $level = 7){
[498]       if(($write = $this->write()) !== false){
[499]           return zlib_encode($write, $compression, $level);
[500]       }
[501] 
[502]       return false;
[503]   }
[504] 
[505]   public function readTag(){
[506]       switch($this->getByte()){
[507]           case NBT::TAG_Byte:
[508]               $tag = new ByteTag($this->getString());
[509]               $tag->read($this);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

===BEGIN CRASH DUMP===
eNrNWWtv4zYW/StcZ4AmC8ux/IxVpECapt0B5pGdZFBgmyKgJcrWRhJVkYrjKfrf99xLSlYy6X7Y
3Q87HUxN8vK+eO6D1O8DmxVqEIWz5Xwym64ms+FA1bWuB9HvA7uvsDS4ur/69Onjp8FwUChj5Ibm
LvJc71QiClXoei9M9kUJnYpwvJwuZ+HZZCbWe6uMUE9b2RgLymNbZ/if1UJibyytEuEU9BNHeQL2
aZYT71NTx6eVjh+ULbJSnZZre/rh+1sQ5BgOotlq9cdwUOXNJisHUSpzo4aDWCeKdJ6txmBxZ+m/
P7Bltgq7ca1sU5fijd1mJvhu3aSpqr9lmomncTumGPGPmZ/2G1mU2zDnFUe+aMmXPFk16zyLRdqU
sc10KXZ1ZtWlLqoa3lPJ8ZvY/6bFc/GPd2+/v7/6cPnxh7cffrr/6R9vr4fiTa4eVY7F5cnvzPnM
K5Klx8dvmCEWvR08PD45EX85P3cq+k2rl4Z/ybP1vSrJVZ4LRPW0aQWfkI3z8bjnlPk4dFbOx5M/
ccp8PO2cMh/PWvL5q06plUxu5eaYVZ2PF56n2WU23h57yzbKfr9n2xzVsjMolkYJYCKKbi9+uiei
iCnOOoo7+8bKDbxUqp0gApJ24HsDNJYQ701dvdgXfEcKOnqQAG62ljEA9svgaCyOTyJxwOfd3Y2q
H1UdfBfX0mx/aIrqeK11rmR5Mvh1ONioUtUyJ3CCivwMYeFokahHyF43WZ4MojEAXWurYw3Cs+lw
IKsMZJPReDQG1SazGMmzJE5Xq9kymc4my2U6D8PFMoznizAOz1KE0iJZz8ZThQ21fMBhY894dMYc
mlJSnA/eZWXzJNa1Km0Q4x9tgrmYjkLICSaT1SgMR+FI5cvR09nifjETR6G4eX8tbreNuGg2YiHG
YTReROGZ+Hx7KSbjcC4cJWRU2woSltB5itEXVcKwwdSbgMV7bVoNMMGDnAddOGPqF7iskjW0tfCW
Gxt28AgeqlRtM0U7j667kbjUZZptBOWPu/quPHoPhN2oSkwWIpxH00U0CVt1F0Tg+AXkkvPvVYn8
VPamK13b83AVTic0uZGU4xJ1HtKokE9Blcs9VDufjnlTJXdlQIenGNrnARPutgivIM+MPddpSjOq
lOtcBb81qt6/mKtj7PNThbbJ+XvgCmhKbSSur4TDFy3KstQIIeV1CGS8zRCxBQ7SnGs2grLrLkjz
bLPtRDsdZZkVCFZP5+YKvW4nUl2DcWeu37qVdRLruhtXj5WnT7I0zeImt3vnGodzq+vAKGsRXeac
pjmjOFfvdJ0nhzmjVNIjoWpz/sPVjxef393SLDllVEljsC05/yv/gXmN1YGRj8prQcjqQnG0L3KC
hngvs1LEjIoGOlHGIXAI2CiumZw8HLy/BliAbYVs0iotZK2E3aKclUCW3UorYnK7FWslsjLOmwRl
DOy/AiXxutEFF0L7NU8jU+RbjZXaEEsKQvkg9rqpPS+RpQK+z9KMJcDtNTCV74nxB6Sxlt1polIJ
xxux0+U3VsiqUrIW5JoCxsaAwB7qC8pezu7dVpWiqTa1TMBgdFcS2B2z6K4UR7fbWgGtmIIWuSw3
Dcq8oELBLvOBYTKMqXbn2Rd2Km293KrYW/F8IxTYWluZ6PRUlaNd9pBVKsnkSNebUxqdvkNw3Ov0
/u3Nx/vFdBVM7mkf3NgxisTdQJWbuwEJ+nmryHfUQRikFmojhOE0jmOqZWlyaV2D4b3JmkIP/FKW
jxQpN4uV2MoyyfmQCzB2uD+I5IKGebNtbKIpRlzXQ8q4SBRxrlHJnVrcCQkKdGgifBoTj5kUf6dI
BwlHfOBXIujaEPujmy32SUKpQbEQXoo7KukZicYAhIlChY7Zuovrt6C0W52Qnw4LAdRaQ6kD+ytO
LS0fWCwojAXgCkSQquu98DgCuU9E3erBDUc/Z3C0LgEpmSQo3MYhj9QE1h6gjjRNzTlIAG9rRf6A
09VvjczpODbZI2gfZd4ocexFIhWfgLmThwSoKOkGOM3NRtURVknyh6ZYw9sIpwuzL+NbaR6A+PoB
ATSi9c84BMZnayRRbWuNHAlIgNoMBecc4XMT9zj99ovcslNrmiuaEpFDJMz7hiEDexBctX5C5rQK
LoA5DPWyU4286tR5m1KEcoeLSByKzH4Dz9madyWK6gOj8MVecQwLcM5iQh5hGwJvZcScKFpdn82x
+lOu13Cs0alt2+88KzJLOalQG8nt9EjcOFXGLDwzdLwu0mHTLmPF2NmCyoXj0/rfsF/SDHBBmkJy
LplVihzRSnTHD2MaBu1Gww5NoUE+g5wNKxmwYpEY33Gq4Kxst9Ra/Z+rX0DTf6M8FcX/SnljdcXy
farq9PHcjEBIUe1DlvHakMxWpXA8mTmtrlWdaS5HFIuGBMackL12XbyFEIVUkxDGmCJAPCgXaZzG
dYkEhgiF3yg7/JlbnTvR3eSc4SnWHdkdF1zigeg7RLJLRyThI6UQqnBMPvqamMx2eSiBCysVUyE0
7BbS1fnY7e0MgCdVZQ5mTsfeTnPyqkLe6qmzeiPrNc4/QNedu+6NIuxVrzKcSBW/R/g9iN1Clg2X
3L4WaEcautYO25zwAgweDS6v4iLqc0NxQNlIfHT1jkdAxFY3edIpkiGD7EpxUJ1wKyrWHAYuxmNn
ozj6kSPhq9zIWHG7O6PSWhdtiqW9fj3oZ6XemcIIf3QvofAKfnr7qIuOt035YJy/3zHqKSHyJGmW
a8QZrBGu0x1yeNZoQIwjCqgHoF7mwItYtcfsA2W18Hr+oN22l8dHRYA6Jbetz8FJ8WT/A5u5EAUx
OnblrPZYaAXRQle9/y2ru7JUls6ia90AjdxVwrXE/ZkbEUldLgog8OSzEgega0z9qktGa9XVRE43
R/301a5Q4Nd7S7yHIgh7YKbax2ID26qCtDJfuKxyqLXuTaOhms3pzh+g24tJr9NI/A1XF7j3HL0w
gHt5/XmIvdBgjfyzyxK7dVmb47tjHzD7SCx9Y3BoGQw7pkc6EhcJ4mkr8/QUTb7rYhIFnHlBEOnw
p8t+QHbVucer1yddPVHwURsk86ELbBL8c1aii4RZgI1iaFOt/3xdXredwqFnpyaINu2Q6++oYS+r
wA/7PRnuXmrdbNzxa58zBVWLmgGtnlTcuGaHkg9dxEfdqiFEcA+DG/koKzNSI/T9y3cipL7FFylq
UFlS25zyXkpTvmm986caOQau5TTi1FhpG2DvdBO7U0KKTExP//YC+OwKotp+lFwAp7jLF5N6pJLn
GDsxzsMyWP2WwG2JRIGljb+awCCKGWr5SqAXeOf8Jp/xRxKmy53tiYdD7NfacLgzCo4+fLy9igQn
cPyNm5qeU3B+xCgrqpybYVbPS+7U69By8ezgY1xJkJS8rQxIrm7QhABoCYSTsa9GlBVdkSNE0n2Y
5n1l8wnk+XSbDl1bfUORTwau6RXtIOw4RMy9ImUoJlgIX1tQNh6dcPwb1deC4XBLnOmW5h9MhEKO
c/Koi3Anyffhw0WZcgpfqKgRo8wi853cG8fb8+nh6FkpYBhdFLop+7XE+PavVYLUJ250+0Cap5+R
mP35VlljNnG6Ox7PC5gIV5NXdzO6SuWupGvluK1VSkmNH18o+dExdFzdk0wvi7okeiMfEd3UKmZ0
81Z0k6v2/pXBl7WuN+Kck0pj2avsF58R0yZnMm0A1YBCNItdVeLbXE1XewADbFtX/VPTpcrFhpEF
YaXgtEu1qrP/xWGQQ9vDeC+fhHzpF1ynYi41Bzw8PwsG6SeZZI3pbfPnIL12HKRuq8cd0aPxoZxE
b19BUyXA4kFB3NqVdEL4Xe5QUJ3ihztiq/voa+V9/tvJjK/7uNo3yp+v389hz/MBfRWJxNl/xK3S
VZN7bv43VbkXjO9KjskA3iOl3QtfwDgy5ElyZaHpgbPuZkOfHugRLRKuT2yPlB6tmwp9k2seHSA5
ebiexfMClyXt8gKJ6ZyGO0mCukmek8U6A/IdiX+/c9f9yCUjepmgh3PhZl259iBx6PWXgi65Ea4D
eit6PtOVk2ezqHJZmeoDDLaazp5FjnpPh+ipWL9Sl/uCbgwcIQb+NZ2idAXyy+KwzAoDa1LIzQbV
x78zdC841G7S54OH161x+hA785o+5C8HZT7il7uBCbcauQOoy8AX50MzybO66r09XdLzI7+HqVxX
VK2GGMMCeuyzbVeHJidF063gbNSnkuo8EfnS2tDpIB57TIT/wNHrIRr0rsa6AtcmPM+NTsgtt/zN
C6fsdrvXXJJnKDfuVK6eJNVbN6CGBfy9ElGrDS8B7HTpjsQv9DNAkRnyLfxX4uiyYNuG9B9u2Yj2
6uHuf+0zN/dWr70D8z2Zq5jhjoHMLtBIZFDUl/ie6iyVFeBfgl7FKXS5JB2kReLHdxe30eTb5XC+
egqH06fpcPJt+G2CSuyy1rGtFQbIMOdnY7EBvo0bzeYn/E6unqwqySGGvkVdog71vtYQhHrDKn62
an7LM6um/D1pGbgvV1/cB6aWZB2jndn2JujxtUxk3Z/yX5S7cVPnvWGa5UB5f8L2Pyhtkv6g6C9t
Ecz8VY2+NP3T+E9sMx4Wa/dK3CNHk7ivbG/i5vrdM+PRzfWtt5IM6YuvtMme+mN/S+cPXuFojqlP
KvU3zD6rbaH7ihtGt+nrtoez+cuZ/yXmWAkn5HUR8Be38Wy8xM83bwGUdL5S6+VimapwKReL5Wp+
tlrP4/FykaxSeXaWTJMZ6uxYvAHv6y0fB31VnGBo9YMqUUr6Lv9ZyQeEPZ/0lKn2kj+q8KfIT5dL
OvmsYv+GU+dg0jPrePzxx78AuPQqWA==
===END CRASH DUMP===

**Comment by iPocket** [comment]
Duplicate.

**Comment by ChaostixZix** [comment]
I had the same problem

**Comment by brentb2529** [comment]
ChaostixZix, did you resolve it? 

Thanks.

**Comment by PrimusLV** [comment]
You have to give server a rest. Just restart the server.
