### ISSUE TITLE
The Server is full!

### ISSUE THREAD

**Issue by Iceyascool** [PocketMine/PocketMine-MP#4294]
### Issue description

I used my Ip address to join and port forwarding is done but when i tried joining in, "Server is full!" pops up immediately...PLEASE HELP
### Steps to reproduce the issue

1. Install the PocketMine in PC
2. Port Forward my ip address
   
   3.Copy Ip address in my internet connection
   
   4.Paste Ip address in the minecraft pe ip address box in create a new server
### OS and versions

- PocketMine-MP: 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
- PHP: ???
- OS: Windows 7

**Comment by PrimusLV** [comment]
Incompatible server and client

**Comment by LargeArt7338551** [comment]
Another solution is to go into the server.properties file and change the amount of player slots.

**Comment by archie426** [comment]
@LargeArt7338551 I can see why u thought that, although that is not the problem, this should probably be changed, is there a file for these errors?

**Comment by GlitchPlayer** [comment]
@LargeArt7338551 @archie426 You guys read books can understand them right? Better read the version then. He's using the old version of pocketmine -__-
@Iceyascool Use the latest version of pocketmine

**Comment by tiNsLeY799** [comment]
I tried getting help with this, as well. Trust me, I got shot down as well. Same responses.
Try running a different server that isn't PM-MP. It fixed my issue, then try to use PM-MP again. If it doesn't work, try asking a dev..

**Comment by azon0320** [comment]
But how to explain this problem that shows 'Server is full' in-game without starting Server in any PM versions?

**Comment by SOF3** [comment]
Please read the README. Project is moved.
