### ISSUE TITLE
Using Genisis: PHP5 plugins working, except plugins that are downloaded in folders. That means I cant use mini games, or slapper. (which I really want.)

### ISSUE THREAD

**Issue by LargeArt7338551** [PocketMine/PocketMine-MP#4295]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by LargeArt7338551** [comment]
If anyone can help me on this I would really appreciate it! Thanks!

**Comment by LargeArt7338551** [comment]
And just for kicks, Im using pocketmine php7

**Comment by robske110** [comment]
This is no issue at all, please close this and go to forums.pocketmine.net for help.

**Comment by dktapps** [comment]
-_- why do people insist on submitting Genisys issues here...

**Comment by archie426** [comment]
omg, why do people always do this, why does no one listen. JUST GO TO THE FLIPPIN GENISYS REPO, this goes for everyone and was the last straw, and in rage cause of java and N##### (this is not advertissing)

**Comment by LargeArt7338551** [comment]
Im sorry I did not realize.

**Comment by LargeArt7338551** [comment]
My 15.0 Phar File is Genisis, everything else is pocketmine.

**Comment by archie426** [comment]
yes that is the only change genisys makes
that is why it is genisys not pocketmine, the src is compiled into .phar
