### ISSUE TITLE
please Pocketmin-pk.phar for version minecraft 0.16

### ISSUE THREAD

**Issue by MarwanEA** [PocketMine/PocketMine-MP#4299]
### Issue description

Write a short description about the issue
Hi want pocketmine-PK.phar for my version minceraft 0.16.0
### Steps to reproduce the issue

1. ...download new PocketMine-pk.phar
2. ...
### OS and versions

- PocketMine-MP:last
- PHP:last
- OS: Android 4.2.2
### Crashdump, backtrace or other files

- ...(nothing)

**Comment by Dog2puppy** [comment]
Go to pmmp/PocketMine-MP

**Comment by MarwanEA** [comment]
Thanks for your comment
But i am new , i don't know how i can download file "pocketmin-pk.phar" (minecraft 0.16.0) in my tablette
