### ISSUE TITLE
How i can know the ip and port of my server

### ISSUE THREAD

**Issue by MarwanEA** [PocketMine/PocketMine-MP#4300]
### Issue description

Write a short description about the issue
### Steps to reproduce the issue

1. ...
2. ...
### OS and versions

- PocketMine-MP:
- PHP:
- OS:
### Crashdump, backtrace or other files

- ...

**Comment by badp1g** [comment]
In plugin? 
Ip: $_SERVER['REMOTE_ADDR'];
Port: $this->getServer()->getPort();

**Comment by GlitchPlayer** [comment]
Google is a nice person to ask

**Comment by DiegoGTRatty** [comment]
@GlitchPlayer 10/10 

You can use google to search your external IP. It should be able to tell you right away.

As for the port, if you didn't modify the setup files, it SHOULD still be the default port (19132).

Also, you should go to this link my freind: https://github.com/pmmp/PocketMine-MP
