### ISSUE TITLE
API Incompatible?

### ISSUE THREAD

**Issue by Rioji101** [PocketMine/PocketMine-MP#4302]
### Issue description:

So i downloaded a few plugins like adminfun, signshop and some other stuff but when i started start.cmd it said (?) that only adminfun loaded and started working. all the other plugins had text stating Incompatible API version. I looked at other posts like these and there people said to go use http://pmt.mcpe.me/api2/ but that didn't work, it said404                                                                     Not Found

nginx/1.4.6 (Ubuntu)
### Steps to reproduce the issue:
1. Download plugins (I dont know if my plugins were the cause, but here is a list of plugins i wanted to use

CrateKeys'
'EconomyAirport'
 'EconomyAPI'
 'EconomyAuction'
 'EconomyCasino'
 'EconomyJob'
 'EconomyLand'
'EconomyProperty'
 'EconomyPShop'
 'EconomySell'
 'EconomyShop'
 'EconomyTax'
 'EconomyUsury'
 'ItemCloud'
 'KitPro'
 'MoreCommands'
 'Pundler'
 'RankUp'
 'SignShop'
 'VanishNP')
2. Start start.cmd 
3. Results should be there.
### OS and versions

- PocketMine-MP: 1.6dev [Unleashed]
- PHP: I don't know if this is supposed to be API or something....
- OS:No clue..
  This server is running PocketMine-MP 1.6dev 「Unleashed」 implementing API version 2.0.0 for Minecraft: PE v0.15.10.0 alpha (protocol version 84)
  ### Crashdump, backtrace or other files
  I don't really know what to put here.... The server log?
  It just says (?) [Server thread/ERROR]: Could not load plugin 'Crate Keys': Incompatible API version (For example)

**Comment by Rioji101** [comment]
![untitled](https://cloud.githubusercontent.com/assets/23150143/19836685/d53998b2-9eb0-11e6-8c81-0e4d3c613d48.jpg)
By the  way this is a screenshot.... Kinda.... Well this is a screenshot i took of the plugins folder if anyone needs that...

**Comment by Rioji101** [comment]
![untitled](https://cloud.githubusercontent.com/assets/23150143/19836707/6b7cf8a0-9eb1-11e6-85d5-818cfe386688.jpg)
This is a PrintScreen? I took of the pugins folder...


![untitled7](https://cloud.githubusercontent.com/assets/23150143/19836717/d353b82e-9eb1-11e6-9551-4c0addcfaf71.jpg)
And this is a PrintScreen i took of my PocketMine folder.

**Comment by SOF3** [comment]
API incompatible means API incompatible. What else do you expect? Do you report to Nokia saying that you can't install WhatsApp on Nokia 3310?

**Comment by Rioji101** [comment]
Still... Economy and those EconomyShop things say they support 2.0.0 and i have 2.0.0

**Comment by GlitchPlayer** [comment]
You only got the version of plugin. Not the API version

**Comment by GlitchPlayer** [comment]
Economy still use old API.

**Comment by IISweePII** [comment]
Alternatively you can edit the .yml to load on API 2.0.0 - 2.1.0, but that is not recommended as the code is outdated (like in 1.14.0) and it may have issues. Try getting a new version of the plugin that supports API 2.0.0+
