### ISSUE TITLE
Keep getting deopped.

### ISSUE THREAD

**Issue by darkshredder11** [PocketMine/PocketMine-MP#4304]
So I'm using an app called plug pocketmine. (I don't believe it's created by pocketmine-mp devs but it still uses their server core according to my knowledge.) and I had a problem when I joined the server. After I joined, I used the in app console to make myself op. But whenever I leave and rejoin I am no longer op. (I can't use most server related commands) wha can I do to fix this?

**Comment by GlitchPlayer** [comment]
Plug Pocketmine is highly modified by their devs. Yes, plug pocketmine uses
the pocketmine core but in different way. I recommend you to report this to
the plug pocketmine devs. 3rd-party pocketmines are discouraged.

Also, The pocketmine project is moved
