### ISSUE TITLE
Couldn't find a working PHP 7 binary, please use the installer.

### ISSUE THREAD

**Issue by nurbu1** [PocketMine/PocketMine-MP#4306]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by iPocket** [comment]
lol

**Comment by XDqrkneZ** [comment]
Mmm... I get that message too but I am on Centos 6 64 bits. I've tried re-installing but nothing happens :/ idk bro sry I'm stucked there too

**Comment by eugene-piatenko** [comment]
Same problem
Just installed and run ./start.sh

1. Just installed by >> wget -q -O - http://get.pocketmine.net/ | bash
    Then run >> ./start.sh

2. OS: Ubuntu 16.04.1 LTS
Linux dev 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hihihoholalalolo1227** [comment]
Yes

**Comment by XDqrkneZ** [comment]
Eugene that didntI work either :((

**Comment by josenj** [comment]
I got it working by opening up start.sh with a text editor and replacing php7 with php5
