### ISSUE TITLE
Not able to craft in 16.2 pocketmine server.

### ISSUE THREAD

**Issue by AutoGrind** [PocketMine/PocketMine-MP#4308]
### Issue description
Im able to craft tree blocks into wood blocks but once I have wood blocks Im not able to craft any further, for example a crafting table.

### Steps to reproduce the issue
To reproduce Its pretty obvious, try to craft a crafting table out of four wood blocks.

### OS and versions
* PocketMine-MP: Hydration implanted API 2.1.0 for MCPE 16+
* PHP: 7.0.3
* OS: Google Pixel Android 7.1 and same issue on Android 6

**Comment by dktapps** [comment]
omg... are you seriously stupid?

a. this repository is dead
b. this is NOT THE HYDRACON REPOSITORY.
c. read the damn README.

**Comment by SOF3** [comment]
@dktapps it says "Hydration implanted API 2.1.0" not "hydracon implemented API 2.1.0" ;)

**Comment by dktapps** [comment]
@SOF3 well, that either means Hydracon or... nothing else, since Steadfast doesn't have API 2.1. So I took a guess.

**Comment by IISweePII** [comment]
Try using a different server software to run your servers on (that is in PHP language), this repository has not been updated within a while so many stuff is behind (you can try using Pmmp or Genisys or some other useful software)

**Comment by SOF3** [comment]
Genisys will no longer be under active development.

**Comment by AutoGrind** [comment]
dktapps your just an asshole to the others thanks for the help

**Comment by dktapps** [comment]
@AutoGrind You have a nerve calling _me_ an asshole for submitting an issue related to **third-part-modified** builds of PocketMine at the original repository.

**Comment by SOF3** [comment]
@dktapps He said **your** just an asshole. I suppose it is a grammar mistake; it means "your asshole is just an asshole". This is perfectly true, and I think it is a compliance for your alimentary canal's health.

**Comment by AutoGrind** [comment]
no i called him an asshole and meant it. yeah i made a mistake with putting it in the wrong repository but it didn't deserve being called stupid as dktapps did
