### ISSUE TITLE
Installing PHP7 for MAC OS X

### ISSUE THREAD

**Issue by Anoche** [PocketMine/PocketMine-MP#4311]
When trying to download the latest PHP 7  for mac (posted 5 days ago at https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries#files) it says when i press 'enter' : -bash: /Users/ianjacobesquivel/Downloads/PHP_7.0.13_x86-64_MacOS (1).tar.gz: Permission denied

**Comment by EnderNator10** [comment]
seemed like u need to reinstall ur OSX late reply i know
