### ISSUE TITLE
Anyone have phar files and php files for 0.16.0?

### ISSUE THREAD

**Issue by Anoche** [PocketMine/PocketMine-MP#4312]
please comment the link for the 0.16.0 phar files. Latest one on bintray is outdated

**Comment by SOF3** [comment]
Project already moved to https://github.com/pmmp/PocketMine-MPM

**Comment by dktapps** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/README.md

**Comment by Anoche** [comment]
@SOF3 how do i start a pocketmine server with these files then?

**Comment by Anoche** [comment]
@SOF3 Do i just download the whole thing and do the normal ./start.sh ?

**Comment by SOF3** [comment]
Read the README!
