### ISSUE TITLE
Couldn't find a working PHP 7 binary, please use the installer > Ubuntu 16.04.1

### ISSUE THREAD

**Issue by benyanke** [PocketMine/PocketMine-MP#4314]
### Issue description

After installing the server using the described method, it can't find the php binary. 

### Steps to reproduce the issue

1. Sudo apt install perl gcc g++ make automake libtool autoconf m4 gcc-multilib
2. Download and run startup script for linux (http://get.pocketmine.net/)
3. Run ./start.sh
4. "Couldn't find a working PHP 7 binary, please use the installer."

### OS and versions

* PocketMine-MP: Most recent
* PHP: included in download script
* OS: Ubuntu 16.04.1 LTS

**Comment by dktapps** [comment]
This repository has been abandoned for various reasons, it is now located at https://github.com/pmmp/PocketMine-MP.git

Useful links:
https://github.com/PocketMine/PocketMine-MP/blob/master/README.md#weve-moved-head-over-to-here-to-get-some-goodies

https://forums.pmmp.io/threads/get-pmmp-io-for-linux-macos.243/

**Comment by benyanke** [comment]
Thank you! I wasn't aware of the move, I'll try and set it up. Thank you for the info!

**Comment by benyanke** [comment]
Is there any reason this repository (and it's website) haven't been redirected? I know I had no clue abbout the new repo, as i'm an old pocketmine user, and I doubt I'm the only one.
