### ISSUE TITLE
Logged Out due to login timeout

### ISSUE THREAD

**Issue by Thehiyahiya2222** [PocketMine/PocketMine-MP#4315]
Every time I try to join a plug pocketmine server that I made, it always shows up with the error "Login Timeout". I am using no plugins.

OS: 10.2
Pocketmine: 2.21
Minecraft: 1.0

**Comment by Driesboy** [comment]
use pmmp

**Comment by Driesboy** [comment]
os 10.2?
pocketmine 2.21?

**Comment by Thehiyahiya2222** [comment]
I can't download pmmp because I am on an apple device (iOS 10.2)

**Comment by Driesboy** [comment]
? jailbreak?

**Comment by Thehiyahiya2222** [comment]
None of the jail breaks I have tried worked because they are all those "Take a survey" or "Download this app". Any jailbreaks you would recommend?

**Comment by Driesboy** [comment]
pagu

**Comment by Driesboy** [comment]
but they dont have a ios 10 update
