### ISSUE TITLE
Ubuntu 16.04 error with server need help!!

### ISSUE THREAD

**Issue by Morrilack** [PocketMine/PocketMine-MP#4316]
[Description]
Hello I recently just started to look into how to setup a MCPE server on Ubuntu 16.04, but it seems I have come across an error. Before it said I needed to find the right PHP file to run it and I found them .7 version of it well there where several; I've have attempted to use different versions of the PHP files but everyone seems to give me this error can someone please explain to me what is going on and how to fix it?

[Error I am having]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/linuxserver/pocketmine/PocketMine-MP.phar/src/pocketmine/Server.php on line 71

**Comment by Morrilack** [comment]
I need the most recent version of the PHP/downloads for the most recent version of minecraft pocket edition if possible

**Comment by robske110** [comment]
https://jenkins.pmmp.io/job/PHP-Linux-x64/lastBuild/ 
Latest linux 64bit php bin 7.0.x

https://jenkins.pmmp.io/job/PocketMine-MP%20Dev/lastBuild/
Latest offically built phar [Versions as of Mon9Jan mcpe 1.0.x api 3.0.0-ALPHA2]

New GitHub repo: https://github.com/pmmp/pocketmine-mp

For more questions please open a thread on forums.pmmp.io or read rtfd.pmmp.io or read instructions on pmmp.io!
