### ISSUE TITLE
How to do /give with tags?

### ISSUE THREAD

**Issue by CaptainRalph** [PocketMine/PocketMine-MP#4317]
Hey guys, I forget how to use /give with tags. Can anyone please tell me how again?

**Comment by hihihoholalalolo1227** [comment]
?

**Comment by hihihoholalalolo1227** [comment]
Just use anvil

**Comment by CaptainRalph** [comment]
It's not working, the item disappeared when I choose the item

**Comment by CaptainRalph** [comment]
I mean, when I put them in my hand

**Comment by TheDeibo** [comment]
If you read the repository README.MD, you'll notice that this repository is no longer maintained, and that all issues are to be sent to http://github.com/pmmp/PocketMine-MP/issues

Other friendly links:
http://pmmp.io
or the forums:
http://forums.pmmp.io.

**Comment by CaptainRalph** [comment]
I think I know how. Example; /give PianoRalph04 397:3 64 {display:{Name"SteveHead"}}
