### ISSUE TITLE
World field to open stream

### ISSUE THREAD

**Issue by seby162119** [PocketMine/PocketMine-MP#4318]
Problem on Linux:
I put map in world but I see this
Warning: file_put_contents(/home/test/worlds/Hub/level.dat): failed to open stream: Permission denied in /home/test/src/pocketmine/level/format/generic/BaseLevelProvider.php on line 128

**Comment by TheDeibo** [comment]
If you read the repository README.MD, you'll notice that this repository is no longer maintained, and that all issues are to be sent to http://github.com/pmmp/PocketMine-MP/issues

Other friendly links:
http://pmmp.io
or the forums:
http://forums.pmmp.io.
