### ISSUE TITLE
the server is outdated!

### ISSUE THREAD

**Issue by hihihoholalalolo1227** [PocketMine/PocketMine-MP#4319]
the server is outdated anyone please give me the 1.0.0 server link

**Comment by SOF3** [comment]
Someone give me the _Homo sapiens_ server link please.

**Comment by hihihoholalalolo1227** [comment]
Plz

**Comment by TheDeibo** [comment]
If you read the repository README.MD, you'll notice that this repository is no longer maintained, and that all issues are to be sent to http://github.com/pmmp/PocketMine-MP/issues

Other friendly links:
http://pmmp.io
or the forums:
http://forums.pmmp.io.

**Comment by MrClever** [comment]
Which is all nice, except jenkins.pmmp.io is returning 522 (timeout) errors
so no installations are working at the moment.

Cheers,

James
