### ISSUE TITLE
Pocketmine Logged out due to timeout

### ISSUE THREAD

**Issue by abigdog44** [PocketMine/PocketMine-MP#4320]
Hi, I have been trying to use pocketmine on my computer and every time i try to connect via phone it says in the console...
Player has logged out due to timeout

I not able to get in the game either!
Plz Help

**Comment by hihihoholalalolo1227** [comment]
I even worse I join and the server crash but just me

**Comment by TheDeibo** [comment]
If you read the repository README.MD, you'll notice that this repository is no longer maintained, and that all issues are to be sent to http://github.com/pmmp/PocketMine-MP/issues

Other friendly links:
http://pmmp.io
or the forums:
http://forums.pmmp.io.

**Comment by simonlange** [comment]
and which is?

**Comment by robske110** [comment]
???

**Comment by daniktheboss** [comment]
Potato

**Comment by robske110** [comment]
Tree

**Comment by daniktheboss** [comment]
Pineapple

**Comment by TheDeibo** [comment]
Guys, We no longer use this issue tracker. Please view #4321 for more information

**Comment by dktapps** [comment]
Deibo

**Comment by robske110** [comment]
dktapps

**Comment by dktapps** [comment]
Bacon!

**Comment by TheDeibo** [comment]
![image](https://cloud.githubusercontent.com/assets/10010369/22855051/523f6dac-f071-11e6-9bf7-2d642c1999bb.png)

**Comment by daniktheboss** [comment]
... shoghi 😭
