### ISSUE TITLE
I WILL F**K SHOG!

### ISSUE THREAD

**Issue by ghost** [PocketMine/PocketMine-MP#4322]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...
DONT GIVE UP POCKETMINE OR I'll FK U

**Comment by TheClimbing** [comment]
You know... They literally spammed everywhere that PocketMine-MP has moved... Can't you read ReadMe?

**Comment by dktapps** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/4321#issuecomment-276606697 ¯\_(ツ)_/¯

**Comment by SOF3** [comment]
I would like to see you doing that. Mind sending me a video after you do?

**Comment by 13358172372** [comment]
@SOF3 love u

**Comment by 13358172372** [comment]
@shoghicp

**Comment by 13358172372** [comment]
@Scallop

**Comment by 13358172372** [comment]
@yescallop

**Comment by dktapps** [comment]
Too late for this sadly. He's already fucked.
