### ISSUE TITLE
"Could not load plugin '-----': Incompatible API version"

### ISSUE THREAD

**Issue by winterbuild7074** [PocketMine/PocketMine-MP#4323]
### Issue description

What can I do to fix this errors? The plugin won't load.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 1.6.2dev
* API: 3.0.0
* PHP:
* OS:

### Crashdump, backtrace or other files

[Server] Server thread/ERROR Could not load plugin 'MyPlot': Incompatible API version
[Server] Server thread/ERROR Could not load plugin 'VoteReward': Incompatible API version

**Comment by SOF3** [comment]
#4321

**Comment by hihihoholalalolo1227** [comment]
me too

**Comment by infinity-pe** [comment]
Close this - I fixed the problem already.

**Comment by jojoe77777** [comment]
@infinity-pe only you can close it.

**Comment by NFGamerMC** [comment]
Found out how to FIX,
Just extract the .phar and change the API version, then just compress the file again and place in /plugins

**Comment by jojoe77777** [comment]
@NFGamerMC 🤦‍♂️

**Comment by MinuhaFire** [comment]
:)
