### ISSUE TITLE
Outdated server – How to update?

### ISSUE THREAD

**Issue by winterbuild7074** [PocketMine/PocketMine-MP#4324]
### Issue description

Every time I try to connect to my server
`Cloud not connect: Outdated server!`

How can I update? Plus, I cannot find a PocketMine-MP.phar file in my FTP.

### Steps to reproduce the issue

Trying to connect to the server

### OS and versions

I don't know any of these, I cannot get into my server.
* PocketMine-MP:
* PHP: 
* OS: iOS only - Windows 7 Computer

### Crashdump, backtrace or other files

`[Server thread/INFO]: [/80.187.122.129:27172] logged out due to Outdated server!`

**Comment by remotevase** [comment]
https://github.com/pmmp/PocketMine-MP

**Comment by remotevase** [comment]
#4321

**Comment by nopenothing** [comment]
Woah why did you leave your IP in that

**Comment by robske110** [comment]
Because noone fucking cares about IPs. They are not the ultimate key to your computer.

**Comment by AndresKiros** [comment]
Please help! Im having the same problem!!

**Comment by AndresKiros** [comment]
@infinity-pe

**Comment by AndresKiros** [comment]
I figured it out! my pocketmine is working!
This is what I did:
I downloaded the newst php form poggit (where the pocketmine team is operating now!) 
https://poggit.pmmp.io/r/2038/PocketMine-MP.phar
I placed it my server folder then I just ran it!

**Comment by remotevase** [comment]
Once again, @AndresKiros see #4321.
