### ISSUE TITLE
Water not flowing from ocean

### ISSUE THREAD

**Issue by ZizzyZizzy** [PocketMine/PocketMine-MP#4326]
### Issue description
When breaking blocks near an existing body of water, like the ocean, water does not flow into the now empty space.

Pouring water into empty spaces causes water to flow as expected.
http://i63.tinypic.com/rbl4c3.png

### Steps to reproduce the issue
Walk to any body of water and break a block at water level.

### OS and versions
* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.3.0 (protocol version 101)
* PHP: 7.0.15
* OS: CentOS 6.8

### Crashdump, backtrace or other files
N/A

**Comment by dktapps** [comment]
This is long since fixed on PMMP PocketMine-MP. Also, you found the wrong issue tracker.
