### ISSUE TITLE
BlueScreen

### ISSUE THREAD

**Issue by HundredthJam** [PocketMine/PocketMine-MP#4327]
When you join (this happens to everyone including me) the server doesn't take any commands even /help e.t.c and you're stuck in the middle of nowhere (with a blue screen) (or dark blue if it's night) you also can't see any players or blocks. And the biggest issue: you can't walk, run, jump, crouch, e.t.c! It's not a world generation issue because I usually wait about an hour (joining and then leaving the server about every 10-15 minutes. Can you please help me fix this? I'd appreciate a response soon :)!
Btw i'm an iOS user.

**Comment by hihihoholalalolo1227** [comment]
Me too I am using Plug Pocketmine
