### ISSUE TITLE
How to upgrade server memory

### ISSUE THREAD

**Issue by MSG100TC** [PocketMine/PocketMine-MP#4328]
### Issues### Steps to reproduce the issue

1. It lags very often when I tried to walk around in my server.
2. How do I fix this problem? I tried editing the server.properties file but there isn't an option to edit it server memory (Ram)?

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* N/A

**Comment by dktapps** [comment]
If you didn't already figure it out in the 9 months since this issue was opened, you can find the options you're looking for in pocketmine.yml.
