### ISSUE TITLE
Pocketmine on multicraft

### ISSUE THREAD

**Issue by Mirzanas** [PocketMine/PocketMine-MP#4329]
When i try to run pocketmine on multicraft i'm getting an error "[Server] INFO /jar/pocketmine/bin/php7/bin/php: error while loading shared libraries: /jar/pocketmine/bin/php7/bin/../lib/libz.so.1: file too short" 

do you have any idea why?

### OS and versions

* PocketMine-MP:
* PHP: 7

**Comment by MalakasPlayzMC** [comment]
github.com/pmmp/PocketMine-MP
