### ISSUE TITLE
Incompatible API version

### ISSUE THREAD

**Issue by RubberBoa** [PocketMine/PocketMine-MP#4332]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

[Server thread/ERROR]: Could not load plugin 'DevTools': Incompatible API version
[Server thread/ERROR]: Could not load plugin 'EssentialsPE': Incompatible API version

**Comment by CrusherPlaysMC** [comment]
Look up pmmp... there is a new respository for pocketmine

**Comment by RubberBoa** [comment]
Thanks.

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP
