### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by miladesi** [PocketMine/PocketMine-MP#4333]
How to update pocketmine
To 1.0.4

**Comment by dino147** [comment]
Just download the latest phar version from here: [https://jenkins.pmmp.io/job/PocketMine-MP/](Click)
and rename it PocketMine-MP.phar and than just start the server :) That's it.

**Comment by miladesi** [comment]
I want wiht virtual server, crate minecraft server can you help me??

**Comment by dino147** [comment]
You must buy a VPS,try buying from OVH.

**Comment by miladesi** [comment]
. i cant update pocket mine help me .how to open port with vps.
