### ISSUE TITLE
php

### ISSUE THREAD

**Issue by McMasterGGov** [PocketMine/PocketMine-MP#4337]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:7.0
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by thelucyclub** [comment]
If you don't tell anyone what happend, then you might as well just close the dang issue!

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP
