### ISSUE TITLE
[ERROR][HELP_ME]bin\php\php.exe: Exit 127

### ISSUE THREAD

**Issue by GeekQuinsy** [PocketMine/PocketMine-MP#4338]
### Issue description
The server don't want to launching. He said : bin\php\php.exe: Exit 127.

### Steps to reproduce the issue
1. Launching the server
2. Said : bin\php\php.exe: Exit 127

### OS and versions
* PocketMine-MP:1.4.1
* PHP:Unknown
* OS:Windows 7 (French) Professional N x32 bits on a 64x processor

### Crashdump, backtrace or other files
bin\php\php.exe: Exit 127

**Comment by thelucyclub** [comment]
1. That is a PHP issue.
2. Just close all other instances of PHP running, make sure you're not running multiple PM servers.

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP
