### ISSUE TITLE
contOS7  php7

### ISSUE THREAD

**Issue by erxat124** [PocketMine/PocketMine-MP#4339]
system: centOS 7  64x      
How to do this
etmc@zhujiwu ~]$ ls
bin              LICENSE             PocketMine-MP.phar.sig  start.sh
CONTRIBUTING.md  PocketMine-MP.phar  README.md
[etmc@zhujiwu ~]$ ./start.sh
Couldn't find a working PHP 7 binary, please use the installer.
[etmc@zhujiwu ~]$

**Comment by Mooncoder** [comment]
Try reinstalling it and try again.

**Comment by OpnSrcConstruction** [comment]
I am having he same problem except on an Ubuntu 16.04 LTS based OS, and a 17.04 Ubuntu Gnome OS. The problem is the same... php7 is installed by default, but the website bash command && the master branch; don't install php7 or accept the php7 binary in the OS.

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP

**Comment by TheDiamondYT1** [comment]
Also this issue is a support request and should be asked on the new forums

**Comment by OpnSrcConstruction** [comment]
This project is a joke anyways. One shouldn't have to build php7 from source, to be able to run your server. I got a version to run from an outdated installer, but couldn't connect from it being too old. If this repo is outdated, and you don't want to make it private; then backup the code and delete it. The web-site is broken unless you use corporation controlled software(apple/M$). I file bug-reports and they constantly get shot down for stupid issues like above. I just want a simple installer script, for a version; that the current minecraftPE will connect to.

**Comment by TheDiamondYT1** [comment]
@OpnSrcConstruction Then download the pre-compiled binaries...

Standard PHP installations dont come with the requires extensions, so pocketmine provides them for you. **You are a joke**

**Comment by PainTR** [comment]
change php5 text to php7 in your start.sh file
PHP_BINARY="./bin/php5/bin/php"

PHP_BINARY="./bin/php7/bin/php"

**Comment by dktapps** [comment]
@thediamondyt just fucking quit already... if people are too stupid to see the notice on the readme, don't waste your time on them. You're just spamming people's notifications for no good reason.

**Comment by TheDiamondYT1** [comment]
@dktapps I forgot people were notified on this repo..:facepalm:

**Comment by TheDiamondYT1** [comment]
Lol k
