### ISSUE TITLE
Couldn't find  a php7 binary File

### ISSUE THREAD

**Issue by Corsett** [PocketMine/PocketMine-MP#4340]
### Issue description

I was trying to install a server so me and my brother could play on without one of us having to host it. I tried pocketmine and I got through almost everything but when I ran ./start.sh it said it couldn't find a working php7 binary file. Anything Helps! 👍 

### Steps to reproduce the issue

1. Change the bin/php7/bin/php to bin/php5/bin/php in the start.sh folder. ?
2. ...

### OS and versions

* PocketMine-MP: Pocketmine 1.4.1
* PHP:???
* OS: MacOS

### Crashdump, backtrace or other files

* ...

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP
