### ISSUE TITLE
My server

### ISSUE THREAD

**Issue by SyFy12** [PocketMine/PocketMine-MP#4343]
Dear Pocketmine, I have a server issues the spawn eggs end nether potions mobs and redstone don't work please update so I can have command blocks

### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by Mooncoder** [comment]
Is this a actual issue or suggestions?

**Comment by TheDiamondYT1** [comment]
**We've moved.**

A long time ago, actually. The official PocketMine-MP repo has moved and this repo will not be updated ever again.

https://github.com/pmmp/PocketMine-MP
