### ISSUE TITLE
Items not appearing in inventory!

### ISSUE THREAD

**Issue by BudderSticks** [PocketMine/PocketMine-MP#4346]
Whenever i do /give player item amount the item doesnt appear in my inventory. i either i have rejoin or restart the server. Sometimes i can tap a slot in my hot bar to get it. Same problem with kits, ive tried all kit plugins same glitch. My freind has a pm server with totally different plugins and he has the same porblem. This is especially frustrating since one of my main games is KitPvP

Thank you!
-MineTechMCPE.tk
-26055

**Comment by TheDiamondYT1** [comment]
This isn't a place for advertising, and this is the wrong repo to report issues.

**Comment by dktapps** [comment]
@TheDiamondYT1 WILL YOU STOP. You're spamming over 1000 people's notifications wasting your words on idiots who don't read.
