### ISSUE TITLE
MCPE 1.1.0 issues?

### ISSUE THREAD

**Issue by PaXo0** [PocketMine/PocketMine-MP#4347]
### Issue description
Write a short description about the issue
When ever i connect to my server it either times me out as i believe it is outdated but i am running windows 10 and the latest version is 1.4.1 what is outdated is their one for MCPE 1.1.0

### Steps to reproduce the issue
1. Update Files?

### OS and versions

* PocketMine-MP:PocketMine-MP_Installer_1.4.1_x86
* PHP:[INFO] This server is running PocketMine-MP version 1.4.1-980 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)
* OS: Windows 10

### Crashdump, backtrace or other files

* ...

**Comment by poustmal** [comment]
https://github.com/pmmp/pocketmine-mp

**Comment by kenygamer** [comment]
@paxoboy Hello, please make sure you are using the latest PocketMine version, available [here](https://github.com/pmmp/PocketMine-MP).
