### ISSUE TITLE
Unknown error while performing this command 

### ISSUE THREAD

**Issue by CyanCreeper** [PocketMine/PocketMine-MP#4349]
### Issue description While performing any commands I get this error,

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files
 04.07 15:32:30 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in phar:///plugins/Slapper_v1.3.0 (1).phar/src/slapper/Main.php on line 619" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 704
* ...

**Comment by Johnmacrocraft** [comment]
@CyanCreeper *THAT'S SLAPPER PLUGIN ISSUE, NOT POCKETMINE-MP ISSUE.*
