### ISSUE TITLE
Server Help

### ISSUE THREAD

**Issue by SyFy12** [PocketMine/PocketMine-MP#4352]
Dear Pocketmine, your software for MCPE 1.1 is out of date so mobs, end, nether, Command blocks and redstone components are dysfunctional can you please update your Pocketmine software  so all those things become functional

### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by mc-i** [comment]
https://github.com/pmmp/PocketMine-MP
