### ISSUE TITLE
Pocketmine Server Help

### ISSUE THREAD

**Issue by SyFy12** [PocketMine/PocketMine-MP#4355]
### Issue description

Dear Pocketmine, can you please update the server software so my server's mobs, command blocks, redstone, end, and nether function Please FIX!!!!!

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by VCraftMCPE** [comment]
https://github.com/pmmp/PocketMine-MP
