### ISSUE TITLE
error starting 

### ISSUE THREAD

**Issue by NexGenHD** [PocketMine/PocketMine-MP#4357]
### Issue description

Problem starting the server with start.sh

### Steps to reproduce the issue
I have the php version:
[![Screenshot from Gyazo](https://gyazo.com/1d183a2c46b2dcc92f20566d96b06715/raw)](https://gyazo.com/1d183a2c46b2dcc92f20566d96b06715)
on start script get the error:
[![Screenshot from Gyazo](https://gyazo.com/789896f98188d4525132e2fe7256b2ba/raw)](https://gyazo.com/789896f98188d4525132e2fe7256b2ba)
I installed it inside the folder my_pocketmine_folder/bin the last
php tar found in: https://dl.bintray.com/pocketmine/PocketMine/ (version PHP_7.0.6, no 7.0.8 Which is the one I have).
 And now I have the error:
[![Screenshot from Gyazo](https://gyazo.com/e1879d93a21e241ed9de719667c38609/raw)](https://gyazo.com/e1879d93a21e241ed9de719667c38609)
I'm using the latest version of pocketmine.
any solution?

### OS and versions

* PocketMine-MP: 1.4.1 last version, downloaded today
* PHP: 7.0.8
* OS: Ubuntu server 16.10 x86_64

### Crashdump, backtrace or other files

* ...

**Comment by robske110** [comment]
You have successfully downloaded the correct php version, but you are using a PM version for php5 and one that is, really out of date. Simply replace PocketMine-MP.phar with https://jenkins.pmmp.io/job/PocketMine-MP/319/artifact/PocketMine-MP_1.6.2dev-319_3e141afe_API-3.0.0-ALPHA7.phar and also keep in mind that this repo is dead. It has been "moved" to https://github.com/pmmp/PocketMine-MP

**Comment by NexGenHD** [comment]
Thanks !, I worked correctly :)

**Comment by NexGenHD** [comment]
One question, I am now installing plugins, but all that I low down this happens to me:
[![Screenshot from Gyazo](https://gyazo.com/e4d71762e0eb74b474646a2e4a6bc995/raw)](https://gyazo.com/e4d71762e0eb74b474646a2e4a6bc995)
All the plugins that I see in: http://forums.pocketmine.net/plugins/
Are outdated or have not been updated for a long time. Any other page where to download the plugins?

Thanks for the help.

**Comment by MalakasPlayzMC** [comment]
Yes! poggit.pmmp.io and imgcl.co
