### ISSUE TITLE
Player only look straight

### ISSUE THREAD

**Issue by RaulMorales2** [PocketMine/PocketMine-MP#4359]
### Issue description

When I have my family to go to my server my family character are looking straight only and that see me looking straight too.

The version  that I use is 1.1.0

**Comment by RaulMorales2** [comment]
Well our characters are looking only in one directions. We could move but the characters look weird because they look at a direction

**Comment by dktapps** [comment]
This bug has long since been fixed in PMMP's PocketMine-MP. You can get an up to date version from https://github.com/pmmp/PocketMine-MP/releases .
