### ISSUE TITLE
PocketMine-MP Errors

### ISSUE THREAD

**Issue by Keaton1188** [PocketMine/PocketMine-MP#4362]
Hi all, having a issue with one of my plugins, as its not been updated to ALPHA-7 I did it myself and used DevTools, it loads the source code in console etc then it crashes the server.

![untitled](https://user-images.githubusercontent.com/24898745/29995420-e5b076f8-8fe0-11e7-84bb-98b1ab63c6ca.png)

running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA7)
PE version v1.1.0.55

**Comment by JacquelineJohnson39** [comment]
How do I fix thos
