### ISSUE TITLE
no spawning occurs. no moving creatures of any kind to be found.

### ISSUE THREAD

**Issue by aboese** [PocketMine/PocketMine-MP#4366]
Any world I generate seems to have no animals, npcs, or monsters. Fair warning, I am a noob, but I´ve scoured the message boards for hours. 

1. install minecraft pe on Ubuntu (wget -q -O - https://get.pmmp.io | bash -s - -u)
2. Install updated phar & latest available php from frog site
3. ./start.sh
4. End game after no animals found.
5. Remove world directory
6. Check server.properties and pocketmine.yml again. Make tweaks. I´m using survival mode, difficulty 2.
7. Go to step 3.

### OS and versions

* PocketMine-MP:  1.7dev-40
* PHP:  PHP 7.2.0RC2 (cli) (built: Sep 14 2017 18:50:22) ( ZTS )
* OS: Ubuntu 16.04.2 LTS

**Comment by g4m3r0** [comment]
It's because they are still not implemented.
There is a plugin that spawns mobs but it doesn't work well.

https://poggit.pmmp.io/p/PureEntitiesX/empty-version
