### ISSUE TITLE
Unable to Find pthreads Extension

### ISSUE THREAD

**Issue by N1Chris** [PocketMine/PocketMine-MP#4369]
### Issue description
[CRITICAL] Unable to find the pthreads extension.
[CRITICAL] Please use the installer provided on the homepage.
bin\php\php.exe: Exit 1

This says it all. I can run older versions of MCPE on older versions of PHP7 (7.0.4) without any issue, but once MCPE went to PHP 7.2.0 (which isn't even really out yet until later on this month), I have not been able to get it to work.

Simply copying the downloaded PHP files from the website into the bin/php folder causes it to spew out these many "unable to load dynamic library" errors while doing a fresh install of PHP 7.2.0 causes it to spew out the above error. I have also downloaded and installed pthreads correctly according the accompanying readme.md for pthreads.

Can someone please help me?

### Steps to reproduce the issue
1. Install below PHP version
2. Install pthreads from the official pthreads website
3. Try to run PocketMine-MP with the below version

### OS and versions

* PocketMine-MP: PocketMine-MP_1.7dev-351_6db5596b_API-3.0.0-ALPHA9
* PHP: php-7.2.0RC5-Win32-VC15-x64
* OS: Microsoft Windows 7 Professional x64

P.S. I seem to be the only one running Windows while running Pocketmine-MP (don't get the fetish with Linux), so I believe my problem is unique to Windows.

Attached Screenshots:

![1](https://user-images.githubusercontent.com/29324957/32285845-f9a2ced6-bf01-11e7-8680-47c4ca41dbf3.jpg)
![2](https://user-images.githubusercontent.com/29324957/32285846-f9b702e8-bf01-11e7-8a11-a408d10a89d9.jpg)

**Comment by Gumbraise** [comment]
Hello ! I have the same error 

![image](https://user-images.githubusercontent.com/34947108/34456426-21725982-ed96-11e7-97ff-8b4190512751.png)


I have tested several php_pthreads.dll and pthreadsVC2.dll 

![image](https://user-images.githubusercontent.com/34947108/34456447-be8a3fe6-ed96-11e7-9b0f-c071fe3fabd3.png)

It works with MinecraftPE Server PocketMine-MP v.<1 (0.15.0, 0.14.0, etc...) and php between 5 and 7. But I would like install MinecraftPE Server PocketMine-MP v.1.0.9
![image](http://www.mediafire.com/convkey/5e2a/88vdo3ltc6vf8r2zg.jpg) 

If somebody has the solution, we are interested :D 
Bye !

**Comment by dktapps** [comment]
You're using the wrong version. You can get an up to date version from https://github.com/pmmp/PocketMine-MP/releases .

We supply custom-built PHP binaries for Windows containing all of the extensions you need. You can download them from https://ci.appveyor.com/project/pmmp/php-build-scripts/build/artifacts
