### ISSUE TITLE
Can't break blocks or Place blocks without being OP!

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [PocketMine/PocketMine-MP#4370]
### Issue description

Write a short description about the issue
1st problem I ran into was when my friend couldn't break blocks. A quick Google and op-ing him fixed it, but that's really a temporary solution.

2nd problem was when another friend logged in and could break most blocks, but there were a couple that she couldn't. Also, she couldn't open doors. Op-ing her fixed the problem, but once again this isn't the ideal solution.

It seems like a permissions issue, but I can't figure out where to edit them. When I start my Spigot server, I do get a message about permissions.yml being empty, but I'm not sure if that's the place to look. I searched online for templates, but people just said to get PermissionsEX, which I dabbled with later, but couldn't figure out.

This isn't going to be a big server, it might host 5 people tops, but I don't want to op everyone. I want the default permissions to mirror a "vanilla" Minecraft survival experience, and of course give op'd players the "keys to the kingdom".

Anyway, if someone can point me in the right direction I'd be very grateful.

Thanks!
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* OS:

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Check your spawn protection setting in server.properties.
