### ISSUE TITLE
Protocol update forced by App updates

### ISSUE THREAD

**Issue by feikede** [PocketMine/PocketMine-MP#4371]
### Issue description

Since like three days, the Android and iOS MCPE apps are updating. When I try to connect with app version 1.2.5.x to the PMMP Server I get

` [16:36:00] [Server thread/INFO]: [/192.168.2.69:62651] logged out due to Incompatible protocol version (141)
`

### Steps to reproduce the issue

1. Install the most recent MC-PE app from the apple or google store
2. Connect to an PMMP Server (1.7dev-318)

### OS and versions

* PocketMine-MP: 1.7dev-318
* PHP: PHP 7.2.0RC6 (cli) 
* OS: aarch64 linux.suse 4.4.92-18.36-default on Raspberry 3

### Crashdump, backtrace or other files

* 
` [16:36:00] [Server thread/INFO]: [/192.168.2.69:62651] logged out due to Incompatible protocol version (141)
`

Regards
Rainer Feike

**Comment by robske110** [comment]
You simply got a PocketMine version which doesn't support 1.2.5. Just replace your current phar with
https://jenkins.pmmp.io/job/PocketMine-MP/452/artifact/PocketMine-MP_1.7dev-452_f477cfa1_API-3.0.0-ALPHA9.phar and new clients will be able to connect again.
Also, wrong repo. Head over to https://github.com/pmmp/PocketMine-MP
