### ISSUE TITLE
Command @p @e etc - Will it ever work?

### ISSUE THREAD

**Issue by evilosis** [PocketMine/PocketMine-MP#4373]
Issue description

I understand Commands are not always working correctly. Will the option to add @p @e etc be available?
Sorry its not really a bug. 

OS and versions

PocketMine-MP_1.7dev-452_f477cfa1_API-3.0.0-ALPHA9.phar
Minecraft Windows 10 edition and PE v1.2.5
PHP: 7.2_RC3

OS: Windows server 2008 - Hyper V VM running Ubuntu 16.04.3 LTS

**Comment by Awzaw** [comment]
This is the old PocketMine github... check out https://poggit.pmmp.io/p/PlayerSelectors
