### ISSUE TITLE
macOS instal issus

### ISSUE THREAD

**Issue by focusnum** [PocketMine/PocketMine-MP#4375]
Hello
i have this message after installation

Mini-de-Renaud:documents renaud$ curl -sL http://get.pocketmine.net/ | bash
[*] Found PocketMine-MP Final_1.4.1 (build 980) using API 1.11.0
[*] This stable build was released on Mar 17 mar 2015 18:00:47 CET
[*] Installing/updating PocketMine-MP on directory ./
[1/3] Cleaning...
[2/3] Downloading PocketMine-MP Final_1.4.1 phar... done!
[3/3] Obtaining PHP: detecting if build is available...
[3/3] MacOS 64-bit PHP build available, downloading PHP_5.6.10_x86-64_MacOS.tar.gz... checking... regenerating php.ini... done
[*] Everything done! Run ./start.sh to start PocketMine-MP
Mini-de-Renaud:documents renaud$ ./start.sh
Couldn't find a working PHP 7 binary, please use the installer.

i'm using macOS 10.13.11

Thank you

**Comment by dktapps** [comment]
You're using the wrong version. You can get an up to date version from https://github.com/pmmp/PocketMine-MP/releases .

Additionally, an updated installer is available from https://get.pmmp.io :
```
curl -sL http://get.pmmp.io/ | bash -s -
```
