### ISSUE TITLE
PHP 7.2 on Raspbian (Raspberry PI 3)

### ISSUE THREAD

**Issue by juliocoliveira** [PocketMine/PocketMine-MP#4378]
### Issue description
PHP fatar errors:
```
PHP Fatal error:  Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///srv/minecraft/pocket/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///srv/minecraft/pocket/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80
```

### Steps to reproduce the issue
1. Install PHP 7.2 TS from source.
2. Run start.sh

### OS and versions
* PocketMine-MP: Tested stable and development
* PHP: 7.2
* OS: Raspbian (Debian Strech Based): Linux server 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linux

### Crashdump, backtrace or other files
PHP Fatal error:  Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///srv/minecraft/pocket/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///srv/minecraft/pocket/PocketMine-MP.phar/src/pocketmine/Server__32bit.php on line 80

**Comment by dktapps** [comment]
You're using the wrong version. You can get an up to date version from https://github.com/pmmp/PocketMine-MP/releases .
