### ISSUE TITLE
Setting up a 24/7 server?

### ISSUE THREAD

**Issue by lunarcontrol** [PocketMine/PocketMine-MP#544]
I am trying to create a 24/7 server. I learned in this issue: https://github.com/PocketMine/PocketMine-MP/issues/433 that, i need a vps. I would like a total of like 35 or so slots, Is the $10 package going to work for what i am doing?

The website i would like to order the vps from is here: https://www.digitalocean.com/pricing

Also, when i go to install this am i going to follow these instructions: https://github.com/PocketMine/PocketMine-MP/wiki/Setting-up-a-Server#-linux---raspberry-pi since i am chosing Ubuntu 12.04 x32, correct?

One last thing: When i go to create a "droplet" as they call it, what is the host name?[picture attached]
![screen shot 2013-07-13 at 2 40 30 pm](https://f.cloud.github.com/assets/5004460/793425/24377338-ec05-11e2-9bb7-6a8839d2620a.png)

If you have any advice PLEASE comment below! It will be GREATLY appreciated!!!

**Comment by dc4code** [comment]
If you like you can use the Raspberry PI and use these install instructions:
mkdir mcpe
cd mcpe
wget http://dc4code.pe.hu/pj/pmi/pai.sh
sudo chmod a+x pai.sh
./pai.sh
The installation will now begin.

**Comment by sekjun9878** [comment]
Link has been deleted. The only distribution supported or linked here should be the official PocketMine distib. @dc4code.

**Comment by legoboy0215** [comment]
Use GNU screen. Search for it.
