### ISSUE TITLE
installer

### ISSUE THREAD

**Issue by Bluigi** [PocketMine/PocketMine-MP#570]
sorry for being a noob but what is uknown packet id 0x01 and how to get installer version 1.3.3 on windows xp

**Comment by fantasticbaby44** [comment]
Can someone tell me in detail how to do this part please?

" There is no updated installer for Windows XP. Use the old one and manually update the 'src' folder. 
Download the 'Source Code' from https://github.com/PocketMine/PocketMine-MP/releases, extract it, remove the old 'src' folder and copy the 'src' folder you extracted to the old location."
