### ISSUE TITLE
How to import already made Minecraft singleplayer maps into server?

### ISSUE THREAD

**Issue by demolisher23** [PocketMine/PocketMine-MP#632]
I've tried all the fixes I could find, first I tried importing the players folder, chunks.dat, entities.dat, level.dat, and level.dat_old into a folder into the worlds folder in the pocketmine-MP Directory and here's my error:
15:09:19 [INFO] PocketMine-MP Alpha_1.3.3 API #9, LGPL License
15:09:19 [INFO] Loading properties...
15:09:19 [INFO] Starting 0.7.3 alpha #11 Minecraft PE Server at 10.0.0.0:19132
15:09:19 [INFO] Importing Pocket level "Server" to PMF format
15:09:21 [NOTICE] Importing level 7%
15:09:21 [NOTICE] Importing level 13%
15:09:22 [NOTICE] Importing level 19%
15:09:22 [NOTICE] Importing level 25%
15:09:22 [NOTICE] Importing level 32%
15:09:23 [NOTICE] Importing level 38%
15:09:23 [NOTICE] Importing level 44%
15:09:23 [NOTICE] Importing level 50%
15:09:23 [NOTICE] Importing level 57%
15:09:24 [NOTICE] Importing level 63%
15:09:24 [NOTICE] Importing level 69%
15:09:24 [NOTICE] Importing level 75%
15:09:25 [NOTICE] Importing level 82%
15:09:25 [NOTICE] Importing level 88%
15:09:25 [NOTICE] Importing level 94%
15:09:26 [NOTICE] Importing level 100%
15:09:26 [INFO] Preparing level "Server"
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [ERROR] A level 8 error happened: "Undefined index: Health" in "E:\Applications\P
ocketMine-MP\src\API\LevelAPI.php" at line 188
15:09:26 [INFO] Loading plugin "SimpleWorlds" 0.1 by shoghicp
15:09:26 [INFO] Starting GS4 status listener
15:09:26 [INFO] Setting query port to 19132
15:09:26 [INFO] Query running on 0.0.0.0:19132
15:09:26 [INFO] Starting internal ticker calculation
15:09:28 [INFO] Default game type: SURVIVAL
15:09:28 [INFO] Starting plugins...
15:09:28 [SimpleWorlds] Loading levels...
15:09:28 [INFO] Done (8.781s)! For help, type "help" or "?"

Then I tried putting the chunks entities and level.dats into the worlds folder and got a get spawn error.

**Comment by jhperales** [comment]
so, how does one even import? thats what im confused about
