### ISSUE TITLE
Players still appear to "Lag"

### ISSUE THREAD

**Issue by Huntereb** [PocketMine/PocketMine-MP#779]
My issue is simple, players still appear to lag. Not the "Jump around" type of lag (bad connection lag), just a "Freeze, continue walking, freeze, continue walking" kind. This effects all players, so if one person is frozen, the other person is frozen as well. I'm running the latest Dev build and I am only reporting this now because I just brought my player count down from 25 to 20, and it now looks like it has gotten worse (I was on an older build before I updated the player count). It's obviously a server issue, as it happens to all players at the same time every half a second. 

I don't think it's my hardware's fault, as it is always happening no matter how many players are on. I was on earlier with 4 people and it still happened, and then it went up to a full server with 20 people and it was still doing the exact same thing. Players also have been complaining about lag after updating to the most recent build and me lowering the player count. The computer running the server is a Quad-core 3.6 GHz i7 with 1 GB of RAM dedicated to the server (Even though the server only uses about 33 MB's). The task is set to high priority with administrator privileges, and uses about 10% of my CPU when it is full (25 players). I am also connecting to the server over the same network it is running on, but I have been testing it over a 25 mile distance from a different connection and I still see the same issue.

I also do not think it is an issue regarding bandwidth, as I have ran 2 TF2 servers with 35 people combined on them at once with no issues lag-wise.

Is there something I still need to do to fix this? It's very annoying to me, even though players never complain about it for some reason. (I guess they're used to it?)

Also, any estimate on a date for the 1.4 release?

Thanks!

**Comment by RandomAltThingy** [comment]
Sorry to comment on an old issue but this still exists, even when running php7. @shoghicp @intyre
