### ISSUE TITLE
tools, blocks and items "uncrafting"

### ISSUE THREAD

**Issue by unerds** [PocketMine/PocketMine-MP#804]
i've had this happen to me quite a few times, and just received reports from another player of the same thing.

so far for me, it's wooden slabs... it doesn't happen every time...

when i place a wooden slab, it disappears immediately

my hotbar clears out 

when i check my inventory, they've reverted back to wooden planks

stone slabs have done this as well.

i'm not sure what other items are effected by this, but others have reported the same issue.

**Comment by keithbzjr** [comment]
My tools keep uncrafting and the materials go back into the chests. Is this MCPE or pocketmine? Is it my tablet or internet? I know it is not fixed because it is happenning, and it is gamebreaking. I have a pocketserver and a hostingitall server and it happens both places.

**Comment by DjJakkiGlass** [comment]
I'm trying to craft rails to make a rollercoaster and it won't let me :( I can craft Minecraft just fine, but no rails...why?????

**Comment by sithsiri** [comment]
@DjJakkiGlass Just like @PEMapModder said,
"Slabs not crafting is be because of packet loss: the packets crafting things are lost in the UDP connection.
Rails and minecarts don't craft because it is refused."

**Comment by DjJakkiGlass** [comment]
Awww that's a shame =(

On August 8, 2015, at 2:36 PM, sithsiri <notifications@github.com> wrote:

@DjJakkiGlass Just like @PEMapModder said,
"Slabs not crafting is be because of packet loss: the packets crafting things are lost in the UDP connection.
Rails and minecarts don't craft because it is refused."
